### ISSUE TITLE
Scenarios for executive course

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1000]
We need at least 3 urban design scenarios for the executive course. 

Requirements:
- They should look like the output of an urban design competition.
- They should be different in terms of density and occupancy mainly (for starting).
- They should be ready as soon as possible :-) so we can use them to run CEA and test it during the next 2 months.
- They should be delivered in either cad format (where each building footprint is a closed polyline and, each building should be stored in a different layer. the layer name will give a name to the building.
- OR they can be delivered in shapefile format geolocated in Tanjong Pagar Area.

Methods:
- We thought on making a first example with the block generator to get idea about the differences in densities and occupancy.
- later we would decide on which occupancy and density values we could use to make the 3 urban design scenarios by hand.

**Comment by JIMENOFONSECA** [comment]
@amraladdin we made a first stab to the scenarios with Zhongming. Please find them in the reference case repository in the pull request #25. do let us know as soon as possible how they look like and if they work in your machine.

**Comment by amraladdin** [comment]
Checked!
