### ISSUE TITLE
Difference between  "is"  and  "=="

### ISSUE THREAD

**Issue by roglen** [architecture-building-systems/CityEnergyAnalyst#1003]
When debugging i997 as to why thermal_network_matrix does not run in DH mode we came across the following problem: 

       print (network_type is 'DH')     #returns false
       print (if network_type == 'DH')          #returns true

So when replacing "is" with "==" in the code, it runs fine.

Can someone explain why "is" does not work here?

**Comment by JIMENOFONSECA** [comment]
This is a good answer to that!
https://stackoverflow.com/questions/2209755/python-operation-vs-is-not

In general use always “==“

On 30 Jan 2018, 15:05 +0800, Lennart Rogenhofer <notifications@github.com>, wrote:

When debugging i994 as to why thermal_network_matrix does not run in DH mode we came across the following problem:

   print (network_type is 'DH')     #returns false
   print (if network_type == 'DH')          #returns true


So when replacing "is" with "==" in the code, it runs fine.

Can someone explain why "is" does not work here?
