### ISSUE TITLE
Fix installation guide for Ubuntu

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1005]
The prerequisites are not necessary as the guide doesn't use them. While we're at it: Go over the guide and fix up any other issues.

**Comment by daren-thomas** [comment]
I think this could be as simple as updating the `environment.ubuntu.yml` file. Also, this should work similarly for euler.ethz.ch (first tests installing conda were promising, but I need to check for PREFIX as there is a limit to the amount of files I may have in my home directory)

**Comment by daren-thomas** [comment]
status update: the branch `1005-fix-installation-guide-for-ubuntu` is in progress. installation of cea is working and being tested in the new `docker/Dockerfile` which creates a docker image with a fully installed cea. Stuff that still needs to be done:

- copy the `docker/environment.yml` to `environment.ubuntu.yml` (or actually export that environment once built?)
- add installation steps for Daysim (could be a script to run)
- add installation of Daysim to `docker/Dockerfile` (could be just running the script mentioned above)

**Comment by daren-thomas** [comment]
@roglen do you have some input to compiling Daysim / Radiance on ubuntu? I've seen some instructions and have been able to compile a bit, but I'd like to chat with you if you have experience running the CEA on Linux.

**Comment by roglen** [comment]
@daren-thomas sadly I don't think I can be of much help here. I tried to run it in the beginning, and being a complete Ubuntu newbie I couldn't figure it out. During my time using Ubuntu I always took the Radiance files from @shanshanhsieh or @BhargavaKrishnaSreepathi and just copied them in.

**Comment by daren-thomas** [comment]
@roglen ok, thank you! i have been able to figure out most stuff, so i think we got this.

**Comment by daren-thomas** [comment]
status update: The file `docker/Dockerfile` contains a machine-readable guide to installing CEA in a Linux environment, including building Daysim and has been tested to run the following scripts:

- `cea test`
- `cea radiation-daysim`

The documentation for installing on a clean ubuntu will need to be updated. I expect this to change anyway with the M2.12 (installer) efforts. It also depends on what steps are necessary (the docker image used is bare-bones, an standard ubuntu system might already have git & co. installed)

**Comment by daren-thomas** [comment]
status update: our changes to the py4design fork have been merged to the original by kianwe and we can now continue with the development of the installation guide and the Dockerfile.
