### ISSUE TITLE
dodo test for thermal network

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1010]
we have to add the thermal network to the dodo test.
the test should check if the `thermal_network_matrix.py` is running for reference-case-open.
@daren-thomas  could you please give me a hand on that? : )

**Comment by daren-thomas** [comment]
sure! what are the steps to take to ensure it runs? how long will computation take?

**Comment by shanshanhsieh** [comment]
Thanks, @daren-thomas !

Here are the steps:
After obtaining the demand results for reference-case-open, we have to run `thermal_network_matrix.py` for `DH` and `DC` (change 'network-type' in 'cea.config')

It takes 25 mins to run reference-case-open with 'DH', and a bit less for 'DC'
However, it is more important to make sure 'DH' runs.
If we want to save time, it is good enough to run the script only for 'DH'

**Comment by daren-thomas** [comment]
@shanshanhsieh this will increase the time `cea test` takes - both locally (when reviewing pull requests) and on the jenkins server (run for each update to each pull request) and might decrease the value of the dodo test... so i'm wondering... i think we definitively should implement that on the "merge-to-master" part of the jenkins!

BUT: can you think of a way to test the important parts without running the whole script? can it be split up into functions / code-paths that can be tested once?

**Comment by shanshanhsieh** [comment]
yea, i was thinking about the same thing... 
It is quite important to make sure the outputs from parts of the script doesn't break other parts, therefore, i would like to run it from the begining to the end.
Instead of running the script for the whole year, we could do it for 2000 timesteps, which will only take 5 minutes. 

To do this, we have to change two lines of code before running dodo. 
And the question is where to implement the changes?
1. As this modification is only required for the dodo test, modify it everytime via the `dodo.py` script.
2. Implement a `timestep` variable in `cea.config`

**Comment by daren-thomas** [comment]
OR: split the code for a single timestep into a separate function. so you end up with this structure:

```
def main(config):
    pre_simulation(config)
    for t in xrange(HOURS_OF_YEAR):
        simulate_timestep(t, config)
    post_simulation(config)
```

Then, in dodo, you can just run the `pre_simulation`, then 2000 times the `simulation_timestep` and then the `post_simulation`.

Of course maybe you'd end up with some variables to communicate between these steps - those are added parameters.

**Comment by daren-thomas** [comment]
This is somehow related to #1090 - multiprocessing for the thermal network matrix. And the solution above is very ideal - in reality, of course, the code is messier and this can't be done as easily.

**Comment by daren-thomas** [comment]
@shanshan - in the process of doing #1090, i have implemented this. see the pull request #1140
