### ISSUE TITLE
inconsistent saving of checkpoints in optimizaition

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1012]
this blocks #985 >

I replicated the error with the open source case study running th eoptimization for 5 generations and 5 inidividuals.

In the third generation the checkpoint is not saving the same number of information about disconnected buildings, in relation to the existing population.

Basically disconnected_buildings is saving information for 4 individuals but the population is 5.

![image](https://user-images.githubusercontent.com/8973186/35611022-9def0cbe-069e-11e8-982b-161c81b36bf9.png)

![image](https://user-images.githubusercontent.com/8973186/35611070-bfd2ed1e-069e-11e8-81c6-5fcffa928fda.png)

This causes an error while reading the optimization district_dashboard.

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi the network list is also different

![image](https://user-images.githubusercontent.com/8973186/35659594-0c89c4c2-0742-11e8-831a-1934fbd90d15.png)

**Comment by BhargavaKrishnaSreepathi** [comment]
working on it

**Comment by BhargavaKrishnaSreepathi** [comment]
fixed in PR 1016
