### ISSUE TITLE
As a practitioner, I'd like to have verified models of energy supply technogogies

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1017]
CEA needs more technology models of cooling supply systems and storage systems in SG context.

**Comment by shanshanhsieh** [comment]
current value for WTP_MIX_h:
substation pumping : 10% of total cooling demand 
pipe pumping: 1.4% of total cooling demand
thermal loss: 0.06% of total cooling demand

**Comment by JIMENOFONSECA** [comment]
this won't happen any time soon (6 - 12 months time), so we close it
