### ISSUE TITLE
Simple indoor humidity model

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1018]
To calculate humidity at every time step according to the airflows and internal gains (without storage of humidity).
Assume no other sources of humidity.
With this issue, we could calculate latent load for all cooling systems.
Also, update latent loads from mini split unit & central AC.

**Comment by gabriel-happle** [comment]
Following the procedure of new `ISO 52016-1:2007`

`6.5.14 Moisture content and latent heat load`
