### ISSUE TITLE
Update latent loads from current cooling systems in CEA

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1020]
-mini split unit 
-central AC.
this should be implemented when #1018 is closed.

notes form SH&GH's discussion:
An easy model will be assuming outdoor RH + internal gains, then cal. latent load to X% RH 
	   drawback: not considering moisture build-up

**Comment by gabriel-happle** [comment]
https://drive.google.com/file/d/1ocdWLj-Br6Jz7Za-HhP6X-vXvJvQRHm5/view?usp=sharing
