### ISSUE TITLE
Implement variable supply temperatures for cooling systems in CEA

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1021]
This requires connection to OSMOSE.
The supply temperature of each airflow results from optimization in OSMOSE.
And then decide how to iterate within CEA.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh are you planning to do this in the next year, if not please close. I am adding this to known issues

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
