### ISSUE TITLE
Check the new ISO standard

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1023]
Read the new ISO standard and estimate:
- if the new RC model could be implemented in this milestone
- what kind of humidity model is added?

**Comment by gabriel-happle** [comment]
Findings:
- New ISO (52016-1 and 52017-1) calculate detailed energy balances of every building element (each wall, window, floor, etc.) so they are not aggregated to few lumped parameters of the R-C-model (ISO 13789) any more.
- This is therefore a major change towards a much more geometric model.
- This is too complicated to be integrated in the current milestone.

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA you might want to check out ISO 52016-2. It contains a comparison of the new calculations with the RC-model and also some verification with the BESTEST.
