### ISSUE TITLE
CEA Component in Grasshopper: adding the column "Name" to the excel-to-shapefile function

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CityEnergyAnalyst#1032]
The shapefiles generated by the CEA Component only have "floors_ag", "floors_bg", "height_ag" and "height_bg". They are lacking the "Name" columns. Please add the column "Name" to the excel-to-shapefile function.

**Comment by daren-thomas** [comment]
@shizhongming check out commit 4a99b6e2345801633b6944e223e282bfcb3c00e0 for a solution to this.

**Comment by daren-thomas** [comment]
(that's as easy as just synchronizing the ubg branch)

**Comment by shizhongming** [comment]
@daren-thomas works perfectly now! thanks~
