### ISSUE TITLE
CEA Component in Grasshopper: read and apply the spatial reference information from terrain to shapefile.

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CityEnergyAnalyst#1033]
The spatial reference of the shapefiles is not correct. The best way to do we believe is that the CEA Component reads the spatial reference of the terrain.tif provided and apply that spatial references to the zone.shp, district.shp and streets.shp
For the terrian we are using, please refer to the terrain file in the urban design folder

**Comment by daren-thomas** [comment]
Did you know that there is a property in the config file that refers to the spacial reference?

```
"{\"lon_0\": 7.439583333333333, \"k_0\": 1, \"ellps\": \"bessel\", \"y_0\": 200000, \"no_defs\": true, \"proj\": \"somerc\", \"x_0\": 600000, \"units\": \"m\", \"lat_0\": 46.95240555555556}"
```

Huh. This is a mess! BUT: theoretically this is where the spacial reference information in the generated shapefiles are coming from. This is passed as the crs property to geopandas: `gpd.GeoDataFrame(df, crs=crs, geometry=geometry)`

**Comment by daren-thomas** [comment]
OK. So the `crs` parameter is not actually that much of a mess: 

```
[shapefile-tools]
excel-file = {general:scenario}/inputs/building-geometry/zone.xls
shapefile = {general:scenario}/inputs/building-geometry/zone.shp
crs = {"lon_0": 7.439583333333333, "k_0": 1, "ellps": "bessel", "y_0": 200000, "no_defs": true, "proj": "somerc", "x_0": 600000, "units": "m", "lat_0": 46.95240555555556}
index = Name
```
The above is an excerpt from the config file. This is the default value and is set to the crs of the reference-case-open. You can pass your own value for your case study by adding a `crs` input line to the CEA component in grasshopper. The format to use is a JSON dictionary with the values.

I can't read the values from the terrain file, because I don't have a terrain file. Where is the terrain file?

**Comment by shizhongming** [comment]
I created a branch i1033, the terrain file is in the branch (or I shouldnt have created a branch for each...). I also sent a copy of the terrain file via slack..as they dont support the file type here. thanks

**Comment by daren-thomas** [comment]
@shizhongming: check out the pullrequest #1064 that converts `streets.xlsx` into `streets.shp`. Note, you will need to set the option `polygon=False` for polyline shapefiles when running `cea excel-to-shapefile`

**Comment by daren-thomas** [comment]
check the branch `fixing-excel-shapefile` with @JIMENOFONSECA: can we create a pull request? how to test?
