### ISSUE TITLE
CEA Component in Grasshopper: excel-to-shapefile needs to generate polyline shapefile as well

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CityEnergyAnalyst#1035]
The CEA Component now can convert excel to polygon shapefiles. However, to run the optimization of the energy systems, we need a polyline shapefile as well. The CEA Component needs to be able to convert excel to polyline shapefiles. Please add this function if possible.
In the attachment is the excel(ployline) I made. Please let me know if it needs to be changed. This shape file just needs the correct spatial reference system (same as terrain) and geometry information (no Name..).
![9](https://user-images.githubusercontent.com/16640327/35791896-1d091104-0a85-11e8-9725-3df108b5130f.PNG)

**Comment by daren-thomas** [comment]
It seems this can be done with shapefile `LineString` objects. I'll look into it tomorrow. Can you please provide me with an Excel file to test on?

**Comment by shizhongming** [comment]
[streets.xlsx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/1701638/streets.xlsx)
This is an example of excel file. Please let me know if it works.

**Comment by shizhongming** [comment]
@daren-thomas

**Comment by shizhongming** [comment]
Solution1: store the spatial reference system of the terrain file in the config file in the correct format, so that the shapefiles generated will have the correct terrain. 

Solution2: Jimeno said that the not all the spatial reference system will work with the CEA. He proposed to have a standard spatial reference system and unify those of the terrain file and the shapefile to this spatial reference system. This solution has been tried in branch "fixing-excel-shapefile".

**Comment by daren-thomas** [comment]
Given a shapefile with the correct geospacial reference system, the `crs` parameter for the config file can be created like this:

```
In [1]: import geopandas as gpd

In [2]: district_shp = r"C:\Users\darthoma\Documents\GitHub\cea-reference-case\reference-case-ecocampus\baseline\inp
   ...: uts\building-geometry\district.shp"

In [3]: district_df = gpd.GeoDataFrame.from_file(district_shp)

In [4]: district_df.crs
Out[4]:
{u'ellps': u'WGS84',
 u'k': 1,
 u'lat_0': 1.366666666666667,
 u'lon_0': 103.8333333333333,
 u'no_defs': True,
 u'proj': u'tmerc',
 u'units': u'm',
 u'x_0': 28001.642,
 u'y_0': 38744.572}

In [5]: import json

In [6]: print json.dumps(district_df.crs)
{"lon_0": 103.8333333333333, "k": 1, "ellps": "WGS84", "y_0": 38744.572, "no_defs": true, "proj": "tmerc", "x_0": 28001.642, "units": "m", "lat_0": 1.366666666666667}
```
This can be used as a workaround until we have merged @JIMENOFONSECA 's `fixing-excel-shapefile` branch.
