### ISSUE TITLE
RTD not showing documentation for `demand_main`

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1046]
See this link: http://city-energy-analyst.readthedocs.io/en/latest/modules/cea.demand.html#module-cea.demand.demand_main

Expected documentation as after local sphinx build, but found none.

**Comment by daren-thomas** [comment]
@Jack-Hawthorne - assigning this to you. I created this issue a long time ago so I'm not quite sure exactly if it is still valid. If you can reproduce, maybe fix it? Thank you :-)

**Comment by Jack-Hawthorne** [comment]
@daren-thomas i'm assuming that this is caused by the documentation not existing when the original rsts were built.
The only thing that would have to be performed is a rebuild of the rst files using the sphinx-apidoc command. I have a good plan of how to do this, perhaps we could discuss?

**Comment by daren-thomas** [comment]
@Jack-Hawthorne I know you're doing this now in another branch - did that resolve the issue? because, then we can close this one.
