### ISSUE TITLE
add option for heating with mini-split AC

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1053]
This is basically for free with #1020 #1018 #668

**Comment by shanshanhsieh** [comment]
what is mini-split AC for heating?

**Comment by gabriel-happle** [comment]
@shanshanhsieh it means we could add the mini-split as an additional heating system in the CEA.

**Comment by gabriel-happle** [comment]
![image](https://user-images.githubusercontent.com/17002288/38719986-13079960-3f27-11e8-9523-dceb358900cf.png)

This issue would add another air-based system option to the heating system. Resulting in only an `aru` load.
To finish this issue one will just need to do some research on what is the actual supply temperature, as well as the cop to calculate electricity usage.

We are not focusing on heating for the super final version. That is why the milestone and epic are removed.

**Comment by gabriel-happle** [comment]
@shanshanhsieh and @martin-mosteiro is this something that is desired by anyone? Or should I close it?

**Comment by martin-mosteiro** [comment]
No need for this technology from my side
