### ISSUE TITLE
Create tests of CEA dependent on Plots

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1054]
@daren-thomas I wonder if we can create unittests of all plots.

I see that in order to make CEA good to go, It should be able to run all graphs correctly.  

This will help us to keep track of changes in Nomenclature and make sure that the final product is there.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA so you mean... running the plot scripts (there are two main ones, right?) with `cea test` and checking output files? sure. this can be done!

How does this relate to the dashboard effort? It was my understanding, that these plots will be replaced by the dashboard?

"track of changes in Nomenclature"... you know... we *could* formalize the name of output columns... and tie that in with the documentation - sort of create a machine readable representation of the expected column names along with descriptions of those columns and test against those in the tests PLUS also generate the documentation of output fields from that document. What do you think?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas so now you will find a file called plots_main.py. It runs all plots in CEA. If it passes then it will be a first good check. The only issue is that is needs the results of the networks, of the opetimization etc... so maybe it could at the end make testing extremely slow.
