### ISSUE TITLE
Syllabus presentations (15 March 2018)

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1071]
On the 15th of March, each participant in the CEA Executive Course should present the Syllabus of their lecture.

Attached is the schedule of the workshop as discussed on the 8th of February, as well as a Syllabus sample.

[CEA_Syllabus_Template.xlsx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/1747424/CEA_Syllabus_Template.xlsx)

**Comment by gabriel-happle** [comment]
@amraladdin is the Schedule fixed now?
Could you please give a few sentences what you expect in terms of content for each lesson?
I.e., for me it is not clear what is meant with "HVAC Systems + Electricity".
Thanks

**Comment by amraladdin** [comment]
Hey Gabriel, @JIMENOFONSECA has the latest version of the Syllabus template, so perhaps he has updates on this. Regarding "HVAC Systems + Electricity", perhaps you can also check with Jimeno, since he added this to your section.

**Comment by JIMENOFONSECA** [comment]
Let me check and come back to you. Later today

On 1 Mar 2018, 19:42 +0800, Amr Elesawy <notifications@github.com>, wrote:

Hey Gabriel, @JIMENOFONSECA<https://github.com/jimenofonseca> has the latest version of the Syllabus template, so perhaps he has updates on this. Regarding "HVAC Systems + Electricity", perhaps you can also check with Jimeno, since he added this to your section.

**Comment by JIMENOFONSECA** [comment]
@amraladdin I uploaded the syllabus, let me know how it is now. @gabriel-happle just let me know which doubts you have about the topic.

**Comment by amraladdin** [comment]
I checked the Syllabus, no additions from my side

**Comment by shanshanhsieh** [comment]
https://docs.google.com/spreadsheets/d/1Q4-xzaXAdGvNbmPBi_f9l36q9gN1Zpj4K9C9TooIRQo/edit#gid=561081142

**Comment by amraladdin** [comment]
Thank you everyone for your work and Syllabus presentations. I will close this issue and open another one for the next presentations session.
