### ISSUE TITLE
Check for the second wave of accepted scholarships

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1072]
Check for the applications sent and decide on who gets a scholarship and who wouldn't.

**Comment by amraladdin** [comment]
Checked and awaiting Jimeno's feedback. Results are below, as well as on Slack in executive-application Channel:
*ACCEPTED*
**
*MARTY-JOURJON VICTOR*
Reasons for *ACCEPTANCE*: I believe his didactic and research experience align nicely with the theme and goal of the course, since he also worked on policies, I believe he could have a new perspective, which could be interesting in the workshop discussions.
-    Major area in energy and processes.
-    MSc in Energy and Environmental Engineering (INSA Lyon).
-    18 months research experience in Energy modeling of French office building stock at district scale, in which it included typological studies of French districts through clustering methods.
-    Currently a PhD at the CES (Center for Energy efficiency of Systems) with the topic of “Assessment of energy policies at district scale through modeling methods”. (edited)
**
*SAMIRA GARSHABI*
*Before accepting, I'd like to discuss with you first... In case we agree to give her a scholarship, those would be the reasons*:
-    Background relates to the course topic, *although her PhD currently focuses on UHI effect*.
-    First author of publication in Applied Energy, and second in other journals (e.g. energy and building, solar energy), other than conference papers.
-    Awardee of (Scientia PhD Scholar), which according to UNSW is “a cornerstone of the UNSW 2025 Strategy, and aims to attract new PhD scholars of exceptional quality to undertake projects in strategic research areas. There are 125 Scholarships available per year.” (edited)

****

*REJECTED*
**
*AHMED JENDEYA*
-    Studies are focused on telecommunications systems engineering and electrical engineering in general.
-    There was no clear motivation how this specific course would be of interest/benefit for him. (edited)
**
*JUNHAN WEN*:
-    Studies are focused on Structural and mechanical analysis of superstructures.
-    There was no clear motivation how this specific course would be of interest/benefit for her/him.
**
*YUCHEN YANG*:
-    Working experience is more focused on the building scale (whether passive or active systems).
-    The focus of the course lies on energy systems and their integration on a district scale, and we considered applicants with a good level of experience in the field on that specific scale. Although he does have educational experience on energy systems, they were focused on the building scale.
- He has GPA: C in both under- and postgraduate studies. (edited)

**Comment by JIMENOFONSECA** [comment]
thanks for checking this, Yes I agree with both.
best, Jimeno
________________________________

**Comment by amraladdin** [comment]
Finished. Closing issue.
