### ISSUE TITLE
Thermal network plots

### ISSUE THREAD

**Issue by roglen** [architecture-building-systems/CityEnergyAnalyst#1078]
Create thermal network plots for CEA

**Comment by JIMENOFONSECA** [comment]
@roglen maybe you can describe here the results of our meeting? i.e., plots and priority? thanks!

**Comment by roglen** [comment]
Just saw this now, here is the summary:

Types of plots:

1. Plot thermal and pumping network loss over time for the full year in:
a. absolute values
b. relative values (relative to total plant heat produced in that time step)

2. Plot pressure loss and heat loss over distance from plant
(This ran into problems for looped networks (more than one distance from plant), and at low mass flows (Temperature does not always decrease as we move further away from the plant)

3. Plot a "load duration curve" of losses, this can be interesting to compare scenarios to see how losses are spread over the year.

4. Plot supply and return temperature vs ambient temperature for each plant

5. Plot a network image summarizing main network information and losses

**Comment by shanshanhsieh** [comment]
@roglen , there are some conflicts after the multiprocessing branch is merged. Could you please take a look at it? thanks!
