### ISSUE TITLE
Optimisation with the demand outputs

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1079]
The optimisation script should incorporate the new outputs from the demand calculations after #1062 is merged.
The first steps are changing: `decentralized_main`, `substation_main`, and `network_main`
Also, track down how `Egenf_cs` is used. (only for LCA calculation or in optimisation)

**Comment by shanshanhsieh** [comment]
@gabriel-happle  please specify the changes in the demand outputs here (which columns are added/deleted). Thanks!

**Comment by BhargavaKrishnaSreepathi** [comment]
included for cooling in #1251
