### ISSUE TITLE
failing to do pip install.[dev] with master branch in Windows.

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1091]
so there is something happening with the master branch. It seem it cannot install cvxopt which is being collected from pylibburo

Collecting cvxopt (from pyliburo>=0.1a8->cityenergyanalyst==2.7)

did the version of this changed? @daren-thomas have you faced this problem?

 Failed building wheel for cvxopt
  Running setup.py clean for cvxopt
Failed to build cvxopt
Installing collected packages: cvxopt, pyliburo, tqdm, requests-toolbelt, twine, cityenergyanalyst
  Running setup.py install for cvxopt ... error
    Complete output from command C:\Users\JimenoF\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\JimenoF\\AppData\\Local\\Temp\\pip-build-kvtrscq2\\cvxopt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\JimenoF\AppData\Local\Temp\pip-3xl34_tj-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\cvxopt
    copying src\python\coneprog.py -> build\lib.win-amd64-3.6\cvxopt
    copying src\python\cvxprog.py -> build\lib.win-amd64-3.6\cvxopt
    copying src\python\info.py -> build\lib.win-amd64-3.6\cvxopt
    copying src\python\misc.py -> build\lib.win-amd64-3.6\cvxopt
    copying src\python\modeling.py -> build\lib.win-amd64-3.6\cvxopt
    copying src\python\msk.py -> build\lib.win-amd64-3.6\cvxopt
    copying src\python\printing.py -> build\lib.win-amd64-3.6\cvxopt
    copying src\python\solvers.py -> build\lib.win-amd64-3.6\cvxopt
    copying src\python\_version.py -> build\lib.win-amd64-3.6\cvxopt
    copying src\python\__init__.py -> build\lib.win-amd64-3.6\cvxopt
    UPDATING build\lib.win-amd64-3.6\cvxopt/_version.py
    set build\lib.win-amd64-3.6\cvxopt/_version.py to '1.1.9'
    running build_ext
    building 'base' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\src
    creating build\temp.win-amd64-3.6\Release\src\C
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\JimenoF\Anaconda3\include -IC:\Users\JimenoF\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" /Tcsrc/C/base.c /Fobuild\temp.win-amd64-3.6\Release\src/C/base.obj
    base.c
    c:\users\jimenof\appdata\local\temp\pip-build-kvtrscq2\cvxopt\src\c\misc.h(35): error C2146: syntax error: missing ';' before identifier 'z'
    c:\users\jimenof\appdata\local\temp\pip-build-kvtrscq2\cvxopt\src\c\misc.h(35): error C2061: syntax error: identifier 'z'
    c:\users\jimenof\appdata\local\temp\pip-build-kvtrscq2\cvxopt\src\c\misc.h(36): error C2059: syntax error: '}'
    src/C/base.c(46): error C2122: 'void *': prototype parameter in name list illegal
    src/C/base.c(46): error C2122: 'int': prototype parameter in name list illegal
    src/C/base.c(46): error C2122: 'void **': prototype parameter in name list illegal
    src/C/base.c(49): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(52): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(55): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(58): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(60): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(60): error C2061: syntax error: identifier '_complex'
    src/C/base.c(60): error C2059: syntax error: ')'
    src/C/base.c(67): error C2061: syntax error: identifier 'One'
    src/C/base.c(67): error C2059: syntax error: ';'
    src/C/base.c(67): error C2059: syntax error: '['
    src/C/base.c(79): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(79): error C2065: '_complex': undeclared identifier
    src/C/base.c(79): error C2059: syntax error: ')'
    src/C/base.c(79): error C2297: '*': illegal, right operand has type 'void'
    src/C/base.c(79): error C2143: syntax error: missing ')' before ';'
    src/C/base.c(95): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(95): error C2065: '_complex': undeclared identifier
    src/C/base.c(95): error C2059: syntax error: ')'
    src/C/base.c(95): error C2297: '*': illegal, right operand has type 'void'
    src/C/base.c(95): error C2143: syntax error: missing ')' before ';'
    src/C/base.c(96): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(96): error C2065: '_complex': undeclared identifier
    src/C/base.c(96): error C2059: syntax error: ')'
    src/C/base.c(96): error C2297: '*': illegal, right operand has type 'void'
    src/C/base.c(96): error C2143: syntax error: missing ')' before ';'
    src/C/base.c(134): warning C4244: '=': conversion from 'Py_ssize_t' to 'double', possible loss of data
    src/C/base.c(157): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(157): error C2065: '_complex': undeclared identifier
    src/C/base.c(157): error C2100: illegal indirection
    src/C/base.c(157): error C2059: syntax error: ')'
    src/C/base.c(157): error C2297: '*': illegal, right operand has type 'void *'
    src/C/base.c(159): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(159): error C2065: '_complex': undeclared identifier
    src/C/base.c(159): error C2100: illegal indirection
    src/C/base.c(159): error C2059: syntax error: ')'
    src/C/base.c(159): error C2297: '*': illegal, right operand has type 'void *'
    src/C/base.c(161): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(161): error C2065: '_complex': undeclared identifier
    src/C/base.c(161): error C2100: illegal indirection
    src/C/base.c(161): error C2059: syntax error: ')'
    src/C/base.c(161): error C2297: '*': illegal, right operand has type 'void *'
    src/C/base.c(161): error C2297: '*': illegal, right operand has type 'void'
    src/C/base.c(161): error C2143: syntax error: missing ')' before ';'
    src/C/base.c(166): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(166): error C2065: '_complex': undeclared identifier
    src/C/base.c(166): error C2100: illegal indirection
    src/C/base.c(166): error C2059: syntax error: ')'
    src/C/base.c(166): error C2297: '*': illegal, right operand has type 'void *'
    src/C/base.c(166): error C2088: '*': illegal for struct
    src/C/base.c(247): warning C4244: 'function': conversion from 'Py_ssize_t' to 'long', possible loss of data
    src/C/base.c(259): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(259): error C2065: '_complex': undeclared identifier
    src/C/base.c(259): error C2059: syntax error: ')'
    src/C/base.c(259): error C2297: '*': illegal, right operand has type 'void'
    src/C/base.c(259): error C2143: syntax error: missing ')' before ';'
    src/C/base.c(264): error C2146: syntax error: missing ')' before identifier 'a'
    src/C/base.c(264): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(264): error C2061: syntax error: identifier 'a'
    src/C/base.c(264): error C2059: syntax error: ';'
    src/C/base.c(264): error C2059: syntax error: ','
    src/C/base.c(264): error C2059: syntax error: ')'
    src/C/base.c(273): error C2146: syntax error: missing ')' before identifier 'a'
    src/C/base.c(273): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(273): error C2061: syntax error: identifier 'a'
    src/C/base.c(273): error C2059: syntax error: ';'
    src/C/base.c(273): error C2059: syntax error: ','
    src/C/base.c(273): error C2059: syntax error: ')'
    src/C/base.c(281): error C2146: syntax error: missing ')' before identifier 'a'
    src/C/base.c(281): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(281): error C2061: syntax error: identifier 'a'
    src/C/base.c(281): error C2059: syntax error: ';'
    src/C/base.c(281): error C2059: syntax error: ','
    src/C/base.c(281): error C2059: syntax error: ')'
    src/C/base.c(291): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(291): error C2065: 'idiv': undeclared identifier
    src/C/base.c(291): error C2065: 'ddiv': undeclared identifier
    src/C/base.c(291): error C2065: 'zdiv': undeclared identifier
    src/C/base.c(291): error C2099: initializer is not a constant
    src/C/base.c(293): error C2146: syntax error: missing ')' before identifier 'a'
    src/C/base.c(293): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(293): error C2061: syntax error: identifier 'a'
    src/C/base.c(293): error C2059: syntax error: ';'
    src/C/base.c(293): error C2059: syntax error: ','
    src/C/base.c(293): error C2059: syntax error: ')'
    src/C/base.c(302): error C2146: syntax error: missing ')' before identifier 'a'
    src/C/base.c(302): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(302): error C2061: syntax error: identifier 'a'
    src/C/base.c(302): error C2059: syntax error: ';'
    src/C/base.c(302): error C2059: syntax error: ','
    src/C/base.c(302): error C2059: syntax error: ')'
    src/C/base.c(311): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(311): error C2065: 'mtx_irem': undeclared identifier
    src/C/base.c(311): error C2065: 'mtx_drem': undeclared identifier
    src/C/base.c(311): error C2099: initializer is not a constant
    src/C/base.c(360): error C2065: 'number': undeclared identifier
    src/C/base.c(360): error C2146: syntax error: missing ';' before identifier 'a'
    src/C/base.c(360): error C2065: 'a': undeclared identifier
    src/C/base.c(360): fatal error C1003: error count exceeds 100; stopping compilation
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\JimenoF\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\JimenoF\\AppData\\Local\\Temp\\pip-build-kvtrscq2\\cvxopt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\JimenoF\AppData\Local\Temp\pip-3xl34_tj-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\JimenoF\AppData\Local\Temp\pip-build-kvtrscq2\cvxopt\

(C:\Users\JimenoF\Anaconda3) C:\Users\JimenoF\Documents\GitHub\CityEnergyAnalyst>

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I just tested in a new conda environment and didn't have a problem. Next step: testing in a new virtual machine to make sure there are no caches etc.

BTW: Reading through the output, it looks like you might be installing on python3?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I just (successfully) installed on a blank virtual machine. I think your problem has to do with installing into the root Anaconda3 environment, possibly with python 3.x.

Can you please verify and then close this issue?

**Comment by JIMENOFONSECA** [comment]
It works!, thanks!, I have Anaconda 3, I just was working without activating the right CEA environment. my bad. thanks a lot for checking this for me.
