### ISSUE TITLE
CEA EC18 - "Demand Forecast assessment" tutorial update

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1103]
Taking a look at the tutorials, I realized the Demand Forecast Assessment tutorial is not updated:
https://docs.google.com/presentation/d/1o-xfDRPpt7zY2rxcsbTjmVwGqbWXSi_IrxKSaer59-M/edit#slide=id.gc6f73a04f_0_46

**Comment by JIMENOFONSECA** [comment]
@amraladdin would you mind giving us some more details? I guess @gabriel-happle can give a better update about this. I am adding him to the issue instead of me.

**Comment by gabriel-happle** [comment]
Sorry. No time for this.

**Comment by JIMENOFONSECA** [comment]
Changing to another milestone, we will not be able to handle this

**Comment by amraladdin** [comment]
Ok, sounds great! I also changed the priority and the Epic. @gabriel-happle I'll assign you to this task then.

**Comment by gabriel-happle** [comment]
Who needs this urgently @amraladdin?
It's not related to my research.
