### ISSUE TITLE
CEA EC18 - Check Default Databases Tutorial 

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1108]
Check default databases tutorial and make sure it's up-to-date:
https://docs.google.com/presentation/d/1xMG-Vhmqh0jwdLih6WgwFzJrzhlPGdocQKdzZvYnviI/edit#slide=id.g1f177b6116_0_487

**Comment by JIMENOFONSECA** [comment]
@amraladdin checked!
