### ISSUE TITLE
CEA EC18 - Check Advanced Tutorials and create issues

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1111]
Check the following Tutorials on:
http://city-energy-analyst.readthedocs.io/en/latest/tutorials.html

Make, sure they are up-to-date.
If now, create an issue and assign a collaborator to finish it.

*Advanced*

__Below tutorials are published on the CEA website.__

- How does the Urban Solar Radiation tool work?
Seems updated

- How does the Dynamic Demand Forecast feature work?
@JIMENOFONSECA can you check this presentation and update?

- How does the Renewable Energy Assessment tool work?
(Fix title, either on the Tutorials list page or on the slide)
(Slide 13, image requires updating)
@shanshanhsieh can you check this presentation and update?

- How does the Life Cycle Assessment tool work?
(Slide 8, 10, 12, 14, 15, 17... etc. images require updating)
@martin-mosteiro can you check this presentation and update?

- How does the 2000-Watt Bench-marking tool work?
@martin-mosteiro can you check this presentation and update?

- How to study building retrofits in the CEA?
@JIMENOFONSECA can you check this presentation and update?

- How does the Sensitivity Analysis tool work?
@martin-mosteiro can you check this presentation and update if necessary?

__Below tutorials are not published on the CEA website yet.__
- How does the Data Helper tool work?
Amr will work on this.
- How does the Multi-Objective Optimization tool work?
- How does the Multi-Criteria Assessment tool work?
- How does the Mapping and Visualization tool work?
- How does the Bayesian Calibration tool work?
- How does the Block Generator tool work?
Who is supposed to work on the remaining tutorials?

**Comment by martin-mosteiro** [comment]
Worth noting: the tutorial **What are the default databases of CEA?** is incomplete, the section on the construction properties database (i.e., construction_properties.xlsx) only describes the 'ARCHITECTURE' tab.

**Comment by shanshanhsieh** [comment]
the *Renewable Energy Assessment tool* is updated now
