### ISSUE TITLE
CEA EC18 - Check "How to create your own input geometry?" tutorial

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1112]
Check "How to create your own input geometry?" and make sure it's up-to-date:
https://cityenergyanalyst.com/creating-multiple-scenarios#create-new-geometry

**Comment by martin-mosteiro** [comment]
Looks good to me, I haven't changed input geometries in a while but unless ArcGIS has changed some functionality it should still be correct.
