### ISSUE TITLE
Make thermal and pressure network plot interactive

### ISSUE THREAD

**Issue by roglen** [architecture-building-systems/CityEnergyAnalyst#1129]
Add hovering labels, as curent labels overlap and are very unclean for complex networks. 

E.g.
- adjust_text library
- mpld3 library

**Comment by roglen** [comment]
Check out:
- http://www.dalkescientific.com/writings/diary/mw_v_xlogp.html
- https://mpld3.github.io/notebooks/mpld3_demo.html
- https://mpld3.github.io/modules/API.html

**Comment by JIMENOFONSECA** [comment]
duplicate of #2082
