### ISSUE TITLE
Research faster ways for documenting tutorials

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1136]
Since we began developing the CEA, the interface changed several times in short time intervals. This resulted in having to change the tutorials screenshots and explanation (user's manual and how to use the CEA). I'm looking for a way to speed up this process, so I'm searching for a tool that can help us take the tutorials screenshots and perhaps content faster.

I found the following options, which I'm still checking.:
http://stepshot.net/
(I checked this one, takes snapshots while you're using the tool, also takes content from the tool interface and adds it to the screen shot)
Info so far:
Pricing for StepShot Guides Educational version is following:
$12/user month or
$119/user for a year
It is always available here: https://stepshot.net/pricing-guides/ and on 'Plans' tab in your account at https://guides.stepshot.net/ where you can also purchase licenses.

- Tried Windows Step Recorder. Not useful. Minimum options. No editing possibility. No useful formats.
- Tried Greenshot. Not very intuitive. not as fast as Stepshot. Free.
- Tried Adobe Captivate. Very nice and professional. Takes a bit longer time to learn, but probably is worth it. Expensive, but perhaps we can get a Chair License. Need to ask Daren.
- Still need to check the following options:
https://www.itqlick.com/stepshot/competitors
https://alternativeto.net/software/stepshot/

I'm still investigating the below options:
https://www.business2community.com/customer-experience/top-9-online-help-authoring-tools-better-help-desk-support-01341897

https://www.capterra.com/sem-compare/digital-asset-management-software?headline=Document%20Management%20Software&gclid=CjwKCAiA24PVBRBvEiwAyBxf-V-2ga5qk5QE6D7pw0jZH855mEJZGcMqSfKmar_bLFT6Bbe0ZQt79BoCbsQQAvD_BwE&gclsrc=aw.ds

https://www.quora.com/What-are-the-best-online-tools-for-dynamic-document-creation-document-automation-I-have-tried-Drawloop-under-Salesforce-and-found-it-amazingly-complicated

https://www.process.st/software-documentation/

https://www.business2community.com/customer-experience/top-9-online-help-authoring-tools-better-help-desk-support-01341897

https://docs.microsoft.com/en-us/azure/automation/

**Comment by daren-thomas** [comment]
@amraladdin specifically, what problem are you addressing? You mention finding a way to "automate documentation for use in the tutorials and users' manual" but list a bunch of articles instead - which of those is the way you mention? what are you automating?

**Comment by amraladdin** [comment]
@daren-thomas calmer now?

**Comment by daren-thomas** [comment]
@amraladdin yes, thank you.
