### ISSUE TITLE
Check with the LET department at ETH for video recording of the CEA EC

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1137]
Get in touch with:
https://www.ethz.ch/services/en/it-services/catalogue/multimedia.html

Check how we can maximize the use of their services at FCL.

**Comment by amraladdin** [comment]
I received a reply from the LET department:
- We’re not certain as to the support level we can help you with.
- We need to know where these events take place in order to find out what infrastructure we can work upon (videoconferencing, signals, equipment).
- Also, we would like to know whether there is a chance of you or an assistant or a support person in Singapore dealing with recording equipment we might provide (subject to room infrastructure) – is there a willingness and some know-how to support a do-it-yourself approach?

@JIMENOFONSECA what do you think?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA @amraladdin please keep me in the loop as i am responsible for the video taping of the lectures :)

**Comment by amraladdin** [comment]
@daren-thomas Done, I sent you an email with all the correspondences conducted with the LET guys so far. Should I assign you to this issue as well?

**Comment by daren-thomas** [comment]
@amraladdin I just went ahead and added myself. many thanks!

**Comment by amraladdin** [comment]
Great! I'll take myself out from this issue then.
