### ISSUE TITLE
Implement search field in dashboard navigation panel

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1145]
From the mockup:

> A search button to find direct access to the tools included in the menu
>   - search on tool name, tool description, tool category
>   - also search on parameter names and parameter descriptions?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA is this still a thing? (asking, because the interface has changed a lot since the issue was created - maybe we can close it?)

**Comment by JIMENOFONSECA** [comment]
Yes, let’s close it
On 28 Oct 2019, 17:47 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> is this still a thing? (asking, because the interface has changed a lot since the issue was created - maybe we can close it?)
