### ISSUE TITLE
Technical systems in archetypes have outdated codes

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1161]
The archetypes define technical systems by their old codes, thus all heated building types built after 2006 are assigned heating by central AC. This is doesn't make any sense! @JIMENOFONSECA I assume this is a mistake and these buildings were meant to have 'T4' = floor heating (*not* 'T3' = central AC)?

**Comment by JIMENOFONSECA** [comment]
you are right!

On 27 Mar 2018, 12:14 PM +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

The archetypes define technical systems by their old codes, thus all heated building types built after 2006 are assigned heating by central AC. This is doesn't make any sense! @JIMENOFONSECA<https://github.com/JIMENOFONSECA> I assume this is a mistake and these buildings were meant to have 'T4' = floor heating (not 'T3' = central AC)?
