### ISSUE TITLE
thermal_network_matrix.py for DH case is not having any pressure losses in reference-case-open

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1162]
the thermal_network_matrix.py run using `DH` is not having any losses. This is fishy. For the same case study, if the `DC` is run, we are having the losses

**Comment by shanshanhsieh** [comment]
@BhargavaKrishnaSreepathi , I ran the script from master with the `reference-case-open` in the example folder. Both `DH` and `DC` are working fine.
Could you try it out again? and make sure you are changing the `thermal-network` section in the config file.

**Comment by shanshanhsieh** [comment]
@BhargavaKrishnaSreepathi is this issue still relavent?

**Comment by BhargavaKrishnaSreepathi** [comment]
@shanshanhsieh did not check it in recent times

**Comment by shanshanhsieh** [comment]
i can't replicate the error at the moment...
we can reopen an issue if the problem comes up again
