### ISSUE TITLE
Save a file in the network folder to depict the pipe length and diameter of the DH/DC network

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1163]
Based on the thermal_network_matrix.py calculations, the output of the final network along with the pipe properties is to be saved to do the calculation of the pressure losses for a differnt network for the same case study.

**Comment by shanshanhsieh** [comment]
The updated information on pipe properties are saved in files called `DH/DC_AllEdges.csv`
