### ISSUE TITLE
Update Google Sheet "Registration Executive Course"

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1186]
@JIMENOFONSECA could you please update the List Payments on the "Registration Executive Course" Google Sheets?
https://docs.google.com/spreadsheets/d/1ILB-skmKkGubvpSI62lFsIqpBKC6LFvm-Lskw55a2Yo/edit#gid=1254404525

**Comment by JIMENOFONSECA** [comment]
Done :-)

Kind regards,

Dr. Jimeno A. Fonseca
Senior Researcher and Project Coordinator
Multi-Scale Energy Systems for Low-Carbon Cities (MuSES)
Future Cities Laboratory
Singapore ETH-Centre

Chair of Architecture and Building Systems
Institute of Technology in Architecture
ETH Zurich

Scientific Advisory Committee
Energy and Sustainability 2017

On 5 Apr 2018, 17:49 +0800, Amr Elesawy <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> could you please update the List Payments on the "Registration Executive Course" Google Sheets?
https://docs.google.com/spreadsheets/d/1ILB-skmKkGubvpSI62lFsIqpBKC6LFvm-Lskw55a2Yo/edit#gid=1254404525

**Comment by amraladdin** [comment]
Thanks a lot @JIMENOFONSECA 
Regarding the non-confirmed ones. Is there any reason why they haven't paid so far?

Best,
Amr

**Comment by JIMENOFONSECA** [comment]
no idea. I Imagine they first 4 are out. The rest will make the registration effective soon, so do not worry. I take care of this.

________________________________

**Comment by amraladdin** [comment]
Ok great! Thanks!
