### ISSUE TITLE
BUG in electricity demand calculation

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1193]
There is a bug in the weighted schedule calculation of the electricity demand.

E.g. in the Zug case study "Bau A" the demand is way too high as when directly compared to the archetype values.

Appliance power in first hour of year:
`p_use_h * p_use_m * share_occ * Aef * P_appliance =`
`(Restaurant) 0.1 * 0.8 * 0.2 * 14240m2 * 31.7 W/m2 + (Parking) 0.1 * 0.8 * 0.8 * 14240m2 * 0 W/m2 =` `7222 W != 36113 W (currently in CEA)`

Light power in first hour of the year:
`(Restaurant) 0.1 * 0.8 * 0.2 * 14240m2 * 8.3 W/m2 + (Parking) 0.1 * 0.8 * 0.8 * 14240m2 * 2.9 W/m2 = `
`4534 W != 9398 W (currently in CEA)`

The bug is somewhere in the weight calculation in `occupancy_module.calc_remaining_schedules_deterministic`

See also the comments in #1189 

Assigning @martin-mosteiro because he last worked on that script.

**Comment by martin-mosteiro** [comment]
@gabriel-happle The PR #1207 solves an issue with the electricity demands Eref, Edataf, Eprof.

The issue you pointed out, however, is not actually an issue: if you want CEA to give you the same results as the archetypes, you need to run the data helper, and then you will get the archetypal appliance and lighting demand for the mixed use building "Bau A".

For a building with 80% parking and 20% restaurant the appliance and lighting power should be Ea=6.34 W/m2 and El_Wm2=3.98 W/m2. Right now the inputs for "Bau A" are Ea=31.7 W/m2 and El=8.25 W/m2, so the demand should *not* match the archetypal demand.

If you do run the data helper first, you will get the same results as the archetypes indicate.

**Comment by gabriel-happle** [comment]
@martin-mosteiro got it. Thanks.
