### ISSUE TITLE
Maybe a BUG: electricity demand for datacenter might be too high

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1194]
The 500 W/m2 power for `SERVERRROM` in the archetypes DB might be too high.
It causes the BAU 16 in the Zug case study to overheat already in winter.
Heating is not needed at all in that building.

See also the comments in #1189

![image](https://user-images.githubusercontent.com/17002288/38483631-3e59fd02-3c06-11e8-9ac7-06f12eaa9712.png)

![image](https://user-images.githubusercontent.com/17002288/38483697-74d28926-3c06-11e8-8042-259af6d87f6d.png)

@JIMENOFONSECA can I assign this to you?
Or does @martin-mosteiro have any measured values from ETH?

**Comment by JIMENOFONSECA** [comment]
I think something is not working fine with the calculation. Is the 500 W/m2 applied over the entire area? or just that of the servers?

________________________________
