### ISSUE TITLE
Installation guide for windows minor issues

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#1197]
Pycharm community editor links to Anaconda Home Page

Miniconda --  to include whether to add path manually or use the check box upon installation

Installation
		4. cd CityEnergyAnalyst NOT cd documents/CityEnergyAnalyst
		5. remove "and activate cea"

**Comment by daren-thomas** [comment]
@Jack-Hawthorne, for step 4., it kind of depends where you cloned the repository to (on my system it's actually `Documents\Github\CityEnergyAnalyst`)

**Comment by Jack-Hawthorne** [comment]
@daren-thomas this is true, although the steps above specify only cd to documents not to github prior to cloning. Following the instructions directly cloned into documents, would you prefer to cd to github?

**Comment by daren-thomas** [comment]
That folder might not exist yet... so you'd have to `mkdir` it first... you decide :-)
