### ISSUE TITLE
Potential problem with units in results of thermal network

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1204]
So it seems that the pumping losses are marginal in relation to thermal losses. is that correct? @shanshanhsieh @roglen would you mind checking this?

![image](https://user-images.githubusercontent.com/8973186/38596082-1f7f9eaa-3d82-11e8-8be4-225873d3d8d0.png)

**Comment by roglen** [comment]
@JIMENOFONSECA It seems like something is off here. Which network is this from?

**Comment by roglen** [comment]
Thermal losses could be about 1000 times too high here, depending on which case it is. There were some changes to the constants in the master so that might be the cause. I will look into it.
