### ISSUE TITLE
L3 Presentation Draft. UES tools review

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1211]
Finish presentation:
https://docs.google.com/presentation/d/1VhkNrCNKBulpc-cU8ncLhdwR9LuU4nwwWVjkEeriSro/edit#slide=id.g34eecdebe2_0_3

@JIMENOFONSECA could you please send me parts 3 and 4 of your presentation? These would fit better in my lecture.

**Comment by JIMENOFONSECA** [comment]
Hi Amr,

I did not work on those parts, so you can go ahead and develop them.

Best,
Jimeno

On 24 Apr 2018, 04:19 +0800, Amr Elesawy <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> Can you please send me parts 3 and 4 of your presentation? These would fit better in my lecture.
