### ISSUE TITLE
Void deck should consider the base of the building in contact with air and not ground 

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1218]
Void deck should consider the base of the building in contact with air and not ground 
This is a small change to the R-C-model properties calculation.
This issue came up during the developer walk through meeting on 12.04.2018.

@JIMENOFONSECA should it be in the super final version? What priority is this?

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle was this fixed in any of the releases?

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA no, this has not been addressed so far.

**Comment by JIMENOFONSECA** [comment]
so we fixed the voi_deck parameter to account for the number of floors from the surface up that have void-deck. that works for most cases
