### ISSUE TITLE
Issue with outputs of demand calculation

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1223]
@BhargavaKrishnaSreepathi @gabriel-happle this is an interesting issue that involves the connection of the results of the demand, the optimization and the plots.

For the Singaporean context the next caveats exist:

Buildings with district cooling will have a value for Qcsf = x,  Ef =y, and Qwwf =z, whereas  Egen which refers to electricity needed for generation due to cooling or heating systems in the building will be zero or Egen = 0.

Buildings without district cooling (with heatpumps for cooling demand) will have a value of Qcsf = 0, Egen = (Qcs + Qcs_loss)*eff heatpump , Ef = Ea+El +Edata + Eref + Egen

Are we all considering this in your calculations and plots?

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA I don't understand this issue? Do you want to adjust the demand calculation after the optimization?

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle not really. It is to say that cooling does not get counted twice while making the plots or duting the optimization (in terms of Qcsf and Ef).

**Comment by JIMENOFONSECA** [comment]
yep for any case study with cooling you can check this behavior in the demand plots. Maybe we can meet with @BhargavaKrishnaSreepathi and @shanshanhsieh also to fix this issue? I think we need to agree on this inter dependency.

**Comment by BhargavaKrishnaSreepathi** [comment]
Fixed in PR #1265
