### ISSUE TITLE
improve runtime for solar collectors

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1224]
The runtime of `solar_collectors.py` and `photovoltaic_thermal.py` grows in great magnitude as the case study gets bigger.
We need to look into how to improve it. Support from @daren-thomas will be required.

Current runtime for reference-case-open:
- run solar_collector.py with type-scpanel = 'SC1' and t-in-sc=75. this calculates the potential of flat plate collectors. (~10 min)
- run solar_collector.py with type-scpanel = 'SC2' and t-in-sc=150. this calculated the potential of evacuated tube collectors. (~90min)

**Comment by daren-thomas** [comment]
@shanshanhsieh do you have any news on this?

**Comment by shanshanhsieh** [comment]
this issue was resolved in PR#1627 and merged
