### ISSUE TITLE
Fix arcgis interface folder path pop-up

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1225]
@daren-thomas when trying to locate a file from the arcgis interface, the tool does not identify .shp files.

![image](https://user-images.githubusercontent.com/8973186/38720946-ca8bb870-3f2a-11e8-8d67-89474d95bcfd.png)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA this is an easy one: in the `default.config` file, those parameters were specified as `PathParameter` instead of `FileParameter`.

![image](https://user-images.githubusercontent.com/2969564/38854954-68addf3e-4222-11e8-85c5-04ac17622eec.png)

**Comment by JIMENOFONSECA** [comment]
@daren-thomas oh I see... would you mind creating a PR for me to check?

**Comment by daren-thomas** [comment]
please check #1249

**Comment by daren-thomas** [comment]
merged long time ago :-)
