### ISSUE TITLE
seasonhours replacement

### ISSUE THREAD

**Issue by Khayatian** [architecture-building-systems/CityEnergyAnalyst#1229]
Hi all,

Variable "seasonhours" has been removed from the script of globalvariables. What has replaced it? This is in fact important for the preprocessing of the Neural Network to understand heating/cooling seasons.

Tnx

**Comment by gabriel-happle** [comment]
@Khayatian this variable is now part of the databases. Check here:
`cea\databases\CH\archetypes\system_controls.xlsx`

In general we are working on removing all variable from the `gv`. They either move to input databases or to fixed constants inside scripts.

**Comment by JIMENOFONSECA** [comment]
Hi, you can ask Gabriel for info about this issue.

On 13 Apr 2018, 18:31 +0800, Fazel Khayatian <notifications@github.com>, wrote:

Assigned #1229<https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/1229> to @JIMENOFONSECA<https://github.com/JIMENOFONSECA>.

**Comment by Khayatian** [comment]
Hi both,

Thank you for clarifying this @gabriel-happle . I will open a new issue later to update my code with your help.

This issue is resolved and will close it
