### ISSUE TITLE
Table with description of variables for tools and databases

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1238]
@Jack-Hawthorne welcome to the team form my side. 

I believe one crucial aspect of the documentation for the executive course is to have a glossary of terminology. Especially in regards to the contents of all our databases. The glossary should be easy to explore and present the name, nomenclature, unit and description of each variable.

A lot of work has been already done on creating tables describing each variables (check 'how are the input databases of cea organized" tutorial. 

Can I assign this issue to you?

**Comment by Jack-Hawthorne** [comment]
Hey @JIMENOFONSECA, that's not a problem. 

How would you like me to format the documentation for the executive course (would you like in the dev walk-through, tutorials or a new rst?). 

Also what is the approx. deadline for this exec course and is there an exiting branch? I am only able to work 8-10 hours a week, generally Monday mornings until 12.30, and Thurs and Fri afternoons until 18:00.

**Comment by JIMENOFONSECA** [comment]
Hi Jack, yes you can see the deadline in the information of the milestone. i.e., beginning of July.

I think the glossary needs to be accessed quickly so I think it should be at the same level of Tutorials.


________________________________

**Comment by amraladdin** [comment]
Hi @Jack-Hawthorne , did you already start with the variables list? If yes, could you share the document you're working with? It's best if you're using a shared document (e.g. Google Sheets) for example.

**Comment by amraladdin** [comment]
Common terminology Google Sheet link:
https://docs.google.com/spreadsheets/d/149Ugw8BfKI_2wMzOrHHVN3D8pOff29eQIzWg8y9Qy9k/edit#gid=0

**Comment by Jack-Hawthorne** [comment]
@amraladdin i have created a new git branch to address the issue instead. Is this ok?
https://github.com/architecture-building-systems/CityEnergyAnalyst/tree/1238-glossary-terms-and-databases
The super basic csv file is recorded here for Thomas (and anyone else) to work on. I have told him to contact me if he has any questions and he will relay to you or daren if i cannot answer.

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne @daren-thomas is this issue closed?
