### ISSUE TITLE
As a practitioner I want to know what are the common issues of CEA so I do not bother the team with questions

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1239]
@Jack-Hawthorne the section of Known Issues in the manual of CEA should be changed to perhaps a table referencing the error message and a link to the issue in github discussing how to solve it.

see how the guys of Tensorflow do that here (see the table at the end of the next website)

https://www.tensorflow.org/install/install_windows

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is Jack around or would this fit in your domain now?

**Comment by Jack-Hawthorne** [comment]
@JIMENOFONSECA i will have a look at this in the next weeks, apologies for the lack of communication.
