### ISSUE TITLE
As practitioner I would like to have a guide targets in my graphs so I can better compare my solution against my performance goal

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1243]
As an orientation for the user to compare his/her district to... some dotted lines in the background showing target values and maybe an average value...

**Comment by daren-thomas** [comment]
@JIMENOFONSECA who would be the best fit for this issue?

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi or @shanshanhsieh I think this fits your work?

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
