### ISSUE TITLE
Rename "Sewage heat-pump" tool name in ArcGIS interface to "Sewage heat-exchanger"

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1246]
The name is wrong, the tool is called `cea sewage-heat-exchanger`. This is as simple as editing the `CityEnergyanalyst.pyt` file and updating the label property.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA who is the best fit for this?

**Comment by BhargavaKrishnaSreepathi** [comment]
fixed in i1437-quick-fix-to-typo
