### ISSUE TITLE
CEA installation

### ISSUE THREAD

**Issue by stevekardinaljusuf** [architecture-building-systems/CityEnergyAnalyst#1252]
I am at Step no 8 of “Configuration of Pycharm”
8. Type cd *conda2\envs\cea and hit ENTER.

It shows as follows. Please advise. Thank you.

--------------------------------------------
Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\a88491>cd *conda2\envs\cea
The filename, directory name, or volume label syntax is incorrect.
--------------------------------------------

**Comment by daren-thomas** [comment]
@Jack-Hawthorne this is probably something for you to look into. Could you please advise?

@stevekardinaljusuf this is an issue with the documentation. It should read "cd conda2\envs\cea". without the asterix.

**Comment by stevekardinaljusuf** [comment]
Yes.. I tried that too..
----------------
C:\Users\a88491>cd conda2\envs\cea
The system cannot find the path specified.
--------------------------


I tried install at another computer.. It works fine.

**Comment by Jack-Hawthorne** [comment]
@daren-thomas for steps 7 through to 10 on the Configuration of Pycharm, my aim was to create an easy way to add path to env variables. I wasn't aware that it would only be temporary for the cmd session. 

Should I convert this to the original - where it simply stated to add new environment to path?
Perhaps I could add a link for more information?

**Comment by daren-thomas** [comment]
@Jack-Hawthorne - good plan. yes, the temporary nature of the `set` command in batch is surprising at first.

You could mention adding it to the environment path. Though... I don't think it's necessary at all. Actually, I don't really see the reasoning.

**Comment by Jack-Hawthorne** [comment]
sure thing i'll remove the relevant sections (7-9) and only keep the restart pycharm (step 10).
