### ISSUE TITLE
Neural Net ready for server

### ISSUE THREAD

**Issue by Khayatian** [architecture-building-systems/CityEnergyAnalyst#1253]
The Neural Network is ready to run of the server for training the surrogate on ecocampus. The branch is:
i928b_recovering_SuS_Calibration

The process should take around 2 days.
Please ensure the following settings are assigned in the config file:

[neural-network]
year = 2015
warmup_period = 759
nn-delay = 1
nn_passes = 20
number-samples-scaler = 200
number_samples = 10
number_sweeps = 10
autoencoder = false

**Comment by JIMENOFONSECA** [comment]
@Khayatian to make sure it runs, could you upload your config file? thanks!

**Comment by Khayatian** [comment]
Forwarded to you via slack. Let me know if it works.
Thanks
