### ISSUE TITLE
Error: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CityEnergyAnalyst#1264]
Hi, @daren-thomas 
I am seeing this error in both ArcMap and PyCharm... Could you give me a hand about this?
![25](https://user-images.githubusercontent.com/16640327/39183360-499cc68e-47f2-11e8-9cd5-19a360f1264b.PNG)
![26](https://user-images.githubusercontent.com/16640327/39183365-4d6bb19e-47f2-11e8-86ff-37e05230927e.PNG)
Thanks!

**Comment by daren-thomas** [comment]
it means you have a mix between 32-bit and 64-bit installations. check that
your python version is the one you expect it to be. maybe install the
arcgis 64-bit background processing thing?

**Comment by shizhongming** [comment]
Thanks. The script runs on Pycharm now after I install the processing thing. Still now on arcgis Map. But at least I can run the tool now.
Thanks again.
