### ISSUE TITLE
tool for supply system simulation

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1269]
- adapt the optimization to allow simulation of a single individual
- make an arcgis interface

**Comment by shanshanhsieh** [comment]
In this tool, we are planning to let users simulate different supply system configurations.

Which means they can choose:
1. Cooling technologies in the centralized plant
2. Buildings to connect to the network
3. Cooling technologies for all disconnected buildings 
4. Areas to install PV or SC

@JIMENOFONSECA , please let us know if you have further comments, thanks!

**Comment by shanshanhsieh** [comment]
renaning tasks:
1. change the default setting to cooling (don't connect to `isheating` and `iscooling` flags which are used in optimisation)
2. reduce the calculation time-steps to a month (May)

**Comment by shanshanhsieh** [comment]
![image](https://user-images.githubusercontent.com/16998305/42018315-4f860dba-7ae4-11e8-819f-74ab07fef66d.png)
@daren-thomas , help needed here.
I would like to use BuildingsParameter to list out the buildings in the interface, and then send back a list of buildings selected to run the simulation.
It seems like the input from the building selection is not in the format of list.

**Comment by daren-thomas** [comment]
@shanshanhsieh what branch is this?
