### ISSUE TITLE
CEA Progress Overview update on website

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1270]
I noticed while navigating through the CEA website that the roadmap has not been updated since July 2017. So I was wondering if the Development status is also not updated?
If so, can we update it so I can include it in my CEA introductory lecture?
@JIMENOFONSECA

**Comment by JIMENOFONSECA** [comment]
@amraladdin so, yep, we have not updated it completely. I will update the development status, but a new roadmap will be discussed during our meeting of the 9th of July.

**Comment by amraladdin** [comment]
Great! Thanks!
