### ISSUE TITLE
broken links on the CEA website

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1271]
Seems some links on the CEA website are broken. Here is what I found so far:
http://city-energy-analyst.readthedocs.io/en/386-create-readthedocs-style-api-documentation/index.html
You can find this broken link, navigating to: https://cityenergyanalyst.com/overview -> Choose any feature from the left list pane -> then scroll down till the end of the page and click on the **“CEA Developers manual and API”** link (Check an example in the image below).

![image](https://user-images.githubusercontent.com/16256867/39567209-83f371de-4ebe-11e8-902e-adc900b51fc4.png)

Could someone please fix them?
@JIMENOFONSECA @gabriel-happle @BhargavaKrishnaSreepathi @shanshanhsieh @martin-mosteiro @shizhongming

**Comment by JIMENOFONSECA** [comment]
on it

**Comment by JIMENOFONSECA** [comment]
@amraladdin done

**Comment by amraladdin** [comment]
Super!
