### ISSUE TITLE
Update of cea module documentation

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#1272]
found out much of the documentation was being omitted due to a bad initial build.
might be important to note the following execution when building api using sphinx-apidoc:

sphinx-apidoc -fMeT ../cea -o modules

this rewrites the documentation into the docs/modules dir and creates a new rst for each module, without a module contents toctree at the end

**Comment by daren-thomas** [comment]
hey @Jack-Hawthorne could you put that command into a batch file to be run in future? keep it in the `docs` folder or something?

**Comment by Jack-Hawthorne** [comment]
@daren-thomas  the only problem is that it creates new untracked files everytime a make command is run from docs. This really clogs up a git branch with around 250 new files, making change tracking pretty messy. Are you sure this is advantageous?

**Comment by daren-thomas** [comment]
@Jack-Hawthorne let's have a look at this together next time you're in the office, ok?

**Comment by Jack-Hawthorne** [comment]
@daren-thomas ok, so the plan is to address each documentation build error as its own issue, then build new rst files in the API debug branch (which also contains an updated docs config file) once everything is update (or as much as i can do). 

Does this sound like a good approach?

If so i will close this issue and we will have module by module issues and branches through which i can update/fix and then ask the writers to approve the documentation added.

This is a good way to track my progress as well, i will push module branch once the documentation is completed.

**Comment by daren-thomas** [comment]
nope, this creates a sort of "going dark" mode... specifically, having one branch to fix all the issues... better to fix each in it's own branch. you can do as many pull requests as you like, you know. especially if they are small ones - we can easily just merge them then. if you create one mega-branch parallel to master and work on that over a long period of time, you will diverge and merging will be a lot harder. try to create a pull request per work session.

**Comment by daren-thomas** [comment]
We decided to create separate issues for each module that breaks the sphinx build.
