### ISSUE TITLE
CEA Validation only partially moved to new repository

### ISSUE THREAD

**Issue by roglen** [architecture-building-systems/CityEnergyAnalyst#1282]
Due to the large volume of validation files for the thermal network matrix a new repository several months ago and validation files are being added there. 
This makes the existing 'thermal_networks' folder in the `CityEnergyAnalyst\validation` repository redundant. 
I believe we should move all of the validation files to the `cea-validation` repository. 

Question: Would this add a huge amount of deleted lines to someone? Trying to avoid giving myself a million deleted lines or so (.. done that before).

**Comment by daren-thomas** [comment]
@JIMENOFONSECA do you have an opinion on this? I don't really care too much about the deleted lines myself, but I think you had some valid points on why this might be a problem.

**Comment by JIMENOFONSECA** [comment]
HI all, I think that deleting the validation files is OK, we are basically counting authorship depending  the number of lines added to master. So as long as we do not change that. This should be ok. @daren-thomas are you ok with this too?

**Comment by daren-thomas** [comment]
sure! deleting code is one of the best things you can do for a project! (seriously! let's get rid of as much dead wood as possible!)

**Comment by JIMENOFONSECA** [comment]
Closing as we moved all validation to a separate repository
