### ISSUE TITLE
Arcgis plotting interface: "solar-potentials" is a confusing name

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1290]
"solar-potentials" plotting creates files named "solar-radiation". Maybe we can rename the plotting function to "solar-radiation" as well?
After all, it visualizes the results of the "solar radiation" script.

what does @JIMENOFONSECA think?
Can I assign this issue to @daren-thomas?

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle I agree, it makes sense
