### ISSUE TITLE
ArcGIS Interface Heatmaps not working

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1291]
There is an ArcGIS python error when trying to run the `heatmaps` tool in ArcGIS.

![image](https://user-images.githubusercontent.com/17002288/39909440-69d0ee72-5525-11e8-8a0c-3b31ab7a97b8.png)

@JIMENOFONSECA @amraladdin are we planning to use this feature in the executive course?
@daren-thomas can I assign this issue to you?

**Comment by amraladdin** [comment]
Hey Gabriel, thanks for spotting this...

In my opinion, it would be nice to have it, but it's not a priority.
So if we're able to fix the error quickly, that's perfect, if not, we will have to find a way to show them what can be done with the heatmaps tool without actually using it. @JIMENOFONSECA what do you think?

**Comment by JIMENOFONSECA** [comment]
mm it is tricky. I think is good for visualisation, but if there are other better ways to show more tangible results I will use them.

If it is something good to have in CEA I would opt for fixing it.

On 11 May 2018, 3:16 PM +0800, Amr Elesawy <notifications@github.com>, wrote:

Hey Gabriel, thanks for spotting this...

In my opinion, it would be nice to have it, but it's not a priority.
So if we're able to fix the error quickly, that's perfect, if not, we will have to find a way to show them what can be done with the heatmaps tool without actually using it. @JIMENOFONSECA<https://github.com/JIMENOFONSECA> what do you think?

**Comment by gabriel-happle** [comment]
I still have this issue with my interface.
However, I can generate heatmaps from Pycharm.
seems to be some ArcGIS python related issue.
The interface window already shows errors on opening.
![image](https://user-images.githubusercontent.com/17002288/40467107-210c50d8-5f5b-11e8-87bc-643df3acc7a3.png)

**Comment by daren-thomas** [comment]
@gabriel-happle it works on my machine...

- can you tell me what version of arcgis you are running?

best,
daren

**Comment by daren-thomas** [comment]
@gabriel-happle I have received access to one of the computers nigel is preparing and will check there to see if i can reproduce this error.

**Comment by daren-thomas** [comment]
@gabriel-happle I was able to reproduce this error on a computer (imac with bootcamp?) supplied by Nigel. investigating.

**Comment by daren-thomas** [comment]
ugh! now, after playing around a bit, it suddenly works. @gabriel-happle can you confirm that the heatmaps interface is still not working for you? can you `cea install-toolbox` on master? also... if that doesn't work, i'd love to teamviewer into your machine...

**Comment by gabriel-happle** [comment]
Hey @daren-thomas I still have the same error.
Maybe it has to do with my licenses. For some reason I'm one of the few people here in Singapore that can run ArcGIS without VPN. (?)
We can do teamviewer when you have time. I'm back in the office now.

**Comment by daren-thomas** [comment]
@gabriel-happle, @shanshanhsieh this issue can be resolved by the following steps:

- uninstall Anaconda (sorry. this takes forever)
- re-install Anaconda (UNCHECK "Register Anaconda as default Python")
- conda env create
- pip install -e .[dev]
- cea install-toolbox

It is now working on @gabriel-happle 's computer.

**Comment by JIMENOFONSECA** [comment]
Can we add this to the installation guide?, maybe it was done so already.

On 7 Jun 2018, 6:07 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@gabriel-happle<https://github.com/gabriel-happle>, @shanshanhsieh<https://github.com/shanshanhsieh> this issue can be resolved by the following steps:

  *   uninstall Anaconda (sorry. this takes forever)
  *   re-install Anaconda (UNCHECK "Register Anaconda as default Python")
  *   conda env create
  *   pip install -e .[dev]
  *   cea install-toolbox

It is now working on @gabriel-happle<https://github.com/gabriel-happle> 's computer.

**Comment by daren-thomas** [comment]
yes, the installation guide now contains the relevant instruction.

@gabriel-happle in future, alongside the screenshot, an actual textual representation of the error (for instance using the triple-back-tick formatting) will help future user's find the solution.
