### ISSUE TITLE
ArcGIS interface: Single building plots not possible

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1292]
The field in the ArcGIS interface to input single buildings for plotting is not "active", i.e., single building plots can not be created via ArcGIS.

![image](https://user-images.githubusercontent.com/17002288/39909921-76eb0faa-5527-11e8-8ef2-3a518e0d4260.png)

@daren-thomas can I assign this issue to you?

**Comment by gabriel-happle** [comment]
duplicate of #1222

**Comment by daren-thomas** [comment]
fixed in PR #1324, closing this issue as a duplicate
