### ISSUE TITLE
Create a glossary for the CEA Executive Course

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1296]
Create a glossary that contains:
- Create a table with the common terminology/definitions used in the CEA Executive Course and the urban energy domain.
- Create/update a variables list and their meaning, so we can print it and provide the attendees with it.

Make sure to agree with @daren-thomas on the correct hierarchical organization of the document.

**Comment by JIMENOFONSECA** [comment]
btw, there is one table already in the executive channel in slack

**Comment by shanshanhsieh** [comment]
https://docs.google.com/spreadsheets/d/149Ugw8BfKI_2wMzOrHHVN3D8pOff29eQIzWg8y9Qy9k/edit#gid=0

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne I just added you. As discuss the table of variables and potential glossary are top priorities and should be ready for the 15th of June. This day we start to create a booklet (print it) with all presentations and the glossary, variables of CEA
