### ISSUE TITLE
disconnected building calculation - boiler out of range

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1300]
This is the error message when running decentralized building from ArcGIS toolbox

![image](https://user-images.githubusercontent.com/16998305/39975787-36e1a3f4-5763-11e8-888f-ac3c8a6cde76.png)

**Comment by shanshanhsieh** [comment]
basically, the boiler model does not support temperature higher than 100 C, i will implement another boiler model with higher supply temperature

**Comment by BhargavaKrishnaSreepathi** [comment]
fixed in #1358. Thank you shanshan for the amazing work :)
