### ISSUE TITLE
bug error when building does not have cooling or heating in optimization

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1305]
to replicate error run open case for the district heating case. it breaks in the optimization main step.

I think it is in 'B06' which is a parking lot without heating or cooling.

![image](https://user-images.githubusercontent.com/8973186/40035600-0efdee88-5835-11e8-8ea2-c23e4ca4c3a5.png)

**Comment by BhargavaKrishnaSreepathi** [comment]
@JIMENOFONSECA: is it on the Master branch?

**Comment by JIMENOFONSECA** [comment]
yep

Kind regards,

Dr. Jimeno A. Fonseca
Senior Researcher and Project Coordinator
Multi-Scale Energy Systems for Low-Carbon Cities (MuSES)
Future Cities Laboratory
Singapore ETH-Centre

Chair of Architecture and Building Systems
Institute of Technology in Architecture
ETH Zurich

Scientific Advisory Committee
Energy and Sustainability 2017

On 15 May 2018, 1:17 PM +0800, Bhargava Krishna Sreepathi <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA>: is it on the Master branch?

**Comment by BhargavaKrishnaSreepathi** [comment]
fixed in PR #1334
