### ISSUE TITLE
As a Researcher I want to define multiple dashboards to analyze my data

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1307]
This should include the following features:

- add new dashboard to the navigation menu (with custom name)
- add plots to a dashboard (above / below existing plots)
  - hierarchy: plot category / plot name / plot parameters / scenario(s)
  - OR: Wizard?? say... the settings wrench top right of plots opens the wizard for defining plot properties
- remove plots
- change position of plots relative to other plots in dashboard
- default standard issue dashboard

Question: at what level do we store dashboard configuration? Answer: at project level. Note: two sub levels: urban scenario, infrastructure scenario.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA i think it would be cool to show off top 5 plots here. Which ones are these?

**Comment by JIMENOFONSECA** [comment]
@shizhongming @shanshanhsieh @martin-mosteiro @BhargavaKrishnaSreepathi @Khayatian @belloj88 @roglen @ongbolie @JIMENOFONSECA

**Comment by daren-thomas** [comment]
@JIMENOFONSECA let's use this issue as the minimal set of plots to provide for dashboard editor feature.

**Comment by daren-thomas** [comment]
Default plots to show for new dashboard:

- demand/load-curve-suppply
- supply_system/map_chart.py
