### ISSUE TITLE
Add file/folder selection dialogs to the dashboard interface for scenario / weather file selection

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1309]
In the Project page of the dashboard, a file selection dialog should allow the user to navigate to the weather file to use. Also, a folder selection dialog should allow the user to navigate to the scenario to use.

Add these selection dialogs also to any `FileParameter` and `PathParameter` parameters for the tools section of the dashboard.

Maybe create a "weather file selection" thing like used in ArcGIS (a hybrid between dropdown for built-in weather files and file selection dialog for user-provided files)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I have no idea what this means. Closing as not reproducible.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas sorry, this is one of the issues concerning the new CEA interface. It consists in making possible that the user can select the project or the weather file from a folder-dialog. At the moment, the user needs to write the name of the sceanrio

**Comment by daren-thomas** [comment]
@JIMENOFONSECA ok, thank you. I think now I understand. I'm renaming the issue to reflect what I think you meant.
