### ISSUE TITLE
Improve model for direct fired double-effect absorption chiller

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1325]
The current model in CEA for direct fired double-effect absorption chiller is composed of one double-effect absorption chiller and a gas burner. 

During operation, the heat sources are either produced by evacuated tube solar collectors or gas burners, similar examples are seen in literature:
https://www.sciencedirect.com/science/article/pii/S1359431104001255#FIG1
https://www.sciencedirect.com/science/article/pii/S0038092X10002033#sec1
https://www.sciencedirect.com/science/article/pii/S0960148104000424#TBL6
http://www.maya-airconditioning.com/eng/pdf/chmg/CH-MGCE%20CH1%209-1(EN).pdf

The model for gas burner is a duplicate of gas boiler at the moment.
Possible improvement measures are either:
1. find a better gas burner model (which consider flame temperature and the heat exchanger)
2. make a new model for direct-fired double-effect absorption chiller

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
