### ISSUE TITLE
Testing Surrogate accuracy

### ISSUE THREAD

**Issue by Khayatian** [architecture-building-systems/CityEnergyAnalyst#1327]
defining the overhead uncertainty of the surrogate

**Comment by JIMENOFONSECA** [comment]
@Khayatian I wonder if you have any updates on this. It would be great if you can help us to clean the issues that exist.

**Comment by JIMENOFONSECA** [comment]
@Khayatian we close this issue since there is no further development expected until the end of this phase of the project (March 2019)
