### ISSUE TITLE
heating and cooling season

### ISSUE THREAD

**Issue by Khayatian** [architecture-building-systems/CityEnergyAnalyst#1328]
fixing the heating and cooling season connection in the input_matrix.py file. The calling variables should be updated according the latest CEA features.

**Comment by daren-thomas** [comment]
@Khayatian can you explain this issue please?

**Comment by Khayatian** [comment]
@daren-thomas when preparing the input features for training a neural network, the start and end of heating and cooling seasons corresponds to the availability of the heating and cooling system. As the surrogate model was written for Singapore's climate, there was no heating required, therefore the cooling system was always available. However, for other climates, the start and end of the heating and cooling season should be translated to a vector [heating setpoint, cooling setpoint] for each hour of the year. For instance, in cooling season, during each hour of that period, the vector reads [-99,26]. While for every hour of the mid season (both heating and cooling systems are off), the vector reads [-99,99]. Since the indoor temperature never exceeds the supremum and infimum, the heating and cooling systems will never kick in during the mid-season, and that is how we translated it as input features of the neural net.

**Comment by daren-thomas** [comment]
since the way our data is structured with vectors of length (HOURS_IN_YEAR), how about four variables:

- heating_setpoint_lower_bound
- heating_setpoint_upper_bound
- cooling_setpoint_lower_bound
- cooling_setpoint_upper_bound

and instead of using -99 / +99, we could use `NaN` to indicate that it isn't season.

what do you think? @Khayatian? @gabriel-happle?

(and then create this data during the `BuildingPropertiesRow` creation or something...)

**Comment by Khayatian** [comment]
Since I have been lately distant from the latest CEA code, I am unsure whether there was two different vectors for (1) system availability, and (2) the setpoint (as far as I remember, this is how some software like EnergyPlus work, where system availability is Boolean [NaN,1] and setpoint is a float). It mainly comes into play when there are some national/regional/cantonal regulations for switching on the heating system (e.g. 15 Oct in Milan). Actually, @daren-thomas suggestion for the setpoint and setback temperature is very close to what @JIMENOFONSECA prepared as an input vector for the Neural Network, i.e. a single vector composed of setpoint and setback temperatures for every hour of the year (8760), yet, we used +99 (cooling) and -99 (heating) for system unavailability, cause neural networks don't treat NaN well as a general rule. 
I am aware that the surrogate model may not be currently a priority, so please feel free to treat the aforementioned comments as a recommendation rather than a necessity.
