### ISSUE TITLE
Solar potential - PVT panels fail to run

### ISSUE THREAD

**Issue by ongbolie** [architecture-building-systems/CityEnergyAnalyst#1329]
**Mix-low density scenario** 

Error from running PVT panels :

```
Executing: PhotovoltaicThermalPanelsTool C:\Users\Admin\Desktop\reference-case-WTP\MIX_low_density Singapore-2016 c:\Users\Admin\documents\GitHub\cityenergyanalyst\cea\databases\weather\Singapore-2016.epw 1/1/2016 PV1 SC1 true false 0.75 4 35 200 1.3 1000 0.6 0.217
Start Time: Wed May 16 14:26:18 2018
Running script PhotovoltaicThermalPanelsTool...
Executing: c:\users\admin\anaconda3\envs\cea\python.exe -u -m cea.interfaces.cli.cli photovoltaic-thermal --panel-on-roof true --eff-pumping 0.6 --t-in-pvt 35.0 --scenario C:\Users\Admin\Desktop\reference-case-WTP\MIX_low_density --type-pvpanel PV1 --solar-window-solstice 4 --type-scpanel SC1 --fcr 1.3 --k-msc-max 0.217 --weather c:\users\admin\documents\github\cityenergyanalyst\cea\databases\weather\Singapore-2016.epw --panel-on-wall false --date-start 2016-01-01 --ro 1e+03 --dpl 200.0 --min-radiation 0.75
Running photovoltaic-thermal with scenario = C:\Users\Admin\Desktop\reference-case-WTP\MIX_low_density
Running photovoltaic-thermal with date-start = 2016-01-01 00:00:00
Running photovoltaic-thermal with dpl = 200.0
Running photovoltaic-thermal with eff-pumping = 0.6
Running photovoltaic-thermal with fcr = 1.3
Running photovoltaic-thermal with k-msc-max = 0.217
Running photovoltaic-thermal with min-radiation = 0.75
Running photovoltaic-thermal with panel-on-roof = True
Running photovoltaic-thermal with panel-on-wall = False
Running photovoltaic-thermal with ro = 1000.0
Running photovoltaic-thermal with solar-window-solstice = 4
Running photovoltaic-thermal with t-in-pvt = 35.0
Running photovoltaic-thermal with t-in-sc = 75.0
Running photovoltaic-thermal with type-pvpanel = PV1
Running photovoltaic-thermal with type-scpanel = SC1
reading weather data done
calculating solar properties done
gathering properties of PVT collector panel
filtering low potential sensor points done
calculating optimal tile angle and separation done
generating groups of sensor points done
Building B001 done - time elapsed: 42.7199962123  seconds
reading weather data done
calculating solar properties done
gathering properties of PVT collector panel
filtering low potential sensor points done
GB not in expected range
GB not in expected range
GB not in expected range
c:\users\admin\documents\github\cityenergyanalyst\cea\utilities\solar_equations.py:229: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  sensors_rad_clean[sensors_rad_clean[:] <= 50] = 0  # eliminate points when hourly production < 50 W/m2
c:\users\admin\anaconda3\envs\cea\lib\site-packages\pandas\core\frame.py:2366: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._where(-key, value, inplace=True)
c:\users\admin\documents\github\cityenergyanalyst\cea\technologies\solar\solar_collector.py:560: RuntimeWarning: overflow encountered in multiply
  1]  # heat production from solar collector, eq.(5)
c:\users\admin\documents\github\cityenergyanalyst\cea\technologies\solar\solar_collector.py:569: RuntimeWarning: overflow encountered in multiply
  Tout = Tfl[1] + (qgain_Whperm2 * delts) / C_eff  # eq.(8)
c:\users\admin\documents\github\cityenergyanalyst\cea\technologies\solar\solar_collector.py:560: RuntimeWarning: invalid value encountered in subtract
  1]  # heat production from solar collector, eq.(5)
c:\users\admin\documents\github\cityenergyanalyst\cea\technologies\solar\solar_collector.py:574: RuntimeWarning: invalid value encountered in less
  if abs(qdiff < 0.1):
c:\users\admin\documents\github\cityenergyanalyst\cea\technologies\solar\photovoltaic_thermal.py:453: RuntimeWarning: invalid value encountered in greater
  if abs(q_balance_error) > 1:
Traceback (most recent call last):
  File "c:\users\admin\anaconda3\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\admin\anaconda3\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\admin\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 79, in <module>
    main(cea.config.Configuration())
  File "c:\users\admin\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 33, in main
    script_module.main(config)
  File "c:\users\admin\documents\github\cityenergyanalyst\cea\technologies\solar\photovoltaic_thermal.py", line 615, in main
    latitude=latitude, longitude=longitude, weather_path=config.weather, building_name=building)
  File "c:\users\admin\documents\github\cityenergyanalyst\cea\technologies\solar\photovoltaic_thermal.py", line 93, in calc_PVT
    max_yearly_radiation, panel_properties_PV)
  File "c:\users\admin\documents\github\cityenergyanalyst\cea\utilities\solar_equations.py", line 306, in optimal_angle_and_tilt
    sensors_metadata_clean.total_rad_Whm2, Max_Isol_Whperm2yr)
  File "c:\users\admin\anaconda3\envs\cea\lib\site-packages\numpy\lib\function_base.py", line 2734, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "c:\users\admin\anaconda3\envs\cea\lib\site-packages\numpy\lib\function_base.py", line 2816, in _vectorize_call
    for x, t in zip(outputs, otypes)])
TypeError: long() argument must be a string or a number, not 'NoneType'


Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 68, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\Admin\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 155, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (PhotovoltaicThermalPanelsTool).

```

**Comment by amraladdin** [comment]
Here's the error I get when running the PVT component:
Executing: PhotovoltaicThermalPanelsTool C:\reference-case\reference-case-WTP\RES_low_density Singapore-2016 c:\Users\aelesawy\documents\GitHub\cityenergyanalyst\cea\databases\weather\Singapore-2016.epw 01.01.2016 PV1 SC1 true true 0.75 4 35 200 1.3 1000 0.6 0.217
Start Time: Wed May 16 12:54:49 2018
Running script PhotovoltaicThermalPanelsTool...
Executing: C:\ProgramData\Miniconda2\envs\cea\python.exe -u -m cea.interfaces.cli.cli photovoltaic-thermal --panel-on-roof true --eff-pumping 0.6 --t-in-pvt 35.0 --scenario C:\reference-case\reference-case-WTP\RES_low_density --type-pvpanel PV1 --solar-window-solstice 4 --type-scpanel SC1 --fcr 1.3 --k-msc-max 0.217 --weather c:\users\aelesawy\documents\github\cityenergyanalyst\cea\databases\weather\Singapore-2016.epw --panel-on-wall true --date-start 2016-01-01 --ro 1e+03 --dpl 200.0 --min-radiation 0.75
Running photovoltaic-thermal with scenario = C:\reference-case\reference-case-WTP\RES_low_density
Running photovoltaic-thermal with date-start = 2016-01-01 00:00:00
Running photovoltaic-thermal with dpl = 200.0
Running photovoltaic-thermal with eff-pumping = 0.6
Running photovoltaic-thermal with fcr = 1.3
Running photovoltaic-thermal with k-msc-max = 0.217
Running photovoltaic-thermal with min-radiation = 0.75
Running photovoltaic-thermal with panel-on-roof = True
Running photovoltaic-thermal with panel-on-wall = True
Running photovoltaic-thermal with ro = 1000.0
Running photovoltaic-thermal with solar-window-solstice = 4
Running photovoltaic-thermal with t-in-pvt = 35.0
Running photovoltaic-thermal with t-in-sc = 75.0
Running photovoltaic-thermal with type-pvpanel = PV1
Running photovoltaic-thermal with type-scpanel = SC1
reading weather data done
calculating solar properties done
gathering properties of PVT collector panel
filtering low potential sensor points done
calculating optimal tile angle and separation done
generating groups of sensor points done
Building B001 done - time elapsed: 32.5211855299  seconds
reading weather data done
calculating solar properties done
gathering properties of PVT collector panel
filtering low potential sensor points done
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
c:\users\aelesawy\documents\github\cityenergyanalyst\cea\utilities\solar_equations.py:229: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  sensors_rad_clean[sensors_rad_clean[:] <= 50] = 0  # eliminate points when hourly production < 50 W/m2
C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py:2366: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._where(-key, value, inplace=True)
c:\users\aelesawy\documents\github\cityenergyanalyst\cea\technologies\solar\solar_collector.py:560: RuntimeWarning: overflow encountered in multiply
  1]  # heat production from solar collector, eq.(5)
c:\users\aelesawy\documents\github\cityenergyanalyst\cea\technologies\solar\solar_collector.py:569: RuntimeWarning: overflow encountered in multiply
  Tout = Tfl[1] + (qgain_Whperm2 * delts) / C_eff  # eq.(8)
c:\users\aelesawy\documents\github\cityenergyanalyst\cea\technologies\solar\solar_collector.py:560: RuntimeWarning: invalid value encountered in subtract
  1]  # heat production from solar collector, eq.(5)
c:\users\aelesawy\documents\github\cityenergyanalyst\cea\technologies\solar\solar_collector.py:574: RuntimeWarning: invalid value encountered in less
  if abs(qdiff < 0.1):
c:\users\aelesawy\documents\github\cityenergyanalyst\cea\technologies\solar\photovoltaic_thermal.py:453: RuntimeWarning: invalid value encountered in greater
  if abs(q_balance_error) > 1:
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 79, in <module>
    main(cea.config.Configuration())
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 33, in main
    script_module.main(config)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\technologies\solar\photovoltaic_thermal.py", line 615, in main
    latitude=latitude, longitude=longitude, weather_path=config.weather, building_name=building)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\technologies\solar\photovoltaic_thermal.py", line 93, in calc_PVT
    max_yearly_radiation, panel_properties_PV)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\utilities\solar_equations.py", line 306, in optimal_angle_and_tilt
    sensors_metadata_clean.total_rad_Whm2, Max_Isol_Whperm2yr)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\numpy\lib\function_base.py", line 2734, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\numpy\lib\function_base.py", line 2816, in _vectorize_call
    for x, t in zip(outputs, otypes)])
TypeError: long() argument must be a string or a number, not 'NoneType'


Traceback (most recent call last):
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 68, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 155, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (PhotovoltaicThermalPanelsTool).
Failed at Wed May 16 12:55:24 2018 (Elapsed Time: 35.02 seconds)

**Comment by amraladdin** [comment]
Here're the first lines of my cea.config:
...
[general]
scenario = C:\reference-case\reference-case-WTP\RES_low_density
region = SIN
weather = Singapore-2016
multiprocessing = true
