### ISSUE TITLE
Executive course exercises

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1330]
Since we will be doing the exercises being prepared for the executive course, we need to have these asap so we can prepare for the test run. So to the people in charge of the exercises (namely, @amraladdin , @martin-mosteiro, @gabriel-happle, @shanshanhsieh) please provide us with the following information about your exercise:
    - description of the exercise
    - checklist (walkthrough of how they expect to explain the exercise)
    - what scenarios they will run
    - what are the expected results
    - how will they visualize the results

**Comment by martin-mosteiro** [comment]
@gabriel-happle Thanks for creating the issue and the exercise.
@shanshanhsieh This made me think of one more point: since me and Amr are still not very familiar with the supply tools either, in addition to the exercise it would be good to have a brief description of what you will be showing students in both of your live demonstrations (L7E). Just to have an idea what we should show them before the exercise as well. Something like "run the solar photovoltaic potential for PV1; run thermal networks; show results" would be a good direction already.

**Comment by shanshanhsieh** [comment]
@martin-mosteiro 
Here is the outline of LD7 & E2: https://docs.google.com/document/d/1zsUYLlsEjzx5_81s_BkXGFj0J9JKzLpyesVV2jKj1Io/edit
Please feel free to modify and comment in the document : )

**Comment by martin-mosteiro** [comment]
Will do - thanks @shanshanhsieh!

**Comment by martin-mosteiro** [comment]
@shanshanhsieh Thanks again for the exercise. It's very clear and well described step-by-step. I like the learning objectives for the first exercise a lot. The other two exercises, however, don't have such a clear learning objective to me - seems like they'll just run different technologies and see which performs best. Is there any further takeaway message from these? e.g. maybe they can see whether solar collectors make sense with some occupancy types but not with others (i.e., make sense on residential buildings but not on office buildings)?

**Comment by martin-mosteiro** [comment]
Also, @shanshanhsieh since we will have the SC results pre-simulated for them, exercise 3 will not take much time. Any chance we could run a thermal network exercise? Or is there a sewage network exercise that we can do in a relatively short period of time?

**Comment by shanshanhsieh** [comment]
@martin-mosteiro here are the answers
1. Exercise 2: 
a) another objective is to introduce the database, and know what parameters are required for simulation. In the future, they can use the script to evaluate different technologies, this will be possible.
b) great idea to give some first intuition with the results from solar technology and demand simulation (see google doc for update)
2. indeed, Exercise 3 will not be needed since SC2 is presimulated
3. In E3, the exercise is changed to supply system simulation, which will not take place this time since the tool is not ready yet. We are probably not doing network simulation in the executive course due to time constraint.

**Comment by martin-mosteiro** [comment]
@shanshanhsieh Post-test run feedback:
Exercise 1: Worked really well! We actually had someone ask what the threshold value was during the live demonstration, so it was a good exercise to have.
Exercise 2: This one was maybe a bit too simple for our participants, who were mostly engineers with a background in energy and buildings. Nonetheless, it was nice to hear someone say "PV2 is a disaster" before she ran PV3, and to have someone else ask why you would ever use PV3.
Exercise 3: We did not do this exercise due to lack of time. In hindsight, I would have rather done Exerce 3 instead of Exercise 2 since it was the one exercise we had were we connected demand and supply.
All in all a very successful exercise session nonetheless! Thanks for preparing these!

**Comment by martin-mosteiro** [comment]
That being said - we attempted to have an impromptu live demonstration of the thermal networks simulation and the plots did not work. I am not sure if this is a known issue @shanshanhsieh and @roglen, otherwise I'll create a new issue today.

**Comment by roglen** [comment]
@martin-mosteiro please create an issue, i'll have a look. As far as I am aware they should be working.

**Comment by martin-mosteiro** [comment]
@roglen actually, it seems I already did :) #1402
👍 to me from last Friday for following protocol
👎 to present day me for assuming I hadn't followed protocol
