### ISSUE TITLE
Changing functionality to create energy demand plots of individual buildings

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1336]
Hi @JIMENOFONSECA 
I wonder if we should change the way the individual building and district plotting for the energy demand works.
Right now we either create plots for a single building if only `1` building name is provided to be plotted.
If `None` or a `list` of building names is provided, we ignore it and create the district energy demand plots.

Maybe it is better to plot each individual plot for the buildings provided in the `list` and print the district plots as well in any case.

E.g., Now selecting `B001, B003, B005` in the ArcGIS interface or config file creates `0` individual building outputs and **only** the district output.
Intended behavior will be `3` individual building outputs **plus** the district output.

**Comment by JIMENOFONSECA** [comment]
Yes, that could work too. I will leave it low priority for now though. What do you think?

Kind regards,

Dr. Jimeno A. Fonseca
Senior Researcher and Project Coordinator
Multi-Scale Energy Systems for Low-Carbon Cities (MuSES)
Future Cities Laboratory
Singapore ETH-Centre

Chair of Architecture and Building Systems
Institute of Technology in Architecture
ETH Zurich

Scientific Advisory Committee
Energy and Sustainability 2017

On 16 May 2018, 21:48 +0800, Gabriel Happle <notifications@github.com>, wrote:

Hi @JIMENOFONSECA<https://github.com/JIMENOFONSECA>
I wonder if we should change the way the individual building and district plotting for the energy demand works.
Right now we either create plots for a single building if only 1 building name is provided to be plotted.
If None or a list of building names is provided, we ignore it and create the district energy demand plots.

Maybe it is better to plot each individual plot for the buildings provided in the list and print the district plots as well in any case.

**Comment by gabriel-happle** [comment]
see `cea/plots/demand/main.py`

```
    def peak_load(self):
        title = "Peak Load" + self.plot_title_tail
        output_path = self.locator.get_timeseries_plots_file(self.plot_output_path_header + '_peak_load')
        analysis_fields = ["E0_kW", "Qhs0_kW", "Qww0_kW", "Qcs0_kW"]
        data = self.data_processed['yearly_loads'].copy()
        if len(self.buildings) == 1:
            data = data.set_index("Name").ix[self.buildings[0]]
            plot = peak_load_building(data, analysis_fields, title, output_path)
        else:
            plot = peak_load_district(data, analysis_fields, title, output_path)
        return plot
```

etc.

**Comment by JIMENOFONSECA** [comment]
1 year here, we will not have it anytime soon. Closing it.
