### ISSUE TITLE
Qwwf does not match mcpwwf*(Tsupwwf-Tretwwf) in Demand files

### ISSUE THREAD

**Issue by roglen** [architecture-building-systems/CityEnergyAnalyst#1337]
Energy Balance in Demand files of the open case for `wwf` do not add up. 

The way I understand it, per definition, `Qwwf = mcpwwf * (Tsupwwf-Tretwwf)`.

This does not apply in the open case for DH, checked for B02 and B03.

This causes a wrong output of heating demands and distorts results in `thermal_network_matrix.py`

[B03_error.xlsx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2011373/B03_error.xlsx)

**Comment by roglen** [comment]
@shanshanhsieh @gabriel-happle not really sure who this applies to, issue #66 is not directly related to this as far as I can tell.

**Comment by gabriel-happle** [comment]
The reason for this is that `mcpwwf` is calculated between `Tww_tank - Tww_re` in `calc_Qwwf()` in `hotwater_loads.py`.
@shanshanhsieh is taking over from here.

The issue is not critical for the Singapore case, as there is no district heating network planned.

**Comment by JIMENOFONSECA** [comment]
@roglen I included a fix in the branch i1289. could you tell me if this fixes the issue?
you have to rerun the demand_main.py

**Comment by roglen** [comment]
@JIMENOFONSECA looks good now! 
There are still some small deviations, but now they are around 0.1% which I think is reasonable.

**Comment by JIMENOFONSECA** [comment]
Yep, it is a rounding error I believe.

Jimeno
________________________________
