### ISSUE TITLE
Jenkins test for looped networks

### ISSUE THREAD

**Issue by roglen** [architecture-building-systems/CityEnergyAnalyst#1339]
Currently there are large parts of the `thermal_network_matrix.py` which are not being tested because they only apply for looped networks.

We now have an option of creating looped network files in CEA from the config file under the section of `Network Layout`. It can be turned on and off using the `allow_looped_networks` flag. 

Setting this flag to 'True' and running the 'Network Layout' script would allow us to test CEA for looped networks using Jenkins.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh is this still the case?

**Comment by shanshanhsieh** [comment]
Yes, because the case we run the dodo test (`reference-case-open`) does not have a loop network, 
To make this happen, we will first need to set up another dodo test with other case studies (preferably region = SG)

**Comment by JIMENOFONSECA** [comment]
1.5 years in here, we will not have it anytime soon. Closing it.
