### ISSUE TITLE
Executive course demand forecasting exercise

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1340]
@martin-mosteiro and @amraladdin 
Please find the draft for the demand forecasting exercise attached and give some feedback.

@shanshanhsieh @shizhongming @BhargavaKrishnaSreepathi @JIMENOFONSECA @roglen @ongbolie you are also welcome to take a look and give feedback.

[DRAFT_CEA_Exercise_Demand.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2011864/DRAFT_CEA_Exercise_Demand.docx)

**Comment by martin-mosteiro** [comment]
@gabriel-happle Thanks, that looks great. Looks very detailed and well-developed. I haven't been able to read through it yet, so I'll try to give you more detailed feedback soon.

**Comment by martin-mosteiro** [comment]
@gabriel-happle Excellent job, really. Your exercise is very clear and well-defined, easy to follow and specified learning objectives. I think it is perfect as-is, really. I have edited the Word document to create a handout (removing the things the students should take away from the exercises). If you don't mind, I would just use this document as a handout tomorrow at the course.
Really, really good job.

**Comment by martin-mosteiro** [comment]
@gabriel-happle Here's the edited-down version for the handout. Feel free to veto it being distributed if you'd rather not. We'll probably only get to do exercises 1 and 2, but exercise 3 could be a homework exercise for those who are excited to keep trying stuff out ;)
[20180524_CEA_Exercise_Demand.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2032888/20180524_CEA_Exercise_Demand.docx)

**Comment by gabriel-happle** [comment]
looks good. thanks @martin-mosteiro.
Please let me know the feedback of the participants for the final version of the executive course.

**Comment by martin-mosteiro** [comment]
@gabriel-happle Will do!

**Comment by martin-mosteiro** [comment]
Following on point 2 above: buildings had a higher cooling demand for the case with low window to wall ratio than for the case with high window to wall ratio:
![capture](https://user-images.githubusercontent.com/18548065/40542869-3e6d8742-6022-11e8-8191-954216fd9c9a.png)

**Comment by martin-mosteiro** [comment]
They did (these are graphs generated by workshop participants).

**Comment by JIMENOFONSECA** [comment]
Mmm weird...

On 25 May 2018, 20:48 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

They did (these are graphs generated by workshop participants).

**Comment by JIMENOFONSECA** [comment]
Ill have to check it, but it might be a rebound effect of highly insulated walls.

On 25 May 2018, 20:48 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

They did (these are graphs generated by workshop participants).

**Comment by martin-mosteiro** [comment]
One idea that came up during the test run was: perhaps changing the WWR changes the sensor placement for the radiation script such that a sensor gives drastically different results than before?

In any case the decrease in cooling demand is odd as Jimeno said, possibly a consequence of the U-values used when defining the Singaporean office archetype.

Also, please note that the last two graphs I posted was created after deleting B008 from the case study for some testing (so B008 not being there is not an error)
