### ISSUE TITLE
Add multiprocessing and weather file parameter to network interface

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1350]
Thermal network uses multiprocessing and weather file parameters from config.
These parameters are currently not accessible from the ArcGIS interface.

The workaround is to change the config file directly.

@daren-thomas could you help us?
also not sure what milestone to put here.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas and @shanshanhsieh can this be closed?

**Comment by shanshanhsieh** [comment]
yes, these parameters are all shown in the interfaces now thanks to the  `scripts.yml` clean-up by @daren-thomas!
