### ISSUE TITLE
Extract-reference-case tool is missing from the ArcGIS interface

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1351]
The tool "extract-reference-case" has been removed from the ArcGIS interface. This makes it impossible to test-run the CEA without access to the reference-case-open. Is there a specific reason for this?

@JIMENOFONSECA do you have an idea why this was removed?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas should we then leave it as it is?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I don't really think it's good as it is. "We will be supply the user with a reference case" is only thinking as far as the executive course. What about random users that download the tool and want to give it a spin?

**Comment by JIMENOFONSECA** [comment]
I think we can offer a link in the cea manual to download the reference case from github. That could be much cleaner than a tool. What do you think?

On 28 May 2018, 17:34 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> I don't really think it's good as it is. "We will be supply the user with a reference case" is only thinking as far as the executive course. What about random users that download the tool and want to give it a spin?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I like this idea!
