### ISSUE TITLE
Plots: Cannot use scenario comparison

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1353]
I tried to use the "scenarios_comparisons" option in the "Plots" feature (@martin-mosteiro tried as well). We could not choose the different paths to the scenarios. This is because the "Add Value" button doesn't work.

@JIMENOFONSECA sorry for assigning you directly, but this is kind of an emergency.

![image](https://user-images.githubusercontent.com/16256867/40236317-724ca374-5aad-11e8-98ad-dcf13fbab9f9.png)

**Comment by JIMENOFONSECA** [comment]
fixed by Daren
