### ISSUE TITLE
Database copying and "custom" region

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1368]
When running a scenario with region = 'CH' or 'SIN' the archetype databases get copied into the case study, and then if the region needs to be specified as 'custom'.

If, after running the scenario under 'custom', one desires to do LCA calculations, then there'll be an error, because the databases were never copied into the scenario.

@daren-thomas Wouldn't it make more sense for all databases to get copied into the scenario the first time it is run so that if the user then runs a 'custom' scenario based on these databases s/he won't need to copy the files manually from the CEA databases or switch the region back and forth?

**Comment by daren-thomas** [comment]
@martin-mosteiro what if... what if we removed the `custom` region altogether and instead copy each database as needed to the scenario, _unless_ it already exists there. This solves the problem that users need to be able to edit the databases - but we don't want them editing anything inside the cea folders.

(BTW: also remove any mucking around in the cea installation folders during the executive course sessions)

**Comment by martin-mosteiro** [comment]
Sounds like an excellent plan to me!
