### ISSUE TITLE
Aef is hard-coded in CEA

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1374]
Aef is hard-coded into CEA, whereas Af can be modified. However, since the electrical gains are put entirely into the conditioned floor area, if Aef is much bigger than Af the gains will be very substantial.

**Comment by gabriel-happle** [comment]
![image](https://user-images.githubusercontent.com/17002288/40401049-4c8cd62c-5e77-11e8-9fca-58227c43115b.png)

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro now Aef is transformed by E_S a constant = 0.9 Woudl you suggest to make it bigger to avoid this problem?

**Comment by martin-mosteiro** [comment]
I wrote this down in a rush while fixing some issues in the Zurich case study for my presentation yesterday. I don’t think this affects the Singapore case for the course so it’s relatively low priority now. I will look into it on Monday.



Am 23.05.2018 um 10:46 schrieb Jimeno A. Fonseca <notifications@github.com<mailto:notifications@github.com>>:


@martin-mosteiro<https://github.com/martin-mosteiro> now Aef is transformed by E_S a constant = 0.9 Woudl you suggest to make it bigger to avoid this problem?

**Comment by martin-mosteiro** [comment]
@gabriel-happle I agree, but I think we shouldn't change this before the executive course. So let's discuss it in Singapore and assign it there.
