### ISSUE TITLE
BUG: solar radiation plots per building shows wrong percentage values in hovertext

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1375]
see screenshot
`roof` is clearly the highest but shows only as 9%.
I think it's a dataframe sorting issue like in the demand plots.

![image](https://user-images.githubusercontent.com/17002288/40399930-6f60bfc4-5e72-11e8-8f11-f196ee9cf28c.png)

**Comment by JIMENOFONSECA** [comment]
included in fix of branch  i1289
