### ISSUE TITLE
high stagnation temperature for pvt

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1376]
At some instances, the stagnation temperature exceeds the design limits of panels (t_max in the databases).
This reason might be insufficient segments of the hydraulic circuit (Nseg) that are assumed in the simulation.
More research is required to decide the action plan.

more references:
1. Stagnation behaviour of solar thermal systems
https://www.aee-intec.at/0uploads/dateien48.pdf
2. http://www.sunwindenergy.com/content/pushing-stagnation-temperature
3. https://www.volker-quaschning.de/articles/fundamentals4/index.php

**Comment by JIMENOFONSECA** [comment]
1.5 years in here, we will not have it anytime soon. Closing it.
