### ISSUE TITLE
the format in .cpg file has to be ISO-8859-1 

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1377]
After modifying the `.shp` files, they will change the format in `.cpg`
in some cases, it causes error when running the scripts.
after modifying `.shp` files in your case study, always make sure you have **ISO-8859-1** in the `.cpg` (exactly the same format) (special reminder to @martin-mosteiro  and @amraladdin  )

or maybe @JIMENOFONSECA  knows a better solution to this problem?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh right, did you have this error recently? What we tried to do was to make all to that format once we run the new_project tool. did you face this problem recently?

**Comment by shanshanhsieh** [comment]
not from my side, but @amraladdin ran into some errors while testing different geometries.
so, one should always run the `new_project` tool after modifying building geometry?

**Comment by JIMENOFONSECA** [comment]
that should not be the case!
________________________________

**Comment by JIMENOFONSECA** [comment]
@amraladdin fixed, please sync from master
