### ISSUE TITLE
ArcGIS interface: Plotting tool only works if at least one scenario for comparison is selected

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1386]
![image](https://user-images.githubusercontent.com/17002288/40463482-32cb9eb8-5f48-11e8-8f41-a2346fd94601.png)

This is not a critical bug.

**Comment by gabriel-happle** [comment]
duplicate of #1387

**Comment by daren-thomas** [comment]
@JIMENOFONSECA Is there a reason we lumped all plots into the same tool? It seems the cleanest way to fix this one is to split the tools up. If you'd still like them all as one tool, I think I can update the Arcpy parameters in the updateParameterInfo methods.

**Comment by JIMENOFONSECA** [comment]
I will select the option that takes less time and effort on arcgis. I see us moving away from it after the executive course. What do you think?

On 28 May 2018, 17:51 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> Is there a reason we lumped all plots into the same tool? It seems the cleanest way to fix this one is to split the tools up. If you'd still like them all as one tool, I think I can update the Arcpy parameters in the updateParameterInfo methods.

**Comment by daren-thomas** [comment]
sure. i'll look into it.

**Comment by martin-mosteiro** [comment]
This is also true for other values in the plots tool:
![screen shot 2018-05-29 at 13 10 18](https://user-images.githubusercontent.com/18548065/40655552-fb54ccf4-6341-11e8-9455-ec53de218ec0.png)
Issue #1413 covers all of these values being required.

**Comment by daren-thomas** [comment]
updated #1414 to address #1413
