### ISSUE TITLE
ArcGIS plots tools force you to select a scenario to compare to

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1387]
In order to run the plots toolbox, you always need to select a scenario to compare to, even if you are not running scenario comparison. There is a workaround: you can check the box just for the scenario you are running and the plots will work. But it's just an unnecessary nuisance.

**Comment by gabriel-happle** [comment]
@martin-mosteiro check #1386 ;)

**Comment by martin-mosteiro** [comment]
@gabriel-happle Thanks. I'm just quickly jotting down the issues that come up during the test run. Expect more duplicates :)
This issue is closed.
