### ISSUE TITLE
District emissions plot showing the wrong colors

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1388]
This seems to be the same issue that used to happen to every other kind of plot, but it's still happening for district emissions:
<img width="1400" alt="screen shot 2018-05-24 at 11 08 49" src="https://user-images.githubusercontent.com/18548065/40476665-e35fb3f8-5f44-11e8-84fb-60c5ccb6ccdc.png">

**Comment by JIMENOFONSECA** [comment]
This has to do with the version of plotly that you have installed. After updating the issue is solved. did you reinstalled CEA recently?, this should have included the version of plotly compatible with CEA. i.e.,g that included in the enviornmnet.yml file
