### ISSUE TITLE
Region cannot be selected from ArcGIS interface until it's too late

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1391]
Either the "New project" or "Data miner" (aka "Data helper") tool should have an option to select the region to be used and copy the database accordingly. At the moment, the "Data miner" just generates the building properties based on whatever is written in the config file!

**Comment by daren-thomas** [comment]
NOTE: the `create-new-project` script does not use the region at all as far as I can tell, so I have only added it to the `data-helper`.
