### ISSUE TITLE
Changing WWR changes total solar irradiance on buildings

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1418]
This issue is to investigate the behavior described by @martin-mosteiro in #1340 .
In one of the case studies increasing the WWR of a building lowered the overall irradiance onto that geometry.
That behavior is strange and requires some intensive testing.

@JIMENOFONSECA please add your comments here, if you already did some tests.

**Comment by gabriel-happle** [comment]
I had exactly the same idea as you @martin-mosteiro.
That's why I investigated that particular building in terms of sensor placement.
Here is my analysis:

![image](https://user-images.githubusercontent.com/17002288/40706891-abe2e6a2-6421-11e8-9f30-ecf0282454d1.png)

![image](https://user-images.githubusercontent.com/17002288/40706904-b68dfe02-6421-11e8-8cb0-77dbe69d77ef.png)

I conclude, that the default simulation parameters are clearly not good enough!
At least we have to choose the `floors=true` option. With that we can come close to within 5% of the highest resolution I tried.

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA and @shanshanhsieh, (also @shizhongming) this is also interesting for you.
I will make some further tests and also evaluate the simulation time for the whole case study.

**Comment by JIMENOFONSECA** [comment]
Really interesting behavior and great analysis. I wonder how does it change the daily load profile (for the floor case at least)

Kind regards,

Dr. Jimeno A. Fonseca
Senior Researcher and Project Coordinator
Multi-Scale Energy Systems for Low-Carbon Cities (MuSES)
Future Cities Laboratory
Singapore ETH-Centre

Chair of Architecture and Building Systems
Institute of Technology in Architecture
ETH Zurich

Scientific Advisory Committee
Energy and Sustainability 2017

On 30 May 2018, 15:58 +0800, Gabriel Happle <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> and @shanshanhsieh<https://github.com/shanshanhsieh>, (also @shizhongming<https://github.com/shizhongming>) this is also interesting for you.
I will make some further tests and also evaluate the simulation time for the whole case study.

**Comment by gabriel-happle** [comment]
PR #1432 created.
We also need to update all the radiation for all the case studies.
Can you take care of that @JIMENOFONSECA with your fast machine also for the EcoCampus?
Thanks.

**Comment by amraladdin** [comment]
Has this issue been fixed? How will this impact the exercise?

**Comment by martin-mosteiro** [comment]
@amraladdin Yes, @gabriel-happle fixed it with PR #1432. I believe this issue should be closed.

**Comment by gabriel-happle** [comment]
Yep. It should be fixed. However, I actually haven't repeated the exercise with the newest version of case studies and code. That's why I'm keeping it open.
