### ISSUE TITLE
optimization results do not seem accurrate to the Singaporean context

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1423]
Issue 1: 
centralized costs, It seems there are negative values and the bars get juxtaposed.

![image](https://user-images.githubusercontent.com/8973186/40765713-f373881e-64df-11e8-9f09-234d976105d1.png)

![image](https://user-images.githubusercontent.com/8973186/40765732-fb7d3cf8-64df-11e8-917e-859f506335ae.png)

**Comment by BhargavaKrishnaSreepathi** [comment]
I have taken a look at the graphs generated, the CCGT unit generates electricity which is consumed or supplied to the grid. This effectively gives a negative cost to the CCGT. And when the overall costs are calculated this happens. I will try to figure out a better way to show this stacked plot

**Comment by BhargavaKrishnaSreepathi** [comment]
fixed in PR#1468
