### ISSUE TITLE
Distribute the flow of plants so I can find the best configuration

### ISSUE THREAD

**Issue by roglen** [architecture-building-systems/CityEnergyAnalyst#1433]
Currently the mass flow is devided evenly between all plants, this could/should be optimized.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh is this something in the pipeline

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA yes, i would still like to address this issue, it is closely related to WP2 of my thesis.

**Comment by JIMENOFONSECA** [comment]
1.5 years in here, we will not have it anytime soon. Closing it.
