### ISSUE TITLE
Document the Coordinate system used for Shapefiles

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1445]
The function `cea.utilities.standarize_coordinates.shapefile_to_WSG_and_UTM` defines the standard coordinate system to use for the Shapefiles in the CEA.

This should also be mentioned in the documentation.

I checked the Tutorials and the readthedocs documentation and could not find any references. If it exists, then we should make it more prominent.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can you take over this issue please? I think of the group, you're the person with the most knowledge in this matter.

**Comment by JIMENOFONSECA** [comment]
Sure, please assign it to me
On 5 Jun 2018, 16:48 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> can you take over this issue please? I think of the group, you're the person with the most knowledge in this matter.
