### ISSUE TITLE
limit amount of CPUs used for multiprocessing

### ISSUE THREAD

**Issue by roglen** [architecture-building-systems/CityEnergyAnalyst#1450]

**Comment by roglen** [comment]
Reduces the amount of used CPUs in the thermal network matrix to make sure that laptop is still useable while simulation is running.

**Comment by daren-thomas** [comment]
I wonder if we could add a `max-processes` variable to the `[general]` tab with the following semantics:

- `0`: (default) use all available CPU's if multiprocessing
- `n`: use `min(max_processes, mp.cpu_count())` if multiprocessing

**Comment by roglen** [comment]
@daren-thomas what do you think?

**Comment by daren-thomas** [comment]
@roglen i think the trial-and-error thing is unavoidable. i like your suggestion of the `cpu_count() -1` but not sure how you could implement that. what if... negative values for `max-processes` are subtracted from `cpu_count()`?

so, the number of processes used could be calculated like this:

```
if config.multiprocessing:
   processes = cpu_count() + config.max_processes if config.max_processes < 1 else config.max_processes 
```

And have the default in `default.config` be `-1`

**Comment by roglen** [comment]
@daren-thomas  Interesting idea! I like it!
I was thinking of something like this:

`if config.multiprocessing:
      processes = max(min(config.max_processes, cpu_count() -1), 1)`

the max condition so that we have at least one. I guess the downside of this would be that we can't set it to using all cpus. So let's go with what you wrote! Can we add a failsafe for the case with only one CPU? (even though it probably never applies..)

Should I add it to the thermal_network_matrix or will you? (Your code so your lines?)

**Comment by daren-thomas** [comment]
you go ahead. add a failsafe! extract it to a function (`number_of_processes`?) and stick that in utilities or something so we can use it from demand as well - in fact, maybe go and see if you can fix those parts too so we stay consistent?

i'll gladly review your changes :)
