### ISSUE TITLE
Databases folder in case study

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1451]
In order to facilitate access to the users to the databases of cea in each case study. This feature should do:

When running the first simualtion. It should copy the databases folder of CEA to the folder of the case study. This is already done, BUT What it should be different is what databases should be copied and hence be used from there on.

If the region in the config file is CH then COPY to the case study folder:

Databases
/CH
//archetypes
//benchmarks
//systems
//lifecycle

If the region in the config file is changed to SIN, then COPY to the case study folder:

Databases
/SIN
//archetypes
//benchmarks
//systems
//lifecycle

If by any case the user switches between SIN and CH in the region of the config file. It should not matter, then the databases of both regions should be there in a separate folder.

Databases
/CH
/SIN

I made this organizaiton of databases in branch 1451, @daren-thomas could you make this issue your immediate priority and pick up the work from that branch?

**Comment by daren-thomas** [comment]
sure. i have meetings today, but tomorrow i'll look into this. i like your approach.
