### ISSUE TITLE
Update glossary to reflect variable name changes from PR  #1454

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1455]
The upcoming  PR  #1454 will change the subscripts of all the variables like this:

hsf  ——> hs_sys
csf  ——> cs_sys
wwf  ——>ww_sys

I recommend Jack use the replace-text tool in csv and replace all with hsf to hs_sys etc… that is an easy way to do it.

The name of the variables will be

“system heating demand” instead of “final heating demand”
“system cooling demand” instead of “final cooling demand”
etc...

**Comment by daren-thomas** [comment]
@Jack-Hawthorne do you know the status of this issue?

**Comment by Jack-Hawthorne** [comment]
@daren-thomas have all variable name changes been finalized?

If so i will access the branch tomorrow and update the variables and descriptions.

Also, are the changes specific to a particular series of databases or have all the input and default databases been modified?

**Comment by daren-thomas** [comment]
I have merged your changes. We can work starting with this as the current base.

**Comment by daren-thomas** [comment]
all the input and default databases should be harmonized...

**Comment by Jack-Hawthorne** [comment]
there is also one issue of formatting on the glossary preamble - its not major though.

what do you mean exactly by harmonized?

the current structure was built to reflect what amr will present - however, the dependencies could and should be better represented.

**Comment by daren-thomas** [comment]
With harmonized I mean, to make sure that the same naming scheme is used in all databases and outputs. Is it possible to check that? If not, we can close this issue.

As for the dependencies... I'm working on the GraphViz image...
