### ISSUE TITLE
As a researcher, I want the environmental performance to be a function of my system design and operation, so I can evaluate design options in a meaningful way

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1457]
The database of infrastructure LCA should be updated to a more dynamic way of calculating technology environmental impacts.

The idea is to disaggregate infrastructure&materials from fuel usage, similar to cost calculations.
For that we need information on:

- Equipment LCA per unit of generation capacity, e.g., 1 kW of chiller, 1 kWp of PV panel
- Equipment Lifetime, e.g., 15 years for chiller, 20 years for PV panel
- Fuel LCA, e.g., environmental impact of 1 kWh of grid power

E.g., chiller impacts will be calculated with:

`( (size_equipment * LCA_equipment_per_unit) / life_time + fuel_use_per_year * LCA_fuel ) * (1 / cooling_energy_per_year)`

E.g., PV generation impacts:

`(size_equipment * LCA_equipment_per_unit) / life_time * (1 / electricity_generation_per_year )`

Probably for equipment like chillers, CHPs, etc. the equipment size impacts will not be linear (similar to investment costs).

We could take advantage of Ecoinvent and Simapro as long as @ongbolie is with us.

I assigned a bunch of people involved. Whoever doesn't want to be part of this discussion should unassign themselves.

**Comment by ongbolie** [comment]
#1422

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle this is an epic please write it down as an user story and the user persona

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA, @shanshanhsieh, @BhargavaKrishnaSreepathi the lead on this epic is up for grabs. You, as the researchers using multi-objective optimization or the most affected developers.
Of course, I can support with my expertise in LCA.

**Comment by JIMENOFONSECA** [comment]
1.5 years in here, we will not have it anytime soon. Closing it.
