### ISSUE TITLE
Better description of variables inside lake potential tool

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1461]
It is difficult to know what the variables incl. tick boxes do in this tool. I imagine we do not need to run it all the time right? optimization should bypass it if it does not find the file right?

![image](https://user-images.githubusercontent.com/8973186/41142362-fa7a5a54-6b27-11e8-8ae5-1368d30853cb.png)

**Comment by daren-thomas** [comment]
I agree. There is much room for improvement here. Also, what is meant with "Calculate the lake potential of the location"?
