### ISSUE TITLE
Please test the reference-case-WTP-reduced/ WTP_MIX_m

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1464]
Hi Daren, Please run the reference-case-WTP-reduced/WTP_MIX_m.
you can find the scenario here.
https://github.com/architecture-building-systems/cea-reference-case/tree/master/reference-case-WTP-reduced 
The configuration to be tested is here:
https://docs.google.com/spreadsheets/d/16YhTIFRgqFL-EDsPm-nwdn3thEoNwKRrDhfk6OdMvRM/edit#gid=148616131 

For the test run, run with individuals as 2 and generations as 2. If everything is running, then run it longer  , like individuals as 30, and generations as 25.

Also run everything from ArcGIS updating CEA from Master

**Comment by BhargavaKrishnaSreepathi** [comment]
You can find the workflow of running CEA here, http://city-energy-analyst.readthedocs.io/en/latest/cea-workflow-guide.html

**Comment by daren-thomas** [comment]
waiting for optimization `initialind=5, ngen=5`

**Comment by BhargavaKrishnaSreepathi** [comment]
👍
