### ISSUE TITLE
Change the feature name "Data Miner" to "Data Helper"

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1466]
@JIMENOFONSECA , we need to change the name of the "data miner" feature to "data helper". We discussed this in an earlier meeting and you asked me to assign you for this issue.

**Comment by JIMENOFONSECA** [comment]
@amraladdin this is already implemented in master since some weeks, you might have the old version of CEA, please re-install the toolbox. in the command line do

-activate cea
- cea install-toolbox

**Comment by amraladdin** [comment]
Sounds great! Thanks!
