### ISSUE TITLE
Glossary | Inputs and Default Databases

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1467]
Dear Team,

Please find in the below Google Sheet Link the variables list for the *inputs* and *default databases* of the CEA. We need your (The Singapore Team) input to complete the list and finalize the Glossary.

As discussed over Skype, the Singapore team will check the link, fill the missing parts and return it by *Wednesday 13th of June*.

EXPLANATION:
-----------------
Please open the following link:
https://docs.google.com/spreadsheets/d/1SYoAIjXVLS0QfxqH1jf4WmweSPhp-8QCn2kTfgCJis8/edit?usp=sharing

- The yellow color indicates the variables/sets of variables that are new.
- The red color indicates the missing or unclear information.

Jack and Thomas (The Student Assistants working on the Glossary) checked the two Cases CH and SIN. In terms of variables they are identical.
After you return the filled Excel sheet, Jack will upload the file to the respective branch.
If you have urgent questions, you can send an email to Jack ( hjack@student.ethz.ch ) or Thomas ( wuthomas@student.ethz.ch )

ORGANIZATION:
-----------------
The Singapore Team should discuss internally who will take charge of the edits and revision (I assigned most of the team for now).
After the editing of the variables is complete, @daren-thomas , @Jack-Hawthorne , Thomas and myself will sit down to organize the databases in their respective category as presented in the Executive Course.

ADDITIONALLY:
-----------------
Since there's a massive change in the variables, we ask you to write down the new variable names.

**Comment by JIMENOFONSECA** [comment]
@amraladdin  ok, i did my contribution.

**Comment by amraladdin** [comment]
Thanks @JIMENOFONSECA 
Could you tell us who is responsible for double-checking the new variable names from the Singapore team?

**Comment by shanshanhsieh** [comment]
me and @roglen both checked/edited the google sheet as well

**Comment by gabriel-happle** [comment]
I also checked and modified.

**Comment by BhargavaKrishnaSreepathi** [comment]
same here, though very little

**Comment by amraladdin** [comment]
Thanks @BhargavaKrishnaSreepathi @shanshanhsieh @gabriel-happle @roglen @JIMENOFONSECA 
So, the last 2 questions:
**Could you tell us who is responsible for double-checking the new variable names from the Singapore team?**
**There is still missing information, e.g. DC and DH, LCA, QEprof... etc.**

**Comment by shanshanhsieh** [comment]
Hi all, i went through the glossary just now, and broke down the list of the things to do for each one of us in Singapore. Thank you for your time in advance!

@JIMENOFONSECA 
1. in the **input tab**, check row 228-255 (fill the empty boxes, and change color from red to yellow if confirmed)
2. in the **output tab**, check row 265-364 (fill the empty boxes, and change color to white if confirmed)

@BhargavaKrishnaSreepathi 
1. in the **output tab**, check row 364-400 (change color to white if confirmed)

@gabriel-happle 
1. in the **input tab**, check row 12-49, row 170-201 (change color to yellow if confirmed)
2. in the **input tab**, answer the question at row 121, 127
3. in the **output tab**, check row 1-264 (change color to white if confirmed)

**Comment by BhargavaKrishnaSreepathi** [comment]
Thanks @shanshanhsieh for the initiative. Done my part 👍

**Comment by gabriel-happle** [comment]
Thank you @shanshanhsieh I think I'm done too...

@amraladdin the document needs spell checking. I corrected all the refri`d`geration I saw.

@amraladdin it's worth checking the document for occurrences of `pro` and `production`. Many times `pro` was mistaken for `production` while it actually means `industrial processes`, i.e., heat/electricity required by special processes.
 
Also, @amraladdin I suggest to replace all `nominal` nomenclature with `peak`. Nominal doesn't make sense for me in the context of energy demand/consumption.

**Comment by amraladdin** [comment]
Thanks a lot @shanshanhsieh for leading this and thanks @BhargavaKrishnaSreepathi and @gabriel-happle for chipping in.
I'm sorry but I'm on holidays starting this evening and won't have time to check the document. Please refer to @daren-thomas and @Jack-Hawthorne

**Comment by Jack-Hawthorne** [comment]
@gabriel-happle i shall replace all the nominal to peak in the outputs dbs.

I am also not quite happy with the `End-use` description for systems demand, would it be better to change to `System` or `HVAC systems` demand?

I grabbed many of the output variable names from the `naming.csv` in plots, should i deviate from this?
