### ISSUE TITLE
Add cea copy-databases tool

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1475]
This tool, added in PR #1453, needs to be added to the ArcGIS interface (uncomment the class already set up in the CityEnergyAnalyst.pyt file).

Also, the code that runs this functionality automatically has to be removed from the `cea.interfaces.cli.cli.py` file.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas this exists already right? should we close this issue?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas closing, I believe this was removed while we removed the region parameter and the copy databases tool was added to the datahelper
