### ISSUE TITLE
Update knowledge base on how to fix python errors in ArcGIS

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1478]
Following this guide:

- https://www.python.org/dev/peps/pep-0514/

it is possible to see what registry changes to make to get revert the default python version ("PythonCore") back to the ArcGIS version, as opposed to the version installed with Anaconda.

**Comment by JIMENOFONSECA** [comment]
moving all related to ArcGIS to won't have.

**Comment by JIMENOFONSECA** [comment]
We ended support on March 2019.... closing this.
