### ISSUE TITLE
Update labels for the interface of Decentralized Optimization

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1483]
Seriously. They all say "this is a configuration flag, which influences the disconnected building calculations". So, essentially useless for the user.

Also, why is the code in `cea.optimization.preprocessing.disconnected_building_main`, the cea tool called `decentralized`, the configuration file section called `[disconnected-cooling]` and the ArcGIS tool called "Decentralized supply system", while the actual class implementing the tool is called `DecentralizedBuildings`?

This needs to be refactored to be consistent!

**Comment by daren-thomas** [comment]
@JIMENOFONSECA who would be best to assign this issue to? @BhargavaKrishnaSreepathi?

**Comment by JIMENOFONSECA** [comment]
Yes
On 12 Jun 2018, 03:50 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> who would be best to assign this issue to? @BhargavaKrishnaSreepathi<https://github.com/BhargavaKrishnaSreepathi>?

**Comment by martin-mosteiro** [comment]
Same. These options are not very informative.
<img width="757" alt="screen shot 2018-06-12 at 19 21 24" src="https://user-images.githubusercontent.com/18548065/41306297-f0abdd30-6e75-11e8-9b9e-6a6b83ebcde1.png">
