### ISSUE TITLE
place scripts in proper locations

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1486]
- `sewage_heat_exchanger.py` should be in the resource folder
- `lake_potential.py` should be in the resource folder
- why is `radiation_total.py` inside technology/solar?

**Comment by shanshanhsieh** [comment]
@BhargavaKrishnaSreepathi  please confirm the information, i can make the changes quickly

**Comment by BhargavaKrishnaSreepathi** [comment]
@shanshanhsieh: yes, please also keep in mind that the interfaces link to these file locations, so they need to be modified accordingly

**Comment by shanshanhsieh** [comment]
@BhargavaKrishnaSreepathi where should `radiation_total.py` be?

**Comment by BhargavaKrishnaSreepathi** [comment]
cea\plots\4D_plots_ArcGIS

**Comment by shanshanhsieh** [comment]
when trying to move the scripts (`sewage_heat_exchanger.py`), I found a file called `SOURCES.txt`, not sure how this file was created, and if it needs to be updated manually. @daren-thomas, can you tell me?
