### ISSUE TITLE
PV and PV/T Features overwrite results with each run

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1492]
While running the Solar Energy Potential features:
- PV
- PV/T
- SC

The following happend:
- When simulating SC_FP, then simulating SC_ET, the results (Data or Plots) are produced separately and they do not overwrite each other, unless you simulate the same SC type again after changing some of the advanced settings.
- When simulating PV1, then simulating PV2 (or PV3, doesn't matter), the results always overwrite each other, and the results are named "PV". Same thing goes for PV/T.

*This is an issue because it is inconvenient for the users to want to compare different PV technologies for example, especially that they run in a very short time, and have to rename the data or plot results for every technology they make*

@JIMENOFONSECA @shanshanhsieh sorry for assigning you directly, I thought Jimeno needs to take part in the decision regarding this issue, and Shanshan is the Solar Technology expert.

**Comment by shanshanhsieh** [comment]
valid point, @amraladdin 
however, i will only have time to incorporate this change next week.
the reason that it cannot be done easily is that the names of the files are connected to plots, and that part takes more time to change.
if it is still possible to make changes next week, i will make it happen. @JIMENOFONSECA what do you think?

in the planned exercise, we will not ask them to compare results from PV1, PV2, PV3... (no time anyways, and martin think it's rather boring)
if the users want to do it, they can create a new folder (e.g. PV1) in the result directory, move the first batch of results into the folder, and continue with more simulations with other technologies

**Comment by JIMENOFONSECA** [comment]
Well noted Amr!. Next week should do for this issue. I am also planning to implement a better folder structure to the plots folder so we do not get lost...

Jimeno
On 12 Jun 2018, 17:34 +0800, Shanshan Hsieh <notifications@github.com>, wrote:

valid point, @amraladdin<https://github.com/amraladdin>
however, i will only have time to incorporate this change next week.
the reason that it cannot be done easily is that the names of the files are connected to plots, and that part takes more time to change.
if it is still possible to make changes next week, i will make it happen. @JIMENOFONSECA<https://github.com/JIMENOFONSECA> what do you think?

in the planned exercise, we will not ask them to compare results from PV1, PV2, PV3... (no time anyways, and martin think it's rather boring)
if the users want to do it, they can create a new folder (e.g. PV1) in the result directory, move the first batch of results into the folder, and continue with more simulations with other technologies

**Comment by JIMENOFONSECA** [comment]
This issue was covered during the executive course of Jul 2018
