### ISSUE TITLE
We need more scenario analysis plots

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1493]
This is what we have: I believe we need better plots to compare between multiple scenarios in CEA. Please drive ideas in! This is extremely important for the executive course.

Just feel free to unassigned yourself. Ideas are welcome!.

[drive-download-20180612T090620Z-001.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2093352/drive-download-20180612T090620Z-001.zip)

**Comment by amraladdin** [comment]
@JIMENOFONSECA What are Scenario_A and Scenario_B? What are the differences between them?

**Comment by amraladdin** [comment]
@JIMENOFONSECA I'm not sure if it's a good idea to add new plots at this stage? Could cause undesired errors before the Executive Course.

**Comment by martin-mosteiro** [comment]
@amraladdin These look like dummy scenarios (copies of the original) in order to be able to run the plots.

**Comment by amraladdin** [comment]
@martin-mosteiro Yeah, I realized that after writing the comment, so I deleted it and posted a new one :D

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA how about visualizing the urban design input parameters of the scenarios?
- m2 GFA of office space
- m2 GFA of residential space
- ...

Plus maybe the same plots as above disaggregated according to occupancy type, i.e.,
- Emissions per m2 GFA office space
- Emissions per m2 GFA residential space

It could be interesting. Maybe it could reveal "synergies" in supply systems. I'm not sure though.
E.g., in the scenario with lower/higher office share 1m2 GFA of office is more/less efficient...

**Comment by JIMENOFONSECA** [comment]
i got this https://www.sciencedirect.com/science/article/pii/S0360544217320844#fig1

![screen shot 2018-06-12 at 9 46 06 pm](https://user-images.githubusercontent.com/8973186/41294659-2c7a2050-6e8b-11e8-81d0-fe8f1fb4539a.png)
![screen shot 2018-06-12 at 9 47 42 pm](https://user-images.githubusercontent.com/8973186/41294660-2cac8018-6e8b-11e8-95b5-5a6a196ef5a9.png)
![screen shot 2018-06-12 at 9 48 42 pm](https://user-images.githubusercontent.com/8973186/41294661-2cdf4b4c-6e8b-11e8-950f-4ebf8bc86f31.png)
![screen shot 2018-06-12 at 9 51 03 pm](https://user-images.githubusercontent.com/8973186/41294662-2d109c1a-6e8b-11e8-8d9f-a5188cd53e13.png)
