### ISSUE TITLE
Executive Course Exercises | Friday

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1495]
We would like to organize the exercises that will take place Friday afternoon. So far there are the 6 scenarios to run. However, this might not need to run the simulations for most of Friday, so we need to define other exercises in case the attendees have more time. The following is suggested:
- Using another weather file for Singapore in 2030, which takes climate change into account.

We would like to have more suggestions.

**Comment by shizhongming** [comment]
Having a meeting on 20ish
