### ISSUE TITLE
Progress display for optimization algorithm

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1500]
The optimization algorithm produces a lot of output, but it's not obvious how to detect the progress from this output. Maybe a line along the lines of:

```
cea optimization progress: individual 5/5, generation 3/5
```
could that be added? Actually, based on that, an estimate of time remaining could be created...

@BhargavaKrishnaSreepathi what do you think? maybe push the milestone if you don't think it'd be ready for the executive course (but I suspect it's rather easy to add, no?)

**Comment by JIMENOFONSECA** [comment]
@daren-thomas moving to nice to have...
