### ISSUE TITLE
Check hot water energy demand values for Singapore

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1501]
The hot water demand in residential buildings should approximately amount to 20% of electricity consumed.
At the same time we can also check appliance and cooling consumption.
The shares should approx be:
- Cooling around 30-40 % (of Electricity) -> (divide by COP=4 for cooling energy)
- Hot Water around 20% (of Electricity)
- Appliances around 40-50%

![image](https://user-images.githubusercontent.com/17002288/41401939-a4920e2c-6ff3-11e8-85ed-2fb72419a5e7.png)

http://www.e2singapore.gov.sg/Households/Saving_Energy_At_Home/HEA.aspx

The shares we are having now are around:
- Cooling 30% (OK)
- Hot Water 4% (Too LOW)
- Appliances 70% (OK, maybe a bit high)

**Comment by shanshanhsieh** [comment]
```tsd['vww_m3perh'] = schedules['Vww'] * bpr.internal_loads['Vww_lpd'] / 1000  # m3/h```
as far as i understand, the schedules['Vww'] is a fraction of the Liter per day for each hour

**Comment by martin-mosteiro** [comment]
@shanshanhsieh Correct. The hot water schedule is calculated as the scheduled value at time t according to the schedule archetype divided by the sum of the scheduled value for the entire day of the week. This is kind of dumb (why not just redefine the archetype schedule?) but it's the way it was done in CEA from the start.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro so the reason is that we got data about the profile of consumption of hot water in therms of intensity (m3/m3 of water per hour) BUT got the amount of water consumption in liters per person per DAY. So that is the tricky part. We could change the nominal value of water consumption to Peak liters per person (but that is hard to get from a source).

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Thanks for the clarification for the source of the data. However we could just redefine the schedules to skip a step on the CEA code (i.e., give them as x[t]/sum_t(x[t])) - wouldn't that be easier to read?

**Comment by martin-mosteiro** [comment]
Okay, this is weird. Just tested on reference-case-open for comparison and the demand for hot water is higher in office buildings than in residential ones (see graph below - B01 and B02 are 'MULTI_RES' and 'SINGLE_RES', respectively). Sounds like a scheduling issue, indeed.
![screen shot 2018-06-14 at 15 13 23 copy](https://user-images.githubusercontent.com/18548065/41414250-d6d509ec-6fe5-11e8-973a-5d36c00d0b56.png)
And here's WTP_RES_l for reference:
![screen shot 2018-06-14 at 15 16 40](https://user-images.githubusercontent.com/18548065/41414309-f46e7e16-6fe5-11e8-9ce2-f0ac97f110a3.png)

**Comment by gabriel-happle** [comment]
http://www.e2singapore.gov.sg/DATA/0/docs/Voluntary%20Agreement/Household/Executive%20Summary%20%20Key%20Findings.pdf

**Comment by gabriel-happle** [comment]
@shanshanhsieh, @JIMENOFONSECA, @martin-mosteiro 
I believe the hot water calculations are OK.
I didn't find any bug so far. I believe the values make sense.

When comparing with actual SG household energy consumption, the values for hot water match quite well.

Real SG values:
Average public housing electricity consumption (4-room) = 4800 kWh/yr
Hot water electricity (20% of electricity) = 960 kWh/yr
Hot water electricity per person (3.5 persons per 4-room) =  274 kWh/yr

CEA values (Res_h case study B001):
Hot water electricity per person = 558 kWh/yr  (I guess that's OK, as private housing consumption is much higher)

When looking at those values, it seems that rather than the hot water energy demand being too low the other electricity demands are too high.

Indeed, the household electricity consumption in my case study (B001 in RES_h) is 1238 kWh/month/person. 
That's way higher than the consumption of a whole average private household.
I think we have to review either our appliance schedules or our installed power densities!


Sources:

https://www.ema.gov.sg/cmsmedia/Publications_and_Statistics/Publications/ses/2017/energy-consumption/index.html

https://www.ema.gov.sg/cmsmedia/Publications_and_Statistics/Publications/ses/2017/energy-consumption/index.html

http://www.tablebuilder.singstat.gov.sg/publicfacing/createDataTable.action?refId=12305

**Comment by gabriel-happle** [comment]
Action plan:
- make occupant presence (occupant density) dependent on GFA (as opposed to Af)
- check EUI of residential, office and retail buildings and adjust installed lighting and appliance power density in archetypes DB to match SG values

**Comment by gabriel-happle** [comment]
![image](https://user-images.githubusercontent.com/17002288/41523838-f46549d8-730d-11e8-8ae4-d55d16b2bb5c.png)

After the change of occupant density I get following values (for a modified version of MIX_m case study):
- EUI RESIDENTIAL =~ 125 kWh/m2GFA/yr (should be lower)
- EUI RETAIL =~ 190 kWh/m2GFA/yr (should be higher)
- EUI OFFICE =~ 150 kWh/m2GFA/yr (very efficient office)

The shares of Hot Water and Cooling electricity of EUI are:
- RESIDENTIAL: 14% and 18% (quite OK considering overall EUI is too high)
- RETAIL: 0% and 5 - 25% (quite low)
- OFFICE: 0% and 25% (quite low)

This means we are looking for modifications which lower our appliance and lighting use in Residential by approx. half.
At the same time we want to increase our cooling consumption of retail and office buildings.
Such modifications of the archetypes database for SG would be:
- Lower `Ea_Wm2` and `El_Wm2` for residential by approx. half.
- Increase envelope leakiness for Retail and office from `T1` to `T2` and maybe increase WWR for office from 0.35 to 0.7 (value from BCA/Bharath).

**Comment by JIMENOFONSECA** [comment]
Yes! But! For retail, bear in mind that we are not taking into account restaurants! Which increase people density and hot water use.

Maybe the case studies need to include this?
On 18 Jun 2018, 15:56 +0800, Gabriel Happle <notifications@github.com>, wrote:

[image]<https://user-images.githubusercontent.com/17002288/41523838-f46549d8-730d-11e8-8ae4-d55d16b2bb5c.png>

After the change of occupant density I get following values (for a modified version of MIX_m case study):

  *   EUI RESIDENTIAL =~ 125 kWh/m2GFA/yr (should be lower)
  *   EUI RETAIL =~ 190 kWh/m2GFA/yr (should be higher)
  *   EUI OFFICE =~ 150 kWh/m2GFA/yr (very efficient office)

The shares of Hot Water and Cooling electricity of EUI are:

  *   RESIDENTIAL: 14% and 18% (quite OK considering overall EUI is too high)
  *   RETAIL: 0% and 5 - 25% (quite low)
  *   OFFICE: 0% and 25% (quite low)

This means we are looking for modifications which lower our appliance and lighting use in Residential by approx. half.
At the same time we want to increase our cooling consumption of retail and office buildings.
Such modifications of the archetypes database for SG would be:

  *   Lower Ea_Wm2 and El_Wm2 for residential by approx. half.
  *   Increase envelope leakiness for Retail and office from T1 to T2 and maybe increase WWR for office from 0.35 to 0.7 (value from BCA/Bharath).

**Comment by gabriel-happle** [comment]
I made some modifications to archetypes and window and wall constructions.
These are the Pies I end up with a modified MIX_m case study.
![image](https://user-images.githubusercontent.com/17002288/41539216-cae7dec2-733f-11e8-99c6-763fdf57108b.png)
![image](https://user-images.githubusercontent.com/17002288/41539230-d2db2972-733f-11e8-86db-04ff7d2bbfad.png)
![image](https://user-images.githubusercontent.com/17002288/41539240-d9d8e2f0-733f-11e8-8b19-9161ee201e66.png)
![image](https://user-images.githubusercontent.com/17002288/41539351-29b96ea2-7340-11e8-9ee8-87c23d0223ba.png)


EUI_res =~70kWh/m2GFA/yr (still a bit high)
EUI_office =~ 160kWh/m2GFA/yr (still low share of cooling)
EUI_retail =~ 200 kWh/m2GFA/yr (still a bit low and low share of cooling)

**Comment by gabriel-happle** [comment]
SinBerBest Benchmark office
![image](https://user-images.githubusercontent.com/17002288/41571136-60d30506-73a4-11e8-827a-1b112dfce1b1.png)

**Comment by gabriel-happle** [comment]
Cooling load benchmarks for SG:
https://www.bca.gov.sg/GreenMark/others/Cooling_Load_Article_2015.pdf

In peak_cooling_load per m2_Af.

**Comment by martin-mosteiro** [comment]
@gabriel-happle Good check on the feasibility of the numbers. However, I still think there must be something off with the hot water calculation.

If you look at the graph I provided above for the Swiss case (based on reference-case-open, so the buildings all have the same properties other than the occupancy), the hot water demand per square meter was higher for offices than for residential. However, according to the archetypes:
- MULTI_RES: Vww = 40 l/p/d / 40 m2/p = 1 l/m2/d (4.6 kWh/m2 yr in the plot above)
- SINGLE_RES: Vww = 40 l/p/d / 60 m2/p = 0.67 l/m2/d (6.3 kWh/m2/yr in the plot above)
- OFFICE: Vww = 10 l/p/d / 14 m2/p = 0.71 l/m2/d (8.2 kWh/m2/yr in the plot above)

So while it might be that the value are within a feasible range, these results still don't make sense to me.

**Comment by gabriel-happle** [comment]
@martin-mosteiro true. that is strange!
I actually did't compare across functions, because in SG we only have MULTI_RES with hot water consumption and there the amount of water consumed in one day and the energy used for that made sense to me.

**Comment by martin-mosteiro** [comment]
@gabriel-happle @JIMENOFONSECA We need to stay consistent in the definition of floor areas. 

You guys just redefined the hot water calculations in order to use the GFA instead of the conditioned area. Consider however that the Swiss archetypes for example for a residential building have **Af = 0.82 * GFA** in order to account for hallways, basements, etc. So by using GFA for the hot water calculation you just increased the hot water demand in Swiss residential buildings by 22% for no actual reason! So while this change might be reasonable for the Singapore cases I think it doesn't make sense for Switzerland. Please keep this in mind whenever you make changes like these.

In any case, I think we might need to give the definition of the floor areas a bit of thought. As mentioned in #1374 the electrified floor area is hard coded and always the same for all buildings, but then the internal gains due to lighting and appliances are all dumped into the conditioned floor area. That doesn't seem reasonable to me for neither the Singaporean nor Swiss cases.

**Comment by martin-mosteiro** [comment]
I also noticed that the case study I was testing on had no fresh water demand: indeed, I checked the code and the fresh water volume calculation seems to have gone missing. 
![image](https://user-images.githubusercontent.com/18548065/41660557-a9ad04e0-749c-11e8-9a51-9b5a645d38ba.png)
![image](https://user-images.githubusercontent.com/18548065/41660566-b00cfcf0-749c-11e8-8cac-e363cc3b0a35.png)
I'm adding these on a separate branch.

**Comment by JIMENOFONSECA** [comment]
Yes! you are right, we might need to create a flag based on the region and bring back the variables Es which controlled the area with lighting.

Would you like to create an strategy so we can discuss it? btw, do you find it to be the case still that offices get more hot water demand than residential? This could be the case as there are more people per m2 though. Did you accounted for this?

It would be great if we start working in this issue but at this point we will not merge it into master anymore (as the results make sense for the executive course.

________________________________

**Comment by JIMENOFONSECA** [comment]
Really? There is a variable mcptot i think and thata has the volume of fresh water. One way to see it is in the sewage-heat exchanger script which needs this info to run. If it does not exist then it does not run. Could tou check?
On 20 Jun 2018, 21:15 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

I also noticed that the case study I was testing on had no fresh water demand: indeed, I checked the code and the fresh water volume calculation seems to have gone missing.
[image]<https://user-images.githubusercontent.com/18548065/41660557-a9ad04e0-749c-11e8-9a51-9b5a645d38ba.png>
[image]<https://user-images.githubusercontent.com/18548065/41660566-b00cfcf0-749c-11e8-8cac-e363cc3b0a35.png>
I'm adding these on a separate branch.

**Comment by JIMENOFONSECA** [comment]
Martin could it be a problem of the schedules? Could you check if they are ok?
On 20 Jun 2018, 21:15 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

I also noticed that the case study I was testing on had no fresh water demand: indeed, I checked the code and the fresh water volume calculation seems to have gone missing.
[image]<https://user-images.githubusercontent.com/18548065/41660557-a9ad04e0-749c-11e8-9a51-9b5a645d38ba.png>
[image]<https://user-images.githubusercontent.com/18548065/41660566-b00cfcf0-749c-11e8-8cac-e363cc3b0a35.png>
I'm adding these on a separate branch.

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Found the issue: the hot water loads script (which uses 'vfw_m3perh') was called before Eaux_fw (which defines 'vfw_m3perh'). Should be okay now.

**Comment by JIMENOFONSECA** [comment]
Cools is there a pr for this?
On 20 Jun 2018, 21:29 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> Found the issue: the hot water loads script (which uses 'vfw_m3perh') was called before Eaux_fw (which defines 'vfw_m3perh'). Should be okay now.

**Comment by martin-mosteiro** [comment]
There is now :)

**Comment by martin-mosteiro** [comment]
The results for Switzerland makes sense now.
<img width="1397" alt="screen shot 2018-06-21 at 10 55 07" src="https://user-images.githubusercontent.com/18548065/41708709-a00fe9de-7541-11e8-9577-2a183d12e70d.png">
@gabriel-happle I think this issue may be closed now, right?

**Comment by gabriel-happle** [comment]
Yeah, if you are OK with it.
We should tackle your #1374 next!
