### ISSUE TITLE
Add operation cost of solar collectors to heating_resource_activation.py

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1510]
The electricity cost for pumping in the solar collectors should be accounted into the operation cost.
The information is saved in SC_FP_total.csv and SC_FP_total.csv.
Please take note:
1. this is the cost to operate all solar collectors in the area, if only a portion of the total area is installed with solar collectors, this number will reduce proportionally
2. if PVT is used in this script, the corresponding pumping cost should be accounted as well

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh is this issue already addressed?

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA the pumping costs are added to the tropical context, but not the temperature climate yet. I will discuss with @BhargavaKrishnaSreepathi on how to proceed with that.
