### ISSUE TITLE
Create separate tool to run optimization plots

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1519]
The idea is to create a tool to call a specific urban scenario, an specific generation and an specific individual. 
Graphs related to this specific configuration will be generated and will help on the decision making processs

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi  be aware there are some changes taking place on the plots.

![image](https://user-images.githubusercontent.com/8973186/41660138-c4bbf454-74cd-11e8-892c-9b87d748a5fd.png)

could you help me to test here if they run for you?
These are the scripts for that create those three tools now

![image](https://user-images.githubusercontent.com/8973186/41660212-fcc262a2-74cd-11e8-98de-0461a84e25be.png)

**Comment by JIMENOFONSECA** [comment]
all is worked in branch 1519. Daren will help us to improve the interface for the Plots scenario comparisons in the following days.

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi @shanshanhsieh I created a total of 5 plots in the supply_main (single energy system) and 2 for the scenario comparisons. 

I still need to ask daren for help to get the map complete. Be aware that the mapping already calls the thermal network simulation and the layout. I will coordinate with lenny this part. 

Let me know if you have any questions!!

**Comment by JIMENOFONSECA** [comment]
All is in branch 1519. as discussed we cannot changed the scripts except those related to plots at this point

**Comment by shanshanhsieh** [comment]
i added a new script into this branch, it's called `individual_configuration.py`
the output from the script looks like this:
![image](https://user-images.githubusercontent.com/16998305/41901783-65de1d54-7964-11e8-8fa5-24a174d4f6ec.png)

@JIMENOFONSECA  please let me know if that is compatible with the plotting requirements

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh fabulous! many thanks for this!!

**Comment by shanshanhsieh** [comment]
When plotting, one suggestion is the to reduce the table by deleting the columns with zero capacity installed. It will be easier to read the table this way.
