### ISSUE TITLE
PV share of the buildings in Cooling Case need to be configuration dependent

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1537]
Currently, the only check is if the building is having a solar collector or not. If a building does not have solar collector then the area is assumed to have PV. This needs to be changed

**Comment by shanshanhsieh** [comment]
what needs to be done is that we have to set the *area to install PV* as a *variable* in optimization.
so each individual in the optimization will have a different area of pv installed (in the heating case, it is a % of the total available area to install PV)

**Comment by JIMENOFONSECA** [comment]
this is not the case anymore. 1.5 years in here, we will not have it anytime soon. Closing it.
