### ISSUE TITLE
Refactor Optimization

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1541]
This epic collects all the issues regarding a refactoring effort for the optimization code. The goals are:

- refactor to the deap tutorial skeleton (make it easier for new people to understand how the optimization code is set up)
- document the optimization in a top-down fashion to make it easier to get into the code base
- PEP8 the code
- reduce the amount of files saved -> preparation for running on Euler
- parallel processing of the optimization
- adding optimization test coverage to the jenkins

**Comment by daren-thomas** [comment]
hey, @JIMENOFONSECA I just saw this issue and it contains some goals for refactoring the optimization. Since you're doing that now, I thought you might be interested in some of the thoughts I had on this issue back then - the part about the file count is still relevant in my opinion. Also refactoring towards the deap tutorial skeleton seems prudent - as long as that's still how we do optimization.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA so how is this coming along? What is the current status?

**Comment by JIMENOFONSECA** [comment]
On it…baby steps…it will be done by end of September as I see.

But in the meantime I will be making some PR's
On 22 Aug 2019, 4:05 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> so how is this coming along? What is the current status?

**Comment by daren-thomas** [comment]
implemented in PR for #2249
