### ISSUE TITLE
Fix BuildingParameterInfoBuilder to "just work"

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1544]
Currently, the plots tool and others have to override the `updateParameters` method to have a buildings parameter work properly.

This can be fixed with the new way that the parameter info builders work. fixing this would make the code easier for new tools and remove duplication of code.

**Comment by JIMENOFONSECA** [comment]
1.5 years in here, we will not have it anytime soon. Closing it.
