### ISSUE TITLE
further improvements to the optimization/supply system plots for the executive course

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1545]
Instead of creating the files again, plots can reuse the files already created and generate the plots

**Comment by JIMENOFONSECA** [comment]
@bahargav, I think we should be on top of this right now. We need to make the scenario comparisons functional for Wednesday evening

**Comment by BhargavaKrishnaSreepathi** [comment]
already working in the branch i1545, do make the changes there
