### ISSUE TITLE
Strange Behavior of Scenario Comparison Plots

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1550]
Scenario Comparison plots produce stacked bars if Same scenario is selected multiple times.
Expected behaviour would be bars next to each other.

As you can see in the screenshots below, the two MIX_m scenario values are stacked on top of each other (separated by a thin white line). The reason why scenario MIX_m was selected twice, is that the plots only run with a minimum of 3 scenarios.

Is this intended behaviour @JIMENOFONSECA @BhargavaKrishnaSreepathi ?

![image](https://user-images.githubusercontent.com/17002288/42124786-9d9c19be-7c9b-11e8-83eb-a4d04ebe462c.png)
![image](https://user-images.githubusercontent.com/17002288/42124789-b1aa921e-7c9b-11e8-9d2b-4b45e292c3e8.png)

**Comment by gabriel-happle** [comment]
![image](https://user-images.githubusercontent.com/17002288/42124843-e0647f1a-7c9c-11e8-8831-9da8e6bf9d50.png)

**Comment by JIMENOFONSECA** [comment]
Got it. It is kind of unexpected but i guess we need to ask everybody to use different scenarios always :-). Is this something that breaks your exercise?

Btw. For now the generations/individual part does not work and it goes straight into considering the archetypes anf the same scenario. 

We need to upgrade this on wednesday evening at the latest
