### ISSUE TITLE
Bug in the emissions calculations

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1552]
Instead of subtracting the emissions from PV (saved from using solar), it is being added. Thus raising the emissions instead of decreasing them.

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi uhoh. any solution to this?

**Comment by BhargavaKrishnaSreepathi** [comment]
fixed it in the branch #1541, no longer an issue
