### ISSUE TITLE
Split up CityEnergyAnalyst.pyt into multiple tool boxes by category for faster loading

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1555]
I noticed at the course that loading the cea toolbox in ArcGIS takes waaay too long to load.
I profiled it and it seems to be an ArcGIS thing and not something we can optimize. Therefore, I propose splitting the toolbox up into smaller pieces that will each load faster.

At the same time, the list of tools as described in the cea-dashboard could be used to produce the pyt in the `install-toolbox` command - sidestepping the file `cea/interfaces/arcgis/CityEnergyAnalyst.py` - while providing a method for overloading the classes in the yaml file.

**Comment by JIMENOFONSECA** [comment]
Since we will end support for ArcGis soon, we will most likely not be able to solve this issue
