### ISSUE TITLE
service life of systems for embodied energy calculations is more likely to be 25 yrs than 40 yr

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1562]
This refers to the value stored in constants in like 24.
Let's cross check the service life of technical systems.

**Comment by martin-mosteiro** [comment]
For consistency, I looked up the amortization times for technical systems according to SIA 2032:
![2032-c1_2010_d-5](https://user-images.githubusercontent.com/18548065/42305029-9ed05f48-805b-11e8-9b35-5ed8a7a8aaec.png)
For electrical, ventilation and thermal distribution systems, they suggest 30 years, for boreholes 40 years, for heat generation systems 20 years. So 25 years might be reasonable as an average for the systems within the building.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro fixed directly into master, thanks!
