### ISSUE TITLE
Lake potential tool: Lake size parameter does not have units

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1574]
is it m^3? or Liters? nobody knows...

**Comment by martin-mosteiro** [comment]
Also, is this the most sensible way to define the potential from the lake? The key parameters should be the maximum amount you can extract without affecting the environment (m3/h), the temperature at which you can extract the water and the maximum allowed return temperature or temperature difference, no? Or are these parameters all assumed based on the lake size by the tool?

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro yes, those parameters are assumed for now. @martin-mosteiro would you mind making the respective modifications? maybe it would be good that you improve it might be strongly related to your research.
