### ISSUE TITLE
Post a tutorial of arcgis intro steps

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1576]
Cover the basic stuff Amr explained in the first two lectures.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas changing to nice to have. Form our conversations I believe we are leaving ArcGIS. I believe we should then focus on the dashboard.

**Comment by amraladdin** [comment]
Agree with @JIMENOFONSECA ... In addition, it makes sense to have a fixed release for the CEA over ArcGIS, this way we don't have to repeat creating the tutorial many times, which was the case before.

**Comment by amraladdin** [comment]
This issue has been there for a long time. I would like to decide on whether we will do this tutorial or not in our next CEA meeting.

**Comment by JIMENOFONSECA** [comment]
I suggest we do it but for the new interface.

Best, Jimeno
On 10 Jan 2019, 01:13 +0800, Amr Elesawy <notifications@github.com>, wrote:

This issue has been there for a long time. I would like to decide on whether we will do this tutorial or not in our next CEA meeting.

**Comment by JIMENOFONSECA** [comment]
closing issue, we will not offer anymore support for arcgis in a few months time, and there is no one doing this untill then
