### ISSUE TITLE
eff_cs present in LCA_infrastructure is not being used

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1580]
The column named 'eff_cs' in: CityEnergyAnalyst > cea > databases > SIN > lifecycle > LCA_infrastructure.xlsx > COOLING is not being used in CEA.
For the supply heating system, the analogue 'eff_hs' (in the 'HEATING' tab) seems to correspond to the efficiency, based on what I see on line 231 of CityEnergyAnalyst\cea\demand\thermal_loads.py, and for the dwelling hot water, the analogue 'eff_dhw' seems to be the efficiency of the supply system, based on line 153 in CityEnergyAnalyst\cea\demand\hotwater_loads.py. 

But I do not see where 'eff_cs' is used.

It is instead using COP calculations. Please look at lines 51 - 72 in `cea\technologies\heatpumps.py`

**Comment by gabriel-happle** [comment]
I'm not sure about this database structure. Maybe @JIMENOFONSECA or @shanshanhsieh know more.

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi it is used in line 183 of thermal_loads.py

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi can we close this issue?

**Comment by BhargavaKrishnaSreepathi** [comment]
looks like this is fixed quite recently, as when the issue was created, `eff_cs` was not being used. As now it seems to be fixed in CEA, we can close the issue
