### ISSUE TITLE
Make release 2.9

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1582]
@daren-thomas Hi Daren, would you mind making a release before we start working on CEA again?
thanks!!

Also, is there a planer version I can point people to? (the one we used in the computers of the executive course?

**Comment by daren-thomas** [comment]
there is a planer version in the making... it is not quite the same as what we used for the executive course - it's a setup.exe style installation. now... i have ideas on how to make this easier to do, but those would be a sprint of their own. i'll send you an installer today. i'm just finishing up with the testing (in a virtual machine, just to be sure it really works and installs) - that's all that's really missing for 2.9.0.
