### ISSUE TITLE
add more nodes that connect building to network

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1591]
more than one connection from building to network edges should be enabled in the first part of the `network_layout.py`

in the current network layout tool, there is only one way to connect a building to the thermal network (via the shortest path between building node and network edge)
however, this results in odd routes after running steiner spanning tree

**Comment by shanshanhsieh** [comment]
my approach is to add a "Near Table" which include more than one points to connect substations to networks. This way, the potential network (before entering the steiner tree) has more than one line connecting building substations to the network.
However, it is not stable yet. The modifications i made so far are committed in branch `i1591-improve-network-layout`.
@JIMENOFONSECA maybe you could give me a hand on this?
@shizhongming will need to use this PR to run the cases.

otherwise, i will pick it up after my holidays.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh sure, let's pick it up after your holidays

**Comment by shanshanhsieh** [comment]
we can check the DistrictHeatingDesign library developed from CREM
https://gitlab.com/crem-repository/dhd
