### ISSUE TITLE
Make the case study of VMarty run

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1593]
This issue aims at making the case study of @VMarty run through the demand calculation.

I will post some testing updates here to document the process.

**Comment by gabriel-happle** [comment]
issues: `coordes0` crashes during radiation calculation --> `floors_ag` column in `zone.shp` is in wrong format (`Long` instead of `Double` when opened with ArcGIS)

**Comment by gabriel-happle** [comment]
@VMarty a pull request #1592  with a fix that is currently waiting to be merged allows to run your case study.
You can either start testing yourself in branch `i1588-bugfix-ARU-model` or wait until it becomes part of the master.

The other cases `cordees0` and `cordees1` have some faulty input files.

**Comment by VMarty** [comment]
hey, @gabriel-happle, cordees2 is perfectly runninng now, thankyou for fixing this issue ! I will keep you informed of my progress.

**Comment by gabriel-happle** [comment]
cool!
I'm closing this issue then.
