### ISSUE TITLE
Check geometry inputs before processing

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1594]
This is related to observations made in #1593.
Following checks should be done when reading the input shape files:

- Check for unique values in Building Names
- Check for correct data types in other attributes `floors_bg`, ...

I'm assigning @daren-thomas for now.
Please select your priority for this issue.

**Comment by JIMENOFONSECA** [comment]
Adding to list of known issues. For now, users would need to check for that in their input files.
