### ISSUE TITLE
CEA doesn't seem to handle Terrain files with zero values very well

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1595]
@shizhongming was creating terrains for his case studies.
Sometimes the generation of geometries in the radiation script was successful, sometimes not.
The only difference we could see was that terrain files with constant elevation of `0` crashed and while terrain files with constant elevation of `1` worked fine.

Can someone please confirm/negate our observation and work on a fix or warning message @JIMENOFONSECA or @daren-thomas?

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle or @shizhongming just add a warning to the documentation in the part about running the new project tool.

**Comment by gabriel-happle** [comment]
@shizhongming can you take care of this? First I think we need to create some terrain files for testing. I.e., some files that have only a single or a few `0` elevation values.

**Comment by daren-thomas** [comment]
@gabriel-happle do we have a status update on this? how to prioritize it?

**Comment by JIMENOFONSECA** [comment]
Yep, it will just not work for terrains with 0 elevation. It seems to be a daysim problem.
