### ISSUE TITLE
pyliburo is replaced by py4design, thus the installation of the environment needs to take this change into account

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1597]
pyliburo is renamed as py4design, so the change needs to be made. Also, the folder structure in py4design is different than what it used to be for pyliburo. This impacts the radiation scripts in CEA. 

The problem is faced when we are creating the CEA environment afresh

**Comment by JIMENOFONSECA** [comment]
@daren-thomas the best for this is to keep the old version of pyliburo. We do not know what else has changed, and it would be too much work to connect to the new version of the library. I think the problem is that a fresh installation of CEA is looking for pyliburo and it does not exist?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA technical debt - we've known about this for a while. yes, the old version suits our needs. and as I understand it, the installation should still be pulling it from our fork. I'll have a look and see what can be fixed.

**Comment by daren-thomas** [comment]
actually, I think keeping the old pyliburo is harder than it seemed at first... unless... we can publish the fork as pyliburo, but i think we should ask @chenkianwee first before doing this.

@JIMENOFONSECA is @chenkianwee around in singapore? Would you mind asking him in person if we can publish our fork (in his name!) to PyPI?
