### ISSUE TITLE
dbf-to-excel: clarify arguments to script

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1604]
I just ran the dbf-to-excel script:

```
cea dbf-to-excel --dbf-file "C:\reference-case-open\baseline\inputs\building-properties\age.dbf" --excel-file "C:\reference-case-open\baseline\inputs\building-properties\testing.xlsx"
City Energy Analyst version 2.7.22
Running `cea dbf-to-excel` with the following parameters:
- dbf-tools:dbf-file = C:\reference-case-open\baseline\inputs\building-properties\age.dbf
- dbf-tools:excel-file = C:\reference-case-open\baseline\inputs\building-properties\testing.xlsx
Running excel-to-dbf with dbf-file = C:\reference-case-open\baseline\inputs\building-properties\age.dbf
Running excel-to-dbf with excel-file = C:\reference-case-open\baseline\inputs\building-properties\age.xls
```
Notice how the output file (`testing.xlsx`) is not used, but instead the output file is derived from the name of the input file.

Is this the behavior that we want? 

- if so, we need to change the interface to just accept `dbf-file`.
- else, we need to change the script to use `excel-file` as input.

Also, check `excel-to-dbf` for similar behavior.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can you please provide some input in how the tool _should_ work? Fixing it should be a piece of cake.

**Comment by JIMENOFONSECA** [comment]
So what I understand is that it should convert from excel to dbf and viceversa. If an excel file is the input, then it converts to dbf. if a dbf file is input then it is converted to excel.

**Comment by daren-thomas** [comment]
Yes, that's exactly what it does. Just the question is _how_. How is the output name chosen? Is it a parameter to the script? Or is it just the name of the input file with the new extension? Currently, it pretends to do the first, but ends up doing the second. So we should just decide which way we want it.

**Comment by JIMENOFONSECA** [comment]
I think the name can be selected by the user once he/she selects the output directory.

The parameters to ask the user are: 1. the location of the file, and 2. the output to locate the new file (including the name of the new file). The default name is the name of the input file.

Does it work like this?
On 17 Aug 2018, 21:52 +0800, Daren Thomas <notifications@github.com>, wrote:

Yes, that's exactly what it does. Just the question is how. How is the output name chosen? Is it a parameter to the script? Or is it just the name of the input file with the new extension? Currently, it pretends to do the first, but ends up doing the second. So we should just decide which way we want it.
