### ISSUE TITLE
Check scripts.yml for orphan scripts

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1616]
They are listed in the category "default" - I'm not quite sure what to do with some of them. Others, could be added to an interface (`cea-dev`) for more techie usage (like `compile` - but, tbh, we haven't used that script in soooo long!).

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this still a should have? if not maybe we can assign it lower priority or close it?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA please keep it.

**Comment by JIMENOFONSECA** [comment]
I checked this in several PR's already...we keep what is in there for now...
