### ISSUE TITLE
As a researcher I want to know what features CEA does not longer support so I can also use them independently

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1623]
I think this script is orphaned... When I tried to run it, I got this:

```
C:\Users\darthoma\AppData\Local\conda\conda\envs\2018.09.19\python.exe C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/resources/radiation_daysim/create_gml.py
DEBUG:shapely.geos:Trying `CDLL(C:\Users\darthoma\AppData\Local\conda\conda\envs\2018.09.19\Library\bin\geos_c.dll)`
DEBUG:shapely.geos:Library path: 'C:\\Users\\darthoma\\AppData\\Local\\conda\\conda\\envs\\2018.09.19\\Library\\bin\\geos_c.dll'
DEBUG:shapely.geos:DLL: <CDLL 'C:\Users\darthoma\AppData\Local\conda\conda\envs\2018.09.19\Library\bin\geos_c.dll', handle 24680000 at 10531908>
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
Traceback (most recent call last):
  File "C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/resources/radiation_daysim/create_gml.py", line 182, in <module>
    scenario_path = gv.scenario_reference
AttributeError: 'GlobalVariables' object has no attribute 'scenario_reference'
```

It seems it hasn't been run in a very long time...

@JIMENOFONSECA I have taken the liberty of assigning this to you as you are mentioned in the credits and probably the only one on the team who knows for sure what this script is for... I think we can safely remove it. What do you think?

**Comment by JIMENOFONSECA** [comment]
mmm. It would be great to keep it somewhere, it was a hard thing to do and it might be useful if we want to use CITYGML format one day. I wonder If another repository could do? what is your opinion?

________________________________

**Comment by daren-thomas** [comment]
My opinion is to remove any code that doesn't run. You could keep it in a [gist](https://gist.github.com/) for later - and create an issue pointing to the gist so that the code be found later via google...

Keeping dead code is just making the codebase harder to understand for new / existing developers because you never know if it's really safe to delete or not.

**Comment by JIMENOFONSECA** [comment]
Got you. Let’s trash it! :-)

Best, Jimeno
On 21 Sep 2018, 18:16 +0900, Daren Thomas <notifications@github.com>, wrote:

My opinion is to remove any code that doesn't run. You could keep it in a gist<https://gist.github.com/> for later - and create an issue pointing to the gist so that the code be found later via google...

Keeping dead code is just making the codebase harder to understand for new / existing developers because you never know if it's really safe to delete or not.

**Comment by JIMENOFONSECA** [comment]
I made this a bigger issue which entails moving scripts of CEA we will not support anymore as of now. Still we will keep them for the next year at least in our repository, so other researchers can access them.
