### ISSUE TITLE
Add radiation to testing

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1626]
As a consequence of #1620 and #1624 I think the radiation script should be part of the Jenkins tests.
@daren-thomas I'm assigning this to you. You can decide the priority and milestone.

The testing could be done on a single building with a larger sensor grid, instead of the whole case study, in order to save computational time.

**Comment by daren-thomas** [comment]
good point!

**Comment by daren-thomas** [comment]
this would be part of running the cea workflow scripts - addressed in a separate issue.
