### ISSUE TITLE
As a Researcher, I want to learn how to make the streets.shp file

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1636]
A person who wants to use CEA needs to know how to create the streets shapefile.

- what is the format of this file? POLYLINE? MULTIPOLYLINE?
- this should be part of the documentation along with the description of how to create all the other input files?
- this could be a tutorial, linked from the readthedocs

**Comment by JIMENOFONSECA** [comment]
@daren-thomas could you write what the problem is briefly and who needs it? It will help me to prioritise it.

**Comment by JIMENOFONSECA** [comment]
solved in issue #1858
