### ISSUE TITLE
The disconnected script (decentralized?) is only defined for regions "CH" and "SIN"

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1639]
This is evident in the following code:

```
def disconnected_building_main(locator, building_names, config, prices, lca):
    """
    This function computes the parameters for the electrical demand contributing to the pareto optimal alternatives.
    in the future, this aspect should be included in the optimization itself.

    :param locator: locator class
    :param gv: global variables class
    :type locator: class
    :type gv: class
    :return: elecCosts, elecCO2, elecPrim
    :rtype: tuple
    """
    if config.region == 'SIN':
        decentralized_buildings_cooling.disconnected_buildings_cooling_main(locator, building_names, config, prices, lca)
    elif config.region == 'CH':
        decentralized_buildings_heating.disconnected_buildings_heating_main(locator, building_names, config, prices, lca)
    else:
        raise ValueError("the region is not specified correctly")

    print "Run decentralized model for buildings"
```

The issue here is the hard-coding of the regions. The code should not be hard-coded to specific regions as those can be defined by the user. E.g. region "custom". And the tool should be usable in other regions too. Also, this assumes the network can only be a heating network for region=CH. Is that a valid assumption?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh is this still the case? We got rid of the region parameter and we did not noticed it while at it

**Comment by shanshanhsieh** [comment]
there is no region parameter in that script now

this is how it looks like:
![image](https://user-images.githubusercontent.com/16998305/56349002-3cb93600-61fa-11e9-989d-577343184be7.png)

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA fixed this.
