### ISSUE TITLE
As a practicioner, I want to quickly know if my input files are valid, so that I can fix invalid ones

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1647]
CEA often breaks down with cryptic error messages that are hard to fix.
I feel like a lot of trouble could be avoided by checking the input files before running computationally expensive calculations.

This epic contains a collection of issues connected to that.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle do you need more 'error messages' and assertion tools for that besides those added to the new project tool, the optimization, and the radiaton tool? if so maybe we can close this issue and open new ones, should a problem occur?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA @gabriel-happle, we have been working on this with @Jack-Hawthorne: a collection of the schema (and datatypes) of input files needed for scripts to run. The way the new project tool (and others) check the input data is ad-hoc and useful for some specific cases like checking geo stuff and tiff stuff. Given the meta-data we have collected (and are still collecting) we can provide a declarative description of the input file formats and write a function that can check inputfiles given the script name. That would solve this issue. Please keep it open. I think we should even consider promoting it to "Must have". (also, it will be easy to do given the meta data!)

**Comment by JIMENOFONSECA** [comment]
@daren-thomas update?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I'm still waiting for the workflow to run through to be able to collect the information for the last few scripts. Some parts of this issue are implemented: For those scripts where we have metadata, the input files are checked for existence as a pre-condition to running the script and a hint is printed out to the user with recommendations on what scripts to run first.

In the next step, actually checking the schema of the input files could be added - we have the metadata setup to do this. This also touches what we discussed yesterday about scripts working on Dataframes as opposed to file paths.

**Comment by JIMENOFONSECA** [comment]
maybe we close these epics and maintain the individual issues going....It keeps the number of issues tighter.
