### ISSUE TITLE
As a practioner, i would like a guide on how to estimate energy potentials from various solar technologies

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1653]
Write a guide on how to use the results from solar technology simulations:
1. How to pre-filter the combination of technologies to simulate? (e.g. PV1+FP or PV2+ET...)
2. What are the thresholds for? and how to set up a threshold?
3. Estimated simulation time for the user's reference

**Comment by JIMENOFONSECA** [comment]
1.5 years in here, we will not have it anytime soon. Closing it. This is the general case for most tools and not a critical component of the documentation.
