### ISSUE TITLE
As a researcher, I want to be able to run add a new region to the CEA

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1656]
Based on discussion with @daren-thomas, it appears that 'CH' and 'SIN' are hard-coded as the only possible choices in the radiation script.

Updating databases by researcher.

But also remove hardcoded checks for region.

**Comment by daren-thomas** [comment]
@martin-mosteiro not quite sure... essentially, you could start by checking each use of `region` in the code looking for `if` statements and similar constructs... first glance:

- `chiller_absorption.py` might need some checking
- `decentralized_building_main.py` definitely needs checking (but could be fixed maybe by checking another parameters, like... `district-cooling-network`? or `network-type`? see #1664)
- `lca_calculations.py` - aren't you the specialist here? lines 110-117: why even bother with the `if` statement here??
- `solar_equations.py` - basically, need a way to get timezone string from region name - this could be as easy as a file TIMEZONE inside a region database

The rest should be ok... I don't think it'd take long to fix. And probably easiest to do it when adding Dutch case. In fact... If you have time before, You could copy `SIN` folder to `SG` and fix it to accept that region, then delete `SIN` region... This would be an elegant way of also moving to the international region codes!

**Comment by martin-mosteiro** [comment]
Thanks for the answers, @daren-thomas. `lca_calculations.py` is not mine, it's @BhargavaKrishnaSreepathi's code. Agree that the `if` statement is unnecessary. I created a new branch and started taking care of the low hanging fruit.

**Comment by martin-mosteiro** [comment]
This issue is solved by PR #1682.
