### ISSUE TITLE
Energy Supply plot does not handle the buildings parameter

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1658]
While refactoring the plots code, I noticed that some of the plots (e.g. Energy Supply and Energy Demand) will write out plots specifict to a building (i.e. produce a file `basic/demand/Building_B01_energy_supply`) but that plot is exactly the same as the district version except for the title.

**Comment by JIMENOFONSECA** [comment]
being fixed in #1880

**Comment by daren-thomas** [comment]
@JIMENOFONSECA specifically the energy supply plot is _not_ addressed in #1880. This is a separate issue.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I added it to that, it was a quite simple problem to solve in that PR. It was the same problem with the Energy Demand plot

**Comment by daren-thomas** [comment]
Yeah, I just saw that and came here to update my comment :) thank you!
