### ISSUE TITLE
What should we do with test_sensible_loads.py?

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1660]
The code in ``cea/tests/test_sensible_loads.py`` is commented out. Therefore, these tests are not being run at all.

- are they still relevant? 
  - yes: uncomment and perhaps fix them
  - no: remove the file

**Comment by daren-thomas** [comment]
@gabriel-happle it seems you commented out the code. Can we assign this issue to you? (also, using tripple quotes to comment stuff is semantically incorrect, use ``#``. but also, commenting out blocks of code just leaves future developers, possibly yourself, wondering whether that code can be safely removed or not)

**Comment by gabriel-happle** [comment]
@daren-thomas I deactivated this code because I changed the input parameters to the function it is supposed to test.
If it's OK for you I would just remove it.

**Comment by daren-thomas** [comment]
Either change the function or remove it please.

**Comment by gabriel-happle** [comment]
OK. I will remove it then and create a PR.

**Comment by daren-thomas** [comment]
@gabriel-happle nice job! closed!
