### ISSUE TITLE
As a Researcher, I'd like to know why there are different `network-type` parameters

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1664]
This is the list of parameters currently used that are called `network-type`:

- thermal-network:network-type
- plots:network-type
- plots-optimization:network-type
- plots-supply-system:network-type
- plots-scenario-comparisons:network-type
- network-layout:network-type
- multi-criteria:network-type

Why do we need 7 different ones? What are the differences? When to use which one?

**Comment by shanshanhsieh** [comment]
In terms of input argument, they are all the same: `DC` or `DH`.
Reasons:
1. The decisions (on network-type) made in these tools are not connected. For example, you can simulate a DC but plot a DH, although, this is unlikely to happen if you are using the tools in a streamlined process (first simulate DC and then plot DC).
2. At the time we made the ArcGIS interface, it was the easiest way to include this argument.

We can totally combine it as long as this input is still presented in each tool (network simulation, network layout, plotting, supply system simulation, multicriteria)

**Comment by daren-thomas** [comment]
@shanshanhsieh - well, providing the input in all the tools is as easy as listing it in the parameters part of the tool in the scripts.yml file.

we could promote it to the `[general]` section, since it seems to be a statement about the whole project as opposed to a specific script. what do you think?

**Comment by shanshanhsieh** [comment]
yes, it is project specific, but we haven't consider the case with both DC and DH yet
if we promote it to general, we should allow the input to be a list:
case study 1, only DC: `network-type=DC`  -> call all the scripts with the argument `DC`
case study 2, only DH: `network-type=DH`  -> call all the scripts with the argument `DH`
case study 3, both DC & DH: `netowrk-type=DC DH` -> first call all the scripts with the argument `DC` and then call all the scripts with the argument `DH`

**Comment by daren-thomas** [comment]
@shanshanhsieh I'm missing a bit of knowledge here, maybe you can help me out: can the zug reference-case also be run with network-type=DC? will that calculate anything meaningful? how to interpret the results?

**Comment by BhargavaKrishnaSreepathi** [comment]
Yep, currently multi-criteria is set only for DC cases and not DH cases. This needs to be added into CEA.
