### ISSUE TITLE
As a contributer, i want to refactor substation_matrix.py script (replica of substation.py)

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1670]
the `substation_matrix.py` is only used by the thermal network simulation routine, part of the functions are replicas of `sunstation_matrix.py`, which is used by the system optimization routine.
an update is required after refactoring `substation_matrix.py` in #1622

**Comment by daren-thomas** [comment]
@shanshan - is this a must-have or a should-have? what is the status here?

**Comment by shanshanhsieh** [comment]
the respective scripts are working just fine, and not creating problems for now... but it is a logical step to take to avoid duplicate codes, so i guess it falls to should have?

however, there are some steps we can do before solving this issue: create unit tests for all functions in `substation.py`
After that, what left to be done in this issue is to compare duplicate functions in `substation-matrix.py` with the original ones in `substation.py`, and then decide to delete the function (if identical) or rename the function (if different)

**Comment by JIMENOFONSECA** [comment]
1.5 years in here, we will not have it anytime soon. Closing it.
