### ISSUE TITLE
As a practitioner, I would like to know about the new release of CEA, so I can use the latest version

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1683]
I have a list of people who donwloaded CEA. I planned to send an e-mail stating what is new and why they should download the new version.

**Comment by JIMENOFONSECA** [comment]
This is blocked by #1680 and #1582

**Comment by daren-thomas** [comment]
merged #1680 and created release.

**Comment by JIMENOFONSECA** [comment]
Please include the video to CEA in the newletter

**Comment by JIMENOFONSECA** [comment]
Hi all,

This is to announce that the first Newsletter of CEA was sent to 129 unique users of CEA

https://mailchi.mp/b3814dfddd65/announcing-a-new-cea-and-more
Jimeno
