### ISSUE TITLE
As a contributor, I want to add in part load calculations in decentralized heating similar to decentralized cooling case

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1685]
Decentralized Heating currently takes into account the combined load of AHU, ARU and SHU. The script needs to include part load combinations such as AHU only, ARU only, SHU only, AHU+ARU, ARU+SHU, AHU+SHU.

This has been implemented for cooling case, need to be extended for heating case

**Comment by JIMENOFONSECA** [comment]
Updating this for the executive course

**Comment by JIMENOFONSECA** [comment]
1.5 years in here, we will not have it anytime soon. Closing it. @shanshanhsieh is this still a known issue?
