### ISSUE TITLE
As a contributor, I would like to have supply-system-simulation for heating case as is being done for cooling case

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1686]
Currently few parts of the `supply-system-simulation.py` script only works for cooling case. This needs to be extended for heating case too.

**Comment by JIMENOFONSECA** [comment]
This should go for the executive course, I am increasing the priority to this.

**Comment by gabriel-happle** [comment]
maybe @martin-mosteiro can hire a student to help.
This has to be discussed with @JIMENOFONSECA.
This issue should go hand in hand with the refactoring of the optimization code.

**Comment by JIMENOFONSECA** [comment]
done in #2120
