### ISSUE TITLE
As a researcher, I want to know when is the optimization converged for various case studies

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1687]
As the title says, optimization using genetic algorithm need to be tuned to find the ideal combination of number of generations and individuals. Also, these are to be tested on multiple case studies and a thumb rule be developed for when dealing with similar amount of buildings.

There also needs to be tradeoff between the accuracy of the solutions and the amount of computational time that goes into calculating them. For example if we get 95% Pareto front in about 10% of the time compared to 100% Pareto front in 100% time, it is better to go with the 95% one.

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi I believe we are not doing this in the near future.
