### ISSUE TITLE
As a researcher I want to develop a rule of thumb for the optimization parameters

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1689]
Optimization parameters like number of generations, individuals, hall of fame size, euclidean distance, convergence matrix need to be decided for different scenarios

1. Small scale scenarios (~10 buildings)
2. Medium scale scenarios (~20-30 buildings)
3. Large scale scenarios (~100 buildings)

**Comment by JIMENOFONSECA** [comment]
I believe we are not doing this in the near future. Closing this issue and adding it to enhancements
