### ISSUE TITLE
As a developer, I would like `general:region` to be a RegionParameter so I can create new regions.

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1695]
The general:region is defined as a ChoiceParameter, but we should introduce a "RegionParameter" class that is like a ChoiceParameter, but sets the list of available choices to the folders in the cea databases folder + "custom".

Let's add a "RegionParameter" type to the CEA so we can allow the creation of new regions.

**Comment by JIMENOFONSECA** [comment]
Closing it, there was PR already merged about this

**Comment by daren-thomas** [comment]
@JIMENOFONSECA re-opening. What PR do you mean? The RegionParameter has not been implemented as far as I can tell. `default.config` still lists it as a ChoiceParameter, effectively hardcoding the valid list of regions the CEA knows about.

Maybe I'm missing some of the discussion here?

**Comment by JIMENOFONSECA** [comment]
oh, sorry, I saw one PR was merged attached to this issue…

but, maybe we do not need the region issue anymore sisnce we are going to move it only to the data helper..

**Comment by JIMENOFONSECA** [comment]
@daren-thomas alright, we are not using the region parameter anymore since PR #1878
