### ISSUE TITLE
As a user, I would like to create plots that use NFA as the reference area

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1701]
CEA plots currently use gross floor area (GFA) as a reference floor area. This is because it is more in line with the concept of end-use energy intensity, which helps to cover more places worldwide. However, net floor area (NFA) is also important in the European context as well as in the 2000-Watt Society and Minergie. So ideally we would have both options, for example by adding a `reference-area` parameter to the config files, changing the default.config file as follows:

```
[plots]
buildings =
buildings.type = BuildingsParameter
buildings.help = a list of buildings to run graphs or leave blank to simulate district

[...]

reference-area = GFA
reference-area.type = ChoiceParameter
reference-area.choices = GFA, NFA
reference-area.help = Floor area to be used as a reference for the plots: either ground floor area (GFA) or net floor area (NFA)
```

...and then adjusting the plot scripts as necessary.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro want to add this to CEA still?

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA I still think it'd be useful, but it's not a priority for me.

**Comment by JIMENOFONSECA** [comment]
this won't happen any time soon, so we close it
