### ISSUE TITLE
As a researcher, I would like there to be a unit test for the optimization scripts

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1703]
PR #1682 created issues for the optimization script, which I didn't notice since (a) I did not test the script manually, and (b) there are no unit tests for these scripts.

I wrote a script to take a first stab at the issue but will probably need to recruit @daren-thomas to convert my simple script into a full unit test as part of the dodo.

**Comment by martin-mosteiro** [comment]
The progress so far can be found on the branch **1703-unit-test-for-optimization**

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro are you working on this still? I think it would be something that we should have, ideally it is only one gen and 1 individual, otherwise, it gets too long for the Jenkins.

**Comment by martin-mosteiro** [comment]
No, not really. As I mentioned above, I wrote a little code, created a branch, and left it for @daren-thomas to take over. Don't know if he did anything though.
