### ISSUE TITLE
Make release 2.9.1

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1710]

**Comment by daren-thomas** [comment]
skip. do 2.9.2 instead, today.

**Comment by JIMENOFONSECA** [comment]
Sure!

Best, Jimeno
On 24 Jan 2019, 22:28 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> we're doing a release 2.9.2 instead. could you add the zenodo reference to the CREDITS.md file in the branch release-2.9.2? Thank you!
