### ISSUE TITLE
As a Practitioner, I would like to know how to model existing urban heating networks

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1717]
When setting up a case study, how do I model existing urban heating networks? What files do I need to provide? How do I make sure the network is being used?

(Asking for Anja who has such a case)

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh could you please adrees this issue? Thanks!

**Comment by shanshanhsieh** [comment]
yes, i will write a tutorial

**Comment by shanshanhsieh** [comment]
merged with PR#1717
