### ISSUE TITLE
As a Practitioner, I would like to know how to deal with basements that do not have the same footprint as the main building

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1718]
In some buildings of the case study, only parts of the buildings have basements.

(Asking for Anja who has such a case study)

**Comment by JIMENOFONSECA** [comment]
What will change is that the building has slightly lower losses towards the ground in winter. We have identified the total losses to the underground (basement vd/no basement) of be about 2%-4%. 

If this still a need. I would suggest to keep the basement equal to the footprint but to change the height until the volume of the real basement be covered. This shoudl be a way around
