### ISSUE TITLE
As a Practitioner, I would like to know how to model extensions to buildings that differ in height

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1720]
How do I go about extensions of buildings that differ in building function and height to the main building? If I model them as individual buildings as I have done so far – the results are not correct…. 

Is it possible to define if such an extension is a thermal zone or not (open to the outdoor at one front for example in that case like a porch)

@Anja: what do you mean by "the results are not correct..."?

**Comment by JIMENOFONSECA** [comment]
This is one of the current limitations. There are some issues opened but there has not been the time nor the people to do it. #806 

We are open to any master student, who would like to develop this specific setting, and coach him/her.

I assign it to @gabriel-happle since it lies in his realm. Gabriel, let us know if you have a way around solution, thanks!

**Comment by gabriel-happle** [comment]
I also wonder about "the results are not correct" part?
Do we have any examples? Or any models we can compare to measured data?

**Comment by AWillmann** [comment]
What I meant was that the building in total consumes more energy than the single parts of the building individually - this is only important let´s say given the case I want to visualize the total heating demand of each building per year. Then my building does not consume (visually) as much as it actually does. (Is this confusing?)

**Comment by daren-thomas** [comment]
@AWillmann wait... are you talking about the visualization in ArcGIS? So... while the simulation results for each part is correct, when you display the building consumption, it only looks like a single building with a lower total consumption? I think this could be solved with some ArcGIS skills...

**Comment by gabriel-happle** [comment]
@AWillmann why don't you just modify the results file (everything is in editable *.csv format) to visualize exactly what you want?

**Comment by daren-thomas** [comment]
@gabriel-happle can you add a milestone for this, since it is in development? What is the status?

**Comment by gabriel-happle** [comment]
@daren-thomas can we close this?
