### ISSUE TITLE
[Installation Problem]i can't install the cea for Arcgis10.5

### ISSUE THREAD

**Issue by hoseq** [architecture-building-systems/CityEnergyAnalyst#1722]
When i want to install cea for argis10.5 follow the manual(https://city-energy-analyst.readthedocs.io/en/latest/installation-on-windows.html),i have some problems .
    Here is the questions:
    When i go to the 6 step(the follwing figure1),I have this problem:“系统找不到路径”（in english is "The system can't find the path"）.(figure2)
![image](https://user-images.githubusercontent.com/45525658/49620782-5ef5a880-f9fd-11e8-92a6-0cec1a5e98d4.png)
(figure1)
![image](https://user-images.githubusercontent.com/45525658/49620807-7af94a00-f9fd-11e8-8d59-17745bda2399.png)
(figure2)
PS:
I think the problem may occur in step 3(figure3),and figure 4 is how i do it, can you help me see what's wrong in it(especially the path)?
![image](https://user-images.githubusercontent.com/45525658/49620829-982e1880-f9fd-11e8-858d-6435da73c63f.png)
(figure3)
![image](https://user-images.githubusercontent.com/45525658/49620852-ab40e880-f9fd-11e8-86f8-6e0af8df656f.png)
(figure4)

**Comment by hoseq** [comment]
my gmail:dzq19941213@gmail.com

**Comment by daren-thomas** [comment]
@hoseq, you are correct: you made a small mistake between step 3 and 4.

The instructions are set up to use the defaults for the "Local path" field in figure4. While you can choose any folder you like, typically it would be `C:\Users\12195\Documents\Github\CityEnergyAnalyst`. It seems you added in a `cd Documents` to replace `Documents` there.

`cd` is a command for the anaconda prompt (actually, it's for the shell in general) and means "Change Directory". So step 6 is about navigating to the directory you cloned the CEA repository to. The error message you are getting is your system saying you don't have such a directory - as per figure4, your directory is most likely `C:\Users\12195\cd Documents\Github\CityEnergyAnalyst` and step 6 would become: `cd "cd Documents\Github\CityEnergyAnalyst"`. I suggest first deleting that folder, though and repeating steps 3 and 4.

@hoseq could you please report back on whether that fixes your issue?

**Comment by hoseq** [comment]
@daren-thomas ,thanks!Your help was greatly appreciated. I got it. But I have some new problems😂 ,it could happend in "2".
1.When i change the path to"C:\Users\12195\cd Documents\Github\CityEnergyAnalyst", the work of the Installation seem complete.(picture1)
![image](https://user-images.githubusercontent.com/45525658/49772210-57007600-fd27-11e8-81a5-71bbc353effb.png)
(picture 1)
2.Then i go on the next step--"Configuration of Pycharm".（picture2）is my operation,Is there anything wrong in this step.
![image](https://user-images.githubusercontent.com/45525658/49772721-4650ff80-fd29-11e8-9563-d32b8e8d1049.png)
(picture 2)
3.i install the "Setup_CityEnergyAnalyst_2.9.0" (picture 3)of the cea files which download from "https://github.com/architecture-building-systems/CityEnergyAnalyst/releases "
![image](https://user-images.githubusercontent.com/45525658/49772941-16562c00-fd2a-11e8-9e1a-1e44895f4ac4.png)
(picture 3)
4.In the end , i open Aicgis.In my toolbox is nothing.(picture 4)
![image](https://user-images.githubusercontent.com/45525658/49773159-e65b5880-fd2a-11e8-96ec-02c434f7535f.png)
(picture 4)

**Comment by daren-thomas** [comment]
@hoseq yes, in picture2, you are creating a new conda environment instead of using the one created in step 7. Choose an existing conda environment. If you are not sure about the path of the environment, you can find it out by running `conda env list` in the anaconda prompt. It will list your `cea` environment along with the path. Use that in PyCharm, selecting the `python.exe` file in that folder.

Do not install the `Setup_CityEnergyAnalyst_2.9.0,exe` - you have already installed this with the steps above. The installer is a shortcut for users who do not want to edit the code in PyCharm.

**Comment by hoseq** [comment]
@daren-thomas .oh!Thanks. 😂I am the user who do not want to edit the code in PyCharm.I just install cea for my Arcgis 10.5 . So i can just install  "Setup_CityEnergyAnalyst_2.9.0,exe"?
  I try it.And,but the cea does not appear in My Toolboxes.(picture 1)

![image](https://user-images.githubusercontent.com/45525658/50001749-c9e44800-ffd8-11e8-8549-8c6f004ecba1.png)
(picture 1)
And this is the information of installation(picture 2)
![1 2](https://user-images.githubusercontent.com/45525658/50001736-bfc24980-ffd8-11e8-82f7-d923b56adf39.png)
(picture 2)

**Comment by daren-thomas** [comment]
@hoseq, oh dear, then you really went the hard route! I'm so sorry!

Yes, I see your problem. This is currently being fixed, but a new version won't be available for another week or so.

**Comment by daren-thomas** [comment]
@hoseq, please try again, it should work now.

**Comment by gabriel-happle** [comment]
Dear @hoseq,

In order for us to better understand the needs of our users and steer the development of the tool in the future we would like to understand why and how you are using the CityEnergyAnalyst.

Please help us by answering 10 short questions in the [CEA user survey](https://forms.gle/6nR8V5JEDM593g5eA).
The feedback we receive will determine the focus of the upcoming development efforts.

Kind regards,
The CEA development team
