### ISSUE TITLE
ImportError: DLL load failed fiona.ogrext

### ISSUE THREAD

**Issue by justinfmccarty** [architecture-building-systems/CityEnergyAnalyst#1734]
Hello! I am working on getting the CEA set up for use in ArcGIS for retrofit analysis in Vancouver, CA. I also have very little familiarity with python. I have been following the [install guide ](https://city-energy-analyst.readthedocs.io/en/latest/installation-on-windows.html) but have not been able to move past the intial scripts for analysis. Once I am set up in Pycharm and have extracted the reference case I move to running a `demand_main.py` or `solar_collector.py` I recieve the error
`ImportError: DLL load failed: The specified module could not be found.` 

For `demand_main.py` and `radiation_main.py` the most recent call:
**File "C:\Users\justi\Anaconda2\envs\cea\lib\site-packages\fiona\collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: DLL load failed: The specified module could not be found.**

For `solar_collector.py` the most recent call:
**File "C:\Users\justi\Anaconda2\envs\cea\lib\site-packages\osgeo\__init__.py", line 21, in swig_import_helper_mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: The specified module could not be found.**

I have found in several other posts regarding this error the fix related to moving the `proj.dll` file to the _C:\Users\your_name\Anaconda2\envs\cea\Library\bin_ folder but it was there from the install. I also created two paths - a fix I saw in another post (image 1).  

I have reinstalled a few times, but happy to try again. The toolbox shows up in ArcScene (10.5) Please let me know what system info you need from me to diagnose. 

_-Image 1-_
![user variables_12-17](https://user-images.githubusercontent.com/44881937/50121550-eddc9f00-020d-11e9-8c1e-d40ee78fc7c6.PNG)

Thank you for any assistance,
Justin

**Comment by daren-thomas** [comment]
@justinfmccarty thank you for this bug report! We are currently trying to fix a problem with the conda environment step of the installation process. I will contact you again on this issue as soon as we can find a fix. Sadly, this might be _after_ the holidays. I hope you understand.

**Comment by justinfmccarty** [comment]
Daren,

Thank you for letting me know. No problem on my end. I will stay tuned. Happy Holidays!

**Comment by gabriel-happle** [comment]
Dear @justinfmccarty ,

In order for us to better understand the needs of our users and steer the development of the tool in the future we would like to understand why and how you are using the CityEnergyAnalyst.

Please help us by answering 10 short questions in the [CEA user survey](https://forms.gle/6nR8V5JEDM593g5eA).
The feedback we receive will determine the focus of the upcoming development efforts.

Kind regards,
The CEA development team
