### ISSUE TITLE
UnsatisfiableError

### ISSUE THREAD

**Issue by billpoon12138** [architecture-building-systems/CityEnergyAnalyst#1736]
I tried to install the cea (branch release-2.9.0) following the tutorial in ubuntu 18.04.1 LTS, and I encountered the below issue.

After the command : conda env create --file environment.ubuntu.yml
Got the following error:

Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - fiona[version='>=1.7.8']
  - libnetcdf[version='>=4.4.1.1']
  - pythonocc-core=0.18
Use "conda info <package>" to see the dependencies for each package.

I am not really familiar with yml, and wondering if anyone has encountered the same problem and fixed?

Thanks.

**Comment by daren-thomas** [comment]
@billpoon12138 this error basically means that the `environment.ubuntu.yml` file is not up to date and that conda cannot create a python environment to run cea.

We will be looking into this after Christmas 2018.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas Any update? I believe we have the environment for linuk/ubuntu ready?

**Comment by gabriel-happle** [comment]
Dear @billpoon12138 ,

In order for us to better understand the needs of our users and steer the development of the tool in the future we would like to understand why and how you are using the CityEnergyAnalyst.

Please help us by answering 10 short questions in the [CEA user survey](https://forms.gle/6nR8V5JEDM593g5eA).
The feedback we receive will determine the focus of the upcoming development efforts.

Kind regards,
The CEA development team

**Comment by JIMENOFONSECA** [comment]
@billpoon12138 we just updated the environment and included instructions to run CEA in linux. let us know if we can close this issue

**Comment by billpoon12138** [comment]
> @billpoon12138 we just updated the environment and included instructions to run CEA in linux. let us know if we can close this issue

**Comment by billpoon12138** [comment]
@JIMENOFONSECA Thanks for your reply and update, and it works very well now.
