### ISSUE TITLE
As a user, I would like to know what ArcGIS is actually used for

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1739]
The CEA installation guide says the following:
_"Download and install ArcGIS 10.5 - only if you would like to use ArcGIS visuals."_
This is not entirely true - as it turns out, you also need ArcGIS for the thermal network layout script, which is not a visualization tool. Furthermore, both for heatmaps and thermal network layout you need to install Background Geoprocessing as well – this is not indicated anywhere in the manual.

So the CEA installation manual should be updated to account for both of these things.

**Comment by martin-mosteiro** [comment]
(Also leaving a note for future reference for potential master's students from ETH: the IT shop only provides students with ArcGIS 10.6, not 10.5. So they need to be able to get the correct version to use CEA.)

**Comment by daren-thomas** [comment]
@Jack-Hawthorne could you please update the documentation to reflect the fact that the CEA will work with both ArcGIS 10.5 _and_ 10.6 and needs the Background Geoprocessing tools for the network layout scripts to run?
