### ISSUE TITLE
As a user, I would like to be able to run CEA on a clean install without manually installing fiona and gdal

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1741]
After a clean install of CEA following the installation guide, the following issue appears when trying to run the demand: `importerror: no module named fiona [...]`

Manually installing GDAL‑2.2.4 and Fiona‑1.8.4 (available [here](https://www.lfd.uci.edu/~gohlke/pythonlibs)) by downloading the files and doing (for my specific case) `pip install gdal-2.2.4-cp27-cp27m-win_amd64.whl --upgrade` (and the same for fiona) does the trick, but they should rather be installed as part of `pip install -e .[dev]`

**Comment by daren-thomas** [comment]
totally aggree. working on it!

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro it works now, please follow the steps of the PR  #1734 to get it up and running.
