### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1749]
Next steps to reporduce:

1. go to master.
2. Reinstall CEA from scratch.
3. run cea dashboard

![image](https://user-images.githubusercontent.com/8973186/51456349-4e6c7800-1d88-11e9-801b-35e41730cb76.png)

4. Open the browser and get this

![image](https://user-images.githubusercontent.com/8973186/51456366-62b07500-1d88-11e9-80c2-58661a3d721b.png)

Then we get these messages

![image](https://user-images.githubusercontent.com/8973186/51456390-78259f00-1d88-11e9-9ad2-3e8502a7ea34.png)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA this works on my computer. could you please re-check?

**Comment by JIMENOFONSECA** [comment]
Mmm, did you run it from a fresh installation of CEA? As of master?

Might it be that your computer is calling the old cea-dashboard repository?

Maybe I am missing some extra libraries or 3rd party plug-ins?

What do you think?
On 21 Jan 2019, 19:52 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> this works on my computer. could you please re-check?

**Comment by daren-thomas** [comment]
see PR #1752. i think now it works. there were some files missing due to the .gitignore file.
