### ISSUE TITLE
Ensure the Grasshopper plugin works 

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1761]
- for Canada 19th February 2019
- i wonder if project honey-badger is ready by then to do this?

**Comment by shizhongming** [comment]
I updated to the current version of CEA and tested the plugin.
Some worked well and a few did not. I was able to fix them but one.

Thermal-network (used to be call thermal-network-matrix) works well with Pycharm and command line. It can also run with Grasshopper but it just never finishes running...keeps running and I need to force close rhino...I cannot figure it out why....could you have a look @daren-thomas 

p.s. I committed the my changes on Branch  grasshopper--for-2.9.2

**Comment by daren-thomas** [comment]
@shizhongming I can't see your branch - did you push to github after committing?

**Comment by shizhongming** [comment]
@daren-thomas
.....I thought I did...it requires me to sign out and sign in again to successfully push just now...
it is there now. 
grasshopper--for-2.9.2

**Comment by daren-thomas** [comment]
@shizhongming I just updated your branch (`grasshopper--for-2.9.2`) from master. we should probably figure merge soon or create a new branch with your changes...

As far as I can tell your only change is adding the `thermal-network-costs` script? Is that correct?

I'm not sure about the thermal-network script - it takes _forever_ to run and my guess is that it is actually running without a problem, but it's not producing output. I'll need to test this some other time as I need this computer tomorrow morning...

**Comment by daren-thomas** [comment]
@shizhongming is going to restart with a new branch based on master (2.14) and create a pull request.

**Comment by shizhongming** [comment]
Hi @daren-thomas  ,
In making the blog on the current version of CEA-Grasshopper, it raised the following error when running `dbf-to-excel-to-dbf`. I believe this error is block all other commands on Grasshopper. Could you give it a look?
![error](https://user-images.githubusercontent.com/16640327/58074254-61c50e00-7bd7-11e9-8bb9-a1341362999e.PNG)

**Comment by daren-thomas** [comment]
Hi @shizhongming I think that would come from an old version of the cea-grasshopper plugin. Did you do a `cea install-grasshopper`?

**Comment by daren-thomas** [comment]
![image](https://user-images.githubusercontent.com/2969564/58107617-82e32a00-7bea-11e9-9c9a-2bdfd3dc0f3b.png)

**Comment by shizhongming** [comment]
@daren-thomas I think I remembered to do that every time I updated. Probably I forgot this time...It works now....Now, I am testing all the commands in Grasshopper now and I will give an update soon. :)

**Comment by shizhongming** [comment]
@daren-thomas Hi, I am using the installer v2.14..and did the command `cea install-grasshopper`...it still reverted me the same error.. then I tried on another computer...the other computer cannot go through the `cea install-grasshopper`..

**Comment by shizhongming** [comment]
<img width="645" alt="image" src="https://user-images.githubusercontent.com/16640327/58540430-efce7380-822b-11e9-98ee-ea9f14cfd3e3.png">

**Comment by daren-thomas** [comment]
hi @shizhongming i think the installation didn't run through cleanly on that computer. the hint: it's trying to use the python from my user account! can you do this:

`C:\Users\Admin\Documents\CityEnergyAnalyst\Dependencies\Python\python.exe -m pip install -e "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst`

**Comment by shizhongming** [comment]
@daren-thomas following your solutions above. The `cea install-grasshopper` works now. However, there is another issue....as in the picture. The `cea install-grasshopper` command seems to not create a config.py file? in the folder of Rhino? Reynold was trying to help, but we couldnt figure out how....
![image](https://user-images.githubusercontent.com/16640327/58628202-ae14fa00-830b-11e9-8fd8-4466006020a6.png)

**Comment by shizhongming** [comment]
@daren-thomas it seems that @reyery found a solution..he is gonna send a pull request..

**Comment by reyery** [comment]
@daren-thomas I think I found out why and I think it is probably due to the fact that the `install-grasshopper` script is not copying over the `config.py` file.
