### ISSUE TITLE
Add Optimization plots to the Dashboard

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1762]
- part of the effort for Canada 19. February 2019
- @JIMENOFONSECA can you please list which plots to prioritize?

**Comment by JIMENOFONSECA** [comment]
This issue entails adding all the plots inside the script cea/plots/supply_system/main.py

These plots are classified in different categories. I describe the categories we should add first. To see which exact plot belongs to each category and what data each plot needs, check the script cea/plots/supply_system/main.py

In order of importance (category)

1. "system_sizes"
2. "costs_analysis"
2. "thermal_network"
3. "thermal_dispatch_curves"
4. "electrical_dispatch_curves"
5. "supply_mix"
6. "imports_exports"

**Comment by daren-thomas** [comment]
I'm getting this error when running `cea plots-optimization`:

```
Traceback (most recent call last):
  File "c:\Users\darthoma\Miniconda2\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 65, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\main.py", line 644, in main
    plots_main(locator, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\main.py", line 54, in plots_main
    data_address = locating_individuals_in_generation_script(generation, locator)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\multicriteria\optimization_post_processing\locating_individuals_in_generation_script.py", line 60, in locating_individuals_in_generation_script
    data_generation = preprocessing_generations_data(locator, generation)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\multicriteria\optimization_post_processing\locating_individuals_in_generation_script.py", line 141, in preprocessing_generations_data
    data['population_fitness']]  # convert to millions
KeyError: 'population_fitness'
```

It seems the variable `data` refers to the optimization checkpoint and that the key `population_fitness` has been removed...

@JIMENOFONSECA, @BhargavaKrishnaSreepathi any ideas?

(since you guys are probably only back on Wednesday, this issue will not make it this sprint)

**Comment by daren-thomas** [comment]
@BhargavaKrishnaSreepathi I am still getting this error. This is blocking me.

**Comment by BhargavaKrishnaSreepathi** [comment]
I am on it, might take about 3 days to fix it. Will let you know once I finish it

**Comment by daren-thomas** [comment]
@JIMENOFONSECA it seems these plots will only run for DC networks. Do we plan to update them for DH?

**Comment by JIMENOFONSECA** [comment]
Yes, I believe they should also work fo rat cheating case.
On 21 Feb 2019, 5:34 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> it seems these plots will only run for DC networks. Do we plan to update them for DH?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I have no idea what a rat cheating case is.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas hahahaha the spellchecker said this. I meant. "....should also work **for the heating** case..."

**Comment by BhargavaKrishnaSreepathi** [comment]
I will fix the cooling case, but the heating case needs to be written (from scratch) by someone.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas we fixed major problems in the last PR's for these plots. now you can continue with the integration of optimzation plots.

1. run optimization/optimization_main
2 run analysis/multicriteria/main
3. run plots/optimization/main  ---> this will generate the plots
