### ISSUE TITLE
As a Practitioner I want to know how long installation takes so I don't get frustrated waiting.

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#1770]
I've had a couple of enquiries regarding install time from fellow students and thought it would be advantageous to include some ETA's in the ``Get Started with CEA``.

Doing a fresh install to pick up any bugs or issues to be clarified since the new release (cea 2.9.1)

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne merged. thanks for this!
