### ISSUE TITLE
Add openpyxl to the setup.py INSTALL_REQUIRES variables

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1781]
As a Researcher, when installing CEA, all the dependencies should be installed so that all the cea commands can be used. Currently, at least openpyxl is missing.

Maybe this issue should include testing all the CEA commands... as an output, maybe some script in cea/tests that uses the `cea.api` module to run each script?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I had an e-mail the other day of a person asking about this. Is this still an issue? maybe that person installed an old version of CEA with this bug?

**Comment by JIMENOFONSECA** [comment]
this is not anymore an issue in the cea installation V2.24
