### ISSUE TITLE
Implement the network-layout script without ArcGIS tools

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1784]
As a Researcher, I would like to run CEA simulations on systems that don't support ArcGIS (e.g. Docker / Ubuntu / Euler) in order to make use of cloud computing and clusters. Further, removing the ArcGIS requirement makes adopting the CEA easier for Researchers that don't have access to ArcGIS.

**Comment by JIMENOFONSECA** [comment]
the solution is in here: https://stackoverflow.com/questions/27161533/find-the-shortest-distance-between-a-point-and-line-segments-not-line

**Comment by JIMENOFONSECA** [comment]
this could help too https://gis.stackexchange.com/questions/227909/from-shapefile-to-python-networkx
