### ISSUE TITLE
Thermal network layout issues should raise an exception instead of infinite loop

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1786]
When running simulations for manually-created thermal network layouts, issues can arise that cause CEA to be stuck in an eternal loop - but since no flag of any kind is displayed, the user cannot know why the simulation is starting.

I'm namely thinking of a case like the one shown below:
![screen shot 2019-01-20 at 16 02 57](https://user-images.githubusercontent.com/18548065/52128056-3cb28c80-2634-11e9-9269-511df694f979.png)
While visually the shapefile appears to be correct, there are actually only two edges shown in blue - that is, the node in blue is not connected to the perpendicular edge. When simulating, the following code is reached on line 307 of `thermal_network_matrix`:
```
        # The direction of flow is then corrected
        # keep track if there was a change for the iterative process
        changed = [True] * node_mass_flows_df.shape[1]
        while any(changed):
            for i in range(node_mass_flows_df.shape[1]):
                # we have a plant with incoming mass flows, or we don't have a plant but only exiting mass flows
                if ((node_mass_flows_df[node_mass_flows_df.columns[i]].min() < 0) and (
                        edge_node_df.iloc[i].max() > 0)) or \
                        ((node_mass_flows_df[node_mass_flows_df.columns[i]].min() >= 0) and (
                                edge_node_df.iloc[i].max() <= 0)):
                    j = np.nonzero(edge_node_df.iloc[i])[0]
                    if len(j) > 1:  # valid if e.g. if more than one flow and all flows incoming. Only need to flip one.
                        j = random.choice(j)
                    edge_node_df[edge_node_df.columns[j]] = -edge_node_df[edge_node_df.columns[j]]
                    new_nodes = [edge_df['end node'][j], edge_df['start node'][j]]
                    edge_df['start node'][j] = new_nodes[0]
                    edge_df['end node'][j] = new_nodes[1]
                    changed[i] = True
                else:
                    changed[i] = False
```
Since the node shown above was not connected to any edge, the branch that started on that node could not be solved, as the code kept reverting the direction of flow while "looking for" a plant to feed the consumer at the end of the branch.

Perhaps some kind of message should be displayed after the flow is reverted X number of times in order to signal that there might be a problem in the layout?

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro is this still an issue? maybe we can add it to a milestone?, epic?

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA It is, it's just not a priority for anyone, so I don't think anyone is working on it.
