### ISSUE TITLE
Create a user survey

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1791]
- create a survey (e.g., surveymonkey or google forms) to collect info about who is using CEA, which features and for what purpose.
- collect some data about features that are liked and features that are disliked for future development.

**Comment by JIMENOFONSECA** [comment]
you want to use our mailchimp account: we did the newsletter with this: https://cityenergyanalyst.com/newsletter-1/
I can give you the login via slack

**Comment by gabriel-happle** [comment]
comments by arno:

Some comments: a) Maybe you want to make the email optional, so that people can fill in anonymously. b) ‘What is your research about’ : I would choose a dropdown with options rather than free text. Otherwise itt will be hard to categorize and bin. c) I would add a dropdown asking for their background (engineering, arch, etc.) and their expertise / literacy using modeling / energy simulation software.

**Comment by gabriel-happle** [comment]
please take a look at the improved draft:
https://docs.google.com/forms/d/e/1FAIpQLSeFvy0ERAMEVdbwMEqpzEW3grD-4CaWe-Z-iL_o5HHMPtdXoA/viewform

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle @daren-thomas from the CEA plan 

CEA Surveys - Starting on the 1st of April of 2019. Repeats every quarter.
**Description:** 
A survey to existing users of CEA. It should consist of 3 to 5 questions. Example: see Issue #1791 @gabriel-happle

**Goal(s):** 
Identify “What is the worst feature of CEA” aka the hurting point
Identify “What is the best feature of CEA”
Identify "How user friendly is CEA" (1-5 stars), possibly in a few categories (installation, running simulations, analysing results)

**Method:**
Prepare survey to existing users of CEA via Survey Monkey
Gather list of emails of existing users from CEA’s website RESEARCHERS and PLANNERS
Prepare at least one question for each one of the goals of the survey.
Send one survey to at least 100 people every quarter (1st time 01.04.2019).

**KPI’s:** 
Receive at least 10 answers in 7 days.
Identify top hurting point (the worst voted feature of CEA).
Create at least one issue to fix top hurting point.
Schedule issue in CEA sprint.

**Responsible:** 
Scrum Master chooses one team member to be responsible for the survey monkey and call him/her the chunky monkey of the quarter.
Scrum Master creates a chunky monkey survey issue for each quarter starting at Q2/2019 unit Q2/2020 and assigns them as part of the CEA planning meeting to whoever has time.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle I believe you can add these quesitons to the survey:

Identify “What is the worst feature of CEA” aka the hurting point
Identify “What is the best feature of CEA”
Identify "How user friendly is CEA" (1-5 stars), possibly in a few categories (installation, running simulations, analysing results)

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle you can us mail-chimp to distribute the survey. I send you the password and the list of contacts

**Comment by gabriel-happle** [comment]
survey sent via CEA mailing list plus posted on 5 issues tagged `user support`.
Closing this for now.
Creating two new issues for analyzing data and modifying the survey for the next round.
