### ISSUE TITLE
Upload new reference case open to reference case repository

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1796]
- the `dodo` test downloads reference cases from the reference case repository.
- in #1790 a new `reference-case-open` was created.
- we need to upload it to the repository

**Comment by daren-thomas** [comment]
- check dodo: is this really being downloaded in the tests?
- if yes: stop downloading and instead use bundled version
- remove from repository

**Comment by daren-thomas** [comment]
- dodo checked: doesn't download, so, just remove from repository.

**Comment by gabriel-happle** [comment]
This can be closed. Turns out the open case was never part of the repository in the first place :)
