### ISSUE TITLE
Mention deprecation of ArcGIS interface on CEA website and README.md on GitHub

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1799]
The ArcGIS interface will be deprecated in near future (e.g. 2-3 Months). Communicate this via the CityEnergyAnalyst.com website as well as on GitHub.

**Comment by JIMENOFONSECA** [comment]
I will put this for the 1st of May as a deadline, just to not stretch too much the release of a stable version of the dashboard, which is still our priority now.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA yes, this can be closed! :) good job!
