### ISSUE TITLE
Add a deprecation warning to output of ArcGIS scripts

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1801]
When running a script through the ArcGIS interface, output a deprecation warning that the interface will be deprecated soon. Ideally, add a link to information about the dashboard interface to use instead.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I did a first stab to this in the PR #1804 . you probably would like to add this link and additional information in there during your revision.
