### ISSUE TITLE
As a developer I want to access *all* doc strings so I can parse descriptive information 

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#1811]
Some doc strings are not formatted correctly, especially module descriptions or titles. This will be an easy but tedious fix.

**Comment by daren-thomas** [comment]
hey @Jack-Hawthorne what is the status of this?

**Comment by Jack-Hawthorne** [comment]
I haven't started yet. the purpose is in the title - why have doc strings if you cannot parse them. all the ``__future__``  should be able to have docstrings preceding, and are preventing access via the doc method.

in addition i can have a look at the inputlocator doc strings, some of which are out of date
