### ISSUE TITLE
Error when running radiation script for new project

### ISSUE THREAD

**Issue by FionaCollins** [architecture-building-systems/CityEnergyAnalyst#1812]
Hello

I have been struggling with setting up a new project. I get the error visible in the screenshot below when running the radiation-daysim.

![image](https://user-images.githubusercontent.com/46419981/53517978-46fb6580-3ad0-11e9-9471-fa8957e484e2.png)

There must be something going wrong in the terrain_intersection_curves but I can't figure out what. 

This is the terrain file I have

![image](https://user-images.githubusercontent.com/46419981/53518296-07814900-3ad1-11e9-8bd6-bf1e3f8ef4f1.png)
![image](https://user-images.githubusercontent.com/46419981/53518321-1667fb80-3ad1-11e9-98fd-c6edfd43f1fc.png)
(I can't upload it here as a .tif)

NOTE: The building is situated in Almere(Netherlands) thus the terrain model has negative elevations.

Could someone have some hints on what is wrong? (in the terrain file (raster), shapefile...?)

Thanks for the help

**Comment by martin-mosteiro** [comment]
@FionaCollins Thanks for creating the issue. I see you managed to invert the NoData Value as we discussed yesterday, seems like that didn't solve the issue. Did you try to raise the entire case study by 6.75 meters (so the lowest point in the case study is at 0)?

**Comment by FionaCollins** [comment]
Hi Martin,

I tried the following without success:

- lifting the Raster terrain by a few meters
- making a "super" high and "super" deep building (making height_ag and heigh_bg very big) 
- decreasing the raster cell size from 5x5 to 2x2 (because certain buildings are smaller than 4m wide and long)
- tried to modify the code line (y_index, x_index) = np.nonzero(a >= 0) to (y_index, x_index) = np.nonzero(a >= -10)

Do you have an other idea?
The problem lies in the intersection

**Comment by martin-mosteiro** [comment]
From @FionaCollins 
> Daniela sent me a new zone file (she had discovered an error) + vegetation file and now it seems to work magically! I really want to know what she modified haha. 
> But anyway I will continue a bit and get back to you if I still have problems. 
Seems like this issue is solved even though we don't know why. I'll go ahead and close it.
