### ISSUE TITLE
Error in geometry_generator.create_hollowed_facade: IndexError: list index out of range

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1817]
I get the following error when running the radiation script in the Zurich masterplan case study:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.2\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.2\helpers\pydev\pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py", line 218, in <module>
    main(cea.config.Configuration())
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py", line 198, in main
    settings)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\resources\radiation_daysim\geometry_generator.py", line 379, in geometry_main
    nfloor_col="floors_ag")
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\resources\radiation_daysim\geometry_generator.py", line 213, in building2d23d
    window_north, wall_north, normals_windows_north, normals_walls_north  = calc_windows_walls(facade_list_north, wwr_north)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\resources\radiation_daysim\geometry_generator.py", line 339, in calc_windows_walls
    hollowed_facade, hole_facade = create_hollowed_facade(surface_facade, window)  # accounts for hole created by window
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\resources\radiation_daysim\geometry_generator.py", line 105, in create_hollowed_facade
    hole_facade = fetch.topo_explorer(b_facade_cmpd, "face")[0]
IndexError: list index out of range

Process finished with exit code 1
```

Unfortunately I can't really debug this because I don't understand the data types being used in these scripts. I tried to check the inputs being passed into the function in question look as follows:
- **Surface 52 in Building MPB1J** (which runs correctly):
![screen shot 2019-03-03 at 19 28 11](https://user-images.githubusercontent.com/18548065/53699696-715c6400-3deb-11e9-95d7-c3a76fb59f9a.png)
![screen shot 2019-03-03 at 19 29 33](https://user-images.githubusercontent.com/18548065/53699698-75888180-3deb-11e9-9eb1-a6d5a56a4caf.png)
- **Surface 53 in Building MPB1J** (where the error comes up):
![screen shot 2019-03-03 at 19 26 37](https://user-images.githubusercontent.com/18548065/53699705-8afdab80-3deb-11e9-8160-d99bbe0d0c78.png)
![screen shot 2019-03-03 at 19 30 25](https://user-images.githubusercontent.com/18548065/53699708-8cc76f00-3deb-11e9-90ec-4c0cf0c9baee.png)

@JIMENOFONSECA any idea what the issue might be about...?

**Comment by martin-mosteiro** [comment]
This happens not only on my local version, but also on the reference case in the cea-reference-case repository on GitHub. This reference case study used to work correctly, so maybe it's an issue arising from the move to py4design?

**Comment by JIMENOFONSECA** [comment]
@chenkianwee sorry to bother, but from the error, do you see where the problem can be? @daren-thomas just for my understanding, are we working with one specific version of py4design right?

**Comment by JIMENOFONSECA** [comment]
@martin can you try to run the script of generate geometry on its own and then try to visualize the buiding? (there are some commented lines at the end of the code that trigger a visualization of the geometry.

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Thanks for your feedback, very cool feature! Please note that the commented lines don't work at the moment, though, because the function `fetch.geom_explorer` does not exist in py4design anymore (it seems to have been removed during the [renaming commit](https://github.com/chenkianwee/py4design/pull/13/files).

**Comment by JIMENOFONSECA** [comment]
oh, but, where you able to visualise it?
On 4 Mar 2019, 3:28 PM +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> Thanks for your feedback, very cool feature! Please note that the commented lines don't work at the moment, though, because the function fetch.geom_explorer does not exist in py4design anymore (it seems to have been removed during the renaming commit<https://github.com/chenkianwee/py4design/pull/13/files>.

**Comment by martin-mosteiro** [comment]
Yes! ...after fixing some function names ;) Runs fine on reference-case-open, now I'll test my case study.

**Comment by martin-mosteiro** [comment]
<img width="795" alt="screen shot 2019-03-04 at 09 04 20" src="https://user-images.githubusercontent.com/18548065/53718833-a1901b00-3e5c-11e9-9367-11e54fe39764.png">
Visually, the geometry of the building looks okay to me, but once it starts to generate windows the issue occurs...

**Comment by JIMENOFONSECA** [comment]
I see, there is a place where four faces touch each other, might that be the problem?

I wonder what happens if you separate that point of the building in the shape file.

[cid:ED4629CCF22F449EB248E0768D9D2613]
On 4 Mar 2019, 4:06 PM +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

[screen shot 2019-03-04 at 09 04 20]<https://user-images.githubusercontent.com/18548065/53718833-a1901b00-3e5c-11e9-9367-11e54fe39764.png>

Visually, the geometry of the building looks okay to me, but once it starts to generate windows the issue occurs...

**Comment by martin-mosteiro** [comment]
Thanks, @JIMENOFONSECA, splitting up that building worked. I wonder why this never came up before...

**Comment by martin-mosteiro** [comment]
Split up the building to avoid those four corners touching... still no success
<img width="743" alt="screen shot 2019-03-04 at 10 38 42" src="https://user-images.githubusercontent.com/18548065/53724237-c0e17500-3e69-11e9-899d-4a3ed0e1ba4f.png">

**Comment by martin-mosteiro** [comment]
Thanks @JIMENOFONSECA
