### ISSUE TITLE
Add a cea-config load/save/list feature

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1822]
As a developer, I would like to be able to quickly switch between configuration files to reduce errors when testing features designed for different cases - like heating case / cooling case.

I envision a method like:

- `cea-config save my-cooling-config` would save a copy of `~/cea.config` to `~/.cea/my-cooling-config.config`
- `cea-config load my-cooling-config` would replace `~/cea.config` with the contents of `~/.cea/my-cooling-config`
- `cea-config list` would list all saved configs by name - these are the valid candidates for `cea-config load`
- `cea-config reset` would reset the `~/cea.config` file to the contents of the default configuration file

**Comment by JIMENOFONSECA** [comment]
This is a good idea. Could this be coupled with moving the cea.config to the 'CityEnergyAnalyst/cea' location? We could include a git.ignore, so this file is not updated by the developers everytime we merge.

This location of the cea.config will make MUCH easier for new users to use the config file. Also for us. since we avoid having to go to the explorer, users names etc.. to get to the file.

Instead, we can just open it directly from pycharm, or form the folder where we install cea. How could would that be?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA what do you mean by the `CityEnergyAnalyst/cea` location? The source folder? Definitely not! That's the whole point of keeping it where it is: It's part of the installation, not part of the source code!

Also, you can use `cea-config` to make changes to the config file OR (even better) use the dashboard interface?

I see this issue going hand in hand with your issue #1813. We used to have a mechanism for having configuration files _per_ scenario. I think there should be some kind of project mechanism so we can have configurations _per_ project at least.

**Comment by JIMENOFONSECA** [comment]
I see, Would it be possible that the source code is the installation of CEA? 

I do not get where CEA is installed vs. source code location.

Maybe it makes sense to create an installer that indicates where CEA will be installed and create the config file in there? It will make sense to keep the source code in there too. Right?

Having the config file in the %userprofile% is just a difficult place to find it. Especially for first time users.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA we should probably skype regarding difference between source and product. I think we're not quite on the same page here.

**Comment by JIMENOFONSECA** [comment]
sure, let's do this, I am on skype now

________________________________

**Comment by daren-thomas** [comment]
I'm busy with the optimization plots. This would be a distraction. Next week?

**Comment by JIMENOFONSECA** [comment]
ok.. Monday will work. Tuesday, I might be in surgery :-(
________________________________

**Comment by daren-thomas** [comment]
oh no! good luck with surgery!!

**Comment by daren-thomas** [comment]
@JIMENOFONSECA does the start menu shortcut to open the config file in notepad.exe solve the problem of finding the `cea.config` file easily? Then we can concentrate on the load/save features, but demote this to a should-have.

**Comment by JIMENOFONSECA** [comment]
yes, it works quite well. thanks!

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 14 May 2019, 4:07 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> does the start menu shortcut to open the config file in notepad.exe solve the problem of finding the cea.config file easily? Then we can concentrate on the load/save features, but demote this to a should-have.
