### ISSUE TITLE
Document Optimization in CEA

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1826]
This issue collects what @architecture-building-systems/cea-core-developers wants to know about the supply system optimization in CEA.
This is part of @BhargavaKrishnaSreepathi 's handover.
Please feel free to raise any point you would like to know here. I will compile them and upload to the documentation (with minimum effort though, like graphs and short Q&As).

Here are some points i started, please feel free to add:
(could be anything that's related! simple, detailed, difficult, funny questions are all welcome : )

1. What is the workflow of optimization? (distill from the previous graphs bhargav created, or use graphviz).
2. How to run optimization and interpret results? (currently is spread in `how to do analysis in cea` and `files generated by the cea`)
3. How to add new objectives?
4. How to add new variables?

**Comment by shanshanhsieh** [comment]
@BhargavaKrishnaSreepathi 
please check the workflows and update the additional parts in this issue.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh should we have a PR about this anytime soon?

**Comment by shanshanhsieh** [comment]
i am planning to work on it this friday!

**Comment by shanshanhsieh** [comment]
i made a short guide that explains:
- objectives & variables
- and links to workflow & files generated by cea
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/i1826-document-optimization-in-CEA/docs/how-to-run-CEA-optimization.rst
