### ISSUE TITLE
Make one-for-all installer for windows

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1828]
After some discussion with @daren-thomas in the Epic, I believe we should go the executable route. At the best we develop a Cross-platform installer of CEA.

WORKFLOW
The installer should prompt to the user the next option:

Indicate where CEA will be installed.
Then the installer should ask the user to select one option of the next:

1. Repair existing installation of CEA
2. Do a fresh installation of CEA.
3. Update to the latest version of CEA.
4. Install the Developer version of CEA.

OTHER REQUIREMENTS

the installation process should be fast ( less than 10 min)

DELIVERABLES
Installer of CEA for Windows.

**Comment by daren-thomas** [comment]
The installation process being less than 10 minutes is probably an unrealistic goal. We should talk about options. I have some ideas.

**Comment by JIMENOFONSECA** [comment]
Sure, lets put this point in the agenda of next monday’s meeting. Would 4:00pm singapore work for you?

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

On 20 Mar 2019, 17:26 +0800, Daren Thomas <notifications@github.com>, wrote:

The installation process being less than 10 minutes is probably an unrealistic goal. We should talk about options. I have some ideas.

**Comment by daren-thomas** [comment]
i sent you a calendar invite :) see you then!

**Comment by JIMENOFONSECA** [comment]
Folder structure:
(inside the Documents folder)

-CEA
---Repository
---Projects

**Comment by gabriel-happle** [comment]
Separate issues were created: #1916 #1915 #1914 #1913 #1911
