### ISSUE TITLE
Prepare invitations and website

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1829]
Use the same template as last year and create 

1.  Registration page in the website.
2. Send first batch of invitations to downloaders of CEA.

**Comment by JIMENOFONSECA** [comment]
We are ready to send invitations. Here is the link to the registration page. @Khayatian thanks for chipping in :-). @gabriel-happle @shanshanhsieh should I put you also inside for now? I guess it would make sense that one of you guys can join us just for the course. Especially if someone of you is going to CISBAT.

https://cityenergyanalyst.com/executive-course-2019

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle @shanshanhsieh let me know, so I can update the website asap

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA  yes, please keep me in the loop for now!
