### ISSUE TITLE
Add in more documentation and update the naming of flexibility_model in CEA

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1833]
As the name suggests, include more documentation and ways to run

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi is there any suggestion for the renaming of the tools?

**Comment by shanshanhsieh** [comment]
the documentation is included in PR #1837
and the naming stays the same for now
