### ISSUE TITLE
DH_hs_MWhyr, DC_hs_MWhyr and district energy supply plots are misleading

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1834]
I think these variables and plots present misleading information.

See line 308 in `thermal_loads.py` - here the electricity demand for producing the district heating used in the district is calculated, not the amount of district heating supplied (i.e., `tsd['DH_hs'] = tsd['Qhs_sys'] / efficiency_average_year`, where the `efficiency_average_year` is a COP). However, since the variable is labeled "DC" or "DH" it would seem to be representing the amount of heating/cooling extracted from the network, not the electricity used to produce it.

Furthermore, the district energy supply plots show a stacked bar chart with the following values: "District electricity consumption", "District cooling for space cooling demand", "District heating for space heating demand" and "District heating for hotwater demand" (also, note the typo while we're at it). However the y axis is labeled a very generic "Energy demand [MWh/yr]", so I think it gives the wrong impression.

I think these variables should be renamed and the plots be redone in a more intuitive way.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro could you describe the steps you made. Maybe I can reproduce and see which plots you mean?
A picture of the plots you are referring to will also be useful. I get lost in the variety :-)

**Comment by martin-mosteiro** [comment]
@FionaCollins could you maybe provide one of the graphs or data sets that we discussed the other day?
@JIMENOFONSECA basically `DC_sys` in the outputs is given as `Qcs_sys/COP`. So if the cooling demand is, say, 300 MWh/yr and the system COP is 3, then DC_sys is 100 MWh/yr. But this would then be 100 MWh/yr of electricity, not 100 MWh/yr of cooling, hence why I think the naming is misleading.

**Comment by FionaCollins** [comment]
The columns you are talking about are highlighted here: 

[Total_demand.xlsx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/3035838/Total_demand.xlsx)
 
- In general I would say that a little clean up of the demand output variables could be helpful. 
- Also updating the glossary to include all the variable explanations could be considered. The variables defined up until now allow a decent analysis with some searching and making 'educated guesses' ;).
- There are also some output variables that are in the individual building outputs, but not in the final 'total demand' output (example solar gains, radiative heat losses etc.).  I wrote some functions looping through the individual building files to collect them.. let me know if this could be helpful (although the functions are pretty straight forward)

**Comment by daren-thomas** [comment]
@martin-mosteiro, @FionaCollins: I think what @JIMENOFONSECA was asking for is the list of plots affected?

**Comment by martin-mosteiro** [comment]
@FionaCollins do you have the plots we generated through CEA that showed the district energy balance? I think those make the issue quite clear. Thanks!

**Comment by FionaCollins** [comment]
energy supply for district:
![image](https://user-images.githubusercontent.com/46419981/55837263-2be53200-5b21-11e9-8280-f46692607fd6.png)

energy demand for district:
![image](https://user-images.githubusercontent.com/46419981/55837323-50d9a500-5b21-11e9-8ef9-a604dcd199b7.png)

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro @FionaCollins would you mind explaining what the issue is and how it reflects in the plots? Advice on what to modify would be welcome.

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA The top plot posted by Fiona says "District heating for space heating demand". This is itself not a very clear statement.
- Do we mean the amount of heat the district heating network is supplying to the buildings? Then the two should be equal ("District heating for space heating demand"="End use space heating demand" from the bottom plot). They're not.
- Do we mean the amount of exergy used to produce the heating supplied to the buildings? Then the calculation is fine ("District heating for space heating demand" = "End use space heating demand" / COP) but the language is confusing.

**Comment by daren-thomas** [comment]
We decided it's an error. @JIMENOFONSECA will look into this.
