### ISSUE TITLE
Add floor cooling option to CEA demand calculation

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1835]
@FionaCollins's case study includes floor cooling but this currently not available in CEA (and actually labeled as `TODO`). This needs to be added as an option.

**Comment by martin-mosteiro** [comment]
@FionaCollins could you please provide the floor cooling systems parameters you used for your project in order to test them on this branch?

**Comment by FionaCollins** [comment]
A new entry 'T5' was made. However the Case Study of Almere highjacks 'T1' ;) 
The parameters were set as follows:

Description | code | Qcsmax_Wm2 | dTcs_C | Tscs0_ahu_C | dTcs0_ahu_C | Tc_sup_air_ahu_C | Tscs0_aru_C | dTcs0_aru_C | Tc_sup_air_aru_C | Tscs0_scu_C | dTcs0_scu_C
floor cooling   (15/20) | T5 | 100 | 0.5 | NA | NA | NA | NA | NA | NA | 15 | 5

**Comment by gabriel-happle** [comment]
Dear @FionaCollins,

In order for us to better understand the needs of our users and steer the development of the tool in the future we would like to understand why and how you are using the CityEnergyAnalyst.

Please help us by answering 10 short questions in the [CEA user survey](https://forms.gle/6nR8V5JEDM593g5eA).
The feedback we receive will determine the focus of the upcoming development efforts.

Kind regards,
The CEA development team

**Comment by gabriel-happle** [comment]
@martin-mosteiro are you working on this issue for milestone 2.12?

**Comment by martin-mosteiro** [comment]
@gabriel-happle The additional code for floor cooling is done, just needed the technology parameters @FionaCollins provided in order to test the code. However this will not be done by today (duh) so it should be moved to the next milestone.

**Comment by martin-mosteiro** [comment]
@FionaCollins could you provide the reference for the values you used? The lower operating temperatures seem... interesting.

Thanks!

**Comment by martin-mosteiro** [comment]
I assumed floor cooling systems can be modeled basically the same as ceiling cooling systems other than the convective fraction defined by the SIA standard. So I added the following `or` statement in line 104 of `hourly_procedure_heating_cooling_system_load`:
```
        elif control_heating_cooling_systems.has_ceiling_cooling_system(bpr) or \
                control_heating_cooling_systems.has_floor_cooling_system(bpr):

            rc_model_temperatures = calc_cool_loads_radiator(bpr, t, tsd)
```
Here are some results for building B06 from the reference case open.

**1. Comfort**
1.1. Central AC:
![test_Ebalance_baseline](https://user-images.githubusercontent.com/18548065/55820276-034a4180-5afb-11e9-9c04-d9d289fe7fe0.png)
1.2. Chilled ceiling:
![test_comfort_ceiling_cooling](https://user-images.githubusercontent.com/18548065/55820287-0e9d6d00-5afb-11e9-82aa-29257fcf8b67.png)
1.3. Floor cooling:
![test_comfort_floor_cooling](https://user-images.githubusercontent.com/18548065/55820299-152be480-5afb-11e9-96d5-14c14eab8e70.png)
There are no latent loads in the two latter cases. Shouldn't this be supplied by the ventilation systems, @gabriel-happle ?

**2. Comfort**
2.1. Central AC
![test_comfort_baseline](https://user-images.githubusercontent.com/18548065/55820474-7b186c00-5afb-11e9-8235-1b469d52d37b.png)
2.2. Chilled ceiling
![test_comfort_ceiling_cooling](https://user-images.githubusercontent.com/18548065/55820486-81a6e380-5afb-11e9-8c05-e45b92b628f8.png)
2.3. Floor cooling
![test_comfort_floor_cooling](https://user-images.githubusercontent.com/18548065/55820499-866b9780-5afb-11e9-9322-320c9b015d2a.png)
Since there is no considerable amount of dehumidification, the two latter cases have a lower percentage of comfortable summer hours due to humidity being too high. However the floor cooling system performs a bit better due to the lower operating temperatures. The chilled ceiling system (as is currently implemented in CEA) operates really poorly! (less than 50% comfort hours in summer)

**Comment by FionaCollins** [comment]
Hi Martin,
The case study for the anergy grid in Almere suggested a temperature of 7°C for the cooling ring and 17°C for the heating ring throughout the year. I was thinking: 7°C would probably lead to condensations when circulating through the cooling elements, so I took a value in the lower range of ceiling cooling elements. 
The file you attached suggest similar values and I did also use it as inspiration, however I suggested my temperature more as a proposal (leaning on the Almere case study) rather than a value from a specific source. (Probably not the best way to do so, I admit) 

Anergy grid feasibility study Almere:
[11200690-002-HYE-0002-v2-r-Floriade 2022 en het Weerwater_reviewPB-signed.pdf](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/3061018/11200690-002-HYE-0002-v2-r-Floriade.2022.en.het.Weerwater_reviewPB-signed.pdf)


Translation to englisch (google translate):
[Anergy_grid_study_translation.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/3061017/Anergy_grid_study_translation.docx)

**Comment by martin-mosteiro** [comment]
Thanks for the quick reply. How about the maximum cooling power? It matches perfectly to the recommendation in that document, whereas in the paper cited it seems to provide heat transfer coefficients...?

**Comment by gabriel-happle** [comment]
@martin-mosteiro only AC systems 'create' latent loads in the CEA. If there is no system to remove humidity, there is no latent load in the calculation.
Does it answer your question?
If you want latent loads to be covered we need to create a kind of `3for2` system for cooling. I.e., with outdoor air units, air recirculation units and sensible cooling units.
We can do that. We just have to come up with an operating strategy.

**Comment by martin-mosteiro** [comment]
@gabriel-happle Thanks for the feedback. I know that's the case on CEA, the question was more whether that's a feasible system setup. I would assume the ventilation systems would need to take care of some latent load?

**Comment by gabriel-happle** [comment]
@martin-mosteiro I see, you want to control the ventilation system according to humidity. Well, that doesn't exist yet, but I'm sure it can be done.
Right now the ventilation system is supplying the required ventilation rate according to occupancy with the special rules of night flushing and economizer.
Should we add this kind of control? I.e., increase the ventilation rate according to relative humidity thresholds?

**Comment by martin-mosteiro** [comment]
The humidity control part of this issue will be taken care of at a later time (#1904). For now, the floor cooling systems have been implemented and tested, so I will create a PR for this issue.
