### ISSUE TITLE
Broken link in tutorials section of documentation

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1840]
The link nr. 9 in the [advanced section of the tutorials page](https://city-energy-analyst.readthedocs.io/en/latest/tutorials.html#advanced) is broken.

I think it might be a simple typo.

It _should_ link to here: https://city-energy-analyst.readthedocs.io/en/latest/how-to-run-thermal-network-optimization.html?highlight=thermal%20network

**Comment by Jack-Hawthorne** [comment]
haha hot-to-run - apparently not.
