### ISSUE TITLE
Grasshopper interface: robust parser from GH geometries to the CEA format

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CityEnergyAnalyst#1844]
As of the MuSES review on 28 March 2019, the connection between GH and CEA is built in this workflow: GH geometries -> coordinates in excel format -> CEA converts excel to shapefile. Yet we need to a robust parser doing this. 
There is good news. At the end of Year 2018, I realized that there is a toolbox at Grasshopper converting GH geometries to shapefile. In this way, we can bypass the excel as the intermediate format. Let me try this first. Before any further actions. :) @daren-thomas

**Comment by daren-thomas** [comment]
@shizhongming what is the status of this? is there anything i need to do for this? otherwise i'd like to remove myself from the assignees list for now.

**Comment by shizhongming** [comment]
@daren-thomas Sorry for the late reply...I think this issue is not urgent and you may remove yourself from the assignees...

**Comment by daren-thomas** [comment]
This issue could be resolved by writing a blog post (for M2.27?) on how to export a Rhino geometry as a shapefile for CEA.
