### ISSUE TITLE
Occupancy documentation

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1852]
The occupancy modeling part of CEA should be documented better. There are a couple of workflow diagrams I created last week as well as a Spacergy deliverable that describes what is going on in these scripts. I will send these to @Jack-Hawthorne for him to incorporate these into his work.

**Comment by Jack-Hawthorne** [comment]
@martin-mosteiro @JIMENOFONSECA how do you want to present this information? is it super necessary? the occupancy schedules are indexed really weirdly, transposing and dropping nans is a work around for the real issue of how these are written in the xlsx files.

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne yes, we should not go into that trouble.

However, as martin mentioned, he made some diagrams of this already, so I suggest that we just upload Martins diagrams as jpeg to the documentation. that should be a piece of cake right?

**Comment by Jack-Hawthorne** [comment]
@JIMENOFONSECA yeah shouldn't be an issue
