### ISSUE TITLE
DC Network non-looped simulation with 258 buildings throws Memory Error

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#1855]
I am currently trying to run thermal_network.py for a case study with 258 buildings:

![zone_streets](https://user-images.githubusercontent.com/26175926/55408888-3cb20880-5561-11e9-8c43-91e8aa752dbb.png)
with following edges&nodes .shp files:
[edges_nodes.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/3034269/edges_nodes.zip)

The defined parameters for the optimization in the config file are:

- DC
- start-t = 4368
- stop-t = 4380
- minimum-mass-flow-iteration-limit = 5
- diameter-iteration-limit = 5
- optimize-loop-branch = false

config file: [cea_config.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/3034256/cea_config.zip)

If running thermal_network.py (master branch) it throws following error: 

```
Calculating edge mass flows
start calculating mass flows in edges...

 Diameter iteration number  0
Using 7 CPU's
calculating mass flows in edges... time step 4368
calculating mass flows in edges... time step 4369
calculating mass flows in edges... time step 4370
calculating mass flows in edges... time step 4371
calculating mass flows in edges... time step 4372
Traceback (most recent call last):
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network.py", line 3449, in <module>
    main(cea.config.Configuration())
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network.py", line 3442, in main
    thermal_network_main(locator, network_type, network_name, file_type, set_diameter, config, substation_systems)
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network.py", line 457, in thermal_network_main
    use_multiprocessing=config.multiprocessing)
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network.py", line 1676, in calc_max_edge_flowrate
    izip(t, repeat(diameter_guess, nhours), repeat(thermal_network, nhours)))
  File "C:\ProgramData\Miniconda2\envs\cea\lib\multiprocessing\pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\ProgramData\Miniconda2\envs\cea\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
MemoryError: out of memory
calculating mass flows in edges... time step 4373

Process finished with exit code 1
```

The machine I am running this on has following specifications: 

- Processor: Intel(R) Core(TM) i7-3770 CPU @3.4GHz. 4 cores, 8 logical processors
- RAM = 16GB

This issue is differing from issue #1753 since the error occurs for an DC optimization of non looped network with a "low" number of iterations.

Any help on this issue would be greatly appreciated.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh maybe you have some insights about this?

**Comment by daren-thomas** [comment]
@emanuel030 Can we please move our appointment to Tuesday 10:00am? I won't be in the office on Monday...

**Comment by emanuel030** [comment]
@daren-thomas tuesday works fine for me aswell

**Comment by shanshanhsieh** [comment]
@emanuel030 i will try to run this before leaving the office today, and hope to give you some feedback before your meeting with daren on tuesday.

**Comment by shanshanhsieh** [comment]
i have never tried to run such a big network, and there are def rooms to make the code more efficient, so maybe daren will be able to help better here.
my hunch is that the thermal calculation is the bottleneck

what do you need to know from this DC network simulation?
are you using water from the lake? maybe you will only need to know the pressure losses?

**Comment by shanshanhsieh** [comment]
@emanuel030 how's the status for this?
if you had identified that the bottleneck is in thermal calculation, it is possible to modify the script and only run for hydraulic losses.

**Comment by martin-mosteiro** [comment]
@shanshanhsieh Running the simulation without multiprocessing solves the issue... it just takes a very long time. As suggested, skipping the thermal calculation could be a workaround for this specific case.

However I wonder if there's a way to make this simulation less time consuming through parallelizing or other tricks up @daren-thomas's sleeve?

**Comment by daren-thomas** [comment]
Running this from the command line (CEA Console) might work better than from PyCharm...

**Comment by gabriel-happle** [comment]
There are no more memory errors when running from the console.
Closing this issue.
