### ISSUE TITLE
Write blog post for M2.12

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1858]
Each Milestone we write a blog post. @JIMENOFONSECA is taking the lead.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas The first blog is ready. Let me know your comments before making some publicity. Hopefully you can tell me by the end of this week.

https://cityenergyanalyst.com/blogsurrogate/2019/4/5/getting-real-with-data-management-in-cea

**Comment by JIMENOFONSECA** [comment]
@daren-thomas Many thanks for your comments, they were quite useful.
The final Blog article is here:

https://cityenergyanalyst.com/blog/2019/4/5/speedinguppart1
