### ISSUE TITLE
Estimate time of radiation script as a function of building count

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1864]
As a User, I would like to have an idea of how long the radiation script will run so I can plan my day.

The radiation script is one of many scripts in the CEA that can take a while to complete. I assume there is a function describing the runtime of this script and I'm assuming the number of buildings is a good proxy to use for estimating this time.

This issue includes the following steps:

- run the radiation script with multiple scenarios (increasing building count)
- plot the runtimes
- pick a function and calibrate
- use that to print an estimate to the user
- (maybe also pick a first part of the script - geometry generation or similar - to calibrate the function on a per-pc basis for a more accurate prediction)

**Comment by daren-thomas** [comment]
this could be an interesting blog post...

**Comment by JIMENOFONSECA** [comment]
High effort, very low value....We will give priority to other issues in the pipeline and close this. I.e., unitests of everything
