### ISSUE TITLE
As a developer I want the decentralized config to have a building argument to avoid long run times for testing

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#1865]
Developers and practitioners should be able to have tighter control over the specific buildings being investigated. Currently, the decentralized script gets all the buildings for analysis from the total_demand.csv in the outputs. If, say,  decentralized only wants to be run for one specific building, one would have to either:
- run the demand script for only a few buildings, potentially overwriting the total_demand.csv OR
- make a copy of the demand data from all the buildings, and delete data for buildings except those desired.

perhaps there should be an argument in the config, similar to that of ``buildings`` for radiation-daysim and demand which can be applied for scripts like decentralized which would enable more streamlined use (not to mention the decreased run time).

**Comment by daren-thomas** [comment]
@Jack-Hawthorne please expand on the issue description. I do not quite understand your point.

> This should most likely be referenced from the config to allow better control over the script's execution

(how?)

> and not have to delete any data from the output files.

(specifically what data and why would i want to delete any?)
