### ISSUE TITLE
dashboard file directory opener is not working

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1868]
@daren-thomas I am trying to change the project dir, but I cannot navigate to any folder outside of the current parent directory (E:/). The project i want to use is in C:/. 

I think CEA should allow to locate files in any hard drive.

![image](https://user-images.githubusercontent.com/8973186/55846014-befc8700-5b76-11e9-8143-faec4fbd1a4c.png)

**Comment by daren-thomas** [comment]
Ugh! You're right! That's so stupid. And so DOS era... I'll figure out something.

**Comment by JIMENOFONSECA** [comment]
It is relevant….
On 8 May 2019, 9:35 PM +0800, Daren Thomas <notifications@github.com>, wrote:

I'm not quite sure if this is still relevant and if we should maybe wait for the new landing page ux to solidify. I suggest assigning this to @reyery<https://github.com/reyery>.
