### ISSUE TITLE
dashboard plot settings are not working

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1869]
While working inside the plots, I noticed that they are not being recalculated when I change their settings.

I am running the case study that bhargava sent us to test optimzation MIX_low_density.

This is an example for the 'Energy Balance Plot'

1. First I ask CEA to show me the accumulated energy balacne for all buildings

![chrome_riajHxdDZg](https://user-images.githubusercontent.com/8973186/55846543-9d040400-5b78-11e9-87bf-fce405cc00dd.png)

2. The results show me just the balance for B001, But it should be for the entire district

![chrome_JW2tZ4PXeH](https://user-images.githubusercontent.com/8973186/55846572-bc9b2c80-5b78-11e9-9b53-c82f272821e5.png)

3. Now I try to ask CEA to show me the results for any other building B009

![chrome_6D53i6VCOL](https://user-images.githubusercontent.com/8973186/55846590-cde43900-5b78-11e9-8bbc-b5c0f1aa654c.png)

4. The results are exactly the same as before. Notice the scale in the Y axis. It is about the same This means that the chart is not updating.

![chrome_mukNam8qR1](https://user-images.githubusercontent.com/8973186/55846610-de94af00-5b78-11e9-8306-2b2a4558638e.png)

**Comment by daren-thomas** [comment]
Does this hold for other plots too? (Is it a problem with the dashboard implementation of plots or just the EnergyBalancePlot?)

**Comment by JIMENOFONSECA** [comment]
yep. I just tired with the EnergyDemand plot. the same problem. It seems to be systematic...

**Comment by daren-thomas** [comment]
ok. thank you for the clarification. i'll start working on that once the caching PR is merged.

**Comment by daren-thomas** [comment]
I just tried with your example (Energy Balance Plot):

- create new Dashboard
- first plot: Energy Balance Plot for Building 001
- second plot: Energy Balance Plot for Building 002
- notice how the two plots show different values (the difference is rather small, but hovering over the values will show it)

- yes, when selecting all buildings, there _is_ a quirky behavior of the title being "Energy Balance Plot for Building 001" - I) think this is related to another bug (#1658) and is probably a bug in the plot code. Further investigating. (FIXME: we'll need to test each of the plots for this behavior)

**Comment by daren-thomas** [comment]
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/9bec8534-6741-4a9a-8140-cd6416a6bad1)

The reason for this behavior is that this particular plot only works for one building - the first in the list.  I think I can update the code to work with multiple buildings...

**Comment by daren-thomas** [comment]
See [PR 1880](https://github.com/architecture-building-systems/CityEnergyAnalyst/pull/1880) for a fix to this specific issue (there are other issues, namely #1868, #1870 that I still need to check once this has been merged).
