### ISSUE TITLE
Daysim broken in master

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1873]
So it got broken since we enabled Linux machines to use CEA. a few PR's ago.

you can solve this issue by doing:

1. open anaconda prompt
2. do activate cea
3. do pip install -U --no-cache git+https://github.com/chenkianwee/py4design

@daren-thomas is helping us to have a permanent solution to this issue

**Comment by daren-thomas** [comment]
Besides the py2radiance stuff (which is just basically calling out to daysim, right?) - what other stuff are we using from py4design?

We recently saw a demonstration of the COMPAS project being developed at BRG and other ITA chairs and... that would let us do geometry stuff without having to include OCC/pyOCC, which is a tricky dependency of py4design. And they have more manpower to maintain. I would then suggest we wrap Daysim ourselves, as the way py2radiance does it does not handle errors at all (system calls are not checked). And kianwe does not seem to be responding to update requests.

**Comment by JIMENOFONSECA** [comment]
It could make sense, BUT, this will not be a priority until the Interface and the installer be complete

**Comment by daren-thomas** [comment]
We wait a week to see if kianwee was on vacation.

**Comment by chenkianwee** [comment]
Hi sorry for not responding quickly. I would suggest using the honeybee module from the ladybug library. It is actively under development and have a huge community using it compared to my library which is just developed by me, so I don't think it is necessary to wrap daysim urself. (https://www.ladybug.tools/) Ya I agree with daren regarding the geometry engine, PythonOCC is a very tricky dependency. So if other chairs from ITA is doing their own geometry library, I recommend the sitch, as I cannot promise swift replies and response to issues. Sorry

**Comment by daren-thomas** [comment]
@chenkianwee is there a way we could help py4design? the parts we are mainly interested in are in py2radiance. i'm a bit hesitant to incorporating it directly into the CEA because of licensing issues (the GPL license makes this hard even if we were to rewrite most stuff)

Otherwise, we could fork? Would you be ok with that?

**Comment by chenkianwee** [comment]
@daren-thomas I am fine with you forking it, I am glad you can build upon my codes.

**Comment by JIMENOFONSECA** [comment]
Sorry to put the brakes in here, but unless this fork, and publishing this fork /ammendments takes just 1 day, includng future maintenance. I would prefer if Chianwee can just publish in pypi the master version of py4design. Which will solve our inmediate issues.

We have many other things with top priority in the pipeline and should not loose focus at any point in time.

Chianwee, i appreciate your urgent help on this.
On 23 Apr 2019, 22:16 +0800, chenkianwee <notifications@github.com>, wrote:

@daren-thomas<https://github.com/daren-thomas> I am fine with you forking it, I am glad you can build upon my codes.

**Comment by chenkianwee** [comment]
@JIMENOFONSECA so all i need to know is the commit it to PYPI ? If that is the case I just uploaded it, version 0.27 . Sorry for the delay, I must have gotten lost from the messages. Hope it solves your problem.

**Comment by JIMENOFONSECA** [comment]
@chenkianwee many thanks, all works good now! #fixed in PR #1922
