### ISSUE TITLE
Demand calculation B07 problematic

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1881]
@martin-mosteiro @gabriel-happle I think you guys changed the open case study to include servers. Which is great.

However,  there is a problem.. Building 07 is registering a E_sys_kWh (all electrical system end-demand) that does not consider the cooling demand (of the servers) converted into electricity.

Moreover, the energy supplied by the GRID kWh is 0!, despite the supply system being T1 = electrical grid. 

Here you can notice the difference between demand and supply

![image](https://user-images.githubusercontent.com/8973186/56008811-0ff3b300-5d10-11e9-841f-6e0f02703a92.png)

![image](https://user-images.githubusercontent.com/8973186/56008828-200b9280-5d10-11e9-8ad4-824eb6b03dc2.png)

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Due to a typo (see issue #1886) the electricity demand for cooling server rooms wasn't actually being calculated anywhere, so 
- if Edata=0, E_cdata=0 and GRID = E_sys+...+E_cdata=a number
- but if Edata>0, E_cdata=NaN and GRID=E_sys+...+E_cdata=NaN
PR #1887 solves this issue.

**Comment by gabriel-happle** [comment]
Thanks @martin-mosteiro for taking care of this!

**Comment by martin-mosteiro** [comment]
This issue **should** be solved now, but I haven't actually checked. Would make sense to run the open case again and check the results.

**Comment by JIMENOFONSECA** [comment]
yes we can close it now. PR #1887 solved it.
