### ISSUE TITLE
plot-supply-system not running

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1889]
The function `preprocessing_generation_data` in `cea\plots\supply_system\main.py` is not updated with the new names 
this function is similar to `preprocessing_generation_data` in `cea\analysis\multicriteria\main.py`, and update the column names, but they are not exactly the same

**Comment by shanshanhsieh** [comment]
once fixed, this should be added to the `cooling-case-workflow`

**Comment by JIMENOFONSECA** [comment]
fixed in #2120
