### ISSUE TITLE
Daysim error when username has a whitespace

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#1890]
Did a fresh installation of CEA following the steps indicated in the docs (https://city-energy-analyst.readthedocs.io/en/latest/installation-on-windows.html) and was not able to run Daysim.

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\test\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\cityenergyanalyst\cea\interfaces\cli\cli.py", line 56, in main
    script_module.main(config)
  File "c:\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 214, in main
    radiation_singleprocessing(rad, geometry_3D_zone, locator, config.weather, settings)
  File "c:\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 165, in radiation_singleprocessing
    daysim_main.isolation_daysim(chunk_n, rad, building_dict, locator, weather_path, settings)
  File "c:\cityenergyanalyst\cea\resources\radiation_daysim\daysim_main.py", line 161, in isolation_daysim
    rad.execute_epw2wea(weather_path, ground_reflectance = settings.albedo)
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\py4design\py2radiance\__init__.py", line 890, in execute_epw2wea
    results = open(weaweatherfile, "r")
IOError: [Errno 2] No such file or directory: 'c:\\users\\reynol~1\\appdata\\local\\temp\\temp0\\wea\\Zug_60min.wea'
```

I noticed that this is related to issue #1709 
After debugging, I found out that the program was trying to execute:
```
epw2wea c:\\users\\reynold mok\\documents\\development\\cityenergyanalyst\\cea\\databases\\weather\\Zug.epw c:\\users\\reynol~1\\appdata\\local\\temp\\temp0\\wea\\Zug_60min.wea
```
The space in the first directory parameter due to the username definitely messed up the execution so the .wea was not created. Manually enclosing the first parameter in " " using the debugger allowed the program to run and create the file. It was happy with the second parameter.

Possible solution could be to handle this exception in the program, or maybe could ask users to git clone the repo into the root directory (i.e. C:\) at the start so that the program looks for the databases in "c:\\cityenergyanalyst\\cea\\databases\\..." instead, bypassing the username. Not sure if that works yet.

**Comment by daren-thomas** [comment]
hey @reyery! welcome!

ugh! that's an annoying bug to run into. In the end, what I think we need to do is update the `py4design.py2radiance` library to shell out properly - and also check to see if the programs ran correctly. basically, the workflow is to fork that repo, make the fixes and then create a pull request for @chenkianwee to merge to his master. he will also need to update the version number and publish that to PyPI.

I'd rather not instruct people to clone into the root directory as that is generally frowned upon.

**Comment by JIMENOFONSECA** [comment]
@reyery glad you are in. I follow @daren-thomas suggestion, the best is to directly fix the issue, and make a pull request (PR) to the repository owner. We happen to know him, he is a CEA Alumni :-)

**Comment by reyery** [comment]
Thanks for the welcome!

> I'd rather not instruct people to clone into the root directory as that is generally frowned upon.

Ah yes. Noted.

I have just submitted a pull request to the `pydesign` repo with the minor fix and the fix seems to be working on my desktop now, Daysim is now running.

**Comment by JIMENOFONSECA** [comment]
Hi @reyery btw, if you have time, please take a look at issue #1813. This could be our first work together with CEA.  Let me know your thoughts on that issue and if you need more info

**Comment by reyery** [comment]
@JIMENOFONSECA sure no problem, will definitely look into that.

**Comment by daren-thomas** [comment]
Just sent Kianwee an email regarding your PR, @reyery. Let's see how this progresses.

**Comment by daren-thomas** [comment]
Progress report: Green light from Kianwee to work on a PR to fix similar issues and he'll merge then. @reyery 's PR got merged. I suggest we fix the other `os.system` calls and then create a PR with a new version number so we can have a new version on PyPI. In the meantime, we're shipping our own environment anyway, so we could use the GitHub version no problemo. I'll add that to the next release (2.18)
