### ISSUE TITLE
Update documentation on how to create documentation to include inputs / outputs

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1891]
The PR #1877 updates the script `cea trace-inputlocator` to trace input / output files of a script. The PR has a good summary of how to run it and what to expect. This issue concerns two minor missing points:

- update the documentation on rtd to include build instructions for the viz stuff
- automate the steps described in the PR comments:
  - copy all the viz files and dump them in CityEnergyAnalyst\docs\script_dependencies
  - then run the script script_dependencies_gen.py (in the same dir)
  - this should be a batch file or something similar to `bin\make-api-doc.bat`

**Comment by daren-thomas** [comment]
also, find a better place to put this: https://city-energy-analyst.readthedocs.io/en/latest/script-input-outputs.html

**Comment by daren-thomas** [comment]
@Jack-Hawthorne do you have a status update on this?

**Comment by Jack-Hawthorne** [comment]
These have all been addressed by #2017 and #2067 
The graphviz tool now reads the `scripts.yml` when called via the cli `cea-doc graphviz`, rebuilding all the graphviz files and updating the related rst file.
