### ISSUE TITLE
Icons for CEA

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1892]
For the upcoming installer, I need some Icons for the CEA

- multiple resolutions (16x16, 32x32 at least)
- will end up for installer.exe, menu shortcuts, CEA Console (yep. figured that out. it's a thing)

**Comment by shizhongming** [comment]
![16](https://user-images.githubusercontent.com/16640327/56677513-e3b23c00-66ea-11e9-8c1a-9401fcc20f17.png)
![32](https://user-images.githubusercontent.com/16640327/56677514-e44ad280-66ea-11e9-8241-038554384846.png)
![128](https://user-images.githubusercontent.com/16640327/56677515-e44ad280-66ea-11e9-9ab5-9e09b094cb82.png)
![256](https://user-images.githubusercontent.com/16640327/56677518-e44ad280-66ea-11e9-89ab-30cffbc7b98d.png)
Dear @daren-thomas , Please find the 16X16, 32X32, 128X128, 256X256 pixles here. Version 1 and I am happy to adjust them after you try them. :)

**Comment by daren-thomas** [comment]
this is great! @shizhongming could you also create a set with fade to dark background?

**Comment by shizhongming** [comment]
@daren-thomas Hi! How about we use a square instead of rounded corners. (I am not sure I really get your point as when I placed the rounded logo onto a dark background, I did not see any gradient...)
![16_square](https://user-images.githubusercontent.com/16640327/57064227-46619400-6cf8-11e9-8fa6-908d2fa7c8e4.png)
![32_square](https://user-images.githubusercontent.com/16640327/57064235-495c8480-6cf8-11e9-8981-41bea6901837.png)
![128_square](https://user-images.githubusercontent.com/16640327/57064238-4b264800-6cf8-11e9-9054-d7aa63cef500.png)
![256_square](https://user-images.githubusercontent.com/16640327/57064242-4cf00b80-6cf8-11e9-997b-6bc370f1eeb2.png)

**Comment by daren-thomas** [comment]
@shizhongming I like these! I'm using them for my next pull request for the installer and radiation stuff!

**Comment by JIMENOFONSECA** [comment]
sorry to put the brakes for this. the White and purple does not relate to CEA. It would be good to keep the colorful identity we have to until now.

**Comment by JIMENOFONSECA** [comment]
@shizhongming no square, we need a rounded logo, please figure it out how to avoid the white background issue, please...

**Comment by shizhongming** [comment]
@daren-thomas @JIMENOFONSECA I just made a new rounded version and hope they dont have the white edge this time (I dont see white edge as I tested in photoshop)... @daren-thomas one question, the format of the image has to be png only or it accept vector like eps also?

![CEA_desktop_icon_v2 1_16](https://user-images.githubusercontent.com/16640327/57432582-dc516d80-7268-11e9-8443-fcfea4547ff8.png)
![CEA_desktop_icon_v2 1_32](https://user-images.githubusercontent.com/16640327/57432583-dcea0400-7268-11e9-8bca-88717447082b.png)
![CEA_desktop_icon_v2 1_128](https://user-images.githubusercontent.com/16640327/57432584-dcea0400-7268-11e9-9690-3aaa33b76e7d.png)
![CEA_desktop_icon_v2 1_256](https://user-images.githubusercontent.com/16640327/57432585-dd829a80-7268-11e9-83ba-0485d4775868.png)

**Comment by daren-thomas** [comment]
@shizhongming actually, they end up as a *.ico file, but the png files work perfectly for inclusion. The fading issue turned out to be a 24bit vs. 32bit bmp issue (1 bit for transparency or 8bits... turns out, visual studio could only do 24bit icons, but i found a tool that can do 32bit icons so it works!)

closing as it's part of #1947.
