### ISSUE TITLE
Blog entry for Milestone M2.13

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1896]
The Blog should be about how to use Grasshopper and CEA. Potentially, only about creating the Zone.shp file and the occupancy and age files. The rest (district, streets, terrain) can be done with the blog published in M2.12

**Comment by JIMENOFONSECA** [comment]
In reference to issue #481 we will give it a shot and include video tutorials in all Blog entries.

**Comment by shizhongming** [comment]
I am creating a series of blogs on CEA at Grasshopper. The first blog is about the installation of the CEA Grasshopper interface, producing .dbf files. Yet need to include a video.

**Comment by shizhongming** [comment]
@daren-thomas I just finished the first blog on Squarespace....could you have a look? Thanks.

**Comment by daren-thomas** [comment]
@shizhongming how do i access it?

**Comment by shizhongming** [comment]
@daren-thomas Jimeno told me you have credentials to the Squarespace..nvm, i just made it public. Please use this link.
 https://cityenergyanalyst.com/blog-1

**Comment by daren-thomas** [comment]
hey @shizhongming ah. i understand. yes. i probably should have figured that out on my own. sorry.

This is fantastic! I _love_ it!

I do have some small comments:

- the workflow for the installation is different with the introduction of the installer: 
  - step 2 should be: launch the CEA Console from the Start menu
  - step 3 is not required
  - step 4, formatting of indented list
- in "Creating .dbf files", the sentence "If they are renovated, keep the corresponding cells as “0“." should probably be "If they are *not* renovated"
  - check formatting of nested lists

**Comment by shizhongming** [comment]
@daren-thomas thanks for the comment!
However, the `cea install-grasshopper` is currently not working under the cea console. the errors are as follows. could you have a look? Thanks~ (I unpublished the blog for the moment)

C:\Users\Zhongming\Documents\CityEnergyAnalyst
λ cea install-grasshopper
City Energy Analyst version 2.13.5a1
Running `cea install-grasshopper` with the following parameters:
- general:debug = False
  (default: False)
Traceback (most recent call last):
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 56, in main
    script_module.main(config)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\grasshopper\install_grasshopper.py", line 38, in main
    copy_config(scripts_folder)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\grasshopper\install_grasshopper.py", line 54, in copy_config
    shutil.copy(os.path.join(cea_src_folder, 'concept_parameters.py'), cea_dst_folder)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\shutil.py", line 133, in copy
    copyfile(src, dst)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'c:\\users\\zhongming\\documents\\cityenergyanalyst\\cityenergyanalyst\\cea\\concept_parameters.py'

**Comment by daren-thomas** [comment]
ah. right. i think i saw that - but fixed it on your old branch. let me see. i'll create a pull request.

@JIMENOFONSECA this error has to do with the `concept_parameters.py` file being removed. do you know what happened to it? I tried to find it, but I think it never existed?

Anyway, I made a small PR to fix this. Check out #1973

**Comment by daren-thomas** [comment]
@shizhongming still needs to test this, issues with `install-grasshopper` command. @daren-thomas will provide some help.
