### ISSUE TITLE
Blog Post: “Getting Started with your own project” Guide

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1897]
Based on the findings of the 1st CEA user survey, we conclude that there is a comprehensive guide/documentation needed about setting up a new project in CEA from scratch.

This should be addressed in a blog post that also features the new interface and new tools currently in production.

**Comment by gabriel-happle** [comment]
Assigning @reyery to this issue

**Comment by daren-thomas** [comment]
@reyery will finish this today :)

**Comment by reyery** [comment]
Blog is now published!
