### ISSUE TITLE
Yearly plot for district solar technologies graphs don't display any results

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1898]
I did the following:

1. Ran the PV, PVT, FP and ET potential scripts
2. Ran `main` from `cea.solar_technology_potentials`

The following graph is created:
![before](https://user-images.githubusercontent.com/18548065/56380569-cf65cf00-6212-11e9-99b8-4008481d04da.png)

I tried deleting the five instances of `visible='legendonly',` in `cea.solar_technology_potentials.all_tech_yearly` and the graph looks better...
![after](https://user-images.githubusercontent.com/18548065/56380706-2ec3df00-6213-11e9-9f1f-baa504e99d83.png)
But they are still not quite right. Plus, they are not on the same y-axis, so the following happens:
![issue](https://user-images.githubusercontent.com/18548065/56380769-531fbb80-6213-11e9-9d85-7f9c83fc1292.png)

I'm assigning @shanshanhsieh as I suppose she created these plots, feel free to reassign.

**Comment by daren-thomas** [comment]
Closing as not replicated.
