### ISSUE TITLE
More friendly EXIT message when quiting the dashboard

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1911]
![image](https://user-images.githubusercontent.com/8973186/56714241-cd49c600-6766-11e9-857e-69244bedb444.png)

**Comment by daren-thomas** [comment]
what are the steps to reproduce this?

this message is from the browser, not the cea dashboard. basically, you're trying to connect to the dashboard, but the dashboard is not running.

**Comment by JIMENOFONSECA** [comment]
To reproduce:


  1.  run cea dashboard.
  2.  Open the browser.
  3.  In the cea dashboard/bottom left, click the turn off button.

Then you get that messagge.

It would be good to have a pop up  that says (are you sure you want to exit? And then close the browser tab or send a messagge on how to exit.




_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 25 Apr 2019, 18:59 +0800, Daren Thomas <notifications@github.com>, wrote:

what are the steps to reproduce this?

this message is from the browser, not the cea dashboard. basically, you're trying to connect to the dashboard, but the dashboard is not running.

**Comment by daren-thomas** [comment]
I misunderstood: This issue applies to the shutdown button on the CEA Dashboard page.

We could maybe just remove the button? Or shut down the flask application...

**Comment by JIMENOFONSECA** [comment]
not necessary anymore
