### ISSUE TITLE
Make sure radiation-daysim works after installing the CEA with the Installer

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1914]
The installer bundles Daysim binaries. These still need to be tested properly. First field tests (thank you @JIMENOFONSECA) imply it doesn't quite work yet.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I just tested the executable of version 2.13, It does not work. I believe the fix has to do with that of #1909. I made a comment in there...
