### ISSUE TITLE
Update installer to retrieve CEA environment from a known location

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1915]
Currently, I'm hosting the CEA environment on my polybox account. I think we should find a better place to find it - something not only I have access to.

This issue includes updating the Release how-to to include updating the CEA environment with the current version (do a `pip install path-to-cityenergyanalyst` inside that environment, create the 7z archive and post update to new url)

**Comment by JIMENOFONSECA** [comment]
What about storing it in a repository in GitHub?

**Comment by daren-thomas** [comment]
It seems we can do this as part of a release: https://help.github.com/en/articles/distributing-large-binaries

I'm on it.
