### ISSUE TITLE
Open CEA dashboard directly from the ICON

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1916]
3rd ISSUE: I believe I had implemented the option to open automatically the cea interface. Now when I click CEA dashboard it opens this.

I believe it should directly open the browser (no the console). We can open the console with other executable as I see, right?

![image](https://user-images.githubusercontent.com/8973186/56714407-4d702b80-6767-11e9-94d3-4b1a12c4dad8.png)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I believe this works. Can you test it please?

**Comment by JIMENOFONSECA** [comment]
Should I wet for your fixes to the installer so I test all?

**Comment by daren-thomas** [comment]
Since we do have a short deadline, you could maybe test some issues together with this installer: https://www.dropbox.com/s/iavdblwizr9x9v0/Setup_CityEnergyAnalyst_2.13.exe?dl=0

It should have quite a few of the issues resolved.

**Comment by JIMENOFONSECA** [comment]
This works in the latest version of the installer (see releases)
