### ISSUE TITLE
As a user I would like to not get blocked once one Job in the CEA dashboard starts

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1926]
So until now, we have this message window that shows the status and messages when we use a tool in cea.

![image](https://user-images.githubusercontent.com/8973186/57055113-9c6c1280-6ccb-11e9-8853-4d7445c00490.png)

I believe we should change it to a small message bar on the bottom right of the screen (like that one in pycharm. 

This should show without blocking the user to navigate across the interface, while the job gets completed.

Optionally, The user could check the messages inside the job by clicking in this bar. 

The message bar should indicate when the tool is finished.

**Comment by daren-thomas** [comment]
@reyery how long do you think this could take? could you please update the story points for this issue? thank you :)

**Comment by daren-thomas** [comment]
Progress made here in the branch `1926-cea-worker`: a new script `cea-worker` can access a new api (`/server/jobs`) to run scripts. Output is marshalled via HTTP back to the cea webserver.

socket.io is used to pass output back to the browser - currently, the ticker (update from running scripts flash at the bottom of the web page) works, but I still need to port the tools part to use the new system.

**Comment by daren-thomas** [comment]
Progress update for branch `1926-cea-worker`: tools now run using the job api with socket.io for communication between the `cea-worker` process and the browser. yay!

User can hit [ESC] to exit modal dialog and go to other parts of the application (or start another job...) and continue with their work. If an error happens, an Alert is shown with the error message.

Also, while user is working, a "ticker" shows the last line of output at the bottom of the browser window...

TODO: 

- add a "jobs" page that shows all jobs (filter by status?) with their parameters etc.
- allow "minimizing" a job's output dialog
  - make sure output is routed to the "correct" dialog (currently, the output get's all mixed up...)
- fix the alert to be a nicer (modal) dialog
  - with a link to the job overview?
  - with a link to post a bug? (this is probably a bad idea, as we would get swamped with issues that might just be user errors)

**Comment by daren-thomas** [comment]
Progress update:

- jobs page added (`http://localhost:5050/tools/`)
- press [ESC] to close dialog and go start some other job
- updates to job states are reflected in real-time
- click on job in table to show output (output is shown as it happens, but also for jobs that are completed success/error)

TODO:

- add link to jobs page (maybe use that as a starting page for creating jobs?)
- make the minimized output (bottom right) nicer. i'm imagining a combobox to scroll through
