### ISSUE TITLE
Multi-criteria after optimization broken for DH case

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1927]
After running decentralized, and centralized optimization with district heating, I am trying to run multi-criteria. It seems some arrays do not have the same length.

What could be the problem? @shanshanhsieh the data is 4Gb so I can pass it to you via a hardisk

![image](https://user-images.githubusercontent.com/8973186/57117060-f6341180-6d8b-11e9-8722-8599be8db9c5.png)

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh have you had the chance to check that the problem is?

**Comment by shanshanhsieh** [comment]
i just had a quick look, it seems like the script is reading information from the checkpoints.
and the df_network is hard-coded to read `DCN_list_All` (line 167)
that might be the problem? 

![image](https://user-images.githubusercontent.com/16998305/57432781-5aae0f80-7269-11e9-82c1-5c13f0c347d1.png)

**Comment by JIMENOFONSECA** [comment]
Yeah, that is right, the problem is there, it seems it needs to take DHN_list_all when running the heating case. Still, it seems it is returning a list of individuals that do not match the same length for all parameters.

best, Jimeno



On 9 May 2019, 2:50 PM +0800, Shanshan Hsieh <notifications@github.com>, wrote:

i just had a quick look, it seems like the script is reading information from the checkpoints.
and the df_network is hard-coded to read DCN_list_All (line 167)
that might be the problem?

[image]<https://user-images.githubusercontent.com/16998305/57432781-5aae0f80-7269-11e9-82c1-5c13f0c347d1.png>

**Comment by daren-thomas** [comment]
@shanshanhsieh how much time do you think this issue would take to solve? how many story points? could you please update that information?

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA please try to run the script in branch `i1927`
it should be running now, i didnt have time to check the plots, please let me know if the numbers make sense

**Comment by JIMENOFONSECA** [comment]
Hi Shanshan,

Thanks for this. so the multi-criteria runs :-),

However the optimisation (overview and detailed) do not run. Would you mind taking a look?

Many thanks for this!



On 20 May 2019, 8:09 PM +0800, Shanshan Hsieh <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> please try to run the script in branch i1927
it should be running now, i didnt have time to check the plots, please let me know if the numbers make sense

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA great, i will send a PR when i test the results with a cooling case 

for optimization, do you mean the plotting part? could you make a separate issue about that?

**Comment by JIMENOFONSECA** [comment]
Well, the thing is that if the optimization_overview plot does not run, then it means the problem persists. since I cannot visualise it. I d o not know i the results make sense.

Jimeno



_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 21 May 2019, 1:35 PM +0800, Shanshan Hsieh <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> great, i will send a PR when i test the results with a cooling case

for optimization, do you mean the plotting part? could you make a separate issue about that?

**Comment by shanshanhsieh** [comment]
okay, got you, i'll take a look

**Comment by shanshanhsieh** [comment]
Hi @JIMENOFONSECA , this part of plotting is not ready for heating case at all. (you can run the optimization plot until `supply_system_configuration` now.
and the implementation of the cooling case is very confusing, which means i have to first spend some time understanding its structure in order to implement the heating case...

before jumping into the rabbit hole, i think we should have a meeting to discuss what are the other essential improvements required for the executive course, and budget our time on this and other issues accordingly

**Comment by JIMENOFONSECA** [comment]
Sure... i am leaving for 3 weeks after the group meeting of this week. So we need to discuss it promptly...

But in essence, the optimization and its plots should work for the heating case....

What are your thoughts?

Jimeno

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 21 May 2019, 18:21 +0800, Shanshan Hsieh <notifications@github.com>, wrote:

Hi @JIMENOFONSECA<https://github.com/JIMENOFONSECA> , this part of plotting is not ready for heating case at all. (you can run the optimization plot until supply_system_configuration now.
and the implementation of the cooling case is very confusing, which means i have to first spend some time understanding its structure in order to implement the heating case...

before jumping into the rabbit hole, i think we should have a meeting to discuss what are the other essential improvements required for the executive course, and budget our time on this and other issues accordingly
