### ISSUE TITLE
COOLROOM and LAB do not have archetypical process schedules defined

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1932]
While working on #1794 it became evident that COOLROOM and LAB do not have process schedules defined for calculating refrigeration loads and process electricity consumption respectively.

In `occupancy_model.py` line 578 it is obvious that only INDUSTRIAL has a process schedule defined.

process schedules have to be added to the `occupancy_schedules.xlsx` database and the `read_schedules` function has to be adjusted.

**Comment by martin-mosteiro** [comment]
@gabriel-happle The issue with COOLROOMs is addressed in issue #1930.

Regarding LABs, I remember creating a process schedule for these back when I created the LAB archetype (just copied the INDUSTRIAL process schedule), but maybe it got lost along the way? And in any case I don't think a large manufacturer (as used to define the process schedules for INDUSTRIAL) is a valid reference for a LAB. Maybe these should just use the electricity schedules as process schedules?

**Comment by gabriel-happle** [comment]
@martin-mosteiro let me know when #1930 is fixed.

Regarding the LAB, in that case, it would be easier to just increase the equipment load and get rid of the process load.

**Comment by martin-mosteiro** [comment]
I agree. Although in more general terms, I think the "process" calculations in general are not very clear at the moment. Besides, demands for process heating or cooling are probably served by dedicated, separate systems (like in COOLROOMs and SERVERROOMs).

**Comment by martin-mosteiro** [comment]
However, getting rid of the process schedule in labs would mean that LABs can never have process electricity. Which I guess is fair if we assume that processes in LABs are just lumped into appliances.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle @martin-mosteiro do not get rid of this. They are used in optimization as sources of waste heat, and sources that need specific boilers (due to the temperature needs)

**Comment by martin-mosteiro** [comment]
@gabriel-happle #1994 will solve part of the issue described here. The missing part is the process schedules for LABs.

**Comment by gabriel-happle** [comment]
@martin-mosteiro cool. I will copy the Industry schedule for now. And then make a PR soon

**Comment by gabriel-happle** [comment]
@martin-mosteiro you were right! there is a process schedule for LAB, but only in the CH archetypes.
I was checking the reference-case-cooling at the time I made this issue.
I will just add the same schedule to the SG archetypes and test quickly in both regions.

**Comment by gabriel-happle** [comment]
@martin-mosteiro in any case, the process schedules of LAB (and HOSPITAL) were not read by the `read_schedules` function.
I also noticed that HOSPITAL has processes in CH.
I'm therefore adding the same schedules in SG.
