### ISSUE TITLE
district.shp file created by district_geometry_helper does not have 'floors_bg' attribute

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#1933]
Trying to view the district inputs in the dashboard throws this error

```
AttributeError: 'Pandas' object has no attribute 'floors_bg'
```
The district.shp file created by district_geometry_helper does not have the required attributes 'height_bg' and 'floors_bg'.

**Comment by reyery** [comment]
@JIMENOFONSECA I could add both of this attributes as input parameters to the district helper script, similar to what the zone helper is currently doing.

**Comment by JIMENOFONSECA** [comment]
HI Reynold, that behavior is intended. We do not need information about what is underground the district to run simulations at the moment. So it is another set of parameters we can save.
On 6 May 2019, 3:21 PM +0800, Reynold Mok <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> I could add both of this attributes as input parameters to the district helper script, similar to what the zone helper is currently doing.
