### ISSUE TITLE
Delete default dashboard and stop loading/creating plots by default

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1942]
So the CEA dashboard creates random plots once we start a scenario.

It would be good to stop this behavior. Let the user go to the Dashboard and create a new dashboard on its own.

This of course, after running some tools.

**Comment by JIMENOFONSECA** [comment]
@reyery this is closed right?

**Comment by reyery** [comment]
@JIMENOFONSECA Not yet, still working on it. I have stopped the dashboard from creating the default plot, but am trying to change how the user would create/manage different dashboards.
