### ISSUE TITLE
add a publisher to the CEA installer so windows does not stop it

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1945]
basically, offer some information about the publisher to avoid the next message

![image](https://user-images.githubusercontent.com/8973186/57282129-0119d980-70df-11e9-8000-0428a084dab0.png)

**Comment by daren-thomas** [comment]
It's not about offering publisher information, it's about digitally signing the .exe. It depends on the configuration of your operating system (on mine, this does not happen, so I can't really debug it for you - maybe Reymond can replicate this?).

OS X has a similar thing with apps downloaded from the internet, where you have to open them a right way, basically, it means "look, this piece of software can basically do anything it likes, do you really want to run this? we couldn't figure out who made it".

Let's keep this link here for future reference: https://stackoverflow.com/questions/44377666/pyinstaller-exe-throws-windows-defender-no-publisher

(in case we decide to shell out some money to digitally sign this. i think we don't have to do it at this point)

**Comment by JIMENOFONSECA** [comment]
@daren-thomas if that is what is required, I am assigning this to known issues and won't have
