### ISSUE TITLE
zone.cpg file being created when creating new project with dashboard

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#1946]
When creating a new project using the dashboard interface, a zone.cpg file will be created in the new project path.

For example, if the new project is saved as ` C:\new-project\`, a zone.cpg file will be created in the folder structure ` C:\new-project\baseline\inputs\building-geometry\zone.CPG`.

This also happens as long as the project in the current config does not exist, when the page is loading.

i.e. If the project in the current config ` C:\old-project\` does not exist anymore, loading another page would still create ` C:\old-project\baseline\inputs\building-geometry\zone.CPG`.

**Comment by reyery** [comment]
@daren-thomas after debugging for a while, I realized that it might be caused by this context processor that is running at every page load.

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/acd1a295b72e762f0e610f6e0e71752b694172e0/cea/interfaces/dashboard/dashboard.py#L37-L40

**Comment by daren-thomas** [comment]
good debugging! i'm pretty sure somewhere in there the `_ensure_folder_exists` method on `InputLocator` is being called. maybe we can refrain from doing that eagerly?
