### ISSUE TITLE
Create Blog on how to install CEA

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1953]
@daren-thomas I believe the final step on the installer initiative is to write a blog about how to install CEA. Please make the honors

For the blog. Either:

Include some Gif animation of the process: You can use shareX for this in windows.
OR
Create a video of the process.

I suggest to divide the blog in two sections.

1. the first consist in installing the normal version.
2. the second consist in installing the development version (that one should include also steps on how to connect the repository to Github and Pycharm..

**Comment by daren-thomas** [comment]
@JIMENOFONSECA please check this first draft for the blog entry: https://daren-thomas.github.io/installing-cea-on-windows/

**Comment by JIMENOFONSECA** [comment]
Looking good!.

Just a few comments:

1. Just please make a Gif of the Screenshots or a Video, up to you. This is somehow the format we would like to go for. ShareX works like a charm for this in windows.

2. MIT License

3. Divide the Blog into two bog entries. (just like I did for the data helper thing). One entry is for normal users, the second entry is for researchers/developers.

3. For the researchers part, please add information about how to download and add the local repository to Github Desktop (our default git manager).

4. The connection to Pycharm is essential, please add a few steps (in a gif or video) on how to do it.

And that is all. Once ready, go ahead and upload it into the website.

I will be on vacation from Thursday on until the mid-June.

Best,
Jimeno



_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 15 May 2019, 10:08 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> please check this first draft for the blog entry: https://daren-thomas.github.io/installing-cea-on-windows/

**Comment by daren-thomas** [comment]
I made the changes requested and added the post to the squarespace blog thing as a draft. I'm not so sure about a header (poster?) image - how did you guys do that? also: what kind of image should i choose? i'm a bit at a loss here...
