### ISSUE TITLE
The installer shows low-res icons in the desktop

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1955]
![image](https://user-images.githubusercontent.com/8973186/57663912-99a4e200-7628-11e9-92e1-513a11262e2e.png)

**Comment by JIMENOFONSECA** [comment]
Also, in terms of installation steps, the desktop shortcuts should be created as the last step of the installation. Otherwise, there is a temptation to open the CEA before the installation finishes

![image](https://user-images.githubusercontent.com/8973186/57663975-e38dc800-7628-11e9-84ab-0872e17024f3.png)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I wonder if there is any way to find out what resolution windows is using for your desktop. the icon file we ship has multiple resolutions in it: 16x16, 32x32, 128x128, 256x256. I wonder if you have something in between (there might be a 46x46) - I'll investigate.

**Comment by JIMENOFONSECA** [comment]
Hi daren, no worries, I think this is a low priority issue now.

Let’s get into the most important issue next  (publishing a blog on how to install CEA).

thanks,
Jimeno



On 14 May 2019, 2:49 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> I wonder if there is any way to find out what resolution windows is using for your desktop. the icon file we ship has multiple resolutions in it: 16x16, 32x32, 128x128, 256x256. I wonder if you have something in between (there might be a 46x46) - I'll investigate.

**Comment by daren-thomas** [comment]
@shizhongming i checked, the resolution we're missing seems to be 48x48. could you please send me such an icon? thank you :)

**Comment by shizhongming** [comment]
Hi @daren-thomas , Sorry for the late reply as Monday was a public holiday in Singapore...please find the 48X48 here :)

![CEA_desktop_icon_v2 1_48](https://user-images.githubusercontent.com/16640327/58066671-ece4da80-7bbc-11e9-908d-a003dc3417a0.png)
