### ISSUE TITLE
Plots in dashboard are not able to handle 'file does not exist' exception

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#1960]
Plots could not be successful created if the required files cannot be found, causing the dashboard to not be able to handle the exception and show the 500 status code error. 

Plots should still be created and also show useful information such as "Please run xyz simulation..." for the respective missing files, so that the user knows what to do.

**Comment by daren-thomas** [comment]
each plot knows a list of input_files that it requires. you can check for that.

**Comment by daren-thomas** [comment]
add a `check_inputs` to `PlotBase`, similar to:
```
 def get_creators(input_files):
     for locator_method in input_files:
         print meta_data[locator_method.__name__]['created_by']
```

meta_data is jacks's traceinputlocator output, check that here: `\cea\tests\trace_inputlocator.output.new.yml` - copy to `cea\schema.yml` and add stubs for optimization methods until we have all the data.

also, update `input_files` list on plots to be just the method (don't call) and maybe tuple if has parameters (`if type(input_file) is tuple...`)

- add hyperlinks to error message directly to run the tool :-)
