### ISSUE TITLE
Dashboard not working properly on Internet Explorer

### ISSUE THREAD

**Issue by Khayatian** [architecture-building-systems/CityEnergyAnalyst#1967]
The dashboard does not work properly with "internet explorer" (Windows 10). This can be an issue for institutional computers where the default app for browsing is set to "internet explorer". Perhaps a recommendation on the browser can help avoiding this issue.

**Comment by daren-thomas** [comment]
@Khayatian thank you for bringing this up! Would you mind posting some screenshots?

Is this IE (which version?) or Microsoft Edge?

**Comment by Khayatian** [comment]
@daren-thomas Some institutes reset the browser of the computer to IE every time it reboots. In my case, IE doesn't seem to run any of the modules (e.g. demand, daysim solar).

![demand-run- cmd-window](https://user-images.githubusercontent.com/27851066/58008588-fd2d8480-7aec-11e9-862d-8d2851ef2e0b.PNG)

![daysim-run-cmd-window](https://user-images.githubusercontent.com/27851066/58008593-00c10b80-7aed-11e9-857d-36ff6b0b1be9.PNG)

**Comment by daren-thomas** [comment]
> IE (which version?)

@Khayatian could you please answer the above question?

Also, I don't think this looks like an IE problem - I was expecting screenshots of the Dashboard looking all weird in Internet explorer... Could you please give detailed information on what works and what doesn't? What did you do to get this message?

It looks a bit like something is being blocked by a firewall, but I do not have enough information to make an educated guess what it could be.

**Comment by Khayatian** [comment]
@daren-thomas I see, so let me try it on a different PC. Also, the version of the IE is:

![Capture](https://user-images.githubusercontent.com/27851066/58014569-7632d900-7af9-11e9-83b8-706aa61531ac.PNG)

**Comment by Khayatian** [comment]
Apparently, this issue only concerns my computer not IE in general. Therefore, we can close the issue.
