### ISSUE TITLE
Update documentation on how to create a release and include information for Try It button on website

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1969]
@JIMENOFONSECA could you please update the documentation. The link needs to change with every minor release (2.14, 2.15, etc.)

**Comment by JIMENOFONSECA** [comment]
Done centuries ago :-)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA where is it? I'm checking here: https://city-energy-analyst.readthedocs.io/en/latest/how-to-create-a-new-release.html

I can't find it.

**Comment by JIMENOFONSECA** [comment]
Oh I thought it was about repairing the link only

**Comment by daren-thomas** [comment]
I just checked the link. It leads to here: https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v2.20/Setup_CityEnergyAnalyst_2.20.1.exe

Also, the way it's set up, we need to change it with every release. And when I make a new installer (the revision part of the version) - as a sort of hotfix if the first installer didn't work / needed an update, then it needs to change too. This needs to be documented so you're not the only person who knows how to do that.
