### ISSUE TITLE
What happened to the concept module?

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1974]
It seems it's referenced in `cea/optimization/flexibility_model/mpc_district/planning_and_operation_batch_run.py`. It's probably referenced in other places as well.

Was it removed?

**Comment by JIMENOFONSECA** [comment]
if it si not there, then it is removed...

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, maybe let me refrain the question a bit: What is the rationale? Why was it removed? Whoever removed it, didn't do a proper search / replace.

![image](https://user-images.githubusercontent.com/2969564/58234652-52f96b00-7d3f-11e9-8313-f4e90437281b.png)

This code is now non-functional. So I'd really like to know who moved it, where to, and what to do about the stuff that's now broken. Do we delete it?

**Comment by JIMENOFONSECA** [comment]
yep, I believe it is not part of the tools MPC-district and MPC-building anymore, so we can delete it…

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 23 May 2019, 3:47 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA>, maybe let me refrain the question a bit: What is the rationale? Why was it removed? Whoever removed it, didn't do a proper search / replace.

[image]<https://user-images.githubusercontent.com/2969564/58234652-52f96b00-7d3f-11e9-8313-f4e90437281b.png>

This code is now non-functional. So I'd really like to know who moved it, where to, and what to do about the stuff that's now broken. Do we delete it?

**Comment by daren-thomas** [comment]
ok. assigning to you - you are probably the most knowledgeable person on the team regarding this matter. we'll prioritize it next week.
