### ISSUE TITLE
Remove .cache folder from scenario listings

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1977]
The Project overview page in the CEA Dashboard shows the list of scenarios in a project. This is basically a list of all folders inside the project folder.

One of those folders, `.cache` is special, in the sense that it isn't a scenario, rather, it's a cache of plot data and plot outputs. This should not be shown in the listing.

The class `cea.config.ScenarioNameParameter` has a property `_choices` that implements this. It also has a type ("fodler_path") which could be removed at the same time...

**Comment by reyery** [comment]
@daren-thomas I do not see the `.cache` folder in the Project Overview page on my end when it is present in the project folder. However we could still change the current implementation of getting the list of scenarios using the config.

**Comment by daren-thomas** [comment]
Just checked. Confirmed. Closing. Thank you :)
