### ISSUE TITLE
Collapsable input fields for tools

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1979]
The CEA Dashboard tools section lists the parameters for running tools. In the ArcGIS interface, some of these parameters were "collapsed", by specifying a category for the parameter. This improves the user experience, by showing the most relevant parameters and at the same time allowing access to more specific parameters for power users.

**Comment by reyery** [comment]
@daren-thomas I'm not sure how I should choose which parameters should be collapsible. Right now I am thinking of grouping them based on the section the parameter is from, then only show the options relating to the `general` section and maybe it's own section. But judging from `script.yaml`, not a lot of options would be collapsed.

I was thinking maybe we could somehow tag the parameters to indicate which one is "basic" or "advanced" and collapse them accordingly.  I could split `parameters` in the `script.yaml` to include a "basic" and "advanced" key, `parameters` would just be the combination of these two keys.

**Comment by daren-thomas** [comment]
@reyery there is a ".category" portion in the `default.config` file. This was used in the ArcGIS interface to hide stuff that wasn't "default" below collapsing sections, using the ".category" value as the text of these sections. See, e.g. the "create-new-project" parameters.

**Comment by reyery** [comment]
@daren-thomas ah yes I see that now. Will see what I can do with them. Thanks!

**Comment by daren-thomas** [comment]
i think it could be as simple as some bootstrap thing... like maybe this: https://getbootstrap.com/docs/4.3/components/collapse/#accordion-example
