### ISSUE TITLE
Looped network created by layout script with `allow-looped-networks = false`

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#1980]
I have ran a 'thermal-network' optimization on a "large" project with 571 nodes and edges and 258 consuming buildings. The simulation on a CPU with 16GB RAM and 8 processors @3.6GHz has succesfully completed after 33 days. 
During simulation following warning was shown:
![BASELINE_ERROR_2](https://user-images.githubusercontent.com/26175926/58014030-328b9f80-7af8-11e9-8d64-305851ac6fcf.png)
which says: 'No convergence of pipe diameters in loop calculation, possibly due to large amounts of low mass flow. Please retry with alternate network design.'

The looped network option in the config file was turned off however. (used config file: [cea_baseline_1run.config.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/3197322/cea_baseline_1run.config.zip))

The edges file in the input folder after running the 'thermal-network' script does show one loop:
![loop_where_shouldntbe](https://user-images.githubusercontent.com/26175926/58013613-41258700-7af7-11e9-8c54-7c91e6d7d8c3.png)

How come a looped network is created?

**Comment by gabriel-happle** [comment]
can you try to reproduce this @emanuel030 ?
And send the input files `streets.shp` to @shanshanhsieh please.

**Comment by martin-mosteiro** [comment]
@shanshanhsieh here is the streets shapefile. The scenario he is running is the "Masterplan" scenario in the `cea-reference-case` repository. The scenario has changed significantly (an update of the reference case is still pending) but the building geometries should be the same as found in Emanuel's case.

[networks.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/3285337/networks.zip)

**Comment by martin-mosteiro** [comment]
@shanshanhsieh The case study including street networks and thermal networks are all in the `cea-reference-case` repository. The scenario @emanuel030 is referring to is **"1_Baseline"**

**Comment by daren-thomas** [comment]
We can't reproduce this right now.
