### ISSUE TITLE
Installation guide for windows includes misleading pycharm configuration

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1988]
https://city-energy-analyst.readthedocs.io/en/latest/installation-on-windows.html

When using the installer, should the environment in pycharm not point to `...\CityEnergyAnalyst\Dependencies\Python`?
(step 8 in pycharm set up)

**Comment by daren-thomas** [comment]
@gabriel-happle you're right. i'll update it. would you be up for reviewing?

**Comment by gabriel-happle** [comment]
@daren-thomas sure. I can review.
