### ISSUE TITLE
Replace nonsensical "alerts" in dashboard with other messages

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1989]
... maybe a welcome message, instead of something about film festivals
![image](https://user-images.githubusercontent.com/17002288/58071783-4d314780-7bd0-11e9-961a-74dfb4fe237f.png)

Also, nothing happens when you click. So maybe it can be removed altogether.

**Comment by daren-thomas** [comment]
How about this ends up being where simulation job updates get reported? Imagine, you sit down in front of the CEA Dashboard and start an optimization run. Inside the messages you could get updates (generation 1 completed, ... generation n completed, optimization completed) with links to plots showing the results?

**Comment by reyery** [comment]
The alerts are now hidden as of commit fec1a9941b14a37f73928513df967be7bae2f3dc until we can do something about it
