### ISSUE TITLE
Update the plots tools to use the new plotting system

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1990]
The `cea plots` (and relatives) tools use the old plotting system from the last Executive course. Since then, all the plots have been refactored to a class hierarchy, but the legacy code has been left intact - in order to be able to compare.

- rename the scripts to `cea legacy-plots[-*]`
- update the original plot scripts to use the new system
- run both sets and compare results
- make sure to update the output paths of the new plotting system to be the same as the old paths when done!

**Comment by daren-thomas** [comment]
Maybe we remove the `cea plots` tool alltogether. see discussion here: #2038

**Comment by daren-thomas** [comment]
After talking to @JIMENOFONSECA it seems we might just remove the functionality (`cea plots`) altogether. Instead, users will use the dashboard functionality for all plotting.

We still need to clean up and remove all the old plots. @JIMENOFONSECA, let's stay in touch about when we're ready to start removing them!

**Comment by JIMENOFONSECA** [comment]
Hi Daren,

We can erase now all the old plots related to:

1. Demand
2. Solar energy



On 19 Aug 2019, 4:51 PM +0800, Daren Thomas <notifications@github.com>, wrote:

After talking to @JIMENOFONSECA<https://github.com/JIMENOFONSECA> it seems we might just remove the functionality (cea plots) altogether. Instead, users will use the dashboard functionality for all plotting.

We still need to clean up and remove all the old plots. @JIMENOFONSECA<https://github.com/JIMENOFONSECA>, let's stay in touch about when we're ready to start removing them!

**Comment by JIMENOFONSECA** [comment]
Hi Daren,

We can erase now all the old plots related to:

1. Demand
2. Solar energy



On 19 Aug 2019, 4:51 PM +0800, Daren Thomas <notifications@github.com>, wrote:

After talking to @JIMENOFONSECA<https://github.com/JIMENOFONSECA> it seems we might just remove the functionality (cea plots) altogether. Instead, users will use the dashboard functionality for all plotting.

We still need to clean up and remove all the old plots. @JIMENOFONSECA<https://github.com/JIMENOFONSECA>, let's stay in touch about when we're ready to start removing them!

**Comment by daren-thomas** [comment]
We'll actually be erasing the plot tools as soon as we have implemented all the plots.
