### ISSUE TITLE
Issues with installer for CEA 2.14

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#1991]
CEA 2.14 Setup
"Uninstalling 2.14
Successfully installed CEA-2.11"
Version mismatch?
![CEA Setup](https://user-images.githubusercontent.com/29708612/58086206-dcd1f880-7bc6-11e9-9d18-cc126cdefd85.jpg)

CEA Dashboard
After 2.14 install
CEA Version 2.13.5a1
![CEA Version](https://user-images.githubusercontent.com/29708612/58086333-1b67b300-7bc7-11e9-9dd0-68d6bba084f1.jpg)

CEA Dashboard Warning
Do not use development server in a production environment
![CEA Warning](https://user-images.githubusercontent.com/29708612/58086416-46520700-7bc7-11e9-8790-0373420f8aea.jpg)

CEA Dashboard Run
After CEA 2.14 install
CEA Version 2.13.5a1
![CEA Radiation 1](https://user-images.githubusercontent.com/29708612/58086688-c8423000-7bc7-11e9-8fc3-43fa5de05bdb.jpg)

IOError No such file or directory
![CEA Radiation IOError no such file or directory](https://user-images.githubusercontent.com/29708612/58086837-10615280-7bc8-11e9-991f-18568ca61e54.jpg)

Pycharm location of conda environment
https://city-energy-analyst.readthedocs.io/en/latest/installation-on-windows.html
C:\Users\your_name\AppData\Local\conda\conda\envs\cea\python.exe
![Pycharm](https://user-images.githubusercontent.com/29708612/58087708-cb3e2000-7bc9-11e9-9df1-6c05044226d1.jpg)
![Pycharm2](https://user-images.githubusercontent.com/29708612/58087729-d5f8b500-7bc9-11e9-8e63-496586922399.jpg)
![Pycharm3](https://user-images.githubusercontent.com/29708612/58087754-e446d100-7bc9-11e9-8e08-e198bcd34182.jpg)
Looks like Python.exe is in a different folder

After CEA 2.14 Install
CEA 2.9 runs in ArcScene
![ArcGIS CEA2](https://user-images.githubusercontent.com/29708612/58089337-2faeae80-7bcd-11e9-8971-7e3ce662675c.jpg)
How to uninstall?

**Comment by daren-thomas** [comment]
@kerembeygo, there are a bunch of issues lumped into this one, so please be patient, I will try to address them all...

- did you install the "Base Installation" or the "Developer version"?
- it looks like you have previous installations on your computer?
- regarding version mismatch: I think that should be fixed now - maybe re-install or, if you have the developer version, pull from github. Read about the developer version here: https://daren-thomas.github.io/installing-cea-on-windows-part-2/
- regarding "CEA Dashboard Warning": this is expected. we are not running the CEA as a production web server, instead, on localhost. upgrading by adding a separate server would just add more to the installation without any benefits
- regarding "IOError No such file or directory" I can't really see what file it's looking for on your screenshot - but I think updating the CEA will help (try re-installing with the installer, but obtain a fresh copy of the installer from https://github.com/architecture-building-systems/CityEnergyAnalyst/releases (NOTE: we'll be adding a release 2.15 tomorrow)
- regarding "Pycharm location of conda environment" yes, my bad. see https://daren-thomas.github.io/installing-cea-on-windows-part-2/ for a better explaination of how to set up GitHub Desktop and PyCharm for the Developer version
- regarding "CEA 2.9 runs in ArcScene" you can fix this by running `cea install-arcgis` from the CEA Console.

I hope this helps you! Please don't hesitate to ask more questions or provide feedback on whether the above steps helped solve your issues.

**Comment by kerembeygo** [comment]
@daren-thomas 

- I installed "Developer version"

- Yes I have previous versions. I want to uninstall them. There were uninstall.exe files in different versions of CEA folders. I tried to run them. Only uninstall files are gone. See below for properties of CEA 2.15 (on the left) and CEA 2.9 (on the right)
![CEA](https://user-images.githubusercontent.com/29708612/58987014-46691e00-87e7-11e9-9fb1-9c5eecb442d0.jpg)
CEA 2.9 folder after running uninstall.exe
![CEA 2-9](https://user-images.githubusercontent.com/29708612/58987249-d0b18200-87e7-11e9-84fb-16df92d8c34e.jpg)
CEA 2.15 folder after running uninstall.exe
![CEA 2-15](https://user-images.githubusercontent.com/29708612/58987331-f474c800-87e7-11e9-8bba-6da49137ec7e.jpg)

- I did the install with Setup_CityEnergyAnalyst_2.15.exe but I still see 2.13.5a1
![Version](https://user-images.githubusercontent.com/29708612/58987493-3ef64480-87e8-11e9-976d-358c877ff2a9.jpg)

- "IOError No such file or directory" it comes when I want to run scenarios in reference-case-WTP folder
![Data Helper](https://user-images.githubusercontent.com/29708612/58989292-51727d00-87ec-11e9-97f2-4bdd8d0e566e.jpg)
![Data Helper 2](https://user-images.githubusercontent.com/29708612/58989301-56cfc780-87ec-11e9-8c24-fb09005ed249.jpg)

- "Pycharm location of conda environment" I think I did that

- "CEA 2.9 runs in ArcScene" you can fix this by running cea install-arcgis from the CEA Console.
![cea install-arcgis](https://user-images.githubusercontent.com/29708612/58989467-a3b39e00-87ec-11e9-939d-b93b3652e355.jpg)

- I want to uninstall all versions of CEA (if necessary github and pycharm too) and then do the install with the latest installer.

**Comment by daren-thomas** [comment]
@kerembeygo,

ok. you have a bunch of installations. this is going to be a little tricky, as the installation method has changed a bit since 2.9. here are some things i'd like you to try:

- delete the folder `C:\Users\KEREM\AppData\Local\CityEnergyAnalyst`
- delete the folder `C:\Users\KEREM\Documents\CityEnergyAnalyst`
- go to the folder `C:\Users\KEREM` and delete
  - `cea_arcpy.pth`
  - `cea_python.pth`
  - `cea.config`
- check GitHub Desktop for the CityEnergyAnalyst repository and remove it (including from disk when asked) or just delete the folder (probably in `C:\Users\KEREM\Documents\GitHub\CityEnergyAnalyst`)

that should delete any versions you have.

**Comment by daren-thomas** [comment]
@kerembeygo can we close this issue?
