### ISSUE TITLE
Steiner tree script should not connect buildings with no demand

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1995]
The Steiner tree script connects all buildings, regardless of whether they have a demand or not. Sure, the optimization scripts then decide whether buildings should be connected or not, and thus these buildings won't be connected.

But we could instead avoid connecting buildings with no heating/cooling systems at all as a prescreen. It's an easy fix and it can save a lot of calculation time when running single simulations of large case studies.

**Comment by daren-thomas** [comment]
this issue is being rebranded by @martin-mosteiro

**Comment by martin-mosteiro** [comment]
Turns out that @JIMENOFONSECA already solved this issue recently. However the variable names could be made more consistent, plus the script wouldn't work if buildings without demand were not connected but they were also included in the `disconnected_buildings` list.
