### ISSUE TITLE
Negative values in PV potential

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2002]
Some interesting results from Jakub: a PV array producing negative electricity!
<img width="651" alt="image" src="https://user-images.githubusercontent.com/18548065/58244787-a4abf080-7d53-11e9-93f9-2848a5beb880.png">
(That's a building in the Zurich case study and the date is 20 February).

A similar issue had previously been found (and solved) for solar collectors (#1409).

**Comment by shanshanhsieh** [comment]
this behavior cannot be reproduced by `reference-case-open` and `reference-case-cooling`
will be closing this issue for now
