### ISSUE TITLE
test_calc_thermal_loads should be executed for all buildings, not only `B01`

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2004]
Also, there is a "reference-case-cooling" now that should be included in the tests of the demand calculation.
And, I would like to add a SOP where testers explain why and how the test data is updated and write a few lines about why the updated values make sense.
Assigning @daren-thomas for now.

**Comment by gabriel-happle** [comment]
E.g. https://github.com/architecture-building-systems/CityEnergyAnalyst/pull/1994#issuecomment-495462581

**Comment by daren-thomas** [comment]
@gabriel-happle check out `cea.tests.test_calc_thermal_loads.TestCalcThermalLoads#test_calc_thermal_loads_other_buildings` - it runs it for the other buildings too! the testing is just not as strict (tests totals, not individual values).

yes, let's include the reference-case-cooling too!

**Comment by gabriel-happle** [comment]
@daren-thomas I know. I think we can compare the same values as for the individual building. We are only testing 3 quantities for those buildings.
