### ISSUE TITLE
Temperature Axis Title on Solar radiation curve plot covered by legend

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2006]
![screenshot_2019-05-24_city_energy_analyst_default_dashboard.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/29d41bf1-b6c9-4cfd-ac02-24f8c2435b17)

See the above screenshot from the dashboard.

**Comment by JIMENOFONSECA** [comment]
I did this..
