### ISSUE TITLE
Dashboard: Terrain helper tool does not show a success message when finished

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2007]
Terrain helper tool does not show a success message when finished.
I also saw this for the data helper tool, there the close button turned green after running.
In the terrain helper tool the close button was immediately green. This made me question if the tool was still running or maybe crashed.
Not sure if it is intended.

Assigning @reyery for now.

**Comment by daren-thomas** [comment]
I think, the `done / success` message should be done in by the script runners (`cea` command, Dashboard tools, `cea.api.*` etc.) as well as the writing out of parameters (currently, the parameters are printed out by `cea` and the `cea.api` module, but a lot of scripts also manually print them out (and often get them wrong, as it's not updated when the `scripts.yml` gets updated. So. This issue could also fix this...)

**Comment by daren-thomas** [comment]
fixed in PR #2084.
