### ISSUE TITLE
High ΔT in Building nodes for space cooling simulation

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#2016]
I have ran the 'thermal-network' simulation for 4 scenarios.
If analyzing the supply and return temperature in the consumer nodes, a high ΔT gets apparent for each of the nodes. 
This is the supply and return temperature of one node as well as there difference:
![Screenshot 2019-05-27 at 18 40 59](https://user-images.githubusercontent.com/26175926/58431646-03080480-80af-11e9-8465-1887746cf234.png)

The mean ΔΤ for this particular consumer node is 12.3 °C.

As a time series it looks like this: 
![Supply_Temp_ETH_HG_2](https://user-images.githubusercontent.com/26175926/58431673-2b8ffe80-80af-11e9-9314-9f053533c25e.png)
![Return_Temp_ETH_HG_2](https://user-images.githubusercontent.com/26175926/58431672-2b8ffe80-80af-11e9-91a9-779d84d982a5.png)

**Comment by martin-mosteiro** [comment]
@shanshanhsieh The scenarios in question including the district cooling networks that @emanuel030 was simulating are now all available in the `cea-reference-case` repository.

**Comment by martin-mosteiro** [comment]
The issue could not be replicated, so we will not work on it unless it occurs again
