### ISSUE TITLE
Update "PV/SC/PVT Potential per Building for District" plot to look better for the dashboard

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2020]
The "PV/SC/PVT Potential per Building for District" plot (`cea.plots.solar_technology_potentials.all_tech_yearly.AllTechYearlyPlot`) has some issues when plotted with the new system in the dashboard.

- the instructions covers the legend (decide on what to do about that. suggestion: remove instructions)
- when the plot is first opened, nothing is shown
- the table is very long (decide on what to do about that. no suggestion)

**Comment by daren-thomas** [comment]
@shanshanhsieh would you like to collaborate on this please?

**Comment by shanshanhsieh** [comment]
just checked the plots on the interface using version 2.26, it works fine!
