### ISSUE TITLE
Pumping energy calculation incorrect according to literature

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2021]
Just got feedback on the CEA thermal network simulation from . At the moment, we are calculating the pumping energy as follows:
```
pressure_loss_total_kw = sum(np.nan_to_num(pressure_loss_pipe_supply_kW)) + sum(np.nan_to_num(pressure_loss_pipe_return_kW)) + sum(np.nan_to_num(pressure_loss_substations_kW))
```
where
```
pressure_loss_pipe_supply_kW = pressure_loss_pipe_supply__pa * edge_mass_flow / P_WATER_KGPERM3 / 1000 / PUMP_ETA
pressure_loss_pipe_return_kW = pressure_loss_pipe_return__pa * edge_mass_flow / P_WATER_KGPERM3 / 1000 / PUMP_ETA
pressure_loss_nodes_kW = pressure_loss_nodes_pa * node_mass_flow / P_WATER_KGPERM3 / 1000 / PUMP_ETA
```

That is, `Pumping_power = [pressure_loss_pipe(e) * mass_flow_rate (e) + pressure_loss_node(n) * mass_flow_rate(n)] / water_density / pump_efficiency` for each edge _e_ and node _n_.

This is not correct, however. From  _District Heating and Cooling_ (Frederiksen and Werner, 2014), assuming on pump for the entire system (as we do):
```
Pumping_power = (pressure_loss_supply + pressure_loss_return + delta_p_min) / pump_efficiency * mass_flow_rate / water_density
```
where `pressure_loss_supply/return` is the total pressure drop in the supply pipe from the main circulation pump to the most peripheral substation / in the return pipe from the most peripheral substation to the main circulation pump and `delta_p_min` is the minimum pressure difference between the supply and the return pipes from the most peripheral substation.
That is, the pump brings the pressure of the entire volume of water in the network to the pressure needed to supply **the furthest consumer**.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh any comment?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh shall we close this?

**Comment by shanshanhsieh** [comment]
as Martin described, the current method is used in other studies as well, but it does not describe the realistic pumping operation. 
i've done some experiments on how it might work, now that i need it in the model of my next papaer, i will try to implement it in a lean way.
this will be my task for the next sprint

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh progress?

**Comment by daren-thomas** [comment]
@martin-mosteiro is testing this and will merge when done.
