### ISSUE TITLE
Create functionality to assign individual custom occupancy schedule (people) to building

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2024]
For my research I want to create a new functionality that allows the assignment of a custom occupancy schedule to individual buildings.

Since I like using jupyter notebooks, I would like to create some interface to the building models from there.

I imagine, after the building model (i.e. the `bpr`) is created I have to overwrite the occupancy schedule and recalculate the ones depending on it (internal gains, ventilation requirements, etc.), before the rest of the demand code is calculated.

Another option is to change the `read_schedules` function to look up the schedules from another location, e.g., a `csv` file that I create with my jupyter notebook.

I think the latter is easier and doesn't interfere too much with the current flow.

**Comment by gabriel-happle** [comment]
@daren-thomas, if you could quickly explain how `cea` code should be called ideally from `jupyter notebooks` I could turn that into one of the next blogs.

**Comment by daren-thomas** [comment]
oh yeah, i'm hoping to do a blog on that someday too. here's a pointer: check out the `cea.api` namespace in `IPython` - it let's you invoke all the cea scripts from python!

`cea.api.demand(weather='path/to/weather', ...)`

I think the schedules could use some work: at the moment, they're created by this crazy Excel sheet. What if we had a schedule editor in the Dashboard and a more "sane" way to specify schedules? What would that look like? Could we use a "Data management" script to create the schedules per building? That would create the default ones we have now, but _per_ building! And then the user could replace that with their own? So like your option two: `read_schedules` should be a _per_ building method?

**Comment by gabriel-happle** [comment]
@martin-mosteiro I'm entering your `occupancy_model` territory here.
I realized that schedules are created inside the `thermal_loads` script.
As a first step, I think we could move the schedules to the `bpr` object, which is actually something like our "building model".
Is there anything that would speak against that?

@daren-thomas in the future they could be part of the `building_properties`. But I don't think dbf is a good format for them. I guess json or maybe csv is better.
Potentially we could interact with individual building models via the interface.
The `data-helper` will become something like `create-building-models`, followed by an editing/modification step, before running simulations.

**Comment by daren-thomas** [comment]
@gabriel-happle I like that workflow.
@JIMENOFONSECA do we need to stick with dbf? wasn't that just for ArcGIS?

**Comment by gabriel-happle** [comment]
@daren-thomas because this work is still experimental, I would like to have my schedule generator outside of CEA first to test.
Therefore, I would like to input the full yearly schedules of buildings directly. I.e., some vectors of 8760 values.

Currently, there are maximum 12 schedules per building:
`people` - number of people present
`ve` - required fresh air (depends on `people`)
`Qs` - heat gain from `people`
`X` - humidity gain from `people`
`Vww` - hot water demand
`Vw` - fresh water demand
`Ea` - electrical power use of electrical appliances
`El` - electrical power use of lights
`Ed` - electrical power use of data centres
`Epro` - electrical power use of (industrial) processes
`Qhpro` - process heat demand
`Qcre` - refrigeration cooling demand

So the input will contain min. 8760 values, max. 12 x 8760 values.
plus maybe some datetime index. and some meta data.

I like `json` because it translates nicely to python `dict`

**Comment by gabriel-happle** [comment]
@daren-thomas if you have some time, would you please take a look at my branch https://github.com/architecture-building-systems/CityEnergyAnalyst/tree/i2024-read-custom-occupancy-schedule

Basically, I split the demand script into two:
- `make-building-models` creates the `bpr` including the yearly schedules and saves as `pickle`
- `demand` reads the pickle and calculates the demand as usual

I chose `pickle` over `json` for now, because otherwise I would have to translate everything in the `bpr` to `dict` and `list`. I.e., less work.

My plan is to interact with the `pickle` buildings via `jupyter`. I.e.: 
(1) run the `make-building-models` script,
(2) load the pickle building model in jupyter, 
(3) modify values and save again to pickle,
(4) run `demand`

**Comment by martin-mosteiro** [comment]
I've played around with this in my own branch for the whole MATSim population import analysis I'm doing. This might be something worth adding later on (see #2061). I'll assign myself in this issue just to know what format this schedule import will take for future reference.

**Comment by gabriel-happle** [comment]
@martin-mosteiro welcome to my branch. feel free to try it out and give comments for changes.
I can send you some of my jupyter notebooks to try the functionality

**Comment by martin-mosteiro** [comment]
Thanks! The jupyter notebooks would be cool to check out, sure

**Comment by daren-thomas** [comment]
Can we have a PR for this please?

**Comment by gabriel-happle** [comment]
@daren-thomas can we have a meeting about this? Maybe today or next week?

**Comment by gabriel-happle** [comment]
based on discussions with @daren-thomas on the issue. we will abandon my current approach and instead do #2182, #2183, #2184, #2185
