### ISSUE TITLE
Dashboard: Thermo-hydraulic network (branched) requires click on `Save configuration` to apply changes to settings

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2026]
different from other tool interfaces, this one does not accept changes to parameters directly when clicking on `Run ...`. One has to first click on `Save configuration` to apply changes.

**Comment by daren-thomas** [comment]
I'm surprised. The parameters are passed to the script on `[Run]`. I'm guessing the script re-reads the configuration file, possibly in the `main` function. I checked quickly and couldn't find anything. Does this apply to all the parameters? Or maybe just the one that was duplicated? (see issue #2025)

**Comment by gabriel-happle** [comment]
In my case, it applied to all parameters.

**Comment by daren-thomas** [comment]
Alternate steps to reproduce this:

- run dashboard
- open project (cooling-case-workflow/baseline)
- tools -> Life Cycle Analysis -> emissions
- set `year-to-calculate` to 2019
- run emissions

expected it to run for 2019, instead, I got the following output:

```
City Energy Analyst version 2.16
Running `cea emissions` with the following parameters:
- general:scenario = C:\reference-case-cooling\2008-demand-buildings
  (default: C:\reference-case-open\baseline)
- emissions:year-to-calculate = 2020
  (default: 2020)
Running emissions with scenario = C:\reference-case-cooling\2008-demand-buildings
done!
```

Note the `emissions:year-to-calculate` setting is 2020!

I'm assuming this is the same bug, but this way avoids a lengthy simulation time for testing.
