### ISSUE TITLE
INDUSTRIAL, LAB, HOSPITAL archetypes in SG do not have process heat demand (internal loads)

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2030]
INDUSTRIAL, LAB, HOSPITAL archetypes in SG do not have process heat demand (internal loads)
- should they?

**Comment by martin-mosteiro** [comment]
Process heat in the Universitätsspital is used for sterilization, laundry, etc. I suppose that's a common requirement in other hospitals?
Labs and Industry depend on the type of lab and industry considered... 
My take: it's okay for all of them to be 0 by default and it's just a parameter needs to provide for their specific application.

**Comment by daren-thomas** [comment]
@martin-mosteiro, @gabriel-happle does anything need to be done about this? or can we close this issue?

**Comment by daren-thomas** [comment]
update the 0 solution for CH archetypes please.

**Comment by daren-thomas** [comment]
CH Archetypes specify process heat, SG Archetypes don't. User should override as necessary.
