### ISSUE TITLE
reference-case-cooling has only 3 uses

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2031]
- more uses like in reference case open should be tested

**Comment by daren-thomas** [comment]
@gabriel-happle could you please update the reference case? can i assign this to you?

**Comment by daren-thomas** [comment]
@gabriel-happle does it matter which buildings are assigned which uses? there are 16 uses configured and 10 buildings - the easiest would be to assign two uses to each building, round-robin fashion. That way all uses are tested. Would that work?

**Comment by gabriel-happle** [comment]
sure. why not.
