### ISSUE TITLE
Archetypes Database is not really flexible accross multiple scenarios

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2036]
@shizhongming approached me with a question:
- how to modify archetypical construction across multiple (>100) scenarios?

Turns out, that is actually not easily possible. It seems either one has to modify the cea databases (and potentially run into trouble when updating from master/installing a new version) or one has to manually copy-paste/modify the database 100 times.

I think one possible enhancement could be to set up a custom path (i.e., in the data-helper config, maybe even replacing the `region` parameter) to a separate location of local databases.
I.e., when running the data-helper, the user could choose whether the default cea databases should be used or whether the databases should be taken from another location.

What do you think @daren-thomas and @JIMENOFONSECA ?

**Comment by gabriel-happle** [comment]
Maybe in this way, we could create a repository of database structures from different users to be shared and exchanged.
I.e., the workflow would be to copy one of the existing databases and play around with the valid parameters while keeping the same structure, just in another folder anywhere on the computer.

**Comment by daren-thomas** [comment]
I kind of like this idea. I think it could work similar to the weather files, which are either the name of a built-in weather file _or_ the path to a weather file. The region parameter (how cool is it that it's only used in the data-helper now!?) could be just that. Either a built-in region name _or_ the path to a region database folder structure.

**Comment by daren-thomas** [comment]
let's copy archetypes as part of scenario creation and de-couple it from data-helper. let's revisit the workflow here.

**Comment by daren-thomas** [comment]
Let's make the RegionParameter also accept a folder that will be used instead.
