### ISSUE TITLE
CEA 2.14 Energy Potentials

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2037]
For PV2, PV3 selection CEA runs for PV1. 
For FP selection runs for ET
![Photovoltaic Thermal PV2](https://user-images.githubusercontent.com/29708612/58728270-33250f80-83ef-11e9-9362-dd835d7f56e4.jpg)
![Photovoltaic Thermal PV1](https://user-images.githubusercontent.com/29708612/58728281-3c15e100-83ef-11e9-9754-3bd5dc3d510c.jpg)

**Comment by daren-thomas** [comment]
Could this be related to #2026? @reyery would you like to look into this, since you're doing all the Dashboard stuff? Otherwise I can give it a spin...

**Comment by reyery** [comment]
@daren-thomas it seems to be related. I think line 23 causes parameters with dashes to not enter the `if` condition so it will not be set. Removing `.replace('-', '_')` seems to work.

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/45a43dc098c49b24dd94991127187ae621ba8667/cea/api.py#L22-L25

**Comment by daren-thomas** [comment]
This is fixed in PR #2087
