### ISSUE TITLE
Config file has similarly-named options that are confusing

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2038]
The `plots` section of the config file contains the following two options:
```
buildings =
buildings.type = BuildingsParameter
buildings.help = a list of buildings to run graphs or leave blank to simulate district

building =
building.type = SingleBuildingParameter
building.help = The building ID for the Energy Demand, Comfort Plot and Heating Reset-schedule plot. Used only for the
                dashboard plots. For the plots tool, use a single building in the "buildings" variable.
```

Isn't it kind of confusing to have a `buildings` and a `building` option? When exactly should each be used is also not clear. What if I want to run a single plot that is not Energy Demand, Comfort or Heating Reset-schedule?

**Comment by daren-thomas** [comment]
So the problem I was trying to solve here is, some plots only work on a single building. Other plots can work on a district. The was the `cea plots` tool works, is it runs a bunch of plots. It's a bit messy on the details of running SingleBuildingPlots - basically, the plot categories do a big `if` statement on the length of the `buildings` parameter.

The dashboard interface stores plot settings for each plot in the dashboard. That way, you can show the same plot with _different_ settings. Each plot class specifies _which_ parameters it uses and the interface can use that to display the settings dialog. Showing a list of buildings for a plot that only takes one building is just wrong. I suggest we revisit this when the Big Plot Migration has been completed. (and I guess we'll probably remove the `cea plots` command - I wasn't planning to, but it seems like a better option now)

**Comment by martin-mosteiro** [comment]
In that case the question has been clarified and whether to do something about it or not is part of issue #1990. I believe this question-issue can be closed now.
