### ISSUE TITLE
not being able to create new scenarios

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2039]
Hi all,
I am getting:
"Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application." whenever I try to create a new scenario. 
Before it was working fine.
It happens after I put the specifications and click on "Create"

**Comment by daren-thomas** [comment]
@lguilhermers, can you show the output of the dashboard console? You can find it in your taskbar, it's the minimized window with the CEA logo. If you open that, you should see a console with the error message - could you please copy/paste the whole stacktrace here? or do a screenshot?

**Comment by lguilhermers** [comment]
Sure, @daren-thomas 


C:\Users\luis.santos\Documents\CityEnergyAnalyst>SET PATH=C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python;C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts;C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Daysim;C:\Program Files\Microsoft MPI\Bin\;.;C:\DAYSIM\lib\;C:\DAYSIM\bin\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Symantec.cloud\PlatformAgent\;C:\Program Files\MATLAB\R2017b\runtime\win64;C:\Program Files\MATLAB\R2017b\bin;C:\Users\luis.santos\Documents\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;.;C:\DAYSIM\lib\;C:\DAYSIM\bin\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Symantec.cloud\PlatformAgent\;C:\Program Files\MATLAB\R2017b\runtime\win64;C:\Program Files\MATLAB\R2017b\bin;C:\Users\luis.santos\Documents\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;.;C:\DAYSIM\lib\;C:\DAYSIM\bin\;C:\Users\luis.santos\AppData\Local\GitHubDesktop\bin;C:\Users\luis.santos\AppData\Local\Microsoft\WindowsApps;C:\Users\luis.santos\Documents\;C:\Users\luis.santos\AppData\Local\Microsoft\WindowsApps;C:\Users\luis.santos\AppData\Lo

C:\Users\luis.santos\Documents\CityEnergyAnalyst>SET PYTHONHOME=C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python

C:\Users\luis.santos\Documents\CityEnergyAnalyst>SET RAYPATH=C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Daysim

C:\Users\luis.santos\Documents\CityEnergyAnalyst>C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\python.exe -m cea.interfaces.cli.cli dashboard
City Energy Analyst version 2.14
Running `cea dashboard` with the following parameters:
- general:debug = False
  (default: False)
C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\deap\tools\_hypervolume\pyhv.py:33: ImportWarning:

Falling back to the python version of hypervolume module. Expect this to be very slow.

 * Serving Flask app "cea.interfaces.dashboard.dashboard" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://localhost:5050/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:31] "GET / HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:31] "GET /landing/welcome HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:32] "GET /static/vendors/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:32] "GET /static/vendors/bootstrap-daterangepicker/daterangepicker.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:32] "GET /static/vendors/font-awesome/css/font-awesome.min.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:32] "GET /static/vendors/nprogress/nprogress.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:32] "GET /static/vendors/iCheck/skins/flat/green.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:32] "GET /static/vendors/jqvmap/dist/jqvmap.min.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:32] "GET /static/vendors/switchery/dist/switchery.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:32] "GET /landing/static/landing.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:32] "GET /static/build/css/custom.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:32] "GET /static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:32] "GET /static/vendors/jquery/dist/jquery.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:32] "GET /static/vendors/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/images/cea-logo.png HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/fastclick/lib/fastclick.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/nprogress/nprogress.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/iCheck/icheck.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/moment/min/moment.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/bootstrap-daterangepicker/daterangepicker.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/jquery.hotkeys/jquery.hotkeys.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/google-code-prettify/src/prettify.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/jquery.tagsinput/src/jquery.tagsinput.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/switchery/dist/switchery.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/select2/dist/js/select2.full.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/autosize/dist/autosize.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:33] "GET /static/vendors/starrr/dist/starrr.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:34] "GET /landing/welcome HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:35] "GET /landing/open-project HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:35] "GET /tools/static/tools.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:35] "GET /static/vendors/parsleyjs/dist/parsley.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:35] "GET /tools/static/tools.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:35] "GET /landing/open-project HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:36] "POST /landing/open-project/save HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:37] "GET /landing/project-overview HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:37] "GET /static/vendors/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:37] "GET /static/build/js/custom.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:37] "GET /static/images/img.jpg HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:37] "GET /landing/project-overview HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:39] "GET /landing/create-scenario HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:39] "GET /landing/static/landing_map.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:35:40] "GET /landing/create-scenario HTTP/1.1" 200 -

[u'zone-helper']
zone-helper
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
DEBUG:Fiona:GDAL_DATA: C:\Program Files\PostgreSQL\9.5\gdal-data
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:GDAL_DATA: C:\Program Files\PostgreSQL\9.5\gdal-data
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:Deleted pre-existing layer at site
DEBUG:Fiona:Created layer site
DEBUG:Fiona:Created fields
DEBUG:Fiona:Writing started
DEBUG:Fiona:Creating feature in layer: {'geometry': {'type': 'Polygon', 'coordinates': (((103.792101, 1.310482), (103.794075, 1.315009), (103.798388, 1.313314), (103.798882, 1.307994), (103.792101, 1.310482)),)}, 'type': 'Feature', 'id': '0', 'properties': {}}
DEBUG:Fiona:Adding ring ((103.792101, 1.310482), (103.794075, 1.315009), (103.798388, 1.313314), (103.798882, 1.307994), (103.792101, 1.310482))
DEBUG:Fiona:Adding point (103.792101, 1.310482)
DEBUG:Fiona:Adding point (103.794075, 1.315009)
DEBUG:Fiona:Adding point (103.798388, 1.313314)
DEBUG:Fiona:Adding point (103.798882, 1.307994)
DEBUG:Fiona:Adding point (103.792101, 1.310482)
DEBUG:Fiona:Closing ring
DEBUG:Fiona:Built ring
DEBUG:Fiona:Added ring ((103.792101, 1.310482), (103.794075, 1.315009), (103.798388, 1.313314), (103.798882, 1.307994), (103.792101, 1.310482))
DEBUG:Fiona:Flushed data source cache
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
site.shp file created at C:\CEA\test\baseline\inputs\building-geometry\site.shp
City Energy Analyst version 2.14
Running `cea zone-helper` with the following parameters:
- general:scenario = C:\CEA\test\baseline
  (default: C:\reference-case-open\baseline)
- zone-helper:height-ag = 6.0
  (default: None)
- zone-helper:floors-ag = 2
  (default: None)
- zone-helper:year-construction = None
  (default: None)
- zone-helper:height-bg = 0.0
  (default: 3.0)
- zone-helper:floors-bg = 0
  (default: 1)
- zone-helper:occupancy-type = INDUSTRIAL
  (default: Get it from open street maps)
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
DEBUG:Fiona:GDAL_DATA: C:\Program Files\PostgreSQL\9.5\gdal-data
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:GDAL_DATA: C:\Program Files\PostgreSQL\9.5\gdal-data
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Index: 0
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): overpass-api.de:80
DEBUG:urllib3.connectionpool:http://overpass-api.de:80 "GET /api/status HTTP/1.1" 200 151
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): overpass-api.de:80
DEBUG:urllib3.connectionpool:http://overpass-api.de:80 "POST /api/interpreter HTTP/1.1" 200 16965
ERROR:flask.app:Exception on /landing/create-scenario/save [POST]
Traceback (most recent call last):
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\landing\routes.py", line 123, in route_create_scenario_save
    cea.api.zone_helper(cea_config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 28, in script_runner
    script_module.main(config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 248, in main
    zone_helper(locator, config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 126, in zone_helper
    poly, zone_output_path)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 233, in polygon_to_zone
    buildings_floors_below_ground, key="B")
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 97, in clean_attributes
    "REFERENCE"]]
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geodataframe.py", line 455, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2682, in __getitem__
    return self._getitem_array(key)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2726, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1327, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: "['REFERENCE'] not in index"
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:36:22] "POST /landing/create-scenario/save HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2019 09:36:23] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by daren-thomas** [comment]
I've just tried it with the most recent version of the CEA installer (preview: https://www.dropbox.com/s/nnpytege07xo92q/Setup_CityEnergyAnalyst_2.15a0.exe?dl=0) and it seems to work. Would you please re-install CEA and see if it works now? Else, I would need more information of your inputs to re-create the error message: Exact location you're using, what you clicked etc. Maybe a zip of the scenario as created so-far.

**Comment by lguilhermers** [comment]
Dear Daren,
Sorry for the delay. I am using the developer version and pulling the updates from Github, so it should be updated. There is one update from you in the history saying it is version 2.15, so this should be fine.
I will list below the steps I am taking to see if you can help:
1- open CEA (dshboard is indicating is version 2.15)
2 - Create new project (named it "test", output path to a folder in C:\) -> Create
3 - click create new scenario (scenario name "testscenario")
4 - Input data left as default (generate new input files, only zone selected in data management tools
5 - selecting a location in downtown Singapore (you can type "Lau Pa Sat" to find it easier. Starting from up left corner I clicked in the points indicated clockwise.
6 - Click create - error message appears. (Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.)

![image](https://user-images.githubusercontent.com/50981039/59170617-1072c380-8b72-11e9-8606-e2bbffd43e02.png)

**Comment by lguilhermers** [comment]
error log:


C:\Users\luis.santos\Documents\CityEnergyAnalyst>SET PATH=C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python;C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts;C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Daysim;C:\Program Files\Microsoft MPI\Bin\;.;C:\DAYSIM\lib\;C:\DAYSIM\bin\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Symantec.cloud\PlatformAgent\;C:\Program Files\MATLAB\R2017b\runtime\win64;C:\Program Files\MATLAB\R2017b\bin;C:\Users\luis.santos\Documents\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;.;C:\DAYSIM\lib\;C:\DAYSIM\bin\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Symantec.cloud\PlatformAgent\;C:\Program Files\MATLAB\R2017b\runtime\win64;C:\Program Files\MATLAB\R2017b\bin;C:\Users\luis.santos\Documents\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;.;C:\DAYSIM\lib\;C:\DAYSIM\bin\;C:\Users\luis.santos\AppData\Local\GitHubDesktop\bin;C:\Users\luis.santos\AppData\Local\Microsoft\WindowsApps;C:\Users\luis.santos\Documents\;C:\Users\luis.santos\AppData\Local\Microsoft\WindowsApps;C:\Users\luis.santos\AppData\Lo

C:\Users\luis.santos\Documents\CityEnergyAnalyst>SET PYTHONHOME=C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python

C:\Users\luis.santos\Documents\CityEnergyAnalyst>SET RAYPATH=C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Daysim

C:\Users\luis.santos\Documents\CityEnergyAnalyst>C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\python.exe -m cea.interfaces.cli.cli dashboard
City Energy Analyst version 2.15
Running `cea dashboard` with the following parameters:
- general:debug = False
  (default: False)
C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\deap\tools\_hypervolume\pyhv.py:33: ImportWarning:

Falling back to the python version of hypervolume module. Expect this to be very slow.

 * Serving Flask app "cea.interfaces.dashboard.dashboard" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://localhost:5050/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:16:25] "GET / HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:16:25] "GET /landing/welcome HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:16:25] "GET /landing/welcome HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:17:15] "GET /landing/open-project HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:17:15] "GET /landing/open-project HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:17:20] "GET /landing/welcome HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:17:21] "GET /landing/create-project HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:17:22] "GET /landing/create-project HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:18:17] "POST /landing/create-project/save HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:18:17] "GET /landing/project-overview HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:18:17] "GET /landing/project-overview HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:18:19] "GET /landing/create-project HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:18:22] "POST /landing/create-project/save HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:18:22] "GET /landing/project-overview HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:18:23] "GET /landing/project-overview HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:18:24] "GET /landing/create-project HTTP/1.1" 200 -

INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:18:28] "POST /landing/create-project/save HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:18:29] "GET /landing/project-overview HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:18:29] "GET /landing/project-overview HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:18:40] "GET /landing/create-scenario HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:18:41] "GET /landing/create-scenario HTTP/1.1" 200 -
[u'zone-helper']
zone-helper
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
DEBUG:Fiona:GDAL_DATA: C:\Program Files\PostgreSQL\9.5\gdal-data
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:GDAL_DATA: C:\Program Files\PostgreSQL\9.5\gdal-data
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:Created layer site
DEBUG:Fiona:Created fields
DEBUG:Fiona:Writing started
DEBUG:Fiona:Creating feature in layer: {'geometry': {'type': 'Polygon', 'coordinates': (((103.849044, 1.280865), (103.850643, 1.280071), (103.849613, 1.278334), (103.8481, 1.279224), (103.849044, 1.280865)),)}, 'type': 'Feature', 'id': '0', 'properties': {}}
DEBUG:Fiona:Adding ring ((103.849044, 1.280865), (103.850643, 1.280071), (103.849613, 1.278334), (103.8481, 1.279224), (103.849044, 1.280865))
DEBUG:Fiona:Adding point (103.849044, 1.280865)
DEBUG:Fiona:Adding point (103.850643, 1.280071)
DEBUG:Fiona:Adding point (103.849613, 1.278334)
DEBUG:Fiona:Adding point (103.8481, 1.279224)
DEBUG:Fiona:Adding point (103.849044, 1.280865)
DEBUG:Fiona:Closing ring
DEBUG:Fiona:Built ring
DEBUG:Fiona:Added ring ((103.849044, 1.280865), (103.850643, 1.280071), (103.849613, 1.278334), (103.8481, 1.279224), (103.849044, 1.280865))
DEBUG:Fiona:Flushed data source cache
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
site.shp file created at C:\CEA\test\testscenario\inputs\building-geometry\site.shp
City Energy Analyst version 2.15
Running `cea zone-helper` with the following parameters:
- general:scenario = C:\CEA\test\testscenario
  (default: C:\reference-case-open\baseline)
- zone-helper:height-ag = 6.0
  (default: None)
- zone-helper:floors-ag = 2
  (default: None)
- zone-helper:year-construction = None
  (default: None)
- zone-helper:height-bg = 0.0
  (default: 3.0)
- zone-helper:floors-bg = 0
  (default: 1)
- zone-helper:occupancy-type = INDUSTRIAL
  (default: Get it from open street maps)
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
DEBUG:Fiona:GDAL_DATA: C:\Program Files\PostgreSQL\9.5\gdal-data
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:GDAL_DATA: C:\Program Files\PostgreSQL\9.5\gdal-data
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Index: 0
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): overpass-api.de:80
DEBUG:urllib3.connectionpool:http://overpass-api.de:80 "GET /api/status HTTP/1.1" 200 151
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): overpass-api.de:80
DEBUG:urllib3.connectionpool:http://overpass-api.de:80 "POST /api/interpreter HTTP/1.1" 200 2664
ERROR:flask.app:Exception on /landing/create-scenario/save [POST]
Traceback (most recent call last):
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\landing\routes.py", line 123, in route_create_scenario_save
    cea.api.zone_helper(cea_config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 28, in script_runner
    script_module.main(config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 248, in main
    zone_helper(locator, config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 126, in zone_helper
    poly, zone_output_path)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 233, in polygon_to_zone
    buildings_floors_below_ground, key="B")
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 97, in clean_attributes
    "REFERENCE"]]
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geodataframe.py", line 455, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2682, in __getitem__
    return self._getitem_array(key)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2726, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1327, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: "['REFERENCE'] not in index"
INFO:werkzeug:127.0.0.1 - - [10/Jun/2019 11:22:33] "POST /landing/create-scenario/save HTTP/1.1" 500 -

**Comment by lguilhermers** [comment]
Zip file with what was created: https://we.tl/t-KnvzU5ZKnB

**Comment by lguilhermers** [comment]
Hi Darren,
I changed the settings when creating the zone, restoring it to defaults and now I am able to create the scenarios again. Not sure what specifically was set to cause the error.

Would be good if whenever creating a new project from scratch those settings were always set back to the default to avoid loading previous configurations.
