### ISSUE TITLE
Thermal network simulation uses wrong section of the config file

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2041]
From line 439 in thermal_network.py:
```
    if config.thermal_network_optimization.use_representative_week_per_month:
        # we run the predefined schedule of the first week of each month for the year
        start_t = 0
        stop_t = 2016  # 24 hours x 7 days x 12 months
        prepare_inputs_of_representative_weeks(thermal_network)
    else:
        # for debugging purposes, the first and (one-past) last t for hourly calculations can be set in the config file
        start_t = config.thermal_network.start_t
        stop_t = config.thermal_network.stop_t
```
So whether the representative week method is used or not is defined not by the `thermal-network` section of the config file, but by the `thermal-network-optimization` section (i.e., when running thermal network simulation the optimization configuration overrides the simulation configuration).

**Comment by martin-mosteiro** [comment]
@shanshanhsieh I have changed all instances of `config.thermal_network_optimization.use_representative_week_per_month` to ` config.thermal_network.use_representative_week_per_month` as discussed. You can check this on branch `2041-thermal-network-config`.

As discussed, please double check whether this affects the optimization workflow. If it does, I suggest unifying the sections `[thermal-network]` and `[thermal-network-optimization]` in the config file so that there is only one variable called `use_representative_week_per_month` that both workflows use.

**Comment by shanshanhsieh** [comment]
@martin-mosteiro , i've made the changes necessary for the thermal network optimization to accommodate the changes you made. feel free to create a PR!
