### ISSUE TITLE
Grasshopper InputLocator error

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2044]
Currently running Grasshopper is showing this error message.

```
Runtime error (Win32Exception): WindowsError
Traceback:
  line 465, in get_weather_names, "C:\Users\Admin\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\cea\inputlocator.py"
  line 417, in decode, "C:\Users\Admin\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\cea\config.py"
  line 328, in get, "C:\Users\Admin\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\cea\config.py"
  line 46, in run, "C:\Users\Admin\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\cea\interfaces\grasshopper\ghhelper.py"
  line 14, in script
```

Grasshopper is trying to find the `weather` databases but is unable to find them. As seen in the code below, `inputlocator` makes use of `__file__` to find the directory of the database folder, which in this case is `C:\Users\Admin\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\cea\`

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/efb893e3031092f211ae2036a6d42ba4e1ffc703/cea/inputlocator.py#L27-L30

However, the path for the `weather` folder
i.e. `C:\Users\Admin\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\cea\databases\weather`
does not exists as `cea install-grasshopper` does not copy over the databases. Manually copying the database folder to the directory solves the issue, however this is just a temp solution.

I noticed that there is a `databases.pth` file in the directory which is suppsed to point to the databases folder, however I am not familiar with it and do not know why it is working.

**Comment by reyery** [comment]
@daren-thomas I'm not familiar with how `.pth` files are supposed to work, but I am guessing it is supposed to point to the databases path. But this is case it is not working.

**Comment by daren-thomas** [comment]
@reyery could you please add some information of _what_ you're running in grasshopper? maybe the inputs used? thank you.

(i'm guessing it should probably be more something like `os.path.dirname(cea.databases.__file__)` but i'd need to check.

the `.pth` file adds folders to the PYTHONPATH. what is the contents of `databases.pth`?

**Comment by reyery** [comment]
@daren-thomas running anything that would require accessing the databases i.e. `demand` with `scenario` path as input and everything else as default.

The `databases.pth` file provides the correct path to databases 
i.e. `C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\databases`
