### ISSUE TITLE
The CEA Blog is password protected

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2045]
I just published my two blog parts and tried to check the post. I get the following:

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/b3ee55cf-c4ad-4a20-b7f6-8bd3c3403250)

this happens with my posts, but _also_ with jimenos. is there a setting somewhere?

**Comment by shizhongming** [comment]
I just checked the square space settings...it seems the blogs are all locked...I just removed the password settings...It is working now @daren-thomas
