### ISSUE TITLE
Swiss occupancy schedules are really outdated

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2051]
The Swiss occupancy schedules in CEA are based on SIA 2024 (2006). There has been a new version of this standard for four years now (2015)!

The schedules (and particularly the monthly schedules) have changed dramatically, but other boundary conditions (occupant density, water demand, electricity demand) have changed significantly as well.

Check out, for example, the monthly schedules for offices in each case:
1. **SIA 2024 (2006) Grossraumbüro**
![Screen Shot 2019-06-04 at 16 00 12](https://user-images.githubusercontent.com/18548065/58885163-feac9e80-86e1-11e9-873c-971949c01c2d.png)
2. **SIA 2024 (2015) Grossraumbüro**
![Screen Shot 2019-06-04 at 16 00 23](https://user-images.githubusercontent.com/18548065/58885232-1c7a0380-86e2-11e9-8111-909dc535556f.png)
Some of it makes sense (sure, there's less occupants in July and August due to holidays) but some seems completely arbitrary (why is there a spike in occupants in June if most people are out in May, July and August?). As a result of this last point, for example, peak cooling in Switzerland does not happen in August (the hottest month) but in June (because there are 2/3 more occupants compared to August).

The freshwater demands are also way different: while the ratio of fresh water to cold water in the 2006 version is 2:1, in 2015 it is 20:1! Other uses also had changes in the electricity demands for lighting and appliances, though that was not the case for offices.

Finally, I am not sure where the occupant density for SCHOOL in CEA comes from, but it's currently 10 m2/p. According to SIA 2024 (both editions), it should be 2–5 m2/p for school buildings (depending on the specific room function). This matches the density found in buildings that only have classrooms in the Hochschulquartier, but when applied to the entire area the total number of occupants increases dramatically:
1. **Number of occupants using CEA densities**
![Screen Shot 2019-06-04 at 16 18 18](https://user-images.githubusercontent.com/18548065/58886617-82678a80-86e4-11e9-875b-282faf9a2c41.png)
(The purple line is the CEA schedule for the area, the orange line adjusts the number of people to the actual number of employees and students in the area)
2. **Number of occupants after updating occupant density to SIA 2024 (2015) values**
![Screen Shot 2019-06-04 at 16 18 08](https://user-images.githubusercontent.com/18548065/58886741-a62ad080-86e4-11e9-8db2-037c5c0efc33.png)

Comparing to the Singapore archetypes, the density for SCHOOLS there (4m2/p) appears to be quite similar to the Swiss norm (3 m2/p), but the density for the UNIVERSITY archetype is nearly four times as much (19 m2/p).

**Comment by daren-thomas** [comment]
@martin-mosteiro will decide on course of action for next sprint.

**Comment by martin-mosteiro** [comment]
@prakharmehta95 has been working on this for his paper and will create a PR once he is done updating the schedules.

@prakharmehta95 could you maybe give an update on the status of the schedule update?

**Comment by prakharmehta95** [comment]
@martin-mosteiro  I am done updating the schedules, will do a PR soon - for future reference, I want to add in the sources/some decisions we took while discussing what to do.

**Comment by martin-mosteiro** [comment]
@prakharmehta95 Thanks, that'd be perfect. Please do list all sources for future reference.

**Comment by prakharmehta95** [comment]
@martin-mosteiro I have a question - should I leave comments in the excel database files for those values which are a bit unclear/left the same as old SIA 2006 standards, or should I have a separate text file?

Also had some color codes in the files to highlight values where no clear sources were found/values were attained through calculations (e.g. the Hospital energy densities) - keeping the color codes shouldn't be a problem, right? I'll have a legend for it :)
