### ISSUE TITLE
Process schedules for LAB and HOSPITAL are questionable

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2053]
As mentioned in #1932 and #2034, I don't think the process schedules for LAB and HOSPITAL as defined in CEA make sense. Since there are no devoted schedules for these uses in the SIA standard, these were created as a copy of the process schedules for INDUSTRY, however this archetype was created based on data from a heavy manufacturing company in Switzerland. The schedules for processes follow a very specific pattern that likely makes sense in such a context (e.g. the ramp down during Saturdays), but I don't think it is especially representative for labs and hospitals (especially since these are occupied 7 days a week).

I would suggest making these schedules mirror the corresponding function's electricity demand patterns instead (both in CH and SG). This will nonetheless be a simplifying assumption, but one that is based on the specific function being modeled and not some large-scale manufacturer in Switzerland.

The alternative, of course, is researching appropriate process energy schedules for the corresponding functions.

**Comment by martin-mosteiro** [comment]
I'm co-assigning @gabriel-happle since this came up in an issue he created.

**Comment by martin-mosteiro** [comment]
Probably worth getting your opinion on what to do with the SG process schedules, though @gabriel-happle

**Comment by gabriel-happle** [comment]
@martin-mosteiro I would have to do some research. no idea about it right now.
