### ISSUE TITLE
some buildings are not created

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2056]
I noticed that when selecting the zone area some buildings are not created (example below). Is this caused by the open street maps configurations or there might be another reason for that?

![image](https://user-images.githubusercontent.com/50981039/59245575-03c29e00-8c4c-11e9-8a3f-7eeefb3f8d97.png)

**Comment by reyery** [comment]
@lguilhermers may I know which buildings you are referring to? Could be a problem on open street map side, since the data is pulled straight from there.

**Comment by lguilhermers** [comment]
in this case that I indicated, would be the Capitaspring (U/C) building, which was in the middle of my chosen area and was still not generated. I have seen others before, but didn't keep track of them.

**Comment by reyery** [comment]
Oh. The Capitalspring is stated as under construction so it is not considered a building in open street maps. As for others, most probably it was not included in open street maps. Since data from open street maps is crowd sourced, its not exactly accurate.

**Comment by lguilhermers** [comment]
Ok, thanks for the clarification!
