### ISSUE TITLE
CEA has Pandas compatibility issues on Euler

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2057]
Euler uses Pandas version 0.20.3, whereas CEA uses 0.23.4. This can cause compatibility issues when running CEA on Euler. Specifically:
1. _Locally,_ `pd.read_excel(file_path, sheet_name='sheet_name')` produces a dataframe from 'sheet_name'
2. _Locally,_ `pd.read_excel(file_path, sheet_name=['sheet_name'])` produces the following dict: `{'sheet_name': pd.read_excel(file_path, sheet_name='sheet_name')}`
3. _On Euler,_ `pd.read_excel(file_path, sheet_name=['sheet_name'])` produces a dataframe from 'sheet_name'

This causes an issue when running **thermal_networks.py** on Euler – see line 3099 in thermal_network.py:
```
material_properties = pd.read_excel(locator.get_thermal_networks(), sheet_name=['MATERIAL PROPERTIES'])[
    'MATERIAL PROPERTIES']
```
Hence, running on Euler produces `KeyError: 'MATERIAL PROPERTIES'` (as there is no column 'MATERIAL PROPERTIES' in the DataFrame created. This issue will be solved in #2058, but there might be other compatibility issues do to the different versions of Pandas.

**Comment by martin-mosteiro** [comment]
Actually, I was wrong. `sheet_name` doesn't work on Euler at all, only the deprecated `sheetname` works.

**Comment by daren-thomas** [comment]
@martin-mosteiro closed as your PR was merged.
