### ISSUE TITLE
Add option to create building schedules from MATSim population data

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2061]
As discussed with @daren-thomas yesterday, I have created a script to read a MATSim population file and create building schedules from it. This has remained in my own personal branch as I am not sure how interesting it is to other users of CEA, but it could easily be adjusted to create individual building schedules that could be imported as defined in #2024.

@JIMENOFONSECA, @gabriel-happle: would this be a feature worth adding as a side option on CEA?

**Comment by martin-mosteiro** [comment]
This will in any case not be done before July.

**Comment by JIMENOFONSECA** [comment]
Hi Martin. This definately will be great to have as it allows to make future comparisons among occupancy models much more easy. Maybe the matsim data becomes part of a default database for the CH context?

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 12 Jun 2019, 09:44 +0200, Martín Mosteiro-Romero <notifications@github.com>, wrote:

This will in any case not be done before July.

**Comment by gabriel-happle** [comment]
@martin-mosteiro see #2182 and #2185 for the planned features after discussion between me and @daren-thomas

**Comment by daren-thomas** [comment]
@martin-mosteiro does the new schedules feature (#2182) help here? could you create this as a schedule-maker tool (#2185)? this could also be a blog post!

**Comment by martin-mosteiro** [comment]
@daren-thomas No progress made on this yet, need to dive into the new schedules feature and add the MATSim stuff to that.
