### ISSUE TITLE
Add process cooling as an energy demand in CEA

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2063]
As discussed with @daren-thomas, this has been a necessary implementation on my own obscure branch of CEA that should be implemented on the master branch as well.

Unfortunately, building energy demand data is not always detailed enough to provide information of the specific uses for different energy demands in an area. In CEA there are two variables for process energy calculation (process electricity and process heat demand) that lump together these demands regardless of what the exact processes in the building are. The same had to be created for process cooling in the Hochschulquartier since we didn't have detailed data of which processes this cooling was actually being used for.

Since there are already similar parameters for electricity and heating, it makes sense to have the same for cooling. This will not be done before July, though.

**Comment by daren-thomas** [comment]
@martin-mosteiro what is the status here? can you provide a PR?

**Comment by martin-mosteiro** [comment]
@daren-thomas no progress made, but it's an easy addition, so I can take care of it by the next milestone
