### ISSUE TITLE
error caused by small geometries extracted from arcmaps

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2065]
Hi,

I have noticed in quite a few case studies that the zone generating process selects some small geometries (probably some infrastructure components) in Open Street Maps as buildings.
When running the demand those "buildings", this generates an error which @JIMENOFONSECA suggested to bypass by setting the Hs=0, which works for now.
The problem is that sometimes I can't identify all the problematic "buildings" and need to run the simulation each time there is such error, sometimes requiring multiple runs to finish one successful simulation. Every time there is a problematic building, the simulation stops.
Also, there is no clear error message in the CEA dashboard, but I can see it in PyCharm.

Is it possible to add a filter that remove those areas that are clearly not corresponding to buildings? Or perhaps skip the problematic buildings and run the others?

Just a suggestion to help on the workflow and dealing with those outliers from Open Street Maps. If you need more details about it, let me know. Thanks!

**Comment by reyery** [comment]
I have been testing with many different scenarios to find a way to filter out problematic buildings and it seems like buildings generally under 100m<sup>2</sup> would throw the error (not very accurate, some did not when it was around 90). I am not sure there is a surefire way that we can filter out such buildings.

A better idea would be the one that you have suggested is to skip such buildings during simulation when they encounter the error, however I am not sure if that would affect the results. @JIMENOFONSECA what do you think?

**Comment by JIMENOFONSECA** [comment]
I would suggest to:


  1.  Add an explicit messagge to the error of temperature explaining the potential causes of the error to the user. “There was an error in building xxxx, potential problems are an area of less than 100m2.”
  2.  Add a function to CEA where we can eliminate buildings from the zone. It should also erase all the rows in the iput databases with information about that building..

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 17 Jun 2019, 12:15 +0200, Reynold Mok <notifications@github.com>, wrote:

I have been testing with many different scenarios to find a way to filter out problematic buildings and it seems like buildings generally under 100m2 would throw the error (not very accurate, some did not when it was around 90). I am not sure there is a surefire way that we can filter out such buildings.

A better idea would be the one that you have suggested is to skip such buildings during simulation when they encounter the error, however I am not sure if that would affect the results. @JIMENOFONSECA<https://github.com/JIMENOFONSECA> what do you think?

**Comment by lguilhermers** [comment]
I agree that the solution provided by @JIMENOFONSECA seems the best one for the moment. The feature to eliminate buildings would also be useful if I identify that a structure created by open street maps does not correspond to the reality or to the case study analyzed.

**Comment by daren-thomas** [comment]
This is one of the limitations of the model.
