### ISSUE TITLE
Handle type casting exceptions of Openstreetmaps data

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2066]
As mentioned in https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2013#issuecomment-501199526, we need to be careful of type casting values from openstreetmaps as the data might contain erroneous values. 

There should be `try-except`s that provide default/best guesses for such data.

**Comment by JIMENOFONSECA** [comment]
solved in master
