### ISSUE TITLE
CEA not opening

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2068]
Hi,
With latest updates, I am not being able to open the CEA. Is it working normally for you?
Any suggestions on how to deal with that?

Regards,
Luis

**Comment by reyery** [comment]
@lguilhermers Oh if I'm not wrong you are seeing an `ImportError`? I think we just merged a branch that has a new module i.e. `staticmap` that needs to be installed manually (until the new installer is created). 

You can try running this command in the `CEA Console` if that's the case.
```
C:\Users\%USERNAME%\Documents\CityEnergyAnalyst\Dependencies\Python\python.exe -m pip install staticmap
```

If not, do share the error message if there is any.

**Comment by lguilhermers** [comment]
@reyery 
the program closes while trying to open, I can't see any error message or have access to the dashboard.

Thanks!

**Comment by reyery** [comment]
@lguilhermers ok, just tested and my guess was correct. Try running the above command

**Comment by lguilhermers** [comment]
Ok, I just ran your command in cmd outside of CEA instead and it worked.
Thanks!

**Comment by reyery** [comment]
No problem! We should have known this would happen when merging. Closing this issue for now.
