### ISSUE TITLE
ImportError for users on CEA developer version

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2069]
As in #2068, users who have already installed the developers version of the CEA will not be able to launch the dashboard using `CEA Dashboard` shortcut if they update from master when a new module is imported but not installed.

This was recently caused by PR #2055 with the introduction of the `staticmap` module.
Temporary fix now is to run:
```
C:\Users\%USERNAME%\Documents\CityEnergyAnalyst\Dependencies\Python\python.exe -m pip install staticmap
```

**Comment by daren-thomas** [comment]
For pip installable modules, the workflow should be:

- developer adding a dependency needs to add the module to the `INSTALL_REQUIRES` list in `setup.py`

All other users of CEA with the developer version then just need to `pip install -e PATH_TO_CEA_REPO`. In the standard case, as set up by the installer, launch the CEA Console and type:

```
pip install -e CityEnergyAnalyst
```

That will update the requirements as specified in the `INSTALL_REQUIRES` section of `setup.py`. Also, installations with the installer will pick this up even if no new `Dependencies.7z` is released.
