### ISSUE TITLE
Blog for 2.18: Make building models and edit with jupyter

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2072]

**Comment by gabriel-happle** [comment]
@daren-thomas and @JIMENOFONSECA would you mind checking my jupyter notebook first before I convert it into a blog. Thanks!
You can find it here[https://nbviewer.jupyter.org/github/gabriel-happle/blog/blob/master/jupyter-and-CEA.ipynb](url)

**Comment by daren-thomas** [comment]
@gabriel-happle first feedback:

```
c = config.Configuration() # this creates a CEA configuration object
c.extract_reference_case.destination = path_to_folder_for_blog # setting the path to unpack the case study
c.extract_reference_case.case = 'cooling' # selecting the case study to unpack
```

should actually be `cea.api.extract_reference_case(destination=path_to_folder_for_blog, case="cooling")`

I think this shows off the functionality of `cea.api` much better. And also, saves you a lot of extra lines.

**Comment by daren-thomas** [comment]
Also, remove hard-coded paths to your `%userprofile%`. instead, you can use `os.path.expandvars(r"${userprofile}\Documents\blog")`.

**Comment by gabriel-happle** [comment]
@daren-thomas thanks for the great feedback!
Those things are exactly what I need to learn.
>
There is a bit of motivation missing at the top. Is the notebook going to be the blog entry, or are you going to embed it into a blog thing?

**Comment by gabriel-happle** [comment]
@daren-thomas 
Am I correct that `cea.api.demand(scenario_name='name')` does not work?
It should be `cea.api.demand(scenario='path_to_folder')` to work

**Comment by gabriel-happle** [comment]
@daren-thomas I updated the notebook according to your comments.
I hope now it doesn't 

> go against the grain of all the CEA code

**Comment by gabriel-happle** [comment]
@daren-thomas and @JIMENOFONSECA my blog is online as a draft.
I embedded the jupyter notebook directly as an `iframe`. Most of the text is inside the notebook.
Does anyone have time to review?
I will check all the texts with grammarly before publishing as well.

**Comment by daren-thomas** [comment]
Reviewed it - changed jupyter to Jupyter. Published. Thank you very much, Gabriel!
