### ISSUE TITLE
Demand calculation fails after re-running solar radiation

### ISSUE THREAD

**Issue by Khayatian** [architecture-building-systems/CityEnergyAnalyst#2078]
The demand calculation fails after re-running the solar radiation (Daysim engine) module.

To replicate:
(1) open reference-case-open
(2) run solar potential module
(3) run demand module

Demand calculations fail after building #3 is completed.

**Comment by daren-thomas** [comment]
@Khayatian what is the error message?

**Comment by Khayatian** [comment]
@daren-thomas  the error retuned:

City Energy Analyst version 2.16
Running `cea demand` with the following parameters:
- general:scenario = D:\Users\Fazel\Documents\CityEnergyAnalyst\reference-case-open\reference-case-open\baseline
  (default: C:\reference-case-open\baseline)
- general:weather = d:\users\fazel\documents\cityenergyanalyst\cityenergyanalyst\cea\databases\weather\Singapore-2015.epw
  (default: d:\users\fazel\documents\cityenergyanalyst\cityenergyanalyst\cea\databases\weather\Zug.epw)
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- demand:buildings = []
  (default: [])
- demand:loads-output = []
  (default: [])
- demand:massflows-output = []
  (default: [])
- demand:temperatures-output = []
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:format-output = csv
  (default: csv)
- demand:use-dynamic-infiltration-calculation = False
  (default: False)
- demand:use-stochastic-occupancy = False
  (default: False)
- demand:override-variables = False
  (default: False)
- demand:write-detailed-output = False
  (default: False)
- demand:predefined-hourly-setpoints = False
  (default: False)
- general:debug = False
  (default: False)
Running demand calculation for scenario D:\Users\Fazel\Documents\CityEnergyAnalyst\reference-case-open\reference-case-open\baseline
Running demand calculation with weather file d:\users\fazel\documents\cityenergyanalyst\cityenergyanalyst\cea\databases\weather\Singapore-2015.epw
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=True
Running demand calculation with stochastic occupancy=False
read input files
done
Running demand calculation for all buildings in the zone
Using 7 CPU's
Building No. 1 completed out of 9
Building No. 2 completed out of 9
Building No. 3 completed out of 9
Process Process-1:
Traceback (most recent call last):
  File "D:\Users\Fazel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "D:\Users\Fazel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "d:\users\fazel\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\tools\worker.py", line 19, in run_script
    script(**kwargs)
  File "d:\users\fazel\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 28, in script_runner
    script_module.main(config)
  File "d:\users\fazel\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 200, in main
    demand_calculation(locator=locator, config=config)
  File "d:\users\fazel\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 106, in demand_calculation
    format_output, config, write_detailed_output, debug)
  File "d:\users\fazel\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 177, in calc_demand_multiprocessing
    job.get(240)
  File "D:\Users\Fazel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
Exception: Temperature in RC-Model of building B06 out of bounds! First occured at timestep = 1887. The results were Tint = 50.1279023515, theta_c = 49.8611164533, theta_m = 49.7969455152, Check building geometry and internal loads! Building might be too small in size or architecture parameter Hs = 0.9 might be too small for this geometry. Current bounds of range for RC-model temperatures are between -30.0 and 50.0.

**Comment by Khayatian** [comment]
Issue found:
The solar module was run for Singapore, resulting in high solar gains, and therefore internal temperatures rise (outside the bounds of +50 and -30). The Demand works well with Zug weather data file, which has lower solar radiation.
