### ISSUE TITLE
Projection issues with the Spacergy scenarios

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2079]
The latest shapefiles for the Spacergy scenarios after @emanuel030 projected them all to standard coordinates have issues, where the zone and district shapefiles for scenarios 2, 3, and 4 do not match (see image below as example).
This is not the case in the older version of these shapefiles, so projecting the old shapefiles to the new coordinate system might suffice.
![image](https://user-images.githubusercontent.com/18548065/59629432-143eb100-9143-11e9-88ec-25e56e63dcf1.png)

**Comment by daren-thomas** [comment]
@martin-mosteiro is there anything to be done here?

**Comment by martin-mosteiro** [comment]
@daren-thomas Yes – but it only affects my reference case. You can close it if necessary.
