### ISSUE TITLE
Create a model for a ventilation heat exchanger with humidity exchange

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#208]
Heat exchangers should incorporate a humidity exchange model for the Singapore case.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle is this still an issue? what is the action plan?

**Comment by gabriel-happle** [comment]
Should be part of humidity modeling. Action plan up for discussion.

**Comment by shanshanhsieh** [comment]
Humidity recovery in the heat exchangers in AHU should be added (e.g. enthalpy wheel or desiccant wheel)

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
