### ISSUE TITLE
Add network plots to Dashboard

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2082]
Inside `cea.plots.thermal_networks.main.plots_main`, there are three plots that I have not added as part of #1984, as they require some re-thinking of how to show that data. Currently, a png image is produced. For the Dashboard a more interactive and visually interesting plot would be similar to how the `cea/plots/supply_system/map_chart.py` works for the supply system plots. The supply system plots are currently non-functional (see #2081)

The three plots in question:

- DC__network_layout.png
- DC__pressure_loss_networkaggregated.png
- DC__pressure_loss_networkpeak.png

**Comment by daren-thomas** [comment]
Add these maps to the "map" part of map-style dashboard.

- how? does user select the plot to show?
- maybe a dropdown or something.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas so these are ready to add they should be part of the new supply maps #1578  (which show 3D information)

**Comment by gabriel-happle** [comment]
@reyery and @daren-thomas what is the status of this issue?

**Comment by daren-thomas** [comment]
@gabriel-happle There is a PR which addresses it. It hasn't been merged yet.
