### ISSUE TITLE
Scenario images do not update when zone file is updated

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2088]
Currently, the script for generating scenario images in the `project overview` of dashboard only creates an image if it does not exist. So the image for the scenario does not change/refresh when the `zone` file is edited e.g. delete buildings.

One way to solve this would be to create a refresh button for each scenario, which will delete the current image and create a new one.

There could be also be a 'cleanup" script that would delete images for scenarios that do not exist in the project anymore.

**Comment by daren-thomas** [comment]
Another way to solve this would be to compare the timestamps on the `zone.shp` file vs. the scenario preview image. If the `zone.shp` file is newer - recreate the image? This logic would go where the test for existance of that preview image goes. Test for both (`if not preview_image_exists(scenario_name) or preview_image_outdated(scenario_name): create_preview_image(scenario_name)`
