### ISSUE TITLE
windows 2.14 installation error

### ISSUE THREAD

**Issue by SyrinxS** [architecture-building-systems/CityEnergyAnalyst#2089]
Completed the base installation and click on the CEA dashboard, it poped up: python.exe- cannot find ordinal: Ordinal 242 could not be located in the dynamic link library libiomp5md.dll
![1](https://user-images.githubusercontent.com/52148503/60020169-09939700-96c2-11e9-95c2-cff46ef94e95.JPG)
 
I installed 2.13 before, however, I think it has unistalled already.

How can I fix it now?

**Comment by daren-thomas** [comment]
@SyrinxS, could you please try installing the [latest release (2.16)](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/tag/v2.16)?

I don't think you need to uninstall first - just re-run the installer and see if that works for you.

**Comment by daren-thomas** [comment]
Closing this issue as it applies to an older release.
