### ISSUE TITLE
Implement comfort measurements

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#209]
Measure and report comfort levels in buildings as a function of air temperature and humidity.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle is it still an issue? what is the action plan?

**Comment by gabriel-happle** [comment]
Also connected to humidity modeling. Action plan to discuss.

**Comment by gabriel-happle** [comment]
Maybe we could bring back this @shanshanhsieh and @JIMENOFONSECA . Currently comfort/uncomfort is not calculated.
With the moisture model this is possible.

**Comment by JIMENOFONSECA** [comment]
Maybe a nice to have kind of thing?

On 1 Mar 2018, 10:36 +0800, Gabriel Happle <notifications@github.com>, wrote:

Maybe we could bring back this @shanshanhsieh<https://github.com/shanshanhsieh> and @JIMENOFONSECA<https://github.com/jimenofonseca> . Currently comfort/uncomfort is not calculated.
With the moisture model this is possible.

**Comment by JIMENOFONSECA** [comment]
https://plot.ly/~vista/13.embed

**Comment by gabriel-happle** [comment]
https://pypi.python.org/pypi/psychrochart/0.1.10

**Comment by gabriel-happle** [comment]
![image](https://user-images.githubusercontent.com/17002288/38593308-57439a30-3d73-11e8-9b6f-9696b6dd0451.png)

This will be the easiest way to determine thermal comfort in a general way.
Later we could implement the PMV method of Fanger or some of the new methods. Most of them are available in the Ashrae Handbook of Fundamentals

**Comment by gabriel-happle** [comment]
https://www.researchgate.net/figure/Psychrometric-chart-with-superimposed-comfort-zones-for-05-and-10-clo-summer-and_fig2_261566668

corners of zones extracted from this graph

**Comment by gabriel-happle** [comment]
![image](https://user-images.githubusercontent.com/17002288/38600038-4711cb24-3d95-11e8-8456-8a5734c8e3cb.png)

This is my draft of the chart.
Any feedback at this stage @JIMENOFONSECA, @shanshanhsieh, @martin-mosteiro

**Comment by shanshanhsieh** [comment]
looks nice! 
maybe the RH lines can all be the same color (background-ish), and the two comfort zones can be in different colors

**Comment by JIMENOFONSECA** [comment]
very cool!. Maybe as Shanshan said, the RH lines can be grey (part of the background).I would also exclude them from the legend so they are always there.


Kind regards,

Jimeno

On 11 Apr 2018, 2:38 PM +0800, Shanshan Hsieh <notifications@github.com>, wrote:

looks nice!
maybe the RH lines can all be the same color (background-ish), and the two comfort zones can be in different colors

**Comment by gabriel-happle** [comment]
![image](https://user-images.githubusercontent.com/17002288/38611711-fd65a604-3db6-11e8-9fae-40568bad25c2.png)
