### ISSUE TITLE
Temperature in RC-Model out of bounds when running demand

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2097]
@kerembeygo ran into this issue in #2094 - I'm opening this as a separate issue so we can close the first one.

Screenshots of the output:

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/0be79138-f966-42ea-9ea3-4fe437cb6f16)
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/fc8f58bd-59c2-4752-8a48-7410d834b534)
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/583d0f9a-bd0f-40a6-bd54-f8eb840cc48b)
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/e8b65ae8-24b2-4f89-b927-2302493cc04f)

**Comment by JIMENOFONSECA** [comment]
@daren-thomas The error message seems to be clear. Hs might be too small. As discussed this is a limitation of the model. It ode snot handle tiny geometries.
