### ISSUE TITLE
Plots for Demand no working in master

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2105]
@daren-thomas no idea why, but somehow the next plots throw a server error and it has to do with the script:

Heating reset curve
Energy balance

Just try to run it for any case study, it will just not work.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I'm on it. actually, just fixed them as related to #2096, PR is coming any moment now.
