### ISSUE TITLE
Error with the terrain during simulations

### ISSUE THREAD

**Issue by TheoBreidenstein** [architecture-building-systems/CityEnergyAnalyst#2111]
Hello,

I have an error when I want to run Solar Radiation (Daysim system) tool. I have built my own model of Tecnico Lisbon. You could find the Project Folder here : **https://we.tl/t-MnbYw2tmWf** (available until _Jully 5th 2019_).

I have such an error : 

> _ValueError: ERROR: this usually happens when buildings do not overlap with the terrain, try to check if this is the case_

Actually, I can't run any simulation without an _ERROR_. 
However, my model is well represented when I see it in the input section of CEA.

> City Energy Analyst version 2.16
Running `cea radiation-daysim` with the following parameters:
>- general:scenario = C:\Users\theob\Desktop\IN+\Projets\Lisbon\IST_lisbondata
  (default: C:\reference-case-open\baseline)
>- general:weather = C:\Users\theob\Documents\CityEnergyAnalystv16\Dependencies\Python\lib\site-packages\cea\databases\weather\lisbon.epw
  (default: C:\Users\theob\Documents\CityEnergyAnalystv16\Dependencies\Python\lib\site-packages\cea\databases\weather\Zug.epw)
>- general:multiprocessing = True
  (default: True)
>- general:debug = True
  (default: False)
>- radiation-daysim:buildings = []
  (default: [])
>- radiation-daysim:n-buildings-in-chunk = 10
  (default: 100)
>- radiation-daysim:roof-grid = 10
  (default: 10)
>- radiation-daysim:walls-grid = 200
  (default: 200)
>- radiation-daysim:zone-geometry = 2
  (default: 2)
>- radiation-daysim:surrounding-geometry = 5
  (default: 5)
>- radiation-daysim:consider-floors = True
  (default: True)
>- radiation-daysim:rad-ab = 4
  (default: 4)
>- radiation-daysim:rad-ad = 512
  (default: 512)
>- radiation-daysim:rad-as = 32
  (default: 32)
>- radiation-daysim:rad-ar = 20
  (default: 20)
>- radiation-daysim:rad-aa = 0.15
  (default: 0.15)
>- radiation-daysim:rad-lr = 8
  (default: 8)
>- radiation-daysim:rad-st = 0.5
  (default: 0.5)
>- radiation-daysim:rad-sj = 0.7
  (default: 0.7)
>- radiation-daysim:rad-lw = 0.05
  (default: 0.05)
>- radiation-daysim:rad-dj = 0.7
  (default: 0.7)
>- radiation-daysim:rad-ds = 0.0
  (default: 0.0)
>- radiation-daysim:rad-dr = 0
  (default: 0)
>- radiation-daysim:rad-dp = 32
  (default: 32)
>- radiation-daysim:albedo = 0.2
  (default: 0.2)
>- radiation-daysim:daysim-bin-directory = C:\Users\theob\Documents\CityEnergyAnalystv16\Dependencies\Daysim
  (default: C:\Daysim\bin)
verifying geometry files
C:\Users\theob\Desktop\IN+\Projets\Lisbon\IST_lisbondata\inputs\building-geometry\zone.shp
creating 3D geometry and surfaces
Reading terrain geometry
Creating 3D building surfaces
Generating geometry for building B34645
burning building  B34645
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\theob\Documents\CityEnergyAnalystv16\Dependencies\Python\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\Users\theob\Documents\CityEnergyAnalystv16\Dependencies\Python\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\theob\Documents\CityEnergyAnalystv16\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\tools\worker.py", line 19, in run_script
    script(**kwargs)
  File "C:\Users\theob\Documents\CityEnergyAnalystv16\Dependencies\Python\lib\site-packages\cea\api.py", line 28, in script_runner
    script_module.main(config)
  File "C:\Users\theob\Documents\CityEnergyAnalystv16\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\radiation_main.py", line 195, in main
    config)
  File "C:\Users\theob\Documents\CityEnergyAnalystv16\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\geometry_generator.py", line 402, in geometry_main
    height_col='height_ag', nfloor_col="floors_ag")
  File "C:\Users\theob\Documents\CityEnergyAnalystv16\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\geometry_generator.py", line 184, in building2d23d
    face_footprint = burn_buildings(geometry, terrain_intersection_curves)
  File "C:\Users\theob\Documents\CityEnergyAnalystv16\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\geometry_generator.py", line 301, in burn_buildings
    raise ValueError('ERROR: this usually happens when buildings do not overlap with the terrain, try to check if this is the case')
ValueError: ERROR: this usually happens when buildings do not overlap with the terrain, try to check if this is the case

In the project folder I sent, you will find a terrain.tif which correspond exactly to the elevation of my district when I open it with QGIS. Actually I have made it by downloading a file from the NASA RSTM here : **http://dwtkns.com/srtm30m/** and then I cropped the file in QGIS to not take into account such an area but only the area which interrests me and then I exported it as a GeoTIFF file.

I also tried to run it with a project created thanks to the differents helpers but it still do the same.

**Comment by reyery** [comment]
@TheoBreidenstein you should change the coordinate system of your terrain file to a projected coordinate system (UTM) and you can do this with QGIS or ARCGIS.

**Comment by TheoBreidenstein** [comment]
Thank you for your answer,

Actually, it doesn't change anything. I still have the error message : **_ValueError: ERROR: this usually happens when buildings do not overlap with the terrain, try to check if this is the case_**
My files are located in Lisbon PT. I don't know if it is the reason of the problem. Because, when I run the tool with the reference-case-open, it works. 
And when I try to create my terrain file with the terrain helper, I found the same error by running Solar Radiation tool.

**Comment by TheoBreidenstein** [comment]
That is my last < cea radiation-daysim > - output


City Energy Analyst version 2.16
Running `cea radiation-daysim` with the following parameters:
- general:scenario = C:\Users\theob\Desktop\IN+\Projets\Lisbon\reference-case-open\baseline
  (default: C:\reference-case-open\baseline)
- general:weather = C:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\databases\weather\Zug.epw
  (default: C:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\databases\weather\Zug.epw)
- general:multiprocessing = True
  (default: True)
- general:debug = False
  (default: False)
- radiation-daysim:buildings = []
  (default: [])
- radiation-daysim:n-buildings-in-chunk = 100
  (default: 100)
- radiation-daysim:roof-grid = 10
  (default: 10)
- radiation-daysim:walls-grid = 200
  (default: 200)
- radiation-daysim:zone-geometry = 2
  (default: 2)
- radiation-daysim:surrounding-geometry = 5
  (default: 5)
- radiation-daysim:consider-floors = True
  (default: True)
- radiation-daysim:rad-ab = 4
  (default: 4)
- radiation-daysim:rad-ad = 512
  (default: 512)
- radiation-daysim:rad-as = 32
  (default: 32)
- radiation-daysim:rad-ar = 20
  (default: 20)
- radiation-daysim:rad-aa = 0.15
  (default: 0.15)
- radiation-daysim:rad-lr = 8
  (default: 8)
- radiation-daysim:rad-st = 0.5
  (default: 0.5)
- radiation-daysim:rad-sj = 0.7
  (default: 0.7)
- radiation-daysim:rad-lw = 0.05
  (default: 0.05)
- radiation-daysim:rad-dj = 0.7
  (default: 0.7)
- radiation-daysim:rad-ds = 0.0
  (default: 0.0)
- radiation-daysim:rad-dr = 0
  (default: 0)
- radiation-daysim:rad-dp = 32
  (default: 32)
- radiation-daysim:albedo = 0.2
  (default: 0.2)
- radiation-daysim:daysim-bin-directory = C:\CityEnergyAnalyst\Dependencies\Daysim
  (default: C:\Daysim\bin)
verifying geometry files
C:\Users\theob\Desktop\IN+\Projets\Lisbon\reference-case-open\baseline\inputs\building-geometry\zone.shp
creating 3D geometry and surfaces
Reading terrain geometry
Creating 3D building surfaces
Generating geometry for building B36646
burning building  B36646
Process Process-5:
Traceback (most recent call last):
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\tools\worker.py", line 19, in run_script
    script(**kwargs)
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 28, in script_runner
    script_module.main(config)
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\radiation_main.py", line 195, in main
    config)
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\geometry_generator.py", line 402, in geometry_main
    height_col='height_ag', nfloor_col="floors_ag")
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\geometry_generator.py", line 184, in building2d23d
    face_footprint = burn_buildings(geometry, terrain_intersection_curves)
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\geometry_generator.py", line 301, in burn_buildings
    raise ValueError('ERROR: this usually happens when buildings do not overlap with the terrain, try to check if this is the case')
ValueError: ERROR: this usually happens when buildings do not overlap with the terrain, try to check if this is the case

**Comment by TheoBreidenstein** [comment]
Hello, 

I succeed to run the simulation tool and to fix the terrain issue by following the solution of @DespaxJulien in #2060.
The fix is to put terrain.tif, and all other shapefiles in the same coordinate system and in a UTM coordinate system. Actually, I had my district.shp which stayed in WGS 84 / Pseudo Mercator.

Thank you for your help.
