### ISSUE TITLE
Zone helper dialog: ValueError: Can't decode value for non-nullable IntegerParameter

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2112]
Steps to reproduce:

- open "Project Overview > New Scenario"
- select "Generate new input files"
- edit zone helper properties:
  - set `floors-bg` to `2.0`
- click "Save Configuration"

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/16fb0fd1-3e09-4ff8-8e2e-271037cd5fb9)

Expected: Either a message that an integer is expected _OR_ conversion to integer / default value (blank)

Buggy behaviour: Dialog hangs with message "Saving Configuration." see image below:

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/8c4b63e7-7891-41b4-aa5e-0c27ec2a9006)

Traceback:

```
INFO:werkzeug:127.0.0.1 - - [28/Jun/2019 14:12:23] "GET /landing/create-scenario/zone-helper/settings HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jun/2019 14:12:23] "GET /tools/static/tools.js?_=1561723881396 HTTP/1.1" 200 -
scenario: C:\reference-case-cooling
height-ag: 3.0
floors-ag:
year-construction:
height-bg: 3.0
floors-bg: 2.0
ERROR:flask.app:Exception on /landing/save-config/zone-helper [POST]
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\dashboard\landing\routes.py", line 276, in route_save_config
    parameter.set(parameter.decode(request.form.get(parameter.name)))
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\config.py", line 471, in decode
    raise ValueError("Can't decode value for non-nullable IntegerParameter.")
ValueError: Can't decode value for non-nullable IntegerParameter.
```

**Comment by reyery** [comment]
@daren-thomas I have been trying to do the input validation with the help of `decode()` in the `Parameter` classes but found a buggy behavior for `nullable` parameters. 

For example, the `height-ag` parameter for `zone-helper` is a `nullable` `RealParameter`. Entering a string in the input and click "Saving Configuration" would still save the config as `None` even though it is not a number. Is this intentional behavior?

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/e11ce5988e5dc9149f364ceb8b1e2252af09ce87/cea/config.py#L498-L505

**Comment by daren-thomas** [comment]
I think so, no?

So `decode` and `encode` solve the problem of serializing input parameters to strings (since, that is ultimately what gets stored in a cea.config file).

An empty string would then decode to `None`, but not be `float()`-able. So, I think that is as intended.

**Comment by reyery** [comment]
It also decodes a non-empty string to `None` (e.g. entering 'test' into the parameter) and not an error. But if that is an intended behavior, then I would have to find another way to do the validation.

Because right now I am using the `ValueError` as a way to do server-side validation. Probably will create another route for this then.

```
def route_save_config(script):
    """Save the configuration for this tool to the configuration file"""
    for parameter in parameters_for_script(script, current_app.cea_config):
        print('%s: %s' % (parameter.name, request.form.get(parameter.name)))
        try:
            parameter.set(parameter.decode(request.form.get(parameter.name)))
        except ValueError as e:
            return Response(json.dumps({parameter.name: e.message}), 400)
    current_app.cea_config.save()

```

**Comment by daren-thomas** [comment]
I guess you could also modify the code and set it to only return `None` when:

```
if self.nullable and value.strip() = "": 
             return None 
```
