### ISSUE TITLE
Internal server error when switching from DC to DH in optimization plot "Centralized costs per generation unit"

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2122]
Steps to reproduce:

- open project with cooling-case-workflow results
- open baseline scenario
- create a new dashboard
- add plot "Optimization overview / Centralized costs per generation unit"
- (assuming config file is set to DC, you should see the plot)
- change settings of plot, from DC to DH

Expected:
- either plot using DH optimization data
- OR an error message instructing user to generate missing files

Actual behavior:
- error message "ERROR: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

**Comment by JIMENOFONSECA** [comment]
@daren-thomas this plot does not existing anymore...
