### ISSUE TITLE
Enhancement: support to copy/ paste to Excel from Building Properties tables

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2131]
Would be good if I could easily copy/paste the tables shown in the building properties tables. This would support some excel functions to be used in those cases.

Those tables and the selections were very good additions, by the way! Kudos to the team!

**Comment by reyery** [comment]
hey @lguilhermers really appreciate the feedback and suggestion! Could use elaborate on what you mean? Do you mean being able to export the table as an excel file?

**Comment by lguilhermers** [comment]
This would also be something good, but what I meant was it would be good if I could copy the building properties table (like the one below) and paste them or part of them excel. Then if I do any manipulations on excel I would be able to paste it back as well.
Basically it would mean to treat those tables as excel cells in terms of selection, copying and paste, then you can pretty much use any excel function to deal with those cells and send it back to CEA easily.
Not sure how easy it is to implement though, just an idea :)

![image](https://user-images.githubusercontent.com/50981039/60695030-da2b2880-9f12-11e9-9323-6d63f0a70ecd.png)

**Comment by daren-thomas** [comment]
@lguilhermers depending on which tables you need to edit (*.dbf or *.shp), the CEA actually provides tools to export them to Excel and import them back. Check the Tools/Utilities category in the navigation sidebar. E.g. the `zone.shp` file has a bunch of similarly named files with different endings. If you edit the `.dbf` file using this method, just make sure you don't change the `Name` column. All the others can be edited. Note that sometimes the conversion can create problems - hence the input editor in the CEA Dashboard interface.

**Comment by lguilhermers** [comment]
Noted, Daren! Thanks for the suggestions! :)
