### ISSUE TITLE
area error message does not show all buildings under 100m²

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2138]
somehow this error message is missing many buildings

example from a case study:
!!!Warning!!!, the next list of buildings have less than 100m2 of net area, CEA does not handle well thsesbuildings, it might be that CEA fails: These are the buildings[u'B1027', u'B1048', u'B1083', u'B1133']

this (any many other) building was not listed there
![image](https://user-images.githubusercontent.com/50981039/60695233-9be23900-9f13-11e9-87fa-aa3a87df3281.png)

**Comment by reyery** [comment]
I found out there is a difference in calculation for the area of the buildings.

The area in the map is calculated as `footprint area` while for the `demand` script is: `footprint area * floors above ground`. 

@JIMENOFONSECA my findings regarding the `"less than 100m²"` error is tested based on `footprint area`, so the error in the `demand` script might not be accurate.

**Comment by lguilhermers** [comment]
Hi @reyery , well observed and based on what I saw your comments make sense.

What I also found interesting is that I ran a case study with many buildings with footprints smaller than 100m² and had almost no errors regarding it. If you want the case-study to help investigating why this error happens just to some buildings, I can send to you.

Regards,
Luis

**Comment by reyery** [comment]
error message has already been added
