### ISSUE TITLE
Redesigning the dashboard

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2140]
Currently our dashboard layout is vertically stacked with one plot on top of another. This would mean that users would have to scroll down to see all the plots that they have added.

We could improve on this layout by making the plots all in one page instead so that the user can see all the plots in one glance without having to scroll down the page (the whole point of a dashboard).

One of the layouts could be like this (example from [Dash](https://dash-gallery.plotly.host/Portal/))
![Screenshot_2019-07-05 Dash](https://user-images.githubusercontent.com/34395415/60700735-7cefa100-9f2b-11e9-9973-41a4fa4e3b29.png)

We can have one that will show visualizations on a map, accompanied by supporting graphs/plots at the side.

**Comment by daren-thomas** [comment]
The main issue here is that a lot of our plots are time-series plots with time on the x-axis. So they tend to be wider than high. That's why it's currently the way it is. BTW: The plotting system doesn't need to change to do multiple next to each other, so feel free to try this out.
