### ISSUE TITLE
Adding input validation for input editor in dashboard

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2141]
Currently, the input editor in the dashboard only does basic input validation i.e. `string or number`. This is not enough as there are some constraints on inputs such as those in `occupancy` where the sum of the columns must be equal to 1 since each column is the fraction of the gross floor area.

Instead of writing such constraints one by one for each table in javascript, the `schema.yml` should contain such information and javascript should just parse it from there.

**Comment by daren-thomas** [comment]
We could model this similar to how SQL databases specify this information. Maybe check sqlalchemy which a) is already a dependency of the CEA and b) includes ways to define this kind of stuff.
