### ISSUE TITLE
Decentralized cooling and heating are not connected to the Optimization 

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2146]
We found that there is not a feedback loop between the electricity and fuel requirements from the decentralized optimization into the district optimization.

The scripts affected are

optimization_preprocessing_decentralized_main
optimization_master_electricity_main

The tasks are:

1. change the decentralized scri[pt to receive one parameter at the time (ahu, aru etc) No more use of single flags.

2. For the best configuration of the decentralized system, output the activation curve for electricity requirements and fuel requirements and solar requirements (if any)

![image](https://user-images.githubusercontent.com/8973186/60799720-47a2b780-a1a6-11e9-813a-ebd756e87b80.png)

![image](https://user-images.githubusercontent.com/8973186/60799735-50938900-a1a6-11e9-9c63-d79b89e7c7e1.png)

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA , here's a brief update of what happened in branch `i2146-decentralized-cooling`

the changes made so far:
1. `decentralized_buildings_cooling.py`
 - remove cooling_configuration 1-6, only run simulation to supply all units (aru, ahu, scu)
 - remove `aruflag`, `scuflag`... as inputs from config
 - vectorize functions that calculate hourly operation
 - output hourly resource activation of the best config

2. `substation.py`
 - change `cooling_configuration` from integer to a list `['scu']` or `['aru','ahu']`
 - the `cooling_configuration` is now an argument passed by other functions, not an input from config
 
3. `decentralized_buildings_heating.py`
 - vectorize functions that calculate hourly operation
 - output hourly resource activation of the best config
 - remove some flags that constraint the use of resources (no BioGas, no GHP...) as it was unclear 
 - some outputs are ambiguous, maybe we can discuss if we need to keep them (@JIMENOFONSECA )

*TO-DO*
(easier to discuss in person)
1. `generation.py`: remove `aruflag`, `scuflag`...
2. after 1., remove `aruflag`, `scuflag`... in `default.config`
3. discuss supply system models (the design/nominal capacity should not be the peak capacity)
4. discuss the hot water demand in SG context (need to change line32-33 in `decentralized_building_main`)
5. impose a threshold using solar collectors for cooling (can reduce calculation time) 

*Other issues* 
(out of scope of this issue, new issues are made to keep track)
1. improve`burner` model (#1325)
2. improve`direct expansion unit` model (#2219)

**Comment by shanshanhsieh** [comment]
one more issue added: 
3. the CT model gives negative electricity usage at high partload (#2227)
