### ISSUE TITLE
Fix typos in error message for buildings with areas < 100m2

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2147]
"!!!Warning!!!, the next list of buildings have less than 100m2 of net area, CEA does not handle well thsesbuildings, it might be that CEA fails: These are the buildings[u'B1027', u'B1048', u'B1083', u'B1133']"

Just saw this message in a user-reported bug. There are so many things wrong with this error message. Let's fix it!

@JIMENOFONSECA I'm assigning this to you as I think you know exactly where to find the message.

**Comment by JIMENOFONSECA** [comment]
Hi Daren, I am busy with the optimization, you can search the message by doing ctrl+shift+f. It is a very cool feature of pycharm. Absolutely anything can be found with that command..

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 8 Jul 2019, 22:12 +0800, Daren Thomas <notifications@github.com>, wrote:

"!!!Warning!!!, the next list of buildings have less than 100m2 of net area, CEA does not handle well thsesbuildings, it might be that CEA fails: These are the buildings[u'B1027', u'B1048', u'B1083', u'B1133']"

Just saw this message in a user-reported bug. There are so many things wrong with this error message. Let's fix it!

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> I'm assigning this to you as I think you know exactly where to find the message.
