### ISSUE TITLE
interface: when accidentally a wrong "project folder" is opened, CEA will create folders there

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2148]
When unintentionally opening a random folder with `open project` in the GUI, the CEA will create a folder `input` in that location.
This is not desired.

Assigning @reyery and @daren-thomas. Priority, etc. TBD.

**Comment by daren-thomas** [comment]
it seems, the `inputs` folder is never created when opening a "project", but it _is_ created when opening a scenario afterwards.
