### ISSUE TITLE
Show confirmation message when leaving input editor after "Edit Selection" without saving

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2149]
Steps to reproduce:

- open input editor
- select some buildings on the map
- click "Edit Selection"
- make some changes
- click "OK"
- navigate to another page (e.g. "Dashboard")

Expected: Confirmation message.
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/8209318b-27c0-45f1-8315-53c40317a158)

Buggy behavior experienced: No message. Changes are discarded.

**Comment by reyery** [comment]
@daren-thomas I just tested this and it works on my side (both Firefox and Chrome). Do the `changes` object show up in the web console after editing the selection? The alert is triggered when `changes` is not empty.

**Comment by daren-thomas** [comment]
![image](https://user-images.githubusercontent.com/2969564/60876823-eed22e00-a23c-11e9-949e-eb3f8e6782ee.png)

Am I doing something wrong?

**Comment by reyery** [comment]
Oh sorry I meant `inputstore.changes`, either `update` or `delete` property should not be empty

**Comment by daren-thomas** [comment]
you're right. it works. thank you!
