### ISSUE TITLE
Compatibility issue with Microsoft Edge for input editor

### ISSUE THREAD

**Issue by RicardoGomesIST** [architecture-building-systems/CityEnergyAnalyst#2151]
Very basic question I guess. I just started using CEA. I opened one of your examples and I cannot visualize the inputs as other colleague of mine does, doing the same.. (apparently). Thank you very much. first picture my case, 2nd my colleague case

![ScreenHunter_147 Jul  09 18 34](https://user-images.githubusercontent.com/52715280/60910283-4641bf80-a278-11e9-8145-8d957d2a1b8d.jpg)
![image](https://user-images.githubusercontent.com/52715280/60910349-76895e00-a278-11e9-9b42-b65285b0b257.png)

**Comment by reyery** [comment]
Hey @RicardoGomesIST thanks for reporting this issue. From what I can see, it seems that you have a newer version of the CEA tool than your colleague. 

Besides that, could you elaborate on what kind of issue you are facing? If there is nothing showing up could you show me what you see in the web console (Chrome: Options > More tools > Developer tools > Console | Firefox: Options > Web Developer > Web Console)

**Comment by RicardoGomesIST** [comment]
Thank you Reynold for your fast reply. Yes, my issue is that in nothing showing up in the inputs button and I was not able to proceed with the case study analysis.

Regarding the info from the web console, I guess this is enough:
run_datatables
init_compose
run_customtabs
SEC7115: :visited and :link styles can only differ by color. Some styles were not applied to :visited.
building-properties (1,1)
3clicked - sidebar_menu
HTML1300: Navigation occurred.
building-properties (1,1)
CSS3121: The media query -ms-viewport has been deprecated.
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - http://localhost:5050/static/vendors/EasyAutocomplete/easy-autocomplete.css
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - http://localhost:5050/static/vendors/EasyAutocomplete/easy-autocomplete.themes.css
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
store.js (109,45)
SCRIPT5009: SCRIPT5009: 'InputStore' is not defined
building-properties (541,5)

**Comment by RicardoGomesIST** [comment]
the problem is that by default the CEA launches Microsoft Edge and didn't work... I tried in Chrome and looks good. Thanks anyway! best

**Comment by reyery** [comment]
Ah great! Glad to know that it works for you now. Will definitely look into browser compatibility, since we currently only test it on Firefox and Chrome. Thanks for alerting us of this issue!

**Comment by daren-thomas** [comment]
This is a known issue that will go away with the move to the electron interface in M2.23.
