### ISSUE TITLE
`data-helper` must respect existing scenario databases

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2152]
The `data-helper` creates a copy of the archetypes databases in the scenario folder.
If I want to modify my archetypes, I will change values in this local databases.
But then how do I apply these changes?
If I run the `data-helper` again, it will overwrite the archetypes with the default database and hence never be able to apply changes...

We must have an option to use the existing scenario databases!
Or am I missing something?

This is related to #2036

**Comment by daren-thomas** [comment]
Maybe the data-helper needs to be split up into two levels?
OR: don't overwrite archetypes if they're already in the folder?

SO: data-helper should not create / alter `inputs/technologies`. Instead, this should be created by `new-scenario` tool.

OR: data-helper should split "technologies" from databases parameter, add it as a boolean (overwrite/create technologies folder)

building models vs. region-specific data.

Also: re-think the naming everywhere!

**Comment by gabriel-happle** [comment]
yes. This is fixed in #2265
