### ISSUE TITLE
Go through glossary.csv and find all missing information / spelling errors

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2153]
- afterwards: create task to move plots to use glossary.csv instead of naming.csv (remove that)

**Comment by Jack-Hawthorne** [comment]
@daren-thomas has the schema.yml been completely updated yet? the naming_new.csv used the old naming.csv and the old glossary.csv to grab the descriptions and colors etc... to salvage information.

if so, has the `cea doc update naming` been run? i would like to make sure the glossary.csv is fully up to date before proof reading and filling in missing information.

**Comment by daren-thomas** [comment]
@Jack-Hawthorne we're not talking about the same glossary.csv I think. I'm talking of `cea/glossary.csv` which we newly added by moving `naming_new.csv`.

No, the data is not complete, mainly, because the optimization stuff is being refactored as we speak. I still think it's possible to proofread what we have so far - you can always use the diff to check the new stuff when we add that. I think this route adds more value than waiting.

**Comment by Jack-Hawthorne** [comment]
@daren-thomas no worries, i shall finish off the default config help descriptions then move to this one asap.

**Comment by Jack-Hawthorne** [comment]
hey all! in my journey through most of the databases in cea, i am coming up with a few variables which i struggle to define. If you could please take the time to fill in these (don't worry about grammar/spelling, just try to convey the best you can), i would be more than happy to proof/reword and insert into the glossary.

@BhargavaKrishnaSreepathi 

electrical_networks.xlsx

need the description and units for these:

- r_ohm_per_km
- x_ohm_per_km
- z_ohm_per_km
- b_sh_s_per_km
- S_max_MVA
- C_microF_per_km
- l_mH_per_km
- y_ohm_per_km
- g_s_per_km
- b_s_per_km
- I_max_A
- price_sgd_per_m
- lifetime_a
- om_factor
- sub_price_sgd_per_kva
- build_price_sgd_per_kva


supply_systems.xls:PV


- PV_th
- PV_n
- PV_noct
- PV_Bref
- PV_a0
- PV_a1
- PV_a2
- PV_a3
- PV_a4
- misc_losses


supply_systems.xls:SC

- aperture_area_ratio
- n0
- c1
- c2
- mB0_r
- mB_max_r
- mB_min_r
- C_eff
- t_max
- IAM_d
- dP1
- dP2
- dP3
- dP4
- Cp_fluid

supply_systems.xls:HEX

- a_p
- b_p
- c_p
- d_p
- e_p


supply_systems.xls:Absorption_chiller

- el_W
- s_e
- r_e
- s_g
- r_g
- a_e
- e_e
- a_g
- e_g
- m_cw
- m_hw


@martin-mosteiro 

LCA_buildings.xlsx:EMBODIED_ENERGY


- Wall_int_sup
- Wall_int_nosup


@JIMENOFONSECA 

electrical_networks.xlsx

- r_ohm_per_km
- x_ohm_per_km
- z_ohm_per_km
- b_sh_s_per_km
- S_max_MVA
- C_microF_per_km
- l_mH_per_km
- y_ohm_per_km
- g_s_per_km
- b_s_per_km
- I_max_A
- price_sgd_per_m
- lifetime_a
- om_factor
- sub_price_sgd_per_kva
- build_price_sgd_per_kva



don't worry, more to come!

--------------------------


i also have some questions regarding the input databases which are a bit confusing and sometimes misleading:


1.

construction_properties.xlsx:SUPPLY    vs.    construction_properties.xlsx:HVAC

What is the difference here? 

Which are the codes used in the SUPPLY tab, and more specifically for the `type_el` attribute. 
If they are from emissions_systems.xls, what is the distinction between the HVAC and SUPPLY tabs in the construction_properites.xlsx? (note: `type_el` is not defined in emissions_systems.xls, i cannot find it).




2. 

my beef with supply_systems.xls


supply_systems.xls is mainly used for LCC and sometimes (but not always) storing constraint variables related to supply system sizing.

why are they separated by tabs when they generally have all the same variables and primary keys (the `codes`):

- Description
- code
- currency
- a (and variants of)
- b (and variants of)
- c (and variants of)
- d (and variants of)
- e (and variants of)
- LT_yr
- O&M_%
- IR_%
- assumption

this^ could be one tab (named 'LCC') while the sizing stuff another (like 'dim_and_pwr_constraints'):

- Description
- code
- module_length_m
- module_area_m2
- other variables and such
- Cp_fluid
- cap_min
- cap_max
- unit

this would also prevent little key errors from happening when, for example, the attribute 'unit' is accidentally 'unit ' (in the 'TES' tab) and 'assumption' becomes 'Assumptions' (in the 'FC' tab).

Also, there is a piping catalogue in thermal_networks.xls and also one in supply_systems.xls, can they be merged?


3.

emissions_systems.xls have nothing to do with CO2 emission but supply/return temperatures (misleading name). what about HVAC_systems.xls? or something else?

4.

LCA_infrastructure.xlsx

do the codes for LCA_infrastructure and emission_systems match?
which are used as inputs for the supply_systems.dbf and which for technical_systems.dbf?


cheers!

**Comment by martin-mosteiro** [comment]
@Jack-Hawthorne I have already answered your question in person.

**Comment by martin-mosteiro** [comment]
> construction_properties.xlsx:SUPPLY vs. construction_properties.xlsx:HVAC
> What is the difference here?
> Which are the codes used in the SUPPLY tab, and more specifically for the type_el attribute.
> If they are from emissions_systems.xls, what is the distinction between the HVAC and SUPPLY tabs in the construction_properites.xlsx? (note: type_el is not defined in emissions_systems.xls, i cannot find it).
> LCA_infrastructure.xlsx
> do the codes for LCA_infrastructure and emission_systems match?
> which are used as inputs for the supply_systems.dbf and which for technical_systems.dbf?
HVAC = room-level emission systems (e.g., a radiator)
SUPPLY = energy source for the building (e.g., an oil boiler)
The codes in HVAC do come from `emission_systems.xls`. The codes in SUPPLY come from `LCA_infrastructure.xls`.

> emissions_systems.xls have nothing to do with CO2 emission but supply/return temperatures (misleading name). what about HVAC_systems.xls? or something else?
Yes, that is why the corresponding dbf file is called `technical_systems.dbf`. So the same thing is called *emissions_systems* in the CEA database, *HVAC* in the CEA archetypes, and *technical_systems* in the project inputs. I agree that these should all be unified. Maybe it makes sense to rename all of these to HVAC/HVAC_systems.

**Comment by martin-mosteiro** [comment]
> supply_systems.xls:PV
>    PV_n
panel efficiency
>    PV_noct
[NOCT](https://www.pveducation.org/pvcdrom/modules-and-arrays/nominal-operating-cell-temperature)
>    PV_a0, PV_a1, PV_a2, PV_a3, PV_a4
Constants to calculate air mass modifier (not sure what that means though)
>    PV_Bref
Cell maximum power temperature coefficient 
>    misc_losses
Miscellaneous losses

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne 

r_ohm_per_km - Resistance of one conductor of the line
x_ohm_per_km - Reactance of one conductor of the line
z_ohm_per_km - Impendance of one conductor of the line (actually this is not needed)
b_sh_s_per_km - Shunt suseptance of one conductor of the line (actually this is not needed)
S_max_MVA - Maximum apparent power limit of one conductor of the line (actually this is not needed)
C_microF_per_km - Capacitance of one conductor of the line (actually this is not needed)
l_mH_per_km - Inductance of one conductor of the line (actually this is not needed)
y_ohm_per_km - Admittance of one conductor of the line (actually this is not needed)
g_s_per_km - Conductance of one conductor of the line (actually this is not needed)
b_s_per_km - Suseptance of one conductor of the line (actually this is not needed)
I_max_A - Maximum current limit one conductor of the line
price_sgd_per_m - Price for one conductor of the line
lifetime_a - Lifetime of all grid equipment
om_factor - Operation & maintenance cost factor
sub_price_sgd_per_kva - Substation price per nominal power
build_price_sgd_per_kva - Building transformer price per nominal power

**Comment by Jack-Hawthorne** [comment]
thank you both! 
i shall dig through the code for the rest

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne do you have anymore variables missing?
