### ISSUE TITLE
Error in a formula in the documentation on occupant schedules

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2154]
The [occupant schedule documentation](https://city-energy-analyst.readthedocs.io/en/latest/how-are-schedules-defined.html) has a mistake in one of the formulas.

Where it says `T01(t)=(μ−1)/μ*P(t)+P(t+1)` it should be `T01(t)=(μ−1)/(μ+1)*P(t)+P(t+1)`.

@Jack-Hawthorne Could you please correct that? Thanks!

**Comment by Jack-Hawthorne** [comment]
no worries, ill do it now
