### ISSUE TITLE
Buildings underground will throw an error in the solar radiation.

### ISSUE THREAD

**Issue by TheoBreidenstein** [architecture-building-systems/CityEnergyAnalyst#2155]
Hello, 

When I run Solar Radiation (Daysim engine), I have **_RuntimeError: Standard_ConstructionError_** message which occurs some times.

It only occurs with my complete zone.shp (23 buildings) but not with a simplified model with only one of those.
Could you help me to understand how to deal with it ?

Thank you,

**_`<cea - radiation-daysim> - output`_**

> City Energy Analyst version 2.17.1
> Running `cea radiation-daysim` with the following parameters:
> - general:scenario = C:\Users\theob\Desktop\IN+\Projets\Lisbon\IST_lisbondata\Scenario1
>   (default: C:\reference-case-open\baseline)
> - general:weather = C:\CityEnergyAnalyst17\Dependencies\Python\lib\site-packages\cea\databases\weather\PRT_Lisboa.epw
>   (default: C:\CityEnergyAnalyst17\Dependencies\Python\lib\site-packages\cea\databases\weather\Zug.epw)
> - general:multiprocessing = True
>   (default: True)
> - general:debug = False
>   (default: False)
> - radiation-daysim:buildings = []
>   (default: [])
> - radiation-daysim:n-buildings-in-chunk = 100
>   (default: 100)
> - radiation-daysim:roof-grid = 10
>   (default: 10)
> - radiation-daysim:walls-grid = 200
>   (default: 200)
> - radiation-daysim:zone-geometry = 2
>   (default: 2)
> - radiation-daysim:surrounding-geometry = 5
>   (default: 5)
> - radiation-daysim:consider-floors = True
>   (default: True)
> - radiation-daysim:rad-ab = 4
>   (default: 4)
> - radiation-daysim:rad-ad = 512
>   (default: 512)
> - radiation-daysim:rad-as = 32
>   (default: 32)
> - radiation-daysim:rad-ar = 20
>   (default: 20)
> - radiation-daysim:rad-aa = 0.15
>   (default: 0.15)
> - radiation-daysim:rad-lr = 8
>   (default: 8)
> - radiation-daysim:rad-st = 0.5
>   (default: 0.5)
> - radiation-daysim:rad-sj = 0.7
>   (default: 0.7)
> - radiation-daysim:rad-lw = 0.05
>   (default: 0.05)
> - radiation-daysim:rad-dj = 0.7
>   (default: 0.7)
> - radiation-daysim:rad-ds = 0.0
>   (default: 0.0)
> - radiation-daysim:rad-dr = 0
>   (default: 0)
> - radiation-daysim:rad-dp = 32
>   (default: 32)
> - radiation-daysim:albedo = 0.2
>   (default: 0.2)
> - radiation-daysim:daysim-bin-directory = C:\Daysim\bin
>   (default: C:\Daysim\bin)
> verifying geometry files
> C:\Users\theob\Desktop\IN+\Projets\Lisbon\IST_lisbondata\Scenario1\inputs\building-geometry\zone.shp
> creating 3D geometry and surfaces
> Reading terrain geometry
> Creating 3D building surfaces
> Generating geometry for building B34762
> burning building  B34762
> Generating geometry for building B34775
> burning building  B34775
> Generating geometry for building B34794
> burning building  B34794
> Generating geometry for building B34803
> burning building  B34803
> Generating geometry for building B34813
> burning building  B34813
> Generating geometry for building B34832
> burning building  B34832
> Generating geometry for building B34849
> burning building  B34849
> Generating geometry for building B34854
> burning building  B34854
> Generating geometry for building B34861
> burning building  B34861
> Generating geometry for building B34866
> burning building  B34866
> Generating geometry for building B34882
> burning building  B34882
> Generating geometry for building B34901
> burning building  B34901
> Generating geometry for building B34910
> burning building  B34910
> Generating geometry for building B34911
> burning building  B34911
> Generating geometry for building B34935
> burning building  B34935
> Generating geometry for building B34945
> burning building  B34945
> Generating geometry for building B34953
> burning building  B34953
> Generating geometry for building B34955
> burning building  B34955
> Generating geometry for building B34961
> burning building  B34961
> Generating geometry for building B34990
> burning building  B34990
> Generating geometry for building B35015
> burning building  B35015
> Generating geometry for building B35016
> burning building  B35016
> Generating geometry for building B35032
> burning building  B35032
> Generating geometry for building B35039
> burning building  B35039
> Generating geometry for building B35055
> burning building  B35055
> Generating geometry for building B35056
> burning building  B35056
> Generating geometry for building B35072
> burning building  B35072
> Generating geometry for building B35083
> burning building  B35083
> Generating geometry for building B35087
> burning building  B35087
> Generating geometry for building B35098
> burning building  B35098
> Generating geometry for building B35103
> burning building  B35103
> Generating geometry for building B35150
> burning building  B35150
> Generating geometry for building B35161
> burning building  B35161
> Generating geometry for building B35167
> burning building  B35167
> Generating geometry for building B35174
> burning building  B35174
> Generating geometry for building B35187
> burning building  B35187
> Generating geometry for building B35195
> burning building  B35195
> Generating geometry for building B35209
> burning building  B35209
> Generating geometry for building B35246
> burning building  B35246
> Generating geometry for building B35248
> burning building  B35248
> Generating geometry for building B35250
> burning building  B35250
> Generating geometry for building B35259
> burning building  B35259
> Generating geometry for building B35261
> burning building  B35261
> Generating geometry for building B35288
> burning building  B35288
> Generating geometry for building B35301
> burning building  B35301
> Generating geometry for building B35334
> burning building  B35334
> Generating geometry for building B35351
> burning building  B35351
> Generating geometry for building B35356
> burning building  B35356
> Generating geometry for building B35383
> burning building  B35383
> Generating geometry for building B35386
> burning building  B35386
> Generating geometry for building B35451
> burning building  B35451
> Generating geometry for building B35454
> burning building  B35454
> Generating geometry for building B35457
> burning building  B35457
> Generating geometry for building B35480
> burning building  B35480
> Generating geometry for building B35489
> burning building  B35489
> Generating geometry for building B35492
> burning building  B35492
> Generating geometry for building B35502
> burning building  B35502
> Generating geometry for building B35543
> burning building  B35543
> Generating geometry for building B35550
> burning building  B35550
> Generating geometry for building B35556
> burning building  B35556
> Generating geometry for building B35561
> burning building  B35561
> Generating geometry for building B35565
> burning building  B35565
> Generating geometry for building B35583
> burning building  B35583
> Generating geometry for building B35584
> burning building  B35584
> Generating geometry for building B35590
> burning building  B35590
> Generating geometry for building B35610
> burning building  B35610
> Generating geometry for building B35611
> burning building  B35611
> Generating geometry for building B35616
> burning building  B35616
> Generating geometry for building B35619
> burning building  B35619
> Generating geometry for building B35631
> burning building  B35631
> Generating geometry for building B35640
> burning building  B35640
> Generating geometry for building B35650
> burning building  B35650
> Generating geometry for building B35654
> burning building  B35654
> Process Process-9:
> Traceback (most recent call last):
>   File "C:\CityEnergyAnalyst17\Dependencies\Python\lib\multiprocessing\process.py", line 267, in _bootstrap
>     self.run()
>   File "C:\CityEnergyAnalyst17\Dependencies\Python\lib\multiprocessing\process.py", line 114, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\CityEnergyAnalyst17\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\tools\worker.py", line 19, in run_script
>     script(**kwargs)
>   File "C:\CityEnergyAnalyst17\Dependencies\Python\lib\site-packages\cea\api.py", line 28, in script_runner
>     script_module.main(config)
>   File "C:\CityEnergyAnalyst17\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\radiation_main.py", line 195, in main
>     config)
>   File "C:\CityEnergyAnalyst17\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\geometry_generator.py", line 402, in geometry_main
>     height_col='height_ag', nfloor_col="floors_ag")
>   File "C:\CityEnergyAnalyst17\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\geometry_generator.py", line 187, in building2d23d
>     building_solid = calc_solid(face_footprint, range_floors, flr2flr_height, config)
>   File "C:\CityEnergyAnalyst17\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\geometry_generator.py", line 321, in calc_solid
>     vertical_shell = construct.make_loft(moved_face_list)
>   File "C:\CityEnergyAnalyst17\Dependencies\Python\lib\site-packages\py4design\py3dmodel\construct.py", line 1175, in make_loft
>     loft = Construct.make_loft(wire_list, ruled = rule_face, tolerance = tolerance )
>   File "C:\CityEnergyAnalyst17\Dependencies\Python\lib\site-packages\py4design\py3dmodel\OCCUtils\Construct.py", line 422, in make_loft
>     sections.Build()
> RuntimeError: Standard_ConstructionError

**Comment by daren-thomas** [comment]
@TheoBreidenstein this seems to be a problem with building  `B35654`. Could you check that geometry please? What does the footprint look like?

**Comment by TheoBreidenstein** [comment]
@daren-thomas thank you for your precise answer. Actually, building `B35654` is in the district but not in the zone. Its floor_ag and height_ag was both 0. That is why it didn't work. I try to change the building saying floor_ag=1 and height_ag=4. The simulation tool ran well.

This data come from the city council. It is possible that there is some outliers in the database.

**Comment by daren-thomas** [comment]
i guess that means the building is below-ground only. like an underground park space or something. since the district is used for radiation analysis and a below-ground building wouldn't cast a shadow it could also be deleted. that is, unless the data is just incorrect. i guess you need to find that out for each specific case.
