### ISSUE TITLE
Tables should be a link in the plots (do not visualize them)

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2156]
So plots have some tables. However, it would be better to include a button on the top right of every plot that takes me to this table (like a pop-up or a new screen)

It is rather difficult to use them like they are.

@daren-thomas would you mind creating a class and a structure to handle this event? thanks!

**Comment by daren-thomas** [comment]
@JIMENOFONSECA the plotting system already handles this - it is a purely front-end matter :)

**Comment by JIMENOFONSECA** [comment]
cool, should we implement it straight away?

________________________________

**Comment by reyery** [comment]
I can implement this since I'm working on the dashboard plot layout.
