### ISSUE TITLE
cea dashboard v2.18 create new project

### ISSUE THREAD

**Issue by liaochenxi** [architecture-building-systems/CityEnergyAnalyst#2167]
hello, i just downloaded the latest version cea dashboard v2.18, when i am trying to create a new project, i have several problems. The first one is when i click the button, im not able to select a path.
(<img width="401" alt="image" src="https://user-images.githubusercontent.com/37850333/61389990-33ec0500-a8ba-11e9-92c3-a04e711dfbbd.png">)
The second one is when generate the input files, its always saying saving configuration never to be saved.
<img width="515" alt="image" src="https://user-images.githubusercontent.com/37850333/61390251-b248a700-a8ba-11e9-8c97-14837af1dc47.png">
I wonder whether its a problem related to my installation. But i didnt change any default setting.

Looking forward to your reply.

**Comment by daren-thomas** [comment]
@liaochenxi could you please specify what browser you are using?

**Comment by liaochenxi** [comment]
> @liaochenxi could you please specify what browser you are using?
hello, im using IE 11

**Comment by liaochenxi** [comment]
@daren-thomas I’m using IE 11

**Comment by daren-thomas** [comment]
@liaochenxi we should probably add this to the known issues: I think the dashboard doesn't really work with Internet Explorer. We test on Chrome and Firefox. Is it possible for you to use one of those?

**Comment by liaochenxi** [comment]
@daren-thomas Thanks for your reply. I tried both Chrome and Firefox, now I'm able to save configurations. But when i tried to import my own input files, with neither Chrome nor Firefox, I cannot select the path of input files.

**Comment by liaochenxi** [comment]
fixed by restarting the laptop..
