### ISSUE TITLE
Add REST API to Dashboard for locating stuff

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2168]
Examples:

- GET http://localhost:5000/locator/get_zone_geometry/<project>/<baseline>
- GET http://localhost:5000/locator/get_weather/<project>/<baseline>
- POST http://localhost:5000/locator/get_total_demand/<project>/<baseline>

This would assume the dashboard is configured with a default project location (I suggest `C:\User\<user>\Documents\CityEnergyAnalyst\projects`) on Windows, i.e. a new parameter `{dashboard:projects-root}`.

Motivation:

Assume a `cea-worker`  script, launched with script-name and a dictionary of parameters - similar to how `cea` works. This script would, in addition, have a URL (in this case `http://localhost:5000`) pointing to the CEA Dashboard instance (our "cea-server"). `cea-worker` uses the `schemas.yml` file to figure out which input files to download via GET from the server, creating a temporary/partial scenario, and then runs the script. Using `schemas.yml` again, it POSTs all output files to the cea-server/CEA Dashboard.

This is the quickest solution I can think of to make cea scripts run on a remote computer with access to scenario files without creating a whole database and stuff. Even though... the database and stuff would not be a bad idea...

Using https://serveo.net/, (should work with the `ssh` client already prebuilt into the CEA Windows Installer), we could easily create a Euler implementation of `cea-worker`. We'd still need to figure out the `cea-server` part (splitting up certain scripts into smaller pieces, keeping track of jobs)

**Comment by daren-thomas** [comment]
A lot of this is already implemented with cea-worker... the whole InputLocator situation needs to be revisited. But... I think this would be more cleanly done by moving the scripts away from reading/writing files and reading/writing DataFrames instead.  The problem is, this would require changing every single script... We might actually never get around to doing this.

So the solution presented here is the next best thing...

**Comment by JIMENOFONSECA** [comment]
so we close this for now.....moving away from reading/writing files will not be pursued anytime soon...

**Comment by daren-thomas** [comment]
@JIMENOFONSECA does this mean we're abandoning a cloud version?

**Comment by JIMENOFONSECA** [comment]
Well still we can use containers right? we could create a wrapper for the inputlocator so it sends  and stores data in any particular format we furthermore require. But I may be missing a to of ground knowledge in here.
On 4 Nov 2019, 8:16 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> does this mean we're abandoning a cloud version?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA the reading / writing of files / dataframes is not solved by containers. Containers solve the problem of how to _deploy_ cea-worker instances. The stuff they're working on still has to be somewhere. So this issue _is_ about the wrapper for the InputLocator you're envisioning here.
