### ISSUE TITLE
Manage Dashboards page should use links

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2170]
The Actions column in the Manage Dashboards page (`http://localhost:5050/plots/dashboard/manage`) has three options (Open, Rename, Delete):

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/7623db95-d787-4b0e-85de-ac6da9438669)

I was expecting to be able to click on a row in that table and have it open up the dashboard (we don't need the `Open` action).

The actions are weirdly spaced so that it's hard to identify them as separate actions - either icons or buttons would work better.

**Comment by daren-thomas** [comment]
I guess this can be done as part of the react-ification.

**Comment by reyery** [comment]
There's currently no **Manage Dashboards** page in the electron application, since I not too sure if it is still useful. We could add it in eventually, however I don't think it is relevant now.
