### ISSUE TITLE
Fix margins inside plotly

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2174]
Hi Daren, 

would you mind helping us to fix the margins inside the plotly diagrams? I think that is a property of the layout of each plot. Maybe some property that can be put into Plotbase?

See how the plots get squeezed due to big margins (the white area around each plot) by default in plotly.

![image](https://user-images.githubusercontent.com/8973186/61510424-5a7a7f00-aa25-11e9-9dea-f118c3a84b4b.png)

**Comment by reyery** [comment]
Is it possible to update the `plotly` module for python to the latest version? The new version exports the plot divs as 'reactive' so that it fits itself to the size of the container even when resizing the window. It also allows us to export the plots as `JSON`, which could be useful since the javascript `plotly` library could just use it to plot straight to the DOM.

**Comment by JIMENOFONSECA** [comment]
Yes, let’s do it, daren will have to just upload a new installer and change the environmnet.yml

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 19 Jul 2019, 16:39 +0800, Reynold Mok <notifications@github.com>, wrote:

Is it possible to update the plotly module for python to the latest version? The new version exports the plot divs as 'reactive' so that it fits itself to the size of the container even when resizing the window. It also allows us to export the plots as JSON, which could be useful since the javascript plotly library could just use it to plot straight to the DOM.

**Comment by daren-thomas** [comment]
I'm not sure if we can upgrade. I'll check that. first, it would be good to have the status quo of the plots converted. Before changing everything again. Otherwise we'll never finish.

**Comment by JIMENOFONSECA** [comment]
Alright, let’s start the conversion in a branch.  and tell me what to do with the next plots of the optimization

Jimeno
On 19 Jul 2019, 7:20 PM +0800, Daren Thomas <notifications@github.com>, wrote:

I'm not sure if we can upgrade. I'll check that. first, it would be good to have the status quo of the plots converted. Before changing everything again. Otherwise we'll never finish.

**Comment by reyery** [comment]
@JIMENOFONSECA has fixed this PR #2225
