### ISSUE TITLE
Clarify main-use determination of buildings with exactly equal use mix

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2175]
How is this currently done?
At least there should be some message output to the user. E.g.,
"Main use for B001 with an equal share of OFFICE and MULTI_RES determined to be MULTI_RES. Change occupancy slightly to override default behavior."
Or something like this.

Or, maybe let the user define the main use.

See #2159

**Comment by daren-thomas** [comment]
@gabriel-happle what does the main-use specify that isn't part of the mixed-use schedules?

**Comment by gabriel-happle** [comment]
@daren-thomas the main-use determines all kinds of building model parameters (i.e., which archetype is applied).

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro would you mind making the message? I think you know about the schedules more than any by now.

Just the message will be enough

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA check out PR #2339
