### ISSUE TITLE
unable to launch dashboard

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2180]
this is the error i encountered: 
@daren-thomas , @reyery any clue?
![image](https://user-images.githubusercontent.com/16998305/61525497-22863280-aa4b-11e9-9297-ee800ae36d53.png)

**Comment by reyery** [comment]
The script `annual_costs.py` does not exist in the `master` branch, I think you might have reinstalled CEA while on another branch. Maybe try reinstalling it while in `master`.

**Comment by daren-thomas** [comment]
@shanshanhsieh I got that too. What seems to have happened is that your project directory still has `*.pyc` files left over from when you were testing the optimization branch.

In PyCharm, right-click the `cea` folder and choose "Clear Python compiled files". That should do the trick!

**Comment by reyery** [comment]
@daren-thomas oh didn't know PyCharm could do that. So I'm guessing when running the dashboard, it did not recompile and just ran it from the `*.pyc` files?

**Comment by daren-thomas** [comment]
yes. exactly.

**Comment by reyery** [comment]
oh i see. I have tested it and it seems to have worked.
