### ISSUE TITLE
Refactor and clean up BuildingProperties

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2184]
This could be one of the future steps in streamlining the demand simulation workflow.
Based on discussions with @daren-thomas, the following steps could be done:
- refactoring
- moving calculations to the demand script instead of saving values
- reading the solar heat gains on the go, when needed in the demand calculation instead of storing them in memory
- saving building model files do disc 
- ...

**Comment by daren-thomas** [comment]
@gabriel-happle this is kind of vague and looks more like an epic. What are concrete steps you'd like to perform here? Please create an issue for each one.
