### ISSUE TITLE
create one or more `schedule maker` tools

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2185]
This is connected to #2182
After the CEA is able to read individual building schedules, we will create multiple tools within CEA to create those schedules.
The first one will be `create archetype schedules`, which is basically the conversion of the `occupancy_model.schedule_maker` function to an executable script.

Assigning @martin-mosteiro to this, so that he can track what is happening here.

**Comment by JIMENOFONSECA** [comment]
done in PR #2382
