### ISSUE TITLE
Remove suppression of warnings and resolve the warnings instead

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2186]
We have code like this (found in optimization branch):

```
import warnings
warnings.filterwarnings("ignore")
```

This issue is about tracking down all instances of this pattern and checking to see if the warnings can be resolved. If they really can't, then add a comment to explain which warnings are being suppressed and why. It might even be possible to selectively only filter those warnings - and allow other, new warnings we don't know about yet to bubble up as exceptions!

**Comment by JIMENOFONSECA** [comment]
correct, the best way to check for this is to run it without warnings first. It seems there are some related to scipy.... I cannot remember well
