### ISSUE TITLE
Refactor branching on network-type in optimization code (and other places)

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2187]
We have a lot of code that is broken up into sections of 

```
if network_type == "DH":
   do_stuff_for_dh()
if network_type == "DC":
   do_stuff_for_dc()
```

This often happens in very long functions that should be refactored with "extract method" anyway to make the high-level structure (what) more clear.

At the same time, `do_stuff_for_dh/dc()` could be refactored to extract the varying parts. A typical way to do this with OO would be to have an object (something like `network_helper`?) that encapsulates calculations specific to the network type, so we'd have:

```
class NetworkHelper(object):
   pass
class DistrictHeatingHelper(NetworkHelper):
   some_method_a()
   some_method_b()
class DistrictCoolingHelper(NetworkHelper):
   some_method_a()
   some_method_b()

def do_something(network_helper):
   this_is_the_same_for_both()
   xyz = network_helper.some_method_a()
   this_is_the_same_too(xyz)
```

In fact, we could even go so far as encapsulating everything in a `Network` class and having `DistrictHeatingNetwork` and `DistrictCoolingNetwork` specialize the differing parts...

**Comment by JIMENOFONSECA** [comment]
Hopefully we can tackle this issue once we have the mini-refactoring ready
