### ISSUE TITLE
Make sure we're using the print function as opposed to print statement everywhere

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2188]
This is one of the first steps towards Python 3 compatibility. At the same time, use `str.format()` instead of string concatenation.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas can you assign a milestone, label, and developer? thanks

**Comment by JIMENOFONSECA** [comment]
won't happen any time soon... closing
