### ISSUE TITLE
Plots in the row template do not have same functionality

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2190]
So in the "rows" tempalate" the button of "changing plot" does not exist

**Comment by daren-thomas** [comment]
![image](https://user-images.githubusercontent.com/2969564/61623272-96585300-ac76-11e9-93e2-5b9f356ac824.png)

I think @JIMENOFONSECA means the icon on the left in this screenshot. This should be a simple change.
