### ISSUE TITLE
Clicking on a plot's name takes me to a single view of the plot

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2192]
So when we click on the plot's name it takes me to a bigger version of the plot in the same window. This makes difficult to work and come back to where i was working.

The functionality whould be different:

If the user clicks on the plot's name, it should open a new window and take her to a single "big" view of the plot. (it can be the html version of it).  It is not necessary that the plot opens inside teh CEA dashboard...

**Comment by daren-thomas** [comment]
That's not the only solution to this usability bug: We could also display a link "back to dashboard {dashboard name}".

What problems are you trying to solve _exactly_? I'm not a big fan of opening a new window. But I _am_ open to convincing arguments.

The display necessarily _has_ to happen as part of the "dashboard" in the sense that it has to be a URL passing through our flask server, as the "html" version of the plots don't really exist - they're created on-the-fly in the flask server.

**Comment by JIMENOFONSECA** [comment]
got it.

So the main argument:

1. for the user it is just a hassle to come back and reload the entire CEA once she goes into the plot
2. the user wants to see the plot BIG (the entire webpage). like we used to see them before the dashboard.
3. a BIG and separate window leaves more room for exploration. the user can open several and see them in a BIG screen or save them.

would that work?


On 22 Jul 2019, 5:45 PM +0800, Daren Thomas <notifications@github.com>, wrote:

That's not the only solution to this usability bug: We could also display a link "back to dashboard {dashboard name}".

What problems are you trying to solve exactly? I'm not a big fan of opening a new window. But I am open to convincing arguments.

The display necessarily has to happen as part of the "dashboard" in the sense that it has to be a URL passing through our flask server, as the "html" version of the plots don't really exist - they're created on-the-fly in the flask server.

**Comment by reyery** [comment]
would not be issue if moved to electron

**Comment by daren-thomas** [comment]
@reyery how _exactly_ would the move to electron address this issue?

**Comment by daren-thomas** [comment]
Status update: #2288 (FEATURE: New React Dashboard) removed the link in the plot title.
