### ISSUE TITLE
Remove naming.csv

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2200]
The naming.csv file, as I understand, has been superseded by the glossary.csv file. We can remove it if we are careful:

- remove `cea.inputlocator.InputLocator#get_naming`
- update `cea/plots/variable_naming.py`
  - use the `glossary.csv` file as input. make sure the interface stays the same (for now)
- remove/update/fix `cea.utilities.doc_update_naming.main`

**Comment by JIMENOFONSECA** [comment]
we are using several variables in the plots, to 1. name them and 2. give them colors..

**Comment by daren-thomas** [comment]
@JIMENOFONSECA yes, I know, but that data is also inside the `glossary.csv` file - so it's redundant and editing `cea.plots.naming` to use `glossary.csv` should be a small change.

**Comment by JIMENOFONSECA** [comment]
Alright let’s do it.

I added some lines recently to naming.csv for the optimization and supply systems plots.

I hope we do not for get them...

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 24 Jul 2019, 22:05 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> yes, I know, but that data is also inside the glossary.csv file - so it's redundant and editing cea.plots.naming to use glossary.csv should be a small change.

**Comment by daren-thomas** [comment]
The Jupyter notebook in `2200-remove-naming-csv` is an attempt at checking for consistency in the naming.csv and glossary.csv files (also, to make sure we don't forget anything when removing naming.csv).

It's showing up some problems, for instance the variable "Excavation" has two different descriptions, depending on which worksheet (`lca_buildings.xlsx:EMBODIED_EMISSIONS` vs. `lca_buildings.xlsx:EMBODIED_ENERGY`) is used. I'm wondering: should we make these unique?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I checked and it's not as easy as I believed it would be. Mainly because of how the unique constraints in `naming.csv` are not met in `glossary.csv`.

If you want, you can look into [the notebook I started for this](https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/2200-remove-naming-csv/notebooks/2200-remove-naming-csv.ipynb).

I tried to update the `glossary.csv` with the data from PR #2530, but that then adds a lot of "TODO" items, replacing info we already entered.

I suggest we close this issue and move on - sometimes,

> Although practicality beats purity.
> -- The Zen of Python, by Tim Peters
