### ISSUE TITLE
plot basic and electrical network layout error

### ISSUE THREAD

**Issue by liaochenxi** [architecture-building-systems/CityEnergyAnalyst#2201]
Hello, I have already got the csv files of solar radiation and energy demand, but when i was using plot basic, I got the following error. <img width="770" alt="image" src="https://user-images.githubusercontent.com/37850333/61722316-5a9eb580-ad6a-11e9-90cb-e45b4f9486aa.png">
It seems that its related to the plant node, then i run the thermal network layout. For DC and DH, there is no problem. I got edges and nodes. But for EL, electrical network, here comes the error, UnboundLocalError: local variable 'field' referenced before assignment.
<img width="674" alt="image" src="https://user-images.githubusercontent.com/37850333/61722985-8ff7d300-ad6b-11e9-987f-abe020c10db5.png">
I'm thinking is there something i forgot to do before running the simulation? Looking forward to your reply.

**Comment by JIMENOFONSECA** [comment]
@liaochenxi sorry for the late response. Kindly check out the new version of CEA, released yesterday. It includes a dashboard tab where you can create all the plots one by one as desired.

Let me know if the error is persistent in the new script
