### ISSUE TITLE
Schedule of temperature set-points for CEA

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2204]
The heating and cooling set points are controlled as follows:
```
def get_heating_system_set_point(people, t, bpr, weekday):
    """
    :param people:
    :param t: hour of the year, simulation time step [0...HOURS_IN_YEAR]
    :type t: int
    :param bpr: BuildingPropertiesRow
    :type bpr: cea.demand.building_properties.BuildingPropertiesRow
    :param weekday:
    :return: heating system set point temperature [°C]
    :rtype: double
    """

    if is_heating_season(t, bpr):

        if people == 0:
            if 5 <= weekday <= 6:  # system is off on the weekend
                return np.nan  # huge so the system will be off
            else:
                return bpr.comfort['Ths_setb_C']
        else:
            return bpr.comfort['Ths_set_C']
    else:
        return np.nan  # huge so the system will be off
```

This means that if a building is occupied 7 days a week, the heating/cooling systems will be turned off when people aren't there on Saturdays and Sundays. This doesn't seem very realistic – why would a building that is occupied 7 days a week treat a Sunday differently from a Monday?

This leads to results like these:
<img width="940" alt="Screen Shot 2019-07-24 at 11 46 14" src="https://user-images.githubusercontent.com/18548065/61783889-f0891d80-ae08-11e9-9161-d837e98b5767.png">
(the golden line is measured data, the other lines are different simulations using CEA)

Me and @gabriel-happle discussed this and we think whether a system is on or not on weekends should be an input parameter – either a simple input (something like `type_cs`) or a temperature setpoint schedule – I believe @BhargavaKrishnaSreepathi worked on this at one point.

**Comment by gabriel-happle** [comment]
I think temperature set-point schedules is a good idea. We should add it to the schedules file so that the user has more control.

Actually, I'm reviewing a paper on this topic right now.
It states ISO 13790 standard as source and gives a schedule like this for residential:
07:00 - 17:00  :  16°C
17:00 - 23:00  :  21°C
23:00 - 07:00  :  18°C

If we want to allow this kind of input, we should define 24-h schedules with temperatures directly.
Not only set-point and set-back times.

**Comment by JIMENOFONSECA** [comment]
just include a new variable in the inputs/indoor-comfort, saying whether the weekend operation is allowed or not and then update the code accordingly....

**Comment by daren-thomas** [comment]
@JIMENOFONSECA separating out the schedule logic from the actual simulation should be the way to go - adding conditional logic just makes things more complex. Instead, the code that creates the schedules could add the new variable you mention - plus, users could provide their own schedules, maybe based on measured data.

**Comment by martin-mosteiro** [comment]
Now that I've seen how the new schedule maker works, I think it makes sense to have the temperature as an additional schedule, but it also makes sense to have an input parameter that defines whether the systems should be off on weekends or not. So it'd be something like:
1. Set `config.demand.are_systems_off_on_weekends` (True / False)
2. Run schedule maker
3. The resulting schedules would then contain a set point temperature column that would or would not include weekends.
The user could then adjust these schedules on a building-by-building basis.

**Comment by gabriel-happle** [comment]
@martin-mosteiro actually, the system control should be able to detect temperatures of `np.nan` as systems are `off`. We just have to check how to process inputs from csv correctly...

I'm writing this because I'm a bit confused by your point 3.

**Comment by JIMENOFONSECA** [comment]
I believe this is implemented already. Check the flag: use user temperatures of the demand script.

Bhargava created this to use the outputs of a model predictive control which defines the optimal setpoints of buildings

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 25 Aug 2019, 20:34 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

Now that I've seen how the new schedule maker works, I think it makes sense to have the temperature as an additional schedule, but it also makes sense to have an input parameter that defines whether the systems should be off on weekends or not. So it'd be something like:

  1.  Set config.demand.are_systems_off_on_weekends (True / False)
  2.  Run schedule maker
  3.  The resulting schedules would then contain a set point temperature column that would or would not include weekends.
The user could then adjust these schedules on a building-by-building basis.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle @martin-mosteiro @daren-thomas 

I believe we should get a solution to this issue soon. I was visiting Energy Plus and Design-Builder with Luis (one of our users). The solution might be quite simple and it is related to adding a schedule of air-conditioning and natural ventilation. 

It can be added to the excel file we already have for each type of occupancy (in occupancy_schedules.xls). We need to start implementing it. @gabriel-happle are you in to do this together next week?, maybe we prepare a plan and show it to martin? @martin-mosteiro are you available next week?

**Comment by martin-mosteiro** [comment]
Agreed, this should be fixed. @JIMENOFONSECA I'm available for discussion next week.

Today, @prakharmehta95 and I tested simply adding a boolean (`systems_on_on_weekends`) that would define whether the systems should be off over the weekend or not. This is a simple solution that however only allows the systems to be on or off for  all buildings with no weekend occupants (i.e., no diversity between buildings).

The air conditioning schedules would also make sense, but (a) do we have access to such schedules for every building occupancy type?, and (b) that would mean that for example every building of a given occupancy type would have the same schedule (i.e., no diversity between buildings with the same occupancy type).

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA what is a schedule of air-conditioning?
I believe, what we should implement are the set-point temperatures directly as mentioned above.
The schedule of natural ventilation should be easy to implement.

**Comment by lguilhermers** [comment]
As for natural ventilation, there is also a general schedule, similarly to mechanical ventilation, which for most of the cases should be the same as the occupancy (and is also loaded as the occupancy schedule by default).

An interesting control I found for natural ventilation is this set of rules:
 "Note that when using the Calculated natural ventilation model option windows and vents are only opened when:
- The inside air temperature is above this cooling setpoint temperature, and
- The inside air temperature is greater than the outside air temperature, and
- The operation schedule allows ventilation."
Which seems very reasonable compared to a real behavior of opening windows.

More here:
https://designbuilder.co.uk/helpv6.0/Content/_Environmental_comfort.htm (Ventilation Setpoint Temperatures)

**Comment by gabriel-happle** [comment]
Hi @lguilhermers, well I kind of disagree with the "reasonability". Those are just assumptions.
Currently, the opening of windows in CEA is related to the required fresh air supply, irrespective of any temperatures. 
What you are describing is a mode of increasing ventilation rates for "natural cooling".

**Comment by lguilhermers** [comment]
Hi @gabriel-happle,
I agree with the controls of fresh air, Design Builder also has requirements for those. As I said, this is one model for calculated natural ventilation which is particularly interesting to me. Although being just assumptions (those models are based on many assumptions anyway), they can prevent a non-natural behavior of opening windows, for example when it is too cold or too hot.
This may just be an additional layer you might consider for the future. Or not, if the developers consider is too much detail for a high level BEM. But I thought was worth sharing if natural ventilation is intended to be explored for passive design.
Right now my models for residential buildings in Singapore based mostly on defaults are estimating a much higher consumption than metered values. This can also be due to the fact that Singaporeans are more willing to use natural ventilation beyond only the fresh air requirements.

**Comment by JIMENOFONSECA** [comment]
After a conversation with @gabriel-happle and @lguilhermers we decided to give it a try to:

1. Create a schedule for setpoints for heating and cooling
2. Connect that schedule to CEA
3. test against data in Singapore.

@lguilhermers will do 1, @gabriel-happle will then do 2. @lguilhermers and myself will do the testing.

**Comment by gabriel-happle** [comment]
@lguilhermers this runs an is ready to be tested.
Please check branch https://github.com/architecture-building-systems/CityEnergyAnalyst/tree/i2204-temperature-setpoints

**Comment by gabriel-happle** [comment]
For most of the buildings, changes don't affect much.
It seems that some setpoints were changed when updating the databases.
![image](https://user-images.githubusercontent.com/17002288/66201253-8547ab80-e6d5-11e9-8fc3-bdb3496db7c3.png)

**Comment by martin-mosteiro** [comment]
>  It seems that some setpoints were changed when updating the databases.

Yes, that is the case. The temperatures were all set to SIA 2024 (2015). So are the changes observed before mainly due to the changes in the databases?

**Comment by gabriel-happle** [comment]
@martin-mosteiro there are three changes visible here:
1) the systems are not `off` anymore on weekends
2) some systems have been changed to have a set-back in the morning and evening (new temperature schedules)
3) some changes of the database by an earlier PR might not be part of the reference-case-open yet

We can try to replicate the old behavior with the new databases.

**Comment by gabriel-happle** [comment]
Trying to get same heating energy demand of `B03` mainuse `GYM` as previously.

new setpoints:
![image](https://user-images.githubusercontent.com/17002288/66201949-28e58b80-e6d7-11e9-8d26-74dc9e256952.png)

old setpoints emulated with schedule:
![image](https://user-images.githubusercontent.com/17002288/66202485-70b8e280-e6d8-11e9-8da2-311d478e051f.png)

![image](https://user-images.githubusercontent.com/17002288/66202349-1455c300-e6d8-11e9-9598-7201ddd7a06f.png)
![image](https://user-images.githubusercontent.com/17002288/66202783-2d12a880-e6d9-11e9-8a5c-3de138af6c1c.png)

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA should this be a PR now?
Then I have to update the test data according to the new temperature set point schedules.

**Comment by gabriel-happle** [comment]
OK. It was decided with @JIMENOFONSECA to make this change part of the CEA.
I'm therefore updating the tests and submitting a PR
