### ISSUE TITLE
Input editor map will not initialize if district does not exist

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2208]
If the user only creates/has `zone` and not `district` buildings, the map will not initialize with buttons and only show the zoomed out map.

**Comment by daren-thomas** [comment]
What is the expected behavior instead?

**Comment by reyery** [comment]
hmmm.. I was thinking of just showing the zone buildings even without the district buildings. But since district buildings are needed for simulations, maybe there should be some sort of warning also, to let the users know.
