### ISSUE TITLE
Default script category showing up in Dashboard navigation

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2210]
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/d6c63253-35e1-4706-923d-7d19ca9853af)

Notice the "default" link under "Data Management". That shouldn't be there. It currently contains the plots scripts - I think what happened was, they were moved there from "Visualization" without the `interfaces` property being updated. So, if we are going to remove them from the Dashboard, let's just remove `dashboard` from the list of interfaces supported by those scripts...

**Comment by reyery** [comment]
I'm on `master` and I don't see the default category in the side navigation bar. I remember that it was taken out in PR #2203.

**Comment by JIMENOFONSECA** [comment]
yep, that was fixed then..
