### ISSUE TITLE
When the occupancy is changed in the interface, a message has to be displayed to run the data-helper

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2233]
When changing the occupancy in the input editor, changes are not reflected in the other building properties. Therefore, a warning message should be displayed to the user, reminding him to re-run the data helper.
For this case, the data-helper should be executed only for a single building in order to not affect changes that the user made to other buildings. See #2234  for this.

This issue lead to a lot of confusion, see #2230 and #2231.

**Comment by JIMENOFONSECA** [comment]
@reyery would you mind taking a look at this?
