### ISSUE TITLE
Change folder structure of saving and loading schedules

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2235]
With PR #2230 schedule files are read from `input/building-properties` and saved to `output/data/demand`. This change is necessary so that changes in occupancy or other building properties will be applied to the schedule-maker. See #2229 

In the future, a more intuitive folder structure should be used.
This is related to #2185, #2184 and #2183

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle  can you assign a milestone, label, and developer? thanks

**Comment by daren-thomas** [comment]
@martin-mosteiro @gabriel-happle how is this connected to the PR #2302 (Add script to create occupant schedules from MATSim population)?

**Comment by martin-mosteiro** [comment]
I did some minor folder reorganization as part of the MATSim schedule implementation. Might solve this issue or not – up to Gabriel (the creator of this issue and reviewer assigned to PR #2302) to decide.
