### ISSUE TITLE
Default values for network-type are not consistent

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2244]
Some parameters use DH, some DC as the default network-type value.

This can lead to subtle errors.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas can you assign a milestone, label, and developer? thanks

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I thought that was supposed to be done in the planning meeting?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas well the best is that you suggest one, then I check and move to breakdown accordingly.... what do you think?
