### ISSUE TITLE
Replace pydoit with cea workflow for testing the scripts

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2245]
We currently use the pydoit library (see `cea.tests.dodo`) for the testing of the cea in the Jenkins. It's complicated - there is some history with different reference cases, etc. - and not all the scripts are tested.

Instead, we could wire up the heating-case workflow and the cooling-case workflow. We can add some semantics to `cea workflow` yaml files to understand some basic tests (compare files, compute some statistics, run unit tests) and create a test-workflow that does both heating and cooling, one after the other.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas can you assign a milestone, label, and developer? thanks

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I'm not sure this is really a "Must have". Instead, we should have a window in which we run these workflows - preferably a time where the Jenkins isn't busy.
