### ISSUE TITLE
CREATE Symposium poster on CEA

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CityEnergyAnalyst#2254]
As stated in the title. Submission date 15 OCT 19.

**Comment by shizhongming** [comment]
Having the framework of the poster introducing CEA here. It follows the CEA color theme, introduces the users, functions, advantages, platforms, and the key dates of the tool for the main sections, as well as the impacts of CEA on the bottom. Please comment. :) Then, I will send it to the PR group of FCL for approval. Thanks!
![MuSES_poster_2019_v1](https://user-images.githubusercontent.com/16640327/66112117-d5067400-e5fc-11e9-90f6-23aa21d35599.png)

**Comment by shizhongming** [comment]
@JIMENOFONSECA  Please have a look at the second version of the poster. Let me know when you have time to sit down together again.

![MuSES_poster_2019_v2-01](https://user-images.githubusercontent.com/16640327/66188072-f9278b00-e6b8-11e9-8540-bc8d8437c637.png)

**Comment by JIMENOFONSECA** [comment]
Thanks for this. Maybe we change the pic of CEA under HOW? the previous screenshot will do better than this one.



On 4 Oct 2019, 3:09 PM +0800, Zhongming Shi <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> Please have a look at the second version of the poster. Let me know when you have time to sit down together again.

[MuSES_poster_2019_v2-01]<https://user-images.githubusercontent.com/16640327/66188072-f9278b00-e6b8-11e9-8540-bc8d8437c637.png>
