### ISSUE TITLE
decentralized script fails in cli, dashboard, workflow

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2256]
The decentralized script fails because the parameter `{data-helper:region}` is not configured for this script. Which is correct: It shouldn't be configured for that script.

The problem can be traced back to `cea.optimization.preprocessing.decentralized_building_main.disconnected_building_main`, line 38ff:

```
    if (buildings_name_with_heating != [] and config.data_helper.region != 'SG'): 
        #FIXME: temporal fix to avoid heating calculation in SG
        decentralized_buildings_heating.disconnected_buildings_heating_main(locator, total_demand,
                                                                            buildings_name_with_heating,
                                                                            config, prices, lca)
```

This is a bug, anyway, as region `SG` should not be used to test whether heating is necessary or not.

I'm not the domain expert here, but my hunch is, heating should only be done for buildings that have a heating system? Is there a way to test for that? I'm pretty sure there has to be, right?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh I beleive you integrated this change right? can you remind us the rationality please?

**Comment by shanshanhsieh** [comment]
changed to checking if the no space heating systems are installed (T0)
