### ISSUE TITLE
glossary update and proof

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#2260]
In my journey through most of the databases in cea, i am coming up with a few variables which i struggle to define. If you could please take the time to fill in these (don't worry about grammar/spelling, just try to convey the best you can), i would be more than happy to proof/reword and insert into the glossary.

need the description and units for these:

electrical_networks.xlsx

r_ohm_per_km
x_ohm_per_km
z_ohm_per_km
b_sh_s_per_km
S_max_MVA
C_microF_per_km
l_mH_per_km
y_ohm_per_km
g_s_per_km
b_s_per_km
I_max_A
price_sgd_per_m
lifetime_a
om_factor
sub_price_sgd_per_kva
build_price_sgd_per_kva

supply_systems.xls:PV
PV_th
PV_n
PV_noct
PV_Bref
PV_a0
PV_a1
PV_a2
PV_a3
PV_a4
misc_losses

supply_systems.xls:SC
aperture_area_ratio
n0
c1
c2
mB0_r
mB_max_r
mB_min_r
C_eff
t_max
IAM_d
dP1
dP2
dP3
dP4
Cp_fluid

supply_systems.xls:HEX
a_p
b_p
c_p
d_p
e_p

supply_systems.xls:Absorption_chiller
el_W
s_e
r_e
s_g
r_g
a_e
e_e
a_g
e_g
m_cw
m_hw

many thanks!

**Comment by BharathSeshadri** [comment]
@Jack-Hawthorne  I have no clue about cea. Jimeno/Shan Shan will know. If you have Qs about the heat- and mass- transfer calculations for the thermal systems, I can help

**Comment by Jack-Hawthorne** [comment]
@BharathSeshadri sorry! i tagged the wrong person in this one. thanks for responding ;)

**Comment by Jack-Hawthorne** [comment]
@JIMENOFONSECA could you assign someone who knows what these variables are?

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne I believe this is a duplicate issue? I remember giving this information already?
