### ISSUE TITLE
update systems input database schema

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#2263]
I assume supply_systems.xls is mainly used for LCC and sometimes (but not always) storing constraint variables related to supply system sizing.

why are they separated by sheets when they generally have all the same variables and primary keys (the `code` attribute):

- Description
- code
- currency
- a (and variants of)
- b (and variants of)
- c (and variants of)
- d (and variants of)
- e (and variants of)
- LT_yr
- O&M_%
- IR_%
- assumption

this^ could be merged in one sheet (potentially named 'LCC')

the other variables pertaining to size and dimension constraints could be in another (such as 'dim_and_pwr_constraints'):

- Description
- code
- module_length_m
- module_area_m2
- Cp_fluid
- cap_min
- cap_max
- unit
- other variables and such

this would also prevent little key errors from happening when, for example, the attribute 'unit' is accidentally 'unit ' (in the 'TES' sheet) and 'assumption' becomes 'Assumptions' (in the 'FC' tab).

**Comment by Jack-Hawthorne** [comment]
Also, do the codes for LCA_infrastructure and emission_systems match?
which are used as inputs for the supply_systems.dbf and which for technical_systems.dbf?

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne I would appreciate a PR for this.

**Comment by Jack-Hawthorne** [comment]
@JIMENOFONSECA I haven't yet investigated how all the modules use this data and how they would have to be changed following a database schema update.

The steps to achieving this might look something like this:
- Do a mock up of how it would look and send as a .txt
- Make an overview of which modules use which database for all the input databases. 
- Change the schema and update the modules accordingly.

I don't know the priority of this task. I'm working with some CEA users and sharing the frustrations some had when trying to understand which parameters influence which calculations and the overall accessibility of the databases themselves.

**Comment by JIMENOFONSECA** [comment]
Hi Jack, the best to proceed is that we meet. I can help to solve many of these questions.

I am available this week on Wednesday at 6:00pm Singapore time. Maybe you write me to my e-mail to confirm the appointment?

Skype should work.
On 23 Aug 2019, 7:54 PM +0800, Jack-Hawthorne <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> I haven't yet investigated how all the modules use this data and how they would have to be changed following a database schema update.

The steps to achieving this might look something like this:

  *   Do a mock up of how it would look and send as a .txt
  *   Make an overview of which modules use which database for all the input databases.
  *   Change the schema and update the modules accordingly.

I don't know the priority of this task. I'm working with some CEA users and sharing the frustrations some had when trying to understand which parameters influence which calculations and the overall accessibility of the databases themselves.

**Comment by Jack-Hawthorne** [comment]
so unfortunately we have somehow missed each other on both scheduled meetings. However, I have read through the code and found the BuildingProperties object which seems to answer some of my questions. I shall do my best to change up the schema, and document this object's attributes their sources (input files).

**Comment by Jack-Hawthorne** [comment]
@daren-thomas @JIMENOFONSECA 
soooooo, as i have been going through the systems input databases, I've noticed that the schema is really confusing. this is a comment from other users of CEA users too. 

It feels like a tangled mess of wires that seems to work but no one is completely sure how. the LCA is disintegrated from the supply and technologies modules hence the `type_cs` discrepancy. and information is all over the place (especially in supply_systems.xlsx) 

I have been trying to resolve this by coming up with a proposal of something which is congruent - i.e. integration of LCA analysis, costings information etc.. however this will take some time. 

please let me know if i am wasting my time here!
thanks!

**Comment by Jack-Hawthorne** [comment]
@JIMENOFONSECA @daren-thomas @martin-mosteiro please have a look at branch #2263 : `cea/databases/SG/systems` 

there are four new databases which have merged many of the sheets and conflicting sources of information. still yet to be tweaked and completely filled in but it would be nice to have some feedback.

if someone could explain what each of these temperatures is expressing that would be great (in emission_systems.xls) :

dTcs_C / dThs_C : expected temperature losses through transmission?
Ts0_scu_C / Ts0_ahu_C / Ts0_aru_C : nominal supply temperature of the heating/cooling element (isn't this related to the chiller output - conflicting sources? does a re-circulation fan have a coil in it?) 
dT0_ahu_C / dT0_aru_C : are these the temperature drops across the coils? again does an aru have coils?
T_sup_air_aru_C : isn't this the zone temperature, i.e. recirculate the air in the zone right? why is it determined here?

**Comment by shanshanhsieh** [comment]
Hi @Jack-Hawthorne , 
thanks for looking into this.
here are the answers i know:
1. dTcs_C / dThs_C : looking at the usage, i am not so sure abt what is means. maybe @gabriel-happle can explain this better. 
2. Ts0_scu_C / Ts0_ahu_C / Ts0_aru_C : nominal off-coil temperatures of the heating/cooling units. (Chiller operates according to this temperature, not the other way around. aru stands for air-recirculated units, which has a cooling coil to condition the indoor air as oppose to ahu that conditions the outdoor air. )
3. dT0_ahu_C / dT0_aru_C: hot/chilled water temperature drop/increase in the heating/cooling coil.
4. T_sup_air_aru_C: i cant find the usage of this parameter. @gabriel-happle can confirm if this is redundant.

**Comment by gabriel-happle** [comment]
- dTcs_C / dThs_C: is the setpoint correction of the heating/cooling systems. It's used to calculate losses due to emission and control in the `space_emission_systems.py` code
- T_sup_air_aru_C: is the supply air temperature of the air-recirculation unit. I.e., the temperature of the conditioned air coming from your fan-coil unit. It is used in the `airconditioning_model.py` code

**Comment by gabriel-happle** [comment]
@Jack-Hawthorne I can't find a branch #2263. is it on github?

**Comment by Jack-Hawthorne** [comment]
@gabriel-happle @shanshanhsieh 

Thankyou both for the information! It is greatly appreciated.

Apologies, i forgot to publish this branch. However, I after consulting @daren-thomas, I will now create an epic and separate issues pertaining to some confusing aspects and potential fixes for these for the team to review and comment.

Hopefully we can get this sorted without too much hassle!

**Comment by JIMENOFONSECA** [comment]
I saw the issues that were recently created, we close this issue to avoid duplicates
