### ISSUE TITLE
Shallow geothermal potentail tool: AttributeError: Parameter not configured to work with this script

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2268]
This is an issue posted by @kerembeygo (transferred from #2259)

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/e41e25e9-9f4f-4d0c-963a-d239182cf924)
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/b431e724-38fc-4b55-b1b2-20acaf68b7d6)

**Comment by JIMENOFONSECA** [comment]
@reyery maybe you can give us a quick hand with it? in case you do not know how to fix this type of error, I can tell you how. It is good you know how...It happens form time to time...

**Comment by JIMENOFONSECA** [comment]
it was somehow fixed..It does not happen anymore in master
