### ISSUE TITLE
sensitivity-demand-simulate tool: AttributeError: Parameter not configured to work with this script

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2269]
This is an issue posted by @kerembeygo (transferred from #2259)

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/1991447f-37c5-436b-8e3a-5687357a453a)
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/322e23d5-874f-4311-b29d-b5264cf9b702)

**Comment by martin-mosteiro** [comment]
@kerembeygo Thanks for pointing out this issue, however the error doesn't actually appear in the screenshots provided. Could you please copy the full error message?

**Comment by kerembeygo** [comment]
![cea sensitivity-demand-simulate 2](https://user-images.githubusercontent.com/29708612/63539958-d9cb0900-c523-11e9-8acc-490740e3020c.jpg)
![cea sensitivity-demand-simulate 3](https://user-images.githubusercontent.com/29708612/63539966-dc2d6300-c523-11e9-8128-4675469d1c17.jpg)
Two images were forgetten to copy from #2259

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro update?

**Comment by martin-mosteiro** [comment]
@kerembeygo, @JIMENOFONSECA I cannot seem to replicate the issue. The sensitivity analysis step 2 runs correctly on my computer.

@kerembeygo Given that you are getting an error relating to `config.debug`, is it possible that you have this option set to `True` in your config file?

**Comment by kerembeygo** [comment]
![Sensitivity Demand Simulate](https://user-images.githubusercontent.com/29708612/65756645-29ea4c00-e11e-11e9-9523-469eaa8186a7.jpg)
![Sensitivity Demand Simulate 1](https://user-images.githubusercontent.com/29708612/65756684-3bcbef00-e11e-11e9-884e-9aef38d11d56.jpg)
![Sensitivity Demand Simulate 2](https://user-images.githubusercontent.com/29708612/65756702-45eded80-e11e-11e9-9634-087ce4cd1378.jpg)
![Sensitivity Demand Simulate 3](https://user-images.githubusercontent.com/29708612/65756706-48e8de00-e11e-11e9-8fdf-9ae99058a253.jpg)
![Sensitivity Demand Simulate 4](https://user-images.githubusercontent.com/29708612/65756715-4be3ce80-e11e-11e9-888c-9847b62d8a78.jpg)

**Comment by kerembeygo** [comment]
![Sensitivity Demand Simulate 5](https://user-images.githubusercontent.com/29708612/65756923-b137bf80-e11e-11e9-9be9-0ca865610e8a.jpg)
![Sensitivity Demand Simulate 6](https://user-images.githubusercontent.com/29708612/65756926-b39a1980-e11e-11e9-8415-866a1bb4548f.jpg)
![Sensitivity Demand Simulate 7](https://user-images.githubusercontent.com/29708612/65756927-b4cb4680-e11e-11e9-97b2-660f703d6807.jpg)
![Sensitivity Demand Simulate 8](https://user-images.githubusercontent.com/29708612/65756936-bac12780-e11e-11e9-9ffd-bda9b89d6d30.jpg)
![Sensitivity Demand Simulate 9](https://user-images.githubusercontent.com/29708612/65756938-bc8aeb00-e11e-11e9-901c-d2419e953d1b.jpg)

**Comment by kerembeygo** [comment]
After running Sensitivity Analysis I (DOE) (Both Sobol and Morris)
I ran Sensitivity Analysis II (simulation) in dashboard. 
I didn't make any changes in my config file.

**Comment by kerembeygo** [comment]
[general]
project = C:\CEA PROJECT\ISTANBUL\Fatih\Kocamustafapasa
scenario-name = KM1
scenario = {general:project}/{general:scenario-name}
multiprocessing = true
number-of-cpus-to-keep-free = 1
debug = false

[data-helper]
region = CH
overwrite-technology-folder = true
databases = comfort, architecture, HVAC, internal-loads, supply, restrictions

[streets-helper]
bbox = 
streets = all_private

[terrain-helper]
grid-size = 30
elevation = 1

[district-helper]
buffer = 50
height-ag = 
floors-ag = 

[zone-helper]
height-ag = 
floors-ag = 
year-construction = 
height-bg = 3
floors-bg = 1
occupancy-type = Get it from open street maps

[weather-helper]
weather = 

[radiation-daysim]
buildings = 
n-buildings-in-chunk = 100
roof-grid = 10
walls-grid = 200
zone-geometry = 2
surrounding-geometry = 5
consider-floors = true
rad-ab = 4
rad-ad = 512
rad-as = 32
rad-ar = 20
rad-aa = 0.15
rad-lr = 8
rad-st = 0.5
rad-sj = 0.7
rad-lw = 0.05
rad-dj = 0.7
rad-ds = 0
rad-dr = 0
rad-dp = 32
albedo = 0.2
daysim-bin-directory = C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Daysim

[demand]
buildings = 
loads-output = 
massflows-output = 
temperatures-output = 
resolution-output = hourly
format-output = csv
use-dynamic-infiltration-calculation = false
use-stochastic-occupancy = false
override-variables = false
write-detailed-output = false
predefined-hourly-setpoints = false

[emissions]
year-to-calculate = 2020

[benchmark-graphs]
project = {general:scenario}/..
scenarios = baseline, scenario1, scenario2
output-file = {benchmark-graphs:project}/benchmark-graphs.pdf

[extract-reference-case]
destination = {general:scenario}/../..
case = open

[solar]
buildings = 
type-pvpanel = PV1
type-scpanel = FP
panel-on-roof = True
panel-on-wall = True
annual-radiation-threshold = 800
t-in-sc = 
t-in-pvt = 
solar-window-solstice = 4

[retrofit-potential]
keep-partial-matches = true
retrofit-scenario-name = retrofit-HVAC
retrofit-target-year = 2020
age-threshold = 15
eui-heating-threshold = 150
eui-hot-water-threshold = 50
eui-cooling-threshold = 4
eui-electricity-threshold = 20
emissions-operation-threshold = 30
heating-costs-threshold = 2
hot-water-costs-threshold = 2
cooling-costs-threshold = 2
electricity-costs-threshold = 2
heating-losses-threshold = 15
hot-water-losses-threshold = 15
cooling-losses-threshold = 15

[sensitivity-demand]
method = sobol
num-samples = 1000
calc-second-order = false
num-levels = 4
samples-folder = {general:scenario}/../samples
variable-groups = ENVELOPE, INDOOR_COMFORT, INTERNAL_LOADS
sample-index = 0
number-of-simulations = 
simulation-folder = {general:scenario}/../simulation
output-parameters = Qcs_sys_MWhyr, Qhs_sys_MWhyr, E_sys_MWhyr, Qhs_sys0_kW, Qcs_sys0_kW, E_sys0_kW
temporal-scale = yearly

[dbf-tools]
input-file = {general:scenario}/inputs/technology/archetypes/construction_properties.xlsx
output-file-name = converted_file
output-path = {general:scenario}

[shapefile-tools]
excel-file = {general:scenario}/inputs/building-geometry/zone.xls
shapefile = {general:scenario}/inputs/building-geometry/zone.shp
crs = {"lon_0": 7.439583333333333, "k_0": 1, "ellps": "bessel", "y_0": 200000, "no_defs": true, "proj": "somerc", "x_0": 600000, "units": "m", "lat_0": 46.95240555555556}
index = Name
polygon = True

[test]
reference-cases = open
tasks = all
verbosity = 1

[trace-inputlocator]
scripts = data-helper, demand, emissions
meta-output-file = {general:scenario}/outputs/trace_inputlocator.output.yml

[neural-network]
year = 2015
warmup-period = 759
nn-delay = 1
nn-passes = 3
number-samples-scaler = 3
number-samples = 3
number-sweeps = 3
autoencoder = false
boolean-vars = ECONOMIZER, WIN_VENT, MECH_VENT, HEAT_REC, NIGHT_FLSH
climatic-variables = drybulb_C, wetbulb_C, relhum_percent, glohorrad_Whm2, dirnorrad_Whm2, difhorrad_Whm2, skytemp_C, windspd_ms
random-variables = win_wall, Cm_Af, n50, U_roof, a_roof, U_wall, a_wall, U_base, U_win, G_win, rf_sh,
	Ths_set_C, Tcs_set_C, Ths_setb_C, Tcs_setb_C, Ve_lps, Qs_Wp, X_ghp, Ea_Wm2, El_Wm2,
	Vww_lpd, Vw_lpd, dThs_C, dTcs_C, ECONOMIZER, WIN_VENT, MECH_VENT, HEAT_REC, NIGHT_FLSH, dT_Qhs,
	dT_Qcs
target-parameters = Qhs_sys_kWh, Qcs_sys_kWh, Qww_sys_kWh, E_sys_kWh, T_int_C

[single-calibration]
variables = U_win, U_wall, U_roof, n50, Tcs_set_C, Hs
building = B01
load = E_sys
samples = 1000
iterations = 10000
show-plots = true

[thermal-network]
network-type = DH
network-names = 
file-type = shp
set-diameter = true
load-max-edge-flowrate-from-previous-run = false
start-t = 0
stop-t = 8760
use-representative-week-per-month = false
minimum-mass-flow-iteration-limit = 30
minimum-edge-mass-flow = 0.1
diameter-iteration-limit = 10
substation-cooling-systems = ahu, aru, scu
substation-heating-systems = ahu, aru, shu, ww
temperature-control = VT
plant-supply-temperature = 80

[thermal-network-optimization]
network-type = DH
network-names = 
file-type = shp
set-diameter = true
load-max-edge-flowrate-from-previous-run = false
start-t = 0
stop-t = 8760
network-name = 
possible-plant-sites = 
min-number-of-plants = 1
max-number-of-plants = 1
number-of-individuals = 6
chance-of-mutation = 20
number-of-generations = 20
lucky-few = 1
optimize-loop-branch = false
optimize-network-loads = false
optimize-building-connections = false
use-rule-based-approximation = false
use-representative-week-per-month = false
minimum-mass-flow-iteration-limit = 30
minimum-edge-mass-flow = 0.1
diameter-iteration-limit = 10
substation-cooling-systems = ahu, aru, scu
substation-heating-systems = ahu, aru, shu, ww
disconnected-buildings = 
yearly-cost-calculations = false

[optimization]
district-heating-network = false
district-cooling-network = false
detailed-electricity-pricing = false
population-size = 10
number-of-generations = 10
random-seed = 100

[plots]
buildings = 
building = 
categories = demand, solar_potentials, solar_technology, life_cycle_analysis, thermal_network
network-type = DC
network-name = 
plant-node = 
timeframe = monthly

[plots-optimization]
generation = 3
multicriteria = true

[plots-supply-system]
generation = 3
individual = 1
timeframe = monthly

[plots-scenario-comparisons]
urban-energy-system-scenarios = Baseline, none, none, Baseline, 1, 1, Baseline, 1 , 2
categories = demand, supply_mix, costs_analysis, life_cycle_analysis, land_use

[sewage]
heat-exchanger-length = 120
sewage-water-ratio = 0.95
sewage-water-district = 50

[water-body]
max-water-volume-withdrawal = 1000
max-delta-temperature-withdrawal = 8
temperature-max = 6
temperature-min = 4

[shallow-geothermal]
buildings-available = 
extra-area-available = 0.0
average-probe-depth = 10

[create-new-project]
project = cea-new-project
scenario = baseline
output-path = {general:scenario}/../..
zone = {general:scenario}/inputs/building-geometry/zone.shp
terrain = {general:scenario}/inputs/topography/terrain.tif
streets = {general:scenario}/inputs/networks/streets.shp
district = 
occupancy = 
age = 

[decentralized]
detailed-electricity-pricing = false

[network-layout]
network-type = DC
connected-buildings = 
disconnected-buildings = 
pipe-diameter = 150
type-mat = T1
create-plant = true
allow-looped-networks = false
consider-only-buildings-with-demand = false

[supply-system-simulation]
district-heating-network = false
district-cooling-network = false
centralized-vcc = 0.5
centralized-ach = 0.4
centralized-storage = 0.1
reduced-timesteps = true
decentralized-systems = Vapor Compression Chiller
dc-connected-buildings = 

[multi-criteria]
generation = 3
economic-sustainability = 0.8
environmental-sustainability = 0.1
social-sustainability = 0.1
annualized-costs = 0.8
capex-total = 0.1
opex = 0.1
emissions = 0.5
primary-energy = 0.5
renewable-share = 1

[mpc-building]
time-start = 2005-01-01 00:00:00
time-end = 2005-01-01 23:30:00
set-temperature-goal = constant_temperature
constant-temperature = 25.0
pricing-scheme = constant_prices
constant-price = 255.2
min-max-source = constants
min-constant-temperature = 20.0
max-constant-temperature = 25.0
delta-set = 3.0
delta-setback = 5.0

[mpc-district]
time-start = 2005-01-01 00:00:00
time-end = 2005-01-01 23:30:00
set-temperature-goal = constant_temperature
constant-temperature = 25.0
pricing-scheme = constant_prices
constant-price = 255.2
min-max-source = constants
min-constant-temperature = 20.0
max-constant-temperature = 25.0
delta-set = 3.0
delta-setback = 5.0

[electrical-thermal-optimization]
network-type = DC
initialind = 2
halloffame = 20
ngen = 2
fcheckpoint = 1
maxtime = 604800
recoverycheckpoint = 0
random-seed = 
crossoverprobability = 0.5
mutationprobability = 0.2

[workflow]
workflow = district-heating-system
resume = off
resume-file = {general:project}/../resume-workflow.yml

[rename-building]
old = 
new = 

[server]
project-root = {general:project}/..

[worker]
url = http://localhost:5050/server

**Comment by martin-mosteiro** [comment]
Okay, I was finally able to replicate this issue. Interestingly, this doesn't happen when I run sensitivity analysis from Pycharm, only when I do so from the dashboard.
