### ISSUE TITLE
network-layout tool: UnboundLocalError: local variable 'field' referenced before assignment

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2270]
This is an issue posted by @kerembeygo (transferred from #2259)

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/6f1fbe32-d268-478d-b9fa-85df012d21d4)

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/0a17c5df-3025-4966-9e1a-45b6defc02bf)

**Comment by JIMENOFONSECA** [comment]
I can check this...

**Comment by JIMENOFONSECA** [comment]
EL should not be part of the inputs. We do not support that functionality for now. PR #2337 solves this issue
