### ISSUE TITLE
optimization tool: Missing geothermal potential of the scenario. Consider running lake potential script first.

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2271]
This is an issue posted by @kerembeygo (transferred from #2259)

After running `water-body-potential` tool, the `optimization` tool raises this error. (NOTE: the error message needs to be updated to reflect the name change in the tool. Also, the input files system should have caught this first!)

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/74f1f5bd-d1ea-437b-bf1d-e2de3c5daa0b)
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/f5f9d378-af82-49e3-adea-55987f861377)
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/3a21c5e2-cbcc-4ea9-9c72-f9f869bce689)

**Comment by JIMENOFONSECA** [comment]
Let me I fix this...
