### ISSUE TITLE
Update documentation on how to build the docs for a new release

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2277]
The documentation here is outdated: https://city-energy-analyst.readthedocs.io/en/latest/how-to-create-a-new-release.html#building-the-documentation

It needs to be updated to reflect the `cea-doc`  tool.

@Jack-Hawthorne as the author of that tool, I'm assigning this to you. Can you please also add some information about the graphviz stuff etc.?

**Comment by Jack-Hawthorne** [comment]
@daren-thomas can i just add a link to the documentation page of tutorials?

**Comment by daren-thomas** [comment]
@Jack-Hawthorne more or less. The section in the release documentation should at least contain the commands to run for each release. A link to more in-depth tutorials is of course very welcome!

**Comment by Jack-Hawthorne** [comment]
@daren-thomas do they still have to install sphinx ( and are there any version control issues associated?) or is this included in the dev installer?

**Comment by daren-thomas** [comment]
@Jack-Hawthorne confirming your assumption: sphinx is now part of the installer. it just makes it simpler. also no more  `pip install -e .[dev]` (the `[dev]` part is now obsolete)
