### ISSUE TITLE
CEA not opening / not being able to reinstall it

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2283]
Hi all,

For a while I am not being able to open CEA. When it tries to open it closes automatically. The web page is never opened. I was using the developers version and have already updated several times.

Jimeno recommended me to re-install it, but when I tried to do it today, the web page was not found (https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v2.20/Setup_CityEnergyAnalyst_2.20.1.exe)

Please let me know if you have any suggestions so that I can get a working version again.
Thanks!

**Comment by JIMENOFONSECA** [comment]
@lguilhermers We just fixed this. try again!
