### ISSUE TITLE
CEA installation button leads to incorrect URL

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2285]
When selecting "Try CEA", users get a form to fill out and finally a download button. This button leads [here](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v2.20/Setup_CityEnergyAnalyst_2.20.1.exe), which gives a 404 error. The correct link would be [this one](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v2.21/Setup_CityEnergyAnalyst_2.21.exe).

**Comment by JIMENOFONSECA** [comment]
fixed, good catch martin
