### ISSUE TITLE
React code uses hardcoded server:port

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2298]
see: `cea/interfaces/dashboard/plots/static/js/react-dashboard.js` - this code does stuff like 

```
axios.post(`http://localhost:5050/api/dashboard/new`, values)
```

which hardcodes the hostname and port of the cea server. instead, this should just be relative - `/api/dashboard/new` should work just as well.

the rationale for this is that we don't want to hardcode these values as they might change - imagine a future where the CEA is hosted in the cloud - say... `https://app.cityenergyanalyst.com/api/dashboard/new`.

**Comment by reyery** [comment]
Will probably set the `hostname` in a config file or environment variable for the electron application

```
let hostname = process.env.CEA_HOSTNAME or config.CEA_HOSTNAME 
axios.post(`http://${hostname}/api/dashboard/new`, values)
```
