### ISSUE TITLE
Terrain missing file (?) and error on the Solar Calculation

### ISSUE THREAD

**Issue by RicardoGomesIST** [architecture-building-systems/CityEnergyAnalyst#2308]
Hi, I tried to define a new project.First, exported and adapted the zone and district files from OSM. Then, in CEA I tried to define the terrain file (using helper and default values). Then ran the Solar Radiation and returned the error:
ERROR: this usually happens when buildings do not overlap with the terrain, try to check if this is the case
One thing I noticed it that the topography folder just has the TIF file and not the .TWF as your examples. 
Probably due to the error, I have no solar radiations output values (I created the empty folders before).
Can you help me, please? Thank you in advance 
[inputs.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/3615950/inputs.zip)

**Comment by JIMENOFONSECA** [comment]
Unfortunately, your files are not in the same coordinate system. your edits outside of CEA might have changed the format.

Please check our tutorial on how to change your coordinate system to what CEA needs (UTM)
