### ISSUE TITLE
Thermal Network II (simulation) stops without warning

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2311]
![Thermal Network](https://user-images.githubusercontent.com/29708612/64954979-ba5b9d80-d88f-11e9-94dd-27083073415a.jpg)
![CEA Thermal Network1](https://user-images.githubusercontent.com/29708612/64954984-be87bb00-d88f-11e9-8d52-79f2ba94ceae.jpg)
![CEA Thermal Network2](https://user-images.githubusercontent.com/29708612/64954992-c182ab80-d88f-11e9-9533-cc58e854db88.jpg)
![CEA Thermal Network3](https://user-images.githubusercontent.com/29708612/64955006-c3e50580-d88f-11e9-9774-d13f6c5f2512.jpg)
![CEA Thermal Network4](https://user-images.githubusercontent.com/29708612/64955009-c5163280-d88f-11e9-86c1-3cff3cc481cf.jpg)
![CEA Thermal Network5](https://user-images.githubusercontent.com/29708612/64955013-c7788c80-d88f-11e9-9ecc-7c531b9570b6.jpg)
![CEA Thermal Network6](https://user-images.githubusercontent.com/29708612/64955016-c8a9b980-d88f-11e9-9709-d7eb4557ea97.jpg)
![CEA Thermal Network7](https://user-images.githubusercontent.com/29708612/64955017-cb0c1380-d88f-11e9-9413-1d59a251ccb3.jpg)
![CEA Thermal Network8](https://user-images.githubusercontent.com/29708612/64955026-cf383100-d88f-11e9-8b1d-be8735a4a108.jpg)

**Comment by daren-thomas** [comment]
@kerembeygo I'm not sure exactly what you mean - I just ran the script today without any problems on the master branch.

Have you tried running it from the CEA Console? (`cea thermal-network`) - maybe you can see more output there...

How long did you wait to assure it stopped? From your last screenshot, it seems you still have a python session there... it's just currently not doing anything?

**Comment by kerembeygo** [comment]
Yes python session is there but it doesn't perform anything. It happened before.
![Thermal Network 1](https://user-images.githubusercontent.com/29708612/65118918-57cfe200-d9f4-11e9-998a-909cf80b0
![Thermal Network 2](https://user-images.githubusercontent.com/29708612/65118933-5b636900-d9f4-11e9-9121-8fc8ae85670f.jpg)
![Thermal Network 3](https://user-images.githubusercontent.com/29708612/65118945-5e5e5980-d9f4-11e9-9e76-830659173c48.jpg)
![Thermal Network 4](https://user-images.githubusercontent.com/29708612/65119142-92d21580-d9f4-11e9-93a9-2f7e18e349f3.jpg)

**Comment by kerembeygo** [comment]
CEA Console run
![Thermal Hydraulic](https://user-images.githubusercontent.com/29708612/65119430-e8a6bd80-d9f4-11e9-8312-001c1729d810.jpg)

**Comment by kerembeygo** [comment]
Question is I didn't enter any information about the scenario. How does console choose which scenario to perform?

**Comment by kerembeygo** [comment]
The run also increases disc size considerably. How do I clean the excess data from disc?

**Comment by kerembeygo** [comment]
Thermal Networks plots command only try to display DC plots (DH?).  
![ThNw1](https://user-images.githubusercontent.com/29708612/65122979-ec3d4300-d9fa-11e9-90d9-64871c8a2d71.jpg)
![ThNw2](https://user-images.githubusercontent.com/29708612/65122978-ec3d4300-d9fa-11e9-947f-fdb755dbd65f.jpg)
I don' t have any cooling demand for the district. But there must be.
![Energy Demand 1](https://user-images.githubusercontent.com/29708612/65123037-1262e300-d9fb-11e9-9084-7a3114d3f03a.jpg)

**Comment by kerembeygo** [comment]
![Output for thermal-network 1](https://user-images.githubusercontent.com/29708612/65828534-89726400-e2a4-11e9-9e55-3c1c421d2426.jpg)
![Output for thermal-network 2](https://user-images.githubusercontent.com/29708612/65828943-13bcc700-e2a9-11e9-8c27-6d7f953f4cad.jpg)

**Comment by kerembeygo** [comment]
Other issues seem to persist

**Comment by daren-thomas** [comment]
Regarding your question: The config file (`%USERPROFILE%\cea.config`) contains parameter information for the scripts - when you open a project / scenario in the dashboard, this gets set.

You can also save parameters in the tools section of the dashboard for each tool - then you can run them from the CEA Console without specifying the parameters explicitly. You can also modify these parameters with the `cea-config` command, which works exactly like `cea <script-name> --parameter1 value1 --parameter2 value 2...`, except it doesn't execute the script - it will save any parameters passed to it to the config file and show the configuration of the script.

**Comment by daren-thomas** [comment]
Regarding the plots: You can set the parameters of the plots and switch the network type to "DH" with the wrench symbol at the top right of the plot.

Regarding:

> Other issues seem to persist.

Which issues exactly now? Would you mind creating separate issues for each?

Also, a hint if the screenshot workflow is cumbersome for you: You can copy the output of the console / job and paste them here using triple backticks. That also lets you remove repetitive lines from the output.

**Comment by kerembeygo** [comment]
By issues I meant Thermal Network plots. There are seven plots for Thermal Networks. I tried each of them and Dashboard displayed an error message for each of them. I switched the network from DC to DH and it worked except for

Supply and Return Temp. at Plant None vs Ambient Temp. for DH

I have the following message
Traceback (most recent call last):
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router
    return original_handler(e)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router
    return original_handler(e)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\plots\routes.py", line 255, in route_div
    plot_div = plot.plot_div()
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\base.py", line 160, in plot_div
    return self.cache.lookup_plot_div(self, self._plot_div_producer)
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\cache.py", line 51, in lookup_plot_div
    plot_div = producer()
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\base.py", line 163, in _plot_div_producer
    fig = plotly.graph_objs.Figure(data=self.calc_graph(), layout=self.layout)
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\thermal_networks\Supply_Return_Outdoor.py", line 58, in calc_graph
    data_frame = self.plant_temperatures
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\thermal_networks\Supply_Return_Outdoor.py", line 102, in plant_temperatures
    plant_node_supply = supply_df[self.plant_node]
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\internals.py", line 4124, in get
    raise ValueError("cannot label index with a null key")
ValueError: cannot label index with a null key

**Comment by gabriel-happle** [comment]
@daren-thomas please check this issue. thanks.

**Comment by daren-thomas** [comment]
@kerembeygo I just checked and these plots work in master as of today. Can you please update and re-run the thermal-networks simulation?

**Comment by kerembeygo** [comment]
So far I used dashboard for simulations. I'm not familiar with PyCharm. Here are some results.

**Comment by kerembeygo** [comment]
![1](https://user-images.githubusercontent.com/29708612/67202744-0e6b1c00-f412-11e9-93b4-e40212b5f372.jpg)

**Comment by kerembeygo** [comment]
![2](https://user-images.githubusercontent.com/29708612/67202919-7a4d8480-f412-11e9-9c33-047bad086cfb.jpg)

**Comment by kerembeygo** [comment]
![3](https://user-images.githubusercontent.com/29708612/67203482-da90f600-f413-11e9-8fe7-02f4eb075eab.jpg)

**Comment by kerembeygo** [comment]
![4](https://user-images.githubusercontent.com/29708612/67203507-eda3c600-f413-11e9-8a2e-a49112c031a5.jpg)

**Comment by kerembeygo** [comment]
On PyCharm CPU runs at %100. That causes overheating of my notebook. So I had terminate the thermal network simulation.

**Comment by daren-thomas** [comment]
@kerembeygo I think you misunderstood: I didn't mean for you to run with PyCharm. Just to make sure you were using the newest version - Re-installing and choosing "Developer version" should do that for you.

And then re-run the thermal-network script. It should then work. This script _is_ resource heavy, you could _in theory_ use single process mode (set multi-processing to off in the dashboard). It will take a bit longer to compute.

**Comment by kerembeygo** [comment]
I have CEA 2.23. Without running thermal network simulation I tried thermal network plots. For thermal networks - supply and return vs. ambient temp plot I got an error message for the first time. For the second try I had this
![newplot](https://user-images.githubusercontent.com/29708612/67207079-8558e280-f41b-11e9-831b-404df0be0058.png)

**Comment by kerembeygo** [comment]
I don't know whether this solves the issue. If it does I won't go for the simulation. Thermal network simulation takes more than a day to complete.

**Comment by daren-thomas** [comment]
What error did you get the first time you tried? Otherwise, I guess we can close this issue.
