### ISSUE TITLE
Supply system map does not work in single plot view

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2312]
Opening supply system map in single plot view and toggling 3D would cause this error.

![image](https://user-images.githubusercontent.com/34395415/65024780-13970000-d968-11e9-87e1-360e24a8ff79.png)

![image](https://user-images.githubusercontent.com/34395415/65024790-17c31d80-d968-11e9-9414-6872369a3855.png)

From the looks of it, could be some kind of dependency problem with deckgl. Changing to react/bundling js dependencies would most likely solve this.

**Comment by JIMENOFONSECA** [comment]
@reyery did we fix this?

**Comment by reyery** [comment]
@JIMENOFONSECA don't think so. This will probably only affect the web browser version. Once we move to electron this issue would be obsolete.

**Comment by daren-thomas** [comment]
yes. we fixed it long time ago.
