### ISSUE TITLE
Dashboard "set-scenario" does not work in master

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2314]
@reyery maybe we can check this? to replicate just press the 'set-scenario' button in the dashboard

![image](https://user-images.githubusercontent.com/8973186/65113799-1ef53480-da17-11e9-9ed7-4d4b3fd54413.png)

**Comment by reyery** [comment]
Ok found the annoying bug where I forgot to change some function parameters during refactor.
