### ISSUE TITLE
Adding parallel processing to thermal-network-optimization

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2317]
Current thermal-network-optimization is only running the simulation with single processing.
Need to investigate whether the files are saved and read correctly between different rounds of simulations of different individuals.
@daren-thomas , please suggest the plan of attack, thanks!

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh check the optimization code I made. this should give you an idea how to set up GA correctly, including parallel simulations

**Comment by shanshanhsieh** [comment]
Notes from @daren-thomas and my discussion today:
the problem is that the same path is used to store network layouts ( `nodes.shp` and `edges.shp`) of different individuals, and if you start reading / writing to these files in parallel, you're going to run into problems. 

possible solution:
create subfolders (`{gen}_{ind}`) under `input/network/DC`

**Comment by shanshanhsieh** [comment]
the thermal network optimization is not being used in any research for the moment, therefore, does not have to be addressed in M2.28
