### ISSUE TITLE
Construction database available in input folder

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2321]
Hi all,

I had a meeting with Jimeno today to discuss some results today and he raised some issues to be posted here.

One would be that the construction_properties database shouldn't be available for the users to see in inputs - technology folder, as this raises confusion of which fields need to be edited by the user.

Thanks!
Luis

**Comment by daren-thomas** [comment]
@lguilhermers how is that _not_ a user input? I mean, for regions that we include (SG/CH), we can provide this information, but shouldn't the user be able to edit that and create his own region database?

**Comment by lguilhermers** [comment]
I think Jimeno's idea was to let the users create their own database in a separate place. If I understood correctly, with some interface on the dashboard for that.
For me it is a fair point that there needs to be a place to create a personal database, and for now probably the only way to do is by editing this sheet. But I also agree with Jimeno that creates some confusion with what is being considered by CEA as an input. 
It was only after he explained personally that I understood that the data helper load the data from technologies folder, and once you edit the fields at the dashboard, it changed the building-properties (which is the input taken by the simulation).

Hope this could clarify why we raised this issue.
@JIMENOFONSECA can also give some thoughts about it.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas no, the user should not have access to this (at least not in this way) the reason is that 
1. we do not have any user creating their own database (so why bother)
2. having this, creates confusion. We do not know anymore where the data is taken from (what databses can be editted and which not

The way to go is to take it out from the data helper. Should a user wants to create their own database (then we talk about this, if it happens...)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA is this still an issue?

**Comment by daren-thomas** [comment]
Summary of discussion:

- `inputs/technology/archetypes/construction_properties.xls` file is special in that it's only used as a template for the data-helper and should _not_ be edited by the user
- the other files in technologies _can_ be edited and we should provide an interface in the GUI for this.

Creating a new region for the CEA should provide a new `construction_properties.xls` file.

**Comment by JIMENOFONSECA** [comment]
Closing this. Another feature that changes this functionality was implemented in #2489
