### ISSUE TITLE
fields for Es and Ns (visibility at dashboard and definition at glossary)

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2322]
Hi all,

I had a meeting with Jimeno today to discuss some results today and he raised some issues to be posted here.

One would be that the the fields of Ns and Es are not visible at the dashboard to be edited, and this would be useful for the users. Right now they are only accessible by going to the building_properties folder.
Furthermore, it need a definition in the glossary because this parameter is not clear only by the name.

Thanks!
Luis

**Comment by daren-thomas** [comment]
@lguilhermers what fields exactly are you talking about? In what file are they?

**Comment by lguilhermers** [comment]
In architecture.dbf (inputs - building properties) there are 2 parameters named "Es" and "Ns".
From my understanding they control the rate of space that uses electricity and share of the building that is dedicated to apartments (or offices), respectively. 
This is useful because a significant part of the building is used for common spaces, mostly circulation.  This factor should account for those.
So, I guess it is useful to have them at the dashboard and defined in the glossary.

**Comment by JIMENOFONSECA** [comment]
@reyery the columns are not integrated into the dashboard. they do exist in the architecture.dbf
@gabriel-happle would you mind telling use again what NS and Es control for the singapore context?

**Comment by reyery** [comment]
@lguilhermers we have added the variables to the dashboard in master

**Comment by lguilhermers** [comment]
Thanks!

**Comment by lguilhermers** [comment]
@reyery should those fields be visible in the input editor already? I pulled the update, but I still don't see it on my dashboard.
![image](https://user-images.githubusercontent.com/50981039/65489292-6bd87f80-dedd-11e9-863a-ae4e14c7ee08.png)

**Comment by JIMENOFONSECA** [comment]
@lguilhermers you need to restart CEA after updating from master :-). let us know if this works

**Comment by lguilhermers** [comment]
@gabriel-happle just a reminder, if you can provide further clarification of what those parameters (Ns; Es) control.

**Comment by gabriel-happle** [comment]
@lguilhermers
`Es` is the fraction of GFA that has electrical loads, such as e.g., lighting according to the internal loads per m2. This area can be different to the Air-conditioned area.
`Ns` is the fraction of net floor area to GFA. It is used in the occupancy models when calculating the number of people in advanced occupancy models.

**Comment by JIMENOFONSECA** [comment]
https://github.com/gabriel-happle Gabriel, would you mind adding this description to the CeA glossary. It is missing in there
On 24 Sep 2019, 20:57 +0800, Gabriel Happle <notifications@github.com>, wrote:

@lguilhermers<https://github.com/lguilhermers>
Es is the fraction of GFA that has electrical loads, such as e.g., lighting according to the internal loads per m2. This area can be different to the Air-conditioned area.
Ns is the fraction of net floor area to GFA. It is used in the occupancy models when calculating the number of people in advanced occupancy models.

**Comment by daren-thomas** [comment]
@gabriel-happle please add descriptions to the `glossary.csv` file
