### ISSUE TITLE
Dashboard graph names

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2323]
Hi all,

I had a meeting with Jimeno today to discuss some results today and he raised some issues to be posted here.

One would be that the some of the names of graphs at the dashboard are a bit confusing.
He suggested to change "Energy Supply Intensity" to "Energy Use Intensity" and changing the current "Energy Use Intensity" to "Energy End-Use Intensity". This is to avoid confusion with EUI being the common term of the grid electricity consumption per m².

Thanks!
Luis

**Comment by daren-thomas** [comment]
closed with  #2327
