### ISSUE TITLE
feature request: show GFA where there is information about the area and volume

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2326]
Hi CEA team,

Would it be possible to add a feature that calculates the GFA (area * number of floors) and shows it in the input editor, the same way is done for areas and volumes (below)?
In my case I have data about GFA and would like to check with what CEA gives before running the simulations, adjusting the model to match with the available data. 
Right now I believe the only ways to get it are by calculating manually or getting the number in the outputs, after running the simulation.

![image](https://user-images.githubusercontent.com/50981039/65295603-710f9480-db94-11e9-8349-80b716c376d1.png)

**Comment by JIMENOFONSECA** [comment]
@reyery I think we can implement this quite easily in the front end (it is the multiplication of (floors_ag+floorsbg) * area

**Comment by daren-thomas** [comment]
@JIMENOFONSECA is this must-have or should-have?

**Comment by JIMENOFONSECA** [comment]
should…

_______________________
On 30 Oct 2019, 11:33 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> is this must-have or should-have?

**Comment by reyery** [comment]
I could add this in, since I'm currently working on converting the input editor to use react. Shouldn't be too hard
