### ISSUE TITLE
Project sponsor feature request: guide on how to start with CEA

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2336]
It could be a small document about what steps to do now whith the new CEA.

1. https://cityenergyanalyst.com/blog/2019/6/3/how-to-install-the-cea-on-windows-part-1Use this guide to install the development version of CEA and connect to our repository (code base)
2. https://cityenergyanalyst.com/blog/2019/6/28/getting-started-with-your-own-project-1Use these series of blog posts to create a new project and test functionality.
3. https://city-energy-analyst.readthedocs.io/en/latest/how-to-contribute.htmlStart contributing. Here is a guideline on how to.

**Comment by gabriel-happle** [comment]
this could be the blog for M2.24 #2359
