### ISSUE TITLE
CEA V. 2.22 Demand Error

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2342]
![Demand1](https://user-images.githubusercontent.com/29708612/65595918-7ad33680-df9e-11e9-82d7-1584dd6336ca.jpg)
![Demand2](https://user-images.githubusercontent.com/29708612/65595932-8292db00-df9e-11e9-83fd-aeba5d9d4d25.jpg)
![Demand3](https://user-images.githubusercontent.com/29708612/65595946-8888bc00-df9e-11e9-9d17-ada904e68a10.jpg)

**Comment by kerembeygo** [comment]
![Demand](https://user-images.githubusercontent.com/29708612/65624627-f3ec8100-dfd2-11e9-8ad5-d688d4a74dcc.jpg)

**Comment by kerembeygo** [comment]
No error with 2.21

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro @gabriel-happle I guess there were some changes to the databases? please suggest what to do in this case

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Indeed.
@kerembeygo please update CEA and run the data helper again, or alternatively add a column `Qcpro_Wm2` to the file **internal_loads.dbf** in your case study.

**Comment by kerembeygo** [comment]
Yes, data helper worked.
