### ISSUE TITLE
Definitions of E_sys and GRID

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2346]
Hi all,

I was not understanding very clear the difference from GRID and Esys by the the definitions provided and wanted to clarify based on some basic checks I did on the results of a simulation:

GRID means total buildings electricity consumption (and therefore what the grid has to provide to it) and is composed of Eal + Ecs + Eww + Eaux.

Meanwhile is Esys is just the electricity consumed for its final purpose, excluding Ecs and Eww, in which this electricity gets converted to thermal. Therefore, is just considering Eal + Eaux.

_Can anyone please inform if those assumptions are correct?_

If so, perhaps a change in the definitions is appropriate. In my opinion, the term "end-use" can be ambiguous in the definition of Esys, because when you refer to the _end-use consumption of the building_ , in general you are talking about the grid values, not only what is used for appliances and lighting.

**Comment by JIMENOFONSECA** [comment]
We updated the glossary to reflect this in PR #2383 

GRID_kWh,Grid total requirements of electricity = GRID_a + GRID_l + GRID_data + GRID_pro + GRID_aux + GRID_cdata + GRID_cre + GRID_hs + GRID_ww + GRID_cs,kWh

E_sys_kWh,End-use total electricity system consumption = Ea + El + Edata + Epro + Eaux
