### ISSUE TITLE
feature request: suspend simulations

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2349]
Would be nice to be able to abort the simulations in case you see you missed something and want to change or something like that. Right now we have access to the job list but there isn't an option to suspend activities.

**Comment by JIMENOFONSECA** [comment]
@reyery does that work? cancel the job?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA in theory, it would be possible to kill the processes. The "interface" used by CEA scripts doesn't have any knowledge about stopping, so it wouldn't be a clean exit. Really just a killing of the processes. The state of output etc. would be a bit unknown. A bit like hitting the stop execution button in PyCharm. Actually, _exactly_ like that.

**Comment by JIMENOFONSECA** [comment]
That sounds good to me. We can do it like pycharm

On 21 Oct 2019, 5:31 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> in theory, it would be possible to kill the processes. The "interface" used by CEA scripts doesn't have any knowledge about stopping, so it wouldn't be a clean exit. Really just a killing of the processes. The state of output etc. would be a bit unknown. A bit like hitting the stop execution button in PyCharm. Actually, exactly like that.

**Comment by daren-thomas** [comment]
I'm taking over this issue as I just implemented a similar feature and think I'm best suited to tackle this.

**Comment by daren-thomas** [comment]
See PR #2455
