### ISSUE TITLE
warning display for missing data helper

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2351]
Not really a big issue here but I noticed that when I created a new case and by some reason the default of data helper was to have nothing selected on the database (picture below). I ran without noticing and it didn't display any warning. Also when running the solar radiation and demand they were all shown as "success". 
![image](https://user-images.githubusercontent.com/50981039/65870789-a182da00-e3af-11e9-9e51-10802b58a890.png)

Obviously there was no outputs and I could see quickly where I missed, but it would be good to have a warning if there is nothing selected when running the data helper, as it doesn't make much sense and probably the user is missing that.
And also an error message when  trying to run daysim and demand (same as when running daysim without a terrain, for example).

**Comment by JIMENOFONSECA** [comment]
@reyery would you mind taking a look? I believe this is an error of the MultiChoiceParameter of the config. The user should select at least one right?

**Comment by JIMENOFONSECA** [comment]
So we might include this in future releases.
