### ISSUE TITLE
District cooling plant plot does not run without optimizing for cooling

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2373]
This issue was identified as part of PR #2295 

so in essence that plot cannot run without optimizing for district cooling. How would you like to handle that error? @daren-thomas in the front or the back-end. if so how? I am opening a separate issue for this.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA ideally, we use the `input_files` array in the plot class: This approach assumes there is a file that is only present when the optimization for district cooling has been run. The `input_files` array is a list of tuples `(locator_method, list_of_arguments_to_locator_method)` and is checked by the plotting system - the system will output an error (plus a hint of which script to run) if a file is not found.

So, to fix this, all you need to do is add a new input file description to the plot class' `__init__` that can identify if optimization cooling has run.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA are we talking about the plot "Dispatch curve for cooling plant in system"? (I'm not quite sure which plot to check as I couldn't find a plot called "District cooling plant")

**Comment by JIMENOFONSECA** [comment]
Hi Daren, yes, that one. The problem is that either way (ridding for district heating, or running for district cooling) we are generating exactly the same files. What changes are the values of the files. But that is not known apriori. So, the only way would be to create a “dummy file” that describes that the problem was run only for district heating or cooling, right?
On 21 Oct 2019, 6:40 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> are we talking about the plot "Dispatch curve for cooling plant in system"? (I'm not quite sure which plot to check as I couldn't find a plot called "District cooling plant")

**Comment by daren-thomas** [comment]
@JIMENOFONSECA what I noticed was that the file `outputs\data\optimization\slave\gen_1\ind_0_Cooling_Activation_Pattern.csv` doesn't have any columns except for the `DATE`:

```
DATE
2005-01-01 00:00:00
2005-01-01 01:00:00
2005-01-01 02:00:00
2005-01-01 03:00:00
```

The heating version of the file has the following headers:

```
DATE,E_CHP_gen_W,E_Furnace_dry_gen_W,E_Furnace_wet_gen_W,E_PVT_gen_W,Q_BackupBoiler_gen_directload_W,Q_BaseBoiler_gen_directload_W,Q_CHP_gen_directload_W,Q_Furnace_dry_gen_directload_W,Q_Furnace_wet_gen_directload_W,Q_GHP_gen_directload_W,Q_HP_Lake_gen_directload_W,Q_HP_Server_gen_directload_W,Q_HP_Server_storage_W,Q_HP_Sew_gen_directload_W,Q_PVT_gen_directload_W,Q_PVT_gen_storage_W,Q_PeakBoiler_gen_directload_W,Q_SC_ET_gen_directload_W,Q_SC_ET_gen_storage_W,Q_SC_FP_gen_directload_W,Q_SC_FP_gen_storage_W,Q_Storage_gen_directload_W,Q_districtheating_sys_req_W
2005-01-01 00:00:00,99773.421,0.000,0.000,0.000,0.000,0.000,104827.623,0.000,0.000,0.000,0.000,0.000,174460.822,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,104827.623

```

I think the problem here might not actually be a plotting problem but more a problem with how we store the data. What happens if you optimize for DC? will the heating version of this file also have no output? Shouldn't 0 values be output instead?

**Comment by daren-thomas** [comment]
to make this issue googleable, here is the error message in question:

```
KeyError: 'Q_DailyStorage_gen_directload_W'
```

**Comment by JIMENOFONSECA** [comment]
Yes, that is right. The heating version will not have any output.

The output is ok without the columns or values for now…

On 21 Oct 2019, 6:50 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> what I noticed was that the file outputs\data\optimization\slave\gen_1\ind_0_Cooling_Activation_Pattern.csv doesn't have any columns except for the DATE:

DATE
2005-01-01 00:00:00
2005-01-01 01:00:00
2005-01-01 02:00:00
2005-01-01 03:00:00


The heating version of the file has the following headers:

DATE,E_CHP_gen_W,E_Furnace_dry_gen_W,E_Furnace_wet_gen_W,E_PVT_gen_W,Q_BackupBoiler_gen_directload_W,Q_BaseBoiler_gen_directload_W,Q_CHP_gen_directload_W,Q_Furnace_dry_gen_directload_W,Q_Furnace_wet_gen_directload_W,Q_GHP_gen_directload_W,Q_HP_Lake_gen_directload_W,Q_HP_Server_gen_directload_W,Q_HP_Server_storage_W,Q_HP_Sew_gen_directload_W,Q_PVT_gen_directload_W,Q_PVT_gen_storage_W,Q_PeakBoiler_gen_directload_W,Q_SC_ET_gen_directload_W,Q_SC_ET_gen_storage_W,Q_SC_FP_gen_directload_W,Q_SC_FP_gen_storage_W,Q_Storage_gen_directload_W,Q_districtheating_sys_req_W
2005-01-01 00:00:00,99773.421,0.000,0.000,0.000,0.000,0.000,104827.623,0.000,0.000,0.000,0.000,0.000,174460.822,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,104827.623



I think the problem here might not actually be a plotting problem but more a problem with how we store the data. What happens if you optimize for DC? will the heating version of this file also have no output? Shouldn't 0 values be output instead?

**Comment by daren-thomas** [comment]
So... just to clarify: we can only optimize for one case per scenario? Either DC or DH?

**Comment by JIMENOFONSECA** [comment]
correct, we can only optimize for one grid at the time. We reduced functionality in #2550 so we avoid bugs down the road, and unnecessary maintenance
