### ISSUE TITLE
CEA failure on Grasshopper

### ISSUE THREAD

**Issue by dowbh** [architecture-building-systems/CityEnergyAnalyst#2375]
I am now trying to figure out the way of using grasshopper to input data for CEA. After following the instructions on the CEA’s blog, `Grasshopper-to-CEA` specifically, the CEA component in grasshopper still does not work. The following screenshots might be helpful for you to assess the problems. The first shot is the result I got when pulling CEA component to grasshopper. Since I couldn’t find further solutions on the blog for this situation, it will be great if you can provide some suggestions.

![C339223907F342B490C3A60F0A3AA8FE](https://user-images.githubusercontent.com/56314722/66504461-fabcce80-ea7d-11e9-966b-9420d3cd4388.png)

![434C56B03C8F4F839C0F5B9E1392023F](https://user-images.githubusercontent.com/56314722/66504456-f690b100-ea7d-11e9-8716-b965d83fdbc7.png)

**Comment by daren-thomas** [comment]
@dowbh what version of Rhino is this?

**Comment by dowbh** [comment]
Version 5 SR14 64-bit
(5.14.522.8390, 5/22/2017)
Educational Lab License 
----------------------------
This is the version info showing in my rhino.

**Comment by daren-thomas** [comment]
@dowbh I was able to reproduce the error and have a fix in PR #2415 pending review.
