### ISSUE TITLE
Issue #2375 follow-up

### ISSUE THREAD

**Issue by dowbh** [architecture-building-systems/CityEnergyAnalyst#2379]
I'm still having trouble operating CEA in Rhino 5 with Grasshopper v0.9.0076 as mentioned in the previous post. Meanwhile, I tried the same processes in Rhino 6 and the CEA component surprisingly showed up. However, after I hook the required input to CEA component, it still kept showing errors as the image attached below. I'm confused. In the blog, it's said that the  Rhino 5 is required, but it seems the result in Rhino 6 was even closer to what I expect.

![V6](https://user-images.githubusercontent.com/56314722/66589077-9e6fb280-eb42-11e9-9bc2-6ae6192def49.JPG)

**Comment by daren-thomas** [comment]
@dowbh: can you show the error messages themselves?

**Comment by daren-thomas** [comment]
@dowbh, a quick way to find out the error messages is to double-click on the CEA component. This should open up a Python editor with a "Test" button at the top right (I think). When you click that, there will be some output at the bottom of the dialog. Could you copy that and paste it into this issue please?

**Comment by JIMENOFONSECA** [comment]
closing until user comes back to us
