### ISSUE TITLE
Delete Selection button now working

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2388]
The delete selection button, used to delete buildings in the input editor, doesn't seem to be working. Can you please check on that?

**Comment by JIMENOFONSECA** [comment]
@reyery any ideas? I think the save button is also not working..

**Comment by reyery** [comment]
this is the an unfortunate side effect of making CEA ready for the electron app. The native browser alert windows that are supposed to be shown when clicking delete or save have been replaced with a javascript implementation. Adding the dependencies in the html solves this. Should be working now 0f35524
