### ISSUE TITLE
Plots should have a function to show raw data

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2393]
Plots in the dashboard should have a function to allow user to see the raw data used to create the plot so that they can do their own analysis on the data.

One way to do that is to show the users the location of the files used to create the plot and allow they to open such files. This can be achieved in the fronted by getting the `input_files` property of each plot class which contains the path of the files. 

Since not all plot classes have the `input_files` properly filled, the first step for this would be to ensure that every plot class has it filled and pointing to all the files that it uses.

**Comment by daren-thomas** [comment]
That's a cool idea... Note, that the plots generally do a lot of munging of the data before plotting it....

**Comment by reyery** [comment]
Closed by https://github.com/architecture-building-systems/CityEnergyAnalyst-GUI/pull/7
