### ISSUE TITLE
Radiation results do not account for adjacent buildings

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2397]
I am running a case study that includes the building shown in yellow below:
![image](https://user-images.githubusercontent.com/18548065/67223640-ec809200-f42f-11e9-8c4d-ebf614dcce7a.png)
![image](https://user-images.githubusercontent.com/18548065/67223644-f0141900-f42f-11e9-9416-cb4c0a706ca2.png)

As you can see, the building is surrounded on three sides by a taller building. This means that three out of the four sides of the building should have an irradiation of 0. However, the results show the following:
![Screen Shot 2019-10-21 at 18 25 16](https://user-images.githubusercontent.com/18548065/67223763-2782c580-f430-11e9-961c-a408493f36a2.png)

Sure, the western facade (the only one that does not touch the neighboring building) gets most of the irradiation, followed by the roof, as expected. However, 22% of the irradiation falls on the three facades that shouldn't have any irradiation at all.

My first assumption was that the building might not directly touch the neighboring building on the shapefile (which I doubt, given that I snapped the lines when drawing the shapefile on CAD), but even if there was a small gap between the building and the neighbor 22% of all irradiation on those surfaces sounds very high to me.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro mind sending me the case study?
thnaks!
