### ISSUE TITLE
expanding options for Scenario comparison plots

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2404]
Thanks for adding comparison between scenarios in the dashboard, I find it extremely useful!
Would be useful to compare different scenarios for cases other than annual costs.

I am personally interested in energy balances, energy final use intensity and load curves, but I see potential uses for others as well.

Thanks

**Comment by daren-thomas** [comment]
You can use the grid layout of the dashboard to compare multiple scenarios already.
