### ISSUE TITLE
Rename shortcuts (start menu & desktop) to "CEA GUI"

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2405]
Let's rebrand the "CEA Dashboard" feature - starting with the installer and work our way from there:

- rename the shortcuts to "CEA Dashboard" to "CEA GUI"
- rename the script `cea dashboard` to `cea gui`?
  - rename `dashboard.bat` to `cea-gui.bat`
- check documentation for references to "Dashboard"

Reasoning: We have a concept clash - "dashboard" either means the GUI or the dashboard feature of the GUI. I think it would improve the user experience to separate these two concepts.

**Comment by reyery** [comment]
Maybe the script `cea dashboard` should instead be renamed to _server/backend_ or something similar since it only exposes endpoints to interact with cea via http and necessarily the gui
