### ISSUE TITLE
Update documentation on optimization in files-generated-by-the-cea.rst

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2409]
The file `docs/files-generated-by-the-cea.rst` seems to be a bit outdated. I think the title of the file "files generated by the cea" is shown in [script-data-flow](https://city-energy-analyst.readthedocs.io/en/latest/script-data-flow.html)

I think renaming it to an overview of the optimization scripts and updating the information would be a good idea.

@JIMENOFONSECA do you want to have a quick look at this and decide on what to do?

**Comment by daren-thomas** [comment]
Daren has trace-inputlocator data for `decentralized` and `optimization` (heating) scripts. So I can update the script-data-flow stuff.

**Comment by daren-thomas** [comment]
we'll remove this file. but a documentation on how optimization works would be a good idea.

**Comment by JIMENOFONSECA** [comment]
commited to master
