### ISSUE TITLE
Thermal network optimization for DH

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2428]
The `thermal_network_optimization.py` is only working for DC in SG for the moment.
The cost calculation function is still missing to run for DH.
In more detail, a function called `calc_Ctot_hs_district` (similar to `calc_Ctot_cs_district`) should be added.

**Comment by martin-mosteiro** [comment]
After a quick scan of the function `calc_Ctot_cs_district`, it seems to me the following would need to be created:
1. `calc_Ctot_hs_district` (analogous to `calc_Ctot_cs_district`, as @shanshanhsieh mentioned)
2. `calc_Ctot_heating_plants` (analogous to `calc_Ctot_cooling_plants`, would need some methods to calculate the costs of different centralized heating supply systems)
3. `calc_Ctot_hs_disconnected_loads` (analogous to `calc_Ctot_cs_disconnected_loads`)
4. `calc_Ctot_hs_disconnected_buildings` (analogous to `calc_Ctot_cs_disconnected_buildings`)
