### ISSUE TITLE
Create Unitests for Optimization Script

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2435]

**Comment by daren-thomas** [comment]
@JIMENOFONSECA after our TeamViewer session - I think this is now something you can address, right? If I remember correctly, we decided that:

- we'll do integration testing by running the `cea-workflow`
  - this would test that the software "runs through", the bare minimum testing needed
- you can define some units to test (e.g. the cost function)
  - can we define expected values for specific inputs?
- how to test the optimization algorithm itself?
  - idea: by "mocking" the cost function... this would allow us to specify an "optimum" and see if the optimization algorithm selects for it, without having to wait for actual cost function calls...
