### ISSUE TITLE
Sensitivity Analysis Part II (simulation) - ERROR

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2443]
Job Output for 28 - sensitivity-demand-simulate
City Energy Analyst version 2.25.1
Running `cea sensitivity-demand-simulate` with the following parameters:
- general:scenario = C:\Users\KEREM\Documents\CEA Project\Fatih\Fatih1\YavuzSelim1
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = False
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- schedule-maker:schedule-model = deterministic
  (default: deterministic)
- schedule-maker:buildings = []
  (default: [])
- sensitivity-demand:samples-folder = C:\Users\KEREM\Documents\CEA Project\Fatih\Fatih1\samples
  (default: C:\Users\KEREM\Documents\CityEnergyAnalyst\samples)
- sensitivity-demand:simulation-folder = C:\Users\KEREM\Documents\CEA Project\Fatih\Fatih1\simulation
  (default: C:\Users\KEREM\Documents\CityEnergyAnalyst\simulation)
- sensitivity-demand:output-parameters = ['Qcs_sys_MWhyr', 'Qhs_sys_MWhyr', 'E_sys_MWhyr', 'Qhs_sys0_kW', 'Qcs_sys0_kW', 'E_sys0_kW']
  (default: ['Qcs_sys_MWhyr', 'Qhs_sys_MWhyr', 'E_sys_MWhyr', 'Qhs_sys0_kW', 'Qcs_sys0_kW', 'E_sys0_kW'])
- sensitivity-demand:number-of-simulations = None
  (default: None)
- sensitivity-demand:sample-index = 0
  (default: 0)
- demand:buildings = []
  (default: [])
- demand:loads-output = []
  (default: [])
- demand:massflows-output = []
  (default: [])
- demand:temperatures-output = []
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:use-dynamic-infiltration-calculation = False
  (default: False)
- demand:override-variables = False
  (default: False)
- demand:predefined-hourly-setpoints = False
  (default: False)
Running sensitivity-demand-simulate for scenario = C:\Users\KEREM\Documents\CEA Project\Fatih\Fatih1\YavuzSelim1
Running sensitivity-demand-simulate with sample-index = 0
Running sensitivity-demand-simulate with number-of-simulations = None
Running sensitivity-demand-simulate with samples-folder = C:\Users\KEREM\Documents\CEA Project\Fatih\Fatih1\samples
Running sensitivity-demand-simulate with simulation-folder = C:\Users\KEREM\Documents\CEA Project\Fatih\Fatih1\simulation
Running sensitivity-demand-simulate with output-parameters = ['Qcs_sys_MWhyr', 'Qhs_sys_MWhyr', 'E_sys_MWhyr', 'Qhs_sys0_kW', 'Qcs_sys0_kW', 'E_sys0_kW']
Setting prop_overrides['win_wall'] to 0.35380859375
Setting prop_overrides['n50'] to 1.4833984375
Setting prop_overrides['win_op'] to 0.56298828125
Setting prop_overrides['U_base'] to 1.4020019531249999
Setting prop_overrides['U_wall'] to 0.49958007812499994
Setting prop_overrides['U_roof'] to 0.915576171875
Setting prop_overrides['U_win'] to 1.0009765625
Setting prop_overrides['G_win'] to 0.8147949218749999
Setting prop_overrides['Cm_Af'] to 225283.203125
Setting prop_overrides['e_wall'] to 0.8476269531249999
Setting prop_overrides['e_win'] to 0.093916015625
Setting prop_overrides['e_roof'] to 0.30919921875
Setting prop_overrides['a_wall'] to 0.388623046875
Setting prop_overrides['a_roof'] to 0.511083984375
Setting prop_overrides['Hs'] to 0.650244140625
Setting prop_overrides['rf_sh'] to 0.3701171875
Setting prop_overrides['Tcs_set_C'] to 26.318359375
Setting prop_overrides['Ths_set_C'] to 21.37890625
Setting prop_overrides['Tcs_setb_C'] to 27.947265625
Setting prop_overrides['Ths_setb_C'] to 20.70703125
Setting prop_overrides['Ve_lps'] to 10.08984375
Setting prop_overrides['Qs_Wp'] to 76.494140625
Setting prop_overrides['X_ghp'] to 98.2568359375
Setting prop_overrides['Ea_Wm2'] to 6.7802734375
Setting prop_overrides['El_Wm2'] to 14.68994140625
Setting prop_overrides['Vww_lpd'] to 14.072265625
Setting prop_overrides['Vw_lpd'] to 10.80078125
Running demand simulation for sample 0
Using single process
Schedule for building No. 1 completed out of 23: B1000
Schedule for building No. 2 completed out of 23: B1001
Schedule for building No. 3 completed out of 23: B1002
Schedule for building No. 4 completed out of 23: B1003
Schedule for building No. 5 completed out of 23: B1004
Schedule for building No. 6 completed out of 23: B1005
Schedule for building No. 7 completed out of 23: B1006
Schedule for building No. 8 completed out of 23: B1007
Schedule for building No. 9 completed out of 23: B1008
Schedule for building No. 10 completed out of 23: B1009
Schedule for building No. 11 completed out of 23: B1010
Schedule for building No. 12 completed out of 23: B1011
Schedule for building No. 13 completed out of 23: B1012
Schedule for building No. 14 completed out of 23: B1013
Schedule for building No. 15 completed out of 23: B1014
Schedule for building No. 16 completed out of 23: B1015
Schedule for building No. 17 completed out of 23: B1016
Schedule for building No. 18 completed out of 23: B1017
Schedule for building No. 19 completed out of 23: B1018
Schedule for building No. 20 completed out of 23: B1019
Schedule for building No. 21 completed out of 23: B1020
Schedule for building No. 22 completed out of 23: B1021
Schedule for building No. 23 completed out of 23: B1022
read input files
done
Running demand calculation for all buildings in the zone
Using single process
Building No. 1 completed out of 23: B1000
Building No. 2 completed out of 23: B1001
Building No. 3 completed out of 23: B1002
Building No. 4 completed out of 23: B1003
Building No. 5 completed out of 23: B1004
Building No. 6 completed out of 23: B1005
Building No. 7 completed out of 23: B1006
Building No. 8 completed out of 23: B1007
Building No. 9 completed out of 23: B1008
Building No. 10 completed out of 23: B1009
Building No. 11 completed out of 23: B1010
Building No. 12 completed out of 23: B1011
Building No. 13 completed out of 23: B1012
Building No. 14 completed out of 23: B1013
Building No. 15 completed out of 23: B1014
Building No. 16 completed out of 23: B1015
Building No. 17 completed out of 23: B1016
Building No. 18 completed out of 23: B1017
Building No. 19 completed out of 23: B1018
Building No. 20 completed out of 23: B1019
Building No. 21 completed out of 23: B1020
Building No. 22 completed out of 23: B1021
Building No. 23 completed out of 23: B1022
done - time elapsed: 175.2f seconds
Setting prop_overrides['win_wall'] to 0.8856445312499999
Setting prop_overrides['n50'] to 1.4833984375
Setting prop_overrides['win_op'] to 0.56298828125
Setting prop_overrides['U_base'] to 1.4020019531249999
Setting prop_overrides['U_wall'] to 0.49958007812499994
Setting prop_overrides['U_roof'] to 0.915576171875
Setting prop_overrides['U_win'] to 1.0009765625
Setting prop_overrides['G_win'] to 0.8147949218749999
Setting prop_overrides['Cm_Af'] to 225283.203125
Setting prop_overrides['e_wall'] to 0.8476269531249999
Setting prop_overrides['e_win'] to 0.093916015625
Setting prop_overrides['e_roof'] to 0.30919921875
Setting prop_overrides['a_wall'] to 0.388623046875
Setting prop_overrides['a_roof'] to 0.511083984375
Setting prop_overrides['Hs'] to 0.650244140625
Setting prop_overrides['rf_sh'] to 0.3701171875
Setting prop_overrides['Tcs_set_C'] to 26.318359375
Setting prop_overrides['Ths_set_C'] to 21.37890625
Setting prop_overrides['Tcs_setb_C'] to 27.947265625
Setting prop_overrides['Ths_setb_C'] to 20.70703125
Setting prop_overrides['Ve_lps'] to 10.08984375
Setting prop_overrides['Qs_Wp'] to 76.494140625
Setting prop_overrides['X_ghp'] to 98.2568359375
Setting prop_overrides['Ea_Wm2'] to 6.7802734375
Setting prop_overrides['El_Wm2'] to 14.68994140625
Setting prop_overrides['Vww_lpd'] to 14.072265625
Setting prop_overrides['Vw_lpd'] to 10.80078125
Running demand simulation for sample 1
.
.
.
.
.
Running demand simulation for sample 270
Using single process
Schedule for building No. 1 completed out of 23: B1000
Schedule for building No. 2 completed out of 23: B1001
Schedule for building No. 3 completed out of 23: B1002
Schedule for building No. 4 completed out of 23: B1003
Schedule for building No. 5 completed out of 23: B1004
Schedule for building No. 6 completed out of 23: B1005
Schedule for building No. 7 completed out of 23: B1006
Schedule for building No. 8 completed out of 23: B1007
Schedule for building No. 9 completed out of 23: B1008
Schedule for building No. 10 completed out of 23: B1009
Schedule for building No. 11 completed out of 23: B1010
Schedule for building No. 12 completed out of 23: B1011
Schedule for building No. 13 completed out of 23: B1012
Schedule for building No. 14 completed out of 23: B1013
Schedule for building No. 15 completed out of 23: B1014
Schedule for building No. 16 completed out of 23: B1015
Schedule for building No. 17 completed out of 23: B1016
Schedule for building No. 18 completed out of 23: B1017
Schedule for building No. 19 completed out of 23: B1018
Schedule for building No. 20 completed out of 23: B1019
Schedule for building No. 21 completed out of 23: B1020
Schedule for building No. 22 completed out of 23: B1021
Schedule for building No. 23 completed out of 23: B1022
read input files
done
Running demand calculation for all buildings in the zone
Using single process
Building No. 1 completed out of 23: B1000
Building No. 2 completed out of 23: B1001
Building No. 3 completed out of 23: B1002
Building No. 4 completed out of 23: B1003
Building No. 5 completed out of 23: B1004
Building No. 6 completed out of 23: B1005
Building No. 7 completed out of 23: B1006
Building No. 8 completed out of 23: B1007
Building No. 9 completed out of 23: B1008
Building No. 10 completed out of 23: B1009
Building No. 11 completed out of 23: B1010
Building No. 12 completed out of 23: B1011
Building No. 13 completed out of 23: B1012
Building No. 14 completed out of 23: B1013
Building No. 15 completed out of 23: B1014
Building No. 16 completed out of 23: B1015
Building No. 17 completed out of 23: B1016
Building No. 18 completed out of 23: B1017
Building No. 19 completed out of 23: B1018
Building No. 20 completed out of 23: B1019
Building No. 21 completed out of 23: B1020
Building No. 22 completed out of 23: B1021
Building No. 23 completed out of 23: B1022
Traceback (most recent call last):
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\analysis\sensitivity\sensitivity_demand_simulate.py", line 239, in main
    output_parameters=config.sensitivity_demand.output_parameters)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\analysis\sensitivity\sensitivity_demand_simulate.py", line 189, in simulate_demand_batch
    totals, time_series = simulate_demand_sample(locator, config, output_parameters)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\analysis\sensitivity\sensitivity_demand_simulate.py", line 135, in simulate_demand_sample
    totals, time_series = demand_main.demand_calculation(locator, config)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\demand\demand_main.py", line 133, in demand_calculation
    totals, time_series = writer_totals.write_to_csv(building_names, locator)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\demand\demand_writers.py", line 235, in write_to_csv
    df = pd.read_csv(temporary_file)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\KEREM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File c:\users\kerem\appdata\local\temp\B1000T.csv does not exist

**Comment by daren-thomas** [comment]
CEA SCRUM decision: This tool should not be part of the GUI. We won't be actively supporting this tool.
