### ISSUE TITLE
Can't create new scenario with with v2.25 - shapely error

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2449]
after re-installing cea v2.25, i encountered this error when running new scenario:
after selecting the district in OSM, and click `Create` scenario, only an empty `zone.shp` was created
![image](https://user-images.githubusercontent.com/16998305/68414974-93379300-0191-11ea-91a2-f68689cc8d83.png)

@daren-thomas might know what is causing this error?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh we made an important fix over the weekend. mind reinstalling CEA? Once you create the scenario, aim to check the options of the weather file. They should point to a valid weather file to be created. This is a source of typical error.

**Comment by daren-thomas** [comment]
solved in 2.25.2
