### ISSUE TITLE
As a Researcher I would like to calibrate CEA so I can get realistic results to my baseline

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2454]
I will be working on a code for comparison of measured values with model outputs (i.e. validation procedure according to ASHRAE). Later on this will evolve to a calibration tool.

**Comment by FrancisBase** [comment]
Hello,
Is it possible for CEA to make available the data that was used, or any data actually, that can be used that is actual real measured data, to see the differences between the simulation and the reality ?

Surely it's not imaginable that a simulation engine like CEA which is so widespread has not been published without reproducible calibration, so would like to know if you can share the link because could not find it in your site.

**Comment by daren-thomas** [comment]
Could this be broken down into multiple steps that could (realistically) be solved during a sprint? Also, maybe this could be realized as an example of the plugin architecture (see #2716)

**Comment by lguilhermers** [comment]
Hi Daren,

I can give an update about this. We have a functional code that calibrates multiple scenarios against monthly measured data, using the ASHRAE standard and also checking how many building are considered validated. @JIMENOFONSECA has been helping me to enhance it and right now I am testing how it performs.

The code is made for v 2.29, so it needs to be updated. After that I believe it will only need some polishing.
The idea about having in into an architecture plugin sounds good!

**Comment by daren-thomas** [comment]
Removing estimate as it is messing with our sprint velocity calculation.

**Comment by daren-thomas** [comment]
@lguilhermers can you please give an update to this issue?

**Comment by lguilhermers** [comment]
@daren-thomas Sure!

We are running a longer iteration (1000 it) locally with a computer in @emanuel030 house. When it runs we will see if it converged well.

The code itself has been working for a while, but it is very tailored for the needs we have currently. 
Once I analyse this longer run, if it is reasonable, we can discuss about how those can be incorporated in CEA in a more generic way, how does this sound?

**Comment by daren-thomas** [comment]
@lguilhermers - the longer it takes to merge, the harder it will be to merge. But I totally understand that you need to check your results first.

I'm wondering if your changes could be made into a plugin instead? Let's talk when you're done!

**Comment by lguilhermers** [comment]
Yes, indeed.
I think a plugin is a good alternative, as it is a quite 'stand-alone' tool and perhaps doesn't go into the workflow of many of the analysis being done (manual calibration is still quite common, especially for the lack of data).
I have also not seen other tools where calibration is incorporated directly into them, so a plugin can be a first step towards that.

**Comment by daren-thomas** [comment]
@lguilhermers please add a link to your awesome plugin to this issue so people can find it when they search "calibrating cea models"

**Comment by lguilhermers** [comment]
Sorry, forgot about that last week.
Here is the link of the plugin for reference: https://github.com/lguilhermers/calibration_plugin

Thanks @daren-thomas and @jimenofonseca for the support to develop it!
