### ISSUE TITLE
Surroundings helper tool skips buildings...?

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2456]
I wanted to try some stuff by creating the Hochschulquartier case study again from OSM data. So I did the following:
1. Created a new project by selecting the zone shape from the map while selecting "Surroundings" as true and setting the buffer zone as 100 m. I did not get any surroundings in the scenario generated. I tried this two more times with the same results.
2. I used one of the scenarios created in point 1 above and ran the surroundings tool again, again with a buffer of 100 m. I again did not get any surroundings. So I ran it once more and I got a surroundings geometry file with some issues... (See the missing surrounding buildings on either side of the picture)
![surroundings](https://user-images.githubusercontent.com/18548065/68773844-8d77fc80-062c-11ea-9f2e-52b621f56677.png)

Not sure who to assign, so I'm assigning @JIMENOFONSECA and @reyery as a first option!

**Comment by daren-thomas** [comment]
Workaround: create a zone on a different scenario and import that as the district.

Feature idea: click buildings on map to add them to zone / district?
