### ISSUE TITLE
Error when trying to open CEA Dashboard

### ISSUE THREAD

**Issue by fcschuch** [architecture-building-systems/CityEnergyAnalyst#2457]
![Error message CEA Dashboard](https://user-images.githubusercontent.com/57716103/68834510-c055db00-0694-11ea-9e6d-a8f83158919a.JPG)

After installing CEA (with the developer version) I tried to open the Dashboard and received the above error message. I pressed OK and waited a while to see if it would open anyway but it stayed in a "frozen state" until I decided to close the application.

**Comment by daren-thomas** [comment]
@fcschuch our next release is planned for tomorrow, November 15 or Monday. We'll do some testing to make sure both the developer version and the base version work.

If you want, you can try running the command `cea dashboard` from the CEA Console... What is the output of that command? It might have some more hints on what went wrong.

**Comment by fcschuch** [comment]
@daren-thomas Thanks for the information. This is the output I get after running the command:
![Capture](https://user-images.githubusercontent.com/57716103/68854076-0e310a00-06ba-11ea-9d1b-9494f47187b4.JPG)

**Comment by daren-thomas** [comment]
@fcschuch that looks good! We just released verion 2.26: https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/tag/v2.26.0

I suggest you restart your computer and then install this version. I think that should work better.

BTW: I just noticed you installed to "C:\Program Files" as opposed to the default (your "Documents" folder) - that _could_ be part of the problem. Is there a specific reason you need to install to that location? If you don't want to install to "My Documents", could you install to "C:\ProgramData" instead?

**Comment by daren-thomas** [comment]
@fcschuch - I tried installing to "C:\Program Files" and - aside from permission issues - it seems it _does_ work. I still suggest not installing there if possible.
