### ISSUE TITLE
Negative values obtained for Qcs_MWhyr Total cool demand 

### ISSUE THREAD

**Issue by RicardoGomesIST** [architecture-building-systems/CityEnergyAnalyst#2460]
Hello,
I am simulating a residential neighborhood. I asked for energy demand values. 
I used the default technical systems for the HVAC:
T1 for heating, T2 for cooling that correspond on the "emissions systems" to:
T1 -- Radiator   (90/70)
T2 -- mini-split AC (6/15) 
I ran the simulation and it return negative values for the Qcs_MWhyr Total cool demand - Unit: [MWh/year]. How is this possible? Maybe I am missing something or some inputs are wrong.

Thank you very much for your time.

**Comment by daren-thomas** [comment]
Hello @RicardoGomesIST, internally, we use negative values for cooling demand - the absolute value is then used for displaying the demand.

BTW: You should probably be using the output "Qcs_sys_MWhyr" for the cooling demand because it includes distribution and emission losses.

**Comment by RicardoGomesIST** [comment]
Thank you so much Daren. Keep the amazing work!

 



IST, Taguspark, N14.16
