### ISSUE TITLE
bug - not being able to overwrite technology folder

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2461]
![image](https://user-images.githubusercontent.com/50981039/68930012-753ce480-07c8-11ea-9b21-c898e39f066c.png)

when I click in "Run Script" nothing happens. 

I currently need to re-run the technology folder to see my models in the input error, as recommended by @JIMENOFONSECA 
(because right nowI get:
 **Something went wrong.
ERROR MESSAGE: No sheet named <'ALL_IN_ONE_SYSTEMS'>
Details**)

**Comment by daren-thomas** [comment]
So... no notifications that a job is running? no output windows?

what version are you using?

@reyery is there a way to view the output of the GUI? I believe there is an issue for this in the database, right?

**Comment by lguilhermers** [comment]
No, it acts as if I didn't press the button. When I pressed the button to return to defaults or change the config file, it worked. But when I press to run nothing happens

I am using now version 2.25.1

**Comment by lguilhermers** [comment]
It seems to be working fine now. I will close the issue

**Comment by lguilhermers** [comment]
actually, the issue came back. Must be a certain condition that triggers it. Like running demand and trying to run data helper again. I will post here the steps if I manage to reproduce it.
