### ISSUE TITLE
Overlapping between tower and podium

### ISSUE THREAD

**Issue by dowbh** [architecture-building-systems/CityEnergyAnalyst#2468]
Becuase of the way of creating building footprints (all in 2D linework on the same plane), it seems that there would be an inevitable overlapping portion in the scenario of a tower standing on a podium. As shown in the attached image, the podium is penetrated through by the bottom of the tower. I wonder is there a way to allow CEA to read them as two separate volumes? Or would you guys suggest a way to create the footprint differently to resolve that problem? If not, will the overlapping portion be problematic to the simulated results?

![Volume overlay](https://user-images.githubusercontent.com/56314722/69359863-4f876380-0c3e-11ea-98d0-9fce92904745.png)

**Comment by daren-thomas** [comment]
We suggest to separate the footprint so that the part with tower and the part without tower are separate and then assign building use as appropriate.

You can use QGIS to fix this issue.
