### ISSUE TITLE
List of usability issues - Practitioner feedback

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2469]
During the month of November. Prof. Sulzer, head of SCCER FEEB&D was visiting our lab in Singapore. He is a quite experienced engineer, practitioner and researcher. For the purposes of this list of usability issues, he represents the CEA User Persona of Practitioner.

We tested the workflow of two cases studies in Switzerland and gave a special look to the usability perspective of CEA for taking decisions regarding the design of district heating networks, and district energy generation units (thermal).

Here is a list of potential issues in CEA. These should be included in next year's evaluation of the roadmap at the latest.

·         Indication which steps are completed

·         Electricity prices and CO2 intensity per hour, selection of data

·         Potential which are not available should be left out in the optimisation, e.g. PVT or thermal solar

·         Graph: Annual energy consumption DH, Pumping energy twice in black and Pumping Energy should be around 1-3%, see paper Grundlagen und Erläuterungen zu thermischen Netzen, HSLU

·         Why using 3th Generation and not 4th Generarion of DH?

·         Load duration curve pump should similar zu load heat

·         Relative heat and pressure drop: how can it be, that no thermal loss by heat supply

·         Peak Pressure Loss: show Pa/m

·         Aggregated losses in kWh not kW

·         Energy demand: comfort chart does not work

·         Energy demand: always show sum or average of district

·         Solar radiation: show sum of all categories (e.g. roof top) for the district

·         Integrate the second step of choosing a graph into the first window

·         Solar curve: add them up to show the overall curve

·         Show demand in the map per building

·         Why Oil for final use in demand analysis? Just thermal und elektrical energy.

·         Pareto Graph: CO2 kg/m2*a

·         Colouring and order Graph Investment, Annual, etc. Cost Pareto Solution dito Pareto Front Solutions and light/bold

·         Supply System, Cooling dispatch: order input dito others

·         Overview of Technology?

·         Schedules: Water, numbers after ,

·         Decentralised —> Building Scale; Centralised —> District Scale

·         Thermal Network Graph: plant node?

·         Option to chose technology which will be considered, eg. Natural gas

 

 

Freundliche Grüsse

 

Prof. Matthias Sulzer

Head SCCER FEEB&D

**Comment by matthiassulzer** [comment]
Some clarifications:
· Indication which steps are completed

· Electricity prices and CO2 intensity per hour, provide selection of data to choose from

· Potential which are not available should be left out in the optimisation, e.g. PVT or thermal solar

· Graph: Annual energy consumption DH: Pumping energy twice in black and Pumping Energy should be around 1-3%, see paper Grundlagen und Erläuterungen zu thermischen Netzen, HSLU

· Why using 3th Generation (90-70°C) and not 4th Generation of DH (60-70°C)?

· Load duration curve pump should be similar to load heat

· Relative heat and pressure drop: how can it be, that no thermal loss but heat supply is required?

· Peak Pressure Loss: show Pa/m

· Aggregated losses in kWh not kW

· Energy demand: comfort chart does not work

· Charts with Energy demand: always show total/sum or average of the time serie.

· Solar radiation: show sum of all categories (e.g. roof top) for the district

· Integrate the second step of choosing a graph into the first window

· Solar graphs: add values up to show the overall production

· Show demand in the map per building

· Why Oil for final use in demand analysis? Just thermal und electrical energy.

· Pareto Graph: CO2 kg/m2*a

· Colors and order Graphs Investment, Annual, etc. dito Pareto Front Solutions and light/bold

· Supply System, Cooling dispatch: order input dito others

· Overview of chosen Technology?

· Decentralized —> Building Scale; Centralized —> District Scale

· Thermal Network Graph: plant node, the position should be done by the user

· Option to choose technology which will be considered or not be considered, eg. Natural gas

**Comment by daren-thomas** [comment]
@JIMENOFONSECA would you mind splitting this up into a list of issues / epics please? So we can start designing and prioritizing them...

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I selected the issues we may be able to cover until version 3.0, and created new ones. @matthiassulzer many thanks for the comments. We much appreciate this.
