### ISSUE TITLE
move inputs.yml to schemas.yml

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2480]
Let's have only one place for the ground truth of the schemas as mentioned in #2479

**Comment by daren-thomas** [comment]
@JIMENOFONSECA `inputs.yml` contains features not present in `schemas.yml`. While the current state isn't the cleanest solution, it works and the list of files for the input-editor is small and rather static. I suggest we work on more important issues.
