### ISSUE TITLE
changes in the Input Editor not being saved

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2482]
Hi CEA team,

I am getting an error every time I try to save the Input Editor after trying to save _any_ change. It just displays "Something Went wrong."

![image](https://user-images.githubusercontent.com/50981039/69944435-42ae1e00-1522-11ea-8642-bdf7d02b4246.png)

**Comment by daren-thomas** [comment]
@lguilhermers what exact version are you using?

**Comment by lguilhermers** [comment]
@daren-thomas , I was using 2.25.1. I updated to 2.27.0 and it is working now.
