### ISSUE TITLE
error when create a scenario importing input files

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2483]
I was not able to import a .shp file to make those as my "zone" file. I even tried with CEA's own files created in previous projects but the error persists.

When I click in "Create", a new window saying "Creating Scenario" shows up, but goes away right after and the import is not successful. 

![image](https://user-images.githubusercontent.com/50981039/70022927-d1797400-15d0-11ea-8588-4ece5cd465ed.png)

**Comment by daren-thomas** [comment]
@lguilhermers can you provide a test case?
@reyery should the interface maybe show more information if something went wrong?

**Comment by lguilhermers** [comment]
@daren-thomas I tested in the new version (2.27) with CEA shp from other projects and it is working (before it wasn't).
I will have to correct the projection of the shp file I want to import because I think this might be the error source. I update here once I fix it and then try importing it again.

**Comment by daren-thomas** [comment]
@lguilhermers this will be fixed with the next release (2.28) expected tomorrow or Monday.

**Comment by lguilhermers** [comment]
@daren-thomas thanks for the update! I also discussed with Jimeno yesterday and maybe I was missing some steps on my side (e.g. adding some columns in the attribute table of the .shp file). I will try next week in 2.28 and with those additional steps and update you. thanks!

**Comment by daren-thomas** [comment]
@lguilhermers the new version is out, please try it out and report back on whether it solves your problem :)

**Comment by lguilhermers** [comment]
Sorry, I missed that. Yes, everything seems to be running smoothly importing external shp, given that the attribute tables and georeferences are set up correctly. If there is a higher demand for user- imported zones, perhaps a post in the blog with some tips would be useful to not miss anything that is key for CEA. I can help by tracing my steps and issues I faced. :) Thanks, @daren-thomas!
