### ISSUE TITLE
Is it possible to export outputs to someone that doesn't have CEA?

### ISSUE THREAD

**Issue by RicardoGomesIST** [architecture-building-systems/CityEnergyAnalyst#2484]
Hi everyone,
I would like to know if it is possible  to have a sort of a demonstration kit, where you can for instance send the outputs of two scenarios to someone, who doesn't have CEA installed, and the person is able to visualize the buildings and  the results (without the possibility of running or editing of course).
Thank you very much, keep the good work

**Comment by daren-thomas** [comment]
@RicardoGomesIST I think this might be out of scope of the tool. Since the CEA is open source and free to download / install - the user could just do that?
