### ISSUE TITLE
CEA Databases

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2489]
CEA uses databases for analysis. We are planning a case study and we need to create our own databases. I checked the CEA databases in excel files. Some column headers are understandable some are not. Is there a document which explains the column headers and is there a document about how to create your own database?

![1](https://user-images.githubusercontent.com/29708612/70321941-c83f1000-1839-11ea-9e7c-de34922d9355.jpg)

I also used UMI (Urban Modeling Interface)'s template library editor. It seemed more easily editable especially for new constructions.

**Comment by daren-thomas** [comment]
@kerembeygo you can use the glossary search function in the CEA GUI (top right) to search any column headers.

**Comment by kerembeygo** [comment]
**construction_properties Es**
TODO
![1](https://user-images.githubusercontent.com/29708612/70374195-313d8b00-1901-11ea-99bd-4941b222b949.jpg)

**Comment by kerembeygo** [comment]
**Slide down another definition for Es**
![2](https://user-images.githubusercontent.com/29708612/70374244-95604f00-1901-11ea-9357-8a480e54f086.jpg)

**Comment by kerembeygo** [comment]
![3](https://user-images.githubusercontent.com/29708612/70374269-b3c64a80-1901-11ea-842e-87d85da77279.jpg)

**Comment by kerembeygo** [comment]
Too many TODOS
![5](https://user-images.githubusercontent.com/29708612/70374325-0142b780-1902-11ea-9e6c-45f93deb0a0d.jpg)

**Comment by JIMENOFONSECA** [comment]
@kerembeygo we will be adding all this information in the days to come. The next version should have a more thorough description of all the values in CEA. closing this issue for now.
