### ISSUE TITLE
Refactor `usage_schedules` to a more sane structure

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#249]
The `usage_schedules` dictionary (as passed to the `calc-thermal-loads` models) has the following shape:

```
{
            'list_uses': ['ADMIN', 'GYM', ...],
            'schedules': [ ([...], [...], [...], [...]), (), (), () ]
}
```

Each element of the 'list_uses' entry represents a building occupancy type.
Each element of the 'schedules' entry represents the schedules for a building occupancy type (in the same order as they appear in the 'list_uses' entry).
The schedules for a building occupancy type are a 4-tuple (occupancy, electricity, domestic hot water, probability of use), with each element of the 4-tuple being a list of hourly values (8760 values).

This dictionary is built in the `maker.schedule_maker` function based on the `Archetypes_schedules.xlsx` file.

A more sane format for the same information would be:

```
{
    'ADMIN': {
        'occupancy': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.16, 0.32, ... ],
        'electricity': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.16, 0.32, ... ],
        'dhw': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.16, 0.32, ... ],
        'use': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.16, 0.32, ... ],
    },
    'GYM': {
        'occupancy': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.16, 0.32, ... ],
        'electricity': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.16, 0.32, ... ],
        'dhw': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.16, 0.32, ... ],
        'use': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.16, 0.32, ... ],
    },
    ...
}
```

In such a scheme, indexing one of the value lists would be done like:  `usage_schedules['ADMIN']['occupancy']` and the 'list_uses' member is as easy as `usage_schedules.keys()'.

We should track down each usage of this structure and replace it with the more sane approach. Or, maybe even create a class structure in the `maker.schedule_maker` function and return that. While we're at it, rename the `maker` module to `schedules`?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA are you ok with this?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas list_uses is used in several scripts to short-list the uses needed in the case study. Please bear this in mind when doing the changes.  Take a look at the calc_mixed_use function. You might have to restructure this and several other functions around. Otherwise I am ok with the other changes.

**Comment by daren-thomas** [comment]
good point! i guess `list_uses` becomes `uses.keys()` in the proposed structure above. But maybe we do a more OO approach and actually bang out some classes for this. I will tread carefully!

**Comment by daren-thomas** [comment]
This has to be moved until after @gabriel-happle has made his changes!

**Comment by JIMENOFONSECA** [comment]
we won't have this.
