### ISSUE TITLE
URGENT-changing inputs in CEA not working because of schedules

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2490]
@daren-thomas this could not come at the worse time. We were going to present this in NY. The interface (input-editor) does not save any change. The error in the console is the next:

I run data helper already

The version I am using is developer v2.26.0 Downloaded and installed today.

![image](https://user-images.githubusercontent.com/8973186/70374639-db62e600-18f4-11ea-9563-c7ead1ddfc51.png)

**Comment by daren-thomas** [comment]
this seems to work on the test-realeases (2.27.0a*) that i'm creating. i think we can close this issue.
