### ISSUE TITLE
GUI: Setting data management tools options when creating a new scenario UX

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2494]
The UX (User eXperience) of the workflow for creating a new scenario when choosing the weather-helper's (or any of the other helpers') settings is not intuitive:

- open project
- create a new scenario
- choose "Generate new input files using tools"
- select all the Data Management Tools
- open up options

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/8e17fc58-0d35-40d1-92f6-d2e6bf84d9b6)

The issue here is the bottom row of the dialog: The buttons are labeled "Back", "Save to Config", "Default". The user is then supposed to edit the values, click "Save to Config" and then click "Back".

Instead, the user should have the following buttons:

- "Cancel": Closes the dialog, no changes are made, behavior is exactly the same as "Back"
- "Load default settings": All the parameters are set to the `default.config` values, behavior is exactly the same as "Default" - we could also just leave this button, but change the position
- "Save & Close": In addition to the "Save to Config" behavior, the dialog should close.

**Comment by reyery** [comment]
@daren-thomas  could you help me check if this is solved in this PR https://github.com/architecture-building-systems/CityEnergyAnalyst-GUI/pull/9

**Comment by daren-thomas** [comment]
checked: this is solved in release 2.28.1
