### ISSUE TITLE
GUI: hidden parameters with invalid input silently block running scripts

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2500]
When parameters have invalid data, the GUI adds a red outline marker. Some parameters are collapsed though, and this outline marker is hidden:

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/46731b42-c866-4931-849a-864e93c4ca54)

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/dd2edff4-aa04-441d-a23a-cd9b175be4f8)

This is confusing for the user, as the "Run Script" button doesn't work without any visual indicator as to what's wrong.

Steps to reproduce:

- open GUI, select project, select scenario
- rename folder `Daysim` in `C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies` to `Daysim.bak`
- run tool "Building Solar radiation"

(afterwards, rename the `Daysim.bak` folder to `Daysim` to get the system working again)

**Comment by JIMENOFONSECA** [comment]
@reyery can we take a look at this?

**Comment by reyery** [comment]
Fixed in https://github.com/architecture-building-systems/CityEnergyAnalyst-GUI/pull/9
