### ISSUE TITLE
Fails to export Grasshopper geometry to shapefiles

### ISSUE THREAD

**Issue by DespaxJulien** [architecture-building-systems/CityEnergyAnalyst#2501]
Hi,

I tried to export simple Grasshopper geometry to SHP files following [your last blog article](https://cityenergyanalyst.com/blog/2019/12/12/grasshopper-to-cea-part-3-exporting-gh-geometries-to-shapefile).

The Shapefile Export component does not work (see attached picture). 

Do you know what might be causing the problem? I'm running RhinoV6.
Thanks for your help.

Best,
Julien

![image](https://user-images.githubusercontent.com/51714760/71905681-ecf41380-3168-11ea-80c4-dfdbe4471ada.png)

**Comment by daren-thomas** [comment]
@shizhongming would you mind having a look please?

**Comment by shizhongming** [comment]
@DespaxJulien 
Hi Julien,
Thanks for the feedback. I think the reason may be that you drew your polylines in Rhino and referenced it in Grasshopper. Try using GH components to create the geometry and see if it works. Let me know!
Regards, Zhongming
