### ISSUE TITLE
Minor bug in VCC cost calculation: calculation breaks down if chiller size is exactly the maximum

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2509]
Two `if` statements are not compatible, making the code break down if the chiller size is exactly equal to the maximum chiller size in the database:

line 101 in `chiller_vapor_compression.py`
```
 if Q_nom_W <= max_chiller_size:
            VCC_cost_data = VCC_cost_data[(VCC_cost_data['cap_min'] <= Q_nom_W) & (VCC_cost_data['cap_max'] > Q_nom_W)]
```

first line accepts `Q_nom_W == max_chiller_size`
second line is looking for `Q_nom_W < max_chiller_size` 
(`max_chiller_size = max(VCC_cost_data['cap_max'].values)`)

one of the lines has to be changed.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle you can change it to Q_nom_W < max_chiller_size
