### ISSUE TITLE
move Heating/Cooling season to a non northern-hemisphere-based system

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#251]
Currently, the heating/cooling season description (`gv.is_heating_season`, `gv.seasonhours`) is based on the assumption that winter is in December and summer in July. This is only true for the northern hemisphere. And the tropics don't have heating/cooling seasons, so, we need a smarter way to do this.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I would like to hear your thoughts on this...

**Comment by JIMENOFONSECA** [comment]
I will include the gv.season_hours as input parameters in the demand script. This is something that the user should specify always. I imagine this as a calendar option, where first, the users selects if there is heating season (a tick box), i the tick box is activated. the user should select the beginning and end of the heating season. i.e., 12.09.16    -    15.05.17. if the user does not indicate anything (the tickbox is off). then we will consider the entire year as cooling and no heating...

**Comment by daren-thomas** [comment]
does it make sense to include a cooling season and a heating season?
also, `season_hours` is a bit confusing as a name... can we refactor the code a bit? I propose:

- gv contains `start_date_heating_season`, `end_date_heating_season`, `start_date_cooling_season`, `end_date_cooling_season`.
- this get's translated to two ndarrays of booleans: `is_heating_enabled` and `is_cooling_enabled`

what do you think?

**Comment by JIMENOFONSECA** [comment]
yep we an transform it to boolean. what is necessary is to include a new modification to the demand toolbox GUI. see my last comment on how it could be.

yes, it is necessary. heating season and cooling season mean "politically" when you are allowed to heat your building or cool it down. USA, europe (depending on the country) have an specific way to deal with these dates.

**Comment by daren-thomas** [comment]
OK. So I will implement it like that in a branch `i251-heating-cooling-seasons` including an option for the gui.

**Comment by gabriel-happle** [comment]
Please wait for my major changes in demand calculation. Thank you.
#220

**Comment by daren-thomas** [comment]
moving this to next milestone as it might interfere with @gabriel-happle 's work

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this still required?

**Comment by daren-thomas** [comment]
@gabriel-happle - how would this now work? do we want to sit together and look at it?

**Comment by JIMENOFONSECA** [comment]
I see this is something we should definately have to run CEA for Singapore and other locations... chanign to priority 1

**Comment by JIMENOFONSECA** [comment]
The solution will be to select these parameters from the interface in arcgis of the demand script. It should give the option to the user of a calendar to indicate when the heating season starts and ends, when the cooling season starts and ends. and..if there is a heating season or not, and if there is a cooling season or not.

**Comment by daren-thomas** [comment]
OK. I have a problem here. @gabriel-happle do I understand this correctly: we don't actually have any way to indicate cooling season? it's just defined as not-heating-season?

And how does the `seasonhours` work?

I'm trying to refactor this into four dates:

- heating-season-start
- heating-season-end
- cooling-season-start
- cooling-season-end

and the option to set them to blank / None or something if no heating season or cooling season can be defined. or even better: like @JIMENOFONSECA said, two more variables:

- has-heating-season
- has-cooling-season

These variables will be part of the configuration file cascade that I'm busy making.

**Comment by daren-thomas** [comment]
Also. Assuming we assign a date to `heating-season-start`: e.g. `2017-08-01`. Which hour is this then? first hour in the day? last hour in the day?

**Comment by daren-thomas** [comment]
Check out PR #671 (cascading configuration files) - this includes a unittest that replaces the current `gv.is_heating_season` function with one that works on the four dates described above.

Oh. BTW. we don't have a cooling season. And the bounds are not clear. Can @gabriel-happle and @JIMENOFONSECA take a look??

**Comment by gabriel-happle** [comment]
@daren-thomas the original definition of the cooling and heating season was directly given as hour of the year in the globalvars. So maybe from there we can check which hour is exactly meant.
`self.seasonhours = [3216,6192] `  should be 00:00 on that particular day.
Yes, we do not have cooling season and heating season, from what I understand is that there are legal rules on when you are allowed to start heating your building in Switzerland. 

But I agree, we should be able to define four dates.
And maybe also some temperature rules, like the ones mentioned below:


https://www.hausinfo.ch/de/home/recht/mietrecht/nutzung/heizen.html

**Comment by daren-thomas** [comment]
@gabriel-happle how do we proceed? I don't think we can make this milestone - we'd need to test. I have a unittest in the branch that shows an example of calculating the `gv.is_heating_season` function. I don't think the opposite is necessarily cooling season either... and rules would be good, of course!

**Comment by gabriel-happle** [comment]
I also don't think we can make this milestone

**Comment by gabriel-happle** [comment]
@daren-thomas do you still want to do this in the May sprint? Or move it to the next one? Should we talk next week?

**Comment by daren-thomas** [comment]
@gabriel-happle yes, let's talk. No. I think we should move it to the July sprint and use the rest of the may sprint to finish testing the stuff we already coded - as opposed to starting new stuff. BUT, I do think we could start thinking about it now...

**Comment by daren-thomas** [comment]
OK. So... 

- we need to move `gv.is_heating_season` usage in `calc_simple_temp_control` to use the version in `helpers`.
- use demand sections to figure out if heating season or not (same for cooling season)
- main thermal loads function uses this:

```
 def get_hours():
    ...:     t = 6000
    ...:     for i in xrange(8760):
    ...:         yield (t+i) % 8760
```
and we figure out starting t based on some logic tbd

**Comment by daren-thomas** [comment]
we decided: we need a region-specific database for heating and cooling seasons. maybe even a control systems database (can we maybe do this in an incremental issue?).

Long term target for refactoring: A HeatingController and CoolingController?
