### ISSUE TITLE
Not sure if bug: cooling tower cost calculation uses capacity of chiller for calculation

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2510]
the function `calc_generation_costs_capacity_installed_cooling` in `cost_model.py` uses the capacity of the VCC chiller to calculate the costs of the cooling tower for air-source-systems.
Not sure if that is intended or not.
Could you please help @JIMENOFONSECA or @shanshanhsieh?
I can fix it myself, if it is not intended.

e.g. line 566, line 5856 and line 605

```
        # VCC
        Capex_a_VCC_USD, Opex_fixed_VCC_USD, Capex_VCC_USD = VCCModel.calc_Cinv_VCC(Capacity_PeakVCC_AS_W, locator,
                                                                                    'CH3')

        # COOLING TOWER
        Capex_a_CT_USD, Opex_fixed_CT_USD, Capex_CT_USD = CTModel.calc_Cinv_CT(Capacity_PeakVCC_AS_W, locator, 'CT1')
```

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle right, we size the cooling tower proportionately to the capacity of the VCC. so, in my opinion, the code is ok. closing the issue.

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA, not sure if there is a misunderstanding. Right now the cooling tower are exactly the size of the chiller. according to my understanding, the cooling tower capacity should be slightly larger.

**Comment by JIMENOFONSECA** [comment]
Well. We just assumed them to be the same in this case. But feel free to improve it, should you find a better method.

________________________________
