### ISSUE TITLE
Not sure if bug: Centralized chiller cost calculation seems to use decentralized values

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2512]
E.g., line 562 in `cost_model.py` uses chiller type `CH3` to look up values from the databases.

According to `optimization\constants.py` :
```
VCC_CODE_CENTRALIZED = 'CH1'
VCC_CODE_DECENTRALIZED = 'CH3'
```

Not sure if this is a bug or intended. I can fix it if someone can tell me what should be the intended behavior.

**Comment by JIMENOFONSECA** [comment]
oh really? It should use the centralized values. sure you can change that. @shanshanhsieh can you confirm this is the case?
