### ISSUE TITLE
UX: add update function to installer

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2514]
So, it is very difficult to do get an update of CEA, one needs to uninstall and reinstall the entire CEA. The best would be to have autoupdates (today's technology) however this may be complicated due to the different users we have in CEA. 

So a compromise is to at least make an installer that offers the update function. and somehow an automated messagge that informs our users at the interface that a new update is available and that they can download the new version of CEA.

**Comment by JIMENOFONSECA** [comment]
@reyery mind getting this into the pipeline together with @daren-thomas  so both the interface and the code have the option to be updated to a newer version from the installer?

**Comment by reyery** [comment]
@daren-thomas , from what I understand from our current installer, non-dev users have CEA installed using pip.
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/3b777c4a23ab7dc0ef8a1d493af022d549ea21f9/setup/cityenergyanalyst.nsi#L179
So I assume users could actually update their version by running `pip` without using the installer, which could avoid having the users to re-download the huge dependencies file? (That is assuming any new dependencies could be added and installed in `setup.py`)
In that case, we could put the update logic in CEA itself where you could type `cea update` instead of the installer.

**Comment by reyery** [comment]
I tried writing an `update` script for CEA to run `pip install`, but there seems to be some permission error that I can't figure out. Running the same command in console does not seem to give the error.

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/5d488b12546f5915a24ad0e7a49e285144d8f4a9/cea/interfaces/cli/update.py#L70

```
Installing collected packages: cityenergyanalyst
  Found existing installation: cityenergyanalyst 2.28.0
    Uninstalling cityenergyanalyst-2.28.0:
      Successfully uninstalled cityenergyanalyst-2.28.0
ERROR: Could not install packages due to an EnvironmentError: [Error 5] Access is denied: 'c:\\users\\admin\\appdata\\local\\temp\\pip-uninstall-s8mqkj\\cea.exe'
Consider using the `--user` option or check the permissions.
```

**Comment by daren-thomas** [comment]
@reyery, that's expected: `cea.exe` is one of the things pip creates. so we can't use the `cea` / `scripts.yml` mechanism to run that script. it shouldn't be much of a problem, though, right?

How are you planning for the user to use this feature?

**Comment by reyery** [comment]
It would be nice if the user could just type `cea update` to update CEA but it's not huge issue. I could just move it out and run it as a separate python script. It could be launched from a `batch` script for windows, just like how `dashboard` script was launched previously from a shortcut.

From the GUI, it could run the `batch` script to initiate the update process. It would also need to make sure that CEA and the GUI are not running before it can update the relevant files. 

I was wondering if the update 'script' should be written purely using `batch`/`bash`, which would be one way of solving `python.exe` being overwritten for `Dependencies.7z`.

**Comment by daren-thomas** [comment]
@reyery - we could use something like `PyInstaller` to create an exe from a python script. That would solve the overwriting problem, no? (writing the update script in bash / cmd has it's own problems and will be a lot harder to maintain. also, it'll make downloading stuff harder - we _do_ ship curl, but we also want to check different urls etc.)

**Comment by daren-thomas** [comment]
Are we still doing this? (@JIMENOFONSECA, @reyery)

**Comment by JIMENOFONSECA** [comment]
@reyery @daren-thomas after our meeting with the Project Sponsor and the DevTeam, It seems we will have to leave it aside. @reyery mind commenting the reasons why we did not make it at this time and closing the issue? thanks!

**Comment by JIMENOFONSECA** [comment]
@reyery if you want to add your comments. We are closing this issue now
