### ISSUE TITLE
errors running solar radiation

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2531]
Hi all,

I am re-running some old CEA models, due to the updates in the last months. I only kept the building-geometries, age.dbf and occupancy.dbf. I was able to run all the Data Management tools and the schedule helper.
But when I go to run the radiation radiation module, either of the two things happen:"
A) CEA gives an error while Creating 3D building surfaces (ValueError: ERROR: this usually happens when buildings do not overlap with the terrain, try to check if this is the case). Not sure what can be the issue here, since those geometries were used fine in the past.
B) It keeps "stuck" in the step of "Reading terrain geometry", even if I leave it for a long time. The simulation doesn't progress from that point.

I hava attached two case studies (below), each one where one of those situations are happening.
Can you check weather you have the same issues on your side and possibly advise on that?
https://we.tl/t-OQ87UkUHlJ

Thanks!

**Comment by JIMENOFONSECA** [comment]
@lguilhermers the problem should be the coordinate system of your files. In addition the terrain of the buildings may not be overlapping. I suggest to 
1. rerun the terrain helper for that case study.
2. check that you can map the buildings on the terrain using Qgis.

**Comment by lguilhermers** [comment]
@JIMENOFONSECA thanks for the insights.
I tried again those steps, also with new models and the error persists. 
The terrain helper always runs smoothly. Looking at QGis I noticed two things (picture below):
a) although the zones are positioned correctly, the CRS for the new one is 32748, while previously it seems that 32648 was the one being used. If I try to change the CRS system, it puts the old zone in the wrong position in QGis/ CEA. I also tried changing only the .prj file, without success.
b) the terrain looks a continuous vertical stripe from the zone. Probably an error caused by running terrain helper with those different projections highlighted in (a), but not sure...

![image](https://user-images.githubusercontent.com/50981039/73246858-9c615a80-41ea-11ea-89a1-e558d804569b.png)

I see that street helper is also not being completed (gets stuck in "generating streets from Surroundings Geometry" - see Tanjong Pagar and Yushun file attached if necessary). For solar radiation, the new cases get stuck in "Reading terrain geometry", as I said before.
Files tested can be found here: https://we.tl/t-HkF2fLtf7l

The new cases are all based on old cases I was running before, so I am not sure how the coordinate system could have been changed but hopefully those new tests brings some insights.

**Comment by lguilhermers** [comment]
@JIMENOFONSECA thanks for the insights
Together with @emanuel030 we were able to fix the projection, which was what was causing issues. The old files were projected in 32648 while the new ones are in 32748.
I think by fixing this the rest of the helpers/ daysim are able to run fine.
