### ISSUE TITLE
Thermal Network Graph: plant node, the position should be done by the user

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2535]
Taken from #2469

**Comment by daren-thomas** [comment]
Allow the user to select where the plant goes. @reyery feel free to recruit help here.

**Comment by JIMENOFONSECA** [comment]
This type of customization can easily be done with Qgis. The user can take the network layout output file "it is a shapefile" It is saved in outputs/networks/DH/node.shp. Then the user can add a new node in QGIS and assign it the name of "plant" in the attribute table. The user can also use QGIS to modify any part of the network. The user needs to make sure that the node is inside the edges of the network. For this, the user needs to check this by overlaying the edges file located in  outputs/networks/DH/edges.shp
