### ISSUE TITLE
Blog: How to create and save your own databases?

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2537]
- documention on what needs to be done
- GUI should provide a workflow
- how to share it with the community when done?

**Comment by daren-thomas** [comment]
blog this once GUI (#2536?) is created

**Comment by JIMENOFONSECA** [comment]
@daren-thomas it is ready, the blog can go ahead.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA have you found time to check the draft?

- https://daren-thomas.github.io/cea-databases-part-1/
- https://daren-thomas.github.io/cea-databases-part-2/
- https://daren-thomas.github.io/cea-databases-part-3/

**Comment by JIMENOFONSECA** [comment]
@daren-thomas good job on putting this together. I think that as part of the new structure of the documentation. we should migrate the content of these blogs to read the docs. If you agree. please publish it in there. Otherwise please proceed to Squarespace.

**Comment by daren-thomas** [comment]
status update: i'll add to the documentation when updating the tutorials. this will take quite some time

**Comment by AlexJew** [comment]
@daren-thomas If I may just add a comment, in Part 2, after the change in the database ASSEMBLIES/ENVELOPE/CONSTRUCTION, it would be good to add that you need to save the change (click on "Save Databases"). Otherwise, the change isn't registered and you can not use that newly defined value in the Input Editor. 

I have been reading your texts in advance as I am trying to get my head around how to use the Database Editor

**Comment by AlexJew** [comment]
If I could give a suggestion; it would be good to have an explanation about the schedule for the cases of PROCESSES, ELECTROMOBILITY, SERVERS, WATER, LIGHTING and APPLIANCES. It is hard to understand what is the unit and what we are talking about. Also an explanation of the values in USE-TYPES > Properties would be really helpful. Thank you very much for your work, it is of such a huge help in my project!

**Comment by shanshanhsieh** [comment]
@daren-thomas can we close this issue?
