### ISSUE TITLE
Create a structure of the Documentation

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2541]
- who are the users?
- structure?
- what do we have? how to move?
- API Documentation - what's the state there?
- bug everyone about glossary.csv TODO stuff!!!!

**Comment by JIMENOFONSECA** [comment]
@daren-thomas updates on this?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I haven't gotten around to it yet.

**Comment by daren-thomas** [comment]
Next Action: Rebuild the glossary page in RTD - a lot of the locators have changed and I want to be sure we're picking up the correct information (I noticed yesterday that it isn't current).

Further steps:
- check each tutorial, update as necessary
- update the zenodo reference for citing the CEA (@JIMENOFONSECA maybe you can do this?)
- update `schemas.yml` using workflow tracing output (some of the locators changed)
- document how `schemas.yml`, `inputs.yml` and friends work together and what they influence (this will help onboarding new developers/contributors)

Bonus points:
- add `glossary.csv` tests to the unit tests (fail when a TODO is found - that will make it easier to avoid missing documentation in the future)

**Comment by JIMENOFONSECA** [comment]
Glosary unit tests is the best idea i have heard in some time. Totally go for it now. Especially if we can just kill that glossary and get a unified schemas.yml, a single point of atructured reference to variables.

**Comment by daren-thomas** [comment]
Status update: Working on this in #2637

**Comment by shanshanhsieh** [comment]
@shanshanhsieh is going to check the following points:
- check each tutorial, update as necessary
- update the zenodo reference for citing the CEA
- update `schemas.yml` using workflow tracing output (some of the locators changed)
