### ISSUE TITLE
Total demand file not created

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#2543]
I have run the demand script for a new scenario in SG. The single demand file of each building is created but the total demand file is not. I am not an administrator on the machine from which im running it, might this be the problem? ![image](https://user-images.githubusercontent.com/26175926/73060692-6020b800-3ed3-11ea-9b3b-84e45fa46295.png)

**Comment by daren-thomas** [comment]
can you manually create a file there? `C:\Users\emanuel\AppData\local\temp`? maybe with notepad or something. I wonder if that file is being deleted somehow?

**Comment by emanuel030** [comment]
I can create a file manually in `C:\Users\emanuel\AppData\local\temp`. The scenario was set up fresh, here is the config file and scenario anyway: https://we.tl/t-i2QPE4EIR4

**Comment by emanuel030** [comment]
Unfortunately the error is still prevailing, even though I now have admin rights to the machine. What else could be causing this error?

**Comment by daren-thomas** [comment]
@emanuel - this looks like the exact same error you got on Euler. Could this be an issue _not_ with Euler, but with the demand script itself?

**Comment by daren-thomas** [comment]
@emanuel - would you mind sending me a sample case study that _doesn't_ work? that ends with this error message?

**Comment by emanuel030** [comment]
It is a weird one. The demand script is currently working both in Euler and on the desktop without errors. Therefore I don't think it scenario dependent. Here is one scenario where the error appeared at one point https://we.tl/t-cPeWp510Ag but is not appearing now. I believe it is dependent on the file size and some kind of storage limit of the temp folder?! Would it be possible to store the temporary csv files in a different folder?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas maybe we can also return the total.csv files from the demand calculation, keep them in memory and then output the results? In this way we avoid the use of a temporary folder? what do you think?

**Comment by JIMENOFONSECA** [comment]
@emanuel030 I wonder if your are running CEA in debug mode = True. This is not recommended since it is creating extensive xls files which are not necessary.

**Comment by emanuel030** [comment]
I have tested multiple scenarios (also larger), both with and without the debug mode and they have completed successfully on Euler and on PC. Debug mode taking roughly twice as long or longer (1035 seconds vs 490 seconds/ 850sec vs 260sec). The error has not shown and I wouldn't know how to recreate it.
