### ISSUE TITLE
ERROR: zone_helper: invalid literal for int() with base 10: '2017-11'

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2547]
Steps to reproduce:

- create new project / scenario
- choose all helpers (I think this is only a problem with the zone-helper, though)
- select the area indicated in the screenshot (search for "kleinalbis" in the location search bar)
- try to create scenario

Expected the scenario to be created. I think the OSM might be providing age data in the form "YYYY-MM" and that the zone-helper expects it in the form "YYYY", but that is only a guess.

Full Error: 

```
Traceback (most recent call last):
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\dashboard\api\project.py", line 189, in post
    cea.api.zone_helper(config, scenario=new_scenario_path)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 263, in main
    zone_helper(locator, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 145, in zone_helper
    calculate_age_file(zone_df.copy(), year_construction, age_output_path)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 227, in calculate_age_file
    data_floors_sum_with_nan = [np.nan if x is np.nan else int(x) for x in zone_df['start_date']]
ValueError: invalid literal for int() with base 10: '2017-11'
```

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/2a15a03f-c337-4d34-9caf-3ffdbc7913ef)

**Comment by JIMENOFONSECA** [comment]
Yes, that is right. We will need to add more validation rules to the Zone helper. let's take a look to who can do this next sprint.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas we got a new one from Arno this morning...
<img width="1440" alt="Screenshot 2020-02-04 at 18 46 10" src="https://user-images.githubusercontent.com/8973186/73812423-aea94d00-4817-11ea-8d81-7d12bef7ecaa.png">

**Comment by reyery** [comment]
Since we are using `start_date` key of OSM data to find the year of buildings, we need to take note of the various [formats](https://wiki.openstreetmap.org/wiki/Key:start_date#Formatting) that are supported by OSM and parse them accordingly before casting instead of casting it directly (should be easily done using regex). This should also apply to any other key that we are referencing such as `floors`.

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/39e209f080ef30f78344b1277484650d769606bf/cea/datamanagement/zone_helper.py#L221-L236

Also, I think the variable name `data_floors_sum_with_nan` needs to be changed.

**Comment by reyery** [comment]
Just found this website and it seems kinda cool (https://taginfo.openstreetmap.org)

We can see the different types of values used in the `start_date` key [here].(https://taginfo.openstreetmap.org/keys/start_date#values)

**Fun fact**:
 `2017-11` occurs 152 times out of ~14 million values and these are the places in Zurich that has this value
![image](https://user-images.githubusercontent.com/34395415/73839397-db2d8b00-4850-11ea-97cf-f5ff14b0cdfb.png)
My best guess is that this is the building that created the error from Arno
![image](https://user-images.githubusercontent.com/34395415/73839637-71fa4780-4851-11ea-8678-eeb70714b8c4.png)

Ok back to work.

**Comment by JIMENOFONSECA** [comment]
Hahahaha, gee that is what i call a casuality. This proves how hard is to make a bullet proof software. A chances of 10.95 in one million :D
On 5 Feb 2020, 20:02 +0800, Reynold Mok <notifications@github.com>, wrote:

Just found this website and it seems kinda cool (https://taginfo.openstreetmap.org)

We can see the different types of values used in the start_date key [here].(https://taginfo.openstreetmap.org/keys/start_date#values)

Fun fact:
2017-11 occurs 152 times out of ~14 million values and these are the places in Zurich that has this value
[image]<https://user-images.githubusercontent.com/34395415/73839397-db2d8b00-4850-11ea-97cf-f5ff14b0cdfb.png>
My best guess is that this is the building that created the error from Arno
[image]<https://user-images.githubusercontent.com/34395415/73839637-71fa4780-4851-11ea-8678-eeb70714b8c4.png>

Ok back to work.

**Comment by reyery** [comment]
And `2017-11` is only one such example that we will not be able to do direct casting. There were also some values that use Chinese characters to represent the date.

**Comment by JIMENOFONSECA** [comment]
fixed to master
