### ISSUE TITLE
`scenario-name` parameter in config should not accept empty/null values

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2549]
Problem
-
Currently the GUI sets `scenario-name` to an _empty string_ when doing some operations regarding projects using the dashboard server endpoints:
- **create new project** - no scenario exists yet
- **open project** - we do not assume which scenario to open for the user
- **delete project/scenario** - no scenario exists anymore

In the GUI, the user is restricted from doing anything, such as running scripts, when `scenario-name` is an _empty string_ by blocking navigation to such functions since it would undoubtedly cause issues.

However this logic only exists in the front end and not in other interfaces such as **cli** or **grasshopper** which might cause issues when using them to run scripts. The _empty string_ generates a valid `scenario-path` (i.e. the project folder) and causes scripts to look for files in the project folder instead where it will definitely not find them.

Proposed solution
-
The config file should be able to accept a scenario name as a valid input which might not exist in the project path  but not an empty / `null` value, since it does not make sense for it to be an empty value (wish I realized that earlier when making the GUI). With a non empty `scenario-name`, we could use it to check if the scenario path exists before running script while an empty `scenario-name` would just give us a false positive.

Therefore, for scripts we could add to check if the scenario path exists before running it, which could save time tracing missing input files and provide a more useful/explicit error message instead of listing them like this 
```
ERROR: Missing input files:
- C:\CEA PROJECTS\reference-case-open - demo\inputs\building-geometry\zone.shp
- C:\CEA PROJECTS\reference-case-open - demo\inputs\building-properties\age.dbf
- C:\CEA PROJECTS\reference-case-open - demo\inputs\building-properties\occupancy.dbf
```
(not apparent that `scenario-path` does not exist just by reading that)

As for the GUI, it will have to use some kind of state within itself to support such operations and **not** use the config file and the empty string approach.

**Comment by daren-thomas** [comment]
@reyery just wondering - what if the CLI added a check right before the missing input files check for a valid path to the scenario? (I'm asking, because having the `cea.config.Configuration` file making sure the scenario exists could end up being very tricky as there are many edge cases - as you explain above) - or emit a `WARNING: scenario-name is empty`?

I also think the GUI should maintain project / scenario state - that way it doesn't really have to save the config file ever unless the user presses the "Save Config" button in the tool dialog.

**Comment by reyery** [comment]
Hmm. I'm not saying that the config should "make sure the scenario exists" but at least make sure that `scenario-name` is not empty, since that does not make sense (it would just point to the project path). Then again like you said, we could just check in scripts/CLI that `scenario-name` is not empty which would be easier.

And yes the GUI **should** maintain its own project/scenario state and not save to the config unless explicitly by the user. I should have realized that from the start :(

**Comment by shanshanhsieh** [comment]
@reyery what is the status of this issue?

**Comment by reyery** [comment]
@shanshanhsieh I have not started on this yet. Will get to it soon once I finish up the other issues.
