### ISSUE TITLE
Building Solar Radiation : Error if loading a terrain projection UTM 29 N, but successful with UTM 29 S

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2558]
Hello,

I am trying to use the Building Solar Radiation toolbox, however the following error is raised. 

ValueError: ERROR: this usually happens when buildings do not overlap with the terrain, try to check if this is the case

All my files are referenced in WSG 874 / UTM 29N. My terrain file is a 5x5m grid as recommended.

Thank you for your help!

[Inputs.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4191795/Inputs.zip)

**Comment by AlexJew** [comment]
I generated a fixed elevation terrain with the **Data Management > Terrain Helper** tool and realized that the projection was UTM 29S (though my neighbourhood is in Portugal). By loading my terrain file using the UTM 29S projection, the Build Solar radiation tool ran successfully. I believe there must be a bug where the UTM 29 N projection is read as 29 S. This only happens with terrain files (or .tif files), as my zone.shp and district.shp files were properly projected, no matter whether their projection was UTM 29 N or 29 S. 

Here are the succesful inputs .

[Inputs_2.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4192200/Inputs_2.zip)

**Comment by reyery** [comment]
> I believe there must be a bug where the UTM 29 N projection is read as 29 S

Ah thanks for that insight @AlexJew. I will take a look into that and see what I can do to fix it.
