### ISSUE TITLE
Radiation script throws errors if Daysim binaries are found in a path containing whitespaces

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2564]
Some of the binaries for Daysim (e.g. `gen-dc`) make use of information found in a `.hea` (header) file to get its parameters, such as `bin_directory`. However, these binaries are not able to parse path parameters correctly from the `.hea` file if the path contains whitespaces. Since this buggy behavior is caused in the binary code of Daysim there is nothing much we can do on the Daysim side unless we want to fix it and submit a PR to their repo.

This would mostly likely affect users with whitespaces in their username who install CEA in the default path (i.e User Documents) using the Daysim binaries that we ship with CEA. Easiest way to solve this issue would be to check the path of Daysim for any whitespaces before running the Radiation script and warn the user to copy/move the binaries to some other path such as `C:\`

![image](https://user-images.githubusercontent.com/34395415/74621194-fa90b600-5176-11ea-82f1-1d7cba208287.png)

**Comment by daren-thomas** [comment]
@reyery there is already code in the radiation tool checking for existence of the Daysim binaries - maybe we add the check there? The user could get a warning and just have to install Daysim herself (defaults to `C:\Daysim\bin`)
