### ISSUE TITLE
Temperature of R-C model out of bounds

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2567]
Hello,

I've been trying to run CEA's Building Energy Demand Tool, but the following error comes up, no matter the building : 
_« Exception: Temperature in RC-Model of building IE001 out of bounds! First occured at timestep = 4737. The results were Tint = 54.3371290227, theta_c = 49.2210335175, theta_m = 40.0318735086, Check building geometry and internal loads! Building might be too small in size or architecture parameter Hs_ag = 1.0 might be too small for this geometry. Current bounds of range for RC-model temperatures are between -30.0 and 50.0. »_

As you can see, I have already tried to raise the Hs_ag value to its maximum. Also, I know that this tool doesn´t run properly with small buildings, however in this case the building´s area is 217 m2 and its GFA is 871 m2 (the other buildings have similar characteristics). 

I am currently using the default CH values from the archetype database, though the neighbourhood is in Lisbon. I was planning on changing these values later on. What do you suggest? We have already tried changing the **U_roof(T1) to 0.6** and **the U_wall(T5) to 0.8**, but it resulted in the same error.

Here´s a link with the scenario folder. The radiation tool was already ran successfully. 

https://drive.google.com/drive/folders/1xlERvPzj7UDndeEgC0e10fLITmKxpFqN?usp=sharing

I have also wanted to visualise the values computed by outputing an excel file, but I wasn't able to find that option in CEA's current version.

**Comment by JIMENOFONSECA** [comment]
@AlexJew I found that your buildings do not have air-con for cooling in air-conditioning systems. It may be happening that your building is overheating an no A/C is available. can you try again with this config and let us know?

**Comment by RicardoGomesIST** [comment]
Hi Jimeno,
thank you for your fast reply.
I am working together with Alex on this. 
We already tried this:
-- High U values for walls and roofs (1.5 and 1)
-- T19 and T20 for type_cs (supply systems)
--T2 for type_cs (air conditioning)
-- high leakage values (5 h-1)
--cool starts: January....
-- cooling always on with just setpoint at 26ºC
-- no internal gains
-- Zero window wall ratio
-- we deleted the zone and tried and the error appears again on the subsequent zone.

I am running out of options here...

Thank you!

**Comment by gabriel-happle** [comment]
Dear @RicardoGomesIST and @AlexJew,
I tracked down this issue.
Unfortunately, it is not related to any building properties. That's why your changes had little influence.

This issue is related to some calculations with the weather file to get the sky temperature for the long-wave radiation exchange of buildings with the sky.
There was a small bug in the calculation that is now fixed in #2570 #2571.
It caused unrealistic values in net solar heat gains for isolated hours of the year (in your case e.g. in hour 4737) that make the building energy model break down.

Thank you for reporting this bug!

**Comment by AlexJew** [comment]
Thanks @gabriel-happle ! Since the bug originates from CEA, I guess I need to wait for the next version to be uploaded with the bug fixed right?

**Comment by AlexJew** [comment]
Hi @gabriel-happle , is it normal that I don't see any weird value in the radiation excel file for the IE001 building (the building that causes the first bug)?

![imagem](https://user-images.githubusercontent.com/32110882/74731413-d2b95500-523f-11ea-8c2a-41ae92e04928.png)

If needed, here is a selection of the excel files I obtained for the radiation (though probably the same as yours):


[solar-radiation - Copy.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4218879/solar-radiation.-.Copy.zip)

**Comment by gabriel-happle** [comment]
> 
> 
> Thanks @gabriel-happle ! Since the bug originates from CEA, I guess I need to wait for the next version to be uploaded with the bug fixed right?

Yes. The bug has been fixed here #2571. If you are using the developer version of the CEA you can update via GitHub. Otherwise, you have to wait for the next release.

**Comment by gabriel-happle** [comment]
> 
> 
> Hi @gabriel-happle , is it normal that I don't see any weird value in the radiation excel file for the IE001 building (the building that causes the first bug)?
> 
> ![imagem](https://user-images.githubusercontent.com/32110882/74731413-d2b95500-523f-11ea-8c2a-41ae92e04928.png)
> 
> If needed, here is a selection of the excel files I obtained for the radiation (though probably the same as yours):
> 
> [solar-radiation - Copy.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4218879/solar-radiation.-.Copy.zip)

Yes @AlexJew, that is normal. The bug was related to the re-radiation. I.e. the heat loss due to radiation from the building to the sky, not the heat gains from solar radiation.

**Comment by AlexJew** [comment]
Hi @gabriel-happle  , thanks for the reply! Currently, we aren't using the developer version of CEA. Would updating the folder /CityEnergyAnalyst/cea/ after the merging of #2571 would resolve the problem?

**Comment by daren-thomas** [comment]
@AlexJew, check out the [Release 2.30.0](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/tag/v2.30.0) - it includes the #2571 fixes. Does that solve your problem?

**Comment by AlexJew** [comment]
@daren-thomas it does! Thank you very much :)
