### ISSUE TITLE
Database Initializer "ghost" tool (also, inconsistent spelling e.g. "DataBase")

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2573]
I'm trying to open an older (v2.29) scenario with the v2.30 GUI and clicked on the Database editor. Exciting!

I find this page:

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/8d5b579b-3375-4398-ab73-f714103568f4)

COOL! So next I click on "Assign Database" and get sent to this screen:

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/67556f0f-82ea-4894-a408-9b596fc90682)

- Note the "default" caption - This should probably be the category of the tool. I was expecting it to be in the "Data Management" category but maybe the user isn't supposed to ever run this unless the databases aren't present / upgrading a repository? I don't know - maybe the description of the tool could explain more here.
- The label should be "Database", not "DataBase"
- The description should probably tell us more about what kind of initialization is being done and why
- how to start this tool? It doesn't show up in the tools menu. Maybe because it's in the "default" category? Nope. Just checked. It's because the interfaces are restricted: `interfaces: [cli, arcgis]`

**Comment by JIMENOFONSECA** [comment]
@daren-thomas good catch, maybe we can include it into "utilities", but not in datamanagement as this breaks the workflow and may create confusion. You got it right, the user is not supposed to access to it in the tools. It should be an initialization step everyone must go there at first.

**Comment by JIMENOFONSECA** [comment]
fixed in #2569
