### ISSUE TITLE
Rename columns for input databases that refer to another table

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2583]
`type_hs` could be renamed to `component_hs` to show that it refers to rows found in component

![image](https://user-images.githubusercontent.com/34395415/74925499-4493c900-540f-11ea-9b2e-ca180e7a3610.png)

**Comment by daren-thomas** [comment]
@reyery note that this will require writing a db migration as being developed in #2584 - I have come up with a simple system that can be used to provide automatic migrations in newer versions. I was wondering: What are your thoughts on running the migration script from the GUI?

**Comment by daren-thomas** [comment]
We won't fix this as the new standards / assemblies names make this a lot easier for the user to understand.
