### ISSUE TITLE
Changes to structure of database

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2585]
As discussed in the meeting, we could change the structure of some of the databases to make their uses more apparent.

- [x] rename `air-conditioning` to HVAC-components, `supply` to supply-assemblies, etc... in archetypes/construction database to show what databases they refer to

- [x] separate assemblies to different tables based on `system` column e.g. `HEATING`, `COOLING`

**Comment by daren-thomas** [comment]
@reyery is this done? I think it might be?

**Comment by reyery** [comment]
Yeah. Seems to be done. Will close this.
