### ISSUE TITLE
Function checking for DAYSIM binaries for radiation script does not pass binaries installed by DAYSIM installer

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2589]
Currently CEA is checking for a list of files to be present to ensure that the radiation script can run.

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/160cc8c1b2415e8784374fb98eeadc805273de16/cea/resources/radiation_daysim/radiation_main.py#L205-L215

However, it seems that it is only passing the directory of the DAYSIM binaries that we ship with the CEA installation and not the one installed using the original DAYSIM installer.

It is looking for 2 files `isotrop_sky` and `rayinit` that is not found in the `bin` folder but in the `lib` folder of the original DAYSIM directory.
```
c:\daysim\bin [('ds_illum', True), ('epw2wea', True), ('gen_dc', True), ('isotrop_sky', False), ('oconv', True), ('radfiles2daysim', True), ('rayinit', False), ('rtrace_dc', True)]
c:\daysim - copy\bin [('ds_illum', True), ('epw2wea', True), ('gen_dc', True), ('isotrop_sky', False), ('oconv', True), ('radfiles2daysim', True), ('rayinit', False), ('rtrace_dc', True)]
C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\resources\radiation_daysim [('ds_illum', False), ('epw2wea', False), ('gen_dc', False), ('isotrop_sky', False), ('oconv', False), ('radfiles2daysim', False), ('rayinit', False), ('rtrace_dc', False)]
c:\daysim\lib [('ds_illum', False), ('epw2wea', False), ('gen_dc', False), ('isotrop_sky', True), ('oconv', False), ('radfiles2daysim', False), ('rayinit', True), ('rtrace_dc', False)]
c:\users\admin\documents\cityenergyanalyst\dependencies\daysim [('ds_illum', True), ('epw2wea', True), ('gen_dc', True), ('isotrop_sky', True), ('oconv', True), ('radfiles2daysim', True), ('rayinit', True), ('rtrace_dc', True)]
```

We would need to investigate if `isotrop_sky` and `rayinit` are actually needed for our simulations.

**Comment by daren-thomas** [comment]
@reyery if I remember correctly,`isotrop_sky` and `rayinit` are data files and they _are_ required - I believe I just ran the radiation script on an empty folder and kept adding the missing files until it ran through.

I can take over this issue, I think it should be a quick one.
