### ISSUE TITLE
GUI Error :  Database Editor > ARCHETYPES > USE_TYPES --> Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2593]
**Describe the bug**
When wanting to access the **use types** via the GUI,  **Database Editor>ARCHETYPES>USE_TYPES**, there is an error that pops up.

```
TypeError: Cannot convert undefined or null to object

    in Wc
    in div
    in t
    in div
    in t
    in div
    in t
    in t
    in Yc
    in div
    in div
    in Bc
    in Fc
    in div
    in div
    in Unknown
    in b
    in t
    in t
    in main
    in x
    in o
    in section
    in t
    in o
    in section
    in t
    in o
    in el
    in t
    in t
    in t
    in n
    in o
    in p
    in g
    in b
```

**To Reproduce**
1. Open CEA Dashboard
2. Go to Database Editor > ARCHETYPES > USE_TYPES

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 1903

**Comment by JIMENOFONSECA** [comment]
Hi Alex, do you have version 2.30 or version 2.31 of CEA?

**Comment by reyery** [comment]
It could be that the GUI is trying to access a file that does not exist in `USE_TYPES` (e.g. a use-type `EXAMPLE` is found in **schedules** but not in **indoor comfort** or **internal loads**). 
There were quite a few changes in the structure of databases between versions 2.29.0 and 2.31.0 in an attempt to make it easier to understand and navigate through.

In any case, the GUI should show a more readable and actionable error message for the user. Will fix that soon.

**Comment by AlexJew** [comment]
Sorry for the slow response @JIMENOFONSECA ^^ I am currently using the 2.30 version.

**Comment by reyery** [comment]
@AlexJew could you try pressing `Ctrl+Shift+R` in **Database Editor** to force refresh. I think I found the bug that is causing **Database Editor** to find something that is not there.

**Comment by AlexJew** [comment]
Hi @reyery , sorry for not answering earlier. I am currently encountering some issues with Python, and I think I have messed up the environment variables :( CEA Dashboard doesn´t launch so I am trying to install the version 2.31 Once it is set up properly, I'll tell you about it !

**Comment by AlexJew** [comment]
Hi @reyery , my problem has disapperead with the 2.31 version. Thanks :) I'll close the issue then.
