### ISSUE TITLE
Reference cooling case is not updated

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2595]
Have we tested the SG case yet with the 2.31.0 databases? I'm getting the following error:

```
Workflow step: script=archetypes-mapper
Running archetypes_mapper with args {'input_databases': ['comfort', 'architecture', 'air-conditioning', 'internal-loads', 'supply', 'schedules'], 'buildings': [], 'scenario': 'C:\\Users\\darthoma\\Documents\\CityEnergyAnalyst\\projects\\reference-case-cooling\\baseline'}
City Energy Analyst version 2.31.0
Running `cea archetypes-mapper` with the following parameters:
- general:scenario = C:\Users\darthoma\Documents\CityEnergyAnalyst\projects\reference-case-cooling\baseline
  (default: {general:project}\{general:scenario-name})
- archetypes-mapper:input-databases = ['comfort', 'architecture', 'air-conditioning', 'internal-loads', 'supply', 'schedules']
  (default: ['comfort', 'architecture', 'air-conditioning', 'internal-loads', 'supply', 'schedules'])
- archetypes-mapper:buildings = []
  (default: [])

---------------------------
ERROR: Missing input files:
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>

    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 66, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\workflows\workflow.py", line 56, in main
    do_script_step(config, step)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\workflows\workflow.py", line 138, in do_script_step
    run(config, py_script, **py_parameters)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\workflows\workflow.py", line 29, in run
    f(config=config, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 28, in script_runner
    cea_script.print_missing_input_files(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\scripts.py", line 48, in print_missing_input_files
    if 'created_by' in schema_data[method_name]
KeyError: 'get_building_typology'
```

**Comment by daren-thomas** [comment]
(BTW: it works when running from the GUI - @reyery do you have an idea why?)

**Comment by JIMENOFONSECA** [comment]
yes, we noticed it. it was a hotfix into master https://github.com/architecture-building-systems/CityEnergyAnalyst/commit/ccc3157e7094dd686eb129a4e92a02cfe11fb344

is this still an issue?

**Comment by reyery** [comment]
I have a feeling that the input files in `reference-case-cooling` are not updated. And the other thing is that `get_building_typology` is not in **schemas.yml**. 
Also it could be working in the GUI because its running with another scenario with the right files? I'm not sure about that one.

**Comment by JIMENOFONSECA** [comment]
Right, I will actually erase reference cooling and reference WTP, they are just too outdated and nobody is following them.

Jimeno
On 24 Feb 2020, 10:49 AM +0800, Reynold Mok <notifications@github.com>, wrote:

I have a feeling that the input files in reference-case-cooling are not updated. And the other thing is that get_building_typology is not in schemas.yml.
Also it could be working in the GUI because its running with another scenario with the right files? I'm not sure about that one.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can we have maybe another cooling test case to run the workflows on instead?

**Comment by JIMENOFONSECA** [comment]
Maybe we can use the same case study to test both workflows?, or should we prepare new case studies, maybe even we use real data to make sure we are well close to reality?

Jimeno

________________________

Jimeno A. Fonseca
Dr. Sc. ETH Zurich

Senior Researcher
Singapore ETH-Centre (SEC)<https://sec.ethz.ch/>

Project Coordinator
Multi-Scale Energy Systems (MuSES)<https://fcl.ethz.ch/research/high-density-cities/multi-scale-energy-systems.html>

Product Owner & Developer
City Energy Analyst (CEA)<https://cityenergyanalyst.com/>

Principal Investigator
Cooling Singapore (CS1.5)<https://www.coolingsingapore.sg/>
Future Resilience Systems (FRS)<https://frs.ethz.ch/research/cyber-physical-systems/digital-twin-enabled-system-resilience.html>

On 24 Feb 2020, 4:43 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> can we have maybe another cooling test case to run the workflows on instead?

**Comment by daren-thomas** [comment]
I like the idea of having the reference cases be plausible.
