### ISSUE TITLE
GDAL and DAYSIM environment variables are not set for users running scripts from PyCharm

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2597]
Problem
-
Variables `GDAL_DATA`, `PROJ_LIB`, `RAYPATH` are not set when running scripts from PyCharm and this causes some unusual behavior such as in `radiation` script where it runs really fast

Solution
-
We could find a way to set these variables like how it done when running it from console. Or find some way to warn and teach users to include these variables in PyCharm using _configuration_, before running them.

**Comment by daren-thomas** [comment]
similar to checking for Daysim paths, we could also check for GDAL paths and add those to `os.environ` at the beginning of the script.

**Comment by daren-thomas** [comment]
@reyery is only the radiation script affected?
