### ISSUE TITLE
ERROR: data_initializer:

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2601]
Create new scenario
Generate new input files using tools
![1](https://user-images.githubusercontent.com/29708612/75161875-939e6e80-572d-11ea-8c02-e5008b311c57.jpg)
![2](https://user-images.githubusercontent.com/29708612/75161884-9731f580-572d-11ea-88a9-528c93e65279.jpg)
![3](https://user-images.githubusercontent.com/29708612/75161895-9a2ce600-572d-11ea-8b44-6307e01a504c.jpg)
ERROR: data_initializer:
Traceback (most recent call last):
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\api\project.py", line 122, in post cea.api.data_initializer(config, scenario=new_scenario_path, databases_path=payload['databases-path'])
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 52, in __call__    self._runner.__call__(*args, **kwargs)
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 26, in script_runner cea_script.print_script_configuration(config)
  File c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\scripts.py", line 31, in print_script_configuration print('City Energy Analyst version %s' % cea.__version__)
IOError: [Errno 22] Invalid argument

**Comment by daren-thomas** [comment]
@kerembeygo thank you for reporting this :) 

I'm un-assigning myself from this for now - assigning issues is traditionally done during our bi-weekly sprint meeting, or, in critical cases by @JIMENOFONSECA. That way, we can better prioritize our workload and also assign issues to the person most likely to be able to fix it in a timely manner.

**Comment by kerembeygo** [comment]
@daren-thomas I think bug report automatically assigned you. I didn't make any assignment to any person.

**Comment by daren-thomas** [comment]
@kerembeygo I'm very sorry. I wasn't aware of that functionality - it's something new we're trying out internally.

**Comment by JIMENOFONSECA** [comment]
@kerembeygo I am not able to reproduce. What version of CEA are you using? @reyery have you seen this problem? 

@kerembeygo what selection did you do to the data initializer?

**Comment by kerembeygo** [comment]
@JIMENOFONSECA CEA V2.31, I followed the steps above to create new scenario.

I can not open scenarios from previous projects.
![2](https://user-images.githubusercontent.com/29708612/75437583-7ce35c00-5967-11ea-9ce6-8543f61d5cf5.jpg)
![1](https://user-images.githubusercontent.com/29708612/75437594-8240a680-5967-11ea-98c6-dff7c857a29f.jpg)

Database editor 
![3](https://user-images.githubusercontent.com/29708612/75437642-a0a6a200-5967-11ea-9165-33975a45a31b.jpg)

Input editor
![4](https://user-images.githubusercontent.com/29708612/75437684-af8d5480-5967-11ea-95f7-0026bf60ecb5.jpg)

**Comment by kerembeygo** [comment]
I managed to open a previous scenario this time. 

Input file could not be found. You can create the file using archetypes-mapper tool.
![1](https://user-images.githubusercontent.com/29708612/75473334-0154cf80-59a6-11ea-9f50-01e4444425e7.jpg)

Archetypes Mapper
![2](https://user-images.githubusercontent.com/29708612/75473441-3a8d3f80-59a6-11ea-9635-8cf1c8b88122.jpg)

City Energy Analyst version 2.31.0
Running `cea archetypes-mapper` with the following parameters:
- general:scenario = C:\Users\KEREM\Documents\CEA Project\Fatih1\YavuzSelim1
  (default: {general:project}\{general:scenario-name})
- archetypes-mapper:input-databases = ['comfort', 'architecture', 'air-conditioning', 'internal-loads', 'supply', 'schedules']
  (default: ['comfort', 'architecture', 'air-conditioning', 'internal-loads', 'supply', 'schedules'])
- archetypes-mapper:buildings = []
  (default: [])
Traceback (most recent call last):
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 28, in script_runner
    cea_script.print_missing_input_files(config)
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\scripts.py", line 48, in print_missing_input_files
    if 'created_by' in schema_data[method_name]
KeyError: 'get_building_typology'


---------------------------
ERROR: Missing input files:

**Comment by JIMENOFONSECA** [comment]
@kerembeygo so we changed the inputs of CEA in version 2.30 see the warning message in the downloads link https://cityenergyanalyst.com/tryit

"...WARNING: After version 2.30 we do not have any backward compatibility. So your past case studies with CEA will not work. We are working in a transition script to help you migrate. In the mean time you can try the new version or to recreate your case study...."

btw, we just released 2.31.1. that version solves several bugs, if you would like to use it. Still you will not be able to work with past scenarios completely.

**Comment by kerembeygo** [comment]
@JIMENOFONSECA ok, I created a new scenario. Data management, demand forecasting, life cycle analysis, energy potentials tools ran. I'm trying network and optimization tools. I don't know what created the "ERROR: data_initializer" message in the first attempt.
