### ISSUE TITLE
Clean out the unused js + css stuff from the CEA source tree

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2615]
The CEA used to host it's own GUI (in cea/interfaces/dashboard...) including the site template etc. I believe we don't need this anymore as we have the CityEnergyAnalyst-GUI repository that should provide all the necessary libries.

Cleaning this out would reduce the size of the CEA repository and PyPI distributions.

**Comment by reyery** [comment]
I was thinking maybe we could also clear some of our stale branches

**Comment by daren-thomas** [comment]
@reyery has done this in another branch and it will be merged after testing then.
