### ISSUE TITLE
Excessive Installation time of CEA from Singapore --3hours

### ISSUE THREAD

**Issue by leafonseca** [architecture-building-systems/CityEnergyAnalyst#2617]
**Describe the bug**
The installation took too long. Approx. 30 minutes to download and approx. 3 hours to install.

**To Reproduce**
N.A. 

**Expected behaviour**
The tool download and installation should take 30 minutes (compared to other tools).

**Screenshots**
N.A.

**Desktop (please complete the following information):**
 - 2.31

**Comment by JIMENOFONSECA** [comment]
@daren-thomas mind checking the proxies we have for downloading the libraries. This seems to be a recurrent problem now in SG, not sure in CH

**Comment by daren-thomas** [comment]
@JIMENOFONSECA we don't actually download libraries anymore - we download the Dependencies.7z file from GitHub. It doesn't take 3 hours here - maybe check how long downloading that file in SG takes? Current location: https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v2.27.0/Dependencies.7z

It would help if you could monitor the "Details" during the installation to figure out what is taking a long time exactly.

**Comment by leafonseca** [comment]
Hi @daren-thomas, I am Lea, yes it is that file. What should I do?
![image](https://user-images.githubusercontent.com/61671530/75730489-07d9a300-5d28-11ea-886f-497369165ccf.png)

**Comment by daren-thomas** [comment]
Hi Lea, long time no see :) I hope all is well?

Wow. That's really slow. Is this at work? It takes about 30 seconds here. Have you tried talking to your IT? I don't think this is something I can fix from here as I can't really test it.

@JIMENOFONSECA have you tested this on multiple networks? (e.g. is the download speed faster on your home network?)

A possible solution would be to pay for a CDN (Content Delivery Network) - we'd need to test to make sure that we have funding for this and that it actually _is_ faster. It could be that a firewall is scanning the download for viruses and moving to a paid CDN would not solve this in that case.

**Comment by leafonseca** [comment]
Hi Daren,

Great to hear from you, even via CEA :) I will try to download it at home on my private computer and let you know.

Thanks and take care,
Lea

On 3 Mar 2020, at 4:16 PM, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Lea, long time no see :) I hope all is well?

Wow. That's really slow. Is this at work? It takes about 30 seconds here. Have you tried talking to your IT? I don't think this is something I can fix from here as I can't really test it.

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> have you tested this on multiple networks? (e.g. is the download speed faster on your home network?)

A possible solution would be to pay for a CDN (Content Delivery Network) - we'd need to test to make sure that we have funding for this and that it actually is faster. It could be that a firewall is scanning the download for viruses and moving to a paid CDN would not solve this in that case.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas assigning you, so we keep track of next steps. if you consider that we can take a 3rd party service to keep the downloader, please let us know the price, we can budget it.

**Comment by daren-thomas** [comment]
@leafonseca did you try downloading from your home wifi? did that work?

**Comment by daren-thomas** [comment]
it might have been an internet connection issue at the CREATE campus.
