### ISSUE TITLE
Import of CEA OSM should be restricted in terms to a maximum area. The user should receive a message about this restriction

### ISSUE THREAD

**Issue by leafonseca** [architecture-building-systems/CityEnergyAnalyst#2618]
**Describe the bug**
It was not possible to export the 3D buildings, streets, etc. of the entire island of Singapore. An error appeared.

**To Reproduce**
1. Go to 'input data'
2. Draw area
3. Click on 'create'

**Expected behaviour**
N.A.

**Screenshots**

![cea2](https://user-images.githubusercontent.com/61671530/75648473-250c6400-5c8b-11ea-9015-b3d83920984d.JPG)
![cea](https://user-images.githubusercontent.com/61671530/75648469-2342a080-5c8b-11ea-9c35-815833d72f8d.JPG)

**Hardware (please complete the following information):**
 - 2.31

**Comment by leafonseca** [comment]
Hi CEA Team! I did not manage to export the entire city of Singapore in one shot, but various districts. See imaged attached. Thanks.
![cea3](https://user-images.githubusercontent.com/61671530/75778189-515ed800-5d92-11ea-8947-876807b9eac1.JPG)

**Comment by daren-thomas** [comment]
@reyery thinks it might be some kind of rate limiting in the API.

Question: Is this still in scope of the CEA?

**Comment by JIMENOFONSECA** [comment]
Yes, @reyery @daren-thomas it is in scope to solve this issue. This is a basic feedback message needed. While we do not support great extensions of land. The user should not be allowed to do this, and instead receive a message explaining that we do not support it.

**Comment by daren-thomas** [comment]
This is fixed in the GUI. @daren-thomas will test this. and notify @leafonseca about the fix.
