### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'values

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2621]
**Describe the bug**
"AttributeError: 'numpy.ndarray' object has no attribute 'values'"
[Job Output for 3 optimization.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4281034/Job.Output.for.3.optimization.docx)

**To Reproduce**
1. Optimization
2. Supply System Part 2 (centralized)

**Expected behaviour**

**Screenshots**
![1](https://user-images.githubusercontent.com/29708612/75771863-d8dd2480-5d5b-11ea-89eb-3dbb79e60b09.jpg)

**Hardware (please complete the following information):**
 - OS and version: Windows 8.1
 - Version of CEA v. 2.31.1

**Comment by daren-thomas** [comment]
Daren thinks the expression `district_electricity_demands['E_hs_ww_req_disconnected_W'].values` is probably supposed to be a series and somehow got set to an `ndarray` - that's where I'd start to check (maybe a little-used code path set this and it only shows up in specific configurations).

@JIMENOFONSECA I'm assigning this to you for now - is that ok?
