### ISSUE TITLE
As a CEA user, I would like to quickly populate an empty site with a plausible design of street layout and building geometries. How to do that?

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CityEnergyAnalyst#2624]
To run simulations for green field projects, I would like to quickly generate a plausible design of street layout and building geometries for the empty site? How would we do it? The users who need this function can either be designers, engineers, or researchers.

I would like to introduce a new arm of CEA@Grasshopper, the Urban Block Generator. It is a grasshopper-based tool. It generates geometries of street centerlines and building volumes. They are based on a research on the 178 blocks of the six high-density areas of Singapore.
A pre-print version of the relevant research paper can be find here.
https://www.research-collection.ethz.ch/handle/20.500.11850/391820

Upon merging, I will write a blog about using this tool. Also, Urban Block Generator is be pure Grasshopper based and it will not be in conflict with the current development of the CEA interface.

**Comment by JIMENOFONSECA** [comment]
@shizhongming great that you are coming up with this feature. 

It would be great if you are interested in taking the CEA@grasshopper as your own development. Perhaps even creating a repository that does this and attracts users and developers on their own. For the future of CEA, we will not be maintaining CEA interface for Grasshopper (the already outdated one we had). So then it makes sense to create your own repository for this anywise.

The reasons to not maintain Interfaces such as ArcGIS or Grasshopper anymore is that we would  like to focus on the CEA Dashboard main interface for the time to come. This should help us to focus efforts on better user experience in CEA while allowing other users to connect through IMPORTING files in CEA in the near future.

@daren-thomas @shanshanhsieh @reyery we proceed to end support from CEA main repository on Grasshopper (for the reasons above stated). We will let other users such as @shizhongming to come up with their own repository and implementations for external tools such as CEA@grasshopper. I will open an issue for that.

I close this issue for now. Feel free to reopen should there be any doubts.
