### ISSUE TITLE
Select a few buildings from an existing data set

### ISSUE THREAD

**Issue by matthiassulzer** [architecture-building-systems/CityEnergyAnalyst#2625]
**Describe the bug**
I try to select some buildings out of the HQ data set, see https://idethz-my.sharepoint.com/:f:/g/personal/jinxdy7vdt_ethz_ch/Eiq_-l30ZVJEiFuqKVS1eG0B4YkhrfudrccSX32o6J2mBQ?e=w8uzW0

**To Reproduce**
1. Open existing project (Hochschulquartier)
2. Select all buildings
3. Deselect the buildings, which I will analyse (ctrl+clicks on the buildings)
4. Deleted selected buildings

**Expected behaviour**
Expected that the data set will be reduced to the desired buildings. This also took place in the section zone, indoor comfort, surroundings and schedules. However, the data set was not adjusted for typology, architecture, internal-loads, AC and supply systems.

**Screenshots**
![image](https://user-images.githubusercontent.com/54287523/76061919-dc9fbf80-5f84-11ea-8194-6fac2704d6f9.png)
![image](https://user-images.githubusercontent.com/54287523/76061955-f6410700-5f84-11ea-8883-e4bf68362c00.png)

**Hardware (please complete the following information):**
 - Windows
 - Version of CEA you are using 2.31.1

**Comment by reyery** [comment]
@matthiassulzer I see that the input files from the scenario are still using the structure for versions <= `2.29.0`. There was a major change in the input files needed for CEA in version `2.31.0`, (i.e. `age` and `occupancy` files were merged to become `typology`, structure of input databases were simplified and separated into categories to make it easier to understand how they are related to each other, etc)

We are currently working on a migration script (https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2584) to allow users to use their older scenarios with the new version, which would help with this issue.

**Comment by JIMENOFONSECA** [comment]
@reyery update? is the tool included in the new release?

**Comment by reyery** [comment]
Yes, the migration script is now included in version `2.32.0`. You could follow the steps:


>     1. run data-initialiser or choose "Assign Database" in the Database Editor
>     2. run database-migrator in utilities
>     3. edit your typography input table
>     4. run archetypes-mapper tool

This would generate all the missing files that are required.

**Comment by matthiassulzer** [comment]
Dear all

Many thanks for the new release. There are still some errors:
Defining a new scenario, an error of not finding the weather file of Zurich:
[cid:image001.png@01D5F91B.C1719FA0]



Best,

Matthias

Von: Jimeno Fonseca <notifications@github.com>
Gesendet: Freitag, 13. März 2020 03:45
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Select a few buildings from an existing data set (#2625)


@reyery<https://github.com/reyery> update? is the tool included in the new release?

**Comment by matthiassulzer** [comment]
Dear all
To translate the existing HQ file into the new structure failed:
![image](https://user-images.githubusercontent.com/54287523/76608809-93b4b180-6516-11ea-90d3-7d5f9bb3a2d3.png)
![image](https://user-images.githubusercontent.com/54287523/76608830-a3cc9100-6516-11ea-837b-65c45e781dc7.png)
Thanks for an advice. Or could you translate the old version input file of the HQ into the new structure: 
[Hochshulquartier_status_quo.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4328803/Hochshulquartier_status_quo.zip)

Best,
Matthias

**Comment by reyery** [comment]
@matthiassulzer it seems that you would need to run the `data-initializer` tool first (to initialize the new input databases) before running `database-migrator`. 

Nevertheless, I have tried the scenario you provided and converted it to the new structure.
[Hochshulquartier_status_quo.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4336330/Hochshulquartier_status_quo.zip)

_Do note_ you would still have to  run the `archetypes-mapper` tool to generate the other input files (e.g. `internal-loads`) after editing the the information found in the `typography` input table if you want to.

**Comment by matthiassulzer** [comment]
Hi Rey

Many thanks. It works! However, there is still one schedule missing: Electrical mobility.
[cid:image001.png@01D5FB80.D2D7EE90]
Could you please advice, what I have to do. Thanks.

Best,

Matthias

Von: Reynold Mok <notifications@github.com>
Gesendet: Montag, 16. März 2020 07:28
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Select a few buildings from an existing data set (#2625)


@matthiassulzer<https://github.com/matthiassulzer> it seems that you would need to run the data-initializer tool first (to initialize the new input databases) before running database-migrator.

Nevertheless, I have tried the scenario you provided and converted it to the new structure.
Hochshulquartier_status_quo.zip<https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4336330/Hochshulquartier_status_quo.zip>

Do note you would still have to run the archetypes-mapper tool to generate the other input files (e.g. internal-loads) after editing the the information found in the typography input table if you want to.

**Comment by matthiassulzer** [comment]
Hi Rey

I also tried to run architypyes-mapper: schedules. But there is also an error:
[cid:image002.png@01D5FBA3.3E3269F0]

Thanks for your help. Best,

Matthias

Von: Sulzer, Matthias
Gesendet: Montag, 16. März 2020 10:51
An: 'architecture-building-systems/CityEnergyAnalyst' <reply@reply.github.com>; architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Betreff: AW: [architecture-building-systems/CityEnergyAnalyst] Select a few buildings from an existing data set (#2625)

Hi Rey

Many thanks. It works! However, there is still one schedule missing: Electrical mobility.
[cid:image003.png@01D5FBA3.3E3269F0]
Could you please advice, what I have to do. Thanks.

Best,

Matthias

Von: Reynold Mok <notifications@github.com<mailto:notifications@github.com>>
Gesendet: Montag, 16. März 2020 07:28
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com<mailto:CityEnergyAnalyst@noreply.github.com>>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch<mailto:Matthias.Sulzer@empa.ch>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Select a few buildings from an existing data set (#2625)


@matthiassulzer<https://github.com/matthiassulzer> it seems that you would need to run the data-initializer tool first (to initialize the new input databases) before running database-migrator.

Nevertheless, I have tried the scenario you provided and converted it to the new structure.
Hochshulquartier_status_quo.zip<https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4336330/Hochshulquartier_status_quo.zip>

Do note you would still have to run the archetypes-mapper tool to generate the other input files (e.g. internal-loads) after editing the the information found in the typography input table if you want to.

**Comment by reyery** [comment]
There seems to be a bug when trying to calculate schedules. I have fixed the code and you can try pulling it from master if you are on the dev version and run `archetypes-mapper` again.

**Comment by matthiassulzer** [comment]
Hi Rey

Could we have a short phone call. I need some support to link github und CEA.

Many thanks for calling me on +41786259979

Best,

Matthias

Von: Reynold Mok <notifications@github.com>
Gesendet: Dienstag, 17. März 2020 04:13
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Select a few buildings from an existing data set (#2625)


There seems to be a bug when trying to calculate schedules. I have fixed the code and you can try pulling it from master if you are on the dev version and run archetypes-mapper again.

**Comment by reyery** [comment]
Fixed in v2.32.0 and 763771e
