### ISSUE TITLE
As a User, I would like to know what are all the variables in the demand/<building_id>.csv and demand/Total_demand.csv files

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2626]
**Describe the feature you would like to have**
I would like to know what do the columns' names represent and what are their interaction between each other (ex: Eal is the sum of Ea and El). I would like to have this info for the *<building_id>.csv* and *Total_demand.csv* files.

**Describe the end purpose of this feature**
This will enable me to use the data directly from these csv files and process it the way I want to for further visualisation (ex: make it interact with GIS visualisation app via pandas and geopandas). 

**Describe the end-user of this feature**
Anyone (in my case a student, but surely it represents also valuable information for reseachers and practitioners)

**Provide Aditional information if possible**
The data in https://docs.google.com/presentation/d/1o-xfDRPpt7zY2rxcsbTjmVwGqbWXSi_IrxKSaer59-M/edit isn´t up-to-date. The variable names have changed. Also, I do not understand all the differences between the electricity uses (ex: I do not have a clear idea of what *auxiliary electricty use* refers to).

**Comment by JIMENOFONSECA** [comment]
@daren-thomas @shanshanhsieh @reyery i wonder if our glossary is not very effective anymore. Lot’s of todo’s. For quite important information. There is also repetition. Could we mobilize the team to engage on this for one afternoon, perhaps all before we release v3.0? I guess that will do and help tons of stranded users. I met other users in SG this week facing the same problem.

**Comment by daren-thomas** [comment]
This is basically done. Anything still missing should be it's own issue. Thank you all for helping with the glossary definitions!
