### ISSUE TITLE
As a User, I would like to be able to download data from my plots on CEA as a .csv file

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2628]
**Describe the feature you would like to have**
When creating a plot on CEA, I would like to be able to download the data from the plot..

**Describe the end purpose of this feature**
- Produce my own graph 
- Process the data to show relevant tendencies or important hidden correlations

**Describe the end-user of this feature**
- Better communication of the results
- Greater flexibility on the visualisation of results

**Provide Aditional information if possible**
No aditional information

**Comment by JIMENOFONSECA** [comment]
@AlexJew the button on the top right of a plot (right besides the legned toggle) gives you access to the data in CSV. Does this provide the functionality you mentioned?

**Comment by AlexJew** [comment]
@JIMENOFONSECA The button shows which are the files from which the data is extracted, however it may show a list of files and doesn't mention where is the data within this files. Moreover, this data is contained within columns with obscure names (compared to them, the legend's names are much clearer). Rather what I was suggesting, was a feature to export only the data of the plot in a csv file. For example, the structure could be : x axis as rows and y axis as columns. This would create a table with all the info from the plot for the user to plot it as he wants using another tool, ex: matplotlib.
