### ISSUE TITLE
Optimization plots `generation` parameter

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2647]
**Describe the bug**
The  **optimization** plots have a `generation` parameter which does not seem to do anything. Plots for generation 1 and generation 2 are the same as both shows data from multiple generations

**To Reproduce**
1. Create a plot in the **optimization** category e.g. Pareto Curve
2. Change the `generation` plot parameter

**Expected behaviour**
Changing `generation` plot parameter should change the plot

**Screenshots**

![image](https://user-images.githubusercontent.com/34395415/76922487-c9d5a500-690b-11ea-97ae-32990387a1fe.png)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA this might be left over from the changes to how the optimization works?

**Comment by daren-thomas** [comment]
This should be checked by comparing generation 1 to generation 50.

**Comment by reyery** [comment]
Just checked and plots for generation 1 and generation 50 are indeed different so there is nothing wrong with the plots. I suppose then the main issue is that the title of the plots could be misleading. At first I thought that plots show emissions/cost for systems in generation X. But in reality it is the ("top performing"?) systems after X generations.

![image](https://user-images.githubusercontent.com/34395415/77133386-e1449780-6a9d-11ea-81e0-911978466f21.png)

**Comment by reyery** [comment]
@JIMENOFONSECA I believe we can just rename the plots to solve this issue. Maybe something like **Annual Emissions for best individuals after X generations**. What do you think

**Comment by JIMENOFONSECA** [comment]
Excelent name! Go for it
On 23 Mar 2020, 17:30 +0800, Reynold Mok <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> I believe we can just rename the plots to solve this issue. Maybe something like Annual Emissions for best individuals after X generations. What do you think
