### ISSUE TITLE
CEA Dashboard > Data Editor - Cutting the right border of data tables

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2656]
**Describe the bug**
The GUI cuts the right border of data tables in **Data Editor** when they almost fit in the entire screen.

**To Reproduce**
1. Go to **Data Editor**
2. Open a data table (ex: CONSTRUCTION-STANDARDS > STANDARDS_DEFINITION in my case)

**Expected behaviour**
A lower scrolling bar for all databases too wide to fit in the screen.

**Screenshots**

The databases that "almost fit" are cut
![image](https://user-images.githubusercontent.com/32110882/77247340-72e40e80-6c30-11ea-9f99-4afac7ce3619.png)

The databases that are "way too large" get a scrolling bar
![image](https://user-images.githubusercontent.com/32110882/77247423-74fa9d00-6c31-11ea-9b14-ff9e9ae68850.png)

The databases that are "small enough" don't get cut
![image](https://user-images.githubusercontent.com/32110882/77247366-bfc7e500-6c30-11ea-9f4c-c8df93e2099d.png)

**Hardware (please complete the following information):**
 - OS and version: Windows 10 Education, 1909
 - Version of CEA : 2.32

**Comment by reyery** [comment]
@AlexJew can I check if manually resizing the window resizes the table also?

**Comment by AlexJew** [comment]
Hi @reyery , what do you mean by manually resizing the window? When passing my mouse over it, I do not see any resizing symbol. I haven't updated my CEA version yet

**Comment by reyery** [comment]
Try making the application window bigger/smaller by dragging from the corners of the application window. I have a feeling the table only re-renders when the application window resizes.

**Comment by AlexJew** [comment]
As you say, the table resizes properly once I leave the full screen mode. But, if I decide to go back to full screen, the problem comes back.
![image](https://user-images.githubusercontent.com/32110882/78368043-ec79e600-75ba-11ea-9cee-77b083f7ffcd.png)

**Comment by daren-thomas** [comment]
Update: @reyery is close to finding a solution.

**Comment by reyery** [comment]
@AlexJew could you help me test [this](https://polybox.ethz.ch/index.php/s/f0r3lruB9PQVyNa) build of the GUI to see if it still happens on your end?

**Comment by AlexJew** [comment]
Hi @reyery , I will do so tomorrow. Thanks ! :)

**Comment by AlexJew** [comment]
@reyery  the build works! For comparison sake : 
- Testing with original CEA 3.1
![Screen Shot 2020-04-25 at 14 49 35 (2)](https://user-images.githubusercontent.com/32110882/80281659-9f45eb80-8704-11ea-9c2f-7f2e00d474fb.png)

- Testing with your build 
![Screen Shot 2020-04-25 at 14 52 06 (2)](https://user-images.githubusercontent.com/32110882/80281664-ab31ad80-8704-11ea-8006-ae1c19967d68.png)

We clearly see that the borders aren't cut anymore. Thanks for the work :)

**Comment by reyery** [comment]
Thanks for testing it! Will merge this fix into the coming release.
