### ISSUE TITLE
Data Initializator - Unable to found "archetypes" database in SG default database or 

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2657]
**Describe the bug**
When creating a new scenario and choosing a database path, the following error appears.

```
ERROR: data_initializer: we might not have found the 'archetypes' database in the path you indicated, please check the spelling
```

This happens with:
- the SG default database
- a personal database

Strangely, it doesn't happen with the CH default database. 

Here's the full error : 

```
Traceback (most recent call last):
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\api\project.py", line 122, in post
    cea.api.data_initializer(config, scenario=new_scenario_path, databases_path=payload['databases-path'])
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\datamanagement\data_initializer.py", line 82, in main
    initialize_assemblies_database=initialize_assemblies_database
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\datamanagement\data_initializer.py", line 44, in data_initializer
    raise Exception("we might not have found the 'archetypes' database in the path you indicated, please check the spelling")
Exception: we might not have found the 'archetypes' database in the path you indicated, please check the spelling
```

**To Reproduce**
1. Create new scenario in CEA
2. Select either the SG database or a custom database

**Expected behaviour**
The proper import of the selected database.

**Screenshots**
Actually, it might also be related to the fact the **Data Initializor** doesn't enable the selection of all the databases. See the following picture, where we can only select _archetypes_, _assemblies_ and _components_ :

![image](https://user-images.githubusercontent.com/32110882/77526285-3f98be00-6e82-11ea-87f7-fd837a036dce.png)

**Hardware (please complete the following information):**
 - OS and version: Windows 10, 1909
 - Version of CEA: 2.32

**Comment by shanshanhsieh** [comment]
the connection between the databases-path and the script is not stable.
we should first look into how the config file is handling this parameter.

**Comment by reyery** [comment]
@AlexJew are you still getting this error? I have tried multiple ways but was still unable to recreate this bug on my end. However, I do think that this error might not be because CEA was unable to find the path to the databases (the error message was raised by us and not might not accurately represent the actual error), CEA tries to verify the path of the database before running the script.

What I am thinking now is that it might be caused when trying to copy the files, so I have removed our own exception in the code, hopefully that when it when happens, the actual error message with the stack trace would be shown.

**Comment by AlexJew** [comment]
Hi @reyery, tbh I haven't downloaded the latest version yet, so I don't really know if the bug has been corrected since then. Once I've downloaded it and tried creating a new scenario, I'll get back to you, but for the meantime it might be better to close the issue?

**Comment by reyery** [comment]
Alright, no worries. I will just close this issue for now and you could reopen/create a new issue if you encounter this again. Thanks!
