### ISSUE TITLE
As a User, I would like to be able to delete created Use-Types

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2658]
**Describe the feature you would like to have**
I would like to be able to delete Use-Types from the database I am using.

**Describe the end purpose of this feature**
This applies particularly to use-types created by the user. It may happen that after creating a use-type, we realise that we badly initialised it (ex: wrong share of two different use-types) or that we made a typing mistake in the name. For the latter, it can be frustrating, but we can recreate the use-type with the proper name. However, for the former, we have no means available to correct this error and the buildings whose **USE-TYPE** in _typology.dbf_ is of this type are now mapped to a badly defined use-type.

**Describe the end-user of this feature**
Any user of CEA who wants to define a custom use-type.

**Provide Aditional information if possible**
EX. Screenshots, Links, Methods

**Comment by JIMENOFONSECA** [comment]
Hi @AlexJew I wonder if you could 
1. create the new usetype (the right one)
2. go to typologies and select for one or more buildings this new right use_type.
3. Run archetypes mapper to map the archetypes data related to these use types again.

**Comment by AlexJew** [comment]
I am working on it. I'll come back to you as soon as I've done it!

**Comment by AlexJew** [comment]
@JIMENOFONSECA the problem is that once you have created a usetype, you can not overwrite it by creating a new usetype with the same name. Here is the error you get :

```
City Energy Analyst version 2.32.0
Running `cea create-mixed-use-type` with the following parameters:
- general:scenario = C:\Users\jewell\Desktop\CEA\VSA\Typologies_Uses
  (default: {general:project}\{general:scenario-name})
- create-mixed-use-type:use-type = MULTI_RES_OLD
  (default: mixed_use)
- create-mixed-use-type:metadata = mixed-use
  (default: mixed-use)
- create-mixed-use-type:ratios = ['MULTI_RES|1.0']
  (default: ['MULTI_RES|1.0'])
Traceback (most recent call last):
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\utilities\create_mixed_use_type.py", line 125, in main
    'Use-type name {} already exists'.format(use_type_name)
AssertionError: Use-type name MULTI_RES_OLD already exists
```

**Comment by JIMENOFONSECA** [comment]
@AlexJew so I guess we will have to do a workaround.
1. create a new name.
2. edit the multi_res_old and save changes
