### ISSUE TITLE
Raw data explanation

### ISSUE THREAD

**Issue by oskarinis** [architecture-building-systems/CityEnergyAnalyst#2660]
As a Practitioner I would like to have a raw data explanation access. For example, what is the meaning of "o mww_zone_kWperC" in Sewage heat potential raw data? Or "DH_ww_tonCO2" in Emissions raw data? Could you please let me know what exactly do they mean?

Any raw data file contains plenty of shortcut names for some specific parmeter and some of them are really hard to figure out. Then the raw data looses it purpose.

**Comment by JIMENOFONSECA** [comment]
@oskarinis great point, we are addressing this right now in #2626 #2637 Next week is our deadline to release a new version with this fixed. @daren-thomas I add you here so we make sure we cover this in those issues

**Comment by daren-thomas** [comment]
This is merged in master. You can use the GUI to check for explainations - there is a search bar at the top right (Glossary Search). This works for all the input and output files of the CEA. We're still working on the plot output files. Try searching for `DH_ww_` instead:

![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/4f29891e-cc19-4696-ac69-ab8f8a81d94e)
