### ISSUE TITLE
As a developer I would like to know the status of thermal-network-optimization so I can update the corresponding locator methods

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2662]
Some locator methods (e.g. get_optimization_network_all_individuals_results_file, get_optimization_network_generation_individuals_results_file) are only used in the `thermal-network-optimization` script. I'm not sure this script really works anymore.

@JIMENOFONSECA @shanshanhsieh do you know more about this?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh I wonder if this tool should be moved to legacy, unless it is going to be used and documented. perhaps there is a tool in the making>
