### ISSUE TITLE
Status of jobs remain as Pending

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2664]
**Describe the bug**
After latest merge (as of 24/03), I am not being able to send any jobs. Status remain as Pending, without any return

**To Reproduce**
1. I opened different CEA cases (already existent) and try to run several different tasks (from database and demand forecasting) and they were all unsuccessful 

**Expected behaviour**
Complete jobs sent 

**Screenshots**
![image](https://user-images.githubusercontent.com/50981039/77398113-d8c3c800-6de1-11ea-884b-a77f2504d73b.png)

**Hardware (please complete the following information):**
 - Windows 10
 - Version of CEA you are using v. 2.32.0

**Comment by reyery** [comment]
Are you on the developer version? If so, I believe you would need to overwrite the GUI you have to the newest [GUI](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.0.1/win-unpacked.7z), since there where some changes as to how jobs are started.

**Comment by lguilhermers** [comment]
Hi rey, I had overwriten the GUI and did again, but the issues remains... This same version was working before I updated from the master branch just now.

**Comment by reyery** [comment]
I tried it on my end and I get the same issue. It seems that the one that was uploaded is not the latest GUI. I have re-uploaded it, could you try downloading it again [here](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.0.1/win-unpacked.7z).

**Comment by daren-thomas** [comment]
@reyery that might break the release 3.0.1 which doesn't include the pr that introduced this - maybe we should do a release 3.0.2 instead?

**Comment by reyery** [comment]
@daren-thomas oh crap I just realised that PR #2652 was not included in the release. yeah we could, since it would affect developers that are on master without the new GUI.

**Comment by reyery** [comment]
Alright I have reuploaded and reverted the link to the previous build that was uploaded (the one without the endpoint change).

**Comment by lguilhermers** [comment]
It is working again. Thanks!

**Comment by reyery** [comment]
Fixed in [v3.0.2 ](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.0.2/Setup_CityEnergyAnalyst_3.0.2.exe)
