### ISSUE TITLE
As a User I would like "Unnamed: 0" columns to be renamed to better understand their meaning

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2667]
There are 17 instances of columns named "Unnamed:0" (including one "Unnamed:0.1" in the `schemas.yml` file. This is what those columns are called in the corresponding csv files. I believe this is an artefact of how they are created (`df.to_csv`) and it could probably be easily fixed.

Often, a more meaningful name could be "hour" or "hour-of-year".

**Comment by shanshanhsieh** [comment]
we should change those instances to `index=False`

**Comment by daren-thomas** [comment]
@shanshanhsieh I believe most of these are handled in #2637 - we will do a check (grep `schemals.yml`) after merging.

**Comment by daren-thomas** [comment]
I noticed some discrepancies with the `thermal-network` script outputs, depending on if "simplified" or "detailed" model is used:

- `get_thermal_network_node_types_csv_file`:
  - detailed columns: `[,Name,Type,Building,coordinates,Q_hex_h_ahu,Q_hex_h_aru,Q_hex_h_shu,Q_hex_h_ww,Q_hex_plant_kW]`
  - simplified columns: `[Building,Type]`
  - NOTE: I think this is connected with issue #2700
- `get_thermal_network_edge_list_file`: detailed version includes `Name` column
- `get_thermal_network_plant_heat_requirement_file`: the only column in this file has the header `NONE`. That's hardly better than "Unnamed: 0" and should probably be renamed to... idk... `plant_thermal_load_kW` or something?
- `get_thermal_demand_csv_file`: detailed version has extra (unnamed) column for the hours

There is a separate issue for this: #2710

NOTE: This also means we'll need to update the `schemas.yml` descriptions for the columns currently missing...

**Comment by daren-thomas** [comment]
The multi-criteria-analysis script also needs updating: #2711

**Comment by daren-thomas** [comment]
The decentralized script also needs updating: #2712

**Comment by shanshanhsieh** [comment]
@daren-thomas please quickly run through the workflow and check what is remaining.

**Comment by reyery** [comment]
Solved in #2748
