### ISSUE TITLE
Building Solar doesn't work with underground parkings 

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2670]
**Describe the bug**
I have underground parkings that I have defined with _height_ag = floors_ag = 0_ . Even though they won't represent any heat/cooling consumption, they represent an electricity consumption (electric car chargers will be installed) and therefore I need to keep them. 

However, when trying to run **Building Solar Radiation** tool, the program crashes :

1. I run the tool without including them in the list of buildings, and I get the following error : 
```
    floor_to_floor_height = height / nfloors
ZeroDivisionError: float division by zero
```

2. I set _floors_ag = 1_ and _height_ag = 0_, and run the tool without including them in the list of buildings, I get the following error :
```
RuntimeError: Standard_ConstructionError
```

My underground parking geometries overlap with buildings. What could be the solution? **Building Solar Radiation** run completely when excluding the parkings.

**To Reproduce**
1. Download the input and database files from : https://www.dropbox.com/transfer/AAAAAKdzY9szzW_T5157yRChF5m8zOSiR7P0tIGY_OiU5yXtq-Iba_E
2. Create new scenario, import these files as input
3. After running **Archetypes Mapper** and **Weather Helper**, run **Demand Forecasting > Building Solar Radiation**

**Expected behaviour**
Successful running with **Building Solar Radiation** taking into account only the selected buildings and the surroundings

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: Windows 10, 1909
 - Version of CEA: 2.32

**Comment by shanshanhsieh** [comment]
the radiation toold should skip those buildings have height_ag = floors_ag = 0
but a dummy radiation file should be created to pass on to the demand calculation

**Comment by AlexJew** [comment]
Hi, I don't know if that is of any help, but my terrain isn't flat, so I guess that, even if the parkings are considered as underground, they may clash with lower standing building (terrain-wise) that are purely overground.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA do you have an update on this issue?

**Comment by JIMENOFONSECA** [comment]
No, i am not sure if another developer can help. i am swamp these months with other tasks.
On 30 Apr 2020, 15:33 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> do you have an update on this issue?

**Comment by JIMENOFONSECA** [comment]
solved in #2729. We just changed the schema so @AlexJew CEA will throw a proper exception. So you can not run CEA unless al buildings have at least one floor. Unfortunately, the opposite functionality you require was not intended from the beginning. 

If you still require it, we will appreciate a PR with the code modifications. unless @daren-thomas or @shanshanhsieh know about a quick way to add this functionality. Be aware that this affects the full stack of solar, demand, PV technologies etc..

**Comment by AlexJew** [comment]
Ok, thanks for the attempt :/ @JIMENOFONSECA is there any documentation explaining how to use the ELECTROMOBILITY sheet for the Database? I am still quite confused about the units.

**Comment by JIMENOFONSECA** [comment]
No problem.

No, no documentation, but the units and glossary should pretty much tell. You will need to add the electric vehicles as a load per vehicle in internal-loads and then put in the schedule the number of vehicles in every hour of the day.

I hope this helps.
On 13 May 2020, 18:28 +0800, AlexJew <notifications@github.com>, wrote:

Ok, thanks for the attempt :/ @JIMENOFONSECA<https://github.com/JIMENOFONSECA> is there any documentation explaining how to use the ELECTROMOBILITY sheet for the Database? I am still quite confused about the units.
