### ISSUE TITLE
some variables from architecture don't get balanced while running archetypes helper

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2671]
**Describe the bug**
A case with multiple occupancy is not merging some properties according to its weighted average.

**To Reproduce**
1. Go to a new case on v2.32
2. Create multiple typologies (for my case I has 0.6 office, 0.2 retail and 0.2 mixed use, created from half residential and half hotel)
3. Run archetypes mappes
4. See architecture tab (for me it shows Hs_ag = 0.25 and wwr = 0.29, while the mixed values expected would be something around Hs=0.79 and wwr = 0.59, according to v 2.32)

**Expected behaviour**
Mixed values expected would be something around Hs=0.79 and wwr = 0.59, according to v 2.29

**Screenshots**
![image](https://user-images.githubusercontent.com/50981039/77726675-6f3af800-7033-11ea-86db-e5ef00464079.png)

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - Version of CEA you are using  v. 2.32

**Comment by shanshanhsieh** [comment]
@lguilhermers this behavior is expected.
Only internal loads, comfort, and schedules will change with different use types.
The values Hs, wwr is decoupled from the use type, it is determined by the *STANDARD* chosen.

**Comment by lguilhermers** [comment]
Ah, I see. Was not aware of this change, as (I think) before those parameters were also weighted. Thanks for clarifying :)
