### ISSUE TITLE
Start CEA

### ISSUE THREAD

**Issue by S-Haddad-S** [architecture-building-systems/CityEnergyAnalyst#2676]
**Describe the feature you would like to have**
We need to run an energy simulation for an urban area 2km*2km; I would like to see whether we can use your tool for predicting energy demand of this district. We need to use our own weather file and consider future development of the urban area; buildings which are not in the open database. We can create a shape file, Autocad, etc to represent the future scenario considering new constructions in the district if that can be used as an input in your platform. 

I would be grateful to know if your online platform allows us to use our weather file and GIS/shape file for future scenario. Please advise the input we need and the output from the platform. 

•	Is it possible to upload user defined epw – climate data? 
•	Can I get Energy demand/ cooling load for the precinct? 
•	What are the input/output data for the study explained above? 

Many thanks

**Describe the end purpose of this feature**
I could visualize/understand/ energy demand of a distric

**Describe the end-user of this feature**
A Researcher

**Comment by shanshanhsieh** [comment]
Hi @S-Haddad-S , thank you for your interest!
The CEA tool is a stand-alone software and fully open-access, you can download it from here: https://cityenergyanalyst.com/try-cea
The installation is automated for windows OS.

To your questions:
Q1: Is it possible to upload user defined epw – climate data? 
A1: Yes, there is a weather helper tool that assist you to connect your own epw files.
Q2: Can I get Energy demand/ cooling load for the precinct?
A2: Yes, these are the standard outputs of our demand calculation tool.
Q3: What are the input/output data for the study explained above?
A3: The minimum inputs are the geometry (.shp). Once you downloaded the tool, you can follow the step to "Create new scenarios."

Base on your questions, i think CEA is a suitable tool for your project. 
We would highly encourage you to download the tool and try it out!
Please let us know if you encounter any problem.
Wish you all the best for your project : )
