### ISSUE TITLE
Current investment cost database of technologies

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#268]
Build a database of fix cost constants used in conversion technology pricing equations (including specific year and currency) in CEA. This database can then be used as a start to continue with the VEOLIA employee or a master student.
Master thesis topic could be something relating to technology economic data collection in Singapore and optimization of system configurations with different prices and price evolution. 
Possible starting date: Jan 2016

**Comment by JIMENOFONSECA** [comment]
This work has been already done, but need to be integrated to the tool.
check:
https://hues.empa.ch/index.php/Special:RunQuery/Technology_query

it has lots of economic data about technologies. You might want to start there...

**Comment by shanshanhsieh** [comment]
Sure, I will start with combining the information from HUES and the data used in CEA, and then prepare the data base for Singapore.

**Comment by JIMENOFONSECA** [comment]
you might also want to get a way to extract the economic data now intrinsically inside the tool to an excel file. (more easily editable). let's make a detailed plan before implementing.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh @BhargavaKrishnaSreepathi what is the status of this. is it being implemented or is it still necessary? consider the issue is 8 months old an if it is important we need to put it into the development pipeline

**Comment by BhargavaKrishnaSreepathi** [comment]
@shanshanhsieh : On top of adding the cost terms to the database, I will be even changing the investment cost calculation also, i.e. standardize the cost calculations based on the equation we discussed.

**Comment by BhargavaKrishnaSreepathi** [comment]
Make the changes in 'i268-Technology-cost-database' branch

**Comment by shanshanhsieh** [comment]
this issue is related to #478, and will be resolved together in branch `i268`

**Comment by shanshanhsieh** [comment]
The files to be worked upon are: `cea/optimization/master/Cost_model.py` and `least_cost_main.py`

**Comment by shanshanhsieh** [comment]
@BhargavaKrishnaSreepathi The `supply_system.xls` is updated with costs, the references are documented in `system_references.rst`. After checking and writing new functions for cost calculation, the cost-related constants in `globalvar.py` can be safely removed.

**Comment by BhargavaKrishnaSreepathi** [comment]
@shanshanhsieh: we need to have a default parameters for capacities which are not present in the capacity range specified. For example, in boilers, the minimum capacity is 28000, what happens when the capacity thrown by optimizer is less than this?
