### ISSUE TITLE
As a Developer I would like to remove naming.csv file to have a single point of reference for glossary information

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2680]
The way the `naming.csv` file is set up, we'll need to change the plots a bit to be able to move these variables to `schemas.yml`.

It will require that the output variables in the plots is actually an output column in one of our output fields. If that assumption does not hold, we'll need to come up with another plan.

**Comment by shanshanhsieh** [comment]
before plotting, there should be a .csv output of all the data used.
that would require seperated "mini scripts" to replace the "pre-processing" step.

**Comment by daren-thomas** [comment]
we can't get rid of `naming.csv` quite yet as it does not do the same thing as `schemas.yml` and therefore can't be merged quite yet.

- `schemas.yml` describes input and output files and their schema (columns).
- `naming.csv` describes variables used in plots and their colors, legend text etc.

While there is some overlap, `naming.csv` refers to values that aren't part of the output files, but instead derived from them (e.g. aggregates). The current plan is to describe a plot as depending on a set of pre-computation steps that function similar to other cea scripts and have input- and output files - the plots would know how to run those scripts automatically when being plotted. This will replace some portions of the `.cache` as well as simplifying how to present the plot raw data to the user. This will allow us to define the plot variables in `schemas.yml` and thus get rid of `naming.csv`.

**Comment by ShiZhongming** [comment]
name.csv no longer exsits. Hence, I am closing this issue.
