### ISSUE TITLE
As a Developer, I would like to remove the inputs.yml file to have a single point of truth for glossary information

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2681]
The information in this file is in a different format to the `schemas.yml` file - but could easily be expressed in that file.

**Comment by shanshanhsieh** [comment]
- augment `schemas.yml` schema to allow this
- update GUI (possibly) 
- edit API end points in cea.interfaces.dashboard.api.inputs to read from `schemas.yml`
- remove `inputs.yml` from MANIFEST.in
