### ISSUE TITLE
Leap day still shown in plots after being removed from the calculation

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2683]
**Describe the bug**
The leap day error was solved by removing 2/29 from all calculations in PR #2666.
However, in some plots, the leap day is still being displayed with empty values.

**To Reproduce**
1. Run solar radiation with this weather file: **Zuerich-SMA_2016 **
2. Open **solar radiation for district** in dashboard
![image](https://user-images.githubusercontent.com/16998305/78854556-313acc80-7a54-11ea-964d-84889e04d9a6.png)

**Expected behaviour**
The leap day should not be shown in plots.
Please inspect all plots that display data according to datetime.
For example, **Load curve of Heat and Pressure Losses for DH** does not have this issue.

**Comment by daren-thomas** [comment]
Idea: Maybe just change the year-portion of the timeseries to leap-year+1
