### ISSUE TITLE
CEA Installation (Error opening file for writing)

### ISSUE THREAD

**Issue by SanamDabirian** [architecture-building-systems/CityEnergyAnalyst#2684]
Dear CEA Team,

I am going to install the latest version of CEA, but I faced an error (opening files for writing). It does not work even if I select abort or retry or ignore. I would appreciate it if you guide me on how to resolve the issue.
Sincerely,
Sanam Dabirian

![CEA error](https://user-images.githubusercontent.com/55449782/78935204-4a567400-7a7a-11ea-8ecd-e61e89f59f69.jpg)

**Comment by reyery** [comment]
I was not able to reproduce this issue on my end. Maybe you could try installing [v3.0.1](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.0.1/Setup_CityEnergyAnalyst_3.0.1.exe) instead and running it as administrator. It could be because of write permissions.

**Comment by shanshanhsieh** [comment]
Dear @SanamDabirian,
Please check that you have the right permission to this folder, and let us know if the issue persists.
