### ISSUE TITLE
MuSES Grand Finale

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2686]
In YouTube CEA Channel 

3.5 Real Time Simulation Platform in Switzerland (MuSES Grand Finale Part 10/10)
4. Final Remarks and Q&A  

videos are missing. Can you upload them if they are available?

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA are you planning to publish the Final Remarks and Q&A?

**Comment by JIMENOFONSECA** [comment]
done! enjoy!
