### ISSUE TITLE
CEA Error on startup V.3.0.2. but not in v.3.0.1

### ISSUE THREAD

**Issue by LuVoGu** [architecture-building-systems/CityEnergyAnalyst#2690]
**Describe the bug**
I installed CEA following the blog tutorial and every time I tried to launch the dashboard two errors occured (screenshots).    
After a few new downloads and retries (errors occured every time) I downloaded v. 3.0.1 where the errors do not occur and the dashboard starts.

**To Reproduce**
1. install version 3.0.2
2. launch dashboard
3. error window pops up

**Expected behaviour**
The dashboard starting.

**Screenshots**
![Screenshot (2)](https://user-images.githubusercontent.com/63652852/79246117-55921100-7e79-11ea-82da-7d5b791fc57a.png)
![Screenshot (3)](https://user-images.githubusercontent.com/63652852/79246173-63e02d00-7e79-11ea-8529-3b321fea464c.png)

**Hardware (please complete the following information):**
 - Windows 10
 - CEA v. 3.0.2
- NOT in CEA v 3.0.1

**Comment by daren-thomas** [comment]
@LuVoGu this is very unfortunate. I will take special care to test this with the next release coming up end of this week. Please stay tuned. You can try installing V3.0.2 with the Developer mode - that _might_ work, but I will do some testing on Friday to make sure the next release will not have this error.

**Comment by daren-thomas** [comment]
fixed in #2694

@LoVoGu - the pre-Release [v3.0.3a0](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/tag/v3.0.3a0) resolves this issue. An official Release v3.1.0 can be expected by end of this week.
