### ISSUE TITLE
System_costs module doesn't include CapEx of all cooling systems

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#2693]
The system_costs.py module currently only considers Capital Expenditure of District Cooling and disregards Capex for other cooling technologies.  

The cooling capacity QC_sys0_kW should serve as a basis to calculate investment cost for all technologies.

**Comment by daren-thomas** [comment]
@shanshanhsieh can you please perform a triage for this issue?

**Comment by shanshanhsieh** [comment]
hi @emanuel030 , 
are you referring to line 92 in `system_costs.py`?
line 92:
```cooling[service + '_sys_total_capex_yr'] = cooling[service + '0_kW'] * cooling['CAPEX_USD2015kW']```
in which the services are defined as:  `cooling_services = ['DC_cs', 'DC_cdata', 'DC_cre']`

please also indicate what kind of assistance would you need to tackle this issue.
thanks!

**Comment by emanuel030** [comment]
Yes exactly! I already modified the code to make the investment cost dependent on the thermal capacity. I will have to check if it still works with the dashboard plots of costs before creating the pull request.
