### ISSUE TITLE
Handover Grasshopper connections to Zhongming

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CityEnergyAnalyst#2696]
Recently I received several interests and requests about using CEA in Grasshopper. As we ceased to maintain the Grasshopper connection, I wonder if we can fork it out and I can be the one who maintains it? Could we schedule a meeting @daren-thomas for a handover?

Thanks,
Zhongming

**Comment by shizhongming** [comment]
Hi @daren-thomas , concerning this, are you free some time next week to zoom call? My time is quite flexible. :)

**Comment by daren-thomas** [comment]
Hi @shizhongming I'll send you a meeting request on Outlook, ok?

**Comment by shizhongming** [comment]
@daren-thomas thanks and see you later today!

**Comment by daren-thomas** [comment]
This issue is complete with the creation of the `cea-grasshopper` repository.
