### ISSUE TITLE
in thermal_loads, system efficiency not accounted for in building-scale cooling system electricity calculations

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#2697]
We were comparing different supply technologies for a certain case study district and could not find any difference in total energy demand, even though the supply technologies have different efficiencies assigned to them in the SUPPLY database.

It turns out that the thermal_load module of the demand calculations does not take the system efficiency of the 'Building'-scale supply technologies with 'GRID' as a FEEDSTOCK into account. Instead it is modelling the electricity consumption based on a heatpump model. 

To ensure consistency of how the electricity consumption of the cooling systems is calculated, we propose to replace the heatpump model with a simplified calculation to calculate the E_cs. This way the results will be in line with the district scale E_cs and the system efficiency of building-scale cooling systems will be accounted for.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA is this still open? (asking you as you merged the PR #2697)

**Comment by JIMENOFONSECA** [comment]
It can be closed now

Dr. Jimeno Fonseca
Senior Researcher
SEC | ETH Zurich

Read more about City Energy Dynamics<https://www.jimenofonseca.com/>

On 23 Apr 2020, 16:47 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> is this still open? (asking you as you merged the PR #2697<https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2697>)
