### ISSUE TITLE
A guide on how to modify scripts in CEA and create a PR

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2699]
**Describe the feature you would like to have**
For the increasing numbers of collaborators in the CEA, we need to provide infomration on how to modify scripts in CEA and create a PR.

**Describe the end purpose of this feature**
To formalize the process of integrating new collaborators to the CEA development.

**Describe the end-user of this feature**
Anyone who has good ideas and would like to contribute. (A Researcher, a Student, or a Practitioner.)

**Provide Aditional information if possible**
Something similar to this document might be useful: https://city-energy-analyst.readthedocs.io/en/latest/how-to-add-a-new-script-to-the-cea.html

**Comment by shanshanhsieh** [comment]
I would also like to welcome our latest collaborators: @nasty-bos , @emanuel030 , @lguilhermers , @DavidKayanan.
Thank you for your interest, and we are as enthusiastic as you are!

We would like to have your help in shaping this document. 
Please comment here for any questions you have regarding how to modify scripts and create PR in CEA.

**Comment by daren-thomas** [comment]
Something like this: https://city-energy-analyst.readthedocs.io/en/latest/how-to-contribute.html?
It seems we already have that documentation. I'm still creating a PR - with a slightly altered index page, lot's of cleaning up etc.

**Comment by shanshanhsieh** [comment]
@daren-thomas that sounds good!
