### ISSUE TITLE
Incorrect Calculation: Comfort Chart / p_ws_from_t

### ISSUE THREAD

**Issue by compostable** [architecture-building-systems/CityEnergyAnalyst#2703]
**Comfort Chart**

The water vapor saturation pressure is being incorrectly calculated in [p_ws_from_t(t_celsius)](https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/3da65db9f8b26386a7523b15cac2c29a2c5e8bbc/cea/plots/demand/comfort_chart.py#L472):

The [following line](https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/3da65db9f8b26386a7523b15cac2c29a2c5e8bbc/cea/plots/demand/comfort_chart.py#L494):

`    return math.exp(C8/t+C9+C10*t+C11*t**2+C12*t**3+C13*math.log1p(t))`

Should read:

`    return math.exp(C8/t+C9+C10*t+C11*t**2+C12*t**3+C13*math.log(t))`

`math.log1p` adds one (1) to the temperature being used before taking the natural log, which produces an incorrect water vapor saturation pressure. This incorrect water vapor saturation pressure then looks to be propagated to your other psychrometric functions.

I came across this error while testing against PsychroLib's [GetSatVapPres](https://psychrometrics.github.io/psychrolib/_modules/psychrolib.html#GetSatVapPres) for added support of IP units. I've confirmed with ASHRAE 2013 Fundamentals that PsychroLib's calculations are correct.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh it would be good to groom this and other issues as soon as they are identified.  i.e., add the people with knowledge to the conversation. As for this issue @gabriel-happle could help, but I do not know if he is around?

**Comment by gabriel-happle** [comment]
Thank you very much @compostable for spotting this.
It was a great help that you directly linked to the correct equation and documentation in the issue description.
I created a PR for this #2721.
