### ISSUE TITLE
Naming of Cooling technologies in SUPPLY database of assemblies leads to confusion.

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#2704]
Cooling technologies in the SUPPLY database in 'databases\SG\assemblies' calls for a more concrete naming. The naming doesn't effect any of the code.

Naming is proposed as follows:
**Direct expansion unit** (no chiller water-air, or chiller air-air), those are other systems usually used only for central AC which have a chiller (a vapor compression unit normally and either a dry-cooling tower or a wet-cooling tower.
Differentiate between **dry and wet cooling tower** (they are different and have different efficiencies).

**Comment by JIMENOFONSECA** [comment]
@emanuel030 merged? if so, congrats, you can close the issue

**Comment by emanuel030** [comment]
great! yes the database got updated
