### ISSUE TITLE
Check to make sure the format of outputfiles for thermal-network is the same for simplified / detailed

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2710]
I'm not sure this is the case - also, we haven't been testing both of these lately. Instead, we have been using the simplified model. 

See also issue #2700 (Heating Reset Curve plot does not work with reference-case-open / standard workflow (simplified network model))

**Comment by daren-thomas** [comment]
In issue #2667 I tracked down the differences (NOTE: needs to be checked for DC too - they might be different):

I noticed some discrepancies with the `thermal-network` script outputs, depending on if "simplified" or "detailed" model is used:

- `get_thermal_network_node_types_csv_file`:
  - detailed columns: `[,Name,Type,Building,coordinates,Q_hex_h_ahu,Q_hex_h_aru,Q_hex_h_shu,Q_hex_h_ww,Q_hex_plant_kW]`
  - simplified columns: `[Building,Type]`
  - NOTE: I think this is connected with issue #2700
- `get_thermal_network_edge_list_file`: detailed version includes `Name` column
- `get_thermal_network_plant_heat_requirement_file`: the only column in this file has the header `NONE`. That's hardly better than "Unnamed: 0" and should probably be renamed to... idk... `plant_thermal_load_kW` or something?
- `get_thermal_demand_csv_file`: detailed version has extra (unnamed) column for the hours

NOTE: This also means we'll need to update the `schemas.yml` descriptions for the columns currently missing...

**Comment by shanshanhsieh** [comment]
@reyery , what is the status of this issue? is the estimate still valid?
