### ISSUE TITLE
Rename the "Unnamed: 0" column in get_optimization_decentralized_folder_building_cooling_activation

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2712]
The `decentralized` script produces the file `get_optimization_decentralized_folder_building_cooling_activation` that has an index column called "Unnamed: 0" - this should either be renamed or dropped.

**Comment by daren-thomas** [comment]
NOTE: These output files show the same problem:

- `get_optimization_decentralized_folder_building_result_cooling`
- `get_optimization_decentralized_folder_building_result_heating`
- `get_optimization_decentralized_folder_building_result_heating_activation`

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA what is the status of this issue?

**Comment by JIMENOFONSECA** [comment]
yeah, I just send a PR for this.


On 13 May 2020, 3:33 PM +0800, Shanshan Hsieh <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> what is the status of this issue?

**Comment by JIMENOFONSECA** [comment]
solved in #2728
