### ISSUE TITLE
Update optimization script to remove "Unnamed: 0" columns in output

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2713]
Output files found:

- `get_optimization_generation_connected_performance`
- `get_optimization_generation_disconnected_performance`
- `get_optimization_generation_total_performance`
- `get_optimization_generation_total_performance_pareto`
- `get_optimization_individuals_in_generation`

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I'm assigning this task to you for now as you probably know best how to do this. If you can't make it this sprint, please let me know and move it back to the product backlog and un-assign yourself.

**Comment by JIMENOFONSECA** [comment]
solved in #2728

**Comment by shanshanhsieh** [comment]
@daren-thomas , i am not sure where did you retrieve this list, but
- `get_optimization_generation_connected_performance`
- `get_optimization_generation_disconnected_performance`

were renamed to
- `get_optimization_generation_district_scale_performance`
- `get_optimization_generation_building_scale_performance`

just FYI

**Comment by daren-thomas** [comment]
probably changed _after_ I made the list...
