### ISSUE TITLE
Run coverage on the slow testing workflow to make sure we're testing all code paths

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2715]
This is important so we know what code paths are acutally being tested on a regular basis and which ones might be "dead code". We need this information along with sample output from such a comprehensive workflow test when we port to Python3, so we know that we're actually creating the same product.

- coverage (i think this is the name of the tool) runs a python script and reports on how much (%) of the script is actually being used and points out the branches (like `if / else`) that don't get used.

**Comment by shanshanhsieh** [comment]
@reyery what's the status of this issue?

**Comment by daren-thomas** [comment]
Reynold has run coverage with `cea test --workflow slow` and we have about 40% coverage.

**Comment by daren-thomas** [comment]
@reyery can you please post me the branch so I can join you in our efforts?
