### ISSUE TITLE
As a User I would like to be able to run scripts only after completion of other scripts

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2717]
The `cea workflow` system kind of is a solution to this, but when running scripts using the GUI, say you start a new scenario and run some short scripts (`weather-helper`, `archetypes-mapper`) etc. Next, you want to run `radiation` and then `demand`. Well. Currently you have to run `radiation`, _wait_ for it to complete and _then_ run `demand`. 

What if we could schedule the `demand` script to run when the `radiation` script completes?

Also: If `radiation` failes, the `demand` script should fail too!

I think the tools page should allow assigning a job (identified by id as well as the set of parameters and current state of execution) as a dependency.

**Comment by ShiZhongming** [comment]
With CEA4, we have a batch process workflow feature to let the users to design a workflow. Also, with CEA4, a script's RUN button will only be activated when the necessary file exsits. Hence, to a high extent, we have resolved this issue. Hence, I am closing it.
