### ISSUE TITLE
ERROR: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by PMAU-yahoo** [architecture-building-systems/CityEnergyAnalyst#2720]
I tried to work with the reference-case-open that you provided, but I got the following message:

ERROR: 'NoneType' object is not iterable

Attached a screenshot of the error.

I arrived at that error by doing the following: I opened the project -> selected the scenario -> the tool sent me to the "Input editor" section -> I clicked back into the "Project overview" section and directly back to the "Input editor" section -> then the error appeared.

I didn't modify anything or clicked in any other button.

Now I cannot see the case in the "input editor" even if I start the tool again, but I can run it (I tried the energy demand forecasting and worked) and plot the results in the dashboard.

I "solved" the problem by extracting the folder again from the zip file, but I thought it could be important for your developers to know about the error.

![ErrorCEA](https://user-images.githubusercontent.com/64597666/80721792-f0881d80-8afe-11ea-82b5-793d1822d58f.jpg)

**Comment by shanshanhsieh** [comment]
dear @PMAU-yahoo , 
thank you for bringing this issue to our attention. 
we tried to reproduce it, but failed. 
we are glad that you can solve this issue on your own!
