### ISSUE TITLE
'MissingInputDataException' Solar Radiation

### ISSUE THREAD

**Issue by MarelloAvanzini** [architecture-building-systems/CityEnergyAnalyst#2724]
**Describe the bug**
I have run successfully the 'Building solar radiation' simulation for all the buildings in my scenario, however when I run the 'Building energy demand' on the same buildings an error occurs saying that radiation data is missing.

**To Reproduce**
1. Click on 'Open Project'
2. Find the path of 'Boavista trial - working':
[Boavista trial - working.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4586275/Boavista.trial.-.working.zip)
3. Go to 'Demand forecasting' > 'Building solar radiation'
4. Open 'builgins' selection list, click on 'B1000' and 'Run script'
5. After the Script is completed, go to 'Demand forecasting' > 'Building Energy Demand'
6. Open 'builgins' selection list, click on 'B1000' and 'Run script'
7. See error:
[bug energy demand.txt](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4587736/bug.energy.demand.txt)

**Expected behaviour**
'Building energy demand' should read the radiation data previously generated.

**Hardware (please complete the following information):**
 - iOS 10.12 (CEA running on Windows 10 partition)
 - CEA v. 3.2

**Comment by shanshanhsieh** [comment]
@MarelloAvanzini we will test your input files and get back to you!

**Comment by reyery** [comment]
@MarelloAvanzini based on the input files that you provided, it seems that it is missing the weather, terrain and surrounding geometry files that are needed for `radiation` to run. 

You could use the **weather-helper**, **terrain-helper** and **surroundings-helper** tools in CEA to help you generate these files.

Subsequently, you would have to run **schedule-maker** to create occupancy data for the buildings then run demand

**Comment by daren-thomas** [comment]
@MarelloAvanzini, I hope @reyery 's comment (see above) helped you get it up and running. We're closing the issue for now but will gladly re-open it if you need further assistance.
