### ISSUE TITLE
Fiona/gdal import error: DLL failed : the operating system cannot run%1

### ISSUE THREAD

**Issue by 89ng** [architecture-building-systems/CityEnergyAnalyst#2726]
**Describe the bug**
when startup dashbord, it reported an import error: DLL failed : the operating system cannot run%1, it seems it is related to fiona/gdal, and the same issue occured when I manualy imported fiona/gdal (see as the image below),
I have checked  all the related issues in this repository (including#1708), but none of these worked. I have also tried to re-installed it several times, but the same issues appeared again and again. Could you please give me some help? Or a guidance to install it and configure the proper environment in anaconda3 is also ok (I have anaconda3, but still new to python, especially in terms of environment configuration) . Thank you in advance!

**Screenshots**
![image](https://user-images.githubusercontent.com/58104779/81473455-f7014e00-91fe-11ea-968a-69219a9098db.png)

![image](https://user-images.githubusercontent.com/58104779/81473180-0f706900-91fd-11ea-881e-06025cfcd9d5.png)

(The messy code & Chinese characters mean "the operating system cannot run%1")

**Hardware (please complete the following information):**
 - OS and version: [Windows 10]
 - Version of CEA you are using [e.g. v. 3.2.0]

**Comment by daren-thomas** [comment]
@89ng - can you try importing `fiona` using the python shipped with the CEA Console please? Check your start menu for the "CEA Console" program, then type python.

The CEA Console contains some additional settings (to the environment variables) that are required for GDAL dlls.

Does this solve your issue?

**Comment by 89ng** [comment]
Thank you for your kind reply! But it seems it still does not work. Did I do it correctly? Sorry I am really new to this.
![image](https://user-images.githubusercontent.com/58104779/81542452-f4c10000-9374-11ea-9aaa-b2c35ddafeb6.png)
(The Chinese characters mean "the operating system cannot run%1")

**Comment by daren-thomas** [comment]
@89ng - when you installed the CEA - did you copy it from the installation location to "F:\CES\..." or did you install it to that folder directly?

Can you please try to install it to the default location (in your user profile) and see if that helps?

**Comment by 89ng** [comment]
I just changed the installation location at that time, but I will reinstall it to the default location right now, thank you!

**Comment by 89ng** [comment]
Seems it doesn't work, the same error occured, so weird
![image](https://user-images.githubusercontent.com/58104779/81551424-1d032b80-9382-11ea-8108-cd9bb1320438.png)

**Comment by 89ng** [comment]
Is that possible that I configure the environmental variables or create an unaffected environment mannually?

**Comment by daren-thomas** [comment]
@89ng as per our video call yesterday, I'm closing this. Thank you for taking time to try and debug this with me. I believe the error is due to an unknown state of your operating system. Please feel free to re-open this issue if you have new information. Good luck with your course today!
