### ISSUE TITLE
Other optimization objectives for solar panel tilt angles

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#274]
In `photovoltaic.py`, currently the tilt angle is optimized for the maximum yearly yield. Other optimization objectives could be maximum grid penetration, autonomy...

**Comment by shanshanhsieh** [comment]
Also research on suitable PV panel tilting strategies suitable in Singapore.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh is it part of the PR #334

**Comment by shanshanhsieh** [comment]
nope, this will require further research. There are some references from SERIS already, should not be a big problem. This issue falls in category 1 - stuff we are definitely going to do.

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
