### ISSUE TITLE
Negative values in schemas.yml for databases

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2743]
After implementing **min/max** properties for numerical values in schema.yml (https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2730), there are a few values in the database editor that are throwing errors for being negative while **min** property is set to 0.

Below are the values found that are throwing errors:
- use-types:Indoor Comfort: **Ths_setb_C**
- assemblies:HVAC:controller: **dT_Qcs**
- components:conversion:PV: **PV_a0, PV_a2, PV_a4**
- components:conversion:Absorption_chiller: **r_e, r_g, a_e, a_g**
- components:conversion:HEX: **a, d_p**
- components:conversion:HP: **e**
- components:conversion:TES: **e**

**Comment by shanshanhsieh** [comment]
use-types:Indoor Comfort: Ths_setb_C -> could be negative in COOLROOMS 
assemblies:HVAC:controller: dT_Qcs -> could be negative
@shanshanhsieh will update the rest

**Comment by shanshanhsieh** [comment]
components:conversion:PV: *PV_a1, PV_a2, PV_a4* : *[+0.1,-0.1]*
components:conversion:Absorption_chiller: r_e, r_g, a_e, a_g: could be negative (no fixed bound)
components:conversion:HEX: a, d_p: could be negative (no fixed bound)
components:conversion:HP: e: could be negative (no fixed bound)
components:conversion:TES: e: could be negative (no fixed bound)

**Comment by reyery** [comment]
@shanshanhsieh so for PV_a1, PV_a2, PV_a4, max is 0.1 and min is -0.1. Does that also apply to PV_a0 and PV_a3?

**Comment by shanshanhsieh** [comment]
not exactly, but we can allow that, since these parameters are model specific, there could be other models that require this range.
