### ISSUE TITLE
Update schemas.yml for get_optimization_decentralized_folder_building_result_heating_activation

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2749]
While fixing #2667, I noticed that the file `get_optimization_decentralized_folder_building_result_heating_activation` does not correspond to the `schemas.yml` entry.

missing fields in the file according to schemas.yml:

- BackupBoiler_Status
- Q_BackupBoiler_gen_directload_W
- NG_BackupBoiler_req_Wh
- NG_Boiler_req_Wh
- Q_GHP_gen_directload_W

extra fields found in the file according to schemas.yml:

- NG_Boiler_req_W

**Comment by reyery** [comment]
After looking through the code, the columns for `get_optimization_decentralized_folder_building_result_heating_activation` are not consistent as they are based on different technologies with different properties, and selected based on which is ranked the __"best"__. 

This behaviour also happens for cooling counterpart `get_optimization_decentralized_folder_building_cooling_activation` 
(should this be renamed to match the heating method? i.e. *result_cooling_activation)

## 0: Boiler NG
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/7641b9ac3adc280acd5172e51cae07366f18a494/cea/optimization/preprocessing/decentralized_buildings_heating.py#L115-L118

## 1: Boiler BG
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/7641b9ac3adc280acd5172e51cae07366f18a494/cea/optimization/preprocessing/decentralized_buildings_heating.py#L125-L128

## 2: Fuel Cell
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/7641b9ac3adc280acd5172e51cae07366f18a494/cea/optimization/preprocessing/decentralized_buildings_heating.py#L145-L149

## 3-13: Boiler NG + GHP
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/7641b9ac3adc280acd5172e51cae07366f18a494/cea/optimization/preprocessing/decentralized_buildings_heating.py#L198-L206

Output
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/7641b9ac3adc280acd5172e51cae07366f18a494/cea/optimization/preprocessing/decentralized_buildings_heating.py#L316-L318

**Comment by reyery** [comment]
It seems that most of these columns that being written to disk are not used in any calculations. Only `E_hs_ww_req_W` column seems to be used when get electricity demand of buildings.

`NG_BackupBoiler_req_Wh` and `NG_Boiler_req_Wh` seems to used to get fuel demand of buildings, but the function `extract_fuels_demand_buildings` that is assessing them is not being used - it is commented out. Do we still need this function? Maybe @JIMENOFONSECA might know something about this?

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/f5e116a6623745866ae1e669846ddfc7f50468c1/cea/optimization/master/evaluation.py#L131

If not we could simplify the output, also the schema, and not write any of the other columns.

**Comment by JIMENOFONSECA** [comment]
Hi Rey, shanshan made the script,  it may be needed still. What about the plots? Do they reference to it somehow?
On 1 Jun 2020, 16:39 +0800, Reynold Mok <notifications@github.com>, wrote:

It seems that most of these columns that being written to disk are not used in any calculations. Only E_hs_ww_req_W column seems to be used when get electricity demand of buildings.

NG_BackupBoiler_req_Wh and NG_Boiler_req_Wh seems to used to get fuel demand of buildings, but the function extract_fuels_demand_buildings that is assessing them is not being used - it is commented out. Do we still need this function? Maybe @JIMENOFONSECA<https://github.com/JIMENOFONSECA> might know something about this?

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/f5e116a6623745866ae1e669846ddfc7f50468c1/cea/optimization/master/evaluation.py#L131

If not we could simplify the output, also the schema, and not write any of the other columns.

**Comment by daren-thomas** [comment]
@reyery and @daren-thomas are currently thinking the best way is to just list all the columns all the time with a "N/A" style output for technologies that aren't used. Maybe somewhere down the road someone will do some analysis on this output and having the data tidy (e.g. not having to check each output file for existing columns) will make their job a lot easier.

**Comment by shanshanhsieh** [comment]
plan of attack
1. check whether `E_hs_ww_req_W ` , `NG_BackupBoiler_req_Wh`, `NG_Boiler_req_Wh` are being used in plots, and thus needed to be included in `schema.yml`
2. decide to output none of the columns or use `N/A` for all columns at all time

**Comment by reyery** [comment]
An idea to solve this would be to initialize `heating_dispatch` as an empty DataFrame 

```
heating_dispatch = pd.DataFrame()
```

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/7641b9ac3adc280acd5172e51cae07366f18a494/cea/optimization/preprocessing/decentralized_buildings_heating.py#L98

Then append each technology as a row in the DataFrame. When appending, any columns that do not exist should be initialized as NA.

```
heating_dispatch.append({'Q_Boiler_gen_directload_W': q_load_Wh, 
                        'Boiler_Status': Boiler_Status, 
                        'NG_Boiler_req_W': Qgas_to_Boiler_Wh, 
                        'E_hs_ww_req_W': np.zeros(8760)})
```

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/7641b9ac3adc280acd5172e51cae07366f18a494/cea/optimization/preprocessing/decentralized_buildings_heating.py#L115-L118

Would have to change the how the rows are being iterated as well

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/7641b9ac3adc280acd5172e51cae07366f18a494/cea/optimization/preprocessing/decentralized_buildings_heating.py#L280
