### ISSUE TITLE
Find other methods for SC heat loss calculation

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#275]
In `solar_collector.py`, the collector heat loss is adapted from TRNSYS code, which is able to calculate to secondly time steps. Compare what is used in Sandia library.

**Comment by shanshanhsieh** [comment]
There is no solar thermal collector model in the Sandia library, but I will still look into other methods.

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
