### ISSUE TITLE
Move the hard-coded values out of chiller_vapor_compression into CONVERSION database

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#2751]
In the process of writing new functions to account for part load operation in the 'chiller_vapor_compression' module, several technology specific values were introduced for the calculations. Those should be moved into the 'Chiller' sheet of the CONVERSION workbook of the component database. 

To clean up the code further, a class for the vapor compression chiller shall be introduced, passing down information on the isentropic efficiency (G-Value), maximum/minimum chiller size and part-load specific values,  extracted from the CONVERSION workbook in the 'cooling_main' module down to the 'chiller_vapor_compression' module.

Help, especially regarding creating the class would be highly appreciated.

**Comment by shanshanhsieh** [comment]
@reyery would definitely be able to help on the code structure!

**Comment by daren-thomas** [comment]
@emanuel030 do you have an update to this issue?

**Comment by reyery** [comment]
Closed with #2799
