### ISSUE TITLE
Error in mutation part of the centralized optimization 

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#2752]
When running the centralized optimization ('optimization_main') with a specific case study, the optimization shows an error when mutating the cooling system size. More precisely, the "individual" seems to be of 0 length. 

This error is specific for a specific case study and has not appeared with other scenarios. The case study is saved in this folder: https://polybox.ethz.ch/index.php/s/cpZ6TS03Zw1TsFy

![image](https://user-images.githubusercontent.com/26175926/83222053-fd556b00-a1a9-11ea-923c-02c321453671.png)

The used config file : 
[cea.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4699727/cea.zip)

**Setup:**
 - Windows 10
 - CEA Version 3.3.0 (master branch)

**Comment by emanuel030** [comment]
This error only appears if no technology is selected, as in 'technologies-dc' in the optimization section of the config file

**Comment by shanshanhsieh** [comment]
@reyery will change the default to all technologies if none is specified

**Comment by reyery** [comment]
Just a clarification, must there be at least be a single technology selected (for either DH or DC) for optimization to run?

**Comment by emanuel030** [comment]
> Just a clarification, must there be at least be a single technology selected (for either DH or DC) for optimization to run?

@reyery Yes, I believe so since otherwise the optimization runs into problems when mutating the share of each technology, since there is no share to mutate at all. I would suggest to put Base VCC as a standard.

**Comment by daren-thomas** [comment]
@reyery is going to to a slight modification to `MultiChoiceParameter` (add parameter config `nullable`, if set to false, emtpy strings and lists get decoded to _all selected_)

**Comment by reyery** [comment]
Anyone knows if config parameters for **thermal-network** `substation-cooling-systems` and `substation-heating-systems` can be empty i.e no selection?

Also are `re` and `data` valid choices for `substation-cooling-systems`?

```
[thermal-network]

substation-cooling-systems = ahu, aru, scu
substation-cooling-systems.type = MultiChoiceParameter
substation-cooling-systems.choices = ahu, aru, scu, re, data
substation-cooling-systems.help = List of cooling loads to be supplied (DC mode)
substation-cooling-systems.category = Parameters of detailed model

substation-heating-systems = ahu, aru, shu, ww
substation-heating-systems.type = MultiChoiceParameter
substation-heating-systems.choices = ahu, aru, shu, ww
substation-heating-systems.help = List of heating loads to be supplied (DH mode)
substation-heating-systems.category = Parameters of detailed model
```
