### ISSUE TITLE
Include fuel demand into optimization

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2755]
Currently, fuel demand electricity is not included into optimization as the function is being commented out.

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/f5e116a6623745866ae1e669846ddfc7f50468c1/cea/optimization/master/evaluation.py#L131

**Comment by shanshanhsieh** [comment]
@reyery is it required for Nexus-e? The primary energy is no longer and objective in the optimization.

**Comment by shanshanhsieh** [comment]
@reyery , i think we can safely delete that section of the code.
the calculation was moved to `calc_costs_emissions_decentralized_DH`

**Comment by daren-thomas** [comment]
Status update: This is about deleting a single line. @daren-thomas will do it in the python3 branch.

**Comment by daren-thomas** [comment]
Status update: @daren-thomas _won't_ be doing it in the python3 branch. Instead, he'll do it _after_ the python3 branch is merged to keep the port as conservative as possible.

**Comment by shanshanhsieh** [comment]
Hi @MatNif , 
assigning this issue to you as you are the main developer of the optimization script for now.
i think we can delete that line in your next PR, thanks!
