### ISSUE TITLE
Correct electromobility explanation

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2757]
**Describe the bug**

Curently, the variable _Ev_kWveh_ is erroneously explained in the **Input Editor**. In the glossary, there isn't any information. This is important, as currently there is little explanation about the electric mobility feature, when I believe it represents an increasingly important feature. 

**To Reproduce**

1. Go to Input Editor
2. Select _internal-loads_
3. Go to _Ev_kWveh_ column label 

**Expected behaviour**

I believe a correct explanation would be: "Effective electric load (rated power) per vehicle when charging [kW/vehicle]" 

In such cases, I believe a good default value would be 3,7 kW, a typical value for domestic electric car chargers. It corresponds to a single phase (RMS voltage = 230 V) at 16A

**Screenshots**

What is currently shown in the app: 

![Screen Shot 2020-06-04 at 15 45 35](https://user-images.githubusercontent.com/32110882/83771734-8244f680-a67a-11ea-9002-87214f5dcc3d.png)

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - Version of CEA: 3.1

**Comment by daren-thomas** [comment]
@AlexJew thank you for pointing this out! This kind of attention to detail really helps us improve the CEA :)

@JIMENOFONSECA can you look into this please? Might be as simple as editing one field in `schemas.yml` and also updating the databases (if we really want to change the default value)...

**Comment by JIMENOFONSECA** [comment]
@daren-thomas sure, easy to solve, I made a PR #2768 for this. I hope this solves the issue.
