### ISSUE TITLE
Enable different solar collector connection configurations

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#276]
In `solar_collector.py`, individual solar collectors are all connected in parallel, which leads to higher mass flow rate than in reality.
We need to create the option to calculate different types of collector arrangements using building as unit (parallel/series/combined).

**Comment by shanshanhsieh** [comment]
refer to Sandia PVlib class `pvlib.pvsystem.PVSystem` for array arrangement: N(series)*M(parallel) 
[http://pvlib-python.readthedocs.io/en/latest/modules.html#module-pvlib.pvsystem](url)

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
