### ISSUE TITLE
Value Error in network-layout for multiple case studies

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#2761]
Running network-layout I ran into the following error for multiple case studies. For multiple other case studies it ran without problems.

`ValueError: There was an error while creating the Steiner tree. Check the streets.shp for isolated/disconnected streets (lines) and erase them, the Steiner tree does not support disconnected graphs.`

Checking in Arcmap for disconnected streets manually none could be found. I further tried both 'planarize lines' as well as 'integrate' with a large tolerance (up to 1m) to connect possibly disconnected lines. Those methods didn't solve the issue though. The methods are described here:
https://gis.stackexchange.com/questions/109378/checking-connectedness-of-line-shapefile-in-arcmap

The code produces empty edges and node files in the DC folder of the thermal-network folder.

The full error is shown here:
![image](https://user-images.githubusercontent.com/26175926/84057259-00422e00-a9ea-11ea-916a-ba269e850036.png)

I have uploaded a error-throwing case study here: https://polybox.ethz.ch/index.php/s/bMBPwkWu8CwnlUk

**Comment by emanuel030** [comment]
@JIMENOFONSECA do you have an idea if this error is in relation to the changes made in April?

**Comment by JIMENOFONSECA** [comment]
well. did you check if there are streets floating around in the shapefile?

**Comment by emanuel030** [comment]
That was the first thing I did. And none could be found.. I have further used tools 'planarize lines' and 'integrate' to combine lines which are within a certain tolerance. This results in the following change in street files (e.g. case study LCZ2_Expo, 1. is original, 2. after 'integrate'):
![image](https://user-images.githubusercontent.com/26175926/84117993-f1e52800-aa64-11ea-8e13-bcd98c979d99.png)
![image](https://user-images.githubusercontent.com/26175926/84118017-f9a4cc80-aa64-11ea-989f-ea9457a908d1.png)

But also with those 'simplified' and combined street shapefiles the error couldnt be lifted. Could there be another source?

By now I had this error in 5 different case studies:
(LCZ1_Parangon, LCZ2_Expo, LCZ3_FrankelAve, LCZ4_BoonLay, LCZ6_MountEchoPark)

**Comment by daren-thomas** [comment]
@emanuel030, @shanshanhsieh is this issue resolved? the PR #2762  connected with this issue was merged. did it resolve the issue?

**Comment by emanuel030** [comment]
@daren-thomas the PR did not resolve the issue.  I run into this error roughly every second case study i am running and have to manually edit the streets.shp files in ArcGis in order to succesfully run the network-layout. We amended a comment in the PR, describing on how to solve this error in ArcGis.
