### ISSUE TITLE
Automate the process of creating new releases of CEA

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2769]

**Comment by daren-thomas** [comment]
This should be `cea-dev release` and it should create an installer for the version found in `cea/__init__.py::__version__`.

- pack `Dependencies.7z` to installer
- pack `win-unpacked.7z`  to installer
- avoid PyPI versions
- automate creating CHANGELOG etc.

**Comment by daren-thomas** [comment]
include publishing docker image
