### ISSUE TITLE
Solar Radiation

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2773]
**Describe the bug**
No plot for Solar Radiation (hourly-daily-weekly)
Solar radiation normalization fails (gross floor area-net floor area-air conditioned floor area-building occupancy) Total_demand.csv doesn't exist

**To Reproduce**
1. Run building solar radiation
2. Add plot

**Screenshots**
![SR1](https://user-images.githubusercontent.com/29708612/84590328-3e05e300-ae3e-11ea-8ba3-4a89f6ce54b2.jpg)
![SR2](https://user-images.githubusercontent.com/29708612/84590336-45c58780-ae3e-11ea-83b4-231e6a6e8ffc.jpg)
![SRN1](https://user-images.githubusercontent.com/29708612/84590346-4d852c00-ae3e-11ea-8107-f6f82d165b86.jpg)
![SRN2](https://user-images.githubusercontent.com/29708612/84590352-5aa21b00-ae3e-11ea-812a-e45b381f82ee.jpg)

**Hardware (please complete the following information):**
 - OS Windows 8.1
 - CEA 3.4.0

**Comment by daren-thomas** [comment]
@kerembeygo thank you for pointing this out! We've done some digging and it seems something in the plotly libraries might have changed in a new release - we'll need to look into this more closely.
