### ISSUE TITLE
Photovoltaic Potential

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2774]
**Describe the feature you would like to have**
I ran photovoltaic panels for PV1, PV2, PV3. 
No plot for hourly, daily, weekly
For monthly and yearly plots there is no indication for PV type

**Describe the end purpose of this feature**
I want to see results for PV types

**Describe the end-user of this feature**
A Researcher, a Student, or a Practitioner.

**Provide Aditional information if possible**
![PV1](https://user-images.githubusercontent.com/29708612/84591132-a35cd280-ae44-11ea-9cd3-dddb2359f415.jpg)
![PV2](https://user-images.githubusercontent.com/29708612/84591134-a657c300-ae44-11ea-956b-a6ed390c63a5.jpg)

**Comment by daren-thomas** [comment]
@kerembeygo this seems to be connected to #2773
