### ISSUE TITLE
Solar Collector

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2775]
**Describe the feature you would like to have**
No plot for FP collectors
No plot (hourly, daily, weekly) ET collectors

**Describe the end-user of this feature**
Ex. A Researcher, a Student, or a Practitioner.

**Provide Aditional information if possible**
![SC1](https://user-images.githubusercontent.com/29708612/84591483-7fe75700-ae47-11ea-8589-e1e5a3b28b5f.jpg)
![SC2](https://user-images.githubusercontent.com/29708612/84591488-8544a180-ae47-11ea-9a09-f21ac3abad29.jpg)

**Comment by daren-thomas** [comment]
@kerembeygo this seems to be connected to #2773
