### ISSUE TITLE
Photovoltaic-thermal panels

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2776]
**Describe the feature you would like to have**
Options for PVT are 
FP -> PV1, PV2, PV3
ET -> PV1, PV2, PV3
But there are no plot options 

**Describe the end-user of this feature**
Ex. A Researcher, a Student, or a Practitioner.

**Provide Aditional information if possible**
![PVT1](https://user-images.githubusercontent.com/29708612/84592181-6bf22400-ae4c-11ea-9a2c-3e28e9d713ca.jpg)

**Comment by daren-thomas** [comment]
@kerembeygo could you please elaborate on this:

> But there are no plot options 

I'm not quite sure what you're expecting or envisioning here. What kind of options do you mean?

**Comment by kerembeygo** [comment]
![pvt1](https://user-images.githubusercontent.com/29708612/84653003-3cf3b500-af15-11ea-970c-17139ad2892d.jpg)

There are three types of PV (PV1, PV2, PV3)
Two types of SC (FP-ET)
When I want see the simulation resuIts for each option I can not choose the panel type

![pvt3](https://user-images.githubusercontent.com/29708612/84653587-5e08d580-af16-11ea-92fd-19c8363f193d.jpg)

Results for which PV-SC type

![pvt2](https://user-images.githubusercontent.com/29708612/84653702-914b6480-af16-11ea-9a9c-a6f8d80545a9.jpg)

**Comment by shanshanhsieh** [comment]
Hi @kerembeygo, 
It is not possible to run multiple types of PV in the same scenario, the results get overwritten.
We recommend you to create multiple scenarios with different types of PV or SC, and compare the results among these scenarios.
