### ISSUE TITLE
New scenario: Could not find weather file

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2778]
**Describe the bug**
Traceback (most recent call last):
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\api\project.py", line 185, in post cea.api.weather_helper(config, scenario=new_scenario_path)
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 58, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 38, in script_runner script_module.main(config)
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\weather_helper.py", line 50, in main copy_weather_file(config.weather_helper.weather, locator)
  File "c:\users\kerem\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\weather_helper.py", line 31, in copy_weather_file source_weather_file=source_weather_file
AssertionError: Could not find weather file: 

**To Reproduce**
Create new scenario
Generate new input files using tools
Draw area 
Create
AssertionError: Could not find weather file:

**Expected behaviour**
I didn't have this error before. I was able to create new scenarios for Istanbul and Zurich

**Screenshots**
![NS1](https://user-images.githubusercontent.com/29708612/84593051-8f1fd200-ae52-11ea-85b2-88ac98912a83.jpg)
![NS2](https://user-images.githubusercontent.com/29708612/84593055-91822c00-ae52-11ea-90bc-1aa5cd88cdce.jpg)
![Weather File](https://user-images.githubusercontent.com/29708612/84593059-95ae4980-ae52-11ea-8512-142f38f1b513.jpg)

**Hardware (please complete the following information):**
 - OS and version: Windows 8.1
 - CEA V3.4.0

**Comment by daren-thomas** [comment]
@kerembeygo, the error message looks like you did not specify a weather file in the scenario creation screen. Could you please re-try the scenario creation process, but explicitly selecting the weather (click the configure icon next to it)
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/684323a1-462d-40b1-9c43-8a3b48e84165)

@reyery could the GUI check this on submit?

**Comment by kerembeygo** [comment]
@daren-thomas all options were checked in data management tools (picture above)

I repeated the same process today.

![Zurich4 ERR2](https://user-images.githubusercontent.com/29708612/84647697-72e06b80-af0c-11ea-81e6-f47092c0ad99.jpg)

weather file checked

![Zurich4 ERR3](https://user-images.githubusercontent.com/29708612/84647754-87246880-af0c-11ea-9004-5e383518ae20.jpg)

different area in Zurich

![Zurich4 ERR](https://user-images.githubusercontent.com/29708612/84647787-94415780-af0c-11ea-9efa-b15d3354a287.jpg)

same error message

![Zurich4 ERR5](https://user-images.githubusercontent.com/29708612/84647817-a28f7380-af0c-11ea-9363-c4ee309ece57.jpg)

other inputs seem to be OK

![Zurich4 ERR4](https://user-images.githubusercontent.com/29708612/84647850-b044f900-af0c-11ea-8218-f12c5113570b.jpg)

**Comment by kerembeygo** [comment]
I tried another district in Istanbul without checking the weather file. 

![Nisanca2](https://user-images.githubusercontent.com/29708612/84648796-301f9300-af0e-11ea-8b77-59b1a599572f.jpg)

I got no error message this time

![Nisanca3](https://user-images.githubusercontent.com/29708612/84648835-3c0b5500-af0e-11ea-8026-d05c179f90da.jpg)

**Comment by reyery** [comment]
@kerembeygo could you check the `cea.config` file and under `weather-helper`, is weather empty? If it is, you would have to press the gear icon beside the weather-helper tool in the GUI to set the file path.

**Comment by kerembeygo** [comment]
I set the file path this time and there was no error. Config file weather-helper is set to file path.

But solar radiation for district plot gives no results for certain months. Plot covers more than one year

![SR1](https://user-images.githubusercontent.com/29708612/84655526-c1e0cd80-af19-11ea-9694-4c0b37dca9ce.jpg)

**Comment by daren-thomas** [comment]
@kerembeygo could you please send us this scenario to try and reproduce your error? maybe also a copy of the weather file you are using?

**Comment by kerembeygo** [comment]
[Nisanca4.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4830666/Nisanca4.zip)

**Comment by daren-thomas** [comment]
@kerembeygo I'm sorry, I've been very busy with the porting of the CEA to the newest version of Python and haven't gotten around to looking into this.

From a quick scan of your screenshots, it looks like your weather file contains multiple years. We don't support this. Can you try with another weather file, that only contains data for one year?

@reyery just checked the .epw file in the scenario you posted. The number of rows seems to be right, but the year column seems to be wrong.
