### ISSUE TITLE
Check for empty geometries in streets.shp file

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2785]
In reference to #2782, when the `streets.shp` file has an empty geometry, the current error message is `AttributeError: 'NoneType' object has no attribute 'is_empty'` - this should be more helpful.

Checking the shapefile on read with the `ShapefileSchemaIo` class (e.g. `locator.get_street_network.read()`) for empty geometries should produce this message, maybe as a warning, and just ignore those geometries.

**Comment by ShiZhongming** [comment]
Interesting to know that this is a known issue.
We encountered the same with an IDP Student HS24 yesterday. We have resolved it.
