### ISSUE TITLE
Radiation status:Running - Daysim simulation finished

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2788]
**Describe the bug**
I ran the radiation tool for a district in Zurich. Simulation ended (plots available for solar radiation) but I had contradictory messages at the end. 

When I want to open my scenario and see my district in 3D I have a blank screen.

**To Reproduce**
1.1 Run solar radiation tool
1.2 After simulation check job status bar

2.1 Open your scenario to see in 3D
2.2 Empty blank screen

**Screenshots**
Job status after simulation
![1](https://user-images.githubusercontent.com/29708612/85787877-bb7dfd00-b734-11ea-85f5-26eaa5a52f10.jpg)

![2](https://user-images.githubusercontent.com/29708612/85787923-d18bbd80-b734-11ea-9b91-a4daf0667171.jpg)

No job is being done by CEA
![6](https://user-images.githubusercontent.com/29708612/85788026-faac4e00-b734-11ea-9f8c-a5054c72070f.jpg)

I have radiation plots
![3](https://user-images.githubusercontent.com/29708612/85788559-dc931d80-b735-11ea-99cf-1585a6c36838.jpg)
 
I want to open my scenario
![4](https://user-images.githubusercontent.com/29708612/85788687-06e4db00-b736-11ea-927f-e7a73611d158.jpg)

Blank screen
![5](https://user-images.githubusercontent.com/29708612/85788205-44953400-b735-11ea-83e5-7ece351f6bd8.jpg)

**Hardware (please complete the following information):**
 - OS and version: Windows 8.1
 - CEA 3.4.0

**Comment by kerembeygo** [comment]
I closed the dashboard and reopened it. Now I can see my model in 3D.
![1](https://user-images.githubusercontent.com/29708612/85790024-3a286980-b738-11ea-9211-5aa0f581563c.jpg)

**Comment by daren-thomas** [comment]
@kerembeygo thank you for reporting this. Currently, we can't reproduce the error. We've decided to add a log for the GUI that might help debug this kind of error in the future.
