### ISSUE TITLE
The data export does not work for PVT potential plots

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2790]
**Describe the bug**
Hello, I was not able to export the data for the following PVT potential plots. I realise that it is more complicated since the data is more than two-dimensional. 

![Screen Shot 2020-06-25 at 21 35 12](https://user-images.githubusercontent.com/32110882/85792710-db5cf300-b72b-11ea-9971-158a5e591164.png)

**To Reproduce**
1. Go to Dashboard
2. Plot Solar Potential > PVT
3. Try to export plot data

**Expected behaviour**
The proper export

**Screenshots**
This is the pop-up window I get when trying to export the data.

![Screen Shot 2020-06-25 at 21 35 27](https://user-images.githubusercontent.com/32110882/85792818-ffb8cf80-b72b-11ea-931d-ae5c44a0b941.png)

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - Version of CEA : 3.4

**Comment by ShiZhongming** [comment]
I am closing this and we plan to address all the data export issues altogather.
