### ISSUE TITLE
Building Energy demand - Calculate the Demand- the total demand isn't calculated

### ISSUE THREAD

**Issue by XtaoBai** [architecture-building-systems/CityEnergyAnalyst#2792]
**Describe the bug**
In calculating the demand for an area with 15 buildings. IOError B1000T.csv does not exist, and the job shut down, the total demand hasn't been calculated. 

**To Reproduce**
1. Input the area, run the data management, solar radiation the schedule.
2. Click on demand, then run the script
3. See error

**Expected behaviour**
The total demand should be calculated, and I am not so clear about the meaning of B1000T.csv.

**Information**
City Energy Analyst version 3.4.0
Running `cea demand` with the following parameters:
- general:scenario = C:\Users\111\OneDrive - stu.xmu.edu.cn\Program\demo\CEA\0626\hours
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = True
  (default: False)
- demand:buildings = [u'B1000', u'B1001', u'B1002', u'B1003', u'B1004', u'B1005', u'B1006', u'B1007', u'B1008', u'B1009', u'B1010', u'B1011', u'B1012', u'B1013', u'B1014']
  (default: [])
- demand:loads-output = []
  (default: [])
- demand:massflows-output = []
  (default: [])
- demand:temperatures-output = []
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:use-dynamic-infiltration-calculation = True
  (default: False)
- demand:predefined-hourly-setpoints = False
  (default: False)
Running demand calculation for scenario C:\Users\111\OneDrive - stu.xmu.edu.cn\Program\demo\CEA\0626\hours
Running demand calculation with dynamic infiltration=True
Running demand calculation with multiprocessing=True
Running demand in debug mode: Instant visualization of tsd activated.
Running demand calculation with write detailed output
Running demand calculation for the following buildings=[u'B1000', u'B1001', u'B1002', u'B1003', u'B1004', u'B1005', u'B1006', u'B1007', u'B1008', u'B1009', u'B1010', u'B1011', u'B1012', u'B1013', u'B1014']
read input files
done
Using 7 CPU's
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1000 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1001 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1002 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1003 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1004 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1005 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1006 to .xls file.
Building No. 1 completed out of 15: B1000
Building No. 2 completed out of 15: B1001
Building No. 3 completed out of 15: B1002
Building No. 4 completed out of 15: B1003
Building No. 5 completed out of 15: B1004
Building No. 6 completed out of 15: B1005
Building No. 7 completed out of 15: B1006
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1007 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1009 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1010 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1008 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1012 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1011 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1013 to .xls file.
Building No. 8 completed out of 15: B1007
Building No. 9 completed out of 15: B1009
Building No. 10 completed out of 15: B1010
Building No. 11 completed out of 15: B1008
Building No. 12 completed out of 15: B1011
Building No. 13 completed out of 15: B1012
Building No. 14 completed out of 15: B1013
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1014 to .xls file.
Building No. 15 completed out of 15: B1014Traceback (most recent call last):
  File "C:\Users\111\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Users\111\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\111\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 58, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\111\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "C:\Users\111\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\demand\demand_main.py", line 153, in main
    demand_calculation(locator=locator, config=config)
  File "C:\Users\111\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\demand\demand_main.py", line 128, in demand_calculation
    totals, time_series = writer_totals.write_to_csv(building_names, locator)
  File "C:\Users\111\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\demand\demand_writers.py", line 236, in write_to_csv
    df = pd.read_csv(temporary_file)
  File "C:\Users\111\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\111\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\111\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\111\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\111\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File c:\users\111\appdata\local\temp\B1000T.csv does not exist

**Hardware (please complete the following information):**
 - Win10 pro
 -  CEA v 3.4.0

**Comment by XtaoBai** [comment]
I find close the disable the debugging-specific behaviors, it works. What does this mean?

**Comment by daren-thomas** [comment]
@XtaoBai I'm guessing here - it seems the behavior of the demand script with `--debug on` is to write some additional files. This was probably being used during the development of that script and has not been tested properly since. I'm sorry you ran into this bug. Let's see if we can fix it up.

@gabriel-happle would you mind checking this quickly?
