### ISSUE TITLE
Significant difference between simplified and detailed simulation results for thermal networks

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2793]
**Describe the bug**
Hello CEA developers, I have been testing different network layouts for my case study in Lisbon. First, I wanted to limit myself to the simplified models because of the important amount of connected buildings with the network, but the results seemed to forecast an unrealistically small pumping demand in my opinion. Therefore, I tried running the detailed model, but instead I obtained extremely high pumping energy consumption. What could be the explanation?

The DHC systems would supply a dense urban area with tall buildings. The heat and cold demand is therefore quite concentrated. Here is the layout:

![image](https://user-images.githubusercontent.com/32110882/85947329-ed17e380-b941-11ea-9b78-10ad05c76ac3.png)

Here are the results from the simplified model with the DC network, as we can see the pumping demand is so small that it is barely visible on the histogram:

![Screen Shot 2020-06-28 at 13 21 29](https://user-images.githubusercontent.com/32110882/85947410-68799500-b942-11ea-84ea-b8eeafedc201.png)

Here are the results from the detailed model with the DC network. In that case, the pumping energy demand represent 99,9% of the total energy consumption:

![Screen Shot 2020-06-28 at 13 21 58](https://user-images.githubusercontent.com/32110882/85947414-78917480-b942-11ea-910a-36602d13f702.png)

For the DH network, I was only able to simulate it using the detailed model (see #2781). The results are a bit better, but the pumping energy demand still seems very high:

![Screen Shot 2020-06-28 at 13 23 21](https://user-images.githubusercontent.com/32110882/85947482-e178ec80-b942-11ea-89e9-f05eaf2f65a0.png)

Do you have any idea what would be the cause?

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - Version of CEA: 3.4

**Comment by AlexJew** [comment]
I have wondered, would it be possible:
1. The cause is the plant supply temperature? I have not changed its default value of 80°C, leaving the temperature control to VT.
2. The pumping cost includes the heat pump at the substation to adapt the supply temperature and thus, in case of DC, lower it? 

I was aiming at knowing the pumping cost and thermal losses for an optimised layout and operation. Is this possible with the **Thermal Network Simulation (Part II)** tool?

Here are the parameters used for the simulation:

1. Detailed DC simulation: 
```
- general:scenario = C:\Users\jewell\Desktop\CEA\VSA\Comfort_for_all
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 0
  (default: 1)
- thermal-network:network-type = DC
  (default: DH)
- thermal-network:network-model = detailed
  (default: simplified)
- thermal-network:min-head-substation = 20.0
  (default: 20.0)
- thermal-network:hw-friction-coefficient = 100
  (default: 100)
- thermal-network:peak-load-velocity = 2.0
  (default: 2.0)
- thermal-network:equivalent-length-factor = 0.2
  (default: 0.2)
- thermal-network:peak-load-percentage = 100.0
  (default: 100.0)
- thermal-network:network-names = []
  (default: [])
- thermal-network:set-diameter = True
  (default: True)
- thermal-network:load-max-edge-flowrate-from-previous-run = False
  (default: False)
- thermal-network:start-t = 0
  (default: 0)
- thermal-network:stop-t = 8760
  (default: 8760)
- thermal-network:use-representative-week-per-month = True
  (default: False)
- thermal-network:minimum-mass-flow-iteration-limit = 30
  (default: 30)
- thermal-network:minimum-edge-mass-flow = 0.1
  (default: 0.1)
- thermal-network:diameter-iteration-limit = 10
  (default: 10)
- thermal-network:substation-cooling-systems = [u'ahu', u'aru', u'scu']
  (default: [u'ahu', u'aru', u'scu'])
- thermal-network:substation-heating-systems = [u'ahu', u'aru', u'shu', u'ww']
  (default: [u'ahu', u'aru', u'shu', u'ww'])
- thermal-network:temperature-control = VT
  (default: VT)
- thermal-network:plant-supply-temperature = 80.0
  (default: 80.0)
- thermal-network-optimization:use-representative-week-per-month = True
  (default: False)
```

2. Detailed DH simulation:
```
Running `cea thermal-network` with the following parameters:
- general:scenario = C:\Users\jewell\Desktop\CEA\VSA\Comfort_for_all
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 0
  (default: 1)
- thermal-network:network-type = DH
  (default: DH)
- thermal-network:network-model = detailed
  (default: simplified)
- thermal-network:min-head-substation = 20.0
  (default: 20.0)
- thermal-network:hw-friction-coefficient = 100
  (default: 100)
- thermal-network:peak-load-velocity = 2.0
  (default: 2.0)
- thermal-network:equivalent-length-factor = 0.2
  (default: 0.2)
- thermal-network:peak-load-percentage = 100.0
  (default: 100.0)
- thermal-network:network-names = []
  (default: [])
- thermal-network:set-diameter = True
  (default: True)
- thermal-network:load-max-edge-flowrate-from-previous-run = False
  (default: False)
- thermal-network:start-t = 0
  (default: 0)
- thermal-network:stop-t = 8760
  (default: 8760)
- thermal-network:use-representative-week-per-month = True
  (default: False)
- thermal-network:minimum-mass-flow-iteration-limit = 30
  (default: 30)
- thermal-network:minimum-edge-mass-flow = 0.1
  (default: 0.1)
- thermal-network:diameter-iteration-limit = 10
  (default: 10)
- thermal-network:substation-cooling-systems = [u'ahu', u'aru', u'scu']
  (default: [u'ahu', u'aru', u'scu'])
- thermal-network:substation-heating-systems = [u'ahu', u'aru', u'shu', u'ww']
  (default: [u'ahu', u'aru', u'shu', u'ww'])
- thermal-network:temperature-control = VT
  (default: VT)
- thermal-network:plant-supply-temperature = 80.0
  (default: 80.0)
- thermal-network-optimization:use-representative-week-per-month = True
  (default: False)
```

If you have any suggestion about possible changes to the parameters, please tell me. Thank you :)

**Comment by daren-thomas** [comment]
@shanshanhsieh would you mind checking this please?

**Comment by AlexJew** [comment]
Does it matter whether in _supply_systems.dbf_, the supply source is not district heating? Are there any other inputs for the thermal network simulation than the energy demand of the buildings?

**Comment by AlexJew** [comment]
Hello, 

I have been working on a smaller scale network for faster computation. Here is the DC network for the 30 villas of the neighbourhood: 

![Screen Shot 2020-06-29 at 20 28 23](https://user-images.githubusercontent.com/32110882/86047730-43227f00-ba47-11ea-9c0c-a52160398164.png)

The cold consumption occurs during summer (cooling season from 15/05 to 15/09):

![Screen Shot 2020-06-29 at 20 29 06](https://user-images.githubusercontent.com/32110882/86047818-6816f200-ba47-11ea-9904-0a767822f78a.png)

The results on a year scale seem plausible:

![Screen Shot 2020-06-29 at 20 29 23](https://user-images.githubusercontent.com/32110882/86047839-7402b400-ba47-11ea-8ee4-bf500b7d94df.png)

However, there is their weird behaviour when looking at the load curve. First, the cooling happens in a repetitive patter at different moments within and out of the cooling season. Secondly, the pumping consumption increases steadily along the year :

![Screen Shot 2020-06-29 at 20 29 15](https://user-images.githubusercontent.com/32110882/86047998-b2986e80-ba47-11ea-9471-9941ffc96340.png)

I do not know if this may serve to dig the problem further

**Comment by AlexJew** [comment]
Hello @shanshanhsieh ,

I have been exploring more the scenarios trying to understand what was the factor that could cause such results, and I found out that the _min-mass-flow_ factor had a tremendous effect on the energy consumption. As it decreases:
- it reduces slightly the network thermal loss
- it reduces the network piping size
- it reduces dramatically the pumping power

By default, the parameter's value is 0.1 kg/s and is used to compute the pipe sizing. What is the explanation behind such value? How can we know what will the parameter's value be? It probably changes depending on the network type (DH or DC), on the linear heat density, on the total size of the network, etc. 

Here are the results obtained with 3 different values for _min-mass-flow_. It was done on this small network of 30 villas, testing different DH simulations (DH default simulations gave stranger result than DC).


![Screen Shot 2020-07-01 at 10 34 02](https://user-images.githubusercontent.com/32110882/86228562-6d2e8b00-bb86-11ea-8d44-684e4598bd9c.png)

a. _min-mass-flow_ = 0.1 kg/s (default value)

![Screen Shot 2020-07-01 at 10 32 11](https://user-images.githubusercontent.com/32110882/86228587-761f5c80-bb86-11ea-964c-3d2ebeda4ff5.png)
![Screen Shot 2020-07-01 at 10 32 21](https://user-images.githubusercontent.com/32110882/86228592-77e92000-bb86-11ea-81e5-ca7b07cb8407.png)

b. _min-mass-flow_ = 0.05 kg/s

![Screen Shot 2020-07-01 at 10 35 43](https://user-images.githubusercontent.com/32110882/86228752-aa931880-bb86-11ea-8d4f-eee003503ed0.png)
![Screen Shot 2020-07-01 at 10 35 50](https://user-images.githubusercontent.com/32110882/86228756-ac5cdc00-bb86-11ea-9160-bc451e8bdf72.png)

c. _min-mass-flow_ = 0.02 kg/s

![Screen Shot 2020-07-01 at 10 36 42](https://user-images.githubusercontent.com/32110882/86228837-cc8c9b00-bb86-11ea-9408-05dfa1858b75.png)
![Screen Shot 2020-07-01 at 10 36 50](https://user-images.githubusercontent.com/32110882/86228844-ce565e80-bb86-11ea-8b1e-e41cc0e5d2de.png)

If you could please provide an answer to how that factor is used and how it can be sized for different networks, I would be very grateful 👍

**Comment by shanshanhsieh** [comment]
Hi @AlexJew,

Indeed, in the detailed version, there are more input parameters (assumptions) that influence the results. This also means that the users can have more control over the network operation.
I will set up another issue to unify the default inputs of both simplified and detailed calculations, also, better documentation of the tool ; )

As you said, the `min-mass-flow` changes the flow rate and pipe sizes significantly in some cases and thus resulting in very different network losses. 
The reasons for setting the minimum mass flow in pipes are:
1. Reflect realistic pump operation in real systems (e.g. to avoid air in pumps). 
2. Avoid very high heat losses on those edges and unrealistic supply temperatures. This happens during times when there is are low heating demands from buildings that are far away from the plant.

Unfortunately, this value can be very case-specific, so i can't provide any recommendation to you.
The default value was set by a case of DC in Singapore. The flow rates in DC are normally bigger than in DH (smaller delta T), and that's probably why the constraint has more influence on DH.

In my opinion, you **do not** need this constraint unless:
1. There is a significant heat loss in some parts of your pipes. 
2. The temperature control is set to `VT`

Hope this helps.
Closing this issue for now, we can re-open it if you have more questions.
