### ISSUE TITLE
Ship Reynolds Daysim binaries instead of the official ones

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2794]
@reyery has a new build of the Daysim binaries for x64 and this build avoids a Memory issue with large scenarios.

**Comment by reyery** [comment]
Just found out that there are discrepancies in the outputs for **radiation** when using the different Daysim binaries.
It seems that the newly complied binaries actually runs **faster**, but the outputs are always **different** 
(based on SHA-1 hash of the output folder)

```
Complied Daysim binaries from Daysim repo master
58231D6057F1FEF254C1DDD1DDB479C249B9CD78 69.78s
4953908B20B24FF2587404DB82DDCF31BE7C85C8 69.11s
B8BA47F88AAFF7EB6D68ACE0BB8920C20052E598 69.29s

Daysim binaries from installation
6BFA6479D927DA7B7ECCBAABDC9DC506D0FE5AA5 117.89s
6BFA6479D927DA7B7ECCBAABDC9DC506D0FE5AA5 118.69s
6BFA6479D927DA7B7ECCBAABDC9DC506D0FE5AA5 117.99s
```

Just floating point differences I think, I uploaded some examples for the same one building.

[B1000_radiation.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4859290/B1000_radiation.zip)

```
Example A
2009-01-01 08:00:00,5.82,1508.63,0.38,197.66,1.79,1093.92,1.86,1093.94,0.35,197.53,0.28,149.11,1.36,825.24,1.41,825.25,0.26,149.01
2009-01-01 09:00:00,101.58,1508.63,22.71,197.66,24.18,1093.92,90.69,1093.94,4.55,197.53,17.05,149.11,18.88,825.24,75.35,825.25,3.52,149.01
2009-01-01 10:00:00,175.62,1508.63,26.59,197.66,41.19,1093.92,116.61,1093.94,8.4,197.53,19.87,149.11,31.73,825.24,67.03,825.25,6.49,149.01
2009-01-01 11:00:00,192.76,1508.63,27.58,197.66,48.97,1093.92,184.01,1093.94,10.88,197.53,20.55,149.11,37.22,825.24,91.94,825.25,8.38,149.01
2009-01-01 12:00:00,252.0,1508.63,19.48,197.66,51.22,1093.92,219.4,1093.94,12.59,197.53,14.45,149.11,39.43,825.24,170.42,825.25,9.77,149.01
2009-01-01 13:00:00,215.63,1508.63,13.3,197.66,46.02,1093.92,162.05,1093.94,13.41,197.53,9.93,149.11,35.82,825.24,145.98,825.25,10.52,149.01
2009-01-01 14:00:00,158.19,1508.63,9.31,197.66,36.95,1093.92,110.23,1093.94,12.13,197.53,6.98,149.11,28.81,825.24,101.8,825.25,9.72,149.01
2009-01-01 15:00:00,82.04,1508.63,4.43,197.66,18.43,1093.92,83.42,1093.94,8.03,197.53,3.36,149.11,14.44,825.24,64.82,825.25,6.82,149.01
2009-01-01 16:00:00,2.91,1508.63,0.19,197.66,0.89,1093.92,0.92,1093.94,0.17,197.53,0.14,149.11,0.68,825.24,0.7,825.25,0.13,149.01

Example B
2009-01-01 08:00:00,5.82,1508.63,0.38,197.66,1.79,1093.92,1.86,1093.94,0.35,197.53,0.28,149.11,1.37,825.24,1.42,825.25,0.26,149.01
2009-01-01 09:00:00,101.03,1508.63,22.57,197.66,24.46,1093.92,91.53,1093.94,4.51,197.53,17.05,149.11,19.07,825.24,76.08,825.25,3.46,149.01
2009-01-01 10:00:00,176.57,1508.63,26.38,197.66,41.45,1093.92,117.99,1093.94,8.34,197.53,19.86,149.11,31.85,825.24,69.25,825.25,6.4,149.01
2009-01-01 11:00:00,186.04,1508.63,27.27,197.66,48.95,1093.92,184.94,1093.94,10.77,197.53,20.52,149.11,37.11,825.24,94.45,825.25,8.23,149.01
2009-01-01 12:00:00,209.17,1508.63,19.43,197.66,51.27,1093.92,220.22,1093.94,12.44,197.53,14.73,149.11,39.26,825.24,172.17,825.25,9.56,149.01
2009-01-01 13:00:00,214.56,1508.63,13.34,197.66,46.0,1093.92,162.9,1093.94,13.3,197.53,10.19,149.11,35.6,825.24,146.84,825.25,10.35,149.01
2009-01-01 14:00:00,157.35,1508.63,9.36,197.66,36.84,1093.92,110.79,1093.94,12.14,197.53,7.16,149.11,28.61,825.24,102.25,825.25,9.69,149.01
2009-01-01 15:00:00,82.66,1508.63,4.45,197.66,18.46,1093.92,83.45,1093.94,7.99,197.53,3.43,149.11,14.41,825.24,64.86,825.25,6.76,149.01
2009-01-01 16:00:00,2.91,1508.63,0.19,197.66,0.89,1093.92,0.92,1093.94,0.17,197.53,0.14,149.11,0.68,825.24,0.7,825.25,0.13,149.01
```

It's faster but it will not be able to produce consistent reproducible results.

**Comment by reyery** [comment]
Here are the binaries that I complied [Daysim x64.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4859354/Daysim.x64.zip). Not sure if I did it correctly

**Comment by shanshanhsieh** [comment]
@reyery will compare the results between the two versions and we can discuss once again.
maybe @jimenofonseca would know why this happens?

**Comment by reyery** [comment]
Anyway, I just want to provide an update regarding the differences in the results of the newly complied Daysim binaries.
I have ran the radiation simulation on the reference case with the new binaries 10 times and used the **mean squared error**(MSE)  metric to calculate the error compared to when using the original binaries.

I took the **average** of the MSE between the 10 runs and also calculated the **standard deviation** of the MSEs (not sure what other metric should be used of this comparison). The values are compared based on the building name and the solar radiation of each facade of the building.

The MSEs are considerably low for most of the facades except for some building roof tops. 

_(just realized a graph would be better but I will just put the raw data here first)_
```
roofs_top_kW
Name	avg	std
B1000	2.194	0.336
B1001	0.647	0.161
B1002	0.697	0.121
B1003	0.831	0.179
B1004	0.639	0.092
B1005	0.622	0.152
B1006	2.931	0.468
B1007	0.68	0.088
B1008	1.204	0.245
B1009	7.583	1.525
B1010	28.669	1.934
B1011	3.03	0.302
B1012	149.721	10.816
B1013	8.013	0.366
B1014	181.835	5.656
walls_east_kW
Name	avg	std
B1000	0.083	0.02
B1001	0.341	0.052
B1002	0.216	0.113
B1003	0.314	0.132
B1004	1.524	0.59
B1005	0.421	0.275
B1006	0.09	0.052
B1007	0.349	0.171
B1008	0.231	0.082
B1009	1.438	0.52
B1010	0.144	0.095
B1011	1.343	0.351
B1012	1.077	1.496
B1013	0.15	0.057
B1014	21.351	8.774
walls_north_kW
Name	avg	std
B1000	0.357	0.174
B1001	0.034	0.026
B1002	0.06	0.037
B1003	0.028	0.011
B1004	0.324	0.072
B1005	0.068	0.034
B1006	0.239	0.148
B1007	0.35	0.195
B1008	2.688	0.827
B1009	0.223	0.171
B1010	0.136	0.087
B1011	1.069	0.478
B1012	0.322	0.149
B1013	2.131	0.642
B1014	2.192	0.519
walls_south_kW
Name	avg	std
B1000	1.287	0.328
B1001	0.04	0.017
B1002	0.035	0.016
B1003	0.057	0.017
B1004	0.038	0.01
B1005	0.398	0.135
B1006	0.289	0.075
B1007	0.14	0.037
B1008	0.399	0.159
B1009	0.058	0.03
B1010	0.439	0.24
B1011	0.216	0.089
B1012	2.053	0.5
B1013	0.24	0.073
B1014	0.611	0.142
walls_west_kW
Name	avg	std
B1000	0.05	0.011
B1001	0.039	0.014
B1002	0.049	0.034
B1003	0.1	0.039
B1004	0.246	0.1
B1005	0.32	0.051
B1006	0.082	0.032
B1007	0.03	0.009
B1008	0.05	0.015
B1009	0.581	0.473
B1010	0.164	0.096
B1011	0.09	0.05
B1012	1.066	0.356
B1013	0.122	0.019
B1014	6.485	1.292
windows_east_kW
Name	avg	std
B1000	0.044	0.014
B1001	1.059	0.681
B1002	0.15	0.055
B1003	0.335	0.125
B1004	0.808	0.319
B1005	0.52	0.528
B1006	0.086	0.035
B1007	0.142	0.04
B1008	0.2	0.054
B1009	0.667	0.143
B1010	0.016	0.009
B1011	0.104	0.028
B1012	0.217	0.163
B1013	0.034	0.018
B1014	0.215	0.106
windows_north_kW
Name	avg	std
B1000	0.331	0.127
B1001	0.03	0.011
B1002	0.092	0.048
B1003	0.037	0.033
B1004	0.229	0.052
B1005	0.054	0.027
B1006	0.157	0.101
B1007	0.082	0.055
B1008	1.154	0.461
B1009	0.025	0.021
B1010	0.014	0.012
B1011	0.042	0.018
B1012	0.057	0.041
B1013	0.239	0.048
B1014	0.042	0.01
windows_south_kW
Name	avg	std
B1000	0.737	0.241
B1001	0.041	0.025
B1002	0.083	0.08
B1003	0.308	0.155
B1004	0.066	0.058
B1005	0.413	0.16
B1006	1.166	0.843
B1007	0.102	0.045
B1008	0.62	0.29
B1009	0.008	0.006
B1010	0.058	0.05
B1011	0.01	0.005
B1012	0.0	0.0
B1013	0.037	0.018
B1014	0.015	0.003
windows_west_kW
Name	avg	std
B1000	0.04	0.009
B1001	0.113	0.176
B1002	0.812	0.523
B1003	0.996	0.611
B1004	0.256	0.18
B1005	0.106	0.03
B1006	0.172	0.052
B1007	0.091	0.086
B1008	0.23	0.211
B1009	0.068	0.026
B1010	0.013	0.008
B1011	0.01	0.005
B1012	0.544	0.306
B1013	0.075	0.045
B1014	1.606	0.372
```

**Comment by daren-thomas** [comment]
@reyery would you mind adding the following anaylisis:

- boxplots for each building/direction
- percentages of error compared to total per building

**Comment by reyery** [comment]
First I compared the sensor number/size to make sure that both binaries are working with the same inputs, which fortunately is the case.

Below are the boxplots for 
- Root Mean Squared Error (RMSE)
- Mean Absolute Error (MAE)
- Total Percentage Error
- Total Percentage Error per Building

In general, I think that radiation results for rooftops in all tests are very consistent and close to the benchmark. 
At the end of the day, the error of the total radiation of all facades for each test are within 2% error of the benchmark.

I'm not sure how to interpret RMSE so I also plotted the MAE.

- Root Mean Squared Error
![rmse](https://user-images.githubusercontent.com/34395415/87534109-2da88880-c6c8-11ea-995f-cabe65455e07.png)
- Mean Absolute Error
![mae](https://user-images.githubusercontent.com/34395415/87534088-26817a80-c6c8-11ea-8fb1-9515b44f8fef.png)
- Total Percentage Error
![tpe](https://user-images.githubusercontent.com/34395415/87534245-56308280-c6c8-11ea-8dd0-2a28a9fd614c.png)
- Total Percentage Error per Building
![tpe_building](https://user-images.githubusercontent.com/34395415/87534846-2b92f980-c6c9-11ea-8147-b29465892697.png)

**Comment by daren-thomas** [comment]
We decide to add these binaries as an option to the radiation script with a clear warning for the user that the results are not deterministic, but faster and can handle larger case studies.

**Comment by daren-thomas** [comment]
A Pull Request would include a separate folder for these binaries and the radiation script should set the appropriate radiation:daysim-bin-folder parameter before running. Update required to the installer.

**Comment by daren-thomas** [comment]
@jimenofonseca suggests having the non-deterministic version as the default with option for slower, deterministic version of the binaries.

@reyery could also look into creating another version based on only the memory issue commit and see if that's faster but still deterministic.
