### ISSUE TITLE
Columns with empty results 

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2797]
**Describe the bug**
After comparing the results between the current master and v3.5.0a2, i discovered several columns that contain empty results.

files containing empty result columns:
- `Total_LCA_operation.csv` : GHG_sys_tonCO2, GHG_sys_building_scale_tonCO2, PV_tonCO2, SOLAR_ww_tonCO2
- `Total_demand.csv`: PV_MWhyr, PV0_kW

**To Reproduce**
Run `cea workflow --slow`

**Expected behaviour**
No empty columns

**Screenshots**

**Hardware (please complete the following information):**
 - Windows 10
 - v3.4.0 & v3.5.0a2

**Comment by daren-thomas** [comment]
fixed by #2856
