### ISSUE TITLE
Shapefile with set back storeys

### ISSUE THREAD

**Issue by eap23** [architecture-building-systems/CityEnergyAnalyst#2800]
**Describe the bug**
I have a buildling design with set back storeys (see screenshots). GIS applications as _QGIS_ can interpret elevation of a given polygon as seen in image `QGIS_Issue_Elevation_Stacked.PNG`, but _City Energy Analyst_ does not provide this funtionality (see `CEA_Issue_Elevation_Stacked.PNG`).
The only way I can achieve this in CEA is to define nested polygons where each one has set a total height from ground floor (see `QGIS_Issue_Elevation_Nested.PNG` and `CEA_Issue_Elevation_Nested.PNG`).
How am I supposed to interpret the calcuated demand results for a model similar to the nested approach above?
The zones are stacked within each other and thus result in a much higher volume than it actually is.

**To Reproduce**
1. Create a number of nested polygons for the building outline
2. Define the building height for each zone in the `zone.dbf` file
3. --- here there is no option to define a zone's elevation ---
4. Check the result in _CEA_'s _Input Editor_

**Expected behaviour**
I have the ability to tell _CEA_ at which elevation the zone should be placed in 3d space.

**Screenshots**
![QGIS_Issue_Elevation_Nested](https://user-images.githubusercontent.com/26528531/86609249-00fbbf00-bfac-11ea-868c-26caabcf77fe.PNG)
![CEA_Issue_Elevation_Nested](https://user-images.githubusercontent.com/26528531/86609269-06f1a000-bfac-11ea-9584-1b8121556f62.PNG)
![QGIS_Issue_Elevation_Stacked](https://user-images.githubusercontent.com/26528531/86609280-0bb65400-bfac-11ea-9117-65b1766c6090.PNG)
![CEA_Issue_Elevation_Stacked](https://user-images.githubusercontent.com/26528531/86609291-107b0800-bfac-11ea-930c-b1837fe8f3bb.PNG)

**Hardware (please complete the following information):**
- Windows 10 Enterprise 64-Bit
- Version of CEA is from Setup_CityEnergyAnalyst_3.4.0.exe
- Intel i7 9750H 2.60GHz
- 32 GB RAM

**Comment by shanshanhsieh** [comment]
Hi @eap23, 
The only way to process this geometry is to cut the building vertically, so you will have to make three buildings:
1. 9-floors high, with the smallest rectangular footprint
2. 6-floors high, with a L-shape footprint
3. 3-floors high, with a L-shape footprint

The proposed solution is an approximation.
If you want to reflect changes of complicated geometry, you might have to simulate the building with building simulation tools, and then use that use the output in CEA.

Let us know how it goes.

**Comment by eap23** [comment]
Hi @shanshanhsieh,

thanks for your advise! Will give it a try.
