### ISSUE TITLE
open a project folder or create new projects not working in dashboard after updating CEA

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2801]
**Describe the bug**
Hi, I just updated CEA to latest version (from 3.1.0 to 3.4.0) and I have not been able to open a project folder or create new projects.

**To Reproduce**
1. Go to dashboard
2. Click on new project or open project
3. Click on Create or Open
4. See error (nothing happens)

**Screenshots**
Nothing happens when I click on "Create" (or "Open" in open project)
![image](https://user-images.githubusercontent.com/50981039/86868543-7b8d2180-c107-11ea-9988-e3a7cca00388.png)

**Comment by reyery** [comment]
Hey @lguilhermers, could you try replacing your current GUI files with the latest one here https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.4.0/win-unpacked.7z

There were some changes regarding how the GUI communicates with CEA

**Comment by lguilhermers** [comment]
Ok, it worked! Thanks for the quick reply :)
