### ISSUE TITLE
unexpected value for floors of surroundings when running surrounding-helper

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#2803]
When running surroundings-helper for one specific district, the following error appears: 
![Brighton_Ave_Floor](https://user-images.githubusercontent.com/26175926/87577638-c9a4b500-c705-11ea-85da-80464c1f23c0.png)

It seems that it is caused by an unexpected value when cleaning the attributes of the surroundings. 
![weird_value in floors](https://user-images.githubusercontent.com/26175926/87577735-efca5500-c705-11ea-9fa8-0cffeef992c3.png)

Is this a value extracted from OSM?! It would be great to have a feedback on where this value is coming from. Maybe the easiest would be to catch those unexpected values and set them to 0.

The scenario in question is stored here: https://polybox.ethz.ch/index.php/s/MrkEEpk9jRLEoOw

**Comment by reyery** [comment]
That value was directly extracted from OSM data and unfortunately it is not the cleanest/most accurate dateset. But if I remember correctly, we do try to parse/clean such values with the `zone-helper`, maybe we missed out the `surroundings-helper`. I will take a look at it.
