### ISSUE TITLE
Create Daysim project folder of radiation script using `tempfile.TemporaryDirectory`

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2805]
Currently the **radiation** script creates the Daysim project folder in the **temporary directory** in the form of `temp_{chunk_number}`. This prevents multiple different instances of the **radiation** script to be run together since they might attempt to access the same folder which could result in I/O issues (such as trying to write to the same file while another trying to read from it).

To solve this, we could use `tempfile.TemporaryDirectory` from **python3** to create a temporary folder that has a **unique name** so that each **radiation** script instance would have its own scratch space to create the Daysim project files. As an added bonus,  when using in a python context, it would also be able to cleanup the temporary folder after it is done.

**Comment by shanshanhsieh** [comment]
@reyery is this still the case now?

**Comment by reyery** [comment]
Nope. This has not been implemented yet. But should be really easy to do.

**Comment by reyery** [comment]
Seems to already been included
