### ISSUE TITLE
not able to change the typology-use in the edit selection tab

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2808]
**Describe the bug**
When I try to change the Use writing a new existent typology in the database I get the following error message:
"1ST_USE is not a undefined", the same happens for the other uses. 
Does this have something to do with the class types given for those names? For the ratio, it works normal (if I put a number it accepts, otherwise it says it is not a float)

**Screenshots**
![image](https://user-images.githubusercontent.com/50981039/88521102-10a87980-d027-11ea-8bb8-c005fe61e27b.png)

**Comment by reyery** [comment]
I think it's giving an error because the input is supposed to be a selection box instead of text input box. Will take a look at this bug.

**Comment by lguilhermers** [comment]
Hi Rey, just as an update I found this issues with other toolboxes, for example the STANDARD. I think for all, they were supposed to be selection boxes, so it seems that is indeed the bug. Please let me know if I can assist somehow.

**Comment by shanshanhsieh** [comment]
@reyery , what is the status of this issue?

**Comment by daren-thomas** [comment]
@reyrey what is the status of this issue?

**Comment by lguilhermers** [comment]
@reyery was able to fix this issue in the Hackathon (#2863). It had to do with a flawed logic on the GUI, checking if the type was equal to 'choice', when it actually should check if they are not 'undefined'.
Changing this created the drop down choices in the edit selection, fixing the issue.
