### ISSUE TITLE
ERROR 4: This is a BigTIFF file.  BigTIFF is not supported by this version of GDAL and libtiff.

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2812]
I am running the solar radiation script using a topography downloaded from the [GeoVITe database from ETH](https://geovite.ethz.ch/DigitalElevationModels.html). This leads to the error message in the title. Upgrading to GDAL version 2.2.4 should [apparently](https://gis.stackexchange.com/questions/268124/reading-a-bigtiff-file-gdal) solve the problem, though I'm having trouble upgrading GDAL on my computer due to a separate issue I'm trying to wrap my head around (and certainly won't work on until Monday at the earliest).

But maybe we can make GDAL > 2.2.4 a requirement?

1. Download [this sample case study](https://we.tl/t-kpzQmkohVx).
2. Run the radiation tool
3. See error

 - OS and version: Windows 10
 - Version of CEA you are using: 3.7.0

**Comment by daren-thomas** [comment]
@martin-mosteiro the py3 port uses GDAL 2.4.4 - so... help us make it into master!

**Comment by martin-mosteiro** [comment]
Since this will be solved with the py3 port, I guess this will get resolved... soon. Closing the issue.
