### ISSUE TITLE
Error on startup CEA 3.7.0 in Windows 10

### ISSUE THREAD

**Issue by rfnif** [architecture-building-systems/CityEnergyAnalyst#2820]
Hi! I have CEA version 3.7.0 in Windows 10 and when I start CEA dashboard, it appears these errors. After these errors, the program closes. 

![image1](https://user-images.githubusercontent.com/69899773/90630163-70ee9d80-e218-11ea-9db7-ff520a7c4ed1.jpeg)

When I click "Exit CEA", it appears this error:

![image2](https://user-images.githubusercontent.com/69899773/90630167-72b86100-e218-11ea-81d0-4cabcbd319a7.jpeg)

I already reinstall the program but the errors remain. 
I don't know what I'm doing wrong.

Thank you in advance.

**Comment by daren-thomas** [comment]
@rfnif, can you try to uninstall the CEA (check to make sure the whole folder is deleted) and reinstall again? I think just re-installing might be overwriting a previous installation and would love to make sure a clean installation still produces this bug...

**Comment by shjiang** [comment]
I have the same problem.

**Comment by shjiang** [comment]
> @rfnif, can you try to uninstall the CEA (check to make sure the whole folder is deleted) and reinstall again? I think just re-installing might be overwriting a previous installation and would love to make sure a clean installation still produces this bug...

The error happens again after a clean reinstallation.

**Comment by rfnif** [comment]
@daren-thomas , thanks for your reply, it's solved! I thought that I had already done that, but it didn't solve the problem... 
This time, after I uninstall CEA, I reboot my computer and maybe it was crucial. 
Thanks again for your reply!

**Comment by shjiang** [comment]
> @daren-thomas , thanks for your reply, it's solved! I thought that I had already done that, but it didn't solve the problem...
> This time, after I uninstall CEA, I reboot my computer and maybe it was crucial.
> Thanks again for your reply!

I followed your step, and the error happened again. 
The error was found in the installation process. 

<img width="373" alt="Snipaste_2020-08-25_08-22-47" src="https://user-images.githubusercontent.com/2359242/91109016-45523400-e6ac-11ea-8e04-85e74adbf23e.png">
