### ISSUE TITLE
UNKNOW ERROR with "Input Editor"

### ISSUE THREAD

**Issue by shjiang** [architecture-building-systems/CityEnergyAnalyst#2821]
When openingn the example project in "CityEnergyAnalyst-v3.8.0a0\architecture-building-systems-CityEnergyAnalyst-2956835\cea\examples", or creating a New Scenario,  the "Input Editor" shows "Something went wrong". 

<img width="600" alt="000" src="https://user-images.githubusercontent.com/2359242/90956470-81717300-e4b9-11ea-891b-d0e35072f32e.png">

**Hardware (please complete the following information):**
 - OS and version: Windows 10 1909
 - Version of CEA you are using:3.8.0a0

**Comment by reyery** [comment]
Hi @shjiang could you try running `cea dashboard` in the CEA console and start the application after seeing the message below. It should hopefully show any error messages that would help us troubleshoot this. Thanks!

![image](https://user-images.githubusercontent.com/34395415/91371132-c2171680-e842-11ea-9f87-81b3950769b5.png)

**Comment by shjiang** [comment]
> Hi @shjiang could you try running `cea dashboard` in the CEA console and start the application after seeing the message below. It should hopefully show any error messages that would help us troubleshoot this. Thanks!

Below is the message. Thanks a lot for your reply!

<img width="1106" alt="Snipaste_2020-08-27_09-48-05" src="https://user-images.githubusercontent.com/2359242/91374305-841df080-e84a-11ea-84b4-44b1de7bbadb.png">

**Comment by reyery** [comment]
Hmm, looks like you have another instance of CEA already running. Could you try closing the application and try it again.

**Comment by shjiang** [comment]
I tried and it shows,
<img width="660" alt="Snipaste_2020-08-27_10-05-40" src="https://user-images.githubusercontent.com/2359242/91375308-dfe97900-e84c-11ea-94a8-d1398447d55e.png">

**Comment by reyery** [comment]
With that open, could you try running the input editor again? I should show the error. Thanks!

**Comment by shjiang** [comment]
I have tried to open two projects. The first one was established by myself.  The "Input editor" shows error at the very start.
<img width="929" alt="001" src="https://user-images.githubusercontent.com/2359242/91376199-1de79c80-e84f-11ea-8ce1-bdc7bad7580f.png">

The second one is the example in the cea source code folder. I unzipped it, and opened it with CEA Dashboard.  The "Input editor" worked at first. But after I clicked another label,  for example, the "Project Overview", the "Input editor" started to show error even if I closed the project and opened it again.
<img width="926" alt="002" src="https://user-images.githubusercontent.com/2359242/91376204-217b2380-e84f-11ea-923b-b1201d78c5ff.png">

**Comment by reyery** [comment]
Thanks for the screenshots! That is exactly what we need. Seems there's definitely something up with `fiona`, which seems to be also causing the problem in #2820. We will try to recreate this problem on our end and come up with a fix soon.

**Comment by daren-thomas** [comment]
@shjiang I'm sorry this is taking so long to resolve. Would you mind telling me how you installed the CEA? It seems you're running the new experimental installer (v3.8.0a0) - but what version did you install? also... did you install the regular version or the developer version (second screen in the installer, the checkbox I think)?

**Comment by shjiang** [comment]
I installed the regular version (default option) of v3.8.0a0. In fact, I have tried v3.7.0 either, but it went wrong at the first start.&nbsp;


------------------ Original ------------------

**Comment by shanshanhsieh** [comment]
@shijiang could you please uninstall everything, and try out the v3.10.0?
https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.10.0/Setup_CityEnergyAnalyst_3.10.0.exe

thank you!

**Comment by shjiang** [comment]
I tried and unfortunately I encountered the follow error at the start:

While clicked "Exit CEA", it showed:





Should I do some other tests?


Plus, could you tell me how to install the software without downloading files if I have already downloaded the files "Dependencies.7z" and "win-unpacked.7z" onto my disk?


Thanks a lot!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "architecture-building-systems/CityEnergyAnalyst"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月16日(星期三) 下午3:33
收件人:&nbsp;"architecture-building-systems/CityEnergyAnalyst"<CityEnergyAnalyst@noreply.github.com&gt;;
抄送:&nbsp;"蒋爽"<shjiang@foxmail.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [architecture-building-systems/CityEnergyAnalyst] UNKNOW ERROR with "Input Editor" (#2821)





 
@shijiang could you please uninstall everything, and try out the v3.10.0?
 https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.10.0/Setup_CityEnergyAnalyst_3.10.0.exe
 
thank you!

**Comment by daren-thomas** [comment]
@shjiang - your last error looks like you still had the `v3.8.0a0` Depencencies folder installed when you installed `v3.10.0`. That can lead to problems with DLLs, as `v3.8.0a0` is an experimental release using a different python version.

I suggest manually deleting the folder `C:\Users\jiang\Documents\CityEnergyAnalyst` and reinstalling version 3.10.0. I'm sure that will solve your issue :)

As to your question - it's _possible_ but very involved and won't work with the installer. The easiest is just to install with the installer.

**Comment by shjiang** [comment]
> @shjiang - your last error looks like you still had the `v3.8.0a0` Depencencies folder installed when you installed `v3.10.0`. That can lead to problems with DLLs, as `v3.8.0a0` is an experimental release using a different python version.
> 
> I suggest manually deleting the folder `C:\Users\jiang\Documents\CityEnergyAnalyst` and reinstalling version 3.10.0. I'm sure that will solve your issue :)
> 
> As to your question - it's _possible_ but very involved and won't work with the installer. The easiest is just to install with the installer.

Thanks a lot for your work! @daren-thomas. I failed again on my computer but I made it on another computer. So, it is obvious the problem of my computer.
