### ISSUE TITLE
Deleted buildings are not removed in new simulations

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2822]
**Describe the bug**
Hi all. @emanuel030  and I have noticed a strange behavior, that we are not sure if it is intentional. If we run the simulation and after that, delete certain buildings and re-run the simulation, the old buildings stay in the results folder (with the old results). 
You can easily detect them by the date/time of simulation and delete manually, but wouldn't it be better if the simulations clear the folder before running? I know this can bring other shortcomings (like you getting an error and have no results, losing the previous ones as well), but in our user experience having buildings that are not really part of the simulation was a bit confusing. 

**To Reproduce**
1. Run a demand simulation
2. Delete some buildings
3. Re-run the demand
4. See error (deleted buildings still in the outputs folder)

**Expected behaviour**
Each simulation for outputs clears the folder before running, guaranteeing that the only thing on it will be the results provided by the latest inputs.

**Comment by shanshanhsieh** [comment]
Hi guys, 

Thanks for the suggestion, we will keep it in the pipeline.
However, i am not sure if all users would expect this behavior to happen, they might be shocked that the files have disappeared.

When deleting some buildings, it sounds like a "new scenario/case" to me, and there is a scenario layer in the CEA folder structure.
The general folder structure looks like this: `case/scenario/inputs` . Most of the time the scenario layer is called `baseline` in our reference cases. 

I am labeling it as and should have because this is not impairing the functionality, but please feel free to make adjustment in a branch and we can discuss how to incorporate it.

Let me know what you think? thanks!

**Comment by lguilhermers** [comment]
Yes, got that. I agree it is not such a big deal in the moment, as it is quite a specific situation.

For me deleting buildings was a matter of refining the geometry and getting rid of small buildings that get created from arcmaps (didn't made sense to start a new scenario since I had most of the settings defined). 
But since I had already simulated radiation and demand once, those results (from deleted buildings) were never overwritten, they just stayed in the output folder, which could lead to some confusion.

Is there any motivation to not clear the folder as soon as a command is executed, since the user intends to overwrite it anyway as soon as he clicks on it?

**Comment by daren-thomas** [comment]
@lguilhermers yes, actually. it's not a motivation per se, but rather an emergent behaviour from how the scripts "think" of output - they think in files and not folders so after deleting building "Bxyz", a simulation script wouldn't have any way to "know" anything about "Bxyz_simulation_output.csv".

I'm hoping to make it even more abstract, such that the scripts don't even know what file it's using - that's where the `InputLocator` comes in. If you look at newer versions of the cea, note you can do `locator.get_zone_geometry.read()` and get a `Dataframe` object. This makes the scripts less dependent on _how_ to read and write data and would make replacing the way the data is stored much easier.

The `InputLocator` object is also the reason why scripts don't "know" about folders. Even without the `read`/`write` interface being used in the current scripts (please use this in plugins!), the scripts still use the `locator` to find individual file paths. generally. It's not _impossible_  to do what you're proposing, just... not an obvious conclusion based on the way the scripts "think".

**Comment by daren-thomas** [comment]
we're closing this for now, marked as known issue - we might reopen it at a later stage.
