### ISSUE TITLE
editing void_deck in Database Editor generates an error

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2825]
**Describe the bug**
When trying to edit the database, only "0" is a value accepted for void_decks

**To Reproduce**
1. Go to Database Editor- Archetypes - Envelope Assmblies
2. Try to edit the field void_decks to 1 (or any other value other than 0). Happens in a new standard or editing an old one
3. See error

PS: I am currently bypassing the error by editing directly the .xls file, which so far seems to be ok

**Screenshots**
![image](https://user-images.githubusercontent.com/50981039/91527783-fc62df80-e938-11ea-8841-fe2f1aecf4ec.png)

**Comment by shanshanhsieh** [comment]
hi @lguilhermers ,

please confirm with @jimenofonseca if that is an intended behavior, or the value could be freely assigned.
if the later is true, @reyery could tell you the steps to fix it!

**Comment by lguilhermers** [comment]
@shanshanhsieh 

I have confirmed with him already, he said that integers should be valid there (normally 1, but I imagine the user should be able to set more, as long as it is lower than the number of floors). Another thing to support that is that Standard 1 and 2 have a void deck as 1 from the database.

**Comment by daren-thomas** [comment]
@reyery the `schemas.yml` file says the `max` value is `null` - that might be the problem.

**Comment by shanshanhsieh** [comment]
plan of attack
1. set the max value in `schemas.yml` to any integer
2. limit this value by the number of floors
