### ISSUE TITLE
empty output column in `Bxxx_PVT.csv` and `Bxxx_SC_ET/FP.csv`

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2826]
**Describe the bug**
The column `T_PVT_re_C` in `Bxxx_PVT.csv` contains empty output, which should be zeros or 'nan'.
The same happens in `Bxxx_SC_ET/FP.csv` .

**To Reproduce**
1. Run `photovoltaic_thermal.py`
2. Read `Bxxx_PVT.csv`

**Expected behaviour**
The empty cell should be 'nan', or equivalent.

**Hardware (please complete the following information):**
 - OS and version: Windows10
 - Version of CEA you are using v3.8.0a

**Comment by shanshanhsieh** [comment]
@daren-thomas , i just checked and realized that this only happens in the py3 version.
shall i just go to the branch and fix it?

**Comment by daren-thomas** [comment]
yes, please.

**Comment by daren-thomas** [comment]
@shanshanhsieh as discussed in the meeting, better to create a separate branch, PR, merge to master and then update the py3 PR from master. That way we can continue testing apples to apples.

**Comment by daren-thomas** [comment]
fixed in #2826
