### ISSUE TITLE
empty output column in `Total_LCA_operation.csv ` and `Total_demand.csv`

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CityEnergyAnalyst#2827]
**Describe the bug**
'Total_LCA_operation.csv' contains empty columns.
The same happens in 'Total_demand.csv'.

**To Reproduce**

    Run 'demand_main.py'
    Read 'Total_demand.csv'

**Expected behaviour**
The empty cell should be 'nan', or equivalent.

**Hardware** (please complete the following information):

    OS and version: Windows10
    Version of CEA you are using v3.8.0a

**Comment by shanshanhsieh** [comment]
@shizhongming , can you specify the columns that are empty?
also, is this an issue or did you solve it already?

**Comment by daren-thomas** [comment]
@shanshanhsieh maybe check #2826 for a solution.

While you're at it, how about a script similar to `scenariocompare.py` (check there for how to walk a directory structure) that checks all csv files for empty columns?
