### ISSUE TITLE
Docker container for CEA (py3 version) that runs as a "server"

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2834]
For the ReMap project, details follow.

**Comment by kerembeygo** [comment]
What will be the functional relationship between CEA and ReMaP project? Comparison of simulation results and real time data? Calibration?

**Comment by shanshanhsieh** [comment]
@kerembeygo, 
in ReMaP, we will use the CEA to provide demand data to other project partners to test their technology or control algorithms.
In line with this effort, we will update some CEA database to include future scenarios of districts in Switzerland.
are you familiar with ReMaP? suggestions are welcome!

**Comment by kerembeygo** [comment]
@shanshanhsieh 
For the first time I heard about ReMaP and Nexus-e last year. I asked Jimeno Fonseca whether those platforms would share a common interface and exchange data. He said CEA is a part of ReMaP project. But we didn't talk about the functional relationship between them. All I know is the information on website.

We are in contact with an Austrian Institute to be partners in oncoming H2020 Green Deal program. 
Topic is "4.1 Building and renovating in an energy and resource efficient way"
Proposals are expected to deliver large-scale, real-life demonstrations of promising technology and social innovations.

I wondered whether we can use CEA with a similar functionality in a research project.
