### ISSUE TITLE
Unclear column names and documentation in `Total_demand.csv`

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2839]
This is reported by Marius from Nexus-e.
The definitions of *energy consumption*, *end-use electricity*, and *grid electricity* are unclear to users.

Example:
The total value of end-use electricity exceed the grid electricity, which is not easy to understand. 

![image.png](https://images.zenhubusercontent.com/57b4452fe40e5714b16d75a2/9c1d4879-fdc2-4fca-9a7e-462d76704bfd)

The actual relationship:
E_sys = Ea + El + Ev + Eve + Edata + Eaux + Epro   (all the electricity demand that cannot be replaced by DHC networks)
If the building is only connected to an el. Grid, GRID = E_sys + E_cs + E_hs + E_ww + E_cre + E_cdata = 63 TWh

Eal = Ea + El not sure why this is being calculated, we might have to clean it up to avoid conclusion -> check if it is used in other scripts

**Comment by shanshanhsieh** [comment]
something like the "Modelling Steps" documentation might be helpful
https://pvpmc.sandia.gov/modeling-steps/

**Comment by nasty-bos** [comment]
With a hope to shed some light on demand calculation:  [CEA_demand_documentation.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/6011765/CEA_demand_documentation.docx)

**Comment by shanshanhsieh** [comment]
@nasty-bos , i've updated the document you made: https://nextcloud.ethz.ch/apps/files/?dir=/VILLE/CEA-ReMaP/Documentation&fileid=65887707

next step:
1. update `schema.yml`
2. run `cea glossary` to update `output_files.rst`
3. run `cea-doc html` to build the read-the-docs documentation
4. review the changes in a new version of  `read-the-docs`
