### ISSUE TITLE
Update Grasshopper interface for py3 version

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2841]

**Comment by daren-thomas** [comment]
@shizhongming would you mind testing this please? https://github.com/architecture-building-systems/cea-grasshopper/releases/tag/v1.1.0

**Comment by shizhongming** [comment]
Thanks @daren-thomas working on it!

**Comment by shizhongming** [comment]
I have just completed testing the Grasshopper interface for data management, energy demand, LCA, and solar potentials.
Before I started, I tested CEA and my case study using the command line in the CEA console. Everything worked very well.
For the Grasshopper interface some went through and some did not. The details are as follows.

dbf-excel: worked well
Data-initializer: worked well
weather-helper: worked well
achetypes-mapper: worked well
schedule-maker: the function was activated; outputs were generated; but the execution of the function never ended until I had to force end the program
radiation: worked well
demand: the output for each individual building was generated but the total file was never generated and the execution never ended until I had to force end the program
emissions: worked well
system-costs: worked well
photovoltaic: worked well

Could you take a look @daren-thomas ? Thanks!
I will continue test if other functions work well using the Grasshopper interface.

**Comment by daren-thomas** [comment]
@shizhongming: schedule-maker works for me. does the rhino console output have any hints?

**Comment by daren-thomas** [comment]
@shizhongming same for demand script. they work for me.

**Comment by daren-thomas** [comment]
@shizhongming can you please check again? does it work for you now? do you see any output in the Rhino console log?

**Comment by shizhongming** [comment]
@daren-thomas apologies for the delay and I was on some deadline....
I ran the testing again. This time includes the network-layout and optimization. Still, all is well except the schedule-maker and demand. I tried them several times and each time returned the same problem.

schedule-maker can generate all the outputs but won't end the execution. The Rhino console is as follows.
![schedule-maker](https://user-images.githubusercontent.com/16640327/100305433-09e14180-2fdc-11eb-8e96-a50c7c09611b.PNG)

Demand can generate all the outputs for individual buildings but the total_demand file. When I tried the "end the program", the total_demand was generated before the whole Rhino crushed to end. The console is as follows.
![demand](https://user-images.githubusercontent.com/16640327/100305571-4f057380-2fdc-11eb-9b6b-94cd2ddd41e1.PNG)

Please let me know if you need more information. Thanks!

**Comment by daren-thomas** [comment]
@shizhongming are you running the newest version of CEA?

**Comment by shizhongming** [comment]
@daren-thomas I was using the CEA installed around 4 weeks ago...probably not...let me reinstall to have a try

**Comment by shizhongming** [comment]
@daren-thomas I just installed 3.14....still have the same problem...any other solution I can try?

**Comment by daren-thomas** [comment]
@Shi Zhongming <shi@arch.ethz.ch>
one thing to try is to make sure the simulations work with standard CEA,
so... do they run through when you run them with the GUI?

Next thing to try is to set multiprocessing to "off". Does this make a
difference?

**Comment by shizhongming** [comment]
@daren-thomas everything works well using CEA console command line (with multi-processing)
For Grasshopper interface, everything just worked with single-processing....! Is it a problem we need to fix? or it is my computer's problem...
