### ISSUE TITLE
Coordinate reference system issues when importing zone file

### ISSUE THREAD

**Issue by oisindoherty3** [architecture-building-systems/CityEnergyAnalyst#2842]
I am importing a zone file with polygon geometries in standard lat/long format, which should be based in Dublin, Ireland. When I read in the files however and it projects in CEA the buildings appear in the ocean off the coast of Africa.

I've tried rectifying this through a geometry conversion to UTM coordinates using Geopandas .set_crs however I couldn't get that to accurately work either. 

I've seen the inbuilt function cea.utilities.standarize_coordinates.shapefile_to_WSG_and_UTM discussed in previous issues, which defines the standard coordinate system to use for the Shapefiles in the CEA. However I can't seem to get this to work for me either.

This is my first post to github so excuse any simple fix I may have overseen!

I've attached the zip file with the zone shapefile I've used.

Any help is much appreciated! Thanks!

[GeodirSampleCEA.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/5334295/GeodirSampleCEA.zip)

**Comment by oisindoherty3** [comment]
As an update on this, I have uploaded a more recent version of my shapefile with the lat/longs for a sample district inputted. This still sends me out to the ocean! Hoping you can help, Oisin
[GeodirSampleCEA4326.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/5341416/GeodirSampleCEA4326.zip)

**Comment by oisindoherty3** [comment]
Hey just an update, I was able to get it working through manually setting the original CRS in a Geopandas and then converting those GeoDataFrames to an EPSG of 32629. The issue still remains however when I import latitude and longitudes that it places me in the middle of the sea!

**Comment by daren-thomas** [comment]
@oisindoherty3, Sorry for only getting to this now. Great sleuthing!

I'm not quite sure I understand your last post: After conversion, does it now work for you? Or is your scenario still in the middle of the ocean?

What do you mean with "import latitude and longitudes" - how exactly are you going about this?

**Comment by oisindoherty3** [comment]
Hi Darren,

No problem at all! It works for me now yes, I originally had the geometry column of my imported dataset in EPSG 4326, so purely latitude and longitude. This however was placing me in the ocean, it took a good while of playing around but eventually my solution was to set the crs of my original dataset to its origin country (EPSG 2157, Ireland), then use the Geopandas operation to_crs to set the EPSG to 32629, which then worked perfectly when imported. 

Hopefully this helps someone else in the future with a similar issue!

Regards,
Oisin

**Comment by daren-thomas** [comment]
Hi Oisin,

Thank you for your feedback. That's a useful tip!

Regards,
Daren
