### ISSUE TITLE
Add a list of published plugins

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2843]
**Describe the feature you would like to have**
Our documentation / website should include a page of links to plugins for the CEA. And some basic instructions on how to install and configure plugins.

**Describe the end purpose of this feature**
We want to show a list of additional functionality that can be added to the CEA - and also show off the hard work of our users!

**Describe the end-user of this feature**
All users.

**Provide Aditional information if possible**
NA.

**Comment by shanshanhsieh** [comment]
@daren-thomas , please take a look at the page i created : https://cityenergyanalyst.com/plugins
password to this page: cea

please make any necessary changes, and enable the page if you think it's good to go!
thanks : )

**Comment by daren-thomas** [comment]
@shanshanhsieh I _did_ find a small typo (tamplate vs. template).

I don't really understand how to "enable the page" - I checked the page settings but only found the password thing. How do I enable it?

**Comment by daren-thomas** [comment]
Also add some hints on how to install plugins to this page.

**Comment by daren-thomas** [comment]
we decide: @daren-thomas updates the template to add installation instructions. maybe add a blog post on dealing with plugins (installing, uninstalling, registering in config file...)

**Comment by daren-thomas** [comment]
done.
