### ISSUE TITLE
importing own zone .shp, latitude out of range (must be between 80 deg S and 84 deg N)

### ISSUE THREAD

**Issue by RolandNemeth** [architecture-building-systems/CityEnergyAnalyst#2847]
**Describe the bug**
Using the older GHSHP grasshopper components, I converted some project Rhino 3dm geometries for importing to CEA. The geometries apear to be valid, as I checked them in an ArcGIS viewer, and they show up as expected.

However, when trying to import the geometries, CEA tells me that "ERROR: create_new_scenario: latitude out of range (must be between 80 deg S and 84 deg N)", more specifically;
```
Traceback (most recent call last):
File "c:\users\nemeth.roland\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\api\project.py", line 146, in post
typology=files.get('typology'))
File "c:\users\nemeth.roland\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 58, in call
self._runner.__call__(*args, **kwargs)
File "c:\users\nemeth.roland\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 38, in script_runner
script_module.main(config)
File "c:\users\nemeth.roland\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\create_new_scenario.py", line 120, in main
create_new_scenario(locator, config)
File "c:\users\nemeth.roland\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\create_new_scenario.py", line 46, in create_new_scenario
zone, lat, lon = shapefile_to_WSG_and_UTM(zone_geometry_path)
File "c:\users\nemeth.roland\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\standardize_coordinates.py", line 27, in shapefile_to_WSG_and_UTM
data = data.to_crs(get_projected_coordinate_system(lat, lon))
File "c:\users\nemeth.roland\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\standardize_coordinates.py", line 56, in get_projected_coordinate_system
easting, northing, zone_number, zone_letter = utm.from_latlon(lat, lon)
File "C:\Users\nemeth.roland\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\utm\conversion.py", line 155, in from_latlon
raise OutOfRangeError('latitude out of range (must be between 80 deg S and 84 deg N)')
OutOfRangeError: latitude out of range (must be between 80 deg S and 84 deg N).
```
I did try the .prj file downloaded from the link provided [here](https://cityenergyanalyst.com/blog/2020/05/22/grasshopper-cea-part-4-energy-demand-simulation-using-cea-in-rhino-6), and also with a prj copied from an openstreetmap generated zone at te same location. What could be the problem? I suspect the prj file, or maybe the projection system of the CEA/OSM generated prj had been modified since the blog tutorial, and now a different projection is expected?

**To Reproduce**
1. Convert geometries using GHSHP
1.1 Check geometries using a GIS shp viewer to see if they are valid
2. add .prj file next to the .shp for importing, either from here: https://spatialreference.org/ref/epsg/4326/prj/ or from an Openstreetmap generated project at the same lattitude/longitude
3. try to import to CEA

**Expected behaviour**
I expected the own zone geometry to appear as it should

**Hardware (please complete the following information):**
 - OS Windows 8.1
 - Version of CEA 3.11

**Comment by daren-thomas** [comment]
@RolandNemeth thank you for reporting this. We're looking into it. Can you provide more information? E.g. a test case that shows the error?

**Comment by RolandNemeth** [comment]
@daren-thomas . Hi, thanks for looking into it, I have attached the files here as a zip, with the two prj versions mentioned in the original issue above; let me know if you need anything else to get a clear picture!
The error shows up already with only the zone.shp as imported geometry, but I have attached the streets and surroundings too for completeness.
[CEA_rhino_shp_inputs.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/5428148/CEA_rhino_shp_inputs.zip)

**Comment by RolandNemeth** [comment]
btw, I have found this thread, could be related?
https://github.com/Turbo87/utm/commit/17e570cd3dde0b5daa774b68cbb7130ea2f0016c

**Comment by jimenofonseca** [comment]
Let me suggest some checks, maybe this helps.

Option A.
1. Try reading the file in arcgis without any .prj file added to it (erase it if you have it in the same folder)
2. then try to import it in CEA.

Option B. 
1. Try reading the file in CEA directly without any .prj file added to it (erase it if you have it in the same folder).

Option C.
1. is your location in the north or south poles (outside of the 85 deg N and 84 deg S).
2. if so, we will have to improve the code for this, CEA does not support it.

**Comment by Ekaterina-Vititneva** [comment]
Hi! I did have the same issue for a couple of days with shapefiles from grasshopper (with .prj file from osm). Now, after deleting the .prj files from “inputs\building-geometry” and afterwards inserting them there again it worked to open this scenario and the input editor for it. (I have CEA 3.4 though).

**Comment by shanshanhsieh** [comment]
@RolandNemeth did any of the options solve your problem?

**Comment by nasty-bos** [comment]
Hi @RolandNemeth. Let me share the workflow I was using to deal with the shapefiles: 

1. Start by following this guide: https://cityenergyanalyst.com/blog/2019/12/12/grasshopper-to-cea-part-3-exporting-gh-geometries-to-shapefile
2. Use QGIS to enrich created files from Grasshopper with the coordinate system (in my case, "WGS 1984 UTM Zone 48N" for Singapore) and set the exact location manually. 
3. Export shapefiles from QGIS. 

I would suggest trying out QGIS, it's a free and easy-to-use tool. The same workflow with ArcGIS didn't work for me, so I ended up using QGIS instead. I attach an example of a shapefile [zone_example.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/5461402/zone_example.zip). Let me know if you have further questions, I will be happy to help with QGIS.

**Comment by daren-thomas** [comment]
Closing this issue. @RolandNemeth, feel free to re-open if the proposed solutions don't work.
