### ISSUE TITLE
Write a blog post on how I created a plugin for CEA

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2851]
- reference your research on this topic.
- focus mainly on the _content_ of your plugin (we already have blog posts explaining the _how-to-plugin_)

**Comment by daren-thomas** [comment]
status update: draft session.

**Comment by daren-thomas** [comment]
@lguilhermes, soooo looking forward to the blog post demo tomorrow :)

**Comment by daren-thomas** [comment]
Status update: This is in the making. Some final touches needed before peer review.

**Comment by lguilhermers** [comment]
There is a first version available to read on the slack group. 
If there are no additional feedbacks about it, please let me know the next step to turn it into a blog post 👍
