### ISSUE TITLE
help in restoring v2.22 flexibility_model functionalities

### ISSUE THREAD

**Issue by piotre13** [architecture-building-systems/CityEnergyAnalyst#2858]
I'm quite new to programming world, so I apologize if this question is too silly. I wanted to know if you have any suggestions or ideas on how to restore the flexibility_model module (from the concept version, last version in which it is out of legacy is the v2.22, https://github.com/architecture-building-systems/CityEnergyAnalyst/tree/v2.22/cea/optimization/flexibility_model ).
furthermore i wanted to know if the outputs file of the demand module, still have the same structure in this new version with respect to the v2.22.
Thanks

**Comment by shanshanhsieh** [comment]
@piotre13 the structure of the demand files are still the same, the column names might change a bit since v2.22.
