### ISSUE TITLE
How to estimate energy loads from specific emission system using Energyplus simulation results & modify the energy flow hierarchy for building-level systems

### ISSUE THREAD

**Issue by 89ng** [architecture-building-systems/CityEnergyAnalyst#2859]
**Describe the feature you would like to have**
I find many of the cea functions very helpful to plan & try out systems even at the building-level. However, it is extremely hard for me to find out & modify all the corresponding functions & APIs, I would really appreciate some  brief instructions & explanations regarding the following features:
1.	How to estimate energy loads from specific emission system using Energyplus simulation results (with its IdealHVAC loop), I think some useful function blocks have been designed to estimate loads from specific emission systems (e.g. floor heating & AHUs as DOAS ) based on the demand from an RC-model
2.	How to modify the energy flow hierarchy for building-level systems, e.g. if I would like to have a heat pump directly coupled with solar collectors/PVT at its heat-source, I think the chart below seems to be used to describe all the energy flow hierarchy inside cea, but I still failed to find the main script which contains al  the balance equations of all the energy flows
![supply_system_superstructure (1)](https://user-images.githubusercontent.com/58104779/98352323-28c46780-201e-11eb-9598-d3db28955368.png)

3.	Is that possible that I also encapsulate these functions as functional blocks in Grasshopper, then I could directly link the energy demand simulation results from honeybee to these blocks, and use these modified cea functions for my building system planning & simulation?
I found there seem to be a grasshopper plug-in to link cea, but seems it was designed only for Rhino5?
Some many questions I’ve put on here, I have to say thank you so much in advance, these features are really not necessary to be something to add or improve, for me some instructions on how to DIY it would be enough.

**Describe the end purpose of this feature**
So I could use cea for building system design & first-stage simulation, as cea does reach a good balance between computational complexity & accuracy, and also flexible to edit

**Describe the end-user of this feature**
Building system planner

**Comment by daren-thomas** [comment]
@89ng we'll look into your questions more closely tomorrow and on Thursday during our bi-weekly sprint meeting. Especially regarding questions 1 & 2.

Regarding question 3: We do have a release of the Grasshopper plugin for Rhino 6. See https://github.com/architecture-building-systems/cea-grasshopper/releases

The level of detail is on the separate scripts, of which demand is just one. So no, these function blocks won't show up in Grasshopper and can't easily be factored out either. That's just not one of the goals we had for the CEA.

**Comment by shanshanhsieh** [comment]
1. That's a really good idea! The way the code is set up, the cooling load from the RC-model and the cooling load of the emission systems are not calculated seperately. You can find the details in `hourly_prodecure_heating_cooling_system_load.py`.
Maybe you could check the HIVE project: https://github.com/architecture-building-systems/hive, which breaks up the demand and supply calculation into grasshopper components.


2. The CEA cannot simulate specific supply technologies at the building level. 
In the supply system optimization, building level supply systems are simulated in `cea/optimization/preprocessing/decentralized_buildings_cooling.py` or `decentralized_buildings_heating.py`. There you can the energy balance calculation.

**Comment by 89ng** [comment]
Thanks a lot, it really helps!
