### ISSUE TITLE
Plan a CEA Hackathon

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2863]
For December. With a schedule for pair-programming sessions.

**Comment by shanshanhsieh** [comment]
I think we could tackle the GUI related issues in December 2020, the rest in January 2021.

GUI related issues:
1. using `schmas.yml` to modify inputs #2749 , #2825 *Driver:* @shanshanhsieh 
2. database editor #2572, #2825, #2758 *Driver:* 
3. delete scenario in GUI #2811 *Driver:* @daren-thomas 
4. create scenario #2872, #2871 *Driver:* @nasty-bos 

Coding related topic:
1. How to check if all the codes are in use, and used in the right way? *Driver:* @shanshanhsieh  (example: network script)
2. How to build a test function? *Driver:* @nasty-bos (example: glossary unit test? #2680, #2541 )
3. Documentation #2541
