### ISSUE TITLE
subhourly demand calculation

### ISSUE THREAD

**Issue by piotre13** [architecture-building-systems/CityEnergyAnalyst#2869]
dear all,
I'm looking deeply at the cea codes and I wanted to know if in your opinion is it possible to let the demand module run with a different timestep. I've seen that there are parameter setting the timestep such as the constants in _constants.py_ (HOUR_in_YEAR etc..) do you think that if I make some changes to these constants and to some input data the module could work and return results for example on a 15min base? if yes can you tell me which parametrs and which script must be changed to simulate a 15 min timestep?
Thanks

**Comment by daren-thomas** [comment]
@piotre13 without checking the source code directly, I assume the following: No. It will not be quite as easy.

If I remember correctly, the demand code has two "levels". A high-level one and a low-level one. You can easily spot the high-level functions as they normally include a `tsd` parameter, which stands for "time step data". The lower-level functions calculate the actual equations for each timestep. Except, that the high-level ones calculate some values that can be done for all timesteps in one go.

Now. I'd be surprised if there aren't any hidden dependencies on the number of timesteps being 8760. Weather calculations come to mind.

Also, I'm not sure if the equations still work for smaller timescales - there might be some time constants built in, reflecting the "capacity" in the RC-model. I don't know if these can be used for lower time steps - you'd have to figure that out based on the ISO specification.

So, to answer your question: You'll have to take the demand script apart, step by step, to find the dependencies.

@gabriel-happle is any of what I just described above correct?

**Comment by jimenofonseca** [comment]
@piotre13 Changing CEA to a sub-hourly calculation is not a very straightforward thing to do, unfortunately. 

However, there is a way around which holds very good in many circumstances: Use pandas to post process and subsample the hourly data to 30mins intervals. While at it you can add some stochasticity to the problem.

We have done this approximation in the past to study a network of Model predictive Controllers with CEA connected to price signals of the power grid.

I hope this helps. I am closing this issue for now :-).
