### ISSUE TITLE
Dashboard: Button "Draw" disappears while selecting an area in the map for the zone file

### ISSUE THREAD

**Issue by nasty-bos** [architecture-building-systems/CityEnergyAnalyst#2872]
**Describe the bug**
Button "Draw" disappears while selecting an area in the map for the zone file. 

**To Reproduce**
1. Go to 'Select an area in the map for the zone file'.
2. Type in a location and click "go". 
3. Scroll down to the map and see that there is no button "draw". 

**Expected behaviour**
Button "Draw" should be always present on the map. 

**Screenshots**
![image](https://user-images.githubusercontent.com/37011711/99549710-3b458600-29ba-11eb-8bfb-92dc3c2e6d6d.png)

**Hardware:**
 - OS and version: Windows 10
 - Version of CEA: 3.13.0

**Comment by daren-thomas** [comment]
This happens for me too! Clicking somewhere close to where the button should be can make it show up again. According to @shanshanhsieh zooming in and out can also help.

**Comment by daren-thomas** [comment]
quick-fix: add a warning on the side?

**Comment by nasty-bos** [comment]
> This happens for me too! Clicking somewhere close to where the button should be can make it show up again. According to @shanshanhsieh zooming in and out can also help.

yes, these tricks work for me too

**Comment by daren-thomas** [comment]
let's move the draw button off the map...
