### ISSUE TITLE
Create Buildings that cannot be found on OpenStreetMap

### ISSUE THREAD

**Issue by shjiang** [architecture-building-systems/CityEnergyAnalyst#2876]
Dear all,
I'm studying this wonderful software, and it is found that some buildings (remote villages, etc.) cannot be found on the OpenStreetMap. Can anyone tell me how to add buildings to the new scenario in this case?
Thanks a lot!

**Comment by daren-thomas** [comment]
Basically, you'll need to create your own zone.shp file - using ArcGIS or QGIS or similar software, making sure to save it in the right map projection. Maybe use a similar shapefile based on buildings you _can_ select in open street maps as a starting point?

**Comment by martin-mosteiro** [comment]
@shjiang This resources might help:
1. You might want to create your geometries on geometry and export them to shapefiles for use in CEA: [link](https://cityenergyanalyst.com/blog/2019/12/12/grasshopper-to-cea-part-3-exporting-gh-geometries-to-shapefile)
2. Or perhaps draw your geometries on your prefer CAD software and manually create your shapefiles using GIS software: [link](https://cityenergyanalyst.com/creating-multiple-scenarios#create-new-geometry)

These resources might be somewhat outdated but they should still be usable.

**Comment by shjiang** [comment]
> Basically, you'll need to create your own zone.shp file - using ArcGIS or QGIS or similar software, making sure to save it in the right map projection. Maybe use a similar shapefile based on buildings you _can_ select in open street maps as a starting point?
@daren-thomas  Thanks a lot for your kind reply. It is easier to start with a similar shapefile based on an existing project. I first convert "zone.shp" file to a "dwg" file, modify it, and then convert it back to "shp" file by using ArcCatalog software. If the numbers of the buildings are not the same, the file "zone.dbf" should also be modified.

**Comment by shjiang** [comment]
> @shjiang This resources might help:
> 
> 1. You might want to create your geometries on geometry and export them to shapefiles for use in CEA: [link](https://cityenergyanalyst.com/blog/2019/12/12/grasshopper-to-cea-part-3-exporting-gh-geometries-to-shapefile)
> 2. Or perhaps draw your geometries on your prefer CAD software and manually create your shapefiles using GIS software: [link](https://cityenergyanalyst.com/creating-multiple-scenarios#create-new-geometry)
> 
> These resources might be somewhat outdated but they should still be useful.


@martin-mosteiro  Thanks a lot for your kind reply. I have tired the second method you provided by using ArcCatalog and AutoCad software. I can successfully convert a dwg file to a shape file, with ".shp","shx",".dbf" files generated. However, it is found that the format of the "dbf" file generated is quite different from the format of the file "zone.dbf" that used by CEA.

**Comment by martin-mosteiro** [comment]
@shijang Good to hear the first step worked. Could you please clarify what you mean by the dbf format? Is it a matter of the attributes (e.g., `floors_bg`, `floors_ag`) not being the same or something else?

**Comment by shjiang** [comment]
> @shjiang Good to hear the first step worked. Could you please clarify what you mean by the dbf format? Is it a matter of the attributes (e.g., `floors_bg`, `floors_ag`) not being the same or something else?

The dbf file generated together with shp file by ArcCatalog is like this:
![image](https://user-images.githubusercontent.com/2359242/101605728-81cc5480-3a3d-11eb-83fa-8caa72174d60.png)

The dbf file needed by CEA is like this:
![image](https://user-images.githubusercontent.com/2359242/101605674-6eb98480-3a3d-11eb-90f9-a1201f67df17.png)

**Comment by shanshanhsieh** [comment]
@shjiang, you can add those columns in Arccatalog by editing the .shp files.
in the .shp file, you can add "fields" to represent those columns

**Comment by shjiang** [comment]
> @shjiang, you can add those columns in Arccatalog by editing the .shp files.
> in the .shp file, you can add "fields" to represent those columns

 @shanshanhsieh  Thanks for your reply. I have tried it. It worked. I added "fields" in ArcCatalog and then edited the table in ArcMap.
