### ISSUE TITLE
ReMaP: Collect weather files

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2878]
- Collect weather files from

**Comment by daren-thomas** [comment]
@nasty-bos, this is what we probably need in a first step:

- list of weather stations (and location?) for Switzerland
- for each weather station, one weather file per weather-scenario we'd like to be able to compute
- (the weather station location is probably encoded in the epw file, so no need to do that separately)

**Comment by shanshanhsieh** [comment]
@nasty-bos , can you explain the updates here? thanks!

**Comment by nasty-bos** [comment]
The weather files (.epw) were provided to @daren-thomas for the following stations: Basel, Geneva, Lugano, Zermatt, Zurich. Each location has a status quo file and future projections (2040, 2060) depending on climate change scenario (RCP2.6 or RCP8.5). In total, this accounts to 5 weather files per station.
