### ISSUE TITLE
Remap: program retrofit scenarios

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2880]
Based on a zone.shp file, update the `input/building-properties` folder to reflect the ReMaP/VILLE retrofit scenario.

TODO: specify what files actually get changed and how? (or do we use `archetypes-mapper`?)

**Comment by nasty-bos** [comment]
Same as [2881](https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2881). Can we do this? 
![image](https://user-images.githubusercontent.com/37011711/101910158-d945fe00-3bbe-11eb-9adf-5f679f244036.png)

**Comment by shanshanhsieh** [comment]
this issue is replaced by #2902
