### ISSUE TITLE
Remap: program urban development scenario 

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2881]
Figure out which databases need to be updated in `inputs` for a given `zone.shp` and `urban-development-scenario` choice.

How do we handle densification???

**Comment by daren-thomas** [comment]
we need to discuss this in the 3.17 sprint.

**Comment by nasty-bos** [comment]
@daren-thomas we have urban development, climate change, retrofit and HVAC and supply scenarios. Climate change scenarios will not affect input folder structure. As for the rest, we have only tackled urban development and defined 3 scenarios by now. I have checked which columns in the input files have to be modified. Would it be possible to have one input folder per urban development scenario? See attached. If that's fine, I will provide modified input folder with dummy values in the columns that are to be changed. If not, let's discuss possible alternatives. 
![image](https://user-images.githubusercontent.com/37011711/101908620-a0a52500-3bbc-11eb-9594-45459219d868.png)

**Comment by shanshanhsieh** [comment]
here are some user stories that could facilitate our discussion:
1) user wants to build a case in a district in Lucern
1a) what is the status quo energy demand? -> extract geometry from osm, update building uses, envelope, hvac from GWR database
1b) what is the energy demand in 2035, business as usual UD, NEP retrofit?
1c) what is the energy demand in 2035, balances UD, NEP retrofit?

2) user wants to know the energy demand of the district archetype in a sub-urban area.
2a) what is the status quo?
2b) what is the energy demand in 2060, urban decline UD, business-as-usual retrofit?

**Comment by shanshanhsieh** [comment]
this issue is replaced by #2902
