### ISSUE TITLE
TSD dict in Demand module

### ISSUE THREAD

**Issue by piotre13** [architecture-building-systems/CityEnergyAnalyst#2896]
Hello to everyone,
I'm digging a bit into the demand calculation module of CEA and I wanted to have a bit more of information on some internal datastructure.
Do you know where I can find a complete list of the meanings of the keys present in the tsd dict used in demand?
I think should be really useful to have a nice documentation of the calculations performed, cause i'm not finding the SIA 2024, and maybe with the right corrispondence with the names you've been using.
sorry to bother and really thanks for this tool!!

**Comment by daren-thomas** [comment]
@piotre13 most of the tsd variables correspond to the output columns of the demand script. sadly, the SIA 2024 norm is not free. @gabriel-happle knows more about the calculation.

**Comment by daren-thomas** [comment]
@piotre13, thank you for your patience, we are back from Christmas break and will look into this soon.

**Comment by shanshanhsieh** [comment]
Hi @piotre13,

i understand how it is a bit of a pain to understand these variables, u can normally find the definition following the function using these variables as input arguments.

in `calc_temperatures_emission_systems()`, the main purpose is to calculate the supply conditions of the emission systems.
by emission system, it means the radiators, floor heating panels, air-handling units (ahu), air-recirculating units (aru) etc...
the main calculation here is to understand the conditions on both sides of the heat exchangers.
here we have the air-side (the space to be heated or cooled) and the water side (e.g., hot water in the radiator)
the output of this function is the operating conditions of the water side of the heat exchanger. This will be specifying what the boiler is supplying to the radiator, for example.

- Ta_heating_0 = ta_hs_set : indoor temperature set-point
- Qhs_sys_0: nominal heating load that the building requires
- ma_sup_0: nominal air flow in aru/ahu
- Ta_sup_0: nominal supply air temperature of aru/ahu
- Ta_re_0: nominal return air temperature of aru/ahu
- Qhs_sys_ahu_0: nominal heating load that is being supplied by the ahu

in `calc_Qhs_Qcs_loss`, the heating/cooling loads are being updated with the loss in the emission systems.
we followed ISO15316 to reflect the energy loss in the distribution pipelines within the buildings.

the nominal conditions are normally when the systems are having maximum load, this allows us to size the heat exchangers.
I am not sure what you mean by the min values?
