### ISSUE TITLE
shapefile import error creating a new scenario (manually created zone.shp file)

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#2901]
**Describe the bug**
For a project I need to use my own shapefiles for energy demand simulation. I can create a new scenario by using the import function, but when I open the input editor there is an unknown error. To use a correct spapefile to perform the process, I tried a shapefile generated by CEA (from another scenario; [zone.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/5714553/zone.zip)) – still the same error. 
The occurring problem may be close to the one described by LeoTom #2753

**Screenshots**
![image](https://user-images.githubusercontent.com/73158684/102592376-ac8c6c00-4113-11eb-92a2-03d7ffad771c.png)
![image](https://user-images.githubusercontent.com/73158684/102592429-bf9f3c00-4113-11eb-88e2-07680503154f.png)

**Hardware:**
 - Windows 10
 - Version of CEA 3.15.0
 - Simulating the energy demands of a scenario created by the CEA tools is working

Thank you in advance

**Comment by nasty-bos** [comment]
Hi @Mar-Ges. To see more information about the occurred error, first you should start the backend of the CEA Dashboard by typing `cea dashboard` in the CEA Console. Then, open the CEA Dashboard application. Please repeat the actions in the Dashboard that led to the error, and send us the information from the CEA Console. In this way, we will be able to see what is causing the error. Please note, that you should have a developer version of CEA installed to be able to use CEA Console. Let us know if you have questions.

**Comment by Mar-Ges** [comment]
Hi @nasty-bos, 

I just installed the developer version and tried to import a shapefile again. The shapefile attached to my first message now creates a  working simulation model. 
Here a copy from the CEA Console: 
[consolefileCEA.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/5716277/consolefileCEA.docx)

Then I tried to use a file prepared after the naming rules of CEA, but it didn't work. 
More details:
[zoneownfile.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/5716283/zoneownfile.zip)
[consoleownfile.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/5716284/consoleownfile.docx)

- Do I have to install the "pandana and urbanaccess " mentioned at the console?
- Is the error occuring because of a mistake in my file?

**Comment by shanshanhsieh** [comment]
hi @Mar-Ges, 
i just checked the `zone.shp` in `zoneownfile.zip`
please try again but make sure the column names are exactly like this: **'Name', 'floors_bg', 'floors_ag', 'height_bg', 'height_ag'**
let me know how it goes!

**Comment by Mar-Ges** [comment]
Hi @shanshanhsieh,

I tried to order and name all columns in the dbf.file correctly, but unfortunately the import still doesn't work. 
Therefore I took a CEA-generated Shapefile as example.

Here the corrected shp.file:
[zoneownfile0104.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/5765025/zoneownfile0104.zip)
shp.file in QGis
![Controlviewshp](https://user-images.githubusercontent.com/73158684/103542881-eee8d380-4e9d-11eb-8548-b96c7195acf4.PNG)
dbf.file in LibreOffice
![dbffile](https://user-images.githubusercontent.com/73158684/103543656-2f951c80-4e9f-11eb-8aa1-5d5fe8655622.PNG)

And a copy from the CEA Console: 
[CEAConsole0104.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/5765005/CEAConsole0104.docx)

**Comment by shanshanhsieh** [comment]
hi @Mar-Ges,
the ordering of the columns isn't important but the capitalization might be.

**Comment by daren-thomas** [comment]
It seems to be a problem with the capitalization of the fields. They need to be in the exact same format as @shanshan mentioned above. To make things harder, it seems most tools (QGIS? GTK DBF Editor) I know of don't make that distinction.

It's possible with a bit of python scripting. Something like this:

```
from geopandas import GeoDataFrame as gdf

path_to_zone_shp = r"C:\Users\me\Downloads\zone.shp"

zone_gdf = gdf.from_file(path_to_zone_shp)
zone_gdf.columns = ["Name", "floors_ag", "floors_bg", "height_ag", "height_bg", "geometry"]
zone_gdf.to_file(path_to_zone_shp)
```

NOTE: using this method, it's a good idea to do it in an `ipython` shell, which can be started from the CEA Console. First, check the columns of `zone_gdf` with `zone_gdf.columns` - they should be in the same order as the assignment afterwards.

I've gone ahead and fixed it for you and started on running the simulations. you'll still need a terrain.tif file it seems... but otherwise it seems to be working! [https://app.zenhub.com/files/49491341/c4f1e252-0d94-4561-9de1-a20197f0966f/download](https://app.zenhub.com/files/49491341/c4f1e252-0d94-4561-9de1-a20197f0966f/download)

**Comment by Mar-Ges** [comment]
Thanks to both of you (@shanshanhsieh and @daren-thomas)- Now I can import my files!
