### ISSUE TITLE
refactor cea/interfaces/dashboard/api/inputs.py to display relavent errors

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2911]
it seems like the errors that are showing are not relevant to the actual problem.
see examples in #2906
we are hoping that refactoring could help

**Comment by shanshanhsieh** [comment]
@reyery is this related to #2795?

**Comment by reyery** [comment]
@shanshanhsieh yea adding a log function after solving this would make debugging such errors easier
