### ISSUE TITLE
Solar radiation error  NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set

### ISSUE THREAD

**Issue by RicardoGomesIST** [architecture-building-systems/CityEnergyAnalyst#2918]
When I run the building solar radiation, it results on an error:

INFO:numexpr.utils:Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.

I used a shapefile form the municipality I am studying. Created the topology file with assigned new standard names. The archetypes mapper run with no problem. I have around 800 buildings. 

Windows 10 Pro
CEA version 3.7.0

TY

**Comment by RicardoGomesIST** [comment]
I believe this is related with the high number of buildings... If i delete and leave just a few, it runs without problems. Can you confirm?

**Comment by shanshanhsieh** [comment]
hi @RicardoGomesIST ,

could you please show the full stack of error msg?
the lines you show seem like warnings but the actual error msg.
if you are running from the GUI, pls follow the steps here to print the errors: 
> 
> 
> running `cea dashboard` in the CEA console and start the application after seeing the message below. It should hopefully show any error messages that would help us troubleshoot this. Thanks!
> 
> ![image](https://user-images.githubusercontent.com/34395415/91371132-c2171680-e842-11ea-9f87-81b3950769b5.png)

**Comment by RicardoGomesIST** [comment]
> C:\Users\Ricardo\CityEnergyAnalyst`

λ cea dashboard
City Energy Analyst version 3.7.0
Running `cea dashboard` with the following parameters:
- general:debug = False
  (default: False)
start socketio.run
Traceback (most recent call last):
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\ricardo\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 65, in main
    script_module.main(config)
  File "c:\users\ricardo\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\dashboard.py", line 33, in main
    socketio.run(app, host='localhost', port=5050)
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_socketio\__init__.py", line 602, in run
    self.wsgi_server.serve_forever()
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\gevent\baseserver.py", line 367, in serve_forever
    self.start()
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\gevent\baseserver.py", line 305, in start
    self.init_socket()
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\gevent\pywsgi.py", line 1490, in init_socket
    StreamServer.init_socket(self)
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\gevent\server.py", line 146, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\gevent\server.py", line 157, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\gevent\server.py", line 256, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
**socket.error: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted: ('localhost', 5050)

>

**Comment by shanshanhsieh** [comment]
Hi @RicardoGomesIST
it seems like there are two CEA Dashboard running at the same time.
please make sure you close all running CEA programs and start from the CEA Console again.
the orders are: open CEA Console > type `cea dashboard` > open CEA Dashboard > run radiation

**Comment by RicardoGomesIST** [comment]
Hi again, The problem was related with some buildings that were not considered as polygons. Some vertices were creating strange shapes within the polygon. Unfortunately, QGIS does not identify this problem, at least from what I know.
Thank you very much.

**Comment by reyery** [comment]
> Hi again, The problem was related with some buildings that were not considered as polygons. Some vertices were creating strange shapes within the polygon. Unfortunately, QGIS does not identify this problem, at least from what I know.
> Thank you very much.

I think the radiation script only supports buildings that are of type `Polygon`, so you might be right about this. 

May I know how you are generating the zone shapefile? That could help us better understand the source of the problem. Because I do know that if you are using the `zone-helper` tool, which pulls the building polygons from Open Street Maps, some buildings might be in the `MultiPolygon` format.

**Comment by RicardoGomesIST** [comment]
> I think the radiation script only supports buildings that are of type Polygon, so you might be right about this.

Yes, that was the error described in CEA. The buildings were not polygons. 

This shapefile came from one portuguese municipality. It require some work to run on CEA. 
Thank you

**Comment by RicardoGomesIST** [comment]
> cea dashboard

**Comment by halsibai** [comment]
> > I think the radiation script only supports buildings that are of type Polygon, so you might be right about this.
> 
> Yes, that was the error described in CEA. The buildings were not polygons so solar radiation could not run,
> 
> This shapefile came from one portuguese municipality. It required some work to run on CEA. Thank you

how did you make them all polygons? is there an option in the cea software ?
