### ISSUE TITLE
3for2 regression model for CEA

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#292]
Program the 3for2 regression model by @shanshanhsieh for the CEA.

@shanshanhsieh please add milestone, etc.

**Comment by shanshanhsieh** [comment]
I made some first attempts to correlate cooling electricity with outdoor T, RH and occupancy, not much correlation is found with linear regression. We could look into time series analysis when we have a chance.

**Comment by JIMENOFONSECA** [comment]
Well... As discussed we have to look at multivariate regression approaches. Linear regression of one vs one variable does not work. check this in detail. There are plenty of people gattering surrogate models from both measurements and simulation. What approach (name of the method) did you used that did not work???

**Comment by gabriel-happle** [comment]
@shanshanhsieh this can be closed, right?
