### ISSUE TITLE
CEA Download Version

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2921]
I downloaded the latest CEA version (V3.18.0). But the file name is 3.15. Is there a name mismatch? Or did you forget to upload the latest release?
![CEA](https://user-images.githubusercontent.com/29708612/106169838-e041c380-61a0-11eb-8d00-4f5d58b7ea00.jpg)

**Comment by shanshanhsieh** [comment]
Hi @kerembeygo,

Thank you for noticing it!
Please download the installer again: https://cityenergyanalyst.com/try-cea
It should download the correct installer for v3.18.0 now
