### ISSUE TITLE
UNKNOWN ERROR Input Editor - Socketadresse

### ISSUE THREAD

**Issue by AWillmann** [architecture-building-systems/CityEnergyAnalyst#2923]
I get an unknown error when opening my project - cea console displays:

OSError: [WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden: ('0.0.0.0', 5050)

How do I solve the issue.... ?

**Comment by daren-thomas** [comment]
@AWillmann, you could try to edit the `cea.config` file. Look under the `[server]` section for a `host` setting and set that to `localhost`.

**Comment by shanshanhsieh** [comment]
@AWillmann are you able to solve this error?

**Comment by AWillmann** [comment]
Yes, thanks.
