### ISSUE TITLE
how to plot dashboard with solar radiation per buildings

### ISSUE THREAD

**Issue by tdallamora** [architecture-building-systems/CityEnergyAnalyst#2926]
the topic is how to plot solar radiation output for each surface (wall and windows and roof);
the default dashboard regards district output, but my goal is to verify the change in case of different scenario and different wwr;
how is the procedure, please?
thank you so much
the reference is the dashboard explained in 20180524_CEA_Exercise_Demand.docx
![immagine](https://user-images.githubusercontent.com/67967511/107027702-d0cc0700-67ac-11eb-8299-c067895a5acd.png)

**Comment by shanshanhsieh** [comment]
Hi @tdallamora,

Currently, the dashboard does not produce the plot you are describing.
However, you can access all the information you need in the `.csv` outputs.
The results are stored in `project folder/scenario folder/outputs/data/solar-radiation/Bxxxx_radiation.csv`.

To create multiple scenarios from a base scenario, you can (a) on the dashboard. Create New Scenario > Import input files > select the `zone.shp` from the base scenario, or (b) from the file explorer, copy the base scenario folder and rename it.
After creating a new scenario folder from the base scenario, you can go and change the wwr of the new scenario.

hope this helps!

**Comment by shanshanhsieh** [comment]
closing this issue for now, please feel free to re-open if anything is unclear, @tdallamora : )
