### ISSUE TITLE
Variable Naming in CEA

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#2927]
Not all variables are listed and explained at the page:
https://city-energy-analyst.readthedocs.io/en/latest/how-to-name-variables.html

I want to get the hourly heating demand for one of my simulated buildings (=Qhs_sys_kWh?) in the building-demand-cvs, but the naming of some columns and their links is unclear.

Examples:
shu 
DC
ve 
v

Close to `Total_demand.csv` #2839

**Comment by shanshanhsieh** [comment]
hi @Mar-Ges ,

for the **variable names** (e.g., `Qhs_sen_shu_kWh`) in the output files, you can refer to the glossary:
https://city-energy-analyst.readthedocs.io/en/latest/glossary.html
the same information can also be found through searching the variable names in the GUI (upper right corner: Glossary search)

please kindly let us know what variable names are missing in the glossary.

quick answer to your examples:
shu: sensible heating unit
DC: District Cooling
ve: ventilation
v: depend on the whole variable name

**Comment by Mar-Ges** [comment]
Hi @shanshanhsieh,
thank you, I didn't know this page before, but its really helpful!
