### ISSUE TITLE
The repository size is 1.6GB, consisting mainly of past datafiles

### ISSUE THREAD

**Issue by Bachibouzouk** [architecture-building-systems/CityEnergyAnalyst#2928]
I cloned the repository locally and was surprised to see the size of the download: 1.6 GB. Especially because the totality of files within the root of `master` sums up to 121.5 MB only. 

**To Reproduce**
1. `git clone https://github.com/architecture-building-systems/CityEnergyAnalyst.git`

I ran this command to list the commits with the largest size ```git rev-list --objects --all |   git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |   sed -n 's/^blob //p' |   sort --numeric-sort --key=2 |   cut -c 1-12,41- |   $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest```

I gathered the largest outputs in this file:
[too_big_commits.txt](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/5933803/too_big_commits.txt)

Inspecting them reveals that most of these files are not in the current version of the repository anymore

I am unsure to which extend rewriting the history by removing those commits is wished. In any case I wanted to point out the problem and propose a potential solution : https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

**Hardware (please complete the following information):**
 - OS and version: [ubuntu 18.04]
 - Version of CEA you are using [e.g. v. 3.18.0]

**Comment by shanshanhsieh** [comment]
Hi @Bachibouzouk,

thanks for pointing that out as well as suggesting the solution!
we will certainly take a look at it.

**Comment by shanshanhsieh** [comment]
Plan of attack:
- files that **do not** exist in the latest master: delete the history
- files that are **still** in the latest master: delete the history, and find a way to keep the latest version (not sure how)

Side effects: 

Standing branches need to **rebase** before merging 
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository
- [ ] How can an existing branch update from master after the git repo has been cleaned?
- [ ] Find out the standing branches and inform owners regarding this action
