### ISSUE TITLE
Central or local heating/hot water supply 

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#2929]
How can I consider the location of heating or hot water supply - for example central in one room per building or  local in each flat of a multiresidential building?

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,

For the space heating systems (`type_hs`), it is assume the whole building has the same system that is supplied the same way.
For example, one boiler per building to supply the radiator.

Could you please elaborate on the type of "local system" you are referring to?
and what will be the differences between the "central systems" and "local systems" that you wish to model?

**Comment by Mar-Ges** [comment]
Hi @shanshanhsieh,

I try to discribe it better by an example:
A "local system" for hot water supply is often placed in german office buildings. Electric instantaneous water heaters are placed in each bathroom/ sanitary room (Main Reason is to avoid a long hot water pipework to save energy and avoid legionella bacteria). 
A "central system" in this case would be one hot water boiler for the whole building. 

I want to consider the "local" hot water for a case study.

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,

The current hot water demand model assumes the "central system" in your definition.
That means `Qww_sys_kWh  = Qww_kWh + losses in distribution` (following ISO EN 15316 standard).

It will require some coding work to add in the "local system". If you are interested to contribute, you can follow these steps: https://city-energy-analyst.readthedocs.io/en/latest/how-to-contribute.html or discuss with me directly.

Meanwhile, i imagine you can take the end-use hot water demand `Qww_kWh` and calculate `Qww_sys_kWh` for "local systems" separately.
