### ISSUE TITLE
Types of mechanical ventilation systems

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#2930]
I want to consider following types of air conditioning:
- only mechanical supply air 
- only mechanical exhaust air
What should I do?

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,

Can you tell me the difference between the two systems?
In CEA, you can choose the type of cooling system independent from the ventilation system.
For example, you can specify a building with no space cooling but with mechanical ventilation by specifying `type_cs` to `HVAC_COOLING_AS0` and `type_vent` to `HVAC_VENTILATION_AS1`.
You can even define your own systems with the Database Editor tool.

**Comment by Mar-Ges** [comment]
Hi @shanshanhsieh,

In residential buildings, air is often supplied through the facade and extract air is removed from selected rooms (often kitchen and bathrooms) through ducts, case of "only mecanical exhaust air" (also shown in the following picture from https://www.hvi.org/resources/publications/mechanical-ventilation-types/) 
![image](https://user-images.githubusercontent.com/73158684/108178853-3604ee00-7105-11eb-9c75-4fe91b4981e9.png)

In the other case of "only mecanical supply air", a fan is used to pressurize a structure, forcing outside air into the building while air leaks out of the building through holes in the shell (often bathrooms and kitchen).
![image](https://user-images.githubusercontent.com/73158684/108179005-62b90580-7105-11eb-8e9d-b132dd3d474a.png)

In the database editor tool I can find the parameter for mechanical ventilation and window ventilation - but I can't match them to supply or exhaust air.

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges ,

In the current CEA models, both ventilation systems are processed the same way.
The mechanical ventilation requirement will induce **thermal load** and **electrical load** according to the following calculations:
- affecting sensible load via the RC model
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/ac1b3860ab711aa593ac9160d9a8d414cc213e09/cea/demand/rc_model_SIA.py#L612-L616
- affecting latent load 
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/ac1b3860ab711aa593ac9160d9a8d414cc213e09/cea/demand/latent_loads.py#L388
- affecting electrical load (auxiliary energy, e.g., fan)
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/ac1b3860ab711aa593ac9160d9a8d414cc213e09/cea/demand/electrical_loads.py#L316-L320

what do you wish to capture between these two ventilation types?

**Comment by shanshanhsieh** [comment]
closing this issue for now, please feel free to re-open it if anything is unclear : )
