### ISSUE TITLE
Unknown Error creating a new scenario

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#2931]
When I want to create a new scenario, it looks like there is an "unknown Error". After restarting CEA the scenario is created and I can use it normally. 
How can I avoid to restart it so often?

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,

Could you please describe your steps in more detail so we can understand where the problem might come from?
For example, which Data Management Tool did you select?

Or better, you could help us to print the full stack of error message.
The error message will help us to identify the source of the error.

pls follow the steps here to print the errors: 
> 
> 
> running `cea dashboard` in the CEA console and start the application after seeing the message below. It should hopefully show any error messages that would help us troubleshoot this. Thanks!
> 
> ![image](https://user-images.githubusercontent.com/34395415/91371132-c2171680-e842-11ea-9f87-81b3950769b5.png)

**Comment by Mar-Ges** [comment]
Hi @shanshanhsieh,

i tried to create the full error message. Since this morning, I can create new scenarios without error and restarting. When it occures again, I'll collect the full error message and post it here.
