### ISSUE TITLE
Calculation of envelope area - opaque and windows

### ISSUE THREAD

**Issue by RicardoGomesIST** [architecture-building-systems/CityEnergyAnalyst#2936]
Hi,
is there a way to quantify the envelope  (walls and windows) area by orientation and outdoors boundary?
I need to calculate the investment for insulating the walls and replacing the windows of a neighborhood.

Thank you
Best regards

**Comment by shanshanhsieh** [comment]
Hi @RicardoGomesIST,

The areas of walls and windows are in the radiation outputs.
Please follow this directory: `.../outputs/data/solar-radiation/Bxxx_geometry.csv`
hope this helps!

**Comment by RicardoGomesIST** [comment]
Hi Shanshansieh, thank you,
for getting all the areas per orientation for instance I should perform some programming as there is not an easiest way yet?
Best

**Comment by shanshanhsieh** [comment]
it seems so!
maybe you could publish your scripts as a [plug-in](https://cityenergyanalyst.com/blog/2020/6/12/cea-plugins-part-1-introduction) so the effects of your hard work could be multiplied : )

**Comment by shanshanhsieh** [comment]
closing this issue for now, please feel free to re-open if there are more questions, @RicardoGomesIST!
