### ISSUE TITLE
solar for DHW and PV - how to define panel area?

### ISSUE THREAD

**Issue by RicardoGomesIST** [architecture-building-systems/CityEnergyAnalyst#2939]
hi, 
I have a question regarding building retrofit with solar/ PV technologies implementation. I like to evaluate the implementation of solar panels for DHW, solar PV for electricity consumption on a residential neighborhood (only on roofs). 
From my understanding for calculate the DHW from solar energy we should:
1st simulate the needs for DHW (building energy demand). 
2nd simulate the Energy potential/ photovoltaic thermal panels
3rd compare on an hourly basis the production (potential) and the consumption for DHW and the missing energy we may consider for example that is provided by the grid

Is this the best method? How may we define the area of the solar panel? It this automatic to fit the rooftop area according to the panel area (in this case FT panel)? Is there a way to define the solar panel area available for each rooftop?

Regarding the PV is the same logic? IS there a way to simulate PVs system with battery?
 
thank you very much for your time

**Comment by shanshanhsieh** [comment]
Hi @RicardoGomesIST,

There are a few possibilities to customize the installation area of solar panels (available for PV and solar collectors) via the radiation threshold, and roof coverage.
Unfortunately, there are currently no way to customize the exact panel area (e.g., x m2) per building. 
Here are all the customization you can do when specifying solar panels.
![image.png](https://images.zenhubusercontent.com/57b4452fe40e5714b16d75a2/f8c5dab2-5272-4e5f-8ca7-66b9e2d7d766)

The battery storage in CEA is only included in optimization but not simulation at the moment.
It sounds like an great idea to develop into your own CEA plug-in for that!
https://daren-thomas.github.io/cea-plugins-part-1/

**Comment by RicardoGomesIST** [comment]
Thank you very much!
When we ask for:
1. outputs\data\demand: SOLAR_ww_kWh - Solar thermal energy requirement for hotwater supply
2. outputs\data\potentials\solar\B10540_SC_FP.csv: SC_FP_roofs_top_Q_kWh -Heat production from solar collectors on roof tops
- I dont understand the first parameter... it is not the demand...
-What is the relation between these parameters (if exists)?

For a first analysis of the contribution of solar on DHW energy consumption I will calculate the daily hot water demand and the daily solar production (affected by the real area of panels). When the demand is higher than the production energy it is considered that the backup system for DHW enters. 
Is there some obvious error that I am not seeing?

Thank you again

**Comment by shanshanhsieh** [comment]
Hi @RicardoGomesIST,

- `SOLAR_ww_kWh` is a quick estimation based on `Qww_sys_kWh` and a fixed energy efficiency. 
This efficiency could be a user input. The goal is to allow user to get a rough estimation without running more simulations after the demand tool.
1. add a new supply system assembly for hot water via **Database Editor>ASSEMBLIES>HOT_WATER**
2. assign building to that assembly by changing **type_dhw** in the **supply_system tab** of each scenario.
I will recommend you to check this blog post for the exact detail: https://cityenergyanalyst.com/blog/2020/4/23/working-with-cea-databases-part-3

- As you suspected, there is no connection between `SOLAR_ww_kWh` and `SC_FP_roofs_top_Q_kWh`.

- I would agree with your analysis steps.

**Comment by shanshanhsieh** [comment]
closing this issue for now, please feel free to re-open if there are more questions, @RicardoGomesIST!
