### ISSUE TITLE
Temperature of R-C model out of bounds

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#2940]
Hello,

since a few days I can't calculate the energy demand of any buildings. The following message occures:
_Temperature in RC-Model of building B1000 out of bounds! First occured at timestep = 5472. The results were Tint = 9939248.224180229, theta_c = 7322208.736326089, theta_m = 2581702.6242668643, Check building geometry and internal loads! Building might be too small in size or architecture parameter Hs_ag = 1.0 might be too small for this geometry. Current bounds of range for RC-model temperatures are between -30.0 and 50.0._

Same Error message was discussed in: #2567 

I'm using version 3.18.0 on a windows computer

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,

it seems like the building is overheating, as the error message described:
```Check building geometry and internal loads! Building might be too small in size or architecture parameter Hs_ag = 1.0 might be too small for this geometry.```

For trouble shooting, you can first try to delete B1000 and proceed with the demand calculation.
It that works, you can now add B1000 back and check the rest of the parameters.

**Comment by Mar-Ges** [comment]
Hi @shanshanhsieh,

I  tried different combinations of buildings and parameters - finally I changed the weatherfile to an original one, now it is working again. (I'll keep on searching a mistake in my weatherfile )

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,

glad to hear that the trouble shooting is progressing on your end!
yea, checking the weather files are also a point not to miss ; )

good luck!
