### ISSUE TITLE
Workflow Questions

### ISSUE THREAD

**Issue by ConorKN** [architecture-building-systems/CityEnergyAnalyst#2946]
_I will be continuously posting questions concerning my workflows on this issue..._

Is there a way of editing a database via my YAML files or must this be done via dashboard / inputs folders (Microsoft Access,...) ?

**Comment by shanshanhsieh** [comment]
by YAML files do you mean if there is a function that you can include in a workflow to update databases?

it depends a bit on which database are you updating.
in general, it is done via dashboard or direct editing with any editing software

**Comment by daren-thomas** [comment]
it's relatively easy to write a plugin that can update databases for you - any cea plugin automatically becomes usable from the yaml workflows.

**Comment by ConorKN** [comment]
@shanshanhsieh @daren-thomas 
Yes. I was thinking, instead of working with the input editor, it would be more efficient to update the archetypes/assemblies/components, when testing multiple scenarios. The idea was that I could create standards for each scenario in advance and then swap them around as I wished with my workflow.

can multiple plugins be used at the same time? I am already using the gwr-mapper...

**Comment by shanshanhsieh** [comment]
yes, you can have multiple plug-ins:
https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2924#issuecomment-772653473

**Comment by shanshanhsieh** [comment]
closing this issue for now, please feel free to re-open when there are more questions, @ConorKN!
