### ISSUE TITLE
model calibration: how do I update the typology without changing the architecture?

### ISSUE THREAD

**Issue by AWillmann** [architecture-building-systems/CityEnergyAnalyst#2955]
Hi, I am currently trying to calibrate the CEA model to match the consumption data of an existing campus site. Therefore, I would like to change the typology of individual buildings, i.e. introducing serverrooms, without changing my user input architecture data, i.e. specific construction data. Is that possible? 
What I tried: updating the typology (second use 20% serverroom) and saving the changes to the input editor. However, the total demand file after re-simulating the energy demand does not show any E_data consumption. It does not take the added serverroom into account. I am afraid that - if I re-run the archetype helper - all my user input data of the building skin will be lost...

**Comment by shanshanhsieh** [comment]
Hi @AWillmann,

In Archetypes Mapper, you can customize the database and building you would like to update.
I would suggest you to make a copy of the current scenario and play around with it.
[Here](https://cityenergyanalyst.com/blog/2020/4/23/working-with-cea-databases-part-1) you can find which databases in a scenario(case study) are modified by archetype mappers.

![image.png](https://images.zenhubusercontent.com/57b4452fe40e5714b16d75a2/09e37802-595d-4c86-9b77-ec86db4642f1)

Side note: if you are building a database that could be generalized for most buildings in the city/region you are studying, you can try to build a customized following this [instruction](https://cityenergyanalyst.com/blog/2020/4/23/working-with-cea-databases-part-3)
