### ISSUE TITLE
CEA Dashboard generates an error after first time installation

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#2958]
I just downloaded and installed the CEA new version, which I downloaded from the website.
I received the below error when I tried to open the dashboard for the first time.

![image.png](https://images.zenhubusercontent.com/57b431eee40e5714b16d74ed/89fa2dec-7454-4fed-833d-52be957d2d1e)

**Comment by shanshanhsieh** [comment]
hi @amraladdin , 
could you please try the installation again after making sure the folder is clean?
Please first uninstall CEA, and then make sure `Documents\CityEnergyAnalyst` is deleted before starting a new installation.

**Comment by martin-mosteiro** [comment]
@amraladdin I had similar issues a while back, the solution suggested by @shanshanhsieh worked for me!

**Comment by shanshanhsieh** [comment]
on the other hand, please note that if you are installing v3.22, only the developer version is working.
see #2971 , v3.23 will come next week!

**Comment by amraladdin** [comment]
Perfect! Thank you for the update! I'll await the v3.23 then :)

**Comment by shanshanhsieh** [comment]
release v3.23 is in the spring backlog now in #2975
