### ISSUE TITLE
Not able to import/export database editor

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2960]
**Describe the bug**
When clicking import or export button inside the database editor on the dashboard, it returned "success", but no action was taken.

**To Reproduce**
1. Go to dashboard, open a project
2. Go to database editor
3. export database editor
4. check if anything is being exported

**Hardware (please complete the following information):**
 - OS and version: Windows10
 - v3.22

**Comment by shanshanhsieh** [comment]
@reyery please indicate the part of the code that we should be testing, thanks!

**Comment by reyery** [comment]
I just realised the endpoint was removed for some reason. I have a feeling I did that by accident. Putting it back in should solve it.

https://github.com/architecture-building-systems/CityEnergyAnalyst/commit/61dba927b53824551840302020b1f93c55b684c8#diff-11f98fdf1a51cb7bfe4fb01cb840a2eccc4676fc03de2d8d3561b3b25d4f40abL401-L416
