### ISSUE TITLE
Issues in databases for Singapore

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2961]
the CONSTRUCTION_STANDARD.xlsx presents repeated STANDARDs.

Additionally, ASSEMBLIES-WALL (in ENVELOPE.xls) contains the column U_base which is now taken from the FLOOR component.

**Comment by shanshanhsieh** [comment]
@lguilhermers, thanks for the solve! this issue will be closed after the PR is merged!
