### ISSUE TITLE
changing text attributes in edit multiple selection does not work

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2964]
**Describe the bug**
When trying to edit parameters for multiple buildings in the edit selection window (input editor), only numerical parameters can be changed. I remember having this issue before but could not find the issue here

**To Reproduce**
1. Go to a scenario and select multiple buildings
2. Click on the edit selection in a tab that has text parameters  (e.g., typology or architechture)
3. Try to edit text parameters

**Screenshots**
![image](https://user-images.githubusercontent.com/50981039/116523369-bff0e480-a908-11eb-8a8b-cac336c03fff.png)

 - Version of CEA you are using [v. 3.32]

**Comment by shanshanhsieh** [comment]
it is working on cea v3.30.0
