### ISSUE TITLE
PCM thermal storage for district Cooling

### ISSUE THREAD

**Issue by jimenofonseca** [architecture-building-systems/CityEnergyAnalyst#2973]
**Describe the feature you would like to have**
We will be integrating a PCM (phase change material) thermal storage for the district cooling system of CEA. THis is part of the DUCT modeling effort of Cooling Singapore. I will be supporting this effort in the next three months :-)

@shanshanhsieh, I wonder if your have come across about ideas of an ice thermal storage that we can easily integrate into CEA. Here are the top options we have found so far for the singaporean context:

1.	2021, Stefano Mazzoni, Jia Yin Sze, Benedetto Nastasi, Sean Ooi, Umberto Desideri, Alessandro Romagnoli. A techno-economic as-sessment on the adoption of latent heat thermal energy storage sys-tems for district cooling optimal dispatch & operations, Applied Ener-gy.
2.	2020, Y.L. Shao, K.Y. Soh, Y.D. Wan, M. Kumja, Z. Khin, M.R. Islam, K.J. Chua, Simulation and experimental study of thermal storage sys-tems for district cooling system under commercial operating condi-tions, Energy,
3.	2019, Stefano Mazzoni, Sean Ooi, Benedetto Nastasi, Alessandro Romagnoli, Energy storage technologies as techno-economic parame-ters for master-planning and optimal dispatch in smart multi energy systems, Applied Energy.
4.	2017, Gabriele Comodi, Francesco Carducci, Jia Yin Sze, Nagarajan Balamurugan, Alessandro Romagnoli, Storing energy for cooling de-mand management in tropical climates: A techno-economic compari-son between different energy storage technologies, Energy,

What do you think of this?

**Describe the end purpose of this feature**
It will simulate an ice thermal storage system as part of the district cooling simulation of CEA. this feature will add a quasi-steady-state model to do this.

**Describe the end-user of this feature**
A researcher (Future position for district cooling expert for Cooling Singapore).

**Comment by jimenofonseca** [comment]
@shanshanhsieh I wonder if you have any other model I should consider?

**Comment by shanshanhsieh** [comment]
@jimenofonseca , this is a great addition to the technology library!
i dont have any reference specifically for ice storage, but i have quickly looked through the references you provided. 
the model formulation from Mazzoni (1&3) could be compatible to CEA, and the details are well documented
it is definitely a good place to start.
let me know how it goes : )

**Comment by jimenofonseca** [comment]
Hi Shanshan!, yes, i am finishing now the development and about to start to build the unit-tests. Still it can take one month more to finish.

**Comment by MatNif** [comment]
@jimenofonseca As discussed today I found a bug in storage_tank_pcm.py as I ran a test on 3 buildings in Singapore using Branch 2973.

![image](https://user-images.githubusercontent.com/93093343/140319676-f690bae3-a050-4e6e-9fce-e3c57f97d1bf.png
[TestRun_Branch2973.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/7475023/TestRun_Branch2973.zip)
)

**Comment by jimenofonseca** [comment]
@MatNif perfect. It now runs. you just need to sync. You will get some errorrs of a negative COP, but that is another issue different from the storage. It has to do with the Vapour Compression Chillers. Maybe A new issue can be opened for that.

Please try on your end, and aim to check graphs etc. before our next meeting if possible. Thanks!

**Comment by MatNif** [comment]
@jimenofonseca just tried it. Works like a charm. Thank you for fixing the issue and see you tomorrow.

**Comment by shanshanhsieh** [comment]
hi @MatNif ,
could you please give an estimate on when we could start testing this? thanks!

**Comment by MatNif** [comment]
Hi @shanshanhsieh,
I am currently going through the optimization code and refactoring it where I believe it is needed. In that process will also need to go through the technologies. So I will be able to go through the relevant scripts next week.
However, I have not yet managed to figure out how to test this specific part of the script using the CEA dashboard. Do you have ideas?
