### ISSUE TITLE
database migrator should also check "outputs" folder

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2977]
After changing naming in the database via #2957, the outputs in **outputs/data/occupancy** and **outputs/data/demand** are not usable.
It would be great if the database migrator could resolve this by either:
1. change the column names in both folders if exist
2. send out a warning message to rerun these two scripts if results exist

**Comment by shanshanhsieh** [comment]
@martin-mosteiro  @reyery do you have any comment?

**Comment by reyery** [comment]
@shanshanhsieh would just renaming the columns be enough, since the results are not changed if I understand it correctly.

**Comment by shanshanhsieh** [comment]
@reyery , yes, only the column names are different. so renaming columns would be enough.
just wondering if the naming, database migrator, is also changing output data would be too confusing...

**Comment by reyery** [comment]
Yeah, it could be confusing for some people. Maybe we could just rename to `data-fixer` or something similar.

**Comment by martin-mosteiro** [comment]
Hey, sorry, this was in my junk mail for some reason 🤗 I can add that feature to the database migrator. If not, can also help with creating a `data-fixer` as needed.

**Comment by shanshanhsieh** [comment]
@martin-mosteiro that would be cool if you could add that function to change those column names in the output folder.
as for the name, how about just change it to `data migrator`, so it's not specific to the database
