### ISSUE TITLE
Energy demand does not re-calculate Edata

### ISSUE THREAD

**Issue by AWillmann** [architecture-building-systems/CityEnergyAnalyst#2978]
After adding a serverroom as a second use, the building energy demand forecast does not calculate Edata. I have re-run the archetype mapper for internal loads, comfort, air-conditioning, supply and schedules. In the schedules input the server use does appear as "1" for 24/7. However, after re-running the total electricity demand, there is no consumption for the server. What did I do wrong?

**Comment by shanshanhsieh** [comment]
@AWillmann, 

i will recommend the following steps:
1. In Database Editor>ARCHETYPES>USE-TYPES edit or add a USE-TYPE with data center load.
- please make sure to specify the load in both **Properties (Ed_Wm2)** and **Schedules** section for SERVERS.
- please note that Edata_Wm2 is related to Es: Fraction of gross floor area with electrical demands.
2. In Input Editor, assign the USE-TYPE with data center load to buildings.
3. In Archetypes-mapper, update **schedules** and **internal-loads** for buildings you wish to update
4. Run Building Schedules for buildings you wish to update
5. Run Building Energy Demand

I am guessing that you might be missing the Ed_Wm2 in step 1 or missing step 4.
hope this explanation is helpful.

**Comment by AWillmann** [comment]
Hi @shanshanhsieh, I did exactly the steps you described - the Ed_Wm2 in the internal loads input section is 20 Wm2 in my case (also 20% of the gross floor area are servers) - however, the totaldemand.csv gives 0.0000000000000 MWhyr as a result. Do you have any other idea how to solve this?

**Comment by AWillmann** [comment]
it´s working now - did you change something?
