### ISSUE TITLE
Qww and NGww - what it is the relation?

### ISSUE THREAD

**Issue by RicardoGomesIST** [architecture-building-systems/CityEnergyAnalyst#2979]
How is NG_ww_MWhyr calculated?

 I believed it was the Qww_MWhyr affected by the efficiency of the supply system (using NG).

In my case I have all the buildings with the same system (supply= efficiency of 0.8 -natural gas-fired boiler) but the ratio Qww/NGww varies for all the buildings.

ty!!

 - Windows 10]
 - Version of CEA 3.7]

**Comment by RicardoGomesIST** [comment]
My bad, the relation is: Qww_sys_MWhyr/ supply efficiency = NG_ww_MWhyr 
So, what is the: 
 Qww_MWhyr - DHW heating demand?

domestic hot water heating demand? Sorry, I dont get it
TY!

**Comment by shanshanhsieh** [comment]
hi @RicardoGomesIST,

Qww_MWhyr is the heating demand calculated with mcp(Tdhw-Tfreshwater)
Qww_sys_MWhyr is Qww_MWhyr  + loss in the system

hope it is clear now!
