### ISSUE TITLE
Pareto curve - Today's system shows no emissions

### ISSUE THREAD

**Issue by buechlerc** [architecture-building-systems/CityEnergyAnalyst#2989]
**Describe the bug**
I plotted the Pareto Curve and the Today's system is situated at point 0 (Equivalent annaual costs)/0 (GHG Emissions)
I think at least the emissons can't be zero

**To Reproduce**
1. set up a new scenario with an area in Switzerland (CH)
2. Run all the Scripts with Default settings. 
3. Go to 'Dashboard'
2. Click on 'Add plot' -> Category: Optimization, Plot-> Pareto curve

**Expected behaviour**
I would expect low annual costs, but high GHG emission for the today's system, since the default supply system for the chosen area is an oil-fired boiler for in everey building.

**Screenshots**
![issue_pareto](https://user-images.githubusercontent.com/85232620/120479539-57d16a80-c3ae-11eb-9503-28a58cbad296.png)

**Hardware (please complete the following information):**
 - OS and version:  Windows 10
 - Version of CEA you are using: v. 3.22.0

**Comment by ShiZhongming** [comment]
We are phasing out this version of optimisation script completely. We will also update the visualisation functionality accordingly. Hence, I close the issue as currently we do not have the capacity to maintain the older optimisation script.
