### ISSUE TITLE
Built together buildings

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#2995]
I want to consider "built together" buildings in my quarter.
Does CEA take the connected wall into account? Or do I have to do some manual changes?

For example:
![image](https://user-images.githubusercontent.com/73158684/123383560-a334fe00-d593-11eb-9e15-e1fffa69ed08.png)

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,

It is possible to simulate this geometry in the CEA.
We are currently doing some fixes for building intersections in #3003, you might want to check out the latest version when that issue is solved.

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,

In the case of buildings with intersecting walls, It is recommended to run solar radiation with the option "consider-intersections"=True.
This flag is only functioning after merging pull request #3006.
Please update the master branch if you are using the developer version.
Or download our next release (v3.26) if you are using the non-developer version.
