### ISSUE TITLE
Heated area below ground

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#2996]
We want to simulate a quater with heated area below ground - do I need to consider the "insulating effect" of ground manually or is it inclued to the CEA-calculations?

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,

In `architecture.dbf`, the type of basement floor is defined with `type_base` for each building.
The code is connected to the material properties specified in `technology/assemblies/ENVELOPE.xls`, you can also add new floor types there.

Hope this helps!

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,

we are closing this issue for now, please re-open it if anything is unclear.
