### ISSUE TITLE
"consider-interactions" Leads to Failed Radiation Sim if No Intersections Exist

### ISSUE THREAD

**Issue by justinfmccarty** [architecture-building-systems/CityEnergyAnalyst#3001]
**Describe the bug**
During radiation simulation the geometry builder encountered a failure to complete and ended the simulation prematurely. Suspect it is due do the "consider-interactions" parameter.

**To Reproduce**
Was running the main radiation script on three buildings in Altstetten (B1003, B1006, B1009), with "consider intersections" on. Tried on both multiprocess and single-processing. Simulation completes:
- terrain intersection (sidenote: would be cool to cache this for future scenario iterations), 
- geometry of surrounding buildings

Appears to fail when trying to intersect buildings. "TypeError: 'itertools.repeat' object is not subscriptable"

If I run the same configuration without "consider intersections" there is no issue. I checked to see if the 3 buildings are intersecting and they do not. I suspect a simple flow control statement would solve this.

**Expected behaviour**
Would expect the CEA to finish the simulation.

**Screenshots**
<img width="1106" alt="Screenshot 2021-07-19 at 12 44 21" src="https://user-images.githubusercontent.com/44881937/126149156-1e9cd510-238e-44a7-b0c3-e7493ee0ef6d.png">

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - Version of CEA you are using: 3.24.0

**Comment by shanshanhsieh** [comment]
Hi @justinfmccarty,
Could you please provide a link to your case (hopefully small), so that we could reproduce the error?
It is potentially linked to #2944 , maybe @jimenofonseca has some inputs on this?

**Comment by jimenofonseca** [comment]
Yep...i solved that problem in the branch aiming to solve 2944. Check out the changes made to the radiation scripts in that branch, and maybe test locally in a new branch. I think the fix is there.

**Comment by justinfmccarty** [comment]
Hey @shanshanhsieh, I just copied a version of the altstetten model that I found in the chair's cloud project folder --> "/Volumes/arch_ita_schlueter/03-Research/01-Projects/30_VILLE/CEA_Projects/Altstetten/Simulations/09062021-altstetten".  Recommend just testing on a few buildings.

@jimenofonseca, I went into the branch you mentioned and copied the updated [geometry-generator.py](https://github.com/architecture-building-systems/CityEnergyAnalyst/commit/f66e1157e6e93d65173d5325c37ec0b14b0da9ab ) into my local CEA. It seems to have fixed the problem that I described above. 

I will let all of Altstetten run overnight with the fix to see what the difference ends up being due to interactions being turned on.

**Comment by shanshanhsieh** [comment]
@justinfmccarty Please let us know if that could be the fix so that maybe @jimenofonseca could make a PR that only solves this issue.
Thank you both! : )

**Comment by justinfmccarty** [comment]
> @justinfmccarty Please let us know if that could be the fix so that maybe @jimenofonseca could make a PR that only solves this issue.
> Thank you both! : )

@shanshanhsieh, Using the geometry-generator.py file that @jimenofonseca patched works. I was curious to the impact using the intersections so I look at a subset of Altstetten. Ran 2 simulations, one with "consider-intersections" as True and one as False.

Looking at the generated geometry files. In buildings that don't have any intersecting/adjacent walls there is 0 difference in total wall area between the two scenarios (as expected). In buildings where there were intersecting/adjacent walls there is a difference. (consider_intersections_true - consider_intersections_false):

walls_east_m2    -34.650833
walls_north_m2   -51.601667
walls_west_m2    -34.650000
walls_south_m2   -62.318333

So definitely seeing the impact of "consider-interactions" in geometry.

**Comment by jimenofonseca** [comment]
fixed in the new PR. Yep. I recommend to run it always, specially in Europe with so many terracehouses here and there :-)

**Comment by shanshanhsieh** [comment]
thank you, @jimenofonseca for the PR and @justinfmccarty for testing!
PR #3006 is merged now.
