### ISSUE TITLE
Unable to install CEA 3.24.0 on Windows 10

### ISSUE THREAD

**Issue by lloydejw** [architecture-building-systems/CityEnergyAnalyst#3012]
**Describe the bug**
When running the installer for CEA 3.24.0, I get the message "Installation Aborted: Setup was not completed successfully. " Under details the error message is
```
pip install cityenergyanalyst==3.24.0 returned 255
Could not install CityEnergyAnalyst 3.24.0
```

**To Reproduce**
Run the CEA 3.24.0 installer 

**Expected behaviour**
Successful installation

**Screenshots**
![ceaError](https://user-images.githubusercontent.com/87302747/128831102-e2485b93-c3c7-4aef-8eb2-7733ddb3bdc7.PNG)

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10] Windows 10
 - Version of CEA you are using [e.g. v. 2.31.1] v. 3.24.0

**Comment by shanshanhsieh** [comment]
Hi @lloydejw ,

Thank you for submitting the issue.
Currently, we are not able to reproduce this error from our side.
In our experience, the installation is always a bit tricky if the destination folder is inside one of the synced folders (e.g., dropbox, onedrive...).
If possible, could you please try out the installation again in the same path as indicated in this guide?
the default path is `C:\Users\windows-user\Documents\CityEnergyAnalyst`
https://daren-thomas.github.io/installing-cea-on-windows-part-1/

**Comment by lloydejw** [comment]
Hi @shanshanhsieh 
Thanks for the suggestion. Removing dropbox from syncing my Documents folder solved the issue and the installation has now worked successfully.
