### ISSUE TITLE
new geometries don´t have a typology - archetype mapper does not run

### ISSUE THREAD

**Issue by AWillmann** [architecture-building-systems/CityEnergyAnalyst#3014]
After adding new geometries to the shp-file in QGIs (tutorial from cea blog), the geometries are part of the map/ input editor in CEA but as there is no typology for the new buildings, the archetype mapper does not run - no building properties are created. How can I solve the problem? 

I have tried to modify the dbf-files by adding the rows for the new buildings - this leads to "unknown error" and after altering the typology-dbf  CEA does not even show the map anymore.

**Comment by shanshanhsieh** [comment]
Dear @AWillmann,

Sorry for the late reply.
After adding new buildings to `zone.shp`, you will also have to add the new buildings to `typology.dbf` before proceeding to archetype mapper.

Here is an example script on how to modify `typology.dbf`: https://nextcloud.ethz.ch/s/aqWprdDob6AjQyk
The script is using CEA functions, therefore, it is recommended to access the script via CEA API.
It can be easily done via typing `jupyter notebook` in the CEA console, more detailed description can be found here: https://cityenergyanalyst.com/blog/2019/8/1/gabriel
