### ISSUE TITLE
Workflow for all scenarios of a project

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#3018]
How can I apply the same workflow for all scenarios of a project?

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,

It is possible to automate a series of simulations through the `cea workflow` command. 
Please refer to this blog post and this tutorial to the steps.

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,
i will close this issue for now, and please feel free to re-open it if you have more questions regarding the workflow.
