### ISSUE TITLE
What causes the RC model to provide extremely high temperatures?

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#3043]
**Describe the bug**
Building overheating is caused generally when the geometry (GFA) or Hs_ag are too small. 
Nonetheless, we have observed buildings with fairly reasonable values to reach above 50 (recently I ran a case study with Tint = 65). This seems unreasonable and might be worth investigating what causes that.

@martin-mosteiro added that the RC model properties are scaled by Hs, and so are the heat gains.

**Comment by shanshanhsieh** [comment]
@lguilhermers any new observations on this?

**Comment by lguilhermers** [comment]
Not really, as I deactivated the error to be able to continue using the model in #2998 .
I should be able to reactivate the error to collect a few cases with temperature overshooting. Would that be useful?

**Comment by lguilhermers** [comment]
I did a few simulations to test the impact of the error on the GRID_cs. 
For that, I tested different HS_ag around the threshold that gives the error (which was pretty small for this case, around 3%) and checked what was the annual GRID and GRID_cs when I turned off the error. What I got was pretty linear results, with a small discontinuity in the specific point that the error happens.
See results below (red dots indicate values that would throw a warning, if it was turned on)
![image](https://user-images.githubusercontent.com/50981039/154014145-6554ee8c-f913-4ca7-b754-c3dcc2623846.png)

I think it still needs more tests to make more concrete conclusions, but it seems that the error itself is not very problematic when you look into long periods.

**Comment by lguilhermers** [comment]
It can also be the case that with Hs_ag = 0.04, the RC temperature is not enough to trigger the warning, but is still higher than usual and impacting the calculations (e.g., 49,9 ºC doesn't trigger the warning but 50.1ºC does). I am not able to judge that with the simulations above.

**Comment by shanshanhsieh** [comment]
Thank you @lguilhermers for testing the results!

As discussed, when specifying a small portion of the conditioned area (Hs_ag < 0.05), high internal temperatures might occur. This is the limitation to the single zone rc model currently used in the CEA.

In the CEA script, we approximate the heat gains proportionally to the conditioned area. However, this approximation might still lead to a relatively high heat gain compared to the small conditioned area.
Here is how the heat gains are being approximated: https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/6d6a1a1369089d3da08e32d7144d6e4ee0592e64/cea/demand/rc_model_SIA.py#L586

Closing this issue for now, but achieving the discussion for future reference.
