### ISSUE TITLE
Welcome Mathias Niffeler to the dev Team

### ISSUE THREAD

**Issue by jimenofonseca** [architecture-building-systems/CityEnergyAnalyst#3055]
Hey @shanshanhsieh let's welcome @MatNif to the dev team. 

He will be soon joining cooling Singapore (team mate of @lguilhermers). 

He will be our go-to-go person for district cooling development based in Singapore.

I introduced him today to CEA devs and operations including:

- The scrum process (planning, sprints, reviews etc.)
- How is our governance. Roles and responsabilities.
- How does zenhub, Kanban board works.
- How to create issues, do PRs, review code. 
- How to build stuff in CEA.

It will be great if you get in contact and start his involvemnet into the sprint and stand-up sessions too! Thanks!

Best, Jimeno

**Comment by MatNif** [comment]
Hi Shanshan

Yes, it's good to hear from you again as well :) and I'm really looking
forward to joining the CEA development team.
I'll be using this E-mail address ***@***.***) for now and I'll
be switching to ***@***.*** as soon as I officially start
working at the SEC on 25th November.
But that means that I'll still be using this E-mail address for the next
scrum, so please send all the additional details this way for now.

Thank you and best regards
Mathias



Am Fr., 29. Okt. 2021 um 11:18 Uhr schrieb Shanshan Hsieh <
***@***.***>:
