### ISSUE TITLE
Data Migrator for Assemblies folder

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#3057]
**Describe the feature you would like to have**
We have changed the format of excel file from .xls to .xlsx in #3026.
We need to build a data migratory to detect and update the database for users with old files.

**Describe the end purpose of this feature**
- When running scenarios with old database, an error message should show up and remind the user to use the data migrator.
- The data migratory should help users to update the format of database but keep the original content.

**Provide Aditional information if possible**
Here is an example from @martin-mosteiro : https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/8618d8c2a824a2383f938109a7d154c977b099ff/cea/datamanagement/data_migrator.py#L148-L248

**Comment by ShiZhongming** [comment]
This has been two years old and I guess no users are using the xls database. Hence, I am closing it.
