### ISSUE TITLE
Error message when setting the weather file in CEA V3.24.0

### ISSUE THREAD

**Issue by ClearKet** [architecture-building-systems/CityEnergyAnalyst#3058]
When setting the new project I've selected "Generate new imput files using tools" in Imput section.
I expected to manage setting the epw. weather file.
But when selelcting the manage setting weather icon an error message appears specifying "Something went wrong with CEA" with no details adde
![Im](https://user-images.githubusercontent.com/93820259/140606388-832d2325-d7e9-4b14-bc59-84594630851f.png)

**Comment by shanshanhsieh** [comment]
Hi @ClearKet

Please follow these steps to see more information about the occurred error:

    open CEA Console and type cea dashboard to start the backend of the CEA Dashboard
    open the CEA Dashboard application. Please repeat the actions in the Dashboard that led to the error, and send us the information from the CEA Console.

This way, we will be able to see what is causing the error. Please note, that you should have a developer version of CEA installed to be able to use CEA Console. Let us know if you have questions.

**Comment by shanshanhsieh** [comment]
Hi @ClearKetHi,

We will close this issue for now.
Please re-open it if the issue persists.
