### ISSUE TITLE
Include Link to youtube Videos of CEA

### ISSUE THREAD

**Issue by jimenofonseca** [architecture-building-systems/CityEnergyAnalyst#3059]
@shanshanhsieh maybe we can put a link on the menu of CEA website to link users to videos of CEA related work. We can reactivate the CEA youtube channel for this. Including the video of Jose's work with CEA. What do you think?

**Comment by shanshanhsieh** [comment]
Hi @jimenofonseca ,

Thanks for the idea. I am currently working with the communication specialist from the chair to revamp the website.
We will take this into account.

**Comment by shanshanhsieh** [comment]
this is being addressed in the new website
