### ISSUE TITLE
calibration plugin installation error

### ISSUE THREAD

**Issue by RicardoGomesIST** [architecture-building-systems/CityEnergyAnalyst#3060]
Hi, 
I tried to install the cea calibration plugin (https://github.com/lguilhermers/calibration_plugin).
I considered the instructions in the command in the CEA console:

`git clone https://github.com/architecture-building-systems/cea-plugin-template.git DESIRED_PATH`

`pip install -e PATH_OF_PLUGIN_FOLDER`

 this gave an error because "this folder does not have the setup.py" file, so I tried 2 ways:

1. I run only considering the "DESIRED_PATH" since there it has the setup.py file 
or
2. I copied pasted the file: "setup.py" to "DESIRED_PATH + 'cea-template-plugin'" 

both installed successfully:
```
Obtaining file:///C:/Users/Ricardo/OneDrive%20-%20Universidade%20de%20Lisboa/Ambiente%20de%20Trabalho/DIA%20ABERTO%20TAGUS/CEA/Oeiras_CEA/calibration
Installing collected packages: cea-plugin-template
  Running setup.py develop for cea-plugin-template
Successfully installed cea-plugin-template
```

 but both gave me an error when trying the next step:

```
λ pcea-config write --general:plugins cea_calibration.CalibrationPlugin
Traceback (most recent call last):
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-config.exe\__main__.py", line 7, in <module>
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\cli\cea_config.py", line 42, in main
    parameter.set(parameter.decode(parameter.replace_references(value)))
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\config.py", line 658, in decode
    return [instantiate_plugin(plugin_fqname) for plugin_fqname in plugin_fqnames]
  File "C:\Users\Ricardo\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\plugin.py", line 268, in instantiate_plugin
    plugin_fqname=plugin_fqname, msg=ex.message))
ValueError: Could not instantiate plugin cea_calibration.CalibrationPlugin (No module named cea_calibration)
```

CEA version 3.18
WIndows 10

**Comment by shanshanhsieh** [comment]
Hi @RicardoGomesIST ,

Great to know that you are interested in using the CEA plugins!
I have reported this issue to the owner (@lguilhermers ) of the plugin here: https://github.com/lguilhermers/calibration_plugin/issues/2#issue-1053489427

Each CEA plugin is maintained by its owner independently from the CEA core repo.
Please feel free to contact the plugin owner via creating issues in their repo if you have specific questions for any plugin.

**Comment by lguilhermers** [comment]
@RicardoGomesIST, I have replied to you in the plugin page. Thanks!
