### ISSUE TITLE
Automized Workflow: Problem with temp data of solar radiation

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#3068]
As part of a research project I'm (trying to) automize a workflow with different scenarios. 
At the moment I'll get a problem with temp data of solar radiation. 
Depending on the computer I reach diffenet numbers of scenario until I get the Error

_FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\Users\\Geske\\AppData\\Local\\Temp\\testscenario5_radiation_geometry_pickle\\zone'_

**Comment by shanshanhsieh** [comment]
@Mar-Ges, this might happen when you are running the same scenario (testscenario5) at the same time.
maybe you could try clean up the Temp folder (`C:\Users\Geske\AppData\Local\Temp`) manually and try again.
also, please make sure all scenarios have unique names, and only one scenario is being run at a time.
let us know if this helps.

**Comment by Mar-Ges** [comment]
Hi @shanshanhsieh,

I named my scanarios by numbers (all unique: testscenario0, testscenario1,....).
And unfortunately I already tried to clean the Temp folder - still the same Error (just a bit later) :(

Here the full workflow-message:


Workflow step 242: script=radiation
================================================================================
Running radiation with args {'scenario': 'C:\\Users\\Geske\\Desktop\\projectsensitivity\\testscenario34', 'multiprocessing': True, 'number_of_cpus_to_keep_free': 1, 'debug': False, 'buildings': ['B1000', 'B1001', 'B1002', 'B1003'], 'use_latest_daysim_binaries': True, 'albedo': 0.2, 'roof_grid': 10, 'walls_grid': 200, 'zone_geometry': 2, 'surrounding_geometry': 5, 'consider_floors': True, 'consider_intersections': False, 'rad_ab': 4, 'rad_ad': 512, 'rad_as': 32, 'rad_ar': 20, 'rad_aa': 0.15, 'rad_lr': 8, 'rad_st': 0.5, 'rad_sj': 0.7, 'rad_lw': 0.05, 'rad_dj': 0.7, 'rad_ds': 0.0, 'rad_dr': 0, 'rad_dp': 32, 'daysim_bin_directory': 'c:\\users\\geske\\desktop\\cityenergyanalyst\\dependencies\\daysim\\bin64', 'n_buildings_in_chunk': 100, 'write_sensor_data': True}
City Energy Analyst version 3.18.0
Running `cea radiation` with the following parameters:
- general:scenario = C:\Users\Geske\Desktop\projectsensitivity\testscenario34
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- radiation:buildings = ['B1000', 'B1001', 'B1002', 'B1003']
  (default: ['B1000', 'B1001', 'B1002', 'B1003'])
- radiation:use-latest-daysim-binaries = True
  (default: True)
- radiation:albedo = 0.2
  (default: 0.2)
- radiation:roof-grid = 10
  (default: 10)
- radiation:walls-grid = 200
  (default: 200)
- radiation:zone-geometry = 2
  (default: 2)
- radiation:surrounding-geometry = 5
  (default: 5)
- radiation:consider-floors = True
  (default: True)
- radiation:consider-intersections = False
  (default: False)
- radiation:rad-ab = 4
  (default: 4)
- radiation:rad-ad = 512
  (default: 512)
- radiation:rad-as = 32
  (default: 32)
- radiation:rad-ar = 20
  (default: 20)
- radiation:rad-aa = 0.15
  (default: 0.15)
- radiation:rad-lr = 8
  (default: 8)
- radiation:rad-st = 0.5
  (default: 0.5)
- radiation:rad-sj = 0.7
  (default: 0.7)
- radiation:rad-lw = 0.05
  (default: 0.05)
- radiation:rad-dj = 0.7
  (default: 0.7)
- radiation:rad-ds = 0.0
  (default: 0.0)
- radiation:rad-dr = 0
  (default: 0)
- radiation:rad-dp = 32
  (default: 32)
- radiation:daysim-bin-directory = c:\users\geske\desktop\cityenergyanalyst\dependencies\daysim\bin64
  (default: C:\Users\Geske\Desktop\CityEnergyAnalyst)
- radiation:n-buildings-in-chunk = 100
  (default: 100)
- radiation:write-sensor-data = True
  (default: True)
Using Daysim binaries from path: c:\users\geske\desktop\cityenergyanalyst\dependencies\daysim\bin64
Using Daysim data from path: c:\users\geske\desktop\cityenergyanalyst\dependencies\daysim\lib
verifying geometry files
zone: C:\Users\Geske\Desktop\projectsensitivity\testscenario34\inputs\building-geometry\zone.shp
surroundings: C:\Users\Geske\Desktop\projectsensitivity\testscenario34\inputs\building-geometry\surroundings.shp
Getting geometry materials
Creating 3D geometry and surfaces
Saving geometry pickle files in: C:\Users\Geske\AppData\Local\Temp\testscenario34_radiation_geometry_pickle
Standardizing coordinate systems
Reading terrain geometry
Creating 3D building surfaces
Calculating terrain intersection of building geometries
Using 5 CPU's
Calculation of terrain intersection for building 1 completed out of 4
Calculation of terrain intersection for building 2 completed out of 4
Calculation of terrain intersection for building 3 completed out of 4
Calculation of terrain intersection for building 4 completed out of 4
Using 5 CPU's
Calculation of terrain intersection for building 1 completed out of 8
Calculation of terrain intersection for building 2 completed out of 8
Calculation of terrain intersection for building 3 completed out of 8
Calculation of terrain intersection for building 4 completed out of 8
Calculation of terrain intersection for building 5 completed out of 8
Calculation of terrain intersection for building 6 completed out of 8
Calculation of terrain intersection for building 7 completed out of 8
Calculation of terrain intersection for building 8 completed out of 8
Generating geometry for surrounding buildings
Generating geometry for buildings in the zone of analysis
Using 5 CPU's
Generating geometry for building 1 completed out of 4
Generating geometry for building 2 completed out of 4
Generating geometry for building 3 completed out of 4multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\users\geske\desktop\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 131, in __apply_func_with_worker_stream
    result = func(*args)
  File "c:\users\geske\desktop\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 368, in calc_building_geometry_zone
    building_geometry.save(os.path.join(geometry_pickle_dir, 'zone', str(name)))
  File "c:\users\geske\desktop\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 267, in save
    os.makedirs(dir_name)
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\Dependencies\Python\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\Users\\Geske\\AppData\\Local\\Temp\\testscenario34_radiation_geometry_pickle\\zone'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 33, in <module>
    sys.exit(load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')())
  File "c:\users\geske\desktop\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 72, in main
    script_module.main(config)
  File "c:\users\geske\desktop\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 83, in main
    do_script_step(config, i, step, trace_input)
  File "c:\users\geske\desktop\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 176, in do_script_step
    run(config, py_script, **py_parameters)
  File "c:\users\geske\desktop\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 29, in run
    f(config=config, **kwargs)
  File "c:\users\geske\desktop\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 59, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\geske\desktop\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 37, in script_runner
    script_module.main(config)
  File "c:\users\geske\desktop\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 231, in main
    locator, config, geometry_pickle_dir)
  File "c:\users\geske\desktop\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 610, in geometry_main
    config, geometry_pickle_dir)
  File "c:\users\geske\desktop\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 217, in building_2d_to_3d
    repeat(consider_intersections, n))
  File "c:\users\geske\desktop\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 96, in wrapper
    result = map_result.get()
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
FileExistsError: [Errno 17] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\Users\\Geske\\AppData\\Local\\Temp\\testscenario34_radiation_geometry_pickle\\zone'

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges ,
We have fixed the bug in PR #3074 .
If you are running CEA with a developer's version, you can update from master.
Otherwise, this change will be included in the next release!
