### ISSUE TITLE
Merging 2973 with main

### ISSUE THREAD

**Issue by MatNif** [architecture-building-systems/CityEnergyAnalyst#3082]
There has been an ongoing discussion within the CEA team and CS 2.0 of whether or not to merge branch 2973 with the main branch and thereby integrating the PCM storage script in the main version of CEA.

Pro:
- PCM storage might be of interest in many different building energy systems
- branch 2973 seamlessly integrates PCM storage into the current workflow in the dashboard

Con:
- The content of the script has not yet been used in a publication (CS 2.0  might thus not be the first to publish)

@jimenofonseca : Since you wrote the entire code, can you pitch in on this? Which way would you go?

**Comment by jimenofonseca** [comment]
Well. Contractually i put a clause so the code i built at EBP belongs to SEC and it is controlled by the Director and the PI of CS.

I would suggest to talk to them (to the PI will suffice) in written just so they are in the same page and  they agree to the idea to make the code part of cea and then open spurce it.

In my view it makes little sense to not integrate it. it makes things just much easier. The value to me does not lie in the code. It lies in the cool experiments and analysis you can do with it.

In my view, there is little chance that someone else publishes studies with this code before you (the only expert who know how to habdle it and make a sense of it).

I hope this helps!

**Comment by MatNif** [comment]
Great. Thank you.

I fully agree with you on the risk of someone publishing before us. I'll see if I can get the Lead PI to see it the same way.

I'll keep you posted when we decide to publish something.
