### ISSUE TITLE
New CEA version: Problem with own database

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#3084]
With the new version 3.26. my own database creats an unknown error - its not longer visible and editable. I can start the archetypemapper - but CEA can't finish it (Architecture, intarnal-loads, indoor-comfort and air-conditioning-systems are created; supply-systems, surroundings and schedules not). 

![image](https://user-images.githubusercontent.com/73158684/152116905-42b5c9dc-eb50-47d8-93dc-9775ec6f4ad3.png)

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges , 
I also encountered the same issue an hour ago in #3083.
Sorry about this glitch, we are working on fixing this! However, it is also holiday times (lunar new year), so please expect some delays.

For now, I will recommend you to modify the `.dbf` files directly through jupyter notebook.
Here are a few hints on how to do that:
Tutorial for running jupyter notebook: https://docs.google.com/presentation/d/1D_xFrhsj90LMcFSnSCau1YfjatfhzD4mEhlnznoXbdI/edit?usp=sharing
Link to the example for dbf manipulation: https://nextcloud.ethz.ch/s/YGQtcmBajxXiDHX
Link to example of how to read building footprint form zone.shp: https://nextcloud.ethz.ch/s/2iyaxBfz8CpyA6k

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges ,
Here is a temporary GUI that you would use. (no re-installation of CEA required)
Steps to download it:
1. Go to https://github.com/architecture-building-systems/CityEnergyAnalyst-GUI/pull/62 and download from the `temp link`
2. unzip the folder
3. click on the `CityEnergyAnalyst-GUI.exe` icon inside the folder.
4. the interface will show up, and it should function as expected

Let us know if this works for you, thanks!

**Comment by Mar-Ges** [comment]
Hi @shanshanhsieh.

thank you! 
I just downgraded CEA to the previous version (now all basics are running again), but I'll try your version on my other computer and let you know how it is working

**Comment by Mar-Ges** [comment]
Hi @shanshanhsieh ,

unfortunately the time limit of the temp link is reached - can you send me a new downloadlink?
