### ISSUE TITLE
Error starting workflow with V3.26

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#3087]
I can't use my workflow-files any more. 
When I try to start them with console - I just get a "failed to create process"

**Comment by lguilhermers** [comment]
Hi @Mar-Ges,

Can you test running from the console:
`cea workflow --workflow cooling-system-current-scenario`
or
`cea workflow --workflow heating-system-current-scenario`

Those are in-built workflows. If they are working, your personalized ones should work as well.
You can find more details here: https://cityenergyanalyst.com/blog/2020/1/14/cea-workflow-how-to-automate-simulations

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,

Please let us know if you could successfully run the test @lguilhermers suggested.
I also tested several workflow files with v3.26, they seem to work fine on my side.

**Comment by shanshanhsieh** [comment]
Hi @Mar-Ges,

We also published a new release (v3.27.0), and we have tested the workflow function.
Maybe you could also give it a try.
For now, we will close this issue. Please feel free to reopen it if new errors pop up.
