### ISSUE TITLE
Exporting database and modifying building properties database 

### ISSUE THREAD

**Issue by ClearKet** [architecture-building-systems/CityEnergyAnalyst#3094]
Dear CEA group, am writing to report few issues:
1 - When manually changing the standard building properties, through the building properties database instead of doing one by one through imput editor, the software is no longer able to read the scenario and gives me "unknown error" as return.
2 - When trying creating new database in order to customize archetypes assemblies and components, with 3.24 version the software doesn't create a folder where to export the database; with the latest 3.27 version  the software is able to create a folder, but then is no longer able to read it in a different scenario.
3 - And finally, when I need to change the building features through imput editor should I only set the building standard in typology section, or should I set the whole fields?

**Comment by shanshanhsieh** [comment]
Hi @ClearKet,

Thank you for submitting the issue.

1. Please follow these steps to see more information about the occurred error:

-     open CEA Console and type cea dashboard to start the backend of the CEA Dashboard
-     open the CEA Dashboard application. Please repeat the actions in the Dashboard that led to the error, and send us the information from the CEA Console.

This way, we will be able to see what is causing the error. Please note, that you should have a developer version of CEA installed to be able to use CEA Console. Let us know if you have questions.

2. Do you mean that it is not possible to Import Database in v3.27? It would be great if you would describe the error in more detail. I have done a quick test on v3.27 and it seems fine.

3. You will only need to specify the STANDARD in the typology tab, and then the rest of the tabs would be updated according to your settings when running archetypes-mapper.

Hope this helps, looking forward to hear back from you.

**Comment by shanshanhsieh** [comment]
@ClearKet we will close this issue for now, please feel free to re-open it if the issue persists.
