### ISSUE TITLE
jobID: 1 - demand

### ISSUE THREAD

**Issue by electron1406** [architecture-building-systems/CityEnergyAnalyst#3099]
**I try to start to make a demand forecasting of a new project but it fails**

**Steps to reproduce the behaviour:**
1-Double click on CEA dashboard icon
2- I open a project, and then I choose an existing one, afterwards, I click open
3- I click on the previously selected building, then it is yellow highlighted 
4- I click on filter on selection
5-I scroll down to Demand forecasting, then Buiding Energy demand, I proceed to calculate the demand
6- I press Run Script, then jobID: 1 - demand started, finally jobID: 1 - demand encounters an error
7- As a consequence, I can not plot 
 
8- See error
jobID: 2 - demand
status: ERROR
parameters:
{
  "scenario": "C:\\Users\\tonycastillo\\Zorrotzaurre\\2020",
  "multiprocessing": true,
  "buildings": [
    "B1000",
    "B1001",
    "B1002",
    "B1003",
    "B1004",
    "B1005",
    "B1006",
    "B1007",
    "B1008",
    "B1009",
    "B1010",
    "B1011",
    "B1012",
    "B1013",
    "B1014",
    "B1015",
    "B1016",
    "B1017",
    "B1018",
    "B1019",
    "B1020",
    "B1021",
    "B1022",
    "B1023",
    "B1024",
    "B1025",
    "B1026",
    "B1027",
    "B1028"
  ],
  "number-of-cpus-to-keep-free": "1",
  "debug": true,
  "loads-output": [
    "PV",
    "GRID",
    "GRID_a",
    "GRID_l",
    "GRID_v",
    "GRID_ve",
    "GRID_data",
    "GRID_pro",
    "GRID_aux",
    "GRID_ww",
    "GRID_hs",
    "GRID_cs",
    "GRID_cdata",
    "GRID_cre",
    "E_sys",
    "Eal",
    "Ea",
    "El",
    "Ev",
    "Eve",
    "Edata",
    "Epro",
    "Eaux",
    "E_ww",
    "E_hs",
    "E_cs",
    "E_cre",
    "E_cdata",
    "Qhs_sen_shu",
    "Qhs_sen_ahu",
    "Qhs_lat_ahu",
    "Qhs_sen_aru",
    "Qhs_lat_aru",
    "Qhs_sen_sys",
    "Qhs_lat_sys",
    "Qhs_em_ls",
    "Qhs_dis_ls",
    "Qhs_sys_shu",
    "Qhs_sys_ahu",
    "Qhs_sys_aru",
    "Qcs_sys_scu",
    "Qcs_sys_ahu",
    "Qcs_sys_aru",
    "DH_hs",
    "Qhs_sys",
    "Qhs",
    "DH_ww",
    "Qww_sys",
    "Qww",
    "DC_cs",
    "Qcs_sys",
    "Qcs",
    "DC_cre",
    "Qcre_sys",
    "Qcre",
    "DC_cdata",
    "Qcdata_sys",
    "Qcdata",
    "NG_hs",
    "COAL_hs",
    "OIL_hs",
    "WOOD_hs",
    "SOLAR_hs",
    "NG_ww",
    "COAL_ww",
    "OIL_ww",
    "WOOD_ww",
    "SOLAR_ww",
    "Qcs_sen_scu",
    "Qcs_sen_ahu",
    "Qcs_lat_ahu",
    "Qcs_sen_aru",
    "Qcs_lat_aru",
    "Qcs_sen_sys",
    "Qcs_lat_sys",
    "Qcs_em_ls",
    "Qcs_dis_ls",
    "Qhpro_sys",
    "Qcpro_sys",
    "QH_sys",
    "QC_sys"
  ],
  "massflows-output": [
    "mcpww_sys",
    "mcptw",
    "mcpcs_sys",
    "mcphs_sys",
    "mcpcs_sys_ahu",
    "mcpcs_sys_aru",
    "mcpcs_sys_scu",
    "mcphs_sys_ahu",
    "mcphs_sys_aru",
    "mcphs_sys_shu",
    "mcpcre_sys",
    "mcpcdata_sys"
  ],
  "temperatures-output": [
    "T_int",
    "T_ext",
    "theta_o",
    "Tww_sys_sup",
    "Tww_sys_re",
    "Tcre_sys_re",
    "Tcre_sys_sup",
    "Tcdata_sys_re",
    "Tcdata_sys_sup",
    "Ths_sys_sup_aru",
    "Ths_sys_sup_ahu",
    "Ths_sys_sup_shu",
    "Ths_sys_re_aru",
    "Ths_sys_re_ahu",
    "Ths_sys_re_shu",
    "Tcs_sys_sup_aru",
    "Tcs_sys_sup_ahu",
    "Tcs_sys_sup_scu",
    "Tcs_sys_re_aru",
    "Tcs_sys_re_ahu",
    "Tcs_sys_re_scu",
    "Ths_sys_sup",
    "Ths_sys_re",
    "Tcs_sys_sup",
    "Tcs_sys_re"
  ],
  "resolution-output": "hourly",
  "use-dynamic-infiltration-calculation": false,
  "overheating-warning": true
}
jobID: 1 - demand
status: ERROR
parameters:
{
  "scenario": "C:\\Users\\tonycastillo\\Zorrotzaurre\\2020",
  "buildings": [
    "B1000",
    "B1001",
    "B1002",
    "B1003",
    "B1004",
    "B1005",
    "B1006",
    "B1007",
    "B1008",
    "B1009",
    "B1010",
    "B1011",
    "B1012",
    "B1013",
    "B1014",
    "B1015",
    "B1016",
    "B1017",
    "B1018",
    "B1019",
    "B1020",
    "B1021",
    "B1022",
    "B1023",
    "B1024",
    "B1025",
    "B1026",
    "B1027",
    "B1028"
  ],
  "number-of-cpus-to-keep-free": "1",
  "loads-output": [
    "PV",
    "GRID",
    "GRID_a",
    "GRID_l",
    "GRID_v",
    "GRID_ve",
    "GRID_data",
    "GRID_pro",
    "GRID_aux",
    "GRID_ww",
    "GRID_hs",
    "GRID_cs",
    "GRID_cdata",
    "GRID_cre",
    "E_sys",
    "Eal",
    "Ea",
    "El",
    "Ev",
    "Eve",
    "Edata",
    "Epro",
    "Eaux",
    "E_ww",
    "E_hs",
    "E_cs",
    "E_cre",
    "E_cdata",
    "Qhs_sen_shu",
    "Qhs_sen_ahu",
    "Qhs_lat_ahu",
    "Qhs_sen_aru",
    "Qhs_lat_aru",
    "Qhs_sen_sys",
    "Qhs_lat_sys",
    "Qhs_em_ls",
    "Qhs_dis_ls",
    "Qhs_sys_shu",
    "Qhs_sys_ahu",
    "Qhs_sys_aru",
    "Qcs_sys_scu",
    "Qcs_sys_ahu",
    "Qcs_sys_aru",
    "DH_hs",
    "Qhs_sys",
    "Qhs",
    "DH_ww",
    "Qww_sys",
    "Qww",
    "DC_cs",
    "Qcs_sys",
    "Qcs",
    "DC_cre",
    "Qcre_sys",
    "Qcre",
    "DC_cdata",
    "Qcdata_sys",
    "Qcdata",
    "NG_hs",
    "COAL_hs",
    "OIL_hs",
    "WOOD_hs",
    "SOLAR_hs",
    "NG_ww",
    "COAL_ww",
    "OIL_ww",
    "WOOD_ww",
    "SOLAR_ww",
    "Qcs_sen_scu",
    "Qcs_sen_ahu",
    "Qcs_lat_ahu",
    "Qcs_sen_aru",
    "Qcs_lat_aru",
    "Qcs_sen_sys",
    "Qcs_lat_sys",
    "Qcs_em_ls",
    "Qcs_dis_ls",
    "Qhpro_sys",
    "Qcpro_sys",
    "QH_sys",
    "QC_sys"
  ],
  "massflows-output": [
    "mcpww_sys",
    "mcptw",
    "mcpcs_sys",
    "mcphs_sys",
    "mcpcs_sys_ahu",
    "mcpcs_sys_aru",
    "mcpcs_sys_scu",
    "mcphs_sys_ahu",
    "mcphs_sys_aru",
    "mcphs_sys_shu",
    "mcpcre_sys",
    "mcpcdata_sys"
  ],
  "temperatures-output": [
    "T_int",
    "T_ext",
    "theta_o",
    "Tww_sys_sup",
    "Tww_sys_re",
    "Tcre_sys_re",
    "Tcre_sys_sup",
    "Tcdata_sys_re",
    "Tcdata_sys_sup",
    "Ths_sys_sup_aru",
    "Ths_sys_sup_ahu",
    "Ths_sys_sup_shu",
    "Ths_sys_re_aru",
    "Ths_sys_re_ahu",
    "Ths_sys_re_shu",
    "Tcs_sys_sup_aru",
    "Tcs_sys_sup_ahu",
    "Tcs_sys_sup_scu",
    "Tcs_sys_re_aru",
    "Tcs_sys_re_ahu",
    "Tcs_sys_re_scu",
    "Ths_sys_sup",
    "Ths_sys_re",
    "Tcs_sys_sup",
    "Tcs_sys_re"
  ],
  "resolution-output": "hourly",
  "multiprocessing": true,
  "debug": true,
  "use-dynamic-infiltration-calculation": false,
  "overheating-warning": true
}

**Comment by shanshanhsieh** [comment]
Dear @electron1406 , 
thank you for submitting your issue.
could you please copy the complete error message? 
it seems like there should be a few more lines below the parts you have shown and that's where the description of the error is.
thanks for your time!

**Comment by electron1406** [comment]
City Energy Analyst version 3.26.0
Running `cea demand` with the following parameters:
- general:scenario = C:\Users\tonycastillo\Zorrotzaurre\2020
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = True
  (default: False)
- demand:buildings = ['B1000', 'B1001', 'B1002', 'B1003', 'B1004', 'B1005', 'B1006', 'B1007', 'B1008', 'B1009', 'B1010', 'B1011', 'B1012', 'B1013', 'B1014', 'B1015', 'B1016', 'B1017', 'B1018', 'B1019', 'B1020', 'B1021', 'B1022', 'B1023', 'B1024', 'B1025', 'B1026', 'B1027', 'B1028']
  (default: [])
- demand:loads-output = ['PV', 'GRID', 'GRID_a', 'GRID_l', 'GRID_v', 'GRID_ve', 'GRID_data', 'GRID_pro', 'GRID_aux', 'GRID_ww', 'GRID_hs', 'GRID_cs', 'GRID_cdata', 'GRID_cre', 'E_sys', 'Eal', 'Ea', 'El', 'Ev', 'Eve', 'Edata', 'Epro', 'Eaux', 'E_ww', 'E_hs', 'E_cs', 'E_cre', 'E_cdata', 'Qhs_sen_shu', 'Qhs_sen_ahu', 'Qhs_lat_ahu', 'Qhs_sen_aru', 'Qhs_lat_aru', 'Qhs_sen_sys', 'Qhs_lat_sys', 'Qhs_em_ls', 'Qhs_dis_ls', 'Qhs_sys_shu', 'Qhs_sys_ahu', 'Qhs_sys_aru', 'Qcs_sys_scu', 'Qcs_sys_ahu', 'Qcs_sys_aru', 'DH_hs', 'Qhs_sys', 'Qhs', 'DH_ww', 'Qww_sys', 'Qww', 'DC_cs', 'Qcs_sys', 'Qcs', 'DC_cre', 'Qcre_sys', 'Qcre', 'DC_cdata', 'Qcdata_sys', 'Qcdata', 'NG_hs', 'COAL_hs', 'OIL_hs', 'WOOD_hs', 'SOLAR_hs', 'NG_ww', 'COAL_ww', 'OIL_ww', 'WOOD_ww', 'SOLAR_ww', 'Qcs_sen_scu', 'Qcs_sen_ahu', 'Qcs_lat_ahu', 'Qcs_sen_aru', 'Qcs_lat_aru', 'Qcs_sen_sys', 'Qcs_lat_sys', 'Qcs_em_ls', 'Qcs_dis_ls', 'Qhpro_sys', 'Qcpro_sys', 'QH_sys', 'QC_sys']
  (default: [])
- demand:massflows-output = ['mcpww_sys', 'mcptw', 'mcpcs_sys', 'mcphs_sys', 'mcpcs_sys_ahu', 'mcpcs_sys_aru', 'mcpcs_sys_scu', 'mcphs_sys_ahu', 'mcphs_sys_aru', 'mcphs_sys_shu', 'mcpcre_sys', 'mcpcdata_sys']
  (default: [])
- demand:temperatures-output = ['T_int', 'T_ext', 'theta_o', 'Tww_sys_sup', 'Tww_sys_re', 'Tcre_sys_re', 'Tcre_sys_sup', 'Tcdata_sys_re', 'Tcdata_sys_sup', 'Ths_sys_sup_aru', 'Ths_sys_sup_ahu', 'Ths_sys_sup_shu', 'Ths_sys_re_aru', 'Ths_sys_re_ahu', 'Ths_sys_re_shu', 'Tcs_sys_sup_aru', 'Tcs_sys_sup_ahu', 'Tcs_sys_sup_scu', 'Tcs_sys_re_aru', 'Tcs_sys_re_ahu', 'Tcs_sys_re_scu', 'Ths_sys_sup', 'Ths_sys_re', 'Tcs_sys_sup', 'Tcs_sys_re']
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:use-dynamic-infiltration-calculation = False
  (default: False)
- demand:overheating-warning = True
  (default: True)
Traceback (most recent call last):
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 59, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 34, in script_runner
    raise cea.MissingInputDataException()
cea.MissingInputDataException


---------------------------
ERROR: Missing input files:
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\weather\weather.epw
  (HINT: try running weather_helper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\building-properties\indoor_comfort.dbf
  (HINT: try running archetypes_mapper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\building-properties\internal_loads.dbf
  (HINT: try running archetypes_mapper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\building-properties\architecture.dbf
  (HINT: try running archetypes_mapper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\building-properties\air_conditioning.dbf
  (HINT: try running archetypes_mapper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\building-properties\supply_systems.dbf
  (HINT: try running archetypes_mapper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\building-properties\schedules\B1000.csv
  (HINT: try running archetypes_mapper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\outputs\data\solar-radiation\B1000_geometry.csv
  (HINT: try running radiation)
- C:\Users\tonycastillo\Zorrotzaurre\2020\outputs\data\solar-radiation\B1000_radiation.csv
  (HINT: try running radiation)
- C:\Users\tonycastillo\Zorrotzaurre\2020\outputs\data\occupancy\B1000.csv
  (HINT: try running schedule_maker)

**Comment by electron1406** [comment]
City Energy Analyst version 3.26.0
Running `cea demand` with the following parameters:
- general:scenario = C:\Users\tonycastillo\Zorrotzaurre\2020
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = True
  (default: False)
- demand:buildings = ['B1000', 'B1001', 'B1002', 'B1003', 'B1004',
'B1005', 'B1006', 'B1007', 'B1008', 'B1009', 'B1010', 'B1011',
'B1012', 'B1013', 'B1014', 'B1015', 'B1016', 'B1017', 'B1018',
'B1019', 'B1020', 'B1021', 'B1022', 'B1023', 'B1024', 'B1025',
'B1026', 'B1027', 'B1028']
  (default: [])
- demand:loads-output = ['PV', 'GRID', 'GRID_a', 'GRID_l', 'GRID_v',
'GRID_ve', 'GRID_data', 'GRID_pro', 'GRID_aux', 'GRID_ww', 'GRID_hs',
'GRID_cs', 'GRID_cdata', 'GRID_cre', 'E_sys', 'Eal', 'Ea', 'El', 'Ev',
'Eve', 'Edata', 'Epro', 'Eaux', 'E_ww', 'E_hs', 'E_cs', 'E_cre',
'E_cdata', 'Qhs_sen_shu', 'Qhs_sen_ahu', 'Qhs_lat_ahu', 'Qhs_sen_aru',
'Qhs_lat_aru', 'Qhs_sen_sys', 'Qhs_lat_sys', 'Qhs_em_ls',
'Qhs_dis_ls', 'Qhs_sys_shu', 'Qhs_sys_ahu', 'Qhs_sys_aru',
'Qcs_sys_scu', 'Qcs_sys_ahu', 'Qcs_sys_aru', 'DH_hs', 'Qhs_sys',
'Qhs', 'DH_ww', 'Qww_sys', 'Qww', 'DC_cs', 'Qcs_sys', 'Qcs', 'DC_cre',
'Qcre_sys', 'Qcre', 'DC_cdata', 'Qcdata_sys', 'Qcdata', 'NG_hs',
'COAL_hs', 'OIL_hs', 'WOOD_hs', 'SOLAR_hs', 'NG_ww', 'COAL_ww',
'OIL_ww', 'WOOD_ww', 'SOLAR_ww', 'Qcs_sen_scu', 'Qcs_sen_ahu',
'Qcs_lat_ahu', 'Qcs_sen_aru', 'Qcs_lat_aru', 'Qcs_sen_sys',
'Qcs_lat_sys', 'Qcs_em_ls', 'Qcs_dis_ls', 'Qhpro_sys', 'Qcpro_sys',
'QH_sys', 'QC_sys']
  (default: [])
- demand:massflows-output = ['mcpww_sys', 'mcptw', 'mcpcs_sys',
'mcphs_sys', 'mcpcs_sys_ahu', 'mcpcs_sys_aru', 'mcpcs_sys_scu',
'mcphs_sys_ahu', 'mcphs_sys_aru', 'mcphs_sys_shu', 'mcpcre_sys',
'mcpcdata_sys']
  (default: [])
- demand:temperatures-output = ['T_int', 'T_ext', 'theta_o',
'Tww_sys_sup', 'Tww_sys_re', 'Tcre_sys_re', 'Tcre_sys_sup',
'Tcdata_sys_re', 'Tcdata_sys_sup', 'Ths_sys_sup_aru',
'Ths_sys_sup_ahu', 'Ths_sys_sup_shu', 'Ths_sys_re_aru',
'Ths_sys_re_ahu', 'Ths_sys_re_shu', 'Tcs_sys_sup_aru',
'Tcs_sys_sup_ahu', 'Tcs_sys_sup_scu', 'Tcs_sys_re_aru',
'Tcs_sys_re_ahu', 'Tcs_sys_re_scu', 'Ths_sys_sup', 'Ths_sys_re',
'Tcs_sys_sup', 'Tcs_sys_re']
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:use-dynamic-infiltration-calculation = False
  (default: False)
- demand:overheating-warning = True
  (default: True)
Traceback (most recent call last):
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py",
line 146, in worker
    run_job(config, job, server)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py",
line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py",
line 59, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py",
line 34, in script_runner
    raise cea.MissingInputDataException()
cea.MissingInputDataException


---------------------------
ERROR: Missing input files:
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\weather\weather.epw
  (HINT: try running weather_helper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\building-properties\indoor_comfort.dbf
  (HINT: try running archetypes_mapper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\building-properties\internal_loads.dbf
  (HINT: try running archetypes_mapper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\building-properties\architecture.dbf
  (HINT: try running archetypes_mapper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\building-properties\air_conditioning.dbf
  (HINT: try running archetypes_mapper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\building-properties\supply_systems.dbf
  (HINT: try running archetypes_mapper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\inputs\building-properties\schedules\B1000.csv
  (HINT: try running archetypes_mapper)
- C:\Users\tonycastillo\Zorrotzaurre\2020\outputs\data\solar-radiation\B1000_geometry.csv
  (HINT: try running radiation)
- C:\Users\tonycastillo\Zorrotzaurre\2020\outputs\data\solar-radiation\B1000_radiation.csv
  (HINT: try running radiation)
- C:\Users\tonycastillo\Zorrotzaurre\2020\outputs\data\occupancy\B1000.csv
  (HINT: try running schedule_maker)

**Comment by shanshanhsieh** [comment]
Hi @electron1406 ,
The error messages are self-explanatory (see HINT).
Several Inputs are incomplete yet, you will need to first gather the inputs following these steps:
- Run Archetypes Mapper
- Run Weather helper
- Run Building Solar radiation (Under Demand Forecasting)
- Run Building Schedules (Under Demand Forecasting)
- Run Building Energy demand (Under Demand Forecasting)

**Comment by electron1406** [comment]
Dear Shanshan, 

I really thank your supportive attitude to help me through overcoming this/these issue(s), as you might notice I am very new to using this sort of GIS-based software. And from my point of view, the instructional material is scarce, do you mind giving me more details about how to perform:

- Run Archetypes Mapper
- Run Weather helper
- Run Building Solar radiation (Under Demand Forecasting)
- Run Building Schedules (Under Demand Forecasting)
- Run Building Energy demand (Under Demand Forecasting)

Since I do not know how to do it, any material for this?

Best regards
