### ISSUE TITLE
energy balance

### ISSUE THREAD

**Issue by wnoor94** [architecture-building-systems/CityEnergyAnalyst#3111]
where can I find the energy balance equation between supply side and demand side in the code? thanks

**Comment by shanshanhsieh** [comment]
Hi @wnoor94,

You can do so by plotting the dispatch curves (see below).
![dispatch.png](https://images.zenhubusercontent.com/57b4452fe40e5714b16d75a2/3b764133-7350-4025-af46-c82787766011)

For the moment, it is describing the dispatch curves for the whole district but not for individual buildings.
You can retrieve them from the raw data output:
- `your_cea_project/your_scenario/outputs/data/optimization/slave/gen_xx/...Activation_Pattern.csv`
- `your_cea_project/your_scenario/outputs/data/optimization/slave/gen_xx/...activation.csv`

**Comment by shanshanhsieh** [comment]
Hi @wnoor94,
closing this issue for now, please feel free to re-open it if you have more questions!
