### ISSUE TITLE
CEA structure

### ISSUE THREAD

**Issue by wnoor94** [architecture-building-systems/CityEnergyAnalyst#3112]
In this CEA structure there is a centrifugal pump, I can't find its code and does the heat pump works for heating and cooling supply
![image-asset](https://user-images.githubusercontent.com/93599371/159126205-8f551428-f588-4c30-b15b-52e26ac43584.png)

**Comment by wnoor94** [comment]
@jimenofonseca

**Comment by shanshanhsieh** [comment]
Hi @wnoor94,
You can find those code if you do a quick search in the repository.
Just to clarify, Centrifugal pumps are to transport hot/cold water in thermal networks, while heat pumps are energy conversion technologies that transfer thermal energy between spaces to produce hot or cold water.
