### ISSUE TITLE
Why can not run optimisation analysis?

### ISSUE THREAD

**Issue by electron1406** [architecture-building-systems/CityEnergyAnalyst#3117]
**Describe the bug**
I am not able to run the optimisation assessment due to an error produced in the meantime when executing this tool. 

**To Reproduce**
After running the Optimisation>>I ran Supply System Part I (decentralized)>>then I move forward to run  Supply System Part II (centralized), but it crashes, you can see it on the script that I posted here and also on the screenshot attached the message point at some missing files and suggest that I have to run the Thermal Network Part II, and I did but it remains the same.

**Expected behaviour**

**Screenshots**
Current Jobs
jobID: 17 - optimization
status: ERROR
parameters:
{
  "scenario": "C:\\Users\\tonycastillo\\T\\T",
  "multiprocessing": true,
  "network-type": "DH",
  "technologies-dh": [
    "NG_Cogen",
    "WB_Cogen",
    "DB_Cogen",
    "NG_BaseBoiler",
    "NG_PeakBoiler",
    "WS_HP",
    "SS_HP",
    "GS_HP",
    "DS_HP",
    "PVT",
    "SC_ET",
    "SC_FP",
    "PV"
  ],
  "technologies-dc": [
    "NG_Trigen",
    "WS_BaseVCC",
    "WS_PeakVCC",
    "AS_BaseVCC",
    "AS_PeakVCC",
    "Storage",
    "PV"
  ],
  "debug": false,
  "number-of-cpus-to-keep-free": "1",
  "population-size": "",
  "number-of-generations": "100",
![Captura de pantalla 2022-03-23 122221](https://user-images.githubusercontent.com/70798389/159688578-2359ee51-e76a-4dac-ae26-e8326a16d623.png)

  "random-seed": "100",
  "mutation-prob": "0.1",
  "mutation-method-integer": "Flipbit",
  "mutation-method-continuous": "Polynomial",
  "crossover-prob": "0.9",
  "crossover-method-integer": "UniformPartialyMatched",
  "crossover-method-continuous": "Uniform"
}

**Hardware (please complete the following information):**
 - OS and version: [Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

**Comment by shanshanhsieh** [comment]
Hi @electron1406, 
the error message is incomplete, thus, we cannot help you to identify the problem.
as of [v3.30.0](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases, the optimization script is running for the testing.

**Comment by shanshanhsieh** [comment]
closing this issue for now, please feel free to re-open it if the error persists.
