### ISSUE TITLE
street helper error 

### ISSUE THREAD

**Issue by Raummma97** [architecture-building-systems/CityEnergyAnalyst#3125]
Hi 
please I need a help .. when I try to create new project  I can't open it from open street map there is unknown error occurs ..it work only when I make two scenarios  in the same project the first one to import files I made it in QGIS and another one open it with open street map ..but it work with error in street helper the error is :   [street error.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/8380158/street.error.docx)

```
City Energy Analyst version 3.24.0
Running `cea streets-helper` with the following parameters:
- general:scenario = C:\idk\idk
  (default: {general:project}\{general:scenario-name})
- streets-helper:bbox = []
  (default: [])
- streets-helper:streets = all_private
  (default: all_private)
generating streets from Surroundings Geometry
Traceback (most recent call last):
  File "C:\Users\HP\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Users\HP\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\HP\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 59, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\HP\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 37, in script_runner
    script_module.main(config)
  File "C:\Users\HP\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\datamanagement\streets_helper.py", line 97, in main
    geometry_extractor_osm(locator, config)
  File "C:\Users\HP\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\datamanagement\streets_helper.py", line 81, in geometry_extractor_osm
    data.loc[:, "name"] = [x[0] if type(x) == list else x for x in data["name"].values]
  File "C:\Users\HP\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geodataframe.py", line 828, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "C:\Users\HP\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\HP\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'name'


```

the shape file of street is :
[streets (2).zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/8380215/streets.2.zip)

**Comment by shanshanhsieh** [comment]
Hi @Raummma97 ,

Could you please provide more information?
What are the differences between the two scenarios? which one was working and which one not?
What files did you import from QGIS?

Thanks

**Comment by Raummma97** [comment]
hi 
the scenario I opened from open street map in the CEA is working 
the scenario with  imported files is not work 
but both  of them I open in the same project because when I open only from cea it say there is unknown error and if I opened only scenario of imported files it isn't working correctly

I import zone, surrounding ,terrain and street shape files

**Comment by Raummma97** [comment]
this what I mean open with CEA open street map and unknown error:

[city-energy-analyst-gui 2022-04-03 09-46-03.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/8403957/city-energy-analyst-gui.2022-04-03.09-46-03.zip)

**Comment by Raummma97** [comment]
@shanshanhsieh

street helper error :
[city-energy-analyst-gui 2022-04-03 10-10-33.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/8403987/city-energy-analyst-gui.2022-04-03.10-10-33.zip)


[street error.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/8403989/street.error.docx)

**Comment by Raummma97** [comment]
when I open an imported files scenario  it opens with errors and it is not work :
[city-energy-analyst-gui 2022-04-03 10-31-47.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/8403999/city-energy-analyst-gui.2022-04-03.10-31-47.zip)

the errors of imported files 
street error and radiation error : 
[radation error.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/8404005/radation.error.docx)


[city-energy-analyst-gui 2022-04-03 10-33-43.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/8404001/city-energy-analyst-gui.2022-04-03.10-33-43.zip)

**Comment by Raummma97** [comment]
this video shows I opened two scenario in the same project the first one from open street map and it work until I create another scenario with imported files  after that the first one working with street error only 

[city-energy-analyst-gui 2022-04-03 10-45-39.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/8404013/city-energy-analyst-gui.2022-04-03.10-45-39.zip)

**Comment by Raummma97** [comment]
@shanshanhsieh

**Comment by Raummma97** [comment]
@daren-thomas

**Comment by reyery** [comment]
Hi @Raummma97, after looking through the errors, I found out that there is a bug in the CEA script `street-helpers` looking for the `name` property which does not exist. I can help fix that. However, I am unable to reproduce the error for the `radiation` script, so I am not too sure how to help you with that.

@shanshanhsieh Do we need the `name` property for streets? Based on what it is, it just shows the name of the road/street which might not exist/available for some places in OSM. I think CEA does not necessary need to store this for streets.

**Comment by shanshanhsieh** [comment]
hi @reyery , thanks for spotting the error!
as far as I know, the `name` property is not necessary for any other scripts, please go ahead and fix it. thanks!

**Comment by Raummma97** [comment]
@reyery @shanshanhsieh   thank you very much >> please I have another problem .. when I run network layout ..can you help me

[layout error.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/8501439/layout.error.docx)

**Comment by Raummma97** [comment]
@daren-thomas

**Comment by shanshanhsieh** [comment]
Hi @Raummma97 , 

It seems like the street properties presented in your case study site are quite different from the streets in other sites we have tested. We are working on addressing this now.
On your side, I will recommend you first try out the same functionality in the context where we have done more testing (e.g., Singapore). This way, we could isolate the problem from the code.

Good luck!

**Comment by Raummma97** [comment]
hi @shanshanhsieh 

I try (Zug and Singapore) the same error occurred 
![Screenshot 2022-04-21 212800](https://user-images.githubusercontent.com/59930298/164528550-47e7e4aa-0b95-4ef7-9a36-8dc67b1c5dd6.png)
[network layout error.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/8534146/network.layout.error.docx)

**Comment by Raummma97** [comment]
@ @shanshanhsieh @reyery @ @daren-thomas @nheeren  please help me to solve the error ??

**Comment by shanshanhsieh** [comment]
Hi @Raummma97 ,
I recommend you to completely uninstall your current CEA (by clicking the icon `Uninstall_CityEnergyAnalyst_3.29.0.exe` and make sure the entire `CityEnergyAnalyst` folder is empty), and install [v3.31.0](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/tag/v3.31.0).
In the new version, we introduced better error reporting functions, which could help us understand the errors you are facing better.

**Comment by Raummma97** [comment]
Hi @shanshanhsieh  .. ok I will do it and try .. thank you

**Comment by Raummma97** [comment]
@shanshanhsieh
