### ISSUE TITLE
Problem using Tools of Datamanagement and demand forecasting

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#3143]
*What happend?* 
We want to simulate energy demands of quarters in a group of students. 
At one computer we can't use all Tools of data management (weatherhelper and terrain helper). Additionally demand forecasting isn't working at all.
Pressing on "Run Script" doesn't cause a reaction.

*What's different to other computers?*
It's a windows computer, all general information are simular to other computers where CEA is running.

**Comment by lguilhermers** [comment]
@Mar-Ges Have you managed to run your scenarios successfully?
As we can't reproduce the error, there is not much support that can be given on that.
I recommend you re-install CEA in case you are not being able to run any of the scenarios.

**Comment by Mar-Ges** [comment]
@lguilhermers we managed to run our scenarios on our university computers. 
(Unfortunately the students computer somehow doesn't work out.... but anyway they are now able to keep on working)
