### ISSUE TITLE
input editor - edit selection: mandatory inputs for unchanged inputs

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#3146]
Some inputs are required in the edit selection pane, even if they remain unchanged.
See the example below:

![image](https://user-images.githubusercontent.com/50981039/165014471-95347f13-3d5f-422e-8202-f5116a88b2af.png)

To reproduce the error:
go to input editor - edit selection 
change one variable and try to press ok
see error

**Comment by MatNif** [comment]
I observed the same issue. 
I also noticed, that even if the unchanged values are re-entered, the changes cannot be saved. 
Also, the 'something went wrong'-error message that appears at the top of the CEA window as a result does not disappear anymore, even if the user discards the changes and navigates away from the input-editor:

<img width="1159" alt="Screen Shot 2022-04-25 at 12 26 17 PM" src="https://user-images.githubusercontent.com/93093343/165021630-06ab30de-639a-4023-aa88-b6ca620998a2.png">

<img width="1184" alt="Screen Shot 2022-04-25 at 12 27 04 PM" src="https://user-images.githubusercontent.com/93093343/165021647-48887020-8fc6-4a71-bebd-b10550408fd2.png">

**Comment by shanshanhsieh** [comment]
this should be working in v3.29.0 onwards @lguilhermers @MatNif

**Comment by lguilhermers** [comment]
It still happens to me, I tested in 3.30.

**Comment by lguilhermers** [comment]
It worked when I updated the GUI, so i am closing the issue.
