### ISSUE TITLE
Building energy demand simulation for buildings with more than 3 use types

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#3173]
**Describe the feature you would like to have**
I would like to be able to simulate buildings with more than 3 use types. This used to be possible before the input file format was changed from `occupancy.dbf` to `typology.dbf`.

Add the moment, the only way to do that is to manually create new "mixed" types and add them to one of the three use types columns. That, however, is cumbersome and prone to introduce human error. However, in principle the CEA data management tools can create mixed schedules with any number of use types – they are just hard-coded to take up to three.

With minor modifications, the CEA scripts can process `typology.dbf` files with more than 3 use types. However, it'd be hard to display more than 3 use types on the dashboard, as all the input columns are defined in `schemas.yml` and it's quite a strict schema which does not support a variable number of columns.

**Describe the end-user of this feature**
Modifying the script would let advanced users (e.g., researchers) to run case studies with any number of use types from the command line while not affecting the user experience of dashboard users.

**Comment by lguilhermers** [comment]
Hi martin, in regards to mixed types, I rememeber some of the parameters does not get "weighted" when creating the mix. If I am not mistaken, this happens mostly for discrete parameters such as the setpoint schedule (defined as none, setpoint and setback), but could happen to others as well (tempreture setpoint (?)).
I think this is very prone to introduce errors or at least missconception on what this mix represent for less aware users.

Not sure if it is something fixable, just giving giving some food for tought since you are looking into that already.

**Comment by martin-mosteiro** [comment]
You are correct, a lot of them are not weighted. Some of them by need (e.g., cooling system type – cannot assign a 50% centralized and 50% hybrid AC :)) others by how reasonable the weighted parameter would be (i.e., if you have a cool room that needs 5°C and a residential building that needs 25°C, a 15°C setpoint satisfies neither requirement). These are just assigned based on the main use of the building.

Actually, I would assume this is of more interest to _advanced_ users than less aware users. I would assume the latter are more interested in getting a rough estimate of energy demand for their project rather than dealing with building operation parameters, but the former might be more interested in knowing these details.

How would you suggest making this clearer to either type of user?

**Comment by lguilhermers** [comment]
True, I think both advanced and less aware users can be caught by these details (and devils are in the details).
I can only think about a warning in case mixed uses are being created, pointing to the parameters which are taken from the main use and applied to all so they can be checked.
As you indicated, the non-weighted parameters are not wrong per say, it is just a limited capability for dealing with a single zone model.
