### ISSUE TITLE
Workflow tool in the dashboard

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#3177]
I was thinking a tool on the GUI that runs a workflow would be very useful.

Motivation:
- from the workflow perspective, it wouldn't have to be project/ scenario specific. You could actually structure a single workflow and run with multiple scenarios, which I believe is not possible in the moment.
- from the dashboard perspective, you can execute multiple runs sequentially, without worrying about it. For example, for new scenarios,  almost always 'archetypes -> weather -> surroundings -> terrain -> surroundings' will be run.

It could be stored as a function inside utilities. Probably in the form of a large textbox (with default being the script to run the data management scripts?)

Feel free to share your thoughts on that.

**Comment by lguilhermers** [comment]
@reyery mentioned the workflow (yml) already supports the variable scenarios according to config and will double check that before closing the issue.

**Comment by reyery** [comment]
The CEA workflow already supports variable scenarios that is read from the config file. 

An example will be like https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/9bae0e1b4d5f395516bb5f8ae3a97b1aa84a70d9/cea/workflows/cooling-system-current-scenario.yml#L1-L14

**Comment by lguilhermers** [comment]
Cool! Then I think there is no need for an interface for that at this point.
Thanks for checking, @reyery!
