### ISSUE TITLE
PV potential error

### ISSUE THREAD

**Issue by irenemansoborras** [architecture-building-systems/CityEnergyAnalyst#3180]
Hi, I would like to report an issue I just had with CEA. 
When trying to define the Photovoltaic Panels, suddenly appears this error.  

![image](https://user-images.githubusercontent.com/105488775/171268924-a1b8a7c6-ccf7-4635-8ce7-02e79cd9f84b.png)

**Comment by lguilhermers** [comment]
Hi @irenemansoborras,

I would recommending installing the latest version of CEA and testing it again, it should be working.
If not, you will be getting a more informative error message that helps to track the issue.

**Comment by irenemansoborras** [comment]
Hi, 
everything is solved now. Thanks!

**Comment by lguilhermers** [comment]
Great, glad it is solved :)
