### ISSUE TITLE
The truth value of a Series is ambiguous

### ISSUE THREAD

**Issue by ahmadyahyazakaria** [architecture-building-systems/CityEnergyAnalyst#3192]
**Describe the bug**
The truth value of a Series is ambiguous

**To Reproduce**
1. Go to 'tools'
2. Click on 'demand forecasting'
3. Click on "building Solar radiation"
4. Click on "run script"
5. Click on "save to config"
6. See error

**Expected behaviour**
Out put result

**Screenshots**

![Capture](https://user-images.githubusercontent.com/108149670/175855680-6e82c581-ab4e-488b-9601-033aed820373.PNG)

**Hardware (please complete the following information):**
 - OS and version: [Windows 10]
 - Version of CEA you are using [e.g. v. 3.31.1]

**Comment by lguilhermers** [comment]
@ahmadyahyazakaria this error doesn't happen in our side. Can you check again your inputs, especially the one that refers to wwr.
There are also some tutorials on the CEA website that might help you with that.

PS: There is no need to save to config after running your simulation, this would be just in case you want to save some permanent changes of the configuration for the simulation.
