### ISSUE TITLE
Archetypes mapper for large scenarios doesn't finish while running on the dashboard

### ISSUE THREAD

**Issue by Iskenderzeynalov** [architecture-building-systems/CityEnergyAnalyst#3194]
So I am trying to run the Archetypes mapper but it is already more than 12 hours of running. Is it normal? My laptop info is in the attached pic. to assess the power. CEA takes about 50% of my CPU. I am unsure about the number of buildings but I will attach the pic of choosing the building's section. I am not sure if it shows the right amount of buildings or not though. The Area is around 95 km2. And apparently 45k buildings.

Now, the questions:

1) Is it normal?
2) Can I do anything about it? Accelerate somehow the run time?

**Comment by lguilhermers** [comment]
@Iskenderzeynalov The most conventional scale to run CEA would be districts (with number of buildings in the 1st and 2nd order of magnitude). We are currently testing CEA capabilities for large scenarios as well, we will notice here if we have more information about that. 

Archetypes mapper is a "light" script, but requires every building to be checked to map its typology and standard to the CEA database, probably requiring significant time for that large of scale.

I would recommend you to also check the inputs in building-geometry/zone.dbf, building-geometry/zone.shp, building-properties/typology.dbf to make sure they are complete and in proper format.

**Comment by lguilhermers** [comment]
@Iskenderzeynalov Apparently there is an issue when running this script in the dashboard for large cases as yours. But we managed to run in a matter of minutes when running via the console or the standalone archetypes_mapper script. You may try that for a quicker solution while we try to fix the issue in the interface. Thank you!

**Comment by Iskenderzeynalov** [comment]
Could You please give me the scrypts that I have to type in the console? I am not used to using the console. I have multiple projects so I have to choose which one I am going to work on in the console but don't know how to do it. Is there a manual for console usage?

**Comment by lguilhermers** [comment]
There is not a manual current, but I will keep this in mind for the next batch of tutorials in the website.

For now if you want to give it a try you can follow these steps:
1) Open via the dashboard and open the scenario you want to run. This will make your current project and scenario path to be saved in the config file.

2) From here you have 2 options:
A) open the console and type `cea archetypes-mapper` and click enter to run it. I believe you need the developers version installed for that.
B) Go to where CEA is installed and look for `...\CityEnergyAnalyst\cea\datamanagement\archetypes_mapper.py`. Open with any python editor and run the script (that is how I did did it).

In step 2, your scenario path will be printed, you can confirm if it is actually the scenario you opened in step 1, it should be.

This worked for us. For a case with 190k + buildings, it took around 15-20 min to run archetypes mapper.

**Comment by Iskenderzeynalov** [comment]
Could You please also check the cea radiation command with many buildings on the console? Because it takes way longer than 20-30 minutes. However, the archetype-mapper worked as you suggested pretty fast. Thanks for that.

**Comment by Iskenderzeynalov** [comment]
Thanks again. Is there an email that I can write to ask more general questions about my idea for the project? I am working on my Master Thesis right now and I am not sure if CEA can help me.

**Comment by Iskenderzeynalov** [comment]
Also, I have another problem. I tried this twice and result was the same. When I do the cea radiation on my laptop, after 4-5 hours of the simulation it gives me a blue screen with "We ran to some problems. Restarting Laptop in ..." and after 5 seconds restarts my laptop. Is it because my laptop is not powerful enough or there is another reason?
