### ISSUE TITLE
inputs for 'start' and 'end' ac systems does not allow 00|00

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#3195]
**Describe the bug**
When trying to include 00|00, equivalent to none, for those periods. CEA complains and doesn't allow this value.

**To Reproduce**
1. Go toinput editor -> ac systems
2. Ty to edit onthe 'start' and 'end' params to 00|00
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/50981039/177927022-6a7fd59a-0646-46da-94d7-ae58ab701790.png)

**Comment by MatNif** [comment]
I talked to @reyery about this today. I implemented his suggested change in the regex and checked whether the 'cea\plots\demand\comfort_chart.py'-script (only file using this as an input) interprets the 00|00 code correctly. Seems all good.

![CEA_airConditioningSystemsTable](https://user-images.githubusercontent.com/93093343/179488454-4dc2cd00-a90f-43bf-b946-d638a8bc627f.png)
