### ISSUE TITLE
Dependent variables in the simulation should be parametric for scenarios evolving over time/trajectories

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#32]
Dependent variables in the simulation that should be parametric for scenarios evolving over time/trajectories: (1) weather, (2) electricity supply mix, (3) prices of energy, (4) occupancy of buildings & schedules of occupants, (5) electricity demand

**Comment by JIMENOFONSECA** [comment]
Can you provide a better description. or is it still relevant?
