### ISSUE TITLE
Potential MSc Topic

### ISSUE THREAD

**Issue by Iskenderzeynalov** [architecture-building-systems/CityEnergyAnalyst#3203]
I am writing my master thesis on sector coupling with hydrogen technology in the city of Linz (which is the city that I live in right now).
I have an idea but am unsure if it is possible to make it happen. So I wanted to ask You about the reality of making it happen on CEA.

The idea:

I want to calculate how much CO2 emissions are in Linz and then calculate how much CO2 emission reduction will be after the implementation of Fuel Cells which will work as CHP because the waste heat from Fuel Cells is planned to be used as well via heat pumps. Also, the economic comparison would be nice to have, to see a sort of Emission reduction return on our investment.

Is it possible to simulate on CEA? If yes, then how?
If not, then is there a similar alternative that You would suggest?

**Comment by Iskenderzeynalov** [comment]
I meant Fuel Cells being used as CHPs since they both produce electricity and heat. 
And by alternative, I meant the best info that I get out of CEA to just add some results for my thesis and do rough calculations on my own.
Yeah, I would like to have a call to discuss some things.

**Comment by MatNif** [comment]
We can discuss right now if you would like to. Would you mind sending me your e-mail address? I'll send you a zoom invite.
