### ISSUE TITLE
Wrong scaling in the Load Curve for District Graph

### ISSUE THREAD

**Issue by Iskenderzeynalov** [architecture-building-systems/CityEnergyAnalyst#3206]
On the right side of the snip is shown the wrong outdoor temperature
![Bug](https://user-images.githubusercontent.com/107115308/180637674-f90a85c5-7554-4714-b645-84c40dffaf15.PNG)

**Comment by reyery** [comment]
Was not able to recreate this issue. Seems to be fixed.
