### ISSUE TITLE
solar radiation scrip: Exception: Some buildings are not of type "Polygon": CEA1176, CEA1177, CEA1178

### ISSUE THREAD

**Issue by RicardoGomesIST** [architecture-building-systems/CityEnergyAnalyst#3210]
When running solar radiation script from console returns the error

```
 File "c:\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\databases_verification.py", line 90, in assert_input_geometry_only_polygon
    raise Exception(
Exception: Some buildings are not of type "Polygon": CEA1176, CEA1177, CEA1178
```
It is a large buiding set - 25400 building - created from zero using CEA tools (so considers OSM polygons)
I cannot find these objects - opened in QGIS the zone file that has only B.... building objects. Runned geometry checker on qgis and also returned no errors. 

System: Windows 10 for Workstations
City Energy Analyst version 3.31.0

**Comment by MatNif** [comment]
The buildings with CEAXXXX as a name are the buildings surrounding your zone of interest. If you select the indicated buildings through the attribute table of the surrounding buildings (surroundings.shp) in QGIS you might be able to identify which of the buildings cause this error and why they might no be considered polygons.
As long as you have other buildings in your surroundings file you could simply delete these elements and try rerunning the radiation script.

**Comment by RicardoGomesIST** [comment]
Thank you! Your suggestion worked perfectly
