### ISSUE TITLE
Retrieve buildings heights from OSM

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#3218]
I checked a few buildings on OSM which have height informed. CEA seems to ignore this information, fetching always the number of floors and assuming a floor height of 3m to calculate height. Wouldn't this be preferable only if the height information was not available?

@shanshanhsieh @reyery @martin-mosteiro please let me know if this was discussed in the past and if it makes sense to implement such feature in the zone helper.

**Comment by martin-mosteiro** [comment]
Fully agree, the height should be taken from OSM if available
