### ISSUE TITLE
Wall partitions aren't accounted for in the demand calculations

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#3221]
The type_part (PARTITION) component seems to not affect any of the calculations. Does it make sense to keep it there?

I have previously integrated it to the input editor, since it was in the construction standards. But now, after doing a sensitivity analysis and seeing there is no impact of this parameter, I think it should be removed from both.

**Comment by martin-mosteiro** [comment]
Partitions weren't originally part of the CEA database, not sure why it was added. I believe the wall area for partitions are estimated as part of the demand calculation (i.e., `partition_area = x * floor_area` where x is some number taken from the standards), so I assume the type of partition _could_ affect the calculations – if the code was written to account for it.

Maybe we can leave the partitions as part of the database even if they don't impact the calculations and leave an open known issue about the fact that partitions aren't accounted for in the demand calculations?

**Comment by lguilhermers** [comment]
I will try to confirm if there are parts of the codes using partitions, but in my sensitivity studies changing it never generated any difference in demand, even in the decimals.

For now I think @martin-mosteiro is suitable, but I would also be in favour of removing inputs it in case it is just a placeholder for a potential model extension.

**Comment by martin-mosteiro** [comment]
After checking, the partitions _will_ have an effect on the embodied energy calculation (albeit probably small). Not sure if anyone is using CEA for LCA calculations, to be honest, but when in doubt I'd rather leave them in.

**Comment by lguilhermers** [comment]
True, I hadn't looked at it from the LCA perspective. Let's leave the partitions as it is then. Leaving open the _known issue_ of the internal mass not impacting demand.
