### ISSUE TITLE
why

### ISSUE THREAD

**Issue by metwaly-ali** [architecture-building-systems/CityEnergyAnalyst#3223]
![image](https://user-images.githubusercontent.com/110869501/184057266-e25d9de7-4f38-44a4-a9a6-f909e549e6c8.png)

**Comment by lguilhermers** [comment]
@metwaly-ali please use the tutorials in our website to get familiar with the tool: https://www.cityenergyanalyst.com/
As we are unable to offer one-to-one support, we use the GitHub for reproduceable issues and bugs only.
