### ISSUE TITLE
merge buildings with the same height and touching geometry

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#3233]
On top of the geometry work we have been doing recently, I think it would be useful to have a tool that checks for connecting geometries and connects them **if** they have the same height.

I envision this to be an optional step inside utilities more than a function inside zone helper, but I also don't see any reason to not be the latter (other than waiting for the current implementations to be better established to avoid too many conflicts).

**Comment by martin-mosteiro** [comment]
Hmmm I think this should be a separate tool, as you suggested. If you have two different buildings that have the same height, it might be easier to treat them as two buildings in some applications, but they could have entirely different properties, especially if they have different owners. This probably doesn't make _too_ much difference in Singapore, but different ownership in Switzerland can mean, for example, different insulation levels, different window types, etc...
