### ISSUE TITLE
`fix_overlapping_geometry` might select wrong information over right information

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#3236]
**Describe the bug**
The `fix_overlapping_geometry` function assigns building heights according to the `height_ag` and `height_bg` attributes in the generated shapefile. However, the comparison of two buildings' heights on a CEA shapefile might be apples to oranges: one might have a height assigned from the OSM height or number of floors data, but another might have a height assigned by taking the case study area's median. By making the selection on which height to assign based on this comparison, we might be assigning a totally fake value (the median of the entire case study area) over a more plausible one (an actual height from OSM).

But does this ever really have an effect? Well, look at these two versions of Lau Pa Sat created by selecting two different case study areas: 
<img width="985" alt="Screen Shot 2022-08-26 at 10 17 24" src="https://user-images.githubusercontent.com/18548065/186802425-877ec4be-6892-4821-85e5-0e60de1ff2dd.png">
<img width="985" alt="Screen Shot 2022-08-26 at 10 17 58" src="https://user-images.githubusercontent.com/18548065/186802459-99b5f735-3471-4ecf-9e65-3a630eb27d9b.png">
Note: there are two overlapping polygons for Lau Pa Sat; the "pizza pie" version is the correct height per OSM; the other polygon has no assigned height nor number of floors, and therefore gets assigned the median height of the case study in CEA. When selecting a smaller area, the median height is much higher such that it exceeds the height taken from OSM, and therefore the taller polygon (the one with a completely artificial 17 floor height) gets selected during the `fix_overlapping_geometry` workflow.

**To Reproduce**
1. Find an area with overlapping polygons with different assigned heights (one has an assigned height, the other one doesn't) – yes, it might be tricky to find another case of this.
2. Run the zone_helper for that area
3. Check the output

**Expected behaviour**
Just like in the geometry creation process, data should be used with the following priority:
1. 'height' taken from OSM
2. 'building:levels' taken from OSM
3. 'height_ag'/'height_bg'

@MatNif please let me know if you have any feedback or ideas on this

**Comment by martin-mosteiro** [comment]
Note: the example case in Lau Pa Sat above was generated by including polygons tagged as `building:part` in OSM (separate issue, #3220), but could happen for other overlapping building polygons.

**Comment by MatNif** [comment]
Hey @martin-mosteiro,

First of all, nice find once again.
The result here obviously does not represent reality. While `fix_overlapping_geometry` did not introduce this problem (if you were to turn off the option, the Lao Pa Sat geometry in the second example would still be generated, it would just overlap with the geometries from the first example) the new branch visibly also doesn't fix it. 

One option to tackle this, I believe, could be the introduction of a qualifier for the building heights, e.g.:
A - known (if OSM height is available)
B - known by proxy (if OSM levels are available)
C - assumed (if the height was set to average of zone)
These qualifiers could then be taken into account when deciding which geometries should be retained in `fix_overlapping_geometry`.

What do you think of that?

**Comment by martin-mosteiro** [comment]
Sounds good! That hierarchy is essentially what is there now (after the PR on using building heights from OSM), though it's implemented in a rather patchy way, clearly the result of adding functionality on top of the original code. I think refactoring that code would be very welcome (if you're keen to tackle it ;)).

If it's a quick fix, you can go ahead and add it to the PR. In the interest of not holding up the PR, though, if it's a longer fix I would suggest making the qualifiers a new issue and tackle it separately.
