### ISSUE TITLE
Error using Building Energy demand

### ISSUE THREAD

**Issue by metwaly-ali** [architecture-building-systems/CityEnergyAnalyst#3240]
1 - ( Describe the case you are trying to run ) : I want work run script to Building Energy demand for the data on the program so I can change the numbers to fit my project.
2- ( Describe the steps you performed leading up to the error ) : Enter Data ( shapefiles ( road - zone - surrounfdin - terrian ) and then Demand forecasting and thenBuilding Energy demand and then   run script .
3- Provide the detailed error message that is CEA prompts ( status: ERROR
parameters:
{
  "scenario": "C:\\Users\\User\\Aswan project\\urban form",
  "multiprocessing": true,
  "buildings": [
    "B1000",
    "B1001",
    "B1002",
    "B1003",
    "B1004",
    "B1005",
    "B1006",
    "B1007",
    "B1008",
    "B1009",
    "B1010",
    "B1011",
    "B1012",
    "B1013",
    "B1014",
    "B1015",
    "B1016",
    "B1017",
    "B1018",
    "B1019",
    "B1020",
    "B1021",
    "B1022",
    "B1023",
    "B1024",
    "B1025",
    "B1026",
    "B1027",
    "B1028",
    "B1029",
    "B1030",
    "B1031",
    "B1032",
    "B1033",
    "B1034",
    "B1035",
    "B1036",
    "B1037",
    "B1038",
    "B1039",
    "B1040",
    "B1041",
    "B1042",
    "B1043",
    "B1044",
    "B1045",
    "B1046",
    "B1047",
    "B1048",
    "B1049",
    "B1050",
    "B1051",
    "B1052",
    "B1053",
    "B1054",
    "B1055",
    "B1056",
    "B1057",
    "B1058",
    "B1059",
    "B1060",
    "B1061",
    "B1062",
    "B1063",
    "B1064",
    "B1065",
    "B1066",
    "B1067",
    "B1068",
    "B1069",
    "B1070",
    "B1071",
    "B1072",
    "B1073",
    "B1074",
    "B1075",
    "B1076",
    "B1077",
    "B1078",
    "B1079",
    "B1080",
    "B1081",
    "B1082",
    "B1083",
    "B1084",
    "B1085",
    "B1086",
    "B1087",
    "B1088",
    "B1089",
    "B1090",
    "B1091",
    "B1092",
    "B1093",
    "B1094",
    "B1095",
    "B1096",
    "B1097",
    "B1098",
    "B1099",
    "B1100",
    "B1101",
    "B1102",
    "B1103",
    "B1104",
    "B1105",
    "B1106",
    "B1107",
    "B1108",
    "B1109",
    "B1110",
    "B1111",
    "B1112",
    "B1113",
    "B1114",
    "B1115",
    "B1116",
    "B1117",
    "B1118",
    "B1119",
    "B1120",
    "B1121",
    "B1122",
    "B1123",
    "B1124",
    "B1125",
    "B1126",
    "B1127",
    "B1128",
    "B1129",
    "B1130"
  ],
  "number-of-cpus-to-keep-free": "1",
  "debug": false,
  "loads-output": [
    "PV",
    "GRID",
    "GRID_a",
    "GRID_l",
    "GRID_v",
    "GRID_ve",
    "GRID_data",
    "GRID_pro",
    "GRID_aux",
    "GRID_ww",
    "GRID_hs",
    "GRID_cs",
    "GRID_cdata",
    "GRID_cre",
    "E_sys",
    "Eal",
    "Ea",
    "El",
    "Ev",
    "Eve",
    "Edata",
    "Epro",
    "Eaux",
    "E_ww",
    "E_hs",
    "E_cs",
    "E_cre",
    "E_cdata",
    "Qhs_sen_shu",
    "Qhs_sen_ahu",
    "Qhs_lat_ahu",
    "Qhs_sen_aru",
    "Qhs_lat_aru",
    "Qhs_sen_sys",
    "Qhs_lat_sys",
    "Qhs_em_ls",
    "Qhs_dis_ls",
    "Qhs_sys_shu",
    "Qhs_sys_ahu",
    "Qhs_sys_aru",
    "Qcs_sys_scu",
    "Qcs_sys_ahu",
    "Qcs_sys_aru",
    "DH_hs",
    "Qhs_sys",
    "Qhs",
    "DH_ww",
    "Qww_sys",
    "Qww",
    "DC_cs",
    "Qcs_sys",
    "Qcs",
    "DC_cre",
    "Qcre_sys",
    "Qcre",
    "DC_cdata",
    "Qcdata_sys",
    "Qcdata",
    "NG_hs",
    "COAL_hs",
    "OIL_hs",
    "WOOD_hs",
    "SOLAR_hs",
    "NG_ww",
    "COAL_ww",
    "OIL_ww",
    "WOOD_ww",
    "SOLAR_ww",
    "Qcs_sen_scu",
    "Qcs_sen_ahu",
    "Qcs_lat_ahu",
    "Qcs_sen_aru",
    "Qcs_lat_aru",
    "Qcs_sen_sys",
    "Qcs_lat_sys",
    "Qcs_em_ls",
    "Qcs_dis_ls",
    "Qhpro_sys",
    "Qcpro_sys",
    "QH_sys",
    "QC_sys"
  ],
  "massflows-output": [
    "mcpww_sys",
    "mcptw",
    "mcpcs_sys",
    "mcphs_sys",
    "mcpcs_sys_ahu",
    "mcpcs_sys_aru",
    "mcpcs_sys_scu",
    "mcphs_sys_ahu",
    "mcphs_sys_aru",
    "mcphs_sys_shu",
    "mcpcre_sys",
    "mcpcdata_sys"
  ],
  "temperatures-output": [
    "T_int",
    "T_ext",
    "theta_o",
    "Tww_sys_sup",
    "Tww_sys_re",
    "Tcre_sys_re",
    "Tcre_sys_sup",
    "Tcdata_sys_re",
    "Tcdata_sys_sup",
    "Ths_sys_sup_aru",
    "Ths_sys_sup_ahu",
    "Ths_sys_sup_shu",
    "Ths_sys_re_aru",
    "Ths_sys_re_ahu",
    "Ths_sys_re_shu",
    "Tcs_sys_sup_aru",
    "Tcs_sys_sup_ahu",
    "Tcs_sys_sup_scu",
    "Tcs_sys_re_aru",
    "Tcs_sys_re_ahu",
    "Tcs_sys_re_scu",
    "Ths_sys_sup",
    "Ths_sys_re",
    "Tcs_sys_sup",
    "Tcs_sys_re"
  ],
  "resolution-output": "hourly",
  "use-dynamic-infiltration-calculation": false,
  "overheating-warning": true
} ) 
4- Provide input files that are located in the input folder of your script ( https://drive.google.com/file/d/1L3lhu09DlyF8WYAdWTIg4UK-bM-ViPjv/view?usp=sharing )

**Comment by kholody** [comment]
Thanks Metwaly-ali for you question 
It seems that this issue is similar to mine. 
So, it would be so helpful if the assistant team could give us the proper solution for it as soon as possible.
there are two problems in having the final results of these two analysis "using building solar radiation" and "Building Energy demand"

Thanks a lot for the assistance.

**Comment by lguilhermers** [comment]
Hi @metwaly-ali and @kholody. Building energy demand will not run unless solar radiation is successfully run.
I have posted more information on the solar radiation issue which might be able to assist you, hope it helps.

**Comment by kholody** [comment]
Thanks a lot for your assisst..I will try to follow your steps hopefully to make it work..

**Comment by kholody** [comment]
Thanks alot for your help ..I will try to follow your steps 
Hopefully to make it work 
Please let me get back to you if anything is going wrong
