### ISSUE TITLE
Reset cea.config to deafults through python

### ISSUE THREAD

**Issue by ddceruti** [architecture-building-systems/CityEnergyAnalyst#3242]
Dear CEA team,
I am really enjoying the tool. I am currently looking to automate the whole workflow for heat demand estimation with python. I do this by "overwriting" the user defined config file with and then call create-new-scenario. Now, sometimes I loose track of the altered configurations, so I would like to have a method for resetting the config to the default.config values directly with a python command. So my idea would be like:
cfg.user_config.reset() or similar.
I would also be fine with "iterating" through the default Sections and overwrite the user defined with the default values...

I have been looking but did not find an easy way to do it within cea.config. Do you have an idea how I could achieve this? 
Thanks in advance!

**Comment by lguilhermers** [comment]
@ddceruti Glad you are being able to use CEA and enjoying it!
I am not sure I fully understood your question, but it seems you want to automate nultiple scripts across different scenarios.
We have already implemented a solution for that using a workflow tool, which is described at:
https://www.cityenergyanalyst.com/blog-posts/2020/01/14/2020-1-14-cea-workflow-how-to-automate-simulations

You will create a text file with the scripts you want to run and add changes you want in the config (so you can change not only the scenario path, but also the config parameters for each script).
Let us know if this seems to solve your issue and/or if you need more help on that.

**Comment by ddceruti** [comment]
Thank you for the quick reply! I think that I did not explain the issue properly... Sorry. I am using workflows and it works very well (I adapted a .yml script from cea/workflows). I am calling them from python directly instead of the CLI, which also works flawlessly. 
I am having a bit of issues with the user cea.config file, since I update it often. To alleviate this issue and make things easier for me, I would like to reset it to the defaults in default.config. Is there any way to reset the cea.config file programatically or manually to the default.config values?
I hope the question is clearer.

**Comment by lguilhermers** [comment]
Thanks for the clarification @ddceruti, I was able to understand more clear now.
@reyery (our MVP developer) mentioned you can add this within the workflow.yml file to restore it to default: 
`- config: default`

Mind trying and see if this attends your need?

**Comment by ddceruti** [comment]
Hi again,
I solved it with that idea! here is how I solved it within my code by adding the cea.config.DEFAULT_CONFIG init argument:

```
    #create instance: call with default values
    cfg = cea.config.Configuration(cea.config.DEFAULT_CONFIG)

    #set general settings
    cfg.general.project = MAIN_DIR + PROJECT_NAME
    cfg.general.scenario_name = SCENARIO_NAME
    
    #modify settings I want
    
    #save to cea.config
    cfg.save()
```

Then call a workflow .yml where other, scenario indipendent settings are passed with "parameters" arguments.

This allows me to automatically create-new-scenarios from python and call always the same workflow .yml file for each different automatically created scenario.

Thanks again for your help and time!

**Comment by lguilhermers** [comment]
Great! Good to see it was solved! :D
