### ISSUE TITLE
terrain file: which format and how to get it?

### ISSUE THREAD

**Issue by RicardoGomesIST** [architecture-building-systems/CityEnergyAnalyst#3244]
Hi,  
I would like to have real terrain file on my CEA simulations. I get one raster file with the following characteristics:
**-Data type	Byte - Eight bit unsigned integer
Band 1	
STATISTICS_APPROXIMATE=YES
STATISTICS_MAXIMUM=255
STATISTICS_MEAN=90.936549744122
STATISTICS_MINIMUM=0
STATISTICS_STDDEV=97.73177664394
STATISTICS_VALID_PERCENT=100
Band 2	
STATISTICS_APPROXIMATE=YES
STATISTICS_MAXIMUM=255
STATISTICS_MEAN=87.637014704511
STATISTICS_MINIMUM=0
STATISTICS_STDDEV=92.429450902658
STATISTICS_VALID_PERCENT=100
Band 3	
STATISTICS_APPROXIMATE=YES
STATISTICS_MAXIMUM=0
STATISTICS_MEAN=0
STATISTICS_MINIMUM=0
STATISTICS_STDDEV=0
STATISTICS_VALID_PERCENT=100**

The file created by CEA data management has the following characteristics:

**Data type	Float32 - Thirty two bit floating point
Band 1	
STATISTICS_APPROXIMATE=YES
STATISTICS_MAXIMUM=1
STATISTICS_MEAN=1
STATISTICS_MINIMUM=1
STATISTICS_STDDEV=0
STATISTICS_VALID_PERCENT=100**

I can transform my file into the same Data type. However, I am having problems normalizing the file.
What I did:
("raster_1stband"-min("raster_1stband"))/(max("raster_1stband")-min("raster_1stband"))
however QGIS crashes. 

Do you think this is the way? 
Thank you again

Any help would be great!

**Comment by jimenofonseca** [comment]
Hi Ricardo. It is a Digital Elevation Model (a simple raster file of 3 bands, where one is the elevation)with a .tif extension. you could create one directly from GIS software such as QGIS or ArcGIS. Also municipality services normally help to get data in this format. 

https://de.wikipedia.org/wiki/Digitales_H%C3%B6henmodell
