### ISSUE TITLE
CEA not supported in Windows 11?

### ISSUE THREAD

**Issue by jimenofonseca** [architecture-building-systems/CityEnergyAnalyst#3247]
Since Version 3.31 does not work at the moment, I tried to install de older version 3.30
 
It does not work in Windows 11. Since there is a new version of python in the windows system (v3.8) provokes a conflict with how the DLLs from GDAL get imported in Python.

It will be good to mention that Windows 11 is not supported before downloading. I think this will apply to version also 3.31

**Comment by jimenofonseca** [comment]
Found that it could be fixed with chaning how gdal gets imported

Change "import gdal" for "from osgeo import gdal"

**Comment by shanshanhsieh** [comment]
this would be related to #3255 #3246, indeed, there might be some problem in the developer's version.
i just tried the installation for **non-developer's version** on windows11 and it works.

**Comment by lguilhermers** [comment]
Fixed in https://github.com/architecture-building-systems/CityEnergyAnalyst/discussions/3264
Thanks @reyery! :D
