### ISSUE TITLE
Building Solar radiation keeps running

### ISSUE THREAD

**Issue by lengelen** [architecture-building-systems/CityEnergyAnalyst#3253]
Hi all, 

I am a new CEA user and wanted to test CEA with a small case study. However, I get stuck with Building Solar radiation, of which the job keeps running (i.e. > 1 h for 3 buildings). It does not give an error but just keeps running and is stuck at:
```
Calculating terrain intersection of building geometries
Using 7 CPU's
```

I already made sure that the daysim-bin-directory is correct, and that the path-name does not contain any spaces or weird letters: "C:\Users\ENGELENL\Documents\CityEnergyAnalyst\Dependencies\Daysim".
I already deleted and reinstalled the software a couple of times but cannot find out where it goes wrong.
I also tested this with different test cases, in different countries, but the issue remains.

I have CEA installed on Windows 10, with the latest downloadable version of CEA (3.31.0).

I added the project as zip file to this issue.
Thanks in advance.
[Exercise1.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/9757104/Exercise1.zip)

**Comment by justinfmccarty** [comment]
Hi @lengelen, I recommend first extracting the reference-case and trying to run the solar radiation script on that. If it works then we can move on to confirm that something is going on with your geometry files.
