### ISSUE TITLE
cannot launch cea dashboard

### ISSUE THREAD

**Issue by 494612231** [architecture-building-systems/CityEnergyAnalyst#3255]
**Describe the bug**
I cannot open the dashboard.

**To Reproduce**
I tried to download v3.31.0 and v3.30.0. I cannot open the dashboard of either version. 
Below are the errors and my revisions:  
1. [ImportError: cannot import name 'run_with_reloader' from 'werkzeug.serving']
I added this function manually to werkzeug, serving
2. [ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers']
I added this function manually to flask.helpers
3. There is no "BaseResponse" file but a "response" file in the werkzeug folder. 
I revised the function name to BaseResponse.
4. There is no "parse_rule" file but "rules" file in werkzeug .routine folder.
I created parse_rule file. 

**Screenshots**
Now it stays in the starting... status
![屏幕截图 2022-10-16 213941](https://user-images.githubusercontent.com/37100987/196038627-834b9e5a-b981-4fd8-b045-972f28990f0b.png)

**Hardware (please complete the following information):**
 - OS and version: win11
 - Version of CEA you are using: v.3.31.0 and v.3.30.0

**Comment by shanshanhsieh** [comment]
Hi @494612231 ,

Thanks for reporting this issue.
Please check the following points to help us understand the situation better:
1. Did you install a developer's version or non-developer's version?
2. Is your CityEnergyAnalyst folder in a local drive (e.g., C:\Users\Shanshan\Documents\CityEnergyAnalyst)? The installation in a cloud drive often leads to some problems (e.g., C:\Users\Shanshan\OneDrive\Documents)
3. Could you please print the error msg from console by following these steps:
- open **CEA Console** and type `cea dashboard` to start the backend of the CEA Dashboard.
- open the **CEA Dashboard** application. Please report the msg shown in **CEA Console**

**Comment by vlada-p** [comment]
Same problem as OP

I've installed non -developer's version in a suggested folder (e.g., C:\Users\Shanshan\Documents\CityEnergyAnalyst) on WIn 10 x64 OS
prt screen of the error is attached

![CEA error](https://user-images.githubusercontent.com/117993160/201345518-35ee3664-30c1-4d41-bf71-20118945f625.png)

**Comment by vlada-p** [comment]
> @494612231 this issue was addressed in the new release (#3264). Can you try reinstalling CEA and check if it works for you now?

I will try and will have an answer for you shortly

**Comment by vlada-p** [comment]
> @494612231 this issue was addressed in the new release (#3264). Can you try reinstalling CEA and check if it works for you now?

the problem still persist. It seams to me the errors are identical. 
I have installed Win developer version in a suggested folder
![image](https://user-images.githubusercontent.com/117993160/201610536-120eabfc-7071-4cc1-ba1b-6988a1866f6a.png)

**Comment by reyery** [comment]
Strange, that looks like something that should already be solved in the new version v3.32.0
@vlada-p Could you try uninstalling CEA and installing it again using this installer?
https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.32.0/Setup_CityEnergyAnalyst_3.32.0.exe

**Comment by 494612231** [comment]
> Strange, that looks like something that should already be solved in the new version v3.32.0 @vlada-p Could you try uninstalling CEA and installing it again using this installer? https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.32.0/Setup_CityEnergyAnalyst_3.32.0.exe
> 
> If the same error pops up again, could you scroll down to the end of the error message as well so that we can see the complete message. Thanks!

Sorry for my late update. I just install the version you provided here, and it works well! Thank you so much for your help.
