### ISSUE TITLE
CEA Dashboard not starting

### ISSUE THREAD

**Issue by vlada-p** [architecture-building-systems/CityEnergyAnalyst#3266]
**Describe the bug**

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

Due to closure of previous issue I'm starting a new one
I've tried installing at least 15 times CEA in last couple of days, v.3.31.0 and lastly v3.32.0 provided in release section and also provided here
https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/3255#issuecomment-1316297715

before every installation I've tried cleaning the registry and making sure there is no CEA folder
Both developer and non-developer version were installed with same outcome on Win 10 x64 OS

prt screens of error's are shown below (whole error)
![Untitled1](https://user-images.githubusercontent.com/117993160/202110661-5c4999f9-1f87-46e8-a531-2db274d0f0f1.png)
![Untitled2](https://user-images.githubusercontent.com/117993160/202110665-f17132ab-2422-4569-a874-2373203a575b.png)

**Comment by reyery** [comment]
Hi @vlada-p, thanks for providing the full error message. This seems to be an issue that we have not encountered before, and I was not able to recreate it on my end as well.

Could you try launching the CEA Console that is installed with CEA (should be able to find the shortcut in the installation path), and type `pip list` in the terminal to list the python libraries that CEA has installed.

**Comment by reyery** [comment]
It seems like it is not properly installed. I would suggest you try to remove all CEA files and reinstall it again. 

If that still fails, you can try installing CEA manually using conda https://city-energy-analyst.readthedocs.io/en/latest/installation/installation-on-windows-manual.html After installing it manually, activate the CEA conda environment and try running `cea dashboard`. Let me know if that works.

**Comment by vlada-p** [comment]
> It seems like it is not properly installed. I would suggest you try to remove all CEA files and reinstall it again.

I've tried that at least 20 times

> If that still fails, you can try installing CEA manually using conda https://city-energy-analyst.readthedocs.io/en/latest/installation/installation-on-windows-manual.html After installing it manually, activate the CEA conda environment and try running `cea dashboard`. Let me know if that works.

I am very sorry but I'm not sure if I am willing to do something like 
_Installation of the code base
Excluding the above software, CEA installation requires approximately 13 GB of storage (depending on your existing Python library) and 1 hour of your time._

and see if that JUST works.
For some reason installation is not working properly on my computer, and that is something I just have to deal with

**Comment by Mar-Ges** [comment]
Unfortunately I also tried a lot of restarts and still get an error message (close to yours @vlada-p) 
![image](https://user-images.githubusercontent.com/73158684/203274592-65ec3191-d02c-439e-a6e7-000f36f4ba9d.png)

But just from reading I think there are different "states of error". (For me "pip list" is creating the list of installed versions and i can use cea "workflows" to simulate existing projects...) --- but maybe we can solve it together  

(Coming from Issue #3246)

**Comment by Mar-Ges** [comment]
Additional report of what I tried: 
- as there was recorded an ImportError with "werkzeug" I downgraded it from 2.2.2 to 0.16.0 
- then i recieved an other error with an ImportError of Flask/jinja2  (unfortunately not solvable by downgrading)

**Comment by vlada-p** [comment]
> Hi @vlada-p, thanks for providing the full error message. This seems to be an issue that we have not encountered before, and I was not able to recreate it on my end as well.

So it turned out to be an issue with locally installed certificate (issued by governing body) and that is why you couldn't recreate the issue. It was also making a lot of "fun" for me while working on a computer I'm currently using and on which I tried installing CEA countless times.
Solution is the following: 
I had to append `ssl.py` found in Documents\CityEnergyAnalyst\Dependencies\Python\Lib\
by adding one line `if <certificate> not in str(cert):` in-between

`if trust is True or purpose.oid in trust:`
                        `certs.extend(cert)`

that was related to specific certificate.


After doing this CEA Dashboard in up and running

**Comment by reyery** [comment]
@vlada-p thanks for updating us about your issue, I am glad that you were able to pinpoint it. I will try to see if we can handle that special case in CEA to prevent it from happening to others as well.

---

> - as there was recorded an ImportError with "werkzeug" I downgraded it from 2.2.2 to 0.16.0

@Mar-Ges this issue regarding socketio has already been solved in the new version with the new installer, I have a feeling that it might not have installed it correctly. I will have to double check the installer again. In any case, you could try manually downgrading `werkzeug` to version 2.0, which is what we have done to solve it.
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/debdc133fd7928def87d751f0ba6a5b535034ff5/environment.yml#L8-L11




I have to admit that the installation for CEA is not really as straightforward as we want it to be. I am currently thinking of ways to streamline the the process and also try to implement an auto update feature.

**Comment by Mar-Ges** [comment]
@reyery thanks for your answer! I just wanted to try it with a new installation - but where can i find the download? (over the Homepage there is a "dead end" after this formular:
![image](https://user-images.githubusercontent.com/73158684/203963835-d5e5bcd0-642a-4053-9f66-302a37d68e1e.png)
I'll try it later again

**Comment by vlada-p** [comment]
@Mar-Ges take a look at the screen shoot


![Untitled](https://user-images.githubusercontent.com/117993160/203992965-bd56c3de-6231-4c5d-a929-feb53caade3a.png)

**Comment by Mar-Ges** [comment]
@vlada-p, @reyery  Thanks to both of you! 

This new installation solved all my problems - now its running and i'll enjoy simulating again :)
