### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by AWillmann** [architecture-building-systems/CityEnergyAnalyst#3279]
**Describe the bug**
since the last windows 10 update (?) CEA V18 does not start anymore

**To Reproduce**
1. try to open CEA
2. workflow test

C:\Users\an1123\CityEnergyAnalyst
(CEA) λ cea test --workflow slow
Traceback (most recent call last):
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\an1123\CityEnergyAnalyst\Dependencies\Python\Scripts\cea.exe\__main__.py", line 4, in <module>
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\cea\interfaces\cli\cli.py", line 14, in <module>
    import cea.config
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\cea\config.py", line 13, in <module>
    import cea.inputlocator
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\cea\inputlocator.py", line 9, in <module>
    import cea.schemas
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\cea\schemas.py", line 14, in <module>
    import geopandas
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\geopandas\__init__.py", line 3, in <module>
    from geopandas.geoseries import GeoSeries  # noqa
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\geopandas\geoseries.py", line 9, in <module>
    from pyproj import CRS, Transformer
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\pyproj\__init__.py", line 50, in <module>
    from pyproj import _datadir
ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.

**Expected behaviour**
How do I fix this? Unistalling the update did not help. 

**Screenshots**

![CEA error](https://user-images.githubusercontent.com/33447712/211261517-1a7e1757-2af5-46c2-aea1-e52b1f235fd7.JPG)
![CEA error 2](https://user-images.githubusercontent.com/33447712/211261537-c32ed0ed-edc3-4b44-a383-73edbadcba24.JPG)

**Hardware (please complete the following information):**
 - Windows 10
 - Version of CEA you are using [e.g. v. 2.18.1]

**Comment by AWillmann** [comment]
Trying to install the missing library fails: 
(base) C:\Users\an1123>pip install pyproj
Defaulting to user installation because normal site-packages is not writeable
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyproj/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyproj/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyproj/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyproj/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyproj/
Could not fetch URL https://pypi.org/simple/pyproj/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pyproj/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement pyproj (from versions: none)
ERROR: No matching distribution found for pyproj
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: There was an error checking the latest version of pip.

**Comment by reyery** [comment]
@AWillmann thanks for report this issue. There seems to be some updates to the dependencies of CEA that is causing this issue, namely `geopandas` and `pyproj`. Unfortunately, due to how CEA is packaged for Windows, there is some problem with the python environment where pip/conda is not accessible through the CEA console. Because of this, there is no straightforward way for users to update the python dependencies for CEA (unless you try to recreate the conda environment manually, and update some references to files). The only way now to solve it is to uninstall and install the latest version of CEA again (which I understand is not ideal).

However, I am currently working on a way to make installation and updating CEA easier, so that users can avoid reinstalling CEA every time there is new version. But I probably can only finish it at the end of the month, given the time I have to dedicate to this.

I suggest trying the reinstall approach for now and let me know if that solves it.

**Comment by AWillmann** [comment]
@reyery Thanks for your quick reply. I need the 3.18 as I am using a German database with my students that only works with this version. I tried re-installing, however re-istalling CEA also does not work for the same reason: 
.....
Pip installing CityEnergyAnalyst==3.18.0

C:\Users\an1123\CityEnergyAnalyst>REM Use the packed conda environment to pip install arguments 

C:\Users\an1123\CityEnergyAnalyst>CALL "C:\Users\an1123\CityEnergyAnalyst\cea-env.bat" 

(CEA) C:\Users\an1123\CityEnergyAnalyst>REM call pip... 

(CEA) C:\Users\an1123\CityEnergyAnalyst>CALL "C:\Users\an1123\CityEnergyAnalyst\Dependencies\Python\python.exe" -m pip install --force-reinstall --no-deps "C:\Users\an1123\CityEnergyAnalyst\Dependencies\cityenergyanalyst.tar.gz" 
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Processing c:\users\an1123\cityenergyanalyst\dependencies\cityenergyanalyst.tar.gz
Building wheels for collected packages: cityenergyanalyst
  Building wheel for cityenergyanalyst (setup.py): started
  Building wheel for cityenergyanalyst (setup.py): finished with status 'done'
  Created wheel for cityenergyanalyst: filename=cityenergyanalyst-3.18.0-py3-none-any.whl size=34813621 sha256=065ecc63b7d7c9143b5018963ee6833910167b6fbae490fa65e3b2e2dffedacc
  Stored in directory: C:\Users\an1123\AppData\Local\Temp\pip-ephem-wheel-cache-q1jpz87p\wheels\7a\5d\f1\c3bbfce45a06db8ed3caa13b99a34e6e882ab5707845535143
Successfully built cityenergyanalyst
Installing collected packages: cityenergyanalyst
  Attempting uninstall: cityenergyanalyst
    Found existing installation: cityenergyanalyst 3.8.0a0
    Uninstalling cityenergyanalyst-3.8.0a0:
      Successfully uninstalled cityenergyanalyst-3.8.0a0
Successfully installed cityenergyanalyst-3.18.0
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
pip install cityenergyanalyst==3.18.0 returned 0
Traceback (most recent call last):
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\an1123\CityEnergyAnalyst\Dependencies\Python\Scripts\cea.exe\__main__.py", line 4, in <module>
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\cea\interfaces\cli\cli.py", line 14, in <module>
    import cea.config
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\cea\config.py", line 13, in <module>
    import cea.inputlocator
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\cea\inputlocator.py", line 9, in <module>
    import cea.schemas
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\cea\schemas.py", line 14, in <module>
    import geopandas
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\geopandas\__init__.py", line 3, in <module>
    from geopandas.geoseries import GeoSeries  # noqa
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\geopandas\geoseries.py", line 9, in <module>
    from pyproj import CRS, Transformer
  File "c:\users\an1123\cityenergyanalyst\dependencies\python\lib\site-packages\pyproj\__init__.py", line 50, in <module>
    from pyproj import _datadir
ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.
"cea --help" returned 1
Installation failed - see Details

**Comment by reyery** [comment]
Ah I see, that definitely complicates things a little. In that case, I think the fastest way to solve this is to manually create the conda environment for CEA v3.18.

It seems like you have access to a local conda environment on your machine (if not you can try installing conda using mambaforge [here](https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe)). I recommend installing `mamba` to your conda to help speed up the dependency solving.
(you would need to run all commands below in a terminal that has access to conda)
```shell
conda install mamba -n base -c conda-forge
```

First, you can download the source code zip for v3.18 [here](https://github.com/architecture-building-systems/CityEnergyAnalyst/archive/refs/tags/v3.18.0.zip). After you extract it, there should be an `environment.yml` file in the folder. You can create the CEA conda environment by running the command:

```shell
mamba env create -f PATH_OF_ENVIRONMENT_FILE
# Example
# mamba env create -f C:\User\foobar\Downloads\CityEnergyAnalyst-3.18.0\environment.yml
```

Once the conda env is created, you would need to activate the conda environment and install CEA.
```shell
# Activate CEA conda environment
conda activate cea

# Install CEA to conda environment
pip install PATH_OF_SOURCE_CODE
# Example
# pip install C:\User\foobar\Downloads\CityEnergyAnalyst-3.18.0
 ```
 
 After this, every time you want to open the CEA Dashboard Application, you would need to manually start the CEA backend first.
```shell
# Activate CEA conda environment
conda activate cea

# Run CEA Dashboard backend
cea dashboard
```
Wait for it to show `start socketio.run` before opening the dashboard application.

Let me know if that works.

**Comment by reyery** [comment]
Anyway, just to confirm so I can investigate this further, v3.18 has been working on your machine all the while, until (maybe) the new windows update was installed? 

It could be something related to #3050, regarding some change of how DLLs are loaded. Potentially, most older versions of CEA might not work now (which could be a problem).

**Comment by AWillmann** [comment]
I tried your suggestion. At step 3 installing CEA to conda environment, I get the same error: 
![CEA error 3](https://user-images.githubusercontent.com/33447712/211823836-c4fe0576-6d65-4e21-a64c-234b868af6a9.JPG)

**Comment by AWillmann** [comment]
regaring #3050 How do I do: .... then set the USE_PATH_FOR_GDAL_PYTHON=YES environment variable to feed the PATH into os.add_dll_directory(). ??

**Comment by reyery** [comment]
Could you try running `python -m pip install --upgrade pip` and see if that upgrades `pip`.

**Comment by AWillmann** [comment]
I did. "Requirement already satisfied"

**Comment by AWillmann** [comment]
> Anyway, just to confirm so I can investigate this further, v3.18 has been working on your machine all the while, until (maybe) the new windows update was installed?
> 
Yes, I can confirm this.

**Comment by reyery** [comment]
Could you try the steps found here https://stackoverflow.com/questions/54394764/pip-is-configured-with-locations-that-require-tls-ssl-however-the-ssl-module-i ? I have a feeling it has something to do with some settings on your machine.
