### ISSUE TITLE
Outdated links in documentation 

### ISSUE THREAD

**Issue by c0nb4** [architecture-building-systems/CityEnergyAnalyst#3286]
**Describe the bug**
In the documentation a wrong link is provided. 

The links is: 

https://www.cityenergyanalyst.com/blog it should be https://www.cityenergyanalyst.com/blogs 

The link can be found here: https://city-energy-analyst.readthedocs.io/en/latest/tutorials.html#users 

**To Reproduce**
1. Go to ' .../latest/tutorials.html#users" 
2. Click on 'Blog Posts' 
3. See error

**Expected behaviour**
The CEA Blog should appear. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/49240249/217766675-773c3b71-8c17-4a4e-9246-4eba606d67eb.png)

**Comment by shizhongming** [comment]
Thank you @c0nb4
It is now fixed the link.
