### ISSUE TITLE
This error shows up while creating a scenario using osmzone_helper: module 'osmnx' has no attribute 'geometries'

### ISSUE THREAD

**Issue by Arunim21** [architecture-building-systems/CityEnergyAnalyst#3288]
**Describe the bug**

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

**Comment by lguilhermers** [comment]
Closing since it is a repeated issue from #3289
