### ISSUE TITLE
More modifying options in GUI

### ISSUE THREAD

**Issue by chrisbay914** [architecture-building-systems/CityEnergyAnalyst#3291]
**Describe the feature you would like to have**
I would like an option in the GUI to have input to change the heated area and not just rely on "floor area * numbers of floors". 

**Describe the end purpose of this feature**
When using an Energy performance certificate (EPC) to validate the model, the heated floor area from the EPC and the simulated one in CEA can differ by 20-30%.

**Describe the end-user of this feature**
Students, researchers, master thesis work

**Comment by lguilhermers** [comment]
Hi @chrisbay914,
I am not sure I fully got your request. But CEA already contains a paremeter 'Hs_ag'. It represents the fraction of conditioned spaces (for both cooling and heating) and seems to be exactly what you want to add. 
Please check it out and see if this satisfies your needs. Thanks!

**Comment by lguilhermers** [comment]
Closing this issue as it seems to have been fully clarified already.
