### ISSUE TITLE
Error when starting CEA

### ISSUE THREAD

**Issue by matttuz** [architecture-building-systems/CityEnergyAnalyst#3294]
**Describe the bug**
CEA doesn't start.

**To Reproduce**
1. Installed it.
2. Tried to start "Dashboard".

**Screenshots**
![grafik](https://user-images.githubusercontent.com/129857742/229785733-bf6e7bde-6700-47e7-b2ea-695b0e2e4fb7.png)

**Hardware (please complete the following information):**
 - OS and version: **Windows 11** !
 - Version of CEA v. 3.32.0

I know CEA is tested for Windows 10. Does this error mean, it doesn't run on Windows 11?

**Comment by jimenofonseca** [comment]
@reyery do you know what the problem may be? does it run at your end?

**Comment by jimenofonseca** [comment]
@shizhongming the installation seems to not be working in new versions since as far as January 2023. Is perhaps somebody looking at it? I can not see branches with the topic at hand

**Comment by shizhongming** [comment]
Thank you @matttuz for keeping us updated. I will close this issue now. 
We will investigate the compatibility of CEA on Windows 11.
