### ISSUE TITLE
cea simulation energy demand error

### ISSUE THREAD

**Issue by yu00oo** [architecture-building-systems/CityEnergyAnalyst#3295]
**Describe the bug**
I followed the video introduction and make a test (use Zurich as a test). When i did demand simulation, it happends error.

  "use-dynamic-infiltration-calculation": false,
  "overheating-warning": true,
  "resolution-output": "monthly"

**To Reproduce**

**Expected behaviour**
i cannot do the simulation

**Screenshots**

**Hardware (please complete the following information):**
 - Windows 10
 -CEA 3.32.0

**Comment by lguilhermers** [comment]
@yu00oo 

From your message, we can't trace back the type of errors that are happening. The 3 lines you posted seems to show only some configuration from the simulation. Can you try running again and copy the whole error?
Also, it would be good to try other scenarios and see if you get the same type of error.
