### ISSUE TITLE
Storage Capacity Plugin development

### ISSUE THREAD

**Issue by jmsx13** [architecture-building-systems/CityEnergyAnalyst#3297]
Dear City Energy Analyst team,

By request of the Center for Innovation, Technology and Policy Research IN+ part of the University of Lisboa, I am developing a Plugin in CEA, as part of my PhD research at the Instituto Superior Técnico, to estimate the storage benefits of solar energy in UBEMs. I am using the result data generated by other processes of CEA, like the building's total electricity consumption, end-use water demand, and the total electricity generated by PV panels and Heat by solar collectors, to simulate the behaviour of battery power banks, solar-heated water tanks and hydrogen production, storage and supply. 

The main goal of the project is to increase the analysis abilities of CEA by simulating the behaviour of storage systems to predict if their application has technical benefits, and develop opensource tools to help users and decision-makers during energy planning and future research of the Centre. Since storage is quite a fundamental element of an energy system, we would be grateful if you consider adding this plugin to the CEA website. 

I have created a repository on GitHub to share it to you (I will share the Pull Request as soon as possible) and will continue working on the code and adding functionalities to the plugin, reason why I would be grateful to hear your comments and feedback to produce an efficient tool. I am still improving algorithms, and testing the results in different study cases, and will be happy to perform any change to make the source code fully compatible with the CEA structure. 

I have followed Daren Thomas' tutorials related to CEA plugins and continue reading the support material on your website. However, I consider that the code of my Plugin still can be improved, since this is my first project using Python, and I am pretty sure that I am not taking full advantage of the functionalities and benefits of this programming language. Finally, I would also appreciate your advice about some doubts I have on how to use the locator method to connect to CSV files and how to properly configure a Plot using YML. 

I look forward to your reply and will let you know as soon I have some code ready for review.

Best regards,

Jaime Cevallos Sierra
PhD candidate / Instituto Superior Técnico
jaime.cevallos@tecnico.ulisboa.pt

**Comment by lguilhermers** [comment]
Hi Jaime, thanks for your contributions to the CEA community.
Your plugin seems indeed relevant and would be a good addition to CEA's current features.
Let us know when you are ready to share the code and we will try to have one or two people to review it.

@shizhongming are you able to give some support on that?

**Comment by shizhongming** [comment]
@jmsx13 
Hi Jaime, thank you for your message.
We are very interested and I am happy that if I can support.

Do you want to use this link to book a meeting with me to know each your situation better?
https://calendly.com/shi-zhongming/30min

Regards, Zhongming
