### ISSUE TITLE
Threshold for PV installation in photovoltaic.py

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#330]
Research on what are the suitable threshold to set in Singapore.
Currently, there are two methods:
1. Certain percentage of the yearly global horizontal radiation.
2. Certain percentage of the maximum yearly radiation received in each building.

Additionally, we should look into:
3. Full load hours [h/yr] = Radiation[Wh/m2/yr]*PV efficiency/power generated per area[W/m2]
    E.g. To achieve 1000 h/yr of load with this system: PV eff.= 0.15, with 250W, 1.6m2 PV panel, the radiation should be larger than 1041666 Wh/m2/yr

**Comment by JIMENOFONSECA** [comment]
It was decided to use minimum solar irradiation per year. It is available in the current CEA version
