### ISSUE TITLE
Refine sensor categorization in photovoltaic.py

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#331]
The current categorization for surface azimuth (teta_z) is set for Zurich condition, the same condition for SG should be updated.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh is this implemented in the #424 ?

**Comment by shanshanhsieh** [comment]
no, the conclusion was that it requires additional research for SG.

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
