### ISSUE TITLE
database-migrator seems not to work in dashboard

### ISSUE THREAD

**Issue by lilaleu** [architecture-building-systems/CityEnergyAnalyst#3310]
**Describe the bug**
A clear and concise description of what the bug is:
I imported a geometry into a new scenario. Now I want to use "database-migrator" as suggested by dashboard. Clinking on respective icon it delivers the error "cea.ScriptNotFoundException: Invalid script name: database-migrator"
Same appears when I try over console. Is it a bug?

**To Reproduce**
1. Go to 'Input Editor'
2. Click on 'typology'
3. Click on 'database-migrator'

**Screenshots**
![grafik](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/127743306/2e969d03-fa22-4550-9a0c-2e4114b65949)

**Hardware (please complete the following information):**
 - OS and version:  Windows 11
 - Version of CEA you are using: V3.32.0 (taken from README)

**Comment by shizhongming** [comment]
@reyery 
Any chance you know this error?

**Comment by lilaleu** [comment]
@shizhongming @reyery 

Is it possible, that the Dashboard calls the database-migrator but actually the name of the function needed is "data_migrator" (https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/master/cea/datamanagement/data_migrator.py)?

Thx to @AlexJew for that idea!

**Comment by reyery** [comment]
@lilaleu Can I check if you have the CEA installed as developer version? 
Also could you try running `cea --version` in the CEA console to confirm the version of CEA that you have.

**Comment by lilaleu** [comment]
City Energy Analyst version 3.32.0

**Comment by lilaleu** [comment]
Recently, I have reinstalled CEA as the user version, not as developer version.

**Comment by reyery** [comment]
@lilaleu this is strange because it would only appear as `database-migrator` if you are on an older version. I could not recreate this issue on my end so it's hard for me to tell what is wrong. Could you try installing the developer version again and see if that fixes it?

**Comment by lilaleu** [comment]
Thanks for trying. I did install the developer version now. Now improvement so far. I even set up a scenario in Pycharm to be able to debug. What is strange that I even get to the point that my typology file got read in as occupancy_file dataframe with the correct data within (see screenshot). From here I don't know how to proceed or what could have gone wrong from this point, that in the end CEA can't read this file. 
![grafik](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/127743306/67ad502b-585b-4b41-89c1-42e0f347d12b)

**Comment by reyery** [comment]
What are the errors are you getting? Is the typology file being used created by the `data-migrator`?

**Comment by lilaleu** [comment]
No errors. Everything fine. I have attached the console-protocol from Pycharm and the typology file, that was copied from the original path into the created scenario after format checking by the code. It seems like it is just another scenario. But when I open it in my Dashboard, it shows me this: 
![grafik](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/127743306/4507f204-3ead-4b1f-99dc-40804974a876)
clicking on "database-migrator" gives me the error shown above. I hope that the attached project might help to understand the issue.
Thank you for your patience!
[cea-new-project.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/11598036/cea-new-project.zip)
[20230530_Create_new_sceanrio_via_PyCharm_geschwaerzt.pdf](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/11598039/20230530_Create_new_sceanrio_via_PyCharm_geschwaerzt.pdf)

**Comment by reyery** [comment]
@lilaleu I have managed to fix the `database-migrator` issue on the Dashboard but it can only be accessed using the dev version.

You could try launching the Dashboard using the command in the CEA console, and it should open in your browser.
```
cea dashboard --browser true
```
Do note that in this version, browsing for files would not work and would require you to enter the directory path manually.
![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/34395415/8b39b11f-8e7f-423e-b19c-ab9ee03a4508)

**Comment by reyery** [comment]
We have just released v3.33.0 which should fix this issue. You can try to reinstalling CEA to check if it solves this for you.
Closing this issue for now, unless there are any updates.
