### ISSUE TITLE
weather_helper: Could not find weather file

### ISSUE THREAD

**Issue by rachex** [architecture-building-systems/CityEnergyAnalyst#3312]
Dear All,
I m houving troubles when creating a new scenario, I have to select the area of interest for the zone file. When doing so, I get the following error message  : "weather_helper: Could not find weather file:"

![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/105674720/96af320c-dce3-47f0-9bee-343935a484b3)
[console.log](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/11463437/console.log)

Find attached the log file for more details on the error message.
Thank you in advance

**Comment by shizhongming** [comment]
Hi @rachex 

Thank you for the question.

When creating a scenario, in the Data Management Tool Section:
- tick "Weather helper"
- then click on the Gear Icon
- select your weather file
- then click save & close
Now, create-scenario should be working.

Let us know if it works here.
