### ISSUE TITLE
Optimization on Dashboard and commandline broken

### ISSUE THREAD

**Issue by jimenofonseca** [architecture-building-systems/CityEnergyAnalyst#3314]
**Describe the bug**
From the Interface or the commandline, the optimization does not run. It runs from pycharm though.

@reyery @MatNif how is this behavior from your side? 

here ist the output

<img width="1202" alt="Bildschirmfoto 2023-05-22 um 07 46 54" src="https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/8973186/69825126-2776-4599-a6af-e7b0469ac4a7">

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

**Comment by MatNif** [comment]
Hi Jimeno, just to check. Which optimissation script are you running exactly? Supply-system part I decentralised, part II centralised (old) or part II centralised-new (on the optimisation enhancement branch)?

**Comment by jimenofonseca** [comment]
Hi Mathias,Im running centalized optimization (II) on master branch.On 22 May 2023, at 08:26, Mathias Niffeler ***@***.***> wrote:﻿
Hi Jimeno, just to check. Which optimissation script are you running exactly? Supply-system part I decentralised, part II centralised (old) or part II centralised-new (on the optimisation enhancement branch)?

**Comment by jimenofonseca** [comment]
@MatNif oder @reyery any idea, I am stuck here :-)

**Comment by MatNif** [comment]
Hi @jimenofonseca. Sorry I was a bit busy these last few days. I'm actually in the process of trying to reproduce this error right now.
I don't quite understand the error message. The only thing I thought of that this could hint to, is that your deap library might not be up to date. But I'll be able to tell you more if I'm able to reproduce the error.

**Comment by MatNif** [comment]
Hey @jimenofonseca. So I tested it, but could not reproduce the error. We could have a call if you want to have a look at the issue together at some point.

**Comment by jimenofonseca** [comment]
Hi Matthias,

Cool, maybe just a thing. what dear library version do you have installed? maybe I can test there and let you know?
Jimeno
