### ISSUE TITLE
Bug in EV schedule

### ISSUE THREAD

**Issue by Juveria-shah** [architecture-building-systems/CityEnergyAnalyst#3327]
Under the Input Editor/schedules/electromobility the input accepts only binary values and can not be modified for integer values.
Path to reproduce error:
Input Editor -> Schedules->Electromobility-> Select building-> input EV number -> ERROR

![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/114220019/216f79ad-85f2-4f57-ae14-4c7ababbb770)

**Comment by Juveria-shah** [comment]
We tried to change the **type to float from int** this did not work.
We also tried to add **value: '{0.0, .. n}'** this did not work as well.

**Comment by jimenofonseca** [comment]
@reyery could you take a look, it looks that this maybe a front-end issue. It should be able to accept the values that one indicates in the schemas.yml. right?

**Comment by jimenofonseca** [comment]
tried once again to fix this locally on mac and windows. no success in any on the backend. suggestions? is there something hardcoded in the front-end?

**Comment by reyery** [comment]
Yes, it seems to be hardcoded in the front end, because schedules are actually not defined in `schemas.yml` because they do not necessary follow the column-row format. I would have to change it in the GUI.
