### ISSUE TITLE
Unit test not running

### ISSUE THREAD

**Issue by Juveria-shah** [architecture-building-systems/CityEnergyAnalyst#3329]
Running the unit test gives an error in the Master.

![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/114220019/1e6e3edc-2821-4320-a551-f10f4f914d47)

**Comment by MatNif** [comment]
Hi @Juveria-shah.
Are you running the tests in the master branch? Did you modify any code before trying to run the unit-test?
When I run the unit tests on the master branch on end, none of these errors appear.

**Comment by Juveria-shah** [comment]
Hi @MatNif ,
Yes, I ran the Master. I tried it again now, there are still some errors.

![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/114220019/1f137bce-1bf7-4322-8987-5ef56647f8fc)

**Comment by shizhongming** [comment]
Hi @Juveria-shah 
We noticed that you may have moved your CEA scenario's inputs file from `users\juh\` to `users\juh\videos` based on the zone.shp path in your screenshot. Try to move the inputs back and run again. If still doesn't work, try re-install CEA.
