### ISSUE TITLE
Improve pv generation calculation taking shading into account

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#333]
This includes the assumptions in two parts: optimal spacing and mutual shading.
Currently, the optimal array spacing is calculated according to the sun at 9am on winter solstice, and assuming no mutual shading between panels.
1. Different ways to estimate optimal spacing should be researched.
2. The effect of mutual shading should be taken into account when calculate PV generation. (one possible way: after pv array placement, take the panel geometries and perform radiation calculation once again)

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
