### ISSUE TITLE
Dahsboard running error

### ISSUE THREAD

**Issue by xinlus-arch** [architecture-building-systems/CityEnergyAnalyst#3337]
hey developers, this is Xinlu, I'm woking on CEA v3.33.0, followed your tutorial on youtube, which shows the version of 2.21. I found out that the module of Building Energy Demand in v3 differs from it in v2, and it always running error in Dashboard. Also, there is no option for output format in the section of Advanced.

I do appreciate your efforts on  this programme, hope to get your response! :D

![v3](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/57466931/afa3babf-1ba1-4264-968e-c7f35e4db97a)

**Comment by shizhongming** [comment]
Hi @xinlus-arch 
Thanks for the message. Can you post your error message here? How many buildings do you have in this scenario?
