### ISSUE TITLE
Radiation Module:  ModuleNotFoundError: No module named 'pyarrow'

### ISSUE THREAD

**Issue by KieranSQ** [architecture-building-systems/CityEnergyAnalyst#3341]
I am using the dashboard and have a ModuleNotFoundError: No module named 'pyarrow'.

How do I install the relevant modules? In the previous version, there were no issues. 

I am using the radiation module and this error occurs for both the simplified and normal version.

![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/34337935/1becaf88-f168-4aec-9c3d-c7a040dc8cb3)

**Comment by MatNif** [comment]
Hey @reyery,

Would you happen to have a solution for this? @shizhongming mentioned this error during the developers meeting as well. I just tested the script and got the same error prompt.
I've never fully understood how CEA sets up the conda environment. It looks to me like the 'pyarrow' dependency is missing in the environment, but I'm not sure what the systematic way is to update the dependencies. Would a simple update of 'environment.yml' solve the issue?

**Comment by shizhongming** [comment]
It seems this error appears only for people who previously have an older version of CEA working on their computer. For my fresh new laptop, all good.

**Comment by shizhongming** [comment]
Also, the CEA command line and pycharm function without an error..

**Comment by KieranSQ** [comment]
> It seems this error appears only for people who previously have an older version of CEA working on their computer. For my fresh new laptop, all good.

Unfortunately this is not the case for me! Brand new desktop with no previous version of CEA

**Comment by reyery** [comment]
@MatNif `pyarrow` has already been added to the `environment.yml` file. Currently there is no "automatic" way to update the CEA dependencies when we add a new one when using the dev version, and has to be done manually.

But it is strange that it is not installed for v3.33.0 since it should have already been packaged into the Windows setup.

@KieranSQ could you try manually installing the module using the CEA Console by running:
```
python -m pip install pyarrow
```

**Comment by KieranSQ** [comment]
@reyery, that works but the simplified version doesn't - gives me a value error. I will look into this in case it is me, but as the original works I am happy! 

Many thanks :)

**Comment by justinfmccarty** [comment]
Just did a fresh Windows install on an ETH lab computer with 3.33. Pyarrow was missing. Recommendation from @reyery worked well.
