### ISSUE TITLE
error running daysim radiation with own shp file created from fme

### ISSUE THREAD

**Issue by gerimous** [architecture-building-systems/CityEnergyAnalyst#3344]
**Describe the bug**
After running all of the data enrichment succesfully the radiation simulation does not work with one specific scenario. Scenarios using shp from QGIS and buildings via the osm feature however seem to not have this problem. The zone shp was created from a CityGML format using fme workbench, the attributes are all correct and cea accepts the file. It says daysim raypath variable might not have been set correctly, I inspected this multiple times however and also reinstalled daysim 4.0.

**To Reproduce**
1. Go to 'demand forecasting'
2. Click on 'building solar radiation and run simulation'

**Expected behaviour**
the radiation simulation to run smoothly 

this is the error : 
City Energy Analyst version 3.33.0
Running `cea radiation` with the following parameters:
- general:scenario = C:\Users\Moussa\reference-case-open\fme_2d
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- radiation:buildings = ['Base Surface']
  (default: [])
- radiation:use-latest-daysim-binaries = True
  (default: True)
- radiation:albedo = 0.2
  (default: 0.2)
- radiation:roof-grid = 10
  (default: 10)
- radiation:walls-grid = 200
  (default: 200)
- radiation:zone-geometry = 2
  (default: 2)
- radiation:surrounding-geometry = 5
  (default: 5)
- radiation:consider-floors = True
  (default: True)
- radiation:consider-intersections = False
  (default: False)
- radiation:rad-ab = 4
  (default: 4)
- radiation:rad-ad = 512
  (default: 512)
- radiation:rad-as = 32
  (default: 32)
- radiation:rad-ar = 20
  (default: 20)
- radiation:rad-aa = 0.15
  (default: 0.15)
- radiation:rad-lr = 8
  (default: 8)
- radiation:rad-st = 0.5
  (default: 0.5)
- radiation:rad-sj = 0.7
  (default: 0.7)
- radiation:rad-lw = 0.05
  (default: 0.05)
- radiation:rad-dj = 0.7
  (default: 0.7)
- radiation:rad-ds = 0.0
  (default: 0.0)
- radiation:rad-dr = 0
  (default: 0)
- radiation:rad-dp = 32
  (default: 32)
- radiation:daysim-bin-directory = C:\Users\Moussa\Documents\CityEnergyAnalyst\Dependencies\Daysim
  (default: C:\Users\Moussa\Documents\CityEnergyAnalyst)
- radiation:n-buildings-in-chunk = 100
  (default: 100)
- radiation:write-sensor-data = True
  (default: True)
Using Daysim binaries from path: c:\users\moussa\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation\bin\win32\bin64
Using Daysim data from path: c:\users\moussa\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation\bin\win32\lib
verifying geometry files
zone: C:\Users\Moussa\reference-case-open\fme_2d\inputs\building-geometry\zone.shp
surroundings: C:\Users\Moussa\reference-case-open\fme_2d\inputs\building-geometry\surroundings.shp
Getting geometry materials
Creating 3D geometry and surfaces
Saving geometry pickle files in: C:\Users\Moussa\reference-case-open\fme_2d\outputs\data\solar-radiation\radiance_geometry_pickle
Standardizing coordinate systems
Reading terrain geometry
Creating 3D building surfaces
Calculating terrain intersection of building geometries
Using 7 CPU's
Calculation of terrain intersection for building 1 completed out of 1
Using 7 CPU's
Calculation of terrain intersection for building 1 completed out of 206
Calculation of terrain intersection for building 2 completed out of 206
Calculation of terrain intersection for building 3 completed out of 206
Calculation of terrain intersection for building 4 completed out of 206
Calculation of terrain intersection for building 5 completed out of 206
Calculation of terrain intersection for building 6 completed out of 206
Calculation of terrain intersection for building 7 completed out of 206
Calculation of terrain intersection for building 8 completed out of 206
Calculation of terrain intersection for building 9 completed out of 206
Calculation of terrain intersection for building 10 completed out of 206
Calculation of terrain intersection for building 11 completed out of 206
Calculation of terrain intersection for building 12 completed out of 206
Calculation of terrain intersection for building 13 completed out of 206
Calculation of terrain intersection for building 14 completed out of 206
Calculation of terrain intersection for building 15 completed out of 206
Calculation of terrain intersection for building 16 completed out of 206
Calculation of terrain intersection for building 17 completed out of 206
Calculation of terrain intersection for building 18 completed out of 206
Calculation of terrain intersection for building 19 completed out of 206
Calculation of terrain intersection for building 20 completed out of 206
Calculation of terrain intersection for building 21 completed out of 206
Calculation of terrain intersection for building 22 completed out of 206
Calculation of terrain intersection for building 23 completed out of 206
Calculation of terrain intersection for building 24 completed out of 206
Calculation of terrain intersection for building 25 completed out of 206
Calculation of terrain intersection for building 26 completed out of 206
Calculation of terrain intersection for building 27 completed out of 206
Calculation of terrain intersection for building 28 completed out of 206
Calculation of terrain intersection for building 29 completed out of 206
Calculation of terrain intersection for building 30 completed out of 206
Calculation of terrain intersection for building 31 completed out of 206
Calculation of terrain intersection for building 32 completed out of 206
Calculation of terrain intersection for building 33 completed out of 206
Calculation of terrain intersection for building 34 completed out of 206
Calculation of terrain intersection for building 35 completed out of 206
Calculation of terrain intersection for building 36 completed out of 206
Calculation of terrain intersection for building 37 completed out of 206
Calculation of terrain intersection for building 38 completed out of 206
Calculation of terrain intersection for building 39 completed out of 206
Calculation of terrain intersection for building 40 completed out of 206
Calculation of terrain intersection for building 41 completed out of 206
Calculation of terrain intersection for building 42 completed out of 206
Calculation of terrain intersection for building 43 completed out of 206
Calculation of terrain intersection for building 44 completed out of 206
Calculation of terrain intersection for building 45 completed out of 206
Calculation of terrain intersection for building 46 completed out of 206
Calculation of terrain intersection for building 47 completed out of 206
Calculation of terrain intersection for building 48 completed out of 206
Calculation of terrain intersection for building 49 completed out of 206
Calculation of terrain intersection for building 50 completed out of 206
Calculation of terrain intersection for building 51 completed out of 206
Calculation of terrain intersection for building 52 completed out of 206
Calculation of terrain intersection for building 53 completed out of 206
Calculation of terrain intersection for building 54 completed out of 206
Calculation of terrain intersection for building 55 completed out of 206
Calculation of terrain intersection for building 56 completed out of 206
Calculation of terrain intersection for building 57 completed out of 206
Calculation of terrain intersection for building 58 completed out of 206
Calculation of terrain intersection for building 59 completed out of 206
Calculation of terrain intersection for building 60 completed out of 206
Calculation of terrain intersection for building 61 completed out of 206
Calculation of terrain intersection for building 62 completed out of 206
Calculation of terrain intersection for building 63 completed out of 206
Calculation of terrain intersection for building 64 completed out of 206
Calculation of terrain intersection for building 65 completed out of 206
Calculation of terrain intersection for building 66 completed out of 206
Calculation of terrain intersection for building 67 completed out of 206
Calculation of terrain intersection for building 68 completed out of 206
Calculation of terrain intersection for building 69 completed out of 206
Calculation of terrain intersection for building 70 completed out of 206
Calculation of terrain intersection for building 71 completed out of 206
Calculation of terrain intersection for building 72 completed out of 206
Calculation of terrain intersection for building 73 completed out of 206
Calculation of terrain intersection for building 74 completed out of 206
Calculation of terrain intersection for building 75 completed out of 206
Calculation of terrain intersection for building 76 completed out of 206
Calculation of terrain intersection for building 77 completed out of 206
Calculation of terrain intersection for building 78 completed out of 206
Calculation of terrain intersection for building 79 completed out of 206
Calculation of terrain intersection for building 80 completed out of 206
Calculation of terrain intersection for building 81 completed out of 206
Calculation of terrain intersection for building 82 completed out of 206
Calculation of terrain intersection for building 83 completed out of 206
Calculation of terrain intersection for building 84 completed out of 206
Calculation of terrain intersection for building 85 completed out of 206
Calculation of terrain intersection for building 86 completed out of 206
Calculation of terrain intersection for building 87 completed out of 206
Calculation of terrain intersection for building 88 completed out of 206
Calculation of terrain intersection for building 89 completed out of 206
Calculation of terrain intersection for building 90 completed out of 206
Calculation of terrain intersection for building 91 completed out of 206
Calculation of terrain intersection for building 92 completed out of 206
Calculation of terrain intersection for building 93 completed out of 206
Calculation of terrain intersection for building 94 completed out of 206
Calculation of terrain intersection for building 95 completed out of 206
Calculation of terrain intersection for building 96 completed out of 206
Calculation of terrain intersection for building 97 completed out of 206
Calculation of terrain intersection for building 98 completed out of 206
Calculation of terrain intersection for building 99 completed out of 206
Calculation of terrain intersection for building 100 completed out of 206
Calculation of terrain intersection for building 101 completed out of 206
Calculation of terrain intersection for building 102 completed out of 206
Calculation of terrain intersection for building 103 completed out of 206
Calculation of terrain intersection for building 104 completed out of 206
Calculation of terrain intersection for building 105 completed out of 206
Calculation of terrain intersection for building 106 completed out of 206
Calculation of terrain intersection for building 107 completed out of 206
Calculation of terrain intersection for building 108 completed out of 206
Calculation of terrain intersection for building 109 completed out of 206
Calculation of terrain intersection for building 110 completed out of 206
Calculation of terrain intersection for building 111 completed out of 206
Calculation of terrain intersection for building 112 completed out of 206
Calculation of terrain intersection for building 113 completed out of 206
Calculation of terrain intersection for building 114 completed out of 206
Calculation of terrain intersection for building 115 completed out of 206
Calculation of terrain intersection for building 116 completed out of 206
Calculation of terrain intersection for building 117 completed out of 206
Calculation of terrain intersection for building 118 completed out of 206
Calculation of terrain intersection for building 119 completed out of 206
Calculation of terrain intersection for building 120 completed out of 206
Calculation of terrain intersection for building 121 completed out of 206
Calculation of terrain intersection for building 122 completed out of 206
Calculation of terrain intersection for building 123 completed out of 206
Calculation of terrain intersection for building 124 completed out of 206
Calculation of terrain intersection for building 125 completed out of 206
Calculation of terrain intersection for building 126 completed out of 206
Calculation of terrain intersection for building 127 completed out of 206
Calculation of terrain intersection for building 128 completed out of 206
Calculation of terrain intersection for building 129 completed out of 206
Calculation of terrain intersection for building 130 completed out of 206
Calculation of terrain intersection for building 132 completed out of 206
Calculation of terrain intersection for building 131 completed out of 206
Calculation of terrain intersection for building 133 completed out of 206
Calculation of terrain intersection for building 134 completed out of 206
Calculation of terrain intersection for building 135 completed out of 206
Calculation of terrain intersection for building 136 completed out of 206
Calculation of terrain intersection for building 137 completed out of 206
Calculation of terrain intersection for building 138 completed out of 206
Calculation of terrain intersection for building 139 completed out of 206
Calculation of terrain intersection for building 140 completed out of 206
Calculation of terrain intersection for building 141 completed out of 206
Calculation of terrain intersection for building 142 completed out of 206
Calculation of terrain intersection for building 143 completed out of 206
Calculation of terrain intersection for building 144 completed out of 206
Calculation of terrain intersection for building 145 completed out of 206
Calculation of terrain intersection for building 146 completed out of 206
Calculation of terrain intersection for building 147 completed out of 206
Calculation of terrain intersection for building 148 completed out of 206
Calculation of terrain intersection for building 149 completed out of 206
Calculation of terrain intersection for building 150 completed out of 206
Calculation of terrain intersection for building 151 completed out of 206
Calculation of terrain intersection for building 152 completed out of 206
Calculation of terrain intersection for building 153 completed out of 206
Calculation of terrain intersection for building 154 completed out of 206
Calculation of terrain intersection for building 155 completed out of 206
Calculation of terrain intersection for building 156 completed out of 206
Calculation of terrain intersection for building 157 completed out of 206
Calculation of terrain intersection for building 158 completed out of 206
Calculation of terrain intersection for building 159 completed out of 206
Calculation of terrain intersection for building 160 completed out of 206
Calculation of terrain intersection for building 161 completed out of 206
Calculation of terrain intersection for building 162 completed out of 206
Calculation of terrain intersection for building 163 completed out of 206
Calculation of terrain intersection for building 164 completed out of 206
Calculation of terrain intersection for building 165 completed out of 206
Calculation of terrain intersection for building 166 completed out of 206
Calculation of terrain intersection for building 167 completed out of 206
Calculation of terrain intersection for building 168 completed out of 206
Calculation of terrain intersection for building 169 completed out of 206
Calculation of terrain intersection for building 170 completed out of 206
Calculation of terrain intersection for building 171 completed out of 206
Calculation of terrain intersection for building 172 completed out of 206
Calculation of terrain intersection for building 173 completed out of 206
Calculation of terrain intersection for building 174 completed out of 206
Calculation of terrain intersection for building 175 completed out of 206
Calculation of terrain intersection for building 176 completed out of 206
Calculation of terrain intersection for building 177 completed out of 206
Calculation of terrain intersection for building 178 completed out of 206
Calculation of terrain intersection for building 179 completed out of 206
Calculation of terrain intersection for building 180 completed out of 206
Calculation of terrain intersection for building 181 completed out of 206
Calculation of terrain intersection for building 182 completed out of 206
Calculation of terrain intersection for building 183 completed out of 206
Calculation of terrain intersection for building 184 completed out of 206
Calculation of terrain intersection for building 185 completed out of 206
Calculation of terrain intersection for building 186 completed out of 206
Calculation of terrain intersection for building 187 completed out of 206
Calculation of terrain intersection for building 188 completed out of 206
Calculation of terrain intersection for building 189 completed out of 206
Calculation of terrain intersection for building 190 completed out of 206
Calculation of terrain intersection for building 191 completed out of 206
Calculation of terrain intersection for building 192 completed out of 206
Calculation of terrain intersection for building 193 completed out of 206
Calculation of terrain intersection for building 194 completed out of 206
Calculation of terrain intersection for building 195 completed out of 206
Calculation of terrain intersection for building 196 completed out of 206
Calculation of terrain intersection for building 197 completed out of 206
Calculation of terrain intersection for building 198 completed out of 206
Calculation of terrain intersection for building 199 completed out of 206
Calculation of terrain intersection for building 200 completed out of 206
Calculation of terrain intersection for building 201 completed out of 206
Calculation of terrain intersection for building 202 completed out of 206
Calculation of terrain intersection for building 203 completed out of 206
Calculation of terrain intersection for building 204 completed out of 206
Calculation of terrain intersection for building 205 completed out of 206
Calculation of terrain intersection for building 206 completed out of 206
Generating geometry for surrounding buildings
Generating geometry for buildings in the zone of analysis
Using 7 CPU's
Generating geometry for building 1 completed out of 1
Creating radiance material file
Creating radiance geometry file
Converting files for DAYSIM
Traceback (most recent call last):
  File "c:\users\moussa\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\moussa\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\moussa\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\moussa\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "c:\users\moussa\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation\main.py", line 180, in main
    run_daysim_simulation(cea_daysim, zone_building_names, locator, config.radiation, geometry_staging_location,
  File "c:\users\moussa\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation\main.py", line 91, in run_daysim_simulation
    daysim.isolation_daysim(
  File "c:\users\moussa\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation\daysim.py", line 287, in isolation_daysim
    daysim_project.execute_ds_illum()
  File "c:\users\moussa\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation\radiance.py", line 336, in execute_ds_illum
    CEADaySim.run_cmd(command1, self.daysim_bin_directory, self.daysim_lib_directory)
  File "c:\users\moussa\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation\radiance.py", line 103, in run_cmd
    raise subprocess.CalledProcessError(process.returncode, cmd)
subprocess.CalledProcessError: Command 'ds_illum "C:\Users\Moussa\AppData\Local\Temp\cea_radiation\projects\chunk_0\chunk_0.hea"' returned non-zero exit status 1.

Transforming weather files to daysim format
Running command `epw2wea "C:\Users\Moussa\reference-case-open\fme_2d\inputs\weather\weather.epw" "C:\Users\Moussa\AppData\Local\Temp\cea_radiation\common_inputs\weather_60min.wea"`
place hochshculQuartier-Zur_-
latitude 47.377
longitude -8.55
time_zone -15.00
site_elevation 464
weather_data_file_units 1

Transforming radiance files to daysim format
Running command `radfiles2daysim "C:\Users\Moussa\AppData\Local\Temp\cea_radiation\common_inputs\rad2daysim.hea" -g -m -d`

Creating daysim project in: C:\Users\Moussa\AppData\Local\Temp\cea_radiation\projects\chunk_0\
Calculating and sending sensor points
Starting Daysim simulation for buildings: ['Base Surface']
Total number of sensors: 73
Writing radiance parameters
Executing hourly solar isolation calculation
Running command `gen_dc "C:\Users\Moussa\AppData\Local\Temp\cea_radiation\projects\chunk_0\chunk_0.hea" -dir`
=======================================================
= gen_dc: calculate direct daylight coefficients      =
= (this simulation may take several minutes to hours) =
=======================================================
calculate 65 direct daylight coefficients for variant static_system...

Running command `gen_dc "C:\Users\Moussa\AppData\Local\Temp\cea_radiation\projects\chunk_0\chunk_0.hea" -dif`
=======================================================
= gen_dc: calculate diffuse daylight coefficients     =
= (ignore WARNING: no light sources found)            =
= (this simulation may take several minutes to hours) =
=======================================================
calculate diffuse daylight coefficients for variant static_system...

Running command `gen_dc "C:\Users\Moussa\AppData\Local\Temp\cea_radiation\projects\chunk_0\chunk_0.hea" -paste`

Running command `ds_illum "C:\Users\Moussa\AppData\Local\Temp\cea_radiation\projects\chunk_0\chunk_0.hea"`

b'IN CASE YOU ARE USING DAYSIM UNDER WINDOWS, THE "RAPYPATH" VARIALBE MIGHT NOT HAVE BEEN SET CORRECTLY. TO TEST THIS, OPEN A DOS PROMPT AND TYPE \'set\'. AMONG THE VARIALBLES DISPLAYED SHOULD BE \'Raypath c:\\Daysim\\lib\'.\r\nPLEASE REFER TO THE DAYSIM TUTORIAL FOR MORE INFORMATION...fatal - file C:\\Users\\Moussa\\AppData\\Local\\Temp\\cea_radiation\\projects\\chunk_0\\chunk_0.dc does not contain any uncommented lines\r\n'

**Hardware (please complete the following information):**
- HP Laptop
 - OS and version: [ Windows 10]
 - Version of CEA you are using [e.g. v. 3.32.0]

**Comment by shizhongming** [comment]
@gerimous did you try another way to create the shapefile?
