### ISSUE TITLE
Mismatch between usage of fossil fuels and installed components

### ISSUE THREAD

**Issue by MatNif** [architecture-building-systems/CityEnergyAnalyst#3347]
**Describe the bug**
The new optimisation script regularly outputs district energy systems with supply systems that include completely unused components, i.e. the components have a sizeable capacity but are never actually in operation.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the 'Supply System Part II (centralised - new script)' on branch #3346  and select a DC system optimization with 'generate-detailed-outputs' set to True.
2. Run any scenario of your choosing.
3. Check out some of the 'NXXXX_annual_breakdown' files under 'outputs>data>optimisation_new>DCS_XXX>Supply_system_operation_details'
4. Observe the mismatch between fossil fuels used (=0) and the cost of supply system components using fossil fuels.

**Expected behaviour**
If no fossil fuels are used in operation. Components using fossil fuels should not be present in the supply system, i.e. have a capacity of 0.

**Comment by shizhongming** [comment]
@MatNif is working on PR to fix this.
