### ISSUE TITLE
Embodied emission update 

### ISSUE THREAD

**Issue by MMeshkinkiya** [architecture-building-systems/CityEnergyAnalyst#3351]
This is a request about essential updates in building Life Cycle Assessment (LCA) calculations in City Energy Analyst (embodied.py).

Whole building Life Cycle Assessment is typically calculated as:

_LCA=LCAproduction + LCAreplacment + LCAend of life + LCAoperation_

However, the LCAreplacement is currently missing in CEA. Therefore, following updates is necessary:
    •	 The LCA of replacement which considers the specific Reference service life for 
        each component.
    •	 Updating the Envelop dataset and adding new inputs as 
        Service_Life_Component (Reference service life).

The additional eq. to consider LCA of replacement is: 

_ni=(((SERVICE_LIFE_OF_BUILDINGS/Service_Life_Component)-1)+1)._

ni should be calculated for each component and multiplied to the GHG_component and the component's area.

Additional comments for source code:
     •	  In the Envelop dataset, GHG_component_KgCO2m2 refers to the sum of GWP layers of each component, which returns the total GWP as: 
  _Total GWP = GWP production + GWP end of life_(to be added)
     •	   To calculate the embodied emission of retrofitted building, only the additional 
           emissions should be considered in the df[total_column]. Which means only 
           the retrofitted components should be involved in the equation and the 
           unchanged components should be set to 0. (to be added)
     •	   Note: The new input variable (Service_Life_Component) is already added for CH dataset and are extracted from: https://doi.org/10.1016/j.dib.2021.107062. (added in #3354)

**Comment by martin-mosteiro** [comment]
@MMeshkinkiya Indeed, this is missing in CEA at the moment. The changes you proposed sound solid and would make a great first contribution to CEA if you're keen!

**Comment by shizhongming** [comment]
Hi @martin-mosteiro 
@MMeshkinkiya is currently helping CEA improve the LCA Component. Soon, she will create a pull request accordingly.
I will add you the reviewer of that PR :D
