### ISSUE TITLE
Radiation script grids seem to have different effect than intended?

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#3352]
**Describe the bug**
I'm running a number of case studies of different sizes in Singapore with the following parameters: `config.radiation.roof_grid = 10` and `config.radiation.walls_grid = 200` (default values). Per the documentation, `Use 200 (maximum) if you want only one point per surface.` Then I repeated the simulations with `config.radiation.roof_grid = 200` and `config.radiation.walls_grid = 10`. Here's a comparison of the number of roof and (total) wall surfaces for each case:
<img width="361" alt="image" src="https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/18548065/14f03c07-2c45-4cd2-a659-11c1105f3094">
(note: the number of wall surfaces for each orientation was always bigger for the second case, so I just added them up for clarity)

So, contrary to the CEA documentation, _increasing_ the roof grid caused there to be _more_ surfaces in the outputs. At the same time, though, _decreasing_ the wall grid _also_ led to _more_ surfaces in the outputs.

**To Reproduce**
1. Create any case study
2. Run the radiation script with the default parameters
3. Run the radiation script with different values for the roof and walls grids
4. Check number of surfaces generated in each case

**Comment by martin-mosteiro** [comment]
After checking the code, there's a typo in `calc_sensors_building` that causes the issue:
```
            sensor_dir, \
            sensor_cord, \
            sensor_type, \
            sensor_area, \
            sensor_orientation, \
            sensor_intersection = generate_sensor_surfaces(face,
                                                           grid_size.roof if srf_type == "roof" else grid_size.walls,
                                                           srf_type,
                                                           orientation,
                                                           normal,
                                                           intersection)
```
`srf_type` can only take the following values: `['walls', 'windows', 'roofs']`. So `grid_size.walls` is used for all surface types. Fixing this typo should solve the issue. I'll test and create a PR if successful.

**Comment by martin-mosteiro** [comment]
Indeed, after fixing that typo the number of surfaces in each case matches expectations:
<img width="361" alt="image" src="https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/18548065/0f4b9cd2-c958-4e4d-b9e6-8bae0f0053e3">
I'm creating a pull request now

**Comment by shizhongming** [comment]
Hi @martin-mosteiro 
Good catch of this error..
I was wondering why we never caught this error way before. After checking some older simulations, it seems this error emerged only after we have switch the radiation files from json to feather. 

I have tested and merged your PR. Thank you.
