### ISSUE TITLE
Unused files in the CEA databases

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#3371]
There are three files in the CEA databases that seem to serve no purpose: `.assemblies/SUPPLY_NEW.xlsx`, `./components/CONVERSION_NEW.xlsx`, and `./components/ENERGY_CARRIERS.xlsx`. They are not called by any functions and the names of at least two of them seem to indicate they are temporary placeholders that should not have been merged into `master`.

I believe this is the work of @MatNif, so could you please clarify what are these files and whether they should (a) be deleted, (b) replace the original files (i.e., `SUPPLY.xlsx` and `CONVERSION.xlsx`), or (c) any other option?

**Comment by shizhongming** [comment]
The new optimization script is set to replace the older on by early 2024. By then, there will not be this issue.
