### ISSUE TITLE
Mac installation guide issue (and one bonus question)

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#3372]
I was going through the Mac installation guide and noticed a couple issues.

First and foremost:
```
*Note*
_(Experimental)_ We have a script that can automate the process below. Just open a Terminal console and enter /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/architecture-building-systems/CityEnergyAnalyst/update-mac-installation/install/mac_installation.sh)" Continue on the next section to find out how to interact with CEA.
```
It's good that that script is listed as experimental, but that step doesn't actually work, as that html leads to a `404: Page Not Found`. If there's no newer version of that script, then that note should probably be removed.

Furthermore, I noticed that while `mamba` used to be a _recommended_ alternative to `conda`, it's now the only listed option. I've tried to install CEA on two (admittedly, old) laptops and keep running into issues due to `mamba`. I'm just wondering if it's a "your computer is old, neenrer, neener" issue or if there's an actual problem with the `mamba` installation as opposed to the old tried and tested `conda`.

Tagging @reyery since I suppose he made these changes.

**Comment by reyery** [comment]
Yeah I think the link for the script is wrong since that branch has been deleted, I could update it to point to the master branch and that should fix it.

As for mamba, I'm not the one who updated the installation docs for Mac. I could take a look at it nevertheless.

**Comment by martin-mosteiro** [comment]
About the `mamba` thing: there seems to have been a `bash` issue with my computer, after fixing that I can run mamba without a problem. That being said, I _did_ have to install `mambaforge` instead of `micromamba` in order to figure out that there was a problem, so I'm not sure whether `micromamba` works or not (it didn't work on the other old computer I tested on).

**Comment by shizhongming** [comment]
I have installed the mac version on both my and Arno's computer. `Micromamba` worked for both...yeah, we need to update the installation guide.
