### ISSUE TITLE
Weather file of Tallinn, Estonia was not found

### ISSUE THREAD

**Issue by nasimrad** [architecture-building-systems/CityEnergyAnalyst#3384]
**Describe the bug**

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

**Comment by shizhongming** [comment]
@nasimrad 
CEA has a number of built-in weather files. For other cities, we suggest you check: 
https://energyplus.net/weather.
Or, you may also want to try to open-data website of your local government.
