### ISSUE TITLE
Error while: Geometry creation for Solar-Radiation: "IndexError: list index out of range"

### ISSUE THREAD

**Issue by lilaleu** [architecture-building-systems/CityEnergyAnalyst#3385]
**Describe the bug**
When trying to run my workflow with the CEA workflow-function I get an error saying "IndexError: list index out of range" during the creation of geometries for the Solar-Radiation simulation. I have attached the protocol of my workflow-execution as txt. Please Scroll down to see the full error. 
**To Reproduce**
1. Run Solar Radiation for all buildings with worflow-yaml in CEA Console
2. Have all default settings
3. Wait for the error occur during geometry creation

**Expected behaviour**
I have found issue #1817 to face the same error-message. Back then the problem was an enclosed court with four outer walls facing each other (or hollowed facade). I looked for similar buildings in my scenario. Screenshots of them attached in Zip-folder. I thus deleted the first, most obvious one to see if that would solve the problem. It didn't. Before I am continuing deleting all my buildings step by step, I would like to find out, if there is a way to identify which building causes the issue. And maybe before this, if this is really the problem here. @martin-mosteiro can you maybe share you're experience with that?

Is this the same issue you encountered in #1817? Or is it something else?

Thank you for every kind of advice!
Best regards!
**Screenshots**
[Troubleshoot.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/12646389/Troubleshoot.zip)
[20230918_Error_ListIndexOutOfRange.txt](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/12646392/20230918_Error_ListIndexOutOfRange.txt)
[20230918_Error_ListIndexOutOfRange_WorkflowYML.txt](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/12646403/20230918_Error_ListIndexOutOfRange_WorkflowYML.txt)

**Hardware (please complete the following information):**
 - OS and version: Windows 10]
 - Version of CEA you are using [ v. 3.32.0]

**Comment by martin-mosteiro** [comment]
@lilaleu Thanks for checking out the old issues! I didn't even remember that old issue myself 😅 But indeed, now I remember I had to split up any buildings with interior courtyards to avoid that issue. The radiation script won't run for any buildings with interior courtyards, unfortunately (or even a podium with a tower in the middle, which is what I was actually running back then. Splitting them _does_ work, though, so:

- **this one is a problem**
<img width="378" alt="Enclosed_Building_01" src="https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/18548065/c83c5aa3-db26-4d5d-a9a6-f83bbea60727">
- **but this one is okay**
<img width="272" alt="Enclosed_Building_03" src="https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/18548065/f96f28a6-367f-4b10-99b4-f4a861acbe0b">

Looking at the image of the whole case study, the first building seems to be the only problematic one. If you're still getting an error after deleting that, then we might need to look into it further. If that's the case, could you maybe upload your case study somewhere so we can check it out?

**Comment by lilaleu** [comment]
[Troubleshoot_BBHof.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/12658612/Troubleshoot_BBHof.zip)

Thanks for your help @martin-mosteiro! 
Since I am a little under pressure for results I have figured a workaround to modify the same district with a slight different geometry, which was already running in a simulation with less modification of the geometries. I think the file from the workaround might be helpful for identification of the problematic buildings. 

I would like to emphasise my approach a little closer: I am preparing building data from German Governmental data to be usable for CEA. This is not an easy task. I assume the data quality from what I read is a lot better in Switzerland, than it is here. An (important) part of the data preparation is dissolving boundaries from buildung-complexes and making them represented as one in order to avoid messy outputs and uninterpretable demand results. The problematic building which we have already identified is one of them. Apparently it is not the only building since the error persists. For my work it facts like you mentioned about enclosed facades are extremely valuable to me. I have checked the files and I am not finding more. Maybe you can see more @martin-mosteiro .

In the ancient issue you could very clearly identify which building prorogued the error. Is there a possibility for the normal user to identify which exact buidling is making trouble? Or is it only feasible when using CEA in an IDE and do some serious debugging (which I am not capable of)? The error messages in dashboard or console  normally do not give much information about this, making troubleshooting hard to impossible for cases like this. I am highly appreciating hints for this! Thank you!

**Comment by martin-mosteiro** [comment]
Good to hear you found a work around, @lilaleu. For future debugging purposes, I recommend turning off multiprocessing and running the simulation again. Running without multiprocessing makes the error messages easier to read and lets you know which building is causing the issue. Maybe that can help in the next stage?

**Comment by lilaleu** [comment]
Ok I see... Only problem is that the calculations especially for Solar-Radiation will take ages with my hardware... Do you have experiences with lowering the sensor resolution for Solar Radiation? What impact does it have on the results? With a lower resolution calculations without multiprocessing might be more feasible then... Thanks for the advice. 

If you have a spare minute @martin-mosteiro to look at the not working file and tell me which building else is making trouble it would be great, since the data quality of this scenario is still a lot better than the workaround ;) 

Thank you so much!

**Comment by martin-mosteiro** [comment]
@lilaleu Actually, just by chance I just ran the following case study on CEA:
![Screenshot 2023-09-21 at 2 55 47 PM](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/18548065/23e5720d-d8e0-4591-8587-b7b43e7cc1aa)
And... the radiation script actually worked. So #1817 does *NOT* seem to be an issue anymore. So indeed, the problem with your case study is not the courtyards, it has to be something else.
I'll have a look at it some time and see if there's some other issue I can identify.

**Comment by lilaleu** [comment]
Hmm... This is very interesting... What do you think of overlapping geometries? Might this be an issue, or does CEA do have an overlapping correction during scenario creation (with input files, without helper-modules)?

**Comment by lilaleu** [comment]
Good to know! I will give it a try tonight (without multiprocessing) and let you know about the results. Very interesting insights, thank you @martin-mosteiro! 

Yes indeed, the files did not see a helper module before. As a feedback I would highly appreciate if the helper-modules would be translated into human readable flow charts with explanation. That might simplify the external data input, if one knew which data-prep to perform before. Just an idea.

**Comment by martin-mosteiro** [comment]
@lilaleu I did a quick check on geopandas and there's overlapping geometries in both shapefiles (i.e., the one that works and the one that doesn't). So while that's not ideal (we can find a solution for that later if you want, though), that is *not* what is causing the issue.

**Comment by lilaleu** [comment]
Alright. It's not an easy one then. 

Yes the overlapping geometries are paradox. In CEA dashboard it looks pretty much like there are many overlapping geometries and also geometries that overlap with the surrounding features. Applying the ArcGIS intersect tool on my zone file though, there isn't any intersection found within the zone file... Can you maybe post the output, which Polygons are supposed to overlap from geopandas? 

Okay but overlaps are not an urgent problem. It seems to work even with overlappings. My ideas of what the problem could be are coming to an end...
