### ISSUE TITLE
Temporary directory settings in "inputlocator.py"

### ISSUE THREAD

**Issue by TesLarry** [architecture-building-systems/CityEnergyAnalyst#3391]
**Describe the bug**
The temporary directory used in CEA is `C:\Users\<username>\AppData\Local\Temp`. This setting may cause some issues when running command `cea radiation` in parallel because a safer directory should be something like `C:\Users\<username>\AppData\Local\Temp\tmpusz704uq`

**Possible Solutions**
1. Go to file `CityEnergyAnalyst>Dependencies>Python>Lib>site-packages>cea>inputlocator.py`
2. Add `self._temp_directory = tempfile.TemporaryDirectory()` to line 35
3. Replace `return tempfile.gettempdir()` in line 1110 by `return self._temp_directory.name`

**Expected behaviour**
I'm not sure if this change may cause any conflicts, but it enables running `cea radiation` in parallel. Could you please check it?

**Hardware (please complete the following information):**
 - OS and version: Windows 11
 - Version of CEA you are using: v. 3.34.2

**Comment by reyery** [comment]
@TesLarry thank you for your comment. The proposed change definitely helps with a better way of creating temporary folders, and solves the issue that you have mentioned. I have pushed a PR regarding this change.
