### ISSUE TITLE
issue about construction_standard in city energy analyst

### ISSUE THREAD

**Issue by Xtian-hub** [architecture-building-systems/CityEnergyAnalyst#3394]
**Describe the feature you would like to have**
i would like to know, how could i get detail about construction_standar. becuse  i studying about city energy analis in America, but i notice the standard of construction only have code name in software.so,if  i conversion data from energy plus document '.idf' to 'excel' within software, what should i do. whether  i could take a look on something about it from somewhere.
**Describe the end purpose of this feature**
So I could visualize detail about construction_standar

**Describe the end-user of this feature**
a Student

**Provide Additional information if possible**
City Energy Analyst software
![屏幕截图 2023-09-27 192143](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/116425364/10c9b662-94e2-4b51-ab71-5ef2c69687b4)

**Comment by shizhongming** [comment]
@Xtian-hub 
You can find details and references of each assemblies (e.g., TIGHTNESS_AS1) in the `ASSMBLIES` TAB next to ARCHETYPES TAB. CEA currently does not have parser to convert EnergyPlus' inputs to CEA's.

**Comment by Xtian-hub** [comment]
您好，我是耿晓天我已经收到了您的来信，稍后我会回复，谢谢?7?8(?1?1ω?1?1)?1?7
