### ISSUE TITLE
I would like CEA to include Longitude and Latitude for each building selected

### ISSUE THREAD

**Issue by ShiZhongming** [architecture-building-systems/CityEnergyAnalyst#3399]
### Discussed in https://github.com/architecture-building-systems/CityEnergyAnalyst/discussions/3397

<div type='discussions-op-text'>

<sup>Originally posted by **meiyiliew** October  9, 2023</sup>
![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/133636025/f063f123-3389-46f7-a94c-1cf5d866215e)

Hi CEA development team, 
as previously discussed with Dr Shi ZhongMing, may I suggest for the longitude and latitude to be included within CEA upon selection of a building. This selection is described in the attached image. 

Please kindly liaise with me, my email meiyi.liew@sec.ethz.ch

Thanks,
M.Y. </div>

**Comment by shizhongming** [comment]
Hi @meiyiliew,

Thanks for the request.
Can you elaborate how you are going to use the lon and lat information for your project?
This will help us evaluate for the appropriate solution.

Best, Zhongming
