### ISSUE TITLE
The accuracy of weather data file

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CityEnergyAnalyst#34]
Usually, the weather data is about the airport or the nearest the weather station. But, for a specific site, because of the urban heat island effect, etc., the weather date should be different from the airport or weather stations.

There should be a procedure to generate such weather data for the specific site. Umi by MIT has such weather generator.

**Comment by JIMENOFONSECA** [comment]
I believe you mean this one?

http://dspace.mit.edu/handle/1721.1/99251

**Comment by gabriel-happle** [comment]
@shizhongming is it OK if I unassigned myself from this issue? Should we close it for now?

**Comment by JIMENOFONSECA** [comment]
we won't have this. DragonFly in Rhino can do this. One can use Dragon Fly before CEA if necessary.
