### ISSUE TITLE
RuntimeError: Standard_FailureCourbes non jointives raised from method Build of class BRepBuilderAPI_MakeShape

### ISSUE THREAD

**Issue by halsibai** [architecture-building-systems/CityEnergyAnalyst#3422]
I'm getting the following error while doing the radiation job 
my shape files are from qgis in the form of esri shapefile

how can i resolve this issue ?

**Comment by MatNif** [comment]
Hi @halsibai ,

This is an error I have never seen so far, but based on its wording, I assume this is likely to result from open geometries. Did you draw the building footprints yourself in QGis?
For context, the radiation script and other parts of CEA only work if the shapefiles abide by OSM standards. For example, building footprints need to be of type "polygon" or "multi-polygon", and the lines connecting at every corner need to meet perfectly (i.e. the coordinates of their endpoints need to be exactly the same). The latter also goes for the street network.

**Comment by halsibai** [comment]
> Hi @halsibai ,
> 
> This is an error I have never seen so far, but based on its wording, I assume this is likely to result from open geometries. Did you draw the building footprints yourself in QGis? For context, the radiation script and other parts of CEA only work if the shapefiles abide by OSM standards. For example, building footprints need to be of type "polygon" or "multi-polygon", and the lines connecting at every corner need to meet perfectly (i.e. the coordinates of their endpoints need to be exactly the same). The latter also goes for the street network.

the shape files are indeed imported from qgis, but they are all polygons and multi-polygons for sure, they are technically from OSM 

i checked the qgis files multiple times

**Comment by ShiZhongming** [comment]
We suggest to redo the shapefile.
