### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by nss-github** [architecture-building-systems/CityEnergyAnalyst#3425]
**Describe the bug**
I am new to CEA.
Obtained the following error message during the "Creating Scenario" phase:
zone_helper: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
There were no problems during the installation phase.
internet connection has been always active.
Happening everyday I try and with different network connections.

**To Reproduce**
during the "Creating Scenario" phase

**Expected behaviour**
Creation of Scenario should occur.

**Screenshots**

![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150924569/cb0347ed-91a2-4ec0-a646-1a907a21694d)

**Hardware (please complete the following information):**
- Windows 11 enterprise
 - Version of CEA you are using = 3.34.2

**Comment by ShiZhongming** [comment]
Hi @nss-github 

We could not replicate this issue.
Any idea what's going on on this case? @reyery 

Regards, Zhongming

**Comment by nss-github** [comment]
Hi,Apparently it is something related to corporate policies and firewalls.The service “overpass-api.de” was being called by the sw and the zscaler blocked it.It is now working with a computer outside the corporate settings.Thank you for your concern.Kind regardsNunoEnviado do meu iPhoneOn 20 Nov 2023, at 12:34, Zhongming Shi ***@***.***> wrote:﻿
Hi @nss-github
We could not replicate this issue.
Any idea what's going on on this case? @reyery
Regards, Zhongming
