### ISSUE TITLE
Make CEA installation faster

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#3426]
Since we have a large number of python dependencies, it some times takes very long to solve/install the dependencies. 

One way of solving it is to install only the dependencies that are difficult/cannot be installed using pip e.g. GDAL, using conda, and install everything else using pip. That would significantly speed up and simplify the python installation.

Another way is to use conda-lock to "presolve" the environment and create a lock file. Then installation could be done by using the lock file to get the exact python dependencies.

**Comment by ShiZhongming** [comment]
Faster installation is always nice! So far, we have not received too many complaints about the speed. Do you think the installer.dmg for mac could be something to be implemented soon?
