### ISSUE TITLE
Radiation sensorpoints use EPSG:32732, an inappropriate coordinate system

### ISSUE THREAD

**Issue by ShiZhongming** [architecture-building-systems/CityEnergyAnalyst#3427]
I am posting this issue on behalf of @yiqiaowang-arch. The original post on the CEA Forum is as follows. It can be found via https://cea2.flarum.cloud/d/22-radiation-sensorpoints-use-epsg32732-an-inappropriate-coordinate-system
(you may need to sign up to view this post)

"""
In solar radiation output (scenario\outputs\data\solar-radiation), a geometry.csv file describes the (x, y, z) coordinate for all sensorpoints in every simulated building.

However, these coordinates are stored in EPSG:32732, which describes the 6°-16°E, 0°-90°S zone of the earth in unit of meters(e.g., (450000, 15000000, 2.5)). Zurich is around 8.5°E 47°N, thus these points should be using EPSG:32632 that describes the northern hemisphere at the same longitude also in meters (e.g., (450000, 5000000, 2.5), notice that y coordinate is 10M smaller), but I'm not sure if this misuse of coordinate system would lead to any inaccuracy.

This issue might also leads to struggles in visualization workflow described in https://www.cityenergyanalyst.com/learning-camp/cea-v-01-visualise-cea-solar-simulation-results-on-building-envelopes. Normally, when using a grasshopper plug-in to import a .shp file, the importing algorithm will automatically choose the best fit coordinate system based on its latitude and longitude range. In our case, EPSG:32632 was automatically chosen. But this does not match the sensorpoint which locations are encoded in EPSG:32732.
As a result, a manually exported DXF file with EPSG:32732 is required to match the sensorpoint, and both don't fit to describe geometry in Zurich.

I have checked that the input zone.shp file is encoded in EPSG:4326, which describes the whole planet in latitude and longitude. I tried to locate the code but it went beyond my capability, so I'm still not sure what caused CEA's choice of coordinate system.

"""

**Comment by reyery** [comment]
@ShiZhongming I see that a PR has been merged for this issue. Can I confirm that this issue is fixed?
