### ISSUE TITLE
Idea: Choice to show scenarios without preview images

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#3429]
**Describe the feature you would like to have**
At the moment I'm creating a lot of Scenarios again (more than 100). Unfortunately, the project is getting really slow (by Dashboard usage). The cmder shows a lot of failed requests fo generate a preview images. I'd like to skip this timeconsuming requests and allow CEA to show the Scenarios without preview images. 

**Describe the end purpose of this feature**
saving time ;) 

**Describe the end-user of this feature**
User with many scenarios

**Comment by ShiZhongming** [comment]
Hi @Mar-Ges 

Thanks for the idea - we will discuss it.
Meanwhile, are you doing some batch processing?

**Comment by Mar-Ges** [comment]
Hi @ShiZhongming 

for the simulation I'm using my own workflow.yml.
But I didn't know how to simple change parameter there (as I don't know a way to create loops in .yml files)

**Comment by ShiZhongming** [comment]
Hi @Mar-Ges 
We have introduced a batch-processing workflow tool. It offers a loop/batch processing option.
Do you want to try it out?

**Comment by ShiZhongming** [comment]
When using the developer's version, on GitHub Desktop, navigate to `Branch idp-23-md` and `fetch-origin`. Then, relaunch your CEA Dashboard and you will find the tool under `utilities` as `Batch process Workflow`. 
We do not have any documentation about this tool yet and I will come up with something once we finished testing it with our students. If you run into any issues or would like to give us feedback, please reach out to me here or via email.
Thank you, @Mar-Ges!

**Comment by ShiZhongming** [comment]
We are taking out the entire Project overview page with CEA4. Hence, I am closing this issue.
