### ISSUE TITLE
SUPPLY_NEW.xlsx and CONVERSION_NEW.xlsx break the database visualisation in Dashboard

### ISSUE THREAD

**Issue by ddceruti** [architecture-building-systems/CityEnergyAnalyst#3432]
The development versions of cea/databases/CH which now contain SUPPLY_NEW.xslx and CONVERSION_NEW.xlsx break the visualization of the database within Dashboard if a database with the old format is imported. 

**To Reproduce**
1. Clone latest version of CEA
2. Try to import a database with the old file structure (so not containing SUPPLY_NEW.xlsx and CONVERSION_NEW.xlsx).

**Expected behaviour**
Normal visualization of the tables.

**Screenshots**
![grafik](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/52672045/b3abeecf-ab92-496f-9357-d8a7fbd32dc2)
Which is thrown in function cea/inputlocator.py line verify_database_template(self) which compares the new database to the CH database in the default configuration.

**Hardware (please complete the following information):**
 - Windows 10
 - CEA 3.34.2 or master branch

**Quickfix**
Just duplicate the SUPPLY and CONVERSION and rename them to SUPPLY_NEW and CONVERSION_NEW in the user defined database. However, be aware that the supply and optimization calculations will use the _NEW excel files instead of the old ones (maybe confirm @MatNif ?).

**Comment by MatNif** [comment]
Hi @ddceruti 

Very valid point. We will have to work on a fix for this in the next few months.
The database editor in the Dashboard actually breaks when you try to open the new databases, regardless of whether you've tried to import an older database in a project or not. There is some other issue there that we need to address.

As for your *Quickfix*: Your proposed method definitely works if you're not trying to run the new optimisation script. If you would like to be able to use the new optimisation script, you can copy the new databases (SUPPPLY_NEW, CONVERSION_NEW **& ENERGY_CARRIERS**) from the CEA's databases folder that you'll find in your developer version's folder structure, typically under: 'C:\Users\UserName\Documents\GitHub\CityEnergyAnalyst\CityEnergyAnalyst\cea\databases\CH' + 'assemblies' / ' components'

**Comment by jimenofonseca** [comment]
@MatNif  may I ask why going for two parallel databases? What makes the "NEW special" and if it is special and important why does not replaces the current one across the code. It seems rather prone to error integrating a database that may not be fully supported as part of the main code. Shall we just take them out until they get replaced for new code?

**Comment by jimenofonseca** [comment]
Got you,Then the right way would be to keep it in a branch until the PR is ready. Before is just cluttering.Master shall have what is ready to use. Branches for work in progress, right?Best,JimenoOn 12 Mar 2024, at 10:15, Mathias Niffeler ***@***.***> wrote:﻿
Hi @jimenofonseca, sorry for the late response. The NEW databases are geared towards the new optimisation script. The main difference with the old optimisation script (i.e., optimisation centralised) is that it offers more granularity in terms of the energy carriers that are utilised and that it allows for far more customisation in the considered technologies.
The idea is to replace the old optimisation with the new optimisation script entirely at some point this year. At that point, the NEW databases will also replace their base versions.

**Comment by MatNif** [comment]
You're generally correct. This could have remained on a separate branch for longer. Since this is a rather large development though we decided to release it to the master branch (while marking it as a 'beta version') before the last CEA user meeting. This allowed us to get wider testing in and make sure the branch was not riddled with unexpected errors.
