### ISSUE TITLE
Error: addr:housenumber

### ISSUE THREAD

**Issue by c0nb4** [architecture-building-systems/CityEnergyAnalyst#3439]
**Describe the bug**

When selecting data in a residential area in Berlin, CEA thowrs an error:  zone_helper: 'addr:housenumber'. 

**To Reproduce**
1. Go to: https://www.openstreetmap.org/#map=18/52.5262/13.30457 
2. Click on "Draw" 
3. Select Block between Tauroggener Straße and Mierendorffplatz, Brahestraße and Onsabrücker Straße
4. Error ist Trhown 
5. 
**Expected behaviour**

Scenario should be created. Tested it for other districts and areas in Berlin. 

**Screenshots**

Selected Area: 
![grafik](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/49240249/b483ce41-1531-4ced-b430-a5da6b39dafd)
 
 
 

**Hardware (please complete the following information):**
 - Windows 11
 - CEA 3.34.2

**Comment by ShiZhongming** [comment]
Hi @c0nb4 

Thanks for posting the issue. We have fixed it. However, we are not able to create a new release before Christmas. The next release is scheduled in January 2024.

There is a bypass to use the fixed CEA for now.  
If you have not installed the developer's version of CEA, we suggest you uninstall CEA and reinstall it and check the box for developer's version.
Then, please download GitHub Desktop and link the repository of CEA from your local computer and it should be located at somewhere: username/documents/github/cityenergyanalyst
Then, sync with the updated master branch.
Then, launch CEA Dashboard and your Berlin case should be working fine.

Let us know if it works or not.

Regards, Zhongming
