### ISSUE TITLE
Error Message: zone_helper: 'addr:housenumber'

### ISSUE THREAD

**Issue by aneihirio** [architecture-building-systems/CityEnergyAnalyst#3442]
[console.log](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/13777245/console.log)
**Describe the bug**
URL IS NOT FOUND
**To Reproduce**

**Expected behaviour**

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

**Comment by ShiZhongming** [comment]
@aneihirio this error will be resolved in the new released scheduled in this week.
