### ISSUE TITLE
Optimisation-new: file-naming issue with very long connevtivity vectors

### ISSUE THREAD

**Issue by MatNif** [architecture-building-systems/CityEnergyAnalyst#3445]
**Describe the bug**
When the connectivity vectors in the new optimisation script become too long (i.e. there are too many buildings in the district), the corresponding string of values which is used to name the created networks becomes too long to save in a filename.

e.g. 
10 buildings in a district could yield the network file -  0_1_2_1_2_2_2_0_1_0_N1001.inp

10000 buildings in a network could therefore yield the network file -
1_0_1_1_...[9996 more connectivity indicators]_N1001.inp
which is too long to be saved.

**To Reproduce**
Run district cooling optimisation new on any district containing more than 200 buildings.

**Expected behaviour**
The file naming convention should change automatically, when the number of buildings in the district becomes too large.

**Comment by jimenofonseca** [comment]
btw, Matthias. In the normal optimization there is a HEX code applied to avoid this. maybe you would like to take a look at this.
