### ISSUE TITLE
'Inputs Editor' turn to blank after running 'archetypes mapper' in CEA dashboard.

### ISSUE THREAD

**Issue by pengxiang-liu** [architecture-building-systems/CityEnergyAnalyst#3451]
**Describe the bug**
'Inputs Editor' turn to blank after running 'archetypes mapper' in CEA dashboard.

**To Reproduce**
1. Open CEA and create a new scenario
2. Run 'archetypes mapper'
3. Click 'Input Editor'

**Expected behaviour**
There should be a map and a table below

**Screenshots**
![Screenshot 2024-01-17 182724](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/34326353/ab3ccf1b-3835-41c5-9565-73e93065f7d2)

**Hardware (please complete the following information):**
 - Windows 11
 - 3.35.0

**Comment by ShiZhongming** [comment]
Hi @pengxiang-liu 
Thanks for posting it. We are just fixing it and will release a fixed version shortly.
I will also criculate how to update your installed CEA.
