### ISSUE TITLE
Data-Migrator for old Scenario: data incomplete 

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#3469]
I want to update a project which is 2 years old to the current CEA version. I used the data-migrator.
Unfortunately, the project remains incomplete. 

- i can see all necessary files in the folder view
- in CEA some are missing: all assemblies and components for the database can't be migrated as well as architecture, air-conditioning and supply systems
- CEA version 3.32.0 on windows

**Comment by Mar-Ges** [comment]
I just updated CEA to version 3.35.1 
(data still incomplete)

**Comment by reyery** [comment]
Hi @Mar-Ges, thanks for reporting this issue. 
Would it be possible for you to send us the scenario or an example of it, so that we can try to recreate and debug it on our end.

**Comment by Mar-Ges** [comment]
Hi @reyery,

you can find a scenario here: 
https://cloud.uni-weimar.de/s/prNDd3bgYzoiSDn

**Comment by reyery** [comment]
I have added a fix to the `data-migrator` here https://github.com/architecture-building-systems/CityEnergyAnalyst/pull/3471

Could you try reinstalling CEA in developer version and see if it works for you.

**Comment by ShiZhongming** [comment]
@Mar-Ges 
Did you resolve this? I saw it is just closed...

**Comment by Mar-Ges** [comment]
Yes! 
I solved both issues on an alternative way (= as I didn't change any components and supplysystems from the swiss database, I just "updated" manually this files from the current swiss database)
