### ISSUE TITLE
Revamp CEA installation

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#3475]
Installation of CEA still has a lot of room for improvement, for Windows, Mac and Linux. 

One major pain point is that there is no auto update feature. Users are not be able to receive new features or bug fixes easily. Most of the time, they are required to uninstall and reinstall CEA again just to get a small bug fix.

On Mac, the process is still very manual and requires the use of the command line. This might not be ideal as most users are not familiar or would not be comfortable with the command line.

**Comment by ShiZhongming** [comment]
I am closing this epic as both the installations for Windows and Mac have signifcantly improved including the auto-update possibility for both CEA 3 and CEA 4.
