### ISSUE TITLE
Program not starting on Windows 10

### ISSUE THREAD

**Issue by ev75** [architecture-building-systems/CityEnergyAnalyst#3493]
After installing the newest version of CEA, the program does not start. After clicking on the dashboard shortcut the logo of the program appears as if it would start but then nothing happens. I have tried reinstalling but I still get the same results. When uninstalling the newest version and installing the previous release the program starts right away on the same machines. 

Affected Platform: Windows 10, tested on 2 physical machines and one virtual machine

**Comment by ShiZhongming** [comment]
Hi @ev75 
Thanks for raising this issue.
We @reyery  have instroduced substantial changes to the installer lately. Hence, it might not be very stable at the moment.
A new release V3.35.4 is to be expected soonish to resolve this issue.

**Comment by moaapplepie** [comment]
Hi!
I have the same problem, the CEA dashboard is not launching. I re-installed the latest version, V3.35.4, yesterday and that's when the issue started.
