### ISSUE TITLE
Importing Scenarios: cea.api has no attribute 'create_new_scenario'

### ISSUE THREAD

**Issue by c0nb4** [architecture-building-systems/CityEnergyAnalyst#3494]
**Describe the bug**

When trying to import a previously generated scenario, the error  _create_new_scenario:_ module 'cea.api' has no attribute 'create_new_scenario': is displayed. 

**To Reproduce**
1. Go to https://github.com/buds-lab/elastic-buildings/tree/main/CEA_model/baseline/2018/inputs 

Download the input files. 

2. Open CEA Dashboard.
3. Click "Create new Scenario". 
4. Import Input files and select the zone.shp 
5. Error pops up. 

**Expected behaviour**
Shapes files and consistent naming should be imported into the project. 

**Hardware (please complete the following information):**
 - OS and version: Windows 11 Pro
 - CEA version: 3.34.2

**Comment by ShiZhongming** [comment]
Hi @c0nb4 
Thanks for raising this issue.
We are aware of this now. It will be fixed in the upcoming v3.35.4 to be released in this week.
