### ISSUE TITLE
creat scenario failed

### ISSUE THREAD

**Issue by yameima** [architecture-building-systems/CityEnergyAnalyst#3499]
**Describe the bug**
zone_helper: local variable 'response' referenced before assignment
**To Reproduce**
1. Go to '.
[console.log](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/14353847/console.log)
..'

**Expected behaviour**

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

**Comment by ShiZhongming** [comment]
Hi @yameima 
We could not replicate your error. Could you elaborate?

**Comment by yameima** [comment]
When I was creating new scenario, I selected the area I needed, and an error was reported in the creation, as shown in the picture. What is the reason for this, thank you for your help
![屏幕截图 2024-02-27 205811](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150877623/f68a2e08-8af2-4e1e-9fb7-10de090bf3f2)

**Comment by reyery** [comment]
Hi @yameima,

It seems that your machine is unable to connect to the OpenStreetMap api to fetch the geometries.
Could you try to open this link https://overpass-api.de/api/status on your browser and let us know if you are open to receive any response. Thanks!

**Comment by yameima** [comment]
> Hi @yameima,
> 
> It seems that your machine is unable to connect to the OpenStreetMap api to fetch the geometries. Could you try to open this link https://overpass-api.de/api/status on your browser and let us know if you are open to receive any response. Thanks!

Hi,when I open this link just like the follow picture
![Uploading image.png…]()

**Comment by yameima** [comment]
Hi,when I open this link just like the follow picture
![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150877623/caadfcfd-f716-4672-82d7-5480b49ca483)

**Comment by yameima** [comment]
The issue has been resolved and I am now able to create scenario. Thank you!

**Comment by reyery** [comment]
@yameima I am glad that it works for you now. Did you do anything to solve this on your end?

**Comment by xie-haonan** [comment]
Hi, how did you address this problem? I am now in the same trouble.

**Comment by xie-haonan** [comment]
@yameima I want your help could you please share your solution?
