### ISSUE TITLE
archetypes-mapper KeyError: '1'

### ISSUE THREAD

**Issue by KFSchlager** [architecture-building-systems/CityEnergyAnalyst#3508]
**Describe the bug**
When executing the archetypes-mapper an Error encounters. 
A copy from the Job Output:
___________________________
  _Traceback (most recent call last):
    File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\pandas\core\indexes\base.py", line 3653, in get_loc
      return self._engine.get_loc(casted_key)
    File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
    File "pandas\_libs\index.pyx", line 155, in pandas._libs.index.IndexEngine.get_loc
    File "pandas\_libs\index_class_helper.pxi", line 70, in pandas._libs.index.Int64Engine._check_type
  KeyError: '1'_
___________________________

After returning to the Input Editor the supply-systems is still empty
(the default CH Archetypes were used)

**To Reproduce**
1. Data management
2. Archetypes mapper
3. Run Script
4. See error in Current Jobs

**Expected behaviour**
No error and assigned supply-systems

**Screenshots**
![grafik](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150781552/7775189f-fbbf-491b-aa76-d7fe9a852be9)

**Hardware:**
 - Windows 10
 - Version of CEA  3.35.4

**Comment by ShiZhongming** [comment]
Hi @KFSchlager 
I tried to replicate your error but I could not.
Possible you share your Inputs folder with us? Then, we can take a look.

**Comment by KFSchlager** [comment]
Hi @ShiZhongming,
yes, of course, where/how can I share it with you?

**Comment by ShiZhongming** [comment]
zip your files and you can attach it when you post comment. @KFSchlager

**Comment by ShiZhongming** [comment]
In case anyone was looking for an answer to such key error "1" or "2"...

As we suspected, it is because of the building names. Please make sure the building names start with letters.
To change building names for existing scenarios, you can use the Rename Building Feature under Tab utilities.
