### ISSUE TITLE
Error in creating project in Dublin

### ISSUE THREAD

**Issue by nasimrad** [architecture-building-systems/CityEnergyAnalyst#3512]
**Describe the bug**

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

**Comment by ShiZhongming** [comment]
@nasimrad 
Can you provide more details about your error?
I just created a new scenario by drawing a random boundary in Dublin, Ireland and it was successful.

**Comment by nasimrad** [comment]
Hello,
Thanks for the email.
I tried to make a boundary in Dublin but it leads to the error.
May I ask you to share tutorial or resources help me to make a data of Dublin and start to do the simulation.

Best Regards,
Nasim

________________________________

**Comment by ShiZhongming** [comment]
Could you copy the error message and post it here?

We have some older materials that you can refer to. https://www.cityenergyanalyst.com/blog-posts/2019/06/28/2019-6-28-getting-started-with-your-own-project-1

**Comment by nasimrad** [comment]
![Picture1](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/87021714/1bf1139e-9898-4512-ac76-23be7d5ae351)

**Comment by nasimrad** [comment]
Thanks for the recommended link. 
I already downloaded the weather data .epw of Dublin, but the part of the tab, Broese the weather file is not active to add the weather file.
![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/87021714/11493642-37bd-450c-b9a8-3cfd809af5fb)

**Comment by reyery** [comment]
Hi @nasimrad,

For the "+ Browse for databases path" button bug, we have fixed it for the GUI but you would have to manually update it on your end for now, without having to reinstall it.

If you are using Windows, you can extract the attached file and replace the app.asar file that is found in your CEA installation path:
e.g.

```
C:\Users\foobar\Documents\CityEnergyAnalyst\dashboard\resources\app.asar
```
[app.asar.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/14422643/app.asar.zip)

Let me know if that works for you.
