### ISSUE TITLE
when I input the shp file to create a new scene, there were some thing wrong

### ISSUE THREAD

**Issue by yameima** [architecture-building-systems/CityEnergyAnalyst#3514]
![屏幕截图 2024-03-05 124750](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150877623/94ca1906-6503-4c40-b853-e00f6b34bad4)
**Describe the bug**

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

**Comment by ShiZhongming** [comment]
Hi @yameima 
As stated in the error message, you need to set a crs on the object (your shapefile) first.
