### ISSUE TITLE
Error using the simplified radiation model 

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#3517]
**ERROR**
`...`
`raise ValueError("List of sample buildings is the same as all buildings. "`
`ValueError: List of sample buildings is the same as all buildings. Consider selecting a subset of buildings instead.`
`...`

**To Reproduce**
1. try to use the simplified radiation without surroundings (I think that's the problem)

**Expected behaviour**
simulate the simplified radiation without surroundings

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - Version of CEA you are using [e.g. v. 3.35.1]

**Comment by ShiZhongming** [comment]
Hi @Mar-Ges 

To use the radiation-simplified script, you will have to unselect some buildings to produce a sample list (see figure below).
Let me know if it works or not works. : D

Regards, Zhongming

<img width="1196" alt="Screenshot 2024-03-08 at 23 38 23" src="https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/16640327/21075fb9-3a01-4932-8d1a-ddbbc59b2d35">

**Comment by yameima** [comment]
hello，when I use the simplified radiation model there were some errors,what I should do something to solve this problem,thank you
![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150877623/3fac3faf-32ea-41b2-b69f-529cc4739258)

**Comment by Mar-Ges** [comment]
Hi @ShiZhongming, 

thanks! It's both necessary to choose a selection of buildings AND necessary to have surroundings.

I'll close this issue, as yameima has a own.
