### ISSUE TITLE
New Input paramters. Are they really Needed?

### ISSUE THREAD

**Issue by jimenofonseca** [architecture-building-systems/CityEnergyAnalyst#3518]
i just say this in the code. It seems that this is not functional information and just brings 7+ parameters to take a look at while using CEA. I would refrain from adding Input paramters to the tables that one will not actively use in the simulation.

 @ShiZhongming are there strong reasons to keep such data as input parameters?

=======
      house_no:
        description: House number in the address(if any)
        type: string
        unit: 'NA'
        values: alphanumeric
        nullable: true
      street:
        description: Street name in the address (if any)
        type: string
        unit: 'NA'
        values: alphanumeric
        nullable: true
      postcode:
        description: Postal code in the address (if any)
        type: string
        unit: 'NA'
        values: alphanumeric
        nullable: true
      house_name:
        description: House number (if any)
        type: string
        unit: 'NA'
        values: alphanumeric
        nullable: true
      resi_type:
        description: Residential type, e.g. HDB for Singapore (if any)
        type: string
        unit: 'NA'
        values: alphanumeric
        nullable: true
      city:
        description: City name in the address (if any)
        type: string
        unit: 'NA'
        values: alphanumeric
        nullable: true
      country:
        description: Country 2-digit code in the address (if any)
        type: string
        unit: 'NA'
>>>>>>> master

**Comment by ShiZhongming** [comment]
Hi @jimenofonseca 
These parameters are assisting post-simulation analysis. They enable our users to link the simulation results to the actual building, either using street address or postal code.
