### ISSUE TITLE
Update installation guide for new radiation script

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#353]

**Comment by gabriel-happle** [comment]
@daren-thomas I changed the milestone as discussed. Also I noticed that nobody is assigned to this issue!

**Comment by JIMENOFONSECA** [comment]
@daren-thomas since you created the issue, what is it about?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA it's about updating the installation guide to include installing the prerequisites for the `cea radiation-daysim` script.
