### ISSUE TITLE
[WinError 1450] when running radiation simulation

### ISSUE THREAD

**Issue by yamei7ma** [architecture-building-systems/CityEnergyAnalyst#3538]
hi,what I should do to solve this problem, my cpu is R9-7940H, windows11,  I don't know why
```
Using Daysim binaries from path: D:\temp\cea-daysim-tempw7qfm7uv
Using Daysim data from path: None
verifying geometry files
zone: E:\XiaoMa\Documents\CEA\project01\test\inputs\building-geometry\zone.shp
surroundings: E:\XiaoMa\Documents\CEA\project01\test\inputs\building-geometry\surroundings.shp
Getting geometry materials
Creating 3D geometry and surfaces
Saving geometry pickle files in: E:\XiaoMa\Documents\CEA\project01\test\outputs\data\solar-radiation\radiance_geometry_pickle
Standardizing coordinate systems
Reading terrain geometry
Creating 3D building surfaces
Calculating terrain intersection of building geometries
Using 15 CPU's
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\pool.py", line 513, in _handle_workers
    cls._maintain_pool(ctx, Process, processes, pool, inqueue,
  File "D:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\pool.py", line 337, in _maintain_pool
    Pool._repopulate_pool_static(ctx, Process, processes, pool,
  File "D:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "D:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\popen_spawn_win32.py", line 73, in __init__
    hp, ht, pid, tid = _winapi.CreateProcess(
OSError: [WinError 1450] 系统资源不足
```

**Comment by reyery** [comment]
Hi @yamei7ma, thank you for reporting this issue. May I know how many buildings are you running for the radiation script. 
Based on the error, I am assuming that your machine ran out of memory, probably due to a large scenario.
Could you provide us with more information about our scenario (e.g. imported building geometries) so that we can investigate it on our end.

**Comment by yamei7ma** [comment]
Hi,thank you for your answer, I run the radiation sumilation for three buildings. This is the project which I use. Can you help me see what's wrong of it. Thank you very much.
[Uploading project01.zip…]()

**Comment by yamei7ma** [comment]
I try to choose other small distrct to create a new scenario, but this problem always happen.

**Comment by yamei7ma** [comment]
I use the example of reference-case-open to run, the same error happen, even my computer reboots.

**Comment by yamei7ma** [comment]
Hi,@reyery ,ok, I will reupload it again. 
[Uploading project01.zip…]()

**Comment by reyery** [comment]
Hi @yamei7ma, I am still not able to recreate this issue on our end on multiple different machines.

I am currently not too sure what causes this issue but maybe we could try something to figure it out.
Could you uninstall and reinstall CEA using this option "Install just for me"?
My guess now is that it could be something to do with administrator rights.

<img width="496" alt="image" src="https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/34395415/8e4c1334-fbd5-4fee-8761-3fecfe8b0929">

**Comment by yamei7ma** [comment]
Hi,@reyery,thank you for your answer,,ok,I will try it.

**Comment by reyery** [comment]
Hi @yamei7ma, did the solution work for you?

**Comment by yamei7ma** [comment]
@reyery,hi,the solution still doesn't work, as soon as I run the radiation simulation, the black screen gets stuck

**Comment by mietn** [comment]
i have the same issue, except for the error message, the whole CEA just crashes, please help!

**Comment by reyery** [comment]
@yamei7ma Unfortunately, I am still not able to reproduce it on my end. Would you be open to schedule a call so that I can troubleshoot it from your machine?

**Comment by reyery** [comment]
@mietn did you receive a different error message? Could you create a new issue and I look at it separately.

**Comment by yamei7ma** [comment]
@reyery hi, thank you for your answer, ok, what should I do to cooperate with you?Do you need remotely operate my computer to solve this problem?
Thank you for your help.

**Comment by marianajanuario97** [comment]
When i try to run radiation or demand i also get stuck on a black screen.

**Comment by reyery** [comment]
@yamei7ma could you send us an email over at cea@arch.ethz.ch and we can arrange a meeting from there.

**Comment by reyery** [comment]
Hi @yamei7ma, could you try installing using this installer and see if it works for you.
https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.35.6/Setup_CityEnergyAnalyst_3.35.6.exe

**Comment by yamei7ma** [comment]
OK,thank you for your help. Thank you for your reply. I'll try it right away

**Comment by yamei7ma** [comment]
@reyery OK,thank you for your help. Thank you for your reply. I'll try it right away

**Comment by yamei7ma** [comment]
@reyery hi, I‘m sorry to bother you again, I failed to download the file, the exe file does not exist.

**Comment by reyery** [comment]
@yamei7ma could you try the link again, I think something went wrong during the upload.

**Comment by reyery** [comment]
Hi @yamei7ma, I was wondering if you were able to test the new installer and if it solves your issue?
