### ISSUE TITLE
Optimisation: Heat rejection components are not operated correctly

### ISSUE THREAD

**Issue by MatNif** [architecture-building-systems/CityEnergyAnalyst#3542]
**Describe the bug**
When operating supply system components for heat rejection in the optimisation script, heat that is to be rejected can falsely be drawn from the available energy potentials. This makes no physical sense.

**To Reproduce**
1. Run an optimisation on a district with and without solar thermal panels
2. Compare heat rejection numbers between the two scenarios
3. You will notice that the heat rejection is considerably lower in the case with solar thermal panels even for very similar systems even though heat rejection should not (or only marginally) be affected by available energy potentials.

**Expected behaviour**
Heat rejection components should operate independently from available energy potentials.

**Comment by jimenofonseca** [comment]
which are heat rejection components?

**Comment by MatNif** [comment]
Hi @jimenofonseca.

In short heat rejection components are all components that can take excess heat from primary cooling or heating components and reject that heat to the environment. e.g. a cooling tower for a vapor compression chiller.
The concept of the current supply systems is described in cea/optimization_new/containerclasses/supplySystemStructure.py. If you need even more information you can find it in this report:
[CS2.0_DistrictCooling_TechnicalReport.pdf](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/14879796/CS2.0_DistrictCooling_TechnicalReport.pdf)
