### ISSUE TITLE
What is the GDAL version used by the last CEA version?

### ISSUE THREAD

**Issue by RicardoGomesIST** [architecture-building-systems/CityEnergyAnalyst#3546]
Hi there, I am trying to run CEA using python but I am stucked with the GDAL version I believe. At least It says :No module named 'gdal' although I have it:  "gdal                      3.5.3           py311h4bd9738_4    conda-forge"

**Comment by reyery** [comment]
Hi @RicardoGomesIST, thanks for reaching out. Could you give us more information about your CEA installation? (e.g. Windows/Mac, setup/manually installation, running it via command line, etc)

**Comment by reyery** [comment]
But to answer your question from the title, the latest CEA was tested against gdal v3.6.2

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/0863b8aa2e940d44900a5f9c6fa7a07ebea75606/conda-lock.yml#L5549-L5550

**Comment by reyery** [comment]
Closed because issue is stale. Kindly reopen if this is still and issue.
