### ISSUE TITLE
Tests pre- and post-PR differ

### ISSUE THREAD

**Issue by MatNif** [architecture-building-systems/CityEnergyAnalyst#3577]
**Describe the bug**
It seems that the tests that are run to check if a branch is valid in a PR and the tests that are run to check if a commit to master is valid differ from one-another. The latest commit to master [cd9df1a](https://github.com/architecture-building-systems/CityEnergyAnalyst/commit/cd9df1ad1cc2728d15204dbceb37094896ea8f79) is one such example. While in the PR all tests were successful.

**Expected behaviour**
I would typically expect the test pre- and post-PR to be identical, or for the test in the PR to be more comprehensive than the ones that are run on a specific commit after the branch is merged. Therefore I would propose that we adapt the tests.

**Comment by reyery** [comment]
For PRs, we are just running the "quick" version of the tests, while for pushes to master we are running the "slow" version of the tests. 
The only reason why this was done was to save time for merging PRs (20 min vs 1h 20 min). But I do see the point of running the same test for both situations. I am figuring out a way to make the "slow" version faster (#3580) which could help with this situation.
