### ISSUE TITLE
EmptyDataError when running schedule-maker 

### ISSUE THREAD

**Issue by KFSchlager** [architecture-building-systems/CityEnergyAnalyst#3581]
**Describe the bug**
Error when executing schedule-maker (EmptyDataError: No columns to parse from file
I compared my inputs with one of a working scenario, but couldn't find any differences and don't know how to solve this problem. Thank you for your help in advance

**To Reproduce**
I'm not sure, how to exactly reproduce it. I used cea in combination with qgis (zone with own building shp and not osm, connecting the archetypes to the house via qgis). Afterwards I was able to run the data management tools and solar radiation successfully, but get the error when using the scedule maker.

**Expected behaviour**
getting a successful status from the tool and having the scedules

**Screenshots**
![grafik](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150781552/70390c0f-eec3-4383-bfbe-6d6dc7a028c8)

**Hardware (please complete the following information):**
 - Windows 10
 - CEA v. 3.35.5

**Comment by ShiZhongming** [comment]
Hi @KFSchlager 

I checked your file and found a solution.
Could you try navigate` Folder ouputs>data>occupancy` and delete everything inside and run `building occupancy` again?

We are trying to figure out why it is causing an error..

**Comment by KFSchlager** [comment]
Hi @ShiZhongming

That worked for me, thank you very much!
