### ISSUE TITLE
Win Error 1450

### ISSUE THREAD

**Issue by KFSchlager** [architecture-building-systems/CityEnergyAnalyst#3585]
**Describe the bug**
Win Error 1450 not enough system ressources when running building energy demand

**To Reproduce**
I don't know how to reproduce it, it works on my laptop (win 10) but not on my remote simulation pc (win 11). Do I have to change anything in the permissions? Win Error 1455 paging file is too small also occurs. 

**Expected behaviour**
The simulation should work
**Screenshots**

**Hardware (please complete the following information):**
 - Windows 11
 - CEA v.3.35.5

**Comment by reyery** [comment]
Hi @KFSchlager, thanks for reporting this issue. We have encountered this issue before and seems to happen to only a few people. We have narrowed it down to a memory error probably due to numpy. We have implemented the fix in the main branch and would be releasing it soon.

**Comment by reyery** [comment]
Hi @KFSchlager, we have just released the new version v3.36.0. You can download the installer [here](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.36.0/Setup_CityEnergyAnalyst_3.36.0.exe). Let me know if it works for you.

**Comment by KFSchlager** [comment]
Hi @reyery , it worked for me, thank you!
