### ISSUE TITLE
How do I display occupied hours/ unoccupied hours summer & winter as a comfort chart? 

### ISSUE THREAD

**Issue by anjaWill** [architecture-building-systems/CityEnergyAnalyst#3589]
I would like to be able to choose in a comfort chart between the options:  occupied hours/ unoccupied hours summer & winter. Currently the comfort charts only shows unoccupied hours in winter, which does not have any impact on the building comfort analysis.... 
Can this be introduced by a dropdown button?

**Comment by ShiZhongming** [comment]
Hi @anjaWill 
On my CEA plot, it shows occupied hours...Hence, I am not exactly sure about your situation. Can you give an example?
![Uploading Screenshot 2024-05-28 at 10.01.21.png…]()

**Comment by ShiZhongming** [comment]
<img width="1023" alt="Screenshot 2024-05-28 at 10 01 21" src="https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/16640327/f5ffa7fe-1af6-47a8-a755-f218edfcc016">

**Comment by anjaWill** [comment]
![newplot](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150787078/5ce02213-918c-4c50-9d9c-69eae66aa700)
This is the plot from my dashboard - only unoccupied hours are displayed. However, the xls-file has 4 tabs with unoccupied/ occupied and summer/winter - does it only show one of the tabs and can I choose which one to show in the plot?

**Comment by ShiZhongming** [comment]
Is it possible to send your scenario inputs folder to me? We will take a closer look.

**Comment by ShiZhongming** [comment]
The unoccupied hours are shown because this building is a parking lot which is not climatised and has not occupancy. Hence, the CEA only plots the unoccupied hours.
