### ISSUE TITLE
radiation analysis of year 1991 - update possible?

### ISSUE THREAD

**Issue by anjaWill** [architecture-building-systems/CityEnergyAnalyst#3590]
I would like to update the radiation analysis data shown in the dashboard as a plot to the current weather file used in the project. Or at least data younger than 30 years. Currently the radiation anaylsis only shows the data of 1991.

**Comment by ShiZhongming** [comment]
Hi @anjaWill 

The plot only shows 1991 as it reads in the weather data's date information.
If you import a weather file is for a later year, it should be reflected on the plot accordingly.
