### ISSUE TITLE
Missing docs (images)

### ISSUE THREAD

**Issue by jimenofonseca** [architecture-building-systems/CityEnergyAnalyst#3614]
Some missing documentation: Pictures do not work anymore.

[Modeling building occupants in CEA – Part 1: Deterministic occupant model — City Energy Analyst (CEA)](https://www.cityenergyanalyst.com/blog-posts/2019/07/11/2019-7-11-modeling-building-occupants-in-the-cea-part-1-deterministic-schedules)
[Modeling building occupants in CEA – Part 2: Stochastic occupant model — City Energy Analyst (CEA)](https://www.cityenergyanalyst.com/blog-posts/2019/07/11/2019-7-11-modeling-building-occupants-in-the-cea-part-2-stochastic-occupant-model)

**Comment by ShiZhongming** [comment]
I was not able to find these images either as the website was migrated once in 2022.
