### ISSUE TITLE
Radiation error: "Terrain provided does not cover all geometries."

### ISSUE THREAD

**Issue by mietn** [architecture-building-systems/CityEnergyAnalyst#3616]
Hi, im working with the newes version of CEA and everytime i try to simulate the radiation, it gives me this error:

"raise ValueError('Terrain provided does not cover all geometries. '
ValueError: Terrain provided does not cover all geometries. Bounds of terrain must be larger than the total bounds of the scene."

Please help, because i need this for a uni project asap!
Thank You!

**Comment by ShiZhongming** [comment]
Hi @mietn 

Did you use the terrain helper to generate the terrain.tif?

**Comment by mietn** [comment]
Hi, yes i used every helper, the only one that didnt work was the treehelper..

**Comment by ShiZhongming** [comment]
Hi,
Currently, the tree helper can only import user-prepared tree data.

It is difficult to reproduce your issue based on the description. Will you be able to share the `Folder Inputs` of your scenario with us by sending it to cea@arch.ethz.ch?

**Comment by pnguyen-dh** [comment]
[inputs.zip](https://github.com/user-attachments/files/15918558/inputs.zip)
Hi, I also have the same issue, after the update to the newest version I think. I can copy and paste the terrain.tif file generated from the last version, and my the radiation will have then other error, I suppose this error come from the fact that my new input has less buildings than the old one. I'm not sure. Anw you can also find my old terrain.
```
outputs\data\solar-radiation\cea_radiation\projects\chunk_0\chunk_0.hea" -dir`

b'The system cannot find the path specified.\r\n'
```
[terrain.zip](https://github.com/user-attachments/files/15918582/terrain.zip)

**Comment by ShiZhongming** [comment]
Hi @pnguyen-dh 

Thanks for sharing the inputs file.
We were able to recreate the issue and we are working on fixing it.
