### ISSUE TITLE
Difference between "individual_PV".csv and PV_total_buildings values. 

### ISSUE THREAD

**Issue by Dashboard-IN3** [architecture-building-systems/CityEnergyAnalyst#3628]
Hi,
why is the sum of the column: PV_roofs_top_E_kWh of one individual building file (example: B1000_PV.csv), different from the respective building value in the "PV_total_buildings.csv" 

I did some calculations and for typically the values of the PV_total_buildings.csv are 68.8% of the sum of the individual buildings file (that as you know have hourly values). 

I am using the last CEA version

**Comment by ShiZhongming** [comment]
Hi @Dashboard-IN3 

I have just checked the PV results of two scenarios: one in Zurich and one in Singapore. I was not able to reproduce your issue. In my two scenarios, the values in PV_total_buildings matched the sum of the corresponding values in the individual files.
I can take a look at your scenario if you want to share your inputs file with us.

**Comment by Dashboard-IN3** [comment]
I ran again the PV script and had the same question. 
Input folder. 
https://www.dropbox.com/scl/fo/67fbyct72gmnu550044pg/AEr8nvmIQva6JUQONR127e0?rlkey=6juscdf52b9k45ex7xkfwvt51&dl=0
ty

**Comment by ShiZhongming** [comment]
Thanks for sharing the inputs.
I still could not reporoduce your issue...I attach my results here.
https://www.dropbox.com/scl/fo/wnt1d27f1i3qtz624u5u9/AC1d_I0QAPh7Q0GwSi-oeOo?rlkey=uc40dnyx42ffx3do2568w4mrx&dl=0

**Comment by Dashboard-IN3** [comment]
I am so sorry. I had two files with the same name.... It is working. Thank you for your fast answer and again my apologies...

**Comment by ShiZhongming** [comment]
No problem!
