### ISSUE TITLE
Optimisation: Multiple Consecutive Runs Mix in Results

### ISSUE THREAD

**Issue by MatNif** [architecture-building-systems/CityEnergyAnalyst#3629]
**Describe the bug**
If a user runs the optimisation script multiple times in the same scenario, the result folder often ends up having the results from the latest run mixed in with some of the results from previous runs. 
Due to an element of randomness in the trial-and-error process that leads to the identification of near-Pareto-optimal networks and supply systems (i.e., the genetic algorithm), the individual solutions that are output often vary in terms of network connection and sometimes even the number of networks installed. This varying structure of the energy systems also results in a varying structure of output files and folders for each optimisation run.
In the current code version, result files are overwritten if they already exist, but the result folders would not be cleared before that. Hence, some of the files from the previous runs may remain after rerunning the optimisation script.

**To Reproduce**
1. Simply run the optimisation script multiple times.
2. Have a look at the time stamps of the result files produced. 

**Expected behaviour**
Either:
A. Clear all results from previous runs if they already exist
or
B. Create a separate folder for the results of each new run

**Comment by ShiZhongming** [comment]
Thanks for raising this @MatNif.
I vote for a toggle allowing user to decide.

If keeping the exisiting files, the older folder will be removed.
If not keeping the existing files, a new folder will be created using the time of simulation. Example, centralised_11.36_2024.07.15.

Potentially this could be applied to more CEA features. For example the photovoltaics. User may want to compare using solar irradiation threshold at 800 or 200. By keeping both results, users can compare the impacts of applying different threshold.

What do you think? @reyery
