### ISSUE TITLE
surrounding helper distance resets

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/CityEnergyAnalyst#3646]
**Describe the bug**
When changing the buffer distance in "Surrounding helper", and I run the script, everything works fine. But the number isn't stored, once I click back on "Surrounding helper". 

**Expected behaviour**
should remember the distance

**Screenshots**
changing value, running script, looks good in input editor
![image](https://github.com/user-attachments/assets/15a19eb2-1b31-4331-b4c1-192dc74f2eac)

going back to Surroundings helper, default number shown
![image](https://github.com/user-attachments/assets/ceebaea4-f749-47df-8a49-c12367f98444)

**Hardware (please complete the following information):**
 - Windows 10
 - v. 3.37.1

**Comment by ShiZhongming** [comment]
Hi @christophwaibel 

Thanks for the recommendation.
Currently, if you click on `Save to Config` then the setting will be saved.
@reyery do you think we can auto-trigger `Save to Config` every time we click on `Run`? 
Users can always click `Reset` anyway to the default setting.

**Comment by ShiZhongming** [comment]
This is resolved with CEA4. Hence, I am closing it.
