### ISSUE TITLE
KeyError: 'primary_components' when running optimization-new

### ISSUE THREAD

**Issue by KFSchlager** [architecture-building-systems/CityEnergyAnalyst#3649]
**Describe the bug**
KeyError when running optimization-new (centralized optimization):
KeyError: 'primary_components'

**To Reproduce**
I am not sure how to reproduce the error,
it occurs, when i run optimization-new for district heating

**Expected behaviour**
No error, optimized network

**Screenshots**
![grafik](https://github.com/user-attachments/assets/c9f13a92-1afb-480a-a1c7-7cf795ee3650)

**Hardware (please complete the following information):**
 - Windows 11
 -  CEA v. 3.36.0

**Comment by MatNif** [comment]
Hi @KFSchlager,

Could you share the complete error message? These last few lines that you share are not quite enough to go by to identify what triggers the error in your case.

**Comment by KFSchlager** [comment]
Hi @MatNif,
I think I resolved the issue, my Supply excel input file was outdated and didn't include the columns for primary, secondary and tertiary components. Now it works.

Thank you
