### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by Justineliv** [architecture-building-systems/CityEnergyAnalyst#3654]
![Screenshot 2024-09-04 at 13 47 35](https://github.com/user-attachments/assets/72f03213-8bd9-4561-93d7-21e0860580a7)
**Describe the bug**
I have not managed to successfully install the program. I am running MAC intel Sonoma 14.4.1. I downloaded the non-developer CEA software for MAC intel today.  After dragging the install to applications and clicking on it, I get the attached message. after a minute. or two of initiation time.

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Hardware (please complete the following information):**
MAC OS Sonoma 14.4.1 Intel UHD Graphics 630 1536 MB
 - Version of CEA you are using [e.g. v. 2.31.1]
 - Console Version 1.1 (8.1.6.3)

**Comment by ShiZhongming** [comment]
Hi @Justineliv Apologies for the delayed reply, as we are a bit short-staffed before school started.
Could click on `Show log` and send us the log?

**Comment by ShiZhongming** [comment]
Please reopen this issue if needed.
