### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'code'

### ISSUE THREAD

**Issue by SNokay35** [architecture-building-systems/CityEnergyAnalyst#3656]
We are facing an error regarding Optimisation Part 2 

Applying fix for Apple Silicon
Applying fix for Apple Silicon
City Energy Analyst version 3.38.0
Running cea optimization-new with the following parameters:
- general:debug = False
  (default: False)
- general:scenario = /Users/piersergiodimaio/Documents/BIPCEA/distretto v2/Rymdgatan district - 2050 Scenario
  (default: {general:project}/{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- optimization-new:network-type = DH
  (default: DH)
- optimization-new:cooling-components = ['ABSORPTION_CHILLERS', 'VAPOR_COMPRESSION_CHILLERS', 'UNITARY_AIR_CONDITIONERS']
  (default: ['ABSORPTION_CHILLERS', 'VAPOR_COMPRESSION_CHILLERS', 'UNITARY_AIR_CONDITIONERS'])
- optimization-new:heating-components = ['BOILERS', 'COGENERATION_PLANTS', 'HEAT_PUMPS']
  (default: ['BOILERS', 'COGENERATION_PLANTS', 'HEAT_PUMPS'])
- optimization-new:heat-rejection-components = ['COOLING_TOWERS']
  (default: ['COOLING_TOWERS'])
- optimization-new:maximum-number-of-networks = 2
  (default: 2)
- optimization-new:objective-functions = ['system_energy_demand', 'anthropogenic_heat']
  (default: ['system_energy_demand', 'anthropogenic_heat'])
- optimization-new:generate-detailed-outputs = False
  (default: False)
- optimization-new:retain-run-results = False
  (default: False)
- optimization-new:available-energy-sources = ['power_grid', 'fossil_fuels', 'bio_fuels']
  (default: ['power_grid', 'fossil_fuels', 'bio_fuels'])
- optimization-new:available-energy-potentials = ['photovoltaic_panels', 'photovoltaic_thermal_panels', 'solar_thermal_panels', 'geothermal_energy', 'water_bodies', 'sewage']
  (default: ['photovoltaic_panels', 'photovoltaic_thermal_panels', 'solar_thermal_panels', 'geothermal_energy', 'water_bodies', 'sewage'])
- optimization-new:component-efficiency-model-complexity = constant
  (default: constant)
- optimization-new:systems-algorithm = NSGAIII
  (default: NSGAIII)
- optimization-new:systems-mutation-method = PolynomialBounded
  (default: PolynomialBounded)
- optimization-new:systems-crossover-method = Uniform
  (default: Uniform)
- optimization-new:networks-algorithm = NSGAIII
  (default: NSGAIII)
- optimization-new:networks-mutation-method = ClusterSwitch
  (default: ClusterSwitch)
- optimization-new:networks-crossover-method = ClusterSwap
  (default: ClusterSwap)
- optimization-new:building-clustering-method = Louvain
  (default: Louvain)
- optimization-new:networks-overlap-correction-method = Random
  (default: Random)
- optimization-new:ga-population-size = None
  (default: None)
- optimization-new:ga-number-of-generations = 3
  (default: 3)
- optimization-new:ga-mutation-prob = 0.1
  (default: 0.1)
- optimization-new:ga-crossover-prob = 0.3
  (default: 0.3)
- optimization-new:ga-mutation-eta = 0.5
  (default: 0.5)
- optimization-new:min-head-substation = 20.0
  (default: 20.0)
- optimization-new:hw-friction-coefficient = 100
  (default: 100)
- optimization-new:peak-load-velocity = 2.0
  (default: 2.0)
- optimization-new:equivalent-length-factor = 0.2
  (default: 0.2)
- optimization-new:peak-load-percentage = 100.0
  (default: 100.0)
- optimization-new:network-lifetime = 20.0
  (default: 20.0)
Time elapsed for loading buildings in domain: 0.6502599716186523 s
Time elapsed for loading energy potentials: 0.47604870796203613 s

Setting up optimisation algorithm:

Initializing domain:
1. Creating available supply system components...
Traceback (most recent call last):
  File "/Users/piersergiodimaio/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/worker.py", line 146, in worker
    run_job(config, job, server)
  File "/Users/piersergiodimaio/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "/Users/piersergiodimaio/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/api.py", line 60, in _call_
    self.runner.call_(*args, **kwargs)
  File "/Users/piersergiodimaio/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/api.py", line 38, in script_runner
    script_module.main(config)
  File "/Users/piersergiodimaio/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/optimization_new/domain.py", line 642, in main
    current_domain.optimize_domain()
  File "/Users/piersergiodimaio/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/optimization_new/domain.py", line 146, in optimize_domain
    self._initialize_energy_system_descriptor_classes()
  File "/Users/piersergiodimaio/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/optimization_new/domain.py", line 605, in _initialize_energy_system_descriptor_classes
    Component.initialize_class_variables(self)
  File "/Users/piersergiodimaio/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/optimization_new/component.py", line 73, in initialize_class_variables
    Component.code_to_class_mapping = Component.create_code_mapping(Component._components_database)
  File "/Users/piersergiodimaio/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/optimization_new/component.py", line 89, in create_code_mapping
    component_codes_in_tab = set(database[database_tab].code.values)
  File "/Users/piersergiodimaio/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in _getattr_
    return object._getattribute_(self, name)
AttributeError: 'DataFrame' object has no attribute 'code'

Could you help us to how to proceed?

**Hardware:**
 -  iOS 13.5.1 Ventura
 - Version of CEA 3.38.0

**Comment by MatNif** [comment]
Hi @SNokay35,

I'm sorry for not getting back to you sooner. Could it be that you either (A) created this case quite a while ago or (B) modified the components database in some respect? To me, it very much looks like there is something off about the components database, i.e., the database that holds a description of the heating, cooling, and electricity-generating technologies.

You could try updating your databases with the new defaults by running the 'Database initialiser' found under 'Tools>Utilities'. If you do need customised databases, please make sure you fill in all of the columns for the technologies you add.

I hope this helps.
