### ISSUE TITLE
Clipped list when entering buildings to sim in config

### ISSUE THREAD

**Issue by justinfmccarty** [architecture-building-systems/CityEnergyAnalyst#3657]
**Describe the bug**
I was listing out specific buildings to run with cea radiation in the config file. The first and the last building were not simulated. They seem to be clipped from the list... "building_list[1:-1], somehow?". I am not deep enough into the management of the config file to figure this one out :(. I also was having some issues with the DAYSIM binary option in the Advanced tab in the new dashboard (which is incredible by the way, nice work).

**To Reproduce**
1. Open your cea.config
2. Under Radation options enter the names of the buildings you want to sim ['B1020', 'B1021', 'B1022', 'B1023']
3. In console `run cea radiation`
4. See error in the parameters printout

**Expected behaviour**
Building list would be ['B1020', 'B1021', 'B1022', 'B1023'], not ['B1021', 'B1022']

**Screenshots**
<img width="1673" alt="Screenshot 2024-09-21 at 16 24 38" src="https://github.com/user-attachments/assets/e6f36ab9-ea4c-4700-bb8f-52597b2b8b6c">
<img width="1668" alt="Screenshot 2024-09-21 at 16 25 17" src="https://github.com/user-attachments/assets/c940bacd-a8e5-4001-a320-8b9e0e550f3a">

**Hardware (please complete the following information):**
 - OS and version: Windows 11
 - Version of CEA you are using 4.0.0 alpha (fresh install)

**Comment by reyery** [comment]
@justinfmccarty, you do not need to include the square brackets when listing the buildings e.g. B1020, B1021, B1022, B1023. Currently it is parsing it as "[B1020" , "B1021" , "B1022", "B1023]", and after filtering the invalid choices i.e. the first and last items with the brackets, only the ones in the middle are taken as valid choices.

I think we could add a warning message to alert the users of invalid choices, that would make it clearer.

**Comment by justinfmccarty** [comment]
Thanks @reyery, I'll just go feel foolish for a few hours 😅
