### ISSUE TITLE
Installation in windows remote desktop fails

### ISSUE THREAD

**Issue by brauliobarahona** [architecture-building-systems/CityEnergyAnalyst#3667]
**Describe the bug**
I followed the instructions for an installation in windows, filled in the form, and pressed download. I tried to run the installer and it worked for a while but it failed saying that the path is invalid, as shown below:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/90585ec8-2ddc-4738-9f98-86126be424c4">

**Expected behaviour**
I would have expected the installer to simply work from any directory in windows OS.

**Hardware (please complete the following information):**
 - Remote desktop withWindows 10 Enterprise, Version 22H2
 - Version 3.38.0

**Comment by reyery** [comment]
@brauliobarahona thank for for reporting this issue. May I know if you are installing CEA on a shared/network drive? The installer does not work very well for such locations.

**Comment by brauliobarahona** [comment]
hello @reyery, yes as shown in the image the disk from where I try to install is a network drive mounted on the machine, I do not see why it should matter, maybe it is just the way the strings with the path are parsed?

**Comment by brauliobarahona** [comment]
Should I expect the installer to work now? I am eager to test it again, thanks!

**Comment by ShiZhongming** [comment]
Unfortunately, due limited capacity of the CEA Team, we cannot priortise enablbing installing CEA on a shared/network. Hence, I am closing this issue.
