### ISSUE TITLE
Create a load model for latent cooling load (humidity model)

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#370]
The goal could be a model analogue to the thermal RC-model with humidity resistance and capacitance.
This issue is specially relevant for the Singapore (hot+humid climate).
This issue needs some research prior to implementation.

@adam-rysanek from 3for2 might be consulted for the present state of the art of humidity modeling.

**Comment by shanshanhsieh** [comment]
This will be tackled at the end of the WP1 of Shanshan's research (planned timeline: Nov 2017).

**Comment by gabriel-happle** [comment]
@shanshanhsieh and @JIMENOFONSECA 
I'm closing this old issue.
it is solved for now by the issues in epic #811
