### ISSUE TITLE
Make the component in Grasshopper calling CEA

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CityEnergyAnalyst#418]
Script the component in Grasshopper to call for simulation in CEA@ArcGIS.  The output of the component is the energy consumption of the input scenario. 

The attached pic is the general workflow of the loop of the optimization of the form based on the energy performance. P.S. 

![capture](https://cloud.githubusercontent.com/assets/16640327/20519270/32175d6a-b0dd-11e6-8454-f1d58f20ad49.JPG)

**Comment by shizhongming** [comment]
The three components in orange in the pic are assigned to Zhongming, Zhongming and Daren respectively.

**Comment by daren-thomas** [comment]
@shizhongming how does this compare to the other issue / pull request? can we close this?
