### ISSUE TITLE
Add calibration_main script to the dodo file for Jenkins

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#420]
Figure out how to add the calibration routine to the integration tests run by Jenkins.

**Comment by JIMENOFONSECA** [comment]
we might need to do this for sure

**Comment by JIMENOFONSECA** [comment]
For this task, we have to acknowledge that the products of the calibrator are stochastic, so the only way to control if it runs is to see if 5 files (the outputs) are being created for B01 of the open case. 

what it needs to be run in the next order are:
- cea/demand/calibration/calibration_sampling.py
- cea/demand/calibration/calibration_gaussian_emulator.py
- cea/demand/calibration/calibration_main.py

the files that need to be generated are:

locator.get_calibration_samples(building_name)
locator.get_calibration_problem(building_name)
locator.get_calibration_cvrmse_file(building_name)
locator.get_calibration_gaussian_emulator(building_name)
os.path.join(locator.get_calibration_folder(), 'chain-0.csv')

when building_name = 'B01'

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can we upgrade this script to the (new) standard CEA script interface?
- add to cli.config
- rename `run_as_script` to `main`
- accept `config` parameter

What would the configuration section for `calibration` look like?
