### ISSUE TITLE
Include TABS calculation into SIA2044 RC model

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#444]
Include TABS as additional heating/cooling system option in the CEA.
According to SIA2044.

**Comment by gabriel-happle** [comment]
No priority from Singapore side.
How about Zurich @martin-mosteiro ?

**Comment by martin-mosteiro** [comment]
Not a priority, but probably good to have.

**Comment by gabriel-happle** [comment]
check relevance with new ISO standard
