### ISSUE TITLE
Use radiant temperature for heat transfer calculation of non-back-ventilated facades in SIA RC model

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#446]
SIA 2044 section 2.1.5.2 and 2.1.5.3
External temperature for heat transfer through opaque elements should be adjusted for non-back-ventilated elements. According to Lukas Lienhart this is the normal case for buildings.

This issue is related to #443 and #12

**Comment by gabriel-happle** [comment]
Has to be reviewed when higher LOD geometry is available.

**Comment by gabriel-happle** [comment]
check relevance with new ISO standard

**Comment by JIMENOFONSECA** [comment]
This is not a priority, but It would be great if a contributor works on this in the near future
