### ISSUE TITLE
Display Error message in ArcGIS if input files for heatmaps are not found

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#450]
Maybe we need to add some architecture here. How about modules (demand, scenario plots, emissions etc.) follow a convention. Say... a function `validate_input(locator: InputLocator)` that returns `True` if the files required to run this module are present?

The result could even be a tuple `(bool, str)` with an error message?

**Comment by martin-mosteiro** [comment]
@daren-thomas Seems to me that the heatmaps tool has been removed from CEA (Is this the case? If so, it doesn't seem to be justified/documented in any other issue). If that is the case, this issue can be closed.

**Comment by daren-thomas** [comment]
@martin-mosteiro let's look at it in the next review-meeting.

**Comment by daren-thomas** [comment]
confirmed: heatmaps tool has been moved to legacy.
