### ISSUE TITLE
Missing information for Technology and Resources documentation

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#478]
This is a repository of the missing information for documenting scripts in `technologies` and `resources` folders.
Need to consult the theses of Tim Vallrath and Thuy-An Nguyen, also confirm with @JIMENOFONSECA 

- `cogeneration.py`: OP: GT exhaust gas; OP: FC efficiency (energy.gov)

- `furnace.py`: OP: furnace thermal/el part load curve (link not working), COST: bioenergy 2020 (AFO)

- `heatpumpt.py`: COST: two cost functions `calc_Cinv_pump` and `GHP_InvCost`

- `pumps.py`: OP: pump performance curve, OTHER: not clear if `calc_Cinv_pump` and `calc_Ctot_pump` is operation or investment.

- `sewage_heat_exchanger.py`: OP: in `calc_sewage_temperature`, is `trww` the fresh water temperature or DHW return (should be `t_spur`? OP: method for `calc_sewageheat` not consistent with CEA paper

- `natural_gas.py`: COST: energie 360, should that be annualized?

- unknown file `calc_radiator.pyd`
The rest of the documentation is in branch i464-technology-documentation

**Comment by shanshanhsieh** [comment]
OTHER TODOs:
The solar radiation related scripts (photovoltaic.py, photovoltaic_thermal.py,solar_collector) are unchanged, since it will be updated after issue #336 is merged.
The substation.py is unchanged, will be updated when branch i412 is merged.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh  I believe the best is to meet together with bargavah and go through each of these points.

@shanshanhsieh @BhargavaKrishnaSreepathi However it would be good if you could give priority to the issue of costs database.

I believe the prices as of today have changed anywise and we might want to be able to do these changes out of the code.

Please prepare a simple table on how this database can look like and we meet to discuss it.
