### ISSUE TITLE
Create Video Tutorials

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#481]
Create Video Tutorials of CEA.
-> Installing CEA.
-> Making a new project in CEA. - incl. getting geometry and data.
-> Run Solar radiation.
-> run demand.
-> run lifecycle analysis.
-> run district cooling.
.....and more....

**Comment by gabriel-happle** [comment]
We are making video tutorials to be included in the blog posts.
