### ISSUE TITLE
NTU EcoCampus: set up building age database

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#507]
Set up building age database. Consistent with split building shape file.

- Name
- built
- roof = 0
- windows = 0
- partitions = 0
- basement = 0
- HVAC = 0
- envelope = 0

assume no refurbishment, age of building from site survey (ask EcoCampus for confirmation of assumptions)

**Comment by shizhongming** [comment]
Most of the age of buildings is done. Some of them are unable to trace....

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi you will come across with this issue in order to run the optimization algorithm for ecocampus.
