### ISSUE TITLE
EcoCampus: Read in and use measured demand data in CEA instead of calculated demand

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#515]
CEA has to be able to overwrite calculated heating / cooling / electricity / water demand per building with real measured data input.

- create data reader, maybe in collaboration with @daren-thomas 
- overwrite or bypass demand calculation in tsd file with input data.

**Comment by daren-thomas** [comment]
Do you have time this week to skype about this?

**Comment by gabriel-happle** [comment]
@daren-thomas of course. any time.

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA do you think this is still desired? Or can I close it for now?
