### ISSUE TITLE
Implement Water supply temperature in SG

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#519]
should be close to soil temperature (find in literature), assume constant

**Comment by shanshanhsieh** [comment]
SG soil temperature: 33.5 C; river temperature: 27.5 C
http://www.sciencedirect.com/science/article/pii/S2095263513000290

**Comment by shanshanhsieh** [comment]
Average water temperature in SG: 27-29 C (hottest in May)
https://weather-and-climate.com/average-monthly-water-Temperature,Singapore,Singapore

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh is this being implemented? it seems like an easy thing to do, you probably want toget this info related to the weather file.
