### ISSUE TITLE
Remove magic numbers for heating systems and cooling systems

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#52]
replace in first step with enumerations / constants, then maybe with classes.

**Comment by daren-thomas** [comment]
e.g. in `calc_Qem_ls`

**Comment by daren-thomas** [comment]
I just checked and it seems we moved to a solution half-way in the middle using "T1", "T2" etc. to name heating and cooling systems.

@JIMENOFONSECA, is there a good reason to do this instead of using more descriptive names?

**Comment by JIMENOFONSECA** [comment]
Good? Lets discuss it on slack one day... Maybe we find a better solution..

**Comment by daren-thomas** [comment]
Moving this to next milestone, as it might be solved with @gabriel-happle 's changes to the demand calculations...

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is it ready or still important?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA yes, I think it is important.

**Comment by JIMENOFONSECA** [comment]
There is an issue about the interface addressing this
