### ISSUE TITLE
Thermal and Hydraulic Network Optimization

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#524]
Hey @shanshanhsieh,

I will just list out the parameters you expect from the optimization here. Correct me if I missed any.

**Data available from either the .shp or .csv files are the following:**

1. Total number of nodes, represented as J0, J1....J65 (for our current case)
2. Pipes represented as Pipe01, Pipe02...Pipe65 **(Not quite sure what these are? Are they streets?)**

**Data provided by the optimizer:**

1. Supply temperature (This is related to the number of plants)
2. Energy loss per meter (Correlated to insulation, type of pipe material)
3. Provide a dataframe consisting which buildings are 'consumers' and which are 'plants'
4. Provide a dataframe consisting the configuration

Regarding the configuration (point 4 supplied by optimizer), do you expect a dataframe where the rows are the 'nodes' and the columns are the 'pipes'?

**Comment by shanshanhsieh** [comment]
**Data available from either .shp or .csv**

This part includes two steps.
First, to read all the possible nodes (consumers/plants) and edges (most of the time are streets) and construct an `edge-node matrix of all the possible nodes and edges`.  
Second, to output the network layout for simulation, this is another `edge-node matrix of the actual network layout `(connected nodes and selected edges to build pipes). The output edge-node matrix from this step is the one we need for network simulation.

**Data provided by the optimizer**
1. Supply temperature: the bounds of the supply temperature are related to the demand temperature requirement, type of plant and type of network (conventional, anergy, or refrigerant).  I can set up some rules now, but in the future, we will need to further research it.
2. Energy loss per meter: we will have to add another function in the simulation script to assign pipe insulation and material according to energy loss per meter.
3. Dataframe indicating which nodes are 'consumers' and 'plants', it has to be consistent with the output `edge-node matrix of network layout` from the optimizer to the simulation script.
4. Dataframe consisting configuration: this is the `edge-node matrix of network layout` from the optimizer to the simulation script.

**Comment by BhargavaKrishnaSreepathi** [comment]
Use the individuals already present and use minimum spanning tree algorithm to calculate equivalent length from it and proceed to calculate thermal and hydraulic losses

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh this was merged long time ago right?

**Comment by shanshanhsieh** [comment]
yes, these functionalities were added and merged.
