### ISSUE TITLE
EcoCampus: Questions to EcoCampus Facility Managers

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#525]
This is a repository for questions and data we would like to verify with EcoCampus FMs. 
Please put all of your questions in this issue @JIMENOFONSECA @gabriel-happle @shizhongming @BhargavaKrishnaSreepathi

**Comment by shanshanhsieh** [comment]
- Fresh water supply temperature (to chillers and dhw heaters), refers to #519.

- Chilled water network: pipeline layout/ pipe diameter/ pipe insulation/ water flowrate. (asked Samira, still waiting for her reply)

**Comment by JIMENOFONSECA** [comment]
- temperature setpoints

- temperature set-backs and off periods.

- humidity setpoints

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh @gabriel-happle when is there gonna be a meeting anytime soon?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh I do not see this happening. please close the issue and copy the information somewhere else
