### ISSUE TITLE
Launch tool: hydraulic network 

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#539]
Create a GUI on ArcGIS that allows users to draw thermal networks and calculate thermal and hydraulic losses. The workflow will be: reading shape file of thermal networks and user-specified parameters (supply temperature, insulation level...) from ArcGIS, and passing these inputs to the network simulation script developed in #408 #407.
We will work on this issue after the network simulation script is tested with the test cases in #536.

**Comment by JIMENOFONSECA** [comment]
If this is something we need to do, it should be first priority

**Comment by shanshanhsieh** [comment]
Here are requirements of the interface:

- *Input from users*: 
1. Buildings connecting to thermal network (DC or DH)
2. Plant location 
3. Route (limit to branch layout) 
4. Insulation thickness and material property (conductive heat transfer coefficient)

- *Output to visualize*: 
1. Supply temperature at each substation
2. Plant heat requirement
3. Plant pumping requirement

- *Background processes*:
1. Prepare .shp file from user input (see below for guides to prepare .shp files) 
2. Change insulation thickness and material property.
3. Run network simulation
4. Visualize results on ArcGIS

**Comment by JIMENOFONSECA** [comment]
so are the network edges and nodes inputs?
what is the route?

**Comment by shanshanhsieh** [comment]
Route is the pipeline layout.
yes, the user inputs will be stored in `network-nodes.shp` and `network-edges.shp` for the simulation. 
I don't expect the users will modify the .shp file directly, rather, we will translate their inputs via the interface to the attribute tables in the .shp file.

**Comment by JIMENOFONSECA** [comment]
So they are like intermediate outputs right?

**Comment by shanshanhsieh** [comment]
Yes. 
In the current CEA folder structure, it is the input `reference-case-open/baseline/input/network`.
However, in the future, these files will be intermediate outputs prepared by the optimization or determined by users.

**Comment by JIMENOFONSECA** [comment]
Cool!

Best, Jimeno

On 18 May 2017, at 17:30, shanshanhsieh <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes.
In the current CEA folder structure, it is the input reference-case-open/baseline/input/network.
However, in the future, these files will be intermediate outputs prepared by the optimization or determined by users.
