### ISSUE TITLE
Create Latin Hyper Cube random sampling method to test which parameters are more sensitive

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#540]
Create Latin Hyper Cube random sampling method to test which parameters are more sensitive

**Comment by BhargavaKrishnaSreepathi** [comment]
An open source data set having the cost details. Developed by National Renewable Energy Laboratory (NERL). Might be a good source for having a uniform cost equation for all the renewables

http://en.openei.org/apps/TCDB/#blank

**Comment by JIMENOFONSECA** [comment]
If this is something we need to do, it is priority one.
