### ISSUE TITLE
Rename "Demand helper" and "Properties" to "Apply Archetypes"

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#541]
We use the terms "demand helper" and "properties" for the script that needs to be run before running the demand to create additional data required for simulation.

I think renaming these terms to "apply archetypes" communicates more clearly what the script actually does.

I therefore suggest we rename the script and associated tools / interfaces as well as language in user documentation.

**Comment by JIMENOFONSECA** [comment]
The tool was renamed to data helper. Closing this issue.
