### ISSUE TITLE
Pareto plot from ArcGIS

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#543]
the input should be an individual of a generation. The output should be a plot which shows the energy mix, visualization of which buildings are connected

**Comment by BhargavaKrishnaSreepathi** [comment]
Modify the graphs_optimization file and prepare a script that can be run from ArcGIS to generate Pareto-curves in the following scenarios:
1. Pareto front - 2D - all generations - 1 scenario
2. Pareto front - 3D - all generations - 1 scenario
3. Pareto front - 2D - 1 generation - 1 scenario
4. Pareto front - 3D - 1 generation - 1 scenario
5. Pareto front - 2D - 1 generation - all scenarios
6. Pareto front - 3D - 1 generation - all scenarios
7. Plot showing power mix (PIE chart)
8. Plot showing centralized/ decentralized buildings (best case scenario, show the buildings connected in ArcGIS)
9. Cost mix based on technology used (PIE chart)
10. Multicriteria Plots

**Comment by BhargavaKrishnaSreepathi** [comment]
Work in the branch named 'Pareto-curve-plot'

**Comment by JIMENOFONSECA** [comment]
# 11: INPUTS: generation, individual, week of the year

![image](https://cloud.githubusercontent.com/assets/8973186/25112246/9e74906e-2422-11e7-942a-00ce7da8cf9c.png)

**Comment by JIMENOFONSECA** [comment]
# 7: INPUTS: generation, individual. 
The title shows the entire energy consumption in TWh/yr. The pie shows the share in percentage.

7.1 pie of local vs non locally produced. - self-sufficiency pie
7.2 renewable vs non-renewable pie.  - the renewable pie balloons into a stacked bar chart with technologies and distinguished what is local and what is grid.
7.3. power mix of all resources independently if they are local or not.

**Comment by JIMENOFONSECA** [comment]
# 9: INPUTS: generation, individual. 
The title shows the total investment costs in $. The pie shows the share in percentage.

- pie showing share district heating and cooling and electricity micro-grid. It ballons into individual technologies

**Comment by BhargavaKrishnaSreepathi** [comment]
use branch #i543-Plots-and-Analysis

**Comment by BhargavaKrishnaSreepathi** [comment]
Sunburst charts might be a really good way to visualize many of these plots
https://support.office.com/en-us/article/Create-a-sunburst-chart-in-Office-2016-4a127977-62cd-4c11-b8c7-65b84a358e0c?ui=en-US&rs=en-US&ad=US&fromAR=1

**Comment by JIMENOFONSECA** [comment]
cool idea! go for it!, let me know if we can help
On 2 May 2017, at 11:06 am, BhargavaKrishnaSreepathi <notifications@github.com<mailto:notifications@github.com>> wrote:


Sunburst charts might be a really good way to visualize many of these plots
https://support.office.com/en-us/article/Create-a-sunburst-chart-in-Office-2016-4a127977-62cd-4c11-b8c7-65b84a358e0c?ui=en-US&rs=en-US&ad=US&fromAR=1
