### ISSUE TITLE
suggestion for code that is easier to read demand/space_emission_systems.py

### ISSUE THREAD

**Issue by pjayathissa** [architecture-building-systems/CityEnergyAnalyst#593]
Hi Shanshan

line 198 and 243 of `demand/space_emission_systems.py`

I would recommend writing it like this to make it easier for future readers:
```python
if cooling_system=='T0'
    #No heating or cooling sytem installed
    delta_theta_int_inc_cooling = 0.0
else:
   # the cooling supply temperature is doing something
   delta_theta_int_inc_cooling = control_delta_cooling[control_system] + 
         system_delta_cooling[cooling_system]
```

Would you be free to have a chat about this sometime. I am currently trying to build some supply systems but I don't know how to determine the supply temperature.

**Comment by JIMENOFONSECA** [comment]
no answer to this issue, it will be closed
