### ISSUE TITLE
setup a supply_main file similar to demand_main file

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#603]
This file needs to be run to get the following files:

1. Geothermal.csv
2. SWP.csv
3. PV.csv
4. PVT_35.csv
5. SC_60.csv
6. SC_75.csv

Right now they are being shipped along with the reference-case-zug

**Comment by BhargavaKrishnaSreepathi** [comment]
@JIMENOFONSECA : Can you let me know how the above mentioned 'csv' files are being created. For 'reference-case-zug', the above mentioned files are already present in 'baseline -> outputs -> data -> potentials', whereas for 'reference-case-open', the 'potentials' folder has files with names as 'xx_PV' and 'xx_sensors'. I think these might be used in 'photovoltaic.py' file which requires sensors_data

**Comment by JIMENOFONSECA** [comment]
Geothermal.csv
- I suggest to take it out form the optimization
SWP.csv
- I suggest to take it out from the optimization
PV.csv, PVT_35.csv, SC_60.csv, SC_75.csv
- Created from the PV scripts in technologies. they are being redeveloped in #336 and arre waiting to merge

**Comment by BhargavaKrishnaSreepathi** [comment]
Ok will work on this after #336 is merged

**Comment by shanshanhsieh** [comment]
At the moment, the results of the PV generation are saved for individual buildings.
The old results 'PV.csv' are the aggregation of the entire district. 
@BhargavaKrishnaSreepathi , how does the current optimization procedure handle this information, does it decide the amount of panel installed at the building level?

**Comment by BhargavaKrishnaSreepathi** [comment]
[documentation Thuy-an.PDF](https://github.com/architecture-building-systems/CEAforArcGIS/files/960595/documentation.Thuy-an.PDF)
@shanshanhsieh : Nope. It actually takes the total area and then assigns a percentage of this area for PV, PVT and SC. It is not done at building level.

**Comment by shanshanhsieh** [comment]
@BhargavaKrishnaSreepathi do you see this be finished in `spring May`? 
I personally would put it to the first priority of the coming sprint, since it will have to wait until #636 is merged as well.

**Comment by BhargavaKrishnaSreepathi** [comment]
@shanshanhsieh: I think it will take longer than that, as both of us have other issues to wrap up.

**Comment by BhargavaKrishnaSreepathi** [comment]
This is not necessary anymore, as the guide of running CEA is made available. Which includes a separate section for potentials calculation. The remaining steps are already incorporated into optimization in various PRs
