### ISSUE TITLE
Logging system and user activity monitoring

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#618]
Reading through #570 (ValueError: operands could not be broadcast together with shapes (8760,) (4984,) (8760,)) I think some kind of system to log errors to might be a good idea.

Currently we are printing them to STDOUT. When doing stuff like the sensitivity analysis or the optimization , this leads to messages being hidden in `.lsf` files that nobody is ever going to go through.

What kind of requirements would such a system have? Here are some ideas off the top of my head:

- simple mode outputs to STDOUT
- complex mode stores in a database (allow storing messages from multiple processes / computing nodes)
- each message has some attributes:
  - a message text (obviously)
  - a timestamp (for sorting)
  - a session id - some way to identify the whole process, even if split up over multiple computers
  - a task id - to be able to talk about a specific simulation / task (note this is different from os process in that an os process could be used for multiple tasks)
  - fully qualified name of function/method logging the error?

In addition, maybe a task list could be maintained stating the input parameters to a task? This could be the options sent to the `cea` program, taking care to make sure the paths are rendered absolute. This way, any task that failed for some reason could be re-run in the debugger...

We could maybe even have a `cea-debug <taskid>` cmd? (have fun learning pdb...)

@JIMENOFONSECA, @BhargavaKrishnaSreepathi do you have any input?

**Comment by JIMENOFONSECA** [comment]
We had some ideas in the past, Now that we have access to uses via webservices, we will start monitoring usage. The idea is that we can get more information about the hurting points of CEA in a more tangible and quantifiable manner.
