### ISSUE TITLE
Emission System Supply Temperatures too high?

### ISSUE THREAD

**Issue by pjayathissa** [architecture-building-systems/CityEnergyAnalyst#626]
Hi @shanshanhsieh , thanks for the skype today

I was having a look at the **CEAforArcGIS/cea/databases/CH/Systems/emission_systems.xls**

For the heating, do you not think that 90C is too high? Do you have any references for these numbers?

Cheers

PJ

**Comment by shanshanhsieh** [comment]
There are two types of radiators in the database, 90 C is possible for the old radiators. 
These data are based on Jimeno's case studies in Switzerland, therefore, I do not have the references at the moment. Maybe you could check out the standards?
