### ISSUE TITLE
Initialize scenario feature (for databases etc.)

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#639]
- copy archetypes and other database stuff to the scenario folder
- CEA reads these files by default from scenario folder, failing over to database versions
- include weather file (this reduces the amount of options a user has to set for each run...)
- ties in with the cascading configuration file

**Comment by daren-thomas** [comment]
see also #451 - moving archetypes to the scenario folder

**Comment by daren-thomas** [comment]
@JIMENOFONSECA wasn't there a PR for this?

**Comment by JIMENOFONSECA** [comment]
Yep, there is a new tool in cea>uitlities>create_new_project.py

It was merged already

Jimeno

On 5 Feb 2018, 21:03 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/jimenofonseca> wasn't there a PR for this?
