### ISSUE TITLE
Check coordinate systems of input files on radiation / demand etc.

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#640]
They need to all be in the same projected coordinate system. When they are not, raise an error message that includes a link to the user documentation on how to fix that (one of the FAQ presentations)

@JIMENOFONSECA are we going to define a default for the CEA tool? Or still let the user choose?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas i believe they can choose. but it needs to be projected and be the same always.
