### ISSUE TITLE
Retroffiting Manual in FAQ

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#643]
@amraladdin please include the details here, thanks!

**Comment by amraladdin** [comment]
According to our last discussion, a small restructuring of the presentations will take place, as follows:
- Presentation on "How to ensure you have a correct main (aka baseline) scenario?"

Regarding the retrofitting set of presentations, the following changes should take place:
- Create a general presentation on "How to edit databases?"
- Create 3 sub-presentations that tackle the retrofitting topic: a) HVAC, b) Appliances, and c) Envelope.

For that to happen, we need to:
- Create/adapt a case study with a few number of buildings, and upload it on the Website/GitHub.
- Each case results should show the variation in results in % (post processing using Excel).

@JIMENOFONSECA feel free to edit in case I forgot/misunderstood one or more of the above-mentioned points.

**Comment by JIMENOFONSECA** [comment]
@amraladdin  i think it is not necessary to adapt a casee study. the HQ should be sufficient in this matter. the analysis should take the same time in any case study. Making another one is nice to have but troublesome timewise for the goal of this milestone

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro is the case study in the server up to date to do the study?

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA no, it's still waiting to be merged
https://github.com/architecture-building-systems/cea-reference-case/pull/13

**Comment by JIMENOFONSECA** [comment]
done! thanks!
________________________________

**Comment by JIMENOFONSECA** [comment]
@daren-thomas hi Daren, would you mind giving me an extra hand to the interface of this tool? you helped me about two weeks ago, but there is some help i need, @skype?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA check out the newest commit: It includes an interface. Instead of checkboxes it works like this: if there is a value in the input field, then that criteria is to be used. if the field is empty, then ignore that criterium. i think that works quite well.

![image](https://user-images.githubusercontent.com/2969564/27038952-c26129f2-4f8c-11e7-9c1d-4289f9e93572.png)

**Comment by JIMENOFONSECA** [comment]
Great! Thanks for this. The only thing is that it would be good to keep default values there. (They are like rules of thumb, and they are good to guide the user). In this context, it would be good to have checkboxes too.  the checkboxes should enable or disable charging the default values.

On 12 Jun 2017, at 22:33, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/jimenofonseca> check out the newest commit: It includes an interface. Instead of checkboxes it works like this: if there is a value in the input field, then that criteria is to be used. if the field is empty, then ignore that criterium. i think that works quite well.

[image]<https://user-images.githubusercontent.com/2969564/27038952-c26129f2-4f8c-11e7-9c1d-4289f9e93572.png>

**Comment by daren-thomas** [comment]
We can do that, at the expense of cluttering the UI. An alternative would be to add example values to the labels. What would you prefer?

**Comment by JIMENOFONSECA** [comment]
From my side, i would prefer the tick boxes that enable each field. In addition, it would be good to create subcategories in the interface so it is easy to read the Filters and do not clutter too much the UI

On 13 Jun 2017, at 3:28 pm, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


We can do that, at the expense of cluttering the UI. An alternative would be to add example values to the labels. What would you prefer?

**Comment by JIMENOFONSECA** [comment]
<img width="527" alt="screen shot 2017-06-13 at 4 41 54 pm" src="https://user-images.githubusercontent.com/8973186/27073730-776d603e-5057-11e7-8189-73cbbe088624.png">

**Comment by daren-thomas** [comment]
@JIMENOFONSECA you happen to know what those are called? that could be a good way to do it... still include checkboxes? i have a checkbox version coming up next. still ironing out some bugs...

**Comment by JIMENOFONSECA** [comment]
Mm no idea about the name. Looking forward to seeing the version with the checkboxes.

Best, Jimeno

On 13 Jun 2017, at 18:57, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/jimenofonseca> you happen to know what those are called? that could be a good way to do it... still include checkboxes? i have a checkbox version coming up next. still ironing out some bugs...

**Comment by daren-thomas** [comment]
If only I can get it to work!!

**Comment by daren-thomas** [comment]
OK. Check out the perfected interface combining the checkboxes as well as grouping the options by category.

**Comment by amraladdin** [comment]
#1 ERRORS AND ISSUES RELATED TO i643
-----------------------------------------------
After conducting a successful simulation using the Building Retrofit Potential Feature, I could not locate the "potentials" folder, which contains the retrofit_filters.csv file. Neither in the original scenario, i.e. "baseline", nor the created retrofitting case, i.e. "age_HVAC". Below are the screenshots of the simulation run:

(Inputs)

![error02_a](https://user-images.githubusercontent.com/16256867/27170621-ddc37906-51ae-11e7-8360-15da03bf07cd.jpg)

(Successful run)

![error02_b](https://user-images.githubusercontent.com/16256867/27170652-f81c3b30-51ae-11e7-8d39-82c8a4e71564.jpg)

(No "potentials" folder or "retrofit_filers.csv" files created)

![error02_c](https://user-images.githubusercontent.com/16256867/27170725-35ae213e-51af-11e7-8a26-6906c98a604d.jpg)


While in the documentation created by Jimeno, the .csv file is successfully generated:

![error02_d](https://user-images.githubusercontent.com/16256867/27170792-7d1725c0-51af-11e7-9070-18982f35d091.jpg)

**Comment by amraladdin** [comment]
#2 ERRORS AND ISSUES RELATED TO i643
-----------------------------------------------

While testing branch i643, I found an issue:
- When using the cost criteria, an error occurs as seen in the following images:

(In this example I chose age and costs, however, even when I use the costs alone, the feature does not work.)

![error01_a](https://user-images.githubusercontent.com/16256867/27170180-459831f4-51ad-11e7-9a5e-583bb136ca15.jpg)

(Here's a snapshot of the error)

![error01_b](https://user-images.githubusercontent.com/16256867/27170230-7b6957e0-51ad-11e7-93a4-a1bf5cdf403d.jpg)

(and of course, the expected new scenario, i.e. "baseline_HVAC" is not created)

![error01_c](https://user-images.githubusercontent.com/16256867/27170283-a4982d44-51ad-11e7-8293-989108815ab2.jpg)

**Comment by JIMENOFONSECA** [comment]
@amraladdin fixed. please check the guidelines. Now i included the interface. there is not need of the retrofit_potential file. Only buildings that comply with the criteria are kept in the new scenario. Would you mind complementing and modifying the presentation? thanks!!!

**Comment by amraladdin** [comment]
Great! Thanks! I will sync the new version, test it and report if I find any errors.

**Comment by JIMENOFONSECA** [comment]
@amraladdin could we try to finish this? :-)

**Comment by amraladdin** [comment]
Not any time soon to be honest. This semester, my work schedule is more than full. I will also need someone who knows how this tool works to guide me through it. Otherwise, I can have time to explore the tool myself after December. I've already tried this before but the tool was still buggy, so I ended up spending a lot of time trying to make it work with no outcome.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro @amraladdin this feature will not be anymore supported in CEA so we will not create a tutorial. Check PR #1677
