### ISSUE TITLE
'Qwwf' is assumed to be supplied via storage all the time

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#66]
Could be different according to water heater types.

**Comment by gabriel-happle** [comment]
I will have a look at this for the next milestone.
@shanshanhsieh what is the exact background of this issue?

**Comment by shanshanhsieh** [comment]
The final heating energy required for hot water is  `Qwwf = Qww + Qww_dis_ls_r + Qww_dis_ls_nr + Qww_st_ls`, in which the heat loss in storage is included by default.
Currently, the storage tank volume is set to be the maximum instantaneous hot water flow rate (m3/hr), which is the normal case for thankless water heater. What could be improved here is to have the choice for storage tank sizes with respect to the type of storage you want to install. 
for example:
a. tank less water heater (with little storage)
b. short-term storage (diurnal)
c. long-term storage (week-month)

**Comment by gabriel-happle** [comment]
The future of this issue will be decided on the MuSES workshop on future energy systems on the 20/09/2016.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle was this decided? should this be considered?

**Comment by gabriel-happle** [comment]
I think this is needed. Especially for Singapore case and instant heaters.
