### ISSUE TITLE
create a (unit) test for BuildingProperties generation

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#660]
While working on #656 I encountered a problem in `thermal_loads.BuildingProperties` object initialization.
Basically there were some illegal keys `T0` in the archetypes database, which did not provide a link to the respective building systems database. This means the dataframe merge commands used in the various functions don't find a match and the respective building is dropped.

We could implement a very easy test for this.
It would check weather all the dataframes contain the same number of buildings as specified in the `zone.shp` file. If not, the code should break immediately and point the user into the direction of which key/field might be corrupt.

@daren-thomas where and how would we implement such a test?

**Comment by daren-thomas** [comment]
such a test would create a minimal set of files to read in. maybe need to restructure the code to make it "testable". i'll look into it some day!
