### ISSUE TITLE
As a researcher, I want a robust and up-to-date multi-zone demand calculation, so I can simulate a higher level of granularity in terms of uses

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#664]
It refers to a step that can be done in parallel to issue #662. In basic therms the output of the radiation tool will not change.

This issue entails:
- changing occupancy.dbf in reference case open to consider multizonning (Jimeno). Floor by floor. Indicate in the radiation file which surface belongs to which floor.
- making multizonning in CEA (Gabriel) and connecting to radiation. (for this, it is good to create "zones" when some floors have the same function. We should avoid doing the analysis floor by floor.

**Comment by JIMENOFONSECA** [comment]
what happens with funcitons that have an area less than one floor? @martin-mosteiro

**Comment by JIMENOFONSECA** [comment]
![b3abdc60d729f442eeaebc9dcb2a8241](https://cloud.githubusercontent.com/assets/8973186/26722427/7d552e20-47c2-11e7-8e0c-d4555717d698.png)

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle i made the occupancy.dbf with the zoning convention. you can take this issue from here. I did it for the open case for now. 

Please continue the work in the branch i664-multi-zone-radiation

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA I'm working on that in branch i664-multi-zone-radiation but I prefer that @martin-mosteiro 's mixed-use modifications are merged first. I will prepare the database structure of the thermal zones first in theory. But this issue can not be finished in this sprint.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle @martin-mosteiro i finished my part in here. The part about identfying the floor of each surface could not be completed. let me know if you need help.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle @martin-mosteiro status?, this is being a bottle neck in the work we are doing with @Khayatian any chance you can put it as a priority?

**Comment by gabriel-happle** [comment]
OK @JIMENOFONSECA . I will make this my priority now.

**Comment by gabriel-happle** [comment]
check #935 and split up into tasks

**Comment by gabriel-happle** [comment]
I converted this to an epic as it contains all the information.
I added all the issues connected to the R-C-model in SIA/ISO to this Epic.
While implementing the multi-zoning, they can be implemented easily.

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
