### ISSUE TITLE
Export Rhino urban generator to CEA files

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#665]
based on #662 it was found that in order to connect the urban generator to CEA for now. The best is to create databases readable by CEA.

These are all the input files contained in CEA/examples/open-case-study.zip/baseline/inputs>

- Zone.shp
- architecture.dbf
- occupancy.dbf
- age.dbf

**Comment by shizhongming** [comment]
@daren-thomas 
Hi Daren
I have been able to build up the script to export CEA files in PyCharm. However, as you told me that the ghPython works differently... How did you manage to call libraries in ghPython?
Thanks.

**Comment by shizhongming** [comment]
@daren-thomas an update here. I am able to install some libraries and some scripts work now. I am figuring out how to install numpy for IronPython..

**Comment by shizhongming** [comment]
@daren-thomas Please find the xlsx files in the recent commit for the generation of CEA files. Let me know if you think somewhere needs to be changed. Thanks~

**Comment by daren-thomas** [comment]
@shizhongming what must i do to run the current (your)  version?

**Comment by daren-thomas** [comment]
@shizhongming I've started looking at this and trying some stuff out. I think we already have most of the primitives needed: The CEA has a script `cea excel-to-dbf` that could be used. We'd need only a few small changes:

- UBG Excel output should have the correct column names (currently all uppercase)
- add a script `cea excel-to-shp` that parses the coordinates (note for future me: use `ast.literal_eval`)
- for documentation purposes, a table of columns -> field_specs for each of these tables would be tres
  cool! If we keep this in machine readable format (e.g. a file in the databases section), then we could use 
  that in these tools.

**Comment by daren-thomas** [comment]
we're closing this as this is basically the same as the epic (a sort of meta-issue)
