### ISSUE TITLE
Test the implementation of NN in Keras

### ISSUE THREAD

**Issue by Khayatian** [architecture-building-systems/CityEnergyAnalyst#666]
Test the obtained accuracy on a larger sample (~1000) of buildings with various geometries, occupancy profiles, internal gains, construction materials, HVAC systems, etc...

**Comment by Khayatian** [comment]
this issue is literally the DEIVIL issue as the corresponding reference number is 666.

**Comment by JIMENOFONSECA** [comment]
@Khayatian can we close this issue?
