### ISSUE TITLE
Add low exergy (3for2) system to Demand calculation

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#668]
Currently, there are four emission system for cooling (none/ radiant panels/ centralized AC/ mini-split AC). But it is not possible to have a combination of these systems.
A low-exergy emission system which consists radiant panels, dehumidification of indoor air, and ventilation should be implemented.
Support from @gabriel-happle  will be needed.

**Comment by gabriel-happle** [comment]
sure!

**Comment by shanshanhsieh** [comment]
Implement the calculation procedure with a generic control strategy designed by SH&GH (see workflow).
The script should calculate sensible & latent cooling loads from the 3for2 system.
Need to add additional variables to tsd. (e.g. Qsen,radiator)

**Comment by shanshanhsieh** [comment]
CEA_new_AC_20170727.png
