### ISSUE TITLE
Speed-up Daysim radiation Script with Parallel computing /refactoring

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#683]
The current speed for the open case:

19 min considering windows, floors materials and reflections. 1 point per surface. = 2225 sensors
++1h considering  windows, floors, materials and reflections. 5x5 grid of points. = 8093 sensors

@daren-thomas can I assign this to you for the next milestone?

**Comment by daren-thomas** [comment]
As I understand it, the Daysim tool is the bottleneck here - I can take a look at this, but I'd be surprised if we can make this much faster...

**Comment by JIMENOFONSECA** [comment]
Many thanks! It is calculating chunks of buildings in series. But it would be improved if this can be done in parallel i guess..

Best, Jimeno

On 16 Jun 2017, at 15:35, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


As I understand it, the Daysim tool is the bottleneck here - I can take a look at this, but I'd be surprised if we can make this much faster...

**Comment by JIMENOFONSECA** [comment]
It is already fast. the fix was based on tuning the hyperparameters.
