### ISSUE TITLE
Launch tool: solar isolation

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#684]
- [   ] Create interface to the Daysim Radiation Tool.
- [   ] Create Tutorial How does the Urban Solar Radiation tool work?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA sure, I'd like to do that. Also, we should move the `settings.py` stuff to the cascading configuration files ;-)

**Comment by JIMENOFONSECA** [comment]
Sure, although as every tool works independently in CEA (and it should) i wonder if every tool should have its own config or settings file rather than a mega file for all tools.

Best, Jimeno

On 16 Jun 2017, at 15:33, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/jimenofonseca> sure, I'd like to do that. Also, we should move the settings.py stuff to the cascading configuration files ;-)

**Comment by daren-thomas** [comment]
it's all about tradeoff... the config file proposal i have made is divided into sections, one for each tool. i suggest we see how well that plays out and then split the files up if they end up becoming too complicated.

**Comment by JIMENOFONSECA** [comment]
One question, do you expect this config file to be edited from the GUI of each tool in arc-gis? Or what interface will be used?



On 16 Jun 2017, at 16:28, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


it's all about tradeoff... the config file proposal i have made is divided into sections, one for each tool. i suggest we see how well that plays out and then split the files up if they end up becoming too complicated.

**Comment by daren-thomas** [comment]
I'm still figuring that out, Jimeno. what do you think: could editing by hand work?

**Comment by JIMENOFONSECA** [comment]
by hand it would be difficult, especially for new users.

I imagine including these parameters inside the ArcGIS GUI of each tool and creating a separate file storing default values in the main root folder of each tool. Example of the settings.py file in cea/radiation/radiation_daysim

This might make it accessible for 1. the user of arcgis. and 2. the developers (who only see cea and the rootfolder from pycharm).

In essence I see the CEA toolbox working as independent tools, each one with some important variables to consider and worth manipulating for research purposes.

what do you think?


________________________________

**Comment by JIMENOFONSECA** [comment]
@daren-thomas The Solar Radiation tool should point to the file: cea/resources/radiation_daysim/radiation_main. 

It should require as inputs:
- the scenario
- the weather file
- the config properties stored provisionally in the settings.py file included in cea/resources/radiation_daysim

**Comment by daren-thomas** [comment]
merging the pull requests #725 and #783 first would make this easier. as is, those two pull requests will probably create a merge conflict...
