### ISSUE TITLE
Calculate the CmFunction in Detail

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#7]
This function relates the thermal mass of the building. It can be calculated in a detailed way according to ISO standards. it will need also archetypes to facilitate this. It would be good to use if understanding the sensitivity of thermal mass is needed.

**Comment by shanshanhsieh** [comment]
Same for **Am**, effective thermal mass.
As well as gathering data from Singapore.

**Comment by JIMENOFONSECA** [comment]
From experience in the 3for2 project, the moisture content capacitance of furniture and equipment might play a major role in the profile of hourly cooling requirements. way around it is to opt for a lumped capacitance for moisture content in the model. the value should be calibrated  with measured data and then keep it as a standard for simulation. A more detailed way will be to model materials inside buildings (need of archetypes) and check procedure included in TrnSys to this end

**Comment by JIMENOFONSECA** [comment]
I suggest to close this issue as we might not want to get into the detail of several materials. We know that construction materials in Singapore are quite similar in the whole building stock

**Comment by gabriel-happle** [comment]
check with #935

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
