### ISSUE TITLE
Launch Tool: Solar Energy Potential Analysis

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#711]
- [   ] Create interface to energy potential analysis: Solar technologies, Fuels.
- [   ] Create Tutorial How does the Renewable Energy Assessment tool work?

**Comment by daren-thomas** [comment]
@shanshanhsieh where do I start here?

**Comment by shanshanhsieh** [comment]
@daren-thomas , I believe we have to first look at the settings file together, this is where the arguments of the functions and default constants are saved now. Do you have time to skype tomorrow or next monday?

**Comment by daren-thomas** [comment]
@shanshanhsieh i can skype tomorrow, say, 10 o'clock my time? 11 could work too...

**Comment by daren-thomas** [comment]
NOTE: Interface is being created on the branch `i636-connect-solar-collector-and-PVT-with-new-radiation-results`

**Comment by shanshanhsieh** [comment]
The interface for PV panels is completed in branch `i636`.
In this branch, the interface of SC and PVT should also be added.

**Comment by daren-thomas** [comment]
Created the branch `711-launch-tool-energy-potential-analysis` based on `i636-connect-solar-collector-and-PVT-with-new-radiation-results` and am starting on the interface now.

**Comment by daren-thomas** [comment]
@shanshanhsieh: check out the 711 branch for a solar collector tool in ArcGIS. Is it missing anything? I'll take a stab at the PVT tool tomorrow morning (will you be available for questions?)
