### ISSUE TITLE
Launch tool: Supply Systems Optimization

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#713]
- [ ] Create interface to multi-objective optimization with CEA.
- [ ] Create Tutorial How does the Multi-Objective Optimization tool work?

**Comment by daren-thomas** [comment]
@BhargavaKrishnaSreepathi when do we sit down to check this out together?

**Comment by BhargavaKrishnaSreepathi** [comment]
@daren-thomas: I am currently working on developing the case study for Eco campus. Once it is done, we can work on this tool. Sorry for the late response

**Comment by BhargavaKrishnaSreepathi** [comment]
@daren-thomas: When can we sit together to discuss this one?

**Comment by BhargavaKrishnaSreepathi** [comment]
hey @daren-thomas, i think we should work on this toolbox. Can you tell me when we can start?

**Comment by daren-thomas** [comment]
hey @BhargavaKrishnaSreepathi sure! we can start tomorrow if you like. what script is the tool for?

**Comment by BhargavaKrishnaSreepathi** [comment]
Sure, let us start today. I will keep my evening free, do ping me once you are in the office. The tool is to call the 'optimization_main.py' and to provide the inputs through ArcGIS interface

**Comment by daren-thomas** [comment]
OK. So, the first step would be to edit the `CityEnergyAnalyst.py` file and add a subclass of `CeaTool`  and see if that already fixes it...

**Comment by BhargavaKrishnaSreepathi** [comment]
Sure, will give it a go
