### ISSUE TITLE
Memory error running Daysim

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#721]
@daren-thomas I am having the same problem of #320 while appending lists and running the daysim routine. There is a memory error caused by access to memory.

The array length is  70'080.000 points = 8760 hours X 8000 sensor points. This is a typical value we are having in the ecocampus case with daysim and it seems that python 32bits cannot handle this.

This is what the python community says about this:

https://stackoverflow.com/questions/4441947/why-python-memory-error-with-list-append-lots-of-ram-left

**Comment by daren-thomas** [comment]
@JIMENOFONSECA did you try it with 64 bit python? Does the problem go away then?

I'd rather investigate this some more - moving to 64 bit python is going to be a *lot* of work. A quick back-of-the-envelope calculation shows that you're not actually hitting the 2GB limit with your array, so I think that might not really be the problem. But yes. It is getting close.

Please provide a stack trace (the complete error message with line it breaks on) and steps to recreate this problem so I can debug.

**Comment by daren-thomas** [comment]
Hey @JIMENOFONSECA, I've just tested the most simple thing I could come up with:

```
In [12]: lst = [float(x) for x in range(8760 * 8000)]
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-12-635f1d6bed46> in <module>()
----> 1 lst = [float(x) for x in range(8760 * 8000)]

MemoryError:
```

So, can confirm that we can't create lists that long. I also tried to do this:

```
In [10]: np.zeros(lstlen)
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-10-8748e3de8982> in <module>()
----> 1 np.zeros(lstlen)
```

So no `numpy` lists either. Now. Where to go from here? Maybe using 64 bit python could help. This amount of floats would take up about 0.5 GB of RAM, plus overhead. Maybe we can come up with an algorithm that doesn't require everything to be in RAM at the same time? This is how it is normally done: Also, as we tackle bigger and bigger scenarios, we're going to run into this problem again and again.

Can you point out where the MemoryError is happening? Show how to recreate the error. Then we can treat this as a bug to fix.

**Comment by JIMENOFONSECA** [comment]
Hi Daren, yes te error takes place when writing files to json

We tried to write to csv and it was bad. Json gave some more room.

The writing process of the output takes place in the last lines of code in the daysim_main.py

it is a quite similar memory error to the old radiation script.

I agree that we will have bigger and bigger scenarios so we might want to consider using 64 bit too.

On 12 Jul 2017, at 22:10, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #721<https://github.com/architecture-building-systems/CEAforArcGIS/issues/721> to @JIMENOFONSECA<https://github.com/jimenofonseca>.

**Comment by daren-thomas** [comment]
seems to be running in master. closing issue.
