### ISSUE TITLE
radiation_arcgis script uses daylight saving time

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#724]
This is specific to CH cases. Check method `calc_radiation_day`. For the ecocampus study, we should probably fix this. AFTER we get the MemoryError thing fixed.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I am unable to run arcpy in master, any ideas?

![image](https://user-images.githubusercontent.com/8973186/30801971-a55b0b74-a217-11e7-8219-398fa6e0a0a1.png)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: what is the contents of the `cea_arcpy.pth` file in your home folder (`C:\Users\your_user_name`)?

mine is this:

```
C:\Program Files (x86)\ArcGIS\Desktop10.5\bin64
C:\Program Files (x86)\ArcGIS\Desktop10.5\arcpy
C:\Program Files (x86)\ArcGIS\Desktop10.5\scripts
```

**Comment by daren-thomas** [comment]
![image](https://user-images.githubusercontent.com/2969564/30810459-80741e5c-a205-11e7-9565-c41cca92a3d7.png)

**Comment by JIMENOFONSECA** [comment]
I have version 10.4, would that be the problem?

if so, it is kind of a hassle getting 10.5 arcgis in here right now. would you mind trying my branch in your computer?

i724-daylight-saving? I am making a pull request

________________________________
