### ISSUE TITLE
DataHelper GUI should allow for selection of Archetypes and Functions Database

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#729]
As we have archetypes databases for two locations now, the GUI of the DataHelper should have some kind of mechanism to select which database to use to generate the buildings.

**Comment by daren-thomas** [comment]
Agree. Also, the DataHelper (or some other tool? create-new-scenario?) should copy those archetypes to the input folder of the scenario for the user to edit. I think there might even be an open issue about that somewhere...

**Comment by JIMENOFONSECA** [comment]
fixed with the region variable in the config
