### ISSUE TITLE
Create workaround for EcoCampus heating / cooling season issue

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#736]
Before #251 we can create a simple workaround to run EcoCampus calculations. Maybe in a separate branch with special values in globalvars

**Comment by gabriel-happle** [comment]
@daren-thomas is that ok for you?

**Comment by daren-thomas** [comment]
sure. that's what separate branches are for. except, you'll need to reference that branch then in your publication?

**Comment by gabriel-happle** [comment]
branch e001 is running EcoCampus under assumptions of only centralized AC
