### ISSUE TITLE
Missing energy potentials that need to be incorporated into CEA

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#744]
List out all the possible potentials and make them zero if they are not applicable to a certain location.

A few of the possible potentials are:
1. Sewage
2. Data Center
3. Compressed Air (produce heat when decompressed)
4. Municipal Solid Waste
5. Horticulture Waste
6. Wind
7. Waste heat from processes
8. Fossil fuels like Grid natural gas, grid bio gas
9. Heat sinks like Lake, Sea. (boundary conditions need to be set for this)

Apart from this, if there are any other technologies, they can be added.

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi so as discussed, would you mind creating a branch and putting this into your pipeline? let me know when and I can go ahead and start implementing the restrictions file

**Comment by BhargavaKrishnaSreepathi** [comment]
Summary of discussion:
1. Create a dbf file with the restrictions corresponding to potentials in a site.
2. This need to be created in a way similar to using data helper
3. This is then integrated into optimization framework

**Comment by JIMENOFONSECA** [comment]
this won't happen any time soon (6 - 12 months time), so we close it
