### ISSUE TITLE
Visualize floors in a building with different usages

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#75]
Currently, there is only one usage per building. We should be able to assign different usages in different floors to model mixed used buildings. (could be done in City Engine, but not in the current version of CEA tool)

**Comment by shanshanhsieh** [comment]
it will complement issue #63

**Comment by JIMENOFONSECA** [comment]
Not exactly. Currently CEA can consider mixed use as a percentage or ratio. what would be good is to add a visual image of selection of users in a floor basis

**Comment by shanshanhsieh** [comment]
true, i remember there was a constraint that all the percentage should be equal to 1 at the end, but couldn't locate it now. 

In this case, does the current method already consider how will the thermal masses of the neighboring floors affect each others? just thinking the room temperatures might be different if the neighboring floors has different usage patterns, and thus affecting energy demand in other floors... therefore, it might influence the decision on zone placement within a building?

**Comment by JIMENOFONSECA** [comment]
Exactly! That is exactly where we should get to with multi-thermal zoning...

Sent on the road

**Comment by shanshanhsieh** [comment]
so the problem i mentioned will be addressed in issue#12, and i will change this issue into a sole visualization problem.

**Comment by JIMENOFONSECA** [comment]
@shizhongming a year old issue what are your plans about this.

**Comment by shizhongming** [comment]
Sorry, I have just seen this issue. In the grasshopper tool, can already provide multi-zone use assignment on a floor-basis. However, we decided to not to have the multi-zone a long time ago, right? So, we just close this issue...
