### ISSUE TITLE
Research Question: Influence on the optimal pipe layout due to multiple plants

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#750]
Will the optimal pipe layout calculated be very different when multiple plants are connected to multiple networks as opposed to multiple plants connected to one network in a district

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi assigning this issue back. You can close it as well if it is not a research question anymore.

To me, it is!

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi status? Clossing and making it won't have if not in the pipeline
