### ISSUE TITLE
calculate electric tariffs based on the peak and non-peak periods

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#751]
The electricity calculations need to be modified to include a dynamic change in the tariffs based on the peak and non-peak periods. Occupancy database can be used for this purpose. This also falls in line with the Intra-CREATE grant

**Comment by gabriel-happle** [comment]
@BhargavaKrishnaSreepathi I'm unassigning myself. OK?

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi that is closed right?
