### ISSUE TITLE
Solar potential calculations need to updated based on the installation area instead of total area

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#754]
Currently, CEA is using the average potential of the total panel installation area. This needs to be modified. The area for SC/PVT should only be the combined area of the buildings connected to the heating network. The area available in the disconnected buildings should not be considered in this. The disconnected buildings can install PV.

**Comment by BhargavaKrishnaSreepathi** [comment]
Use class similar to BuildingProperties used in demand.py file

**Comment by shanshanhsieh** [comment]
For the ecocampus case, we will stick to the current method: choosing a percentage of total area for PV/PVT/SC installation.
After acquiring results from optimization, we should do a more detailed calculation with the actual potentials from assigned surfaces to find out the discrepancy from the current method.

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi I wonder if this was fixed?

**Comment by JIMENOFONSECA** [comment]
This was fixed in #2295
