### ISSUE TITLE
Pre-filter the site resource potentials

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#755]
Update the technology configurations such as nHeat, nSolar according to the resource potential present on a site. Currently it is a hard coded value

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi is this still the case?

**Comment by JIMENOFONSECA** [comment]
no more valid, the optimization scripts work differently now.
