### ISSUE TITLE
Bounds set for SC, PVT and PV in the optimization need to be changed

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#757]
The bounds are to be dynamic and are linked to the building network. SC/PVT will depend on the buildings connected. The remaining area will be used for PV installation

**Comment by shanshanhsieh** [comment]
Do you mean the upper bounds of available area to install each type of solar panels?

**Comment by shanshanhsieh** [comment]
is this resolved, @BhargavaKrishnaSreepathi ?

**Comment by BhargavaKrishnaSreepathi** [comment]
we are actually dealing with this in a different way now. We are still assuming the upper bound of the available area to be the maximum roof area. So I dont think this is resolved, but I am not sure if this is something to be resolved?
