### ISSUE TITLE
Envelope systems and archetypes

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#758]
Since the incorporation of the envelope systems to the CEA databases, the construction properties assumed by the archetypes have changed significantly.
![image](https://user-images.githubusercontent.com/18548065/28524792-3cae25c8-7082-11e7-984f-02733cab506f.png)
For example, residential buildings used to have window U-values of 0.9 to 1.5. Now the U-values are 3.1 to 4.8 for all cases except renovation in 2020.

Was this a conscious decision to change U-values so significantly? And if so, do we have a source for the new assumptions? Or was this a mistake?

@JIMENOFONSECA, @gabriel-happle: since you guys created the envelope systems file, maybe you can shed some light?

**Comment by JIMENOFONSECA** [comment]
Hi martin,

This is a mere mistake. Please feel free to revert it.

Jimeno

On 24 Jul 2017, at 21:28, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #758<https://github.com/architecture-building-systems/CEAforArcGIS/issues/758> to @JIMENOFONSECA<https://github.com/jimenofonseca>.
