### ISSUE TITLE
check if 'calc_HVAC' is feasible for cooling loads

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#76]
Currently using the Kaempf model, we should check if that is the best way to calculate cooling load (de-humidification and cooling).

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle is this issue still open? if so, what are the plans to address it?

**Comment by gabriel-happle** [comment]
We are actually not using Kaempf model any more. As it assumed 100% outdoor air, which is not reasonable. But anyways we will see as soon as we run our first Singapore simulations, whether our models are feasible
