### ISSUE TITLE
storage_main.py need to be modified to include additional technologies

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#772]
There is only one storage technology being considered at the moment, where a storage tank with a fixed volume is considered and it is maintained at a certain temperature.

The current logic is to make sure the thermal energy in the storage at the starting of the year is equal to the thermal energy at the end of the year. This is to ensure no further accumulation or utilizing more thermal energy than the available limit

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
