### ISSUE TITLE
Operating cost of solar collectors is not calculated

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#773]
Also, the auxiliary equipment electricity required to run HEX of data servers and compressed air, as well as storage heat pump is not calculated

**Comment by BhargavaKrishnaSreepathi** [comment]
nice catch...Just found that the cost calculations for the SC, PV, PVT have Capex_a, Opex_fixed terms but are missing Opex_var term. @shanshanhsieh Can you help me with this? I am suspecting that the electricity charges of PV, PVT has some portion deducted for operating the technology. Is this the case? Or do you suggest something else. For reference, the cost calculations for the SC are done in `cea\technologies\solar\solar_collector.py`.

**Comment by shanshanhsieh** [comment]
i am on it!
