### ISSUE TITLE
Decide whether to keep the "create_function_graphs" functionality

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#782]
This functionality is currently broken and might not be necessary; It uses graphviz to create a call graph of the functions in the CEA. We need to fix it a bit or remove it from the codebase.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas remove if not necessary

**Comment by shizhongming** [comment]
replace with a guide of pycharm profiler

**Comment by gabriel-happle** [comment]
@daren-thomas 
I took some screenshots on how to run the profiler.
Where should this guide be added?

**Comment by gabriel-happle** [comment]
![image](https://user-images.githubusercontent.com/17002288/37506401-a1996e74-2924-11e8-9dbb-f9b63f714317.png)

I also tried the `coverage.py`
I guess that's quite a useful feature for testing.

https://coverage.readthedocs.io/en/coverage-4.5.1/

**Comment by daren-thomas** [comment]
@gabriel-happle it should be added to the readthedocs documentation. see the `docs` folder in the repo. maybe best add it to the developer's walk-through toc as a separate file ('how to profile with pycharm'?)

**Comment by JIMENOFONSECA** [comment]
@daren-thomas as discussed, I Think we can erase that create_graphs functionality.

**Comment by daren-thomas** [comment]
It seems this has been removed a while ago.
