### ISSUE TITLE
Removing innumerable saved files generated in optimization main

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#785]
Running optimization main file creates so many files with just two rows present in them. I do not think we will ever use these files. These files include:

1. AveragedCostData.csv
2. InvestmentCostDetailed.csv
3. PrimaryEnergyBySource.csv
4. SlaveCostData.csv
5. SlaveDetailedEmissionData.csv
6. SlaveDetailedEprimData.csv
7. SlaveToMasterCostEmissionsPrimE.csv
8. Storage_Sizing_Parameters.csv
9. StorageOperationData.csv

Most of these files just have two rows . If we still want to save them, we can put all the parameters into only one file instead of creating a clutter of files. 

@JIMENOFONSECA @daren-thomas: any comments on this?

**Comment by JIMENOFONSECA** [comment]
As soon as they do not affect functionality, take them out at your discretion

________________________________

**Comment by BhargavaKrishnaSreepathi** [comment]
addressed in PR #889
