### ISSUE TITLE
Connect Daysim radiation to demand calculation

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#797]
Before the whole multi-zone demand calculation #664 I want to connect the daysim radiation to the single zone thermal loads calculation.
In the future I think it would be good to offer both options (single-zone and multi-zone) in the CEA.
What do you think @martin-mosteiro and @JIMENOFONSECA ?

**Comment by gabriel-happle** [comment]
As far as I can see the following functions would have to change:

`thermal_loads.get_prop_solar()`

`sensible_loads.calc_Asol()`

`blinds.calc_blinds_activation()`

`sensible_loads.calc_I_sol()`

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle I think this is a good call in terms of functionality (single and multi-zone). It can also help us to know, what is the effect of multi-zone vs. single zoning into demand calculation. Similar to what we did with infiltration. a quite straightforward research question that can be solved with this.

Good call. this should be integrated first than the multizone.

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA but we are not keeping the old radiation engine, right?
Can I overwrite this functions?

**Comment by JIMENOFONSECA** [comment]
I do not think so, so please go ahead.

On 26 Sep 2017, at 16:05, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/jimenofonseca> but we are not keeping the old radiation engine, right?
Can I overwrite this functions?
