### ISSUE TITLE
Create online manual for sensitivity analysis tool

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#799]

**Comment by martin-mosteiro** [comment]
Done!

**Comment by JIMENOFONSECA** [comment]
Check tutorials?

On 28 Feb 2018, 00:02 +0800, Daren Thomas <notifications@github.com>, wrote:

I can't find the online manual for this anywhere... Where is it?

**Comment by daren-thomas** [comment]
![image](https://user-images.githubusercontent.com/2969564/36782278-c19436ea-1c78-11e8-9365-8bd126692511.png)

i did that. that is why i created this issue: it's not there. there's no link. this is the page the "https://cityenergyanalyst.com/" site links to when manuals->tutorials is clicked. i assume it used to be accessible from this page?

http://city-energy-analyst.readthedocs.io/en/latest/tutorials.html

**Comment by JIMENOFONSECA** [comment]
Fixed!

On 28 Feb 2018, 18:17 +0800, Daren Thomas <notifications@github.com>, wrote:

[image]<https://user-images.githubusercontent.com/2969564/36782278-c19436ea-1c78-11e8-9365-8bd126692511.png>

i did that. that is why i created this issue: it's not there. there's no link. this is the page the "https://cityenergyanalyst.com/" site links to when manuals->tutorials is clicked. i assume it used to be accessible from this page?

http://city-energy-analyst.readthedocs.io/en/latest/tutorials.html
