### ISSUE TITLE
Modify current MOO for multiple zone connections

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#80]
- For mixed used buildings, the optimization should also determine the specific zones at which time period will be connected via network.
- The is assuming large buildings in the future high density cities, different zones in one building might connect to different sets of networks. More research is required regarding this assumption as well.

**Comment by BhargavaKrishnaSreepathi** [comment]
@shanshanhsieh : does this mean, that the network is time dependent? or more like there are two or three networks for the entire year. These networks will be operated at different times of the day based on the requirement?

**Comment by shanshanhsieh** [comment]
1.  network is time dependent? or more like there are two or three networks for the entire year. These are all possible hypothesis, need more research to decide
2. These networks will be operated at different times of the day based on the requirement? Yes, this is how the current network is running as well.

**Comment by BhargavaKrishnaSreepathi** [comment]
Do you mean, that in current setting there are multiple networks with same buildings?

**Comment by shanshanhsieh** [comment]
Yes, in the current setting, district cooling and district heating networks are separated, therefore, could have different layout/connections.

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
