### ISSUE TITLE
As a researcher, I'd like to implement new cooling technologies in CEA

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#811]

**Comment by shanshanhsieh** [comment]
This Epic will be activated at the second stage of Hybrid Cooling System analysis (Nov, 2017).

- Update CEA demand calculation with low-ex cooling system (Outdoor air unit/ Sensible cooling unit/Latent cooling unit)

- Connect demand results from CEA to OSMOSE

- Implement new cooling system models in CEA

**Comment by gabriel-happle** [comment]
Hi @shanshanhsieh could you please check quickly if any of the remaining low priority issues #208, #610, #1022, #1053 of this epic need to be in the super final version?
Otherwise my part of this epic is finished in terms of functionalities. The rest will be bug-fixing on the go.

**Comment by gabriel-happle** [comment]
#1053 removed from epic after consultation with @shanshanhsieh.
