### ISSUE TITLE
Think about how to make the whole course into a story

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#818]
with subplots per day.

Remember: a story has a hero (bonus points if the attendees get to be heros) and villain (can be abstract) etc.

**Comment by JIMENOFONSECA** [comment]
@amraladdin my advice is to do it in the order we have it. From data mining up to optimizing the area up to comparing scenarios.

morning hours. theoretical input.
afternoon hours. hands on the tool with a practical exercise.

**Comment by amraladdin** [comment]
I'll start from that point and then see what will evolve. This point, however, will begin after we settle on the date of the winter school tomorrow (monday 9th of October)

**Comment by amraladdin** [comment]
I think this can be merged with the Detailed schedule preparation issue.

**Comment by amraladdin** [comment]
I suggest to combine this issue with #919
