### ISSUE TITLE
Prepare a list of Keynote speakers and presentation topics

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#819]
We need to list Keynotes alternatives to be presented during the workshop. This will help reduce the work load on the team members, and encourage potential users to apply for the course.

It would be great if most of the speakers were from Singapore (To avoid high costs and CO2 emissions flying from other destinations). Therefore we need suggestions.

My suggestion is:
- Arno Schlueter, introduction to urban energy systems. 1-1.5 hour lecture, presented on the first day.

**Please provide more alternatives.**
@JIMENOFONSECA @shanshanhsieh @gabriel-happle @shizhongming @Khayatian @martin-mosteiro @BhargavaKrishnaSreepathi

**Comment by JIMENOFONSECA** [comment]
I think we need to keep the lesson focused on the topic of urban energy systems. I will go for a technical audience and provide input accordingly in the morning. This is something the past workshop was missing. The scope of each lesson should be to explain what is behind the scenes of the calculations.

The potential speakers i could propose giving technical 1-hour input could be People of MuSES + you and Martin (Martin will stay for 6 months here, so he will need to travel anywise).

@shanshanhsieh would you be in with a 1 hour lesson about how to analyze energy potentials?
@gabriel-happle would you be in with a 1 hour lesson about the guts of the demand calculation in buildings?
@BhargavaKrishnaSreepathi would you be in with a 1 hour lessons on how to optimize a district energy system?
@shizhongming would you be in with a 1 hour lesson on how to create scenarios?
@amraladdin would you provide input on how to mine data and the data helper?
I will provide input on urban energy systems analysis in general. 

We could leave this issue to the 9th of october discussion.

**Comment by amraladdin** [comment]
@JIMENOFONSECA with Keynote speakers, I meant with someone famous or has a high position in the university like Arno. This person would focus on the general topic and present examples. This, according to Arno, helps attract applicants to the course. Perhaps you and Arno should talk about who to invite. Otherwise, we can say that you will give one Keynote, and Arno will give another.

As for the data mining and data helper, yes, I'm willing to give this session.

Regarding our audience. I'm not sure how technical you plan this course to be. Do you mean going through the Python code in class? Or just explaining what's behind the calculations?

**Comment by amraladdin** [comment]
Keynotes:
o	AS	- 1.5 hours, general introduction and examples.
o	JF	- Input on urban energy systems analysis in general (Process and rule of  thumb calculations).
Workshop lectures:
o	SH	- 1 hour lesson about how to analyze energy potentials.
o	GH 	- 1 hour lesson about the guts of the demand calculation in buildings.
o	BK	- 1 hour lessons on how to optimize a district energy system?
o	ZS	- 1 hour lesson on how to create scenarios.
o	AE	- 1 hour on how to mine data and the data helper?

According to our meeting today, each CEA developer should be able to finish the following by end of the year:
- BK | Singapore case study.
- SH | optimization, solar potential and Singapore status quo cooling load.
- GH | radiation script.
- ZS | Inventory and GH plugin (together with Daren).

**Comment by shanshanhsieh** [comment]
small modifications:
BK | Supply system optimization for Singapore case study (EcoCampus).
SH | Solar potential, Singapore status quo cooling technologies, support BK in optimization.

**Comment by amraladdin** [comment]
Great! Updated :) Thanks Shanshan!

**Comment by amraladdin** [comment]
@JIMENOFONSECA We mentioned we would like to contact Francois Marechal to be a keynote speaker at the end of the workshop. Is this still the case? Also, he will be presenting prospects in the field of urban energy systems analysis, is this correct?
