### ISSUE TITLE
CEA Executive course cost

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#820]
We need to decide on how much we intend to charge our students for a 5 or 6 days CEA Executive course. To do so, we need to first check other course costs, which might relate to our domain.

I need someone to check how much the BCA (Building and Construction Authority) and A*STAR (Institute for Science, Technology and Research) in Singapore.

@gabriel-happle @shanshanhsieh @shizhongming could you please help get this information? How much do these institutions charge per full day of courses?

**Comment by JIMENOFONSECA** [comment]
@amraladdin students will not pay for this. I think it is enough with the flights, + accommodation they will have to cover on their own. I do not see charging students happening. 

The cost of the course from FCL's other executive courses is 1700SGD /person for three days including lunch. 

I would not organize lunch, but tea. I assume that without lunch for the five days we can charge **3000 SGD**

**Comment by amraladdin** [comment]
Ok great. I will however need someone from Singapore to manage the preparation of the tea, coffee, hall registration... etc.

Regarding the cost, I will add it to the brochure. As for the students not paying, I don't mind, as long as it is ok for you, Arno and ETH.
