### ISSUE TITLE
Potential Venue and maximum number of attendees

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#821]
We need to define the maximum number of applicants. Therefore, I need someone to:
- Check for Venues at FCL and check how many attendees it can hold. We don't want to aim for more than 20 attendees (Maximum).
- Define a maximum number of attendees, based on availability of places.
- Define the number of scholarships we can give based on the previous steps.

**Comment by JIMENOFONSECA** [comment]
@amraladdin 

The Venue: - Incubator Room at the Future Cities Laboratory.
Max number: - we can accommodate up to 30, you decide if 20.
Scholarships: - Students will not pay for it. So they will need to have the scholarship. 
So i think we open the calls and based on how many people we get willing to pay. We then receive students.

**Comment by JIMENOFONSECA** [comment]
@amraladdin this was decided, should we close the issue?

**Comment by amraladdin** [comment]
Yes sir.
