### ISSUE TITLE
Credit points and list of contacts

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#822]
How many credit points would this course provide to students?

If we calculate according to ETH, then every 25 hours = 1 credit point. Assuming we have 8 hours per day * 6 days, that's 2 credit points. Does this make sense? Or is there a different way of calculating credit points for workshops and winter schools?

@JIMENOFONSECA  @BhargavaKrishnaSreepathi @martin-mosteiro 

Also, we need a contact for the applicants. I can add my name, but I will also need someone from Singapore to help, @JIMENOFONSECA should I add your contact? Or would you nominate someone else?

**Comment by JIMENOFONSECA** [comment]
Man, no idea. I think it seems right but I would cross check with Valerie or Arno.

Best, Jimeno

On 26 Sep 2017, at 19:09, Amr Elesawy <notifications@github.com<mailto:notifications@github.com>> wrote:


How many credit points would this course provide to students?

If we calculate according to ETH, then every 25 hours = 1 credit point. Assuming we have 8 hours per day * 6 days, that's 2 credit points. Does this make sense? Or is there a different way of calculating credit points for workshops and winter schools?

@JIMENOFONSECA<https://github.com/jimenofonseca> @BhargavaKrishnaSreepathi<https://github.com/bhargavakrishnasreepathi> @martin-mosteiro<https://github.com/martin-mosteiro>

**Comment by JIMENOFONSECA** [comment]
@amraladdin  please add my contact. and add those 2 credit points.

**Comment by amraladdin** [comment]
I double checked with Ursula Suter from the studetn planning. I found out that 35 hours of work (lectures + home work) would be equal to 1 credit points. So I think we should state that it's = 1 ECTS only. @JIMENOFONSECA do you agree?

**Comment by JIMENOFONSECA** [comment]
Hi amr,

It is fine for me :-),

Best, Jimeno

On 9 Oct 2017, at 19:09, Amr Elesawy <notifications@github.com<mailto:notifications@github.com>> wrote:


I double checked with Ursula Suter from the studetn planning. I found out that 35 hours of work (lectures + home work) would be equal to 1 credit points. So I think we should state that it's = 1 ECTS only. @JIMENOFONSECA<https://github.com/jimenofonseca> do you agree?

**Comment by amraladdin** [comment]
I believe this is also decided. Will close this issue.
