### ISSUE TITLE
CEA Winter School - Create a detailed daily schedule

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#823]
Create a detailed schedule and share with the CEA Development team.

**Comment by JIMENOFONSECA** [comment]
@amraladdin waiting for this

**Comment by amraladdin** [comment]
This will also be decided after defining what the tool features presented will be and the case study we will be working on (after Monday 9th of October).

**Comment by amraladdin** [comment]
Points to resolve before creating the final schedule:
- Will we have a Singapore Case study?
- What features is the tool expected to have by then?
- Who will participate? For how long?

We have already discussed on some of these points, but I'm keeping them here as a check point.

**Comment by amraladdin** [comment]
Preliminary schedule:
Keynotes:
o AS - 1.5 hours, general introduction and examples.
o JF - Input on urban energy systems analysis in general (Process and rule of thumb calculations).
Workshop lectures:
o SH - 1 hour lesson about how to analyze energy potentials.
o GH - 1 hour lesson about the guts of the demand calculation in buildings.
o BK - 1 hour lessons on how to optimize a district energy system?
o ZS - 1 hour lesson on how to create scenarios.
o AE - 1 hour on how to mine data and the data helper?

According to our meeting today, each CEA developer should be able to finish the following by end of the year:

    BK | Supply system optimization for Singapore case study (EcoCampus).
    SH | Solar potential, Singapore status quo cooling technologies, support BK in optimization.
    GH | radiation script.
    ZS | Inventory and GH plugin (together with Daren).
