### ISSUE TITLE
installing CEA dev on workstation

### ISSUE THREAD

**Issue by Khayatian** [architecture-building-systems/CityEnergyAnalyst#827]
Im installing CEA dev. on a workstation (here in Singapore) to test some codes. I run into an error, from which I took a screenshot (you may find it attached to the text). Could someone please provide me some insight/potential fix on this issue?

![screenshot](https://user-images.githubusercontent.com/27851066/30891963-8efde4d0-a368-11e7-97ae-4285fa458ef6.png)

**Comment by JIMENOFONSECA** [comment]
@Khayatian did you try to follow the new installation guide?

**Comment by Khayatian** [comment]
update on the issue:

cannot connect pycharm to CEA as I do not have the file python.exe in any of the following locations:
C:\Users\your_name\Anaconda2\envs\cea\python.exe
or
C:\Users\your_name\AppData\Local\conda\conda\envs\cea\python.exe

**Comment by Khayatian** [comment]
update:
tried uninstalling reinstalling, no python.exe file in the suggested directory

**Comment by JIMENOFONSECA** [comment]
Please contact Daren Via Slack and ask for a meeting immediately to solve this.
we need to move on with the experiments.

best, JImeno
________________________________

**Comment by Khayatian** [comment]
Ok, I will proceed with it now

**Comment by Khayatian** [comment]
new update:
the issue was resolved through administrative access.
The new error says that "the command line is too long"

**Comment by Khayatian** [comment]
the error:
![Untitled2.png](https://images.zenhubusercontent.com/59cb0a21b0222d5de47944a4/dc5fdff7-cdab-45db-a463-87b7b79914ff)

**Comment by daren-thomas** [comment]
@Khayatian Fazel, before we close this issue: could you please comment on how you fixed it? For future generations, weisch...

**Comment by Khayatian** [comment]
The issue was with administration access, so I just ran the code as administrator.
