### ISSUE TITLE
Create Mailchimp account and send out invitations

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#828]
@amraladdin I believe the poster is a good beginning. however it would be easier if we use mailchimp to distribute e-mails to all the community. Please check the channel in Slack I have sent you via e-mail examples of the executive course the guys from mobility did. There is also an excel file on slack with the names of people to whom invite.

**Comment by amraladdin** [comment]
Good job Jimeno. Which channel are you talking about on Slack? the Winter School Channel? What should I be looking at there? I did receive your emails, but not on Slack.

I agree, seems like a better idea to use mailchimp for the invitations.
