### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by Khayatian** [architecture-building-systems/CityEnergyAnalyst#829]
I am getting this error related to fiona, I tried the instructions from the installation guide, but there is no proj.dll in C:\Users\your_name\Anaconda2\envs\cea\proj.dll , however, the file is in its correct location at:
C:\Users\your_name\Anaconda2\envs\cea\Library\bin

some help will be appreciated

**Comment by daren-thomas** [comment]
@Khayatian do you have a screenshot of the whole error? Can you import fiona from the command line? What operating system are you running on? What version of python? Which part of the installation guide did you follow? Is this the first installation on that system?

**Comment by daren-thomas** [comment]
@Khayatian Fazel, is this connected to #827 at all?

**Comment by Khayatian** [comment]
@daren-thomas 
1) I will add a screenshot rightaway,
2) I will try to import fiona from command line and see whether it works
3) python 2.7 x64
4) I installed the cea for developers guide, the installation finished without error
5) yes this is the first installation on our tool on this windows 2012 server OS

**Comment by Khayatian** [comment]
No the previous issue was fully resolved once I got administrative access.

**Comment by Khayatian** [comment]
Traceback (most recent call last):
  File "C:/CityEnergyAnalyst/cea/demand/calibration/nn_generator/nn_random_sampler.py", line 2, in <module>
    from cea.demand.demand_main import properties_and_schedule
  File "C:\CityEnergyAnalyst\cea\demand\demand_main.py", line 16, in <module>
    from cea.demand import thermal_loads
  File "C:\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 11, in <module>
    from geopandas import GeoDataFrame as Gdf
  File "C:\Users\fazel\Anaconda2\envs\cea\lib\site-packages\geopandas\__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "C:\Users\fazel\Anaconda2\envs\cea\lib\site-packages\geopandas\io\file.py", line 3, in <module>
    import fiona
  File "C:\Users\fazel\Anaconda2\envs\cea\lib\site-packages\fiona\__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "C:\Users\fazel\Anaconda2\envs\cea\lib\site-packages\fiona\collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: DLL load failed: The specified procedure could not be found.

Process finished with exit code 1

**Comment by Khayatian** [comment]
@daren-thomas  could you please tell me how to import fiona from command line?

**Comment by daren-thomas** [comment]
```
C:\Users\darthoma\Documents\GitHub\CityEnergyAnalyst (i351-calibrator-cea)
λ python
Python 2.7.13 | packaged by conda-forge | (default, May  2 2017, 13:28:48) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
>>>
```

**Comment by JIMENOFONSECA** [comment]
Guys, talking on the phone will solve this faster :-))).

- prefer face to face rather than tools to fix problems..


On 27 Sep 2017, at 3:30 pm, Fazel Khayatian <notifications@github.com<mailto:notifications@github.com>> wrote:


@daren-thomas<https://github.com/daren-thomas> could you please tell me how to import fiona from command line?
