### ISSUE TITLE
Prepare a TEST PLAN meeting

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#845]
- [x] Set a date to meet Daren and go through the Test plan preparation.

- Outcome of this meeting should be:   

- [x] Tentative structure and breakdown of the tasks

- [ ] Proposed timeline

- [ ] Tasks assignment (Who can be our brother community testers?)

**Comment by amraladdin** [comment]
We should continue working on this

**Comment by amraladdin** [comment]
@daren-thomas should we follow up on this?

**Comment by daren-thomas** [comment]
@amraladdin I'm working on branch `845-test-plan` creating documentation for testing. feel free to add any ideas in the `docs/testplan` folder.

**Comment by amraladdin** [comment]
hi @daren-thomas, where can I find the `docs/testplan` folder?

**Comment by daren-thomas** [comment]
@amraladdin  you need to check out branch 845-test-plan for the folder to show up in your repository.
