### ISSUE TITLE
LCA and Economic Database for Singapore

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#846]
We need to get LCA and economic databases for Singapore. Otherwise, we will have to work with the Swiss database. To do so, for each point, we need to:

- [ ] List potential candidates that might have this information or can help get it.

- [ ] List what needs to be defined for each point.

**Comment by amraladdin** [comment]
Hey @gabriel-happle and @JIMENOFONSECA , I believe you had some candidates, which we can contact. Any news on that?

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA and @amraladdin
please check this and tell me if I have to edit/modify anything: 
https://sirop.org/app/9e469258-c744-40d6-a4d0-c9b84687c76b?_k=feAcXlj7-oL0O7Ig

**Comment by JIMENOFONSECA** [comment]
It looks good. thanks for taking care of this.

On 10 Nov 2017, at 12:03 pm, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/jimenofonseca> and @amraladdin<https://github.com/amraladdin>
please check this and tell me if I have to edit/modify anything:
https://sirop.org/app/9e469258-c744-40d6-a4d0-c9b84687c76b?_k=feAcXlj7-oL0O7Ig

**Comment by amraladdin** [comment]
Hey guys, did you get any applications yet?

**Comment by gabriel-happle** [comment]
@amraladdin Yes. We have someone that is interested. He could start in April.
A Malaysian master student from TU Berlin.
I don't think there is any chance we could start earlier. So I don't know if we already have our data in time for the course. But at least we could then show that we are working in it and that we will have it soon...
What do you think?
Do you want to take a look at his CV?

**Comment by amraladdin** [comment]
Hey Gabriel,
I agree. So no embodied energy calculations using the CEA, but I guess we could do the LCA using an Excel sheet, right? and mention that we are working on it. Yeah, please send me his CV, thanks.

Best,
Amr

**Comment by gabriel-happle** [comment]
@amraladdin after consultation with Jimeno I offered the position to the student.

**Comment by amraladdin** [comment]
@gabriel-happle Thanks for the update... I thought you had already chosen him. I'll close this issue then.
