### ISSUE TITLE
Connect substation scripts in a single script

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#85]
connect substationMain.py, substationModel.py and substationFn.py into one substation script

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh is this still relevant? what is the action plan?

**Comment by shanshanhsieh** [comment]
yes, i would still like to do this! but it comes after the network optimization is stable, therefore, stays as priority 2!
