### ISSUE TITLE
Prepare a list of dates for the CEA Summer School

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#850]
Taking into account:
- NUS and NTU free summer periods.
- ETHZ summer vacation and exam dates.
- The FCL conference and summit.

**Comment by amraladdin** [comment]
@JIMENOFONSECA here's all the infromation regarding the exams, important dates, overlap periods, tentative dates and my recommendation.

**NUS and NTU students have the summer holidays**
- From 12.05 till 04.08
**NUS and NTU students have the summer holidays**
- From 09.06 till 06.08
**FCL Conference and Summit**
- From 08.07 till 12.07

Proposed dates:
**- Mon 02.07 till Sat 07.07** (Better dates for workshop preparation, Daren can join, and it is directly attached to the summit and FCL conference, Amr recommends this option)
**- Fri 13.07 till Wed 18.07** (directly attached to the summit and FCL conference, however, goes through the weekend, and daren can't join, having the workshop after the conference might be exhausting for the workshop preparation team)
**- Mon 16.07 till Sat 21.07** (separate from the workshop dates, Daren can't join, too long for the attendees to stay in Singapore, could be exhausting for the workshop preparation team)

**Comment by JIMENOFONSECA** [comment]
Amr, thanks for the info. What about exam session in eth?

Best, Jimeno

On 9 Oct 2017, at 20:17, Amr Elesawy <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/jimenofonseca> here's all the infromation regarding the exams, important dates, overlap periods, tentative dates and my recommendation.

NUS and NTU students have the summer holidays

  *   From 12.05 till 04.08
NUS and NTU students have the summer holidays
  *   From 09.06 till 06.08
FCL Conference and Summit
  *   From 08.07 till 12.07

Proposed dates:
- Mon 02.07 till Sat 07.07 (Better dates for workshop preparation, Daren can join, and it is directly attached to the summit and FCL conference, Amr recommends this option)
- Fri 13.07 till Wed 18.07 (directly attached to the summit and FCL conference, however, goes through the weekend, and daren can't join, having the workshop after the conference might be exhausting for the workshop preparation team)
- Mon 16.07 till Sat 21.07 (separate from the workshop dates, Daren can't join, too long for the attendees to stay in Singapore, could be exhausting for the workshop preparation team)

**Comment by amraladdin** [comment]
ETH Students have their Spring semester exams from the 6th till the 31st of August.

**Comment by amraladdin** [comment]
This has been decided. From Monday 2nd of july till Saturday 7th of July.
