### ISSUE TITLE
Document the configuration file

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#858]
The configuration file needs documentation addressing:

- how does it work? 
- what are the valid parameters that can be entered?
- where to make changes?
  - default.config
  - cea.config
  - project.config
  - scenario.config
- explain the cascade?
- for developers:
  - how to add a new section
  - how to add a new parameter
  - what is going on with the `@property` and `@parameter.setter` methods??

**Comment by JIMENOFONSECA** [comment]
preferable if we combine it with #836

**Comment by daren-thomas** [comment]
@JIMENOFONSECA #836 includes a few short notes on editing the configuration file in the installation guide. The scope of this issue is big enough for it's own issue, I think. We can make #836 dependant on this issue, though, if you like?

**Comment by JIMENOFONSECA** [comment]
Some user cases:
- PACHO runs the cea-toolbox.
- if we run for the first time from pycharm. PACHO will indicate the scenario path in the home folder. After this, a copy called scenario.config will be created in the scenario folder. PACHO will use this to run his simulations.
- if PACHO wants to change scenario for the first time. He needs to do all the process again (change the configuration in home folder again).
- if PACHO creates a new parameter during development in the default configuration file he does not need to do anything. But if he wants to change the new parameter, he needs to copy it and added to the scenario.config manually.

**Comment by JIMENOFONSECA** [comment]
So about the cascading, we talked about allowing the cea.config to only store the scenario where to run the calculations.
the sceanario.config will stores all other properties but the scenario path. In this way we can avoid mismatches and confusion.
