### ISSUE TITLE
Rename variables in retrofit-potential that use "age" instead of "year"

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#875]
The use of the word "age" (as in, an amount of years) is not always appropriate in the retrofit potential script. Go through each such variable and make sure "age" is used as a year-count as opposed to a year to avoid confusion in the reader.

**Comment by JIMENOFONSECA** [comment]
The retrofit potential tool is not anymore supported so this issue can be closed
