### ISSUE TITLE
Encountered a maximum path limit in windows of 260 characters when saving a file

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#880]
For ecocampus case study with 221 buildings, while generating network_totals file, the file name is supposed to be `Total_indcombi`, where indcombi represents 0's and 1's corresponding to if the buildings are active or not. While trying to save this file, I encountered a problem that the file name is too long and thus it cannot be created. To test my hypothesis, I changed the `indcombi` manually to a smaller length and I was able to generate the file without any issue. @daren-thomas @JIMENOFONSECA any thoughts about this? If in case we are going to change `indcombi`, then we need to change it in multiple places or we shoudl think of an alternate way to store these files

**Comment by BhargavaKrishnaSreepathi** [comment]
I found few ways to increase the path limit by changing windows registry. Is it advisable?

https://mspoweruser.com/ntfs-260-character-windows-10/ 
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by JIMENOFONSECA** [comment]
Good point. so there are several places at which this is used as a barcode right?
maybe Daren has an idea. I am out of one at the moment


On 31 Oct 2017, at 4:07 pm, Bhargava Krishna Sreepathi <notifications@github.com<mailto:notifications@github.com>> wrote:


For ecocampus case study with 221 buildings, while generating network_totals file, the file name is supposed to be Total_indcombi, where indcombi represents 0's and 1's corresponding to if the buildings are active or not. While trying to save this file, I encountered a problem that the file name is too long and thus it cannot be created. To test my hypothesis, I changed the indcombi manually to a smaller length and I was able to generate the file without any issue. @daren-thomas<https://github.com/daren-thomas> @JIMENOFONSECA<https://github.com/jimenofonseca> any thoughts about this? If in case we are going to change indcombi, then we need to change it in multiple places or we shoudl think of an alternate way to store these files

**Comment by JIMENOFONSECA** [comment]
yeah that could be a quick solution to move on..


On 31 Oct 2017, at 4:10 pm, Bhargava Krishna Sreepathi <notifications@github.com<mailto:notifications@github.com>> wrote:


I found few ways to increase the path limit by changing windows registry. Is it advisable?

https://mspoweruser.com/ntfs-260-character-windows-10/
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by BhargavaKrishnaSreepathi** [comment]
Sadly, that did not work on my computer. Can someone else try creating a csv file with the following name
`Total_10110011001101111111101101000000101111011010111101100000000000100111111111000110110111010000001000011101000000100010000001010110100100101101100001110000100001101110011100001111100000111100010000011101110110100100000011010.csv` and open it? Thanks

**Comment by BhargavaKrishnaSreepathi** [comment]
Addressed this using hexadecimal numbers instead of binary
