### ISSUE TITLE
cea research installation not working

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#885]
Tried to install CEA following the steps given in installation guide, and got the following error 

`>conda env create
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .......................

ResolvePackageNotFound:
  - libnetcdf 4.4.1.1 vc9_5`

@daren-thomas: any comments?

**Comment by daren-thomas** [comment]
@BhargavaKrishnaSreepathi yes, i know about this. I have a fix, I'll create a PR right now...

**Comment by daren-thomas** [comment]
Fixed with PR #886
