### ISSUE TITLE
Implement bivalent heating systems in disconnected buildings

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#89]
`discBuildMain_noCluster.discBuildOp`
Implement bivalent systems for heating (heat pump for base load and gas boiler for peak (already implemented, but can be improved), include solar thermal,…)

**Comment by JIMENOFONSECA** [comment]
This is a year old issue. @martin-mosteiro what is the status / action plan for this?

**Comment by martin-mosteiro** [comment]
Honestly, I have done nothing on this. I can start looking into it, though.

**Comment by BhargavaKrishnaSreepathi** [comment]
`decentralized_buildings.py` is considering 13 options for now in optimization, which includes fuel cell, boiler and cogeneration technologies. The options go as follows:
1. Bio gas Boiler
2. Natural gas Boiler
3. Fuel Cell
4. 10 options of Geothermal Heat Pump with various % of Boiler and GHP. It goes from 0% Boiler to 90% Boiler

This is presented as a combinatorial problem (or at least that's what the documentation says). Need to go through this in further detail, only then I can comment about this.

**Comment by shanshanhsieh** [comment]
For buildings in Singapore, we might also need to have bivalent systems.  I will revisit this issue for cooling supply around the 4th quarter of 2017.

**Comment by martin-mosteiro** [comment]
@BhargavaKrishnaSreepathi @shanshanhsieh Any updates on this? I don't think I'll need this after all.

**Comment by shanshanhsieh** [comment]
@martin-mosteiro i will not need this at the moment as well, also, with the splitting of OAU, RAU, SCU, we can implement different systems supplying space heating/cooling, and that's sufficient for my research.
therefore, i think this is a "nice to have"

**Comment by JIMENOFONSECA** [comment]
closing. we will not do this
