### ISSUE TITLE
New radiation engine (DAYSIM by P. NEITZEL)

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#9]
The existing radiation engine is dependent on arcgis. It would be great to have a more powerful and stand alone engine.

**Comment by shanshanhsieh** [comment]
KianWee from SMART could possibility implement his algorithm. It will solve this issue if that works.

**Comment by JIMENOFONSECA** [comment]
Paul Nietzel will work on this in the next 6 months as part of his master thesis

**Comment by JIMENOFONSECA** [comment]
@paulneitzel we cannot get it run and get the next error. do you know what could be the cause? this issue is being reworked for the cea tool in the branch i9-New-Radiation-Engine

![image](https://cloud.githubusercontent.com/assets/8973186/20697572/30e0ac00-b635-11e6-8f05-7e5b44c1b374.png)
