### ISSUE TITLE
Create script to generate final reports (output of the entire tool)

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#90]
automatically create reports with plots of the results of the entire tool (after optimization)

**Comment by JIMENOFONSECA** [comment]
This is a year old issue. @shizhongming what is the status / action plan to carry out this task? I believe this was mentioned during the  CEA workshop as a priority for this year.

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA I'm closing this as author on behalf of @shizhongming.
I believe this is solved with all the nice visualizations CEA can create now.
