### ISSUE TITLE
Port to python 3

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#900]
This could be "fun" to do. So basically, to run the neural network in our GPU's and Tensorflow we need python 3.5.  Would this make sense? It might brakedown the code substantially, Specially all the print statement. Any chance I can help with this in a branch?

**Comment by daren-thomas** [comment]
Well... 2019 (or was it 2020?) the NumPy project is going to drop support for python 2 anyway... so. We'll need to look into it...

What I'm mainly worried about is all the dependencies... each single library that we import will need to be checked for a python 3 version...

**Comment by daren-thomas** [comment]
So... If you have time to do that?

**Comment by JIMENOFONSECA** [comment]
Closing. this will not happen in the near future of the project

**Comment by daren-thomas** [comment]
@JIMENOFONSECA Python 2.7 is end-of-life in January 2020. I suggest we do the port, but maybe after MuSES?

**Comment by JIMENOFONSECA** [comment]
yes... i think we open this issue when we need to do it. For now, it is just background noise. I lose time trying to understand the issue (and similar ones) every sprint. i suggest to close all that we will not be doing in a year time. It is just taking us out of focus. It is distracting...

Some pruning to get to our priorities and roadmap will be good. I do not see us working on this issue even in a year tim since we will opt in for work on user-experience related issues...

On 20 Sep 2019, 16:33 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> Python 2.7 is end-of-life in January 2020. I suggest we do the port, but maybe after MuSES?
