### ISSUE TITLE
Minor problem with scripts for solar technologies

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#905]
The scripts `photovoltaic.py` and `photovoltaic_thermal.py` list building names from the occupancies of the buildings, instead of from the shapefile for the zone of study. This can lead to problems when the occupancy includes buildings that are not in the zone of study (e.g. buildings in the district that are outside the zone of study).

Since this list is created in order to input the surface radiation properties of buildings within the area of study, it makes more sense to import the list of names from `zone.dbf` instead.

So I'm changing line 753 in the photovoltaic script (581 in photovoltaic_thermal) from
```
list_buildings_names = dbfreader.dbf_to_dataframe(locator.get_building_occupancy())['Name']
```
to
```
list_buildings_names = dbfreader.dbf_to_dataframe(os.path.join(locator.get_building_geometry_folder(), 'zone.dbf'))[
    'Name']
```

**Comment by martin-mosteiro** [comment]
I made the change above and the script works as expected. However @daren-thomas has some ideas how this could be done better, so I'll let him take over from here.

**Comment by daren-thomas** [comment]
Yes. I suggest we create a `locator.get_zone_building_names()` function. I'm on it!
