### ISSUE TITLE
Cluster building demands according to typical day behaviors

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#92]
check if that is possible

**Comment by JIMENOFONSECA** [comment]
this is a year old issue. @shanshanhsieh what is the status and action plan about this?

**Comment by shanshanhsieh** [comment]
This issue was set up for the WSBE study, but this functionality is not required at the moment.
Therefore, the priority goes to "priority 2" - good to have.
