### ISSUE TITLE
Computing power for executive course

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#922]
The following problem need to resolve
 
1. ArcGIS license server is in ETH (need to turn on VPN when in use) . Since we have to use VPN, we cannot install VPN on other entity notebook

2. We cannot install ETH ArcGIS software on other entity laptop.

3. There is no 30 days evaluation for ArgcGIS, except for ArcGIS Pro.

4. As for all user login into local server, the server will not be able to handle 30 user at the same time doing the process at the same time (beside that we need to purchase 30 Windows client license)
 
5. Estimate per laptop is $1.5k. Total investment   $1.5k x 30 = $45K

**Comment by JIMENOFONSECA** [comment]
@daren-thomas any thoughts?

**Comment by shizhongming** [comment]
talk to ESRI...

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi give us a hand looking for a room in NUS thnaks! HNY2018
