### ISSUE TITLE
Print out advanced demand script parameters in `demand_main.main()`

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#927]
We added new parameters, but don't print them out at the start of the script.

**Comment by daren-thomas** [comment]
In fact, go a step further and create a library function on the `config` object to print out the parameters: `config.print_script_parameters('demand')` and use the `cli.config` file to figure out what parameters to print. Then, update all scripts to use this. Also update the template and the guide (how to create a new script)

**Comment by JIMENOFONSECA** [comment]
@daren-thomas can we close this issue?

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
