### ISSUE TITLE
Fixed mass flow rate inside the heat exchanger

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#93]
Mass flow rate inside the heat exchanger at building substation is currently fixed (mcpa=mcp_1.1), feasible pressure range and pips size inside heat exchanger are not considered.
This belongs to *_`EDMFunction.calc_sewagetemperature`**

**Comment by shanshanhsieh** [comment]
this is relating to #95

**Comment by JIMENOFONSECA** [comment]
This is an year old issue too @shanshanhsieh is this still relevant?

**Comment by JIMENOFONSECA** [comment]
we won't have this
