### ISSUE TITLE
As a researcher, I'd like to know how to install solar technologies in Singapore

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#940]
The following rules/assumptions should be modified to SG conditions:

- Tilt angles
- Threshold for PV/SC installation
- Mutual shading of panels
- ...

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh is this still the case?, if not maybe we can close it?

**Comment by JIMENOFONSECA** [comment]
this won't happen any time soon (6 - 12 months time), so we close it
