### ISSUE TITLE
Modify dynamic supply systems interface

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#945]
The interfaces of `Photovoltaic Panels`, `Solar Collector Panels`, and `PVT Panels` are running smoothly.
But there are some redundant parameters in the individual panes.
Modifications required are shown in the pictures below:
1. For Photovoltaic Panels
![picture1](https://user-images.githubusercontent.com/16998305/34139394-8b54e8be-e4af-11e7-8c16-750a63883696.png)
2. For Solar Collector Panels
![picture2](https://user-images.githubusercontent.com/16998305/34139404-96bebe64-e4af-11e7-8c13-c46e910174bc.png)
3. For PVT panels
![picture3](https://user-images.githubusercontent.com/16998305/34139412-9c5c49ae-e4af-11e7-8738-8ed2aab95130.png)

**Comment by shanshanhsieh** [comment]
@daren-thomas , could you please make this happen?
i tried to go through the files in the interface folder, but only realised i have no clue on where to make the changes : P
thank you!

**Comment by daren-thomas** [comment]
@shanshanhsieh sure I can. The changes all need to happen in the `default.config` file (controls the texts displayed via the `.help` key) and the `cli.config` (lists the parameters a script takes - normally, the entire section, but for special cases like these, we can list them separately in the format `section:parameter`.

**Comment by daren-thomas** [comment]
@shanshanhsieh check out the PR #946 :-)
