### ISSUE TITLE
Check other models for sewage calculation

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#95]
ex. TEMPEST from eawag

This belongs to the script **`EDMFunction.calc_sewagetemperature`**

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh is this still in your agenda? @martin-mosteiro would you like to take this into account? what is the action plan. This is a year old issue

**Comment by martin-mosteiro** [comment]
I'd call it nice to have.

**Comment by shanshanhsieh** [comment]
This is actually not the first priority for my research at the moment.

**Comment by JIMENOFONSECA** [comment]
we won't have this
