### ISSUE TITLE
Need of a dashboard to present results of CEA

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#955]
So we kind of need a way to summarize graphs about the results we expect from CEA. I will give the first stab to the results we expect from the calibration and pass on the work to everyone so we create dashboards for all. I think this could help to see the results of CEA more easily.

**Comment by daren-thomas** [comment]
want to create a mockup of what such a dashboard could look like? we can then take it from there (check my config-editor pull request for an example of how we now have the technology to display web technologies in a GUI - this could be used to display d3 or bokeh graphs and create a "CEA Dashboard" application)

**Comment by JIMENOFONSECA** [comment]
So i Gave it a first stab using dashboards in plotly. The good. It kind of works. the bad: It requires a paid license in the long term. The graphs also take like 20 second perbuilding to be created.

here is the example:

https://plot.ly/~duplicado/71/timeseries-data-for-building-b04/

Now I would like to have in the best scenario something like this:

**Comment by daren-thomas** [comment]
when do we need this?

**Comment by JIMENOFONSECA** [comment]
I believe we should have it ready for March. I am working on all the graphs we need to include. But do not know how to proceed with creating the dashboard.

On 10 Jan 2018, 6:41 PM +0800, Daren Thomas <notifications@github.com>, wrote:

when do we need this?

**Comment by JIMENOFONSECA** [comment]
So this is what I am pointing out with some of the graphs. To self generate some analysis out of what we can observe in the graphs. 

![image](https://user-images.githubusercontent.com/8973186/34814112-7d4fcdc0-f6e7-11e7-8287-32331f1fdedd.png)

**Comment by daren-thomas** [comment]
Let's team up: I can help create a dashboard-style desktop tool (like the config-editor) in exchange for help with the chart portfolio?
