### ISSUE TITLE
Make release 2.7

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#962]
@daren-thomas once released I can fix zenodo. What we include in this version is CEA for Zenodo

**Comment by daren-thomas** [comment]
@JIMENOFONSECA what is the timeline? I'm adding this to M2.7... What are the things we want to have in this release, what will be pushed to the next release (2.8?)

**Comment by JIMENOFONSECA** [comment]
I think the release date is now. It includes compatibility with ubuntu... i am for releasing as often as we can and i think your work on the config reader and ubuntu is great for this release

Best,
Jimeno

On 15 Jan 2018, 16:39 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/jimenofonseca> what is the timeline? I'm adding this to M2.7... What are the things we want to have in this release, what will be pushed to the next release (2.8?)

**Comment by JIMENOFONSECA** [comment]
@daren-thomas some fixes needed from the ubuntu installation

While running the new config-editor
- ImportError: No module named htmlPy...
- ImportError: No module named pysycode.. etc..
-

**Comment by JIMENOFONSECA** [comment]
Maybe we can release after the tests pass?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas what about a release today after the group meeting?

**Comment by JIMENOFONSECA** [comment]
Yep

On 27 Feb 2018, 18:04 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/jimenofonseca> are we done here? I think we can close this now, right?
