### ISSUE TITLE
Renaming tools for ArcGIS

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#963]
As discussed in issue #814, the solar technologies tools (PV,PVT,SC) are now under the **Dynamic Supply Systems** tab, and it's confusing with the **Renewable Energy Assessment** tab.
Therefore, as @daren-thomas suggested, this issue is opened for all to discuss the naming of the current CEA toolbox (see image below). (daren, i also assigned you cuz you know how to make the changes : )

![image](https://user-images.githubusercontent.com/16998305/34979497-5f4bc236-fadc-11e7-8b5c-3f81154bae7d.png)

**Comment by shanshanhsieh** [comment]
my proposals:
1. Move the three solar technologies to "Renewable Energy Assessment", the same tab as "Urban solar radiation"
2. option 1 + make a separate tab for "Urban solar radiation" since it is used for both demand and supply calculations
3. or change "Dynamic Supply Systems" to "Renewable Energy Potential" or "Energy Supply Technologies".

**Comment by JIMENOFONSECA** [comment]
I agree with shanshan's option 3 changing the name to energy supply technologies
