### ISSUE TITLE
Create a simple Dashboard app

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#966]
Based on @JIMENOFONSECA 's dashboard plots, create a simple GUI th!

Something like 
![this](https://user-images.githubusercontent.com/2969564/35269237-c04dfda2-002b-11e8-91a4-4dd677f3a142.jpg)
 that allows browsing these plots.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas so, we have a great team of visualization at FCl who do most of the dashboards for FCL. They could be of potential help. I met them this morning and they explained it to me how it works. In essence everything is possible. the drawbacks.

1. it will work only in singapore.
2. It will not be open source.

I wonder if we can create something like this withtout external help.

![image](https://user-images.githubusercontent.com/8973186/35259650-fe32f45e-0041-11e8-8de7-1db8f3d498e8.png)

**Comment by JIMENOFONSECA** [comment]
look at the diagram created with this. should we try it?
https://plotcon.plot.ly/workshops

**Comment by daren-thomas** [comment]
Hm... that looks a lot different to the sketch you made above. Basically, with the plotly library, you can output `<div>` elements instead of whole html files like you're currently doing. These can then be added to a web page in a grid system. I was going to make a simple version of what you had above first, letting user's click through the different plots. Then, in a next step, I think we could make a more "dashboard" style overview selecting a few plots.

**Comment by daren-thomas** [comment]
I have some stuff to learn (flask, jquery) but I think it is totally doable in a reasonable amount of time.

**Comment by JIMENOFONSECA** [comment]
So how far are in the implementation? because knowing plotly now, we are not far of doing such a dashboard..

**Comment by JIMENOFONSECA** [comment]
well..Dash is basically a nice wrapper of flask + plotly so it allows to create those web pages easily. I can do the plots and the analytics but will need muscle to deliver the dashboard of the sort. Should we go for it?
