### ISSUE TITLE
Interface and dashboard for CEA

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#967]
An epic to store visualization and data mining efforts. Future ideas:

- Dashboard GUI
- IPython Notebook interface to CEA output
- Interface for navigation scenario comparisons

**Comment by JIMENOFONSECA** [comment]
[Dashboard call N2.pdf](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/1706117/Dashboard.call.N2.pdf)
