### ISSUE TITLE
eliminate district  shapefile

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#978]
So I find it is a major source of work, to come up with a file about the surroundings of a neighborhood. The cost benefit of maintaining this input is rather low. 

The only benefit it is giving is in terms of nice visualizations and some over shading that is considered for external buildings. but that is all. 

@martin-mosteiro @amraladdin opinions.

**Comment by amraladdin** [comment]
I agree, we could however just have an outline of the surrounding buildings, cause this will affect the amount of solar irradiation projected on the study area surfaces. Would this be easy to incorporate?

**Comment by JIMENOFONSECA** [comment]
Well it could be the same as the district file, but somehow I thought that outline of buildings can be created with some dummy buildings if necessary..

**Comment by martin-mosteiro** [comment]
So, just to make sure I ran a quick comparison for the following cases: existing Zurich baseline, Zurich baseline with no surrounding buildings (i.e., effectively eliminating 'district.shp') and Zurich baseline with a larger surrounding building sample. I then looked at the heating and cooling demand for the buildings on the outer part of the area (see image).

![screen shot 2018-01-26 at 18 01 44](https://user-images.githubusercontent.com/18548065/35451772-9a9f28ec-02c4-11e8-9a3a-3543cca0556c.png)

The total heating demand for the area only changed by 2% when no context was considered, whereas the cooling demand changed by 1%. The yearly demand per building deviated by a maximum of 10% and the cooling demand by 21%. 

In terms of power, the power demand for the whole sample, the heating power was approximately the same with and without context, whereas the cooling demand was 7% higher. On the building scale, the heating power demand was ±2%, but the cooling power demand was as much as 93% greater.

So in terms of heating/cooling demand the impact of having the surrounding buildings was not very large, but the heating/cooling power was more strongly affected (as expectable).

So given that it can have some considerable impact, wouldn't it make more sense to keep the district when available (i.e., in the Swiss case) and to neglect it or simplify it as suggested by @JIMENOFONSECA when the data is not available?

Any thoughts?

**Comment by JIMENOFONSECA** [comment]
Grande Martin. This is material for a paper or report so let’s keep it in mind for the future. After these findings I will just keep the district file. 

One more question, did you rerun the  daysim solar radiation for this calculation?

**Comment by martin-mosteiro** [comment]
The simulations were done with the Daysim radiation files. I can prepare some visuals with the simulation results if you are interested (or just post the data).

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro @amraladdin So you are right we keep it.
