### ISSUE TITLE
Add pressure losses of valves & turns depending on pipe geometry

### ISSUE THREAD

**Issue by roglen** [architecture-building-systems/CityEnergyAnalyst#979]
Add pressure losses of turns in the piping, depending on pipe geometry and path of pipe

**Comment by roglen** [comment]
How is network data imported?
Assumptions for # of valves, corners, etc. per node?
Where is the pump placed?

**Comment by JIMENOFONSECA** [comment]
Closing, since that level of detail is not needed for our simulations at the moment.
