### ISSUE TITLE
create a script to incorporate oversizing losses

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#983]
Consider an example where a neighborhood is developed in two phases:

First phase is finished in 2005 consisting of 12 buildings and Second phase is finished in 2010 consisting of 12 buildings.

Single phase optimization considers all the 24 buildings for energy system optimization and is installed by 2005. This creates the operation of the energy system configuration below design capacity for a period of 5 years until the second phase is completed.

Multi phase optimization considers 12 buildings in phase-1 and 12 buildings in phase-2 separately and optimizes the energy systems for each phase. Thus phase-1 energy system will be operating at its designed capacity from the time they are installed.

This issue aims to figure out the difference in operating cost for Single Phase optimization and Multi phase optimization during the oversized period.

@JIMENOFONSECA @shanshanhsieh @gabriel-happle : Provide your comments on this topic

**Comment by JIMENOFONSECA** [comment]
So I think we need to consider something which will change the problem a bit.

1. I believe phases should operate in a year to year basis and have buildings connecting to the grid every year.
so for example, if there are 12 buildings planned for phase 1 that lasts 5 years. It means that maybe 2 buildings get connected in year 1, 6, get connected in year 2, and etc.. So the systems is built in year 1 but it is operating form year 1 to 5 at part load capacity.

2. I suggest to create a variable in config that indicates weather the problem will be tackled in phases or not. so with this flag optimisation_main.py know what to do. In this order of ideas we keep the core calculations of conversion units a common feature (which I ope will be upgraded in the future).

3. I do not know if you meant : Single phase optimization considers all the 24 buildings for energy system optimization and is installed by 2010” . Here may I ask for some clarification?.

4. Multiphase-optimization seems like it is a disaggregated problem. one can basically run the 12 buildings in parallel to the other 12 buildings with what we have. Somehow I do not understand how one phase impacts the other, or where the costs decrease..

Maybe we can discuss this in person..

On 25 Jan 2018, 10:25 AM +0800, Bhargava Krishna Sreepathi <notifications@github.com>, wrote:

Consider an example where a neighborhood is developed in two phases:

First phase is finished in 2005 consisting of 12 buildings and Second phase is finished in 2010 consisting of 12 buildings.

Single phase optimization considers all the 24 buildings for energy system optimization and is installed by 2005. This creates the operation of the energy system configuration below design capacity for a period of 5 years until the second phase is completed.

Multi phase optimization considers 12 buildings in phase-1 and 12 buildings in phase-2 separately and optimizes the energy systems for each phase. Thus phase-1 energy system will be operating at its designed capacity from the time they are installed.

This issue aims to figure out the difference in operating cost for Single Phase optimization and Multi phase optimization during the oversized period.

@JIMENOFONSECA<https://github.com/jimenofonseca> @shanshanhsieh<https://github.com/shanshanhsieh> @gabriel-happle<https://github.com/gabriel-happle> : Provide your comments on this topic

**Comment by JIMENOFONSECA** [comment]
2 years here, we will not have it anytime soon. Closing it.
