### ISSUE TITLE
reference case zug not working

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#988]
This is the error i got from running `data_helper`:
![image](https://user-images.githubusercontent.com/16998305/35368595-f3d18f10-01be-11e8-858c-4045fb5b6454.png)
it might have something to do with the updates in `cea-reference-case` two days ago by @JIMENOFONSECA , would you mind taking a look at it?
Thanks!

**Comment by JIMENOFONSECA** [comment]
sure, coudl you update master and run again? However, for the zug case, do not run data helper, the data there is MEASURED!!!

**Comment by shanshanhsieh** [comment]
This is the error I got from running `demand_main` for the zug case downloaded from `cea-reference-case` today.  
@JIMENOFONSECA does it work for you?
![image](https://user-images.githubusercontent.com/16998305/35426172-f05c5026-029b-11e8-8fac-058472c6695b.png)
