### ISSUE TITLE
Dashboard_building does not work for reference-case-zug

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#994]
When running the dashboard for reference-case-zug, under the buildings tab in config file when the names are being provided, it does not accept a space between the letters like 'Bau 02'. This gives an error and further obstructs the script. The same is not the case when running the dashboard for reference-case-open as the buildings are name 'B01' without any spaces. Tried this for dashboards both in demand and the solar potential

**Comment by JIMENOFONSECA** [comment]
@daren-thomas so this is an issue of the config file, is there a workaround?

**Comment by daren-thomas** [comment]
Yes, this is an issue of the config file... `ListParameter` config variables are whitespace delimited. I can add a `CsvParameter` type that is delimited like CSV files. What do you think?

**Comment by JIMENOFONSECA** [comment]
Agree!, the best will be dilimeted by comma ‘,’ as we are kind of used to use this for lists.

On 29 Jan 2018, 21:26 +0800, Daren Thomas <notifications@github.com>, wrote:

Yes, this is an issue of the config file... ListParameter config variables are whitespace delimited. I can add a CsvParameter type that is delimited like CSV files. What do you think?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas let me know if actually we can use the existing ListParameter type but configure it in a way that it uses ',' to separate entries. This will be much more intuitive than the existing way as most of us are used to see lists always being separated by ','

**Comment by daren-thomas** [comment]
@JIMENOFONSECA yes, I can change this - I'll create a pull request for you to test.

**Comment by JIMENOFONSECA** [comment]
Cool! Thanks

Kind regards,

Jimeno

On 5 Feb 2018, 21:07 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/jimenofonseca> yes, I can change this - I'll create a pull request for you to test.
